### ISSUE TITLE
Campos de abstract truncados e duplicados

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#100]
`
No arquivo=serverofi5:/bases/iahx/xml-inbox/regional/pte_regional.xml , id=pte-28957 aparecem três ocorrências do campo "ab" onde cada ocorrência parece ser a continuação da anterior e uma ocorrência do campo "ab_pt" que está truncada. Veja abaixo:

    <field name="ab">Discriminação e generalização estão envolvidas no estabelecimento de controle de estímulos sobre comportamento operante e, do ponto de vista da análise do comportamento, a compreensão de fenômenos como atenção envolve a compreensão de processos envolvidos no estabelecimento de controle de estímulos. Essa interpretação foi a base para estudos experimentais sobre discriminação nos quais se discute diversos aspectos de tal controle. No presente trabalho testou-se a viabilidade de um procedimento para o estabelecimento de discriminações simples sem erros e que permitisse ao experimentador acompanhar o processo de estabelecimento do controle por estímulos envolvidos nessas discriminações. Seis crianças, entre 4 e 5 nos de idade, com desenvolvimento típico participaram do estudo. As crianças trabalhavam em um computador, as respostas solicitadas eram de arrastar e clicar o mouse sobre estímulos dispostos na tela do computador. Os participantes trabalhavam em um computador equipado com um programa que controlava as condições do experimento e registrava as respostas e eventos de interesse. Inicialmente estabeleceu-se, via reforçamento diferencial, uma discriminação simultânea simples entre dois estímulos cuja dimensão relevante era a cor dos estímulos. Em outras 3 fases experimentais foram estabelecidas 3 novas discriminações entre estímulos arbitrários com um procedimento de dica atrasada, no qual se atrasava a cada tentativa correta a apresentação desses SD e S&amp;</field>
    <field name="ab">916; (as cores) sobre os novos estímulos, até que o participante respondesse diferencialmente aos novos estímulos sem a apresentação das cores como fundo. Cada fase de treino foi seguida de um teste em extinção o qual estímulos novos eram apresentados com o SD ou como S&amp;</field>

    <field name="ab">916; recém estabelecidos. Os resultados dos treinos mostraram que houve discriminação sem erro para 4 dos 6 participantes em todos os 3 treinos. Os resultados dos testes mostraram que o desempenho de 4 dos 6 participantes, depois do treino discriminativo parece ter se dado tanto pela seleção do SD como pela exclusão do S&amp;</field>

    <field name="ab_pt">916;, enquanto que um quinto participante teve um desempenho indicativo de controle exclusivo pelo SD. Os resultados são discutidos em termos da efetividade do procedimento para detectar o que vem sendo chamado na literatura de transferência do controle de estímulos (AU)</field>
`

**Comment by botturam** [comment]
É realmente isso que ocorre (abaixo). Trata-se de um erro que ocorre no LILDBI da psicologia da USP. Há algum problema em permanecer assim?

operacao@serverofi5:/bases/lilG4/pte.lil $ mx lilacs "text=as trabalhavam em um computador"
mfn=  2908
  1  "BR85.1"
  2  "28957"
  3  "BR195.3^aDM^b152^cB715p"
  4  "TESE"
  5  "T"
  6  "m"
 16  "Bonito, Maria Amelia Gonçalves"
 18  "Um procedimento para medir o estabelecimento de controle de estímulos em uma discriminação simples, baseado em Touchette (1971)"
 20  "46"
 38  "ilus"
 38  "tab"
 40  "Pt"
 41  "En"
 41  "Pt"
 50  "Pontifícia Universidade Católica de São Paulo. Programa de Estudos Pós-Graduados em Psicologia: Psicologia Experimental Análise do comportamento"
 51  "Mestre"
 62  "s.n"
 64  "2005"
 65  "20050000"
 66  "São Paulo"
 67  "Brasil"
 83  "Discriminação e generalização estão envolvidas no estabelecimento de controle de estímulos sobre comportamento operante e, do ponto de vista da análise do comportamento, a compreensão de fenômenos como atenção envolve a compreensão de processos envolvidos no estabelecimento de controle de estímulos. Essa interpretação foi a base para estudos experimentais sobre discriminação nos quais se discute diversos aspectos de tal controle. No presente trabalho testou-se a viabilidade de um procedimento para o estabelecimento de discriminações simples sem erros e que permitisse ao experimentador acompanhar o processo de estabelecimento do controle por estímulos envolvidos nessas discriminações. Seis crianças, entre 4 e 5 nos de idade, com desenvolvimento típico participaram do estudo. As crianças trabalhavam em um computador, as respostas solicitadas eram de arrastar e clicar o mouse sobre estímulos dispostos na tela do computador. Os participantes trabalhavam em um computador equipado com um programa que controlava as condições do experimento e registrava as respostas e eventos de interesse. Inicialmente estabeleceu-se, via reforçamento diferencial, uma discriminação simultânea simples entre dois estímulos cuja dimensão relevante era a cor dos estímulos. Em outras 3 fases experimentais foram estabelecidas 3 novas discriminações entre estímulos arbitrários com um procedimento de dica atrasada, no qual se atrasava a cada tentativa correta a apresentação desses SD e S&"
 83  "916; (as cores) sobre os novos estímulos, até que o participante respondesse diferencialmente aos novos estímulos sem a apresentação das cores como fundo. Cada fase de treino foi seguida de um teste em extinção o qual estímulos novos eram apresentados com o SD ou como S&"
 83  "916; recém estabelecidos. Os resultados dos treinos mostraram que houve discriminação sem erro para 4 dos 6 participantes em todos os 3 treinos. Os resultados dos testes mostraram que o desempenho de 4 dos 6 participantes, depois do treino discriminativo parece ter se dado tanto pela seleção do SD como pela exclusão do S&"
 83  "916;, enquanto que um quinto participante teve um desempenho indicativo de controle exclusivo pelo SD. Os resultados são discutidos em termos da efetividade do procedimento para detectar o que vem sendo chamado na literatura de transferência do controle de estímulos (AU)^ipt"
 84  "2006-01-26"
 91  "20060124"
 92  "PTA"
 94  "Andery, Maria Amália Pie Adib"
 98  "FONTE"
854  "200500"
855  "0165"
990  "EXPERIMENTAL PSYCHOLOGY"
990  "BEHAVIORAL ASSESSMENT"
990  "ATTENTION"
990  "STIMULUS DISCRIMINATION"
990  "STIMULUS CONTROL"
..

**Comment by heitorbarbieri** [comment]
@viniciusandrade favor verificar.

**Comment by viniciusandrade** [comment]
@botturam 
Só estranhamos o fato da quebra estar ocorrendo após o caracter "&" e por isso pensamos que algum processo nosso estivesse causando a quebra (XML, sed, etc). Caso não seja o caso favor verificar com baixa prioridade se é possivel concatenar todos na mesma ocorrência nestes casos onde o último caracter é o "&"

Obrigado

**Comment by heitorbarbieri** [comment]
Corrigido.
