### ISSUE TITLE
Geração de tabela com descritores MeSH novos, alterados e deletados

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/db-processing#101]
O setor TCS/AFI necessita anualmente da geração de 3 tabelas Excel em meados de setembro, produtos da comparação do MeSH do ano anterior com o do ano atual, onde os elementos (campos) de cada registro são mostrados numa linha:

1) Descritores novos: identifica os DescriptorUI (novos) que não existiam no ano anterior e produz lista com os seguintes elementos: DescriptorUI|TreeNumber (repetitivo e separado com ponto e vírgula numa mesma célula Excel)|TreeNumber (os 3 primeiros caracteres dos TreeNumber separados com jogo da velha)|TreeNumber (somente a primeira ocorrência)|TreeNumber (somente os 3 primeiros caracteres da primeira ocorrência)|DescriptorName (somente o conteúdo do subelemento String)|Annotation|ScopeNote (somente o do conceito preferido)|Term (repetitivo; somente o conteúdo do subelemento String, um a cada duas células subsequentes do Excel, para tradução)

Exemplo:
D000073256|L01.479|L01|L01||Information Technology| | | |[este exemplo de registro não contêm Annotation]| | | |Interconnected system that is used in the automatic acquisition, storage, manipulation, movement, control, display, interchange, transmission, routing or reception of data or information, including computers, ancillary equipment, system software, support services, and related resources. (NAL Agricultural Thesaurus)| | | ||Information Technologies| | | |Technology, Information| | |

2) Descritores alterados: identifica os DescriptorUI que existem tanto no ano anterior quanto no ano atual e produz lista com aqueles DescriptorName que mudaram, com os seguintes elementos: DescriptorUI|TreeNumber (do ano anterior; somente os 3 primeiros caracteres (subcat); ocorrência1; ocorrência 2; ...)|TreeNumber (somente a primeira ocorrência)|DescriptorName do ano anterior| | | |DescriptorName do ano atual, para tradução| | | |subcat ano atual (ocorrência 1+ocorrência 2+ ...)|subcat ano atual (somente os primeiros 3 caracteres da primeira ocorrência do TreeNumber)|DescriptorUI ano atual|ScopeNote (do conceito preferido, do ano anterior)|ScopeNote (do conceito preferido, do ano atual, para tradução)| | | |Term (repetitivos; somente o conteúdo do subelemento String; que sejam diferentes do DescriptorName; um a cada duas células subsequentes do excel, para tradução)

Exemplo:
D056487|C06+C25|C06|Drug-Induced Liver Injury, Chronic|  |  |  |Chemical and Drug Induced Liver Injury, Chronic| | | |C06+C25|C06|D056487|Liver disease lasting six months or more, caused by an adverse drug effect. The adverse effect may result from a direct toxic effect of a drug or metabolite, or an idiosyncratic response to a drug or metabolite.|Liver disease lasting six months or more, caused by an adverse effect of a drug or chemical. The adverse effect may be caused by drugs, drug metabolites, chemicals from the environment, or an idiosyncratic response.| | | |Drug-Induced Liver Injury, Chronic | | | |Liver Injury, Drug-Induced, Chronic| | | |Chemical-Induced Liver Injury, Chronic| | | |Chemically-Induced Liver Injury, Chronic| |  | |Chronic Drug-Induced Liver Injury| | | |Hepatitis, Chronic, Drug-Induced| | | |Liver Injury, Drug-Induced, Chronic| | | |Chemical Induced Liver Injury, Chronic| | | |Chronic Drug Induced Liver Injury| | | |Chemically   Induced Liver Injury, Chronic| | | |Drug Induced Liver Injury, Chronic| | | |Hepatitis, Chronic, Drug-Related| | |

3) Descritores deletados: identifica os DescriptorUI que existiam no MeSH no ano anterior (deletados) e não existem no do ano atual e produz lista com os seguintes elementos: DescriptorUI|TreeNumber (os 3 primeiros caracteres dos TreeNumber separados com jogo da velha)DescriptorName

Exemplo:
D003040|D20#D23|Cobra Venoms

**Comment by falbrito** [comment]
**Referente ao item 1**
Criado script que lê lista de ID's MESH novos, pesquisa no arquivo XML em Inglês 2019 e cria em arquivo no formato ID registros com os campos:

v001 - DescriptorName
v005 - ScopeNote
v020 - TreeNumber
v110 - Annotation
480 - ID MESH

**Scritp utilizado:** 
serverofi4:/bases/dec.000/xml_exportacao/MESH_xmls_dtd/tpl/traz_info.py
* O nome dos arquivos podem variar e estão cravados no script - sujeito a manutenção

**Processos para serem executados:**
Exemplo:
cd /bases/dec.000/xml_exportacao/MESH_xmls_dtd/tpl
python traz_info.py
id2i decs_novos_2019.id create=tmp1
mx tmp1 "gizmo=$TABS/gutf8ans"  "proc='S'" create=novos_2019 -all now
[ -f tmp1.xrf ] && rm tmp1.{mst,xrf}

**Comment by falbrito** [comment]
Desenvolvi um processo no SERVEROFI4 que cria diversos arquivos relacionados a comparação de 2 anos de XML.

**Execução**

Realizar login no SERVEROFI4
Acessar o diretório para executar o script
`cd /bases/dec.000/xml_exportacao/MESH_xmls_dtd/tpl`

Executar o script abaixo colocando o anos que deseja fazer a análise
`./fazTudo.sh 2018 2019`

O insumo desse processamento são arquivos XML do MESH e deverão estar disponíveis no diretório do ano respectivo. Para futuros processamentos deverão ser baixados e gravados no diretório serverofi4:/bases/dec.000/xml_exportacao/MESH_xmls_dtd/<ANO>


**Resultado**

O resultado estará no diretório "wrk"
Acessar diretório wrk
`cd /bases/dec.000/xml_exportacao/MESH_xmls_dtd/wrk`

Os arquivos listados abaixo correspondem a tudo que foi criado e o seu nome e formato definem seu conteúdo

```
decs_FULL_2019.id
decs_FULL_2019.mst
decs_FULL_2019.xrf
decs_novos_2019.id
descritores_alterados_2018_2019.txt
descritores_apagados_2019.txt
descritores_novos_2019.txt
ids_2018.txt
ids_2019.txt
ids_descriptorname_2018.txt
ids_descriptorname_2019.txt
ids_iguais_2018_2019.txt
ids_novos_inseridos_em_2019.txt
ids_que_nao_existem_em_2019.txt

```
Por favor verifiquem se isso já ajuda vocês

**Comment by arthurtreuherz** [comment]
Olá Fábio,

Muito bom! Obrigado e parabéns. Comento cada um dos arquivos


  *   decs_FULL_2019.id mst e xrf
Para que fique ainda mais “parelho” com a versão anterior, solicito incluir no arquivo decs_FULL_2019.id (que na verdade deveria se chamar desc_FULL_2019.id) o campo SeeRelated (os descritores relacionados em inglês) que deve ir para o campo 60^i repetitivo.


  *   decs_novos_2019.id mst e xrf

Da mesma forma que o arquivo acima, favor incluir o campo SeeRelated.


  *   descritores_alterados_2018_2019.txt e descritores_apagados_2019.txt

Todo ano tenho que enviar aos tradutores uma tabela com várias colunas (campos) e executo um procedimento com mx para trazer esses campos. Assim, seria útil se autenticássemos a geração dessa tabela da seguinte maneira:

Do resultado já obtido,

a partir do ID do descritor alterado no ano de 2018 (ano atual),

ler a base 2018 e trazer os seguintes campos, separando-os com pipe na mesma linha (as letras abaixo correspondem à da coluna Excel):

  1.  ID do registro MeSH 2018 (do descritor alterado): v480
  2.  ID do DeCS 2018: com ref(DeCS) trazer o ID do registro DeCS onde ele se encontra
  3.  Código hierárquico 2019: trazer a primeira ocorrência do v20
  4.  Primeira subcategoria 2018: trazer a primeira ocorrência do v20.3
  5.  Subcategorias 2018: trazer todas as ocorrências do v20.3 separadas com +
  6.  Descritor em inglês 2018: v1
  7.  Descritor em espanhol LA 2018: v2
  8.  Descritor em português 2018: v3
  9.  Descritor em espanhol da Espanha 2018: v4
  10. Definição em inglês 2018: v5
  11. Apagados (Del): quando o ID de 2018 deixou de existir em 2019, marcar com sinal de # (neste caso, para descobrir o descritor que o absorveu, é necessário verificar se o descritor de 2018 agora existe como termo alternativo. Caso não exista mais, interromper e iniciar nova linha (para conseguir o ID que o absorveu teremos que aguardar a tabela fornecida pela NLM.
Exemplo para descritores MeSH 2019: https://www.nlm.nih.gov/mesh/2019/download/FateOfDeletedDescriptors2019.pdf
Exemplo para qualificadores MeSH 2019: https://www.nlm.nih.gov/mesh/2019/download/FateOfDeletedQualifiers2019.pdf
Caso exista, é quase garantido que o registro que o absorveu será esse. Assim, é possível seguir abaixo.
a partir do ID do descritor que o absorveu em 2019 (ano seguinte),
                ler a base 2019 e trazer os seguintes campos, separando-os com pipe na mesma linha:

  1.
           *
           *
           *
           *
           *
           *
           *
           *
           *
           *
           *
              *
              *
              *
              *
              *
              *
              *
              *
              *
              *

  1.
              *
              *
              *
              *
              *
              *
              *
              *
              *
              *
              *
              *   Status do descritor do ano 2018 (ano atual) em 2019: verificar com ref(MeSH2018) se o v1 de 2018 continua a existir em 2019. Se continua como entry term, preencher com E aqui, se continua como descritor (MeSH Heading ou MH), preencher com M. Senão, deixar vazio.
              *   ID do registro MeSH 2019 (do descritor que o absorveu): v480
              *   ID do DeCS 2019: quando o ID 2018 e 2019 do MeSH são iguais (alterados) ou quando os descritores MeSH de 2018 e 2019 são iguais e os IDs do MeSH diferentes (deletados), repetir aqui o ID do DeCS de 2018. Senão, são descritores novos e o ID do DeCS e como ainda não foi criado, preencher com “NOVO”.
              *   Código hierárquico 2019: trazer a primeira ocorrência do v20
              *   Primeira subcategoria 2019: trazer a primeira ocorrência do v20
              *   Subcategorias 2019: todas as ocorrências do v20.3 separadas com +
              *   Descritor MeSH 2019 em inglês: v1
              *   Descritor MeSH 2019 em espanhol LA: vazio (o ideal seria: caso o v1 de 2019 já existir em 2018 como descritor, trazer aqui sua tradução existente em v2 e colocar nas observações da coluna V “era descritor DeCS”. Caso o v1 de 2019 já existir em 2018 como v50^i, trazer sua tradução existente em v50^e caso exista e colocar nas observações da coluna V “era termo alternativo”)
              *   Descritor MeSH 2019 em português: vazio (o ideal seria: caso o v1 de 2019 já existir em 2018 como descritor, trazer aqui sua tradução existente em v3 e colocar nas observações da coluna V “era descritor DeCS”. Caso o v1 de 2019 já existir em 2018 como v50^i, trazer sua tradução existente em v50^p caso exista e colocar nas observações da coluna V “era termo alternativo”)
              *   Descritor MeSH 2019 em espanhol da Espanha: vazio (o ideal seria: caso o v1 de 2019 já existir em 2018 como descritor, trazer aqui sua tradução existente em v4 e colocar nas observações da coluna V “era descritor DeCS”. Caso o v1 de 2019 já existir em 2018 como v50^i, trazer sua tradução existente em v50^s caso exista e colocar nas observações da coluna V “era termo alternativo”)
              *   Observações: vazio (o ideal seria fosse preenchido automaticamente quando o descritor MeSH 2019 já existisse como descritor ou como sinônimo em 2018, indicando isso, por exemplo, com “era descritor DeCS” ou “era termo alternativo”, respectivamente)
              *   Definição MeSH 2018 do descritor 2019 (quando já existente): trazer a definição com ref(MeSH 2018) do ID do registro MeSH 2019.
              *   Definição MeSH 2019 em inglês: v5
              *   Definição MeSH 2019 tradução: deixar vazio (o ideal seria que, caso a definição 2018 seja igual à definição 2019, então o tradutor não precisa revisar a tradução e a célula já ficaria preenchida com a tradução existente em 2018.)
              *   UP ing?|UPesp LA?|UPpor?|UPesp España? (o ponto de interrogação à esquerda indica que é um campo repetitivo e a cada nova coluna a partir da coluna Z este sinal deve ser substituído por 1, 2, 3):  trazer os sinônimos em inglês. Aí buscar as traduções no DeCS 2018 e ou MeSH 2018 usando ref(MeSH2018) ou ref(DeCS2018), separando os idiomas em uma sequência de 4 colunas    v50^i|v50^e|v50^p|v50^s|v50^i|v50^e|v50^p|v50^s|…

Geração de outras listagens para os tradutores:


  *   Sinônimos novos em registros já existentes e cujos descritores não mudaram
Comparar MeSH 2018 com MeSH 2019: para os registros cujos ID já existiam, caso seus descritores sejam iguais (isto é, v1 não mudou), trazer os seus sinônimos de 2019 não encontrados em 2018 com o seguinte formato:
v480|v20[3].3|v1|v2|v3|v4|Sinônimo novo em inglês



  *   Definições alteradas

Comparar MeSH 2018 com MeSH 2019: para os registros cujos ID já existiam, caso seus descritores sejam iguais (isto é, v1 não mudou) e caso suas definições sejam diferentes, listar no seguinte formato:

v480|v20[3].3|v1|v2|v3|v4|v5^n 2018|v5^n 2019


  *   Notas de indexação que mudaram

Comparar MeSH 2018 com MeSH 2019: para os registros cujos ID já existiam, caso suas notas de indexação sejam diferentes (v110), listar no seguinte formato:

v480|v20[3].3|v1|v2|v3|v4|v110^n 2018|v110^n 2019

Grato,
Arthur

De: Fabio Brito <notifications@github.com>
Enviada em: Friday, September 21, 2018 10:28 AM
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Treuherz, Arthur (BIR) <treuherz@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Geração de tabela com descritores MeSH novos, alterados e deletados (#101)


Desenvolvi um processo no SERVEROFI4 que cria diversos arquivos relacionados a comparação de 2 anos de XML.

Execução

Realizar login no SERVEROFI4
Acessar o diretório para executar o script
cd /bases/dec.000/xml_exportacao/MESH_xmls_dtd/tpl

Executar o script abaixo colocando o anos que deseja fazer a análise
./fazTudo.sh 2018 2019

O insumo desse processamento são arquivos XML do MESH e deverão estar disponíveis no diretório do ano respectivo. Para futuros processamentos deverão ser baixados e gravados no diretório serverofi4:/bases/dec.000/xml_exportacao/MESH_xmls_dtd/

Resultado

O resultado estará no diretório "wrk"
Acessar diretório wrk
cd /bases/dec.000/xml_exportacao/MESH_xmls_dtd/wrk

Os arquivos listados abaixo correspondem a tudo que foi criado e o seu nome e formato definem seu conteúdo

decs_FULL_2019.id

decs_FULL_2019.mst

decs_FULL_2019.xrf

decs_novos_2019.id

descritores_alterados_2018_2019.txt

descritores_apagados_2019.txt

descritores_novos_2019.txt

ids_2018.txt

ids_2019.txt

ids_descriptorname_2018.txt

ids_descriptorname_2019.txt

ids_iguais_2018_2019.txt

ids_novos_inseridos_em_2019.txt

ids_que_nao_existem_em_2019.txt



Por favor verifiquem se isso já ajuda vocês

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F101%23issuecomment-423530920&data=02%7C01%7Ctreuherz%40paho.org%7C74d5d73282b448dd40e108d61fc61f1d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636731333124283103&sdata=KLuWoQi0XqTl0es2pEclCpz0z1l59uQYMffBJ2NeWXA%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYqG94j3biV6vTKzR47ujc3niJ22bM3aks5udOl9gaJpZM4Wshi5&data=02%7C01%7Ctreuherz%40paho.org%7C74d5d73282b448dd40e108d61fc61f1d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636731333124283103&sdata=XMSWQLAjEcBrF8KsJEZ3XIjaUgb1hs%2Fug4E31zQ2ukE%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by arthurtreuherz** [comment]
Fábio, reenvio agora no doc anexo, para manutenção da formatação das endentações e bullets. Arthur

De: Treuherz, Arthur (BIR)
Enviada em: Wednesday, September 26, 2018 8:57 AM
Para: 'bireme/db-processing' <reply@reply.github.com>; bireme/db-processing <db-processing@noreply.github.com>
Cc: Author <author@noreply.github.com>
Assunto: RES: [bireme/db-processing] Geração de tabela com descritores MeSH novos, alterados e deletados (#101)

Olá Fábio,

Muito bom! Obrigado e parabéns. Comento cada um dos arquivos


  *   decs_FULL_2019.id mst e xrf
Para que fique ainda mais “parelho” com a versão anterior, solicito incluir no arquivo decs_FULL_2019.id (que na verdade deveria se chamar desc_FULL_2019.id) o campo SeeRelated (os descritores relacionados em inglês) que deve ir para o campo 60^i repetitivo.


  *   decs_novos_2019.id mst e xrf

Da mesma forma que o arquivo acima, favor incluir o campo SeeRelated.


  *   descritores_alterados_2018_2019.txt e descritores_apagados_2019.txt

Todo ano tenho que enviar aos tradutores uma tabela com várias colunas (campos) e executo um procedimento com mx para trazer esses campos. Assim, seria útil se autenticássemos a geração dessa tabela da seguinte maneira:

Do resultado já obtido,

a partir do ID do descritor alterado no ano de 2018 (ano atual),

ler a base 2018 e trazer os seguintes campos, separando-os com pipe na mesma linha (as letras abaixo correspondem à da coluna Excel):

  1.  ID do registro MeSH 2018 (do descritor alterado): v480
  2.  ID do DeCS 2018: com ref(DeCS) trazer o ID do registro DeCS onde ele se encontra
  3.  Código hierárquico 2019: trazer a primeira ocorrência do v20
  4.  Primeira subcategoria 2018: trazer a primeira ocorrência do v20.3
  5.  Subcategorias 2018: trazer todas as ocorrências do v20.3 separadas com +
  6.  Descritor em inglês 2018: v1
  7.  Descritor em espanhol LA 2018: v2
  8.  Descritor em português 2018: v3
  9.  Descritor em espanhol da Espanha 2018: v4
  10. Definição em inglês 2018: v5
  11. Apagados (Del): quando o ID de 2018 deixou de existir em 2019, marcar com sinal de # (neste caso, para descobrir o descritor que o absorveu, é necessário verificar se o descritor de 2018 agora existe como termo alternativo. Caso não exista mais, interromper e iniciar nova linha (para conseguir o ID que o absorveu teremos que aguardar a tabela fornecida pela NLM.
Exemplo para descritores MeSH 2019: https://www.nlm.nih.gov/mesh/2019/download/FateOfDeletedDescriptors2019.pdf
Exemplo para qualificadores MeSH 2019: https://www.nlm.nih.gov/mesh/2019/download/FateOfDeletedQualifiers2019.pdf
Caso exista, é quase garantido que o registro que o absorveu será esse. Assim, é possível seguir abaixo.
a partir do ID do descritor que o absorveu em 2019 (ano seguinte),
                ler a base 2019 e trazer os seguintes campos, separando-os com pipe na mesma linha:

  1.
           *
           *
           *
           *
           *
           *
           *
           *
           *
           *
           *
              *
              *
              *
              *
              *
              *
              *
              *
              *
              *

  1.
              *
              *
              *
              *
              *
              *
              *
              *
              *
              *
              *
              *   Status do descritor do ano 2018 (ano atual) em 2019: verificar com ref(MeSH2018) se o v1 de 2018 continua a existir em 2019. Se continua como entry term, preencher com E aqui, se continua como descritor (MeSH Heading ou MH), preencher com M. Senão, deixar vazio.
              *   ID do registro MeSH 2019 (do descritor que o absorveu): v480
              *   ID do DeCS 2019: quando o ID 2018 e 2019 do MeSH são iguais (alterados) ou quando os descritores MeSH de 2018 e 2019 são iguais e os IDs do MeSH diferentes (deletados), repetir aqui o ID do DeCS de 2018. Senão, são descritores novos e o ID do DeCS e como ainda não foi criado, preencher com “NOVO”.
              *   Código hierárquico 2019: trazer a primeira ocorrência do v20
              *   Primeira subcategoria 2019: trazer a primeira ocorrência do v20
              *   Subcategorias 2019: todas as ocorrências do v20.3 separadas com +
              *   Descritor MeSH 2019 em inglês: v1
              *   Descritor MeSH 2019 em espanhol LA: vazio (o ideal seria: caso o v1 de 2019 já existir em 2018 como descritor, trazer aqui sua tradução existente em v2 e colocar nas observações da coluna V “era descritor DeCS”. Caso o v1 de 2019 já existir em 2018 como v50^i, trazer sua tradução existente em v50^e caso exista e colocar nas observações da coluna V “era termo alternativo”)
              *   Descritor MeSH 2019 em português: vazio (o ideal seria: caso o v1 de 2019 já existir em 2018 como descritor, trazer aqui sua tradução existente em v3 e colocar nas observações da coluna V “era descritor DeCS”. Caso o v1 de 2019 já existir em 2018 como v50^i, trazer sua tradução existente em v50^p caso exista e colocar nas observações da coluna V “era termo alternativo”)
              *   Descritor MeSH 2019 em espanhol da Espanha: vazio (o ideal seria: caso o v1 de 2019 já existir em 2018 como descritor, trazer aqui sua tradução existente em v4 e colocar nas observações da coluna V “era descritor DeCS”. Caso o v1 de 2019 já existir em 2018 como v50^i, trazer sua tradução existente em v50^s caso exista e colocar nas observações da coluna V “era termo alternativo”)
              *   Observações: vazio (o ideal seria fosse preenchido automaticamente quando o descritor MeSH 2019 já existisse como descritor ou como sinônimo em 2018, indicando isso, por exemplo, com “era descritor DeCS” ou “era termo alternativo”, respectivamente)
              *   Definição MeSH 2018 do descritor 2019 (quando já existente): trazer a definição com ref(MeSH 2018) do ID do registro MeSH 2019.
              *   Definição MeSH 2019 em inglês: v5
              *   Definição MeSH 2019 tradução: deixar vazio (o ideal seria que, caso a definição 2018 seja igual à definição 2019, então o tradutor não precisa revisar a tradução e a célula já ficaria preenchida com a tradução existente em 2018.)
              *   UP ing?|UPesp LA?|UPpor?|UPesp España? (o ponto de interrogação à esquerda indica que é um campo repetitivo e a cada nova coluna a partir da coluna Z este sinal deve ser substituído por 1, 2, 3):  trazer os sinônimos em inglês. Aí buscar as traduções no DeCS 2018 e ou MeSH 2018 usando ref(MeSH2018) ou ref(DeCS2018), separando os idiomas em uma sequência de 4 colunas    v50^i|v50^e|v50^p|v50^s|v50^i|v50^e|v50^p|v50^s|…

Geração de outras listagens para os tradutores:


  *   Sinônimos novos em registros já existentes e cujos descritores não mudaram
Comparar MeSH 2018 com MeSH 2019: para os registros cujos ID já existiam, caso seus descritores sejam iguais (isto é, v1 não mudou), trazer os seus sinônimos de 2019 não encontrados em 2018 com o seguinte formato:
v480|v20[3].3|v1|v2|v3|v4|Sinônimo novo em inglês



  *   Definições alteradas

Comparar MeSH 2018 com MeSH 2019: para os registros cujos ID já existiam, caso seus descritores sejam iguais (isto é, v1 não mudou) e caso suas definições sejam diferentes, listar no seguinte formato:

v480|v20[3].3|v1|v2|v3|v4|v5^n 2018|v5^n 2019


  *   Notas de indexação que mudaram

Comparar MeSH 2018 com MeSH 2019: para os registros cujos ID já existiam, caso suas notas de indexação sejam diferentes (v110), listar no seguinte formato:

v480|v20[3].3|v1|v2|v3|v4|v110^n 2018|v110^n 2019

Grato,
Arthur

De: Fabio Brito <notifications@github.com<mailto:notifications@github.com>>
Enviada em: Friday, September 21, 2018 10:28 AM
Para: bireme/db-processing <db-processing@noreply.github.com<mailto:db-processing@noreply.github.com>>
Cc: Treuherz, Arthur (BIR) <treuherz@paho.org<mailto:treuherz@paho.org>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Assunto: Re: [bireme/db-processing] Geração de tabela com descritores MeSH novos, alterados e deletados (#101)


Desenvolvi um processo no SERVEROFI4 que cria diversos arquivos relacionados a comparação de 2 anos de XML.

Execução

Realizar login no SERVEROFI4
Acessar o diretório para executar o script
cd /bases/dec.000/xml_exportacao/MESH_xmls_dtd/tpl

Executar o script abaixo colocando o anos que deseja fazer a análise
./fazTudo.sh 2018 2019

O insumo desse processamento são arquivos XML do MESH e deverão estar disponíveis no diretório do ano respectivo. Para futuros processamentos deverão ser baixados e gravados no diretório serverofi4:/bases/dec.000/xml_exportacao/MESH_xmls_dtd/

Resultado

O resultado estará no diretório "wrk"
Acessar diretório wrk
cd /bases/dec.000/xml_exportacao/MESH_xmls_dtd/wrk

Os arquivos listados abaixo correspondem a tudo que foi criado e o seu nome e formato definem seu conteúdo

decs_FULL_2019.id

decs_FULL_2019.mst

decs_FULL_2019.xrf

decs_novos_2019.id

descritores_alterados_2018_2019.txt

descritores_apagados_2019.txt

descritores_novos_2019.txt

ids_2018.txt

ids_2019.txt

ids_descriptorname_2018.txt

ids_descriptorname_2019.txt

ids_iguais_2018_2019.txt

ids_novos_inseridos_em_2019.txt

ids_que_nao_existem_em_2019.txt



Por favor verifiquem se isso já ajuda vocês

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F101%23issuecomment-423530920&data=02%7C01%7Ctreuherz%40paho.org%7C74d5d73282b448dd40e108d61fc61f1d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636731333124283103&sdata=KLuWoQi0XqTl0es2pEclCpz0z1l59uQYMffBJ2NeWXA%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYqG94j3biV6vTKzR47ujc3niJ22bM3aks5udOl9gaJpZM4Wshi5&data=02%7C01%7Ctreuherz%40paho.org%7C74d5d73282b448dd40e108d61fc61f1d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636731333124283103&sdata=XMSWQLAjEcBrF8KsJEZ3XIjaUgb1hs%2Fug4E31zQ2ukE%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by renatomurasaki** [comment]
Fechado, considerando que já estamos na edição 2021
