### ISSUE TITLE
Processamento para troca do código do centro cooperante

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/db-processing#102]
@falbrito 
Conforme descrito no issue https://github.com/bireme/fi-admin/issues/553 pela Sueli é necessário trocar o código do centro cooperante quando os mesmos passam do status LILACS Express para publicados para levar em consideração o centro que realizou a indexação do registro

Alterei na API do FI-ADMIN para realizar esta troca e precisamos que seja realizado um processamento retroativo (6 meses) para que esta alteração seja refletida no IAHX e IAH.

Obrigado

**Comment by falbrito** [comment]
Coleta retroativa realizada a partir da data 01/03/2018.

**Comment by viniciusandrade** [comment]
OK, obrigado.
