### ISSUE TITLE
Campo Limite (ct)

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/db-processing#103]
Dúvida descrita pela Rose em https://github.com/bireme/iahx-opac/issues/51

"O campo Limite reflete "somente" os limites considerados no filtro (cluster), sugiro recuperar todos os demais tipos de limites disponíveis em ct , como alguns tipos de animais utilizados para pesquisa, apontando para este metadado e não para o filtro/cluster."

Favor realizar o levantamento e informar neste ticket a composição atual do índice CT e se é possível adicionar estes outros limites citados pela Rose.

**Comment by botturam** [comment]
@viniciusandrade esse assunto ainda está pensente? podemos encerrar o chamado? Vi que vc já encerrou o bireme/iahx-opac#51


Nas **IAHx**, o campo "ct" representa o campo 76 - Descritor pré-codificado - e pode assumir os seguintes valores (+ combinações entre eles):

ADOLESCENT
ADULT
AGED
AGED, 80 AND OVER
ANIMALS
CATS
CATTLE
CHICK EMBRYO
CHILD
CHILD, PRESCHOOL
CRICETINAE
DOGS
FEMALE
GUINEA PIGS
HISTORY, 15TH CENTURY
HISTORY, 16TH CENTURY
HISTORY, 17TH CENTURY
HISTORY, 18TH CENTURY
HISTORY, 19TH CENTURY
HISTORY, 20TH CENTURY
HISTORY, 21ST CENTURY
HISTORY, ANCIENT
HISTORY, MEDIEVAL
HUMANS
INFANT
INFANT, NEWBORN
MALE
MICE
MIDDLE AGED
PREGNANCY
RABBITS
RATS
YOUNG ADULT

**Comment by viniciusandrade** [comment]
@botturam sim pode fechar pois a dúvida dela era se os valores eram provenientes de um campo ou de estratégias de busca, no caso como são valores de um campo não existe como ajustar esta lista.
