### ISSUE TITLE
Acrescentar parâmetro -decsPath em chamada à função MarkAbstract3.sh

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#107]
Por favor, acrescentar o parâmetro "-deCSPath=/usr/local/bireme/tabs/decs" em toda chamada ao shell MarkAbstract3.sh  em  serverofi5:/bases/iahx/exec/0-process-inbox.sh e em todo outro em que MarkAbstract3.sh aparecer.

Exemplo:

   ./MarkAbstract3.sh ./prefixes.txt /bases/iahx/xml-inbox/regional .+xml zz -deCSPath=/usr/local/bireme/tabs/decs

**Comment by botturam** [comment]
Acrescentado em:

tomcat@serverofi5:/bases/iahx $ find ./ -name "*.sh"|xargs grep --color MarkAbstract3.sh
./proc/mdl5/main/0-process.sh:  $ACAO/MarkAbstract3.sh $ACAO/prefixes.txt $FILE_DIR $FILE_NAM $PWD/xml.index -deCSPath=/usr/local/bireme/tabs/decs
./exec/0-process-inbox.sh:                              $ACAO/MarkAbstract3.sh $ACAO/prefixes.txt $FILE_DIR $FILE_NAM $PWD/xml.index -deCSPath=/usr/local/bireme/tabs/decs
./exec/0-process-inbox.sh:                      $ACAO/MarkAbstract3.sh $ACAO/prefixes.txt $PATH_INPUT/$I_BOX mdl${MDL_ANOCORRENTE2DIGITOSIAHx}_regional.xml $PWD/xml.index -deCSPath=/usr/local/bireme/tabs/decs
./exec/0-process-inbox.sh:                              $ACAO/MarkAbstract3.sh $ACAO/prefixes.txt $FILE_DIR $FILE_NAM $PWD/xml.index -deCSPath=/usr/local/bireme/tabs/decs


OBS: Aguardar proc. na próxima 4f, dia 24/out

**Comment by botturam** [comment]
Heitor,

acabei de fazer um processamento de Portal-Regional -- em homologação -- com a nova feature lil_regional.xml, apenas com a base de dados LILACS.

para testar:

http://pesquisa.homolog.bvsalud.org/portal/

**Comment by botturam** [comment]
disponível em produção
