### ISSUE TITLE
Processar nas coletas OAI-PMH de Recursos Educacionais o campo dc:subject

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#109]

**Comment by renatomurasaki** [comment]
Verificado que o elemento dc:subject com qualifier está disponível no harvesting UNA-SUS. Solicitado a Fiocruz (nodo CVSP Brasil) para incluir no OAI-PMH do Repositorio Drupal o element dc:subject. Aguardando retorno

**Comment by renatomurasaki** [comment]
@botturam @falbrito Favor incluir o dc:subject para construir o cluster Asunto no iAHx da BVS Regional e iAHx dedicado CVSP, considerando que a coleta de Brasil vem de DSpace e Drupal e as demais, com exceção de Chile, vem do FI-Admin. Chile, por agora, fica sem informação de dc:subject (verificar se nas 3 coletas do Chile de fato o elemento dc:subject) está ausente.

**Comment by botturam** [comment]
Sim. O campo Descritor agora é coletado e codificado para funcionar no IAHx, como a LILACS, por exemplo.
