### ISSUE TITLE
MTCI - reprocessamento de estratégia geral

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#113]
Solicito reprocessar a estratégia geral do recorte de MTCI, considerando também a inclusão dos filtros, assim que possível e atualização periódica. 
O arquivo será enviado por e-mail para processamento.

Obrigada

**Comment by pintoros** [comment]
Segue o arquivo txt 
[Estrategia_geral_MTCI_131118.txt](https://github.com/bireme/db-processing/files/2577362/Estrategia_geral_MTCI_131118.txt)

**Comment by botturam** [comment]
A extração dos IDs referentes à estratégia geral foi concluído. Foram recuperados 1.090.629 docs. Agora precisamos extrair os IDs dos Temas. 

Estamos aguardando as estratégias dos temas.

**Comment by pintoros** [comment]
Okay quanto ao resultado. 
#114 aberto para reprocessamento dos temas
