### ISSUE TITLE
GIM - iAHx - manter no índice somente LILACS, EMRO, AFRO, SEARO e WPRO

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#115]
@botturam foi decidido na última reunião do GLG em Genebra, manter no índice de busca somente as bases (Index Medicus) de cada Região da OMS, ou seja, LILACS, EMRO, AFRO, SEARO e WPRO. As demais podem sair do índice.

**Comment by botturam** [comment]
E a base da PAHOIRIS?

**Comment by renatomurasaki** [comment]
Tampoco estará integrada com os demais índices. Somente estarão os Index Medici das Regiões.


Renato Murasaki

Gerente MTI - Metodologias e Tecnologias de Informação

Gerente a.i. AFI - Administração de Fontes de Informação

BIREME/OPAS/OMS

Departamento de Evidência e Inteligência para a Ação em Saúde


Fone: 11 5576-9874

Cel:  11 98302-0210

VoIP: 44874

murasaki@paho.org

________________________________
De: botturam <notifications@github.com>
Enviado: segunda-feira, 3 de dezembro de 2018 11:33:12
Para: bireme/db-processing
Cc: Renato Murasaki; Author
Assunto: Re: [bireme/db-processing] GIM - iAHx - manter no índice somente LILACS, EMRO, AFRO, SEARO e WPRO (#115)


E a base da PAHOIRIS?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F115%23issuecomment-443711087&data=02%7C01%7Cmurasaki%40paho.org%7Ce059cbc2d43942dbbdf108d65923e0a6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636794407972238265&sdata=yXrjrS6oI%2BBmWuqf3lcLZMY02QL9GopUvuykAyKjXt0%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABK16l3m5hhz01x2SIQfPLeH36bLqsjHks5u1SgYgaJpZM4Y81JB&data=02%7C01%7Cmurasaki%40paho.org%7Ce059cbc2d43942dbbdf108d65923e0a6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636794407972248281&sdata=sOjT99xf0M2aJ915BxMD%2BhIn15EyE9oNBClP%2F2Vbplg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
Processamento iniciado. Previsão de término: 10/12/2018

**Comment by botturam** [comment]
Disponível em produção.
