### ISSUE TITLE
BVS - Enfermeria Uruguay - desenvolver processo de coleta e publicação

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#118]
**MOTIVAÇÃO:**
Assunto: BVS Enfermeria UY - prontos para testar OAI - SUGERENCIA
 
Mori
ahora que pasó el CRICS retomamos las tareas para completar la migración 
que falta de BVS Enf
Esta todo pronto, solo falta completar el OAI para el IAHX

La página oficial es https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.bvsenf.org.uy%2Fwp%2F&amp;data=02%7C01%7Cbritofa%40paho.org%7C9445cc17d66748ea0ab708d65f6c1df9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636801315305607091&amp;sdata=IU893jSgEKnUmoNfo%2F1LWwElB4bJXpi7zk%2B0SHVupsM%3D&amp;reserved=0
Está puesto para testar una base llamada   lilacsenf  con 6.016 registros
OAI  lilacsenf
https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.bvsenf.org.uy%2Fisis-oai-provider%2F%3Fverb%3DListSets&amp;data=02%7C01%7Cbritofa%40paho.org%7C9445cc17d66748ea0ab708d65f6c1df9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636801315305607091&amp;sdata=mSnGO0uEgSx8%2Fl9pH7V%2Flos3CHTO3ZB8YYepiM4alpI%3D&amp;reserved=0
https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.bvsenf.org.uy%2Fisis-oai-provider%2F%3Fverb%3DListRecords%26metadataPrefix%3Disis%26set%3Dlilacsenf&amp;data=02%7C01%7Cbritofa%40paho.org%7C9445cc17d66748ea0ab708d65f6c1df9%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636801315305607091&amp;sdata=pq3%2BQSSP49jhY4aGySgvGki6HmAC9GkvL3s5Qqj8MKg%3D&amp;reserved=0

Los registros proceden de dos instituciones
UCU  -  Universidad Católica
UDELAR-FACENF   - Facultad de Enfermería de la Universidad de la República

Sería necesario entonces poner en homolog una página que tenga 
customizado el logo bvs (con link de retorno a la página)
y la columna de la derecha facetada para las dos instituciones
Cuando lo tengan pronto Gustavo ajustará el plugin para hacer el vínculo

Agradezco respuesta, son días complicados para todos debido al fin de año
Saludos
Ernesto

-- 
   .^.                                .^.
   ( )                                ( )
   ===                                ===
  =[=]================================[=]=
   | |  Ernesto Spinak                | |
   =[=]================================[=]=
   ===                                ===
   ( )                                ( )
    V                                  V

**Comment by falbrito** [comment]
Processos que vão da coleta a criação do arquivo XML realizados.

```
operacao@serverofi5:/bases/lilG4/shs.lil $ head flb.sh
echo "BVS ENFERMERIA URUGUAI"
./coleta_oai.sh bue
./pos_coleta_oai.sh bue
./pre_saneamento_fi.sh bue
./iah_like_lilacs_fi.sh bue
./iahx_xml_geral_fi.sh bue

```
XML criado:
`serverofi5:/bases/iahx/xml-inbox/regional/bue_regional.xml`

**Comment by botturam** [comment]
Tarefas do OFI finalizadas. Coleta, processamento e geração de XML concluídas.

Falta dar seguência nas tarefas indicadas no Ocomom 6084
