### ISSUE TITLE
Desenvolver script pos_saneamento_fi.sh

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#12]
Relacionado ao #7

Responsável pelas rotinas de normalização comuns que ocorrem depois das rotinas específicas de uma fonte de informação.

**Comment by botturam** [comment]
não será desenvolvido até que tenhamos mais clareza de sua necessidade. Por enquanto, as rotinas de pre_saneamento_DI.sh e saneamento específico são suficientes.

**Comment by renatomurasaki** [comment]
No momento foi identificado que não há necessidade da etapa genérica de pós saneamento das fontes de informação. Encerrando issue.
