### ISSUE TITLE
Processamento recorte iAHx BVS APS

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#125]
Solicito reprocessar recorte temático geral para BVS APS http://pesquisa.bvs.br/aps
Arquivo anexo
[bvs_aps.txt](https://github.com/bireme/db-processing/files/2823445/bvs_aps.txt)

**Comment by botturam** [comment]
Rose, é a mesma estratégia para LILACS e MEDLINE?

**Comment by pintoros** [comment]
Sim Marcelo, a mesma estratégia será aplicada para LILACS e MEDLINE. Segue anexo o arquivo corrigido:
[bvs_aps_corrigido.txt](https://github.com/bireme/db-processing/files/2870126/bvs_aps_corrigido.txt)

**Comment by botturam** [comment]
Novo processamento com a nova estratégia-geral da APS já está disponível em produção.

**Comment by pintoros** [comment]
Obrigada Marcelo!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:0e7f8bb9-0f40-4f51-b290-7ec874d54294]

________________________________
De: botturam <notifications@github.com>
Enviado: quinta-feira, 7 de março de 2019 12:06
Para: bireme/db-processing
Cc: Pinto, Rosemeire (BIR); Author
Assunto: Re: [bireme/db-processing] Processamento recorte iAHx BVS APS (#125)


Novo processamento com a nova estratégia-geral da APS já está disponível em produção.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F125%23issuecomment-470561776&data=02%7C01%7Cpintoros%40paho.org%7C3d3df56672dd4f716afc08d6a30e79f6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C636875679898197429&sdata=bjvS657bRPNA2URBmhyYBFPtGZ8uHlaNYH%2FzUmilVeU%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAb9LcPqKm--nDkOVpSyH_8TBojyBkhk3ks5vUSr0gaJpZM4afIcq&data=02%7C01%7Cpintoros%40paho.org%7C3d3df56672dd4f716afc08d6a30e79f6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C636875679898197429&sdata=80iIDBO333UmE%2FmZuPJK60vcZ1e%2BCiE58E834p6%2Biqg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
disponível em produção
