### ISSUE TITLE
Gerar arquivos CSV infometria para a base CTDprod da SES-SP

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#129]
@botturam por favor, gerar os arquivos CSV dos registros da base CTDprod da SES-SP, pois após análise da equipe da Secretaria, percebemos que muitos estudos, principalmente tesis e documentos não convencionais, que também estão em LILACS, não foram recuperados nas estratégias de busca.

**Comment by botturam** [comment]
O que é CTD? identifiquei no campo 4 da SES-SP, mas não sei o que é a sigla. Nós ainda não tabulamos este instituto, certo?

**Comment by botturam** [comment]
vou pegar os docs da FI SES-SP cujo campo 4 = CTDPROD.

**Comment by botturam** [comment]
Coloquei em:

ftp.bireme.br  -  user: ofi / ofi@2016

-rwxr-xr-x    1 1066     1006      3060683 Feb 08 16:23 CTDPROD_tabulacoes.zip

**Comment by renatomurasaki** [comment]
Base da produção científica da Secretaria.

Sent from my iPhone

On 8 Feb 2019, at 15:45, botturam <notifications@github.com<mailto:notifications@github.com>> wrote:


O que é CTD? identifiquei no campo 4 da SES-SP, mas não sei o que é a sigla. Nós ainda não tabulamos este instituto, certo?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F129%23issuecomment-461886450&data=02%7C01%7Cmurasaki%40paho.org%7Cae9233213138430d716208d68ded4136%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636852447476456803&sdata=PbXukJXVpKsts5O4XxdIN2tgnFGNip%2FzSZ6Cwl2w7G8%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABK16hU39yyxU9WxzBWONuYCk5SUrULUks5vLbfFgaJpZM4avcet&data=02%7C01%7Cmurasaki%40paho.org%7Cae9233213138430d716208d68ded4136%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636852447476466811&sdata=XzofqqegYdKoD31j3alW8ABTX93QnWjvikcJl9IL9bQ%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
OK. Está gerado, conforme assentamento acima. São 5.311 docs (lilacs_todos.txt)

**Comment by renatomurasaki** [comment]
@botturam obrigado. Arquivo gerado corretamente, entretando, avaliando o retorno desta exportação, precisamos exportar todos os registros que pertencem ao cluster "Coleção SES" identificados por "Produção Científica", ao redor de 15.900 registros.

**Comment by botturam** [comment]
Coloquei em:

ftp.bireme.br - user: ofi / ofi@2016

-rwxr-xr-x    1 1066     1006      8871994 Feb 11 16:39 SESSP_PROD_tabulacoes.zip (15.951 docs)
