### ISSUE TITLE
Tornar a atualização dos dados da WPRIM no GIM trimestral

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#132]
Atualização na última semana de Março, Junho e Setembro e na segunda semana de Dezembro. Está pendente se manteremos o mecanismo de FTP ou se utilizaremos web service. Isso inclui se o processo continuará incremental e se sim, quando faríamos um full para retirada de registros inativos.

**Comment by botturam** [comment]
Aguardando atualização em nosso servidor de FTP, conforme instruções recebidas por e-mail:

Here is our draft plan for uploading data to GIM:
1) At the end of February, we'll upload all records to FTP by zip. 


2) Before the middle of March, we'll provide a document to introduce how to use our API. GIM can evaluate and make the final decision, how to get WPRIM data.

**Comment by falbrito** [comment]
**Motivação para o processamento**


```
De: 王蕾 <wang.lei@imicams.ac.cn>

Enviado: domingo, 24 de março de 2019 00:39
Para: Murasaki, Renato (BIR)
Cc: prosperoso, alma mila; Bottura, Marcelo (BIR); fang.an@imicams.ac.cn; somerbang, helen
Assunto: Re: Re: GIM - WPRO updates
 
Dear Renato,

Apologize to send your email late. We've changed the export program in WPRIM database management. So our full data, the file name is 'WPRIM-2019-3-20.zip', upload to FTP is late.
Now, we've uploaded all new WPRIM data to the FTP,ftp://ftp2.bireme.br/. There is one text file with the total number of the records and 70 XML files in the zip file.

If there is any problem with the data, please contact me.


Best regards,

Wang Lei




-----原始邮件-----
发件人:"Murasaki, Renato (BIR)" <murasaki@paho.org>
发送时间:2019-02-23 04:29:20 (星期六)
收件人: "王蕾" <wang.lei@imicams.ac.cn>
抄送: "prosperoso, alma mila" <prosperosoa@who.int>, "Bottura, Marcelo (BIR)" <botturam@paho.org>, "fang.an@imicams.ac.cn" <fang.an@imicams.ac.cn>, "somerbang, helen" <somerbangh@who.int>
主题: Re: GIM - WPRO updates

Dear Wang Lei,
Thank you for your reply. We believe that the best choice to remove all deleted records is replacing the current data with the full WPRIM data which you will provide to us in the end of this month.
After that, to remove deleted records, we should have a list of ID to do it or try to process a full replacement periodically.
All the best,
Renato

Sent from my iPhone

```

**Comment by falbrito** [comment]
Arquivo baixado a partir do servidor FTP

# Dados para acesso
url: ftp2.bireme.br
user: ghl.wpro
password: 

Destino do insumo
operacao@serverofi5:/bases/oai.pmh/xml.rec/XMLs_WPRIM_nao_apagar/tmp_ftp/WPRIM-2019-3-20
