### ISSUE TITLE
Tornar a atualização dos dados da AIM no GIM mensal

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#133]
Ainda será definido o mecanismo de intercambio. Enquanto AFRO não ajustar o OAI-PMH, faremos a adaptação para o schema do GIM na BIREME.

**Comment by renatomurasaki** [comment]
O envio será via FTP da BIREME.

**Comment by botturam** [comment]
Aguardarei a notificação de atualização do local indicado em nosso FTP:

Atualmente o conteúdo é:

ftp> ls /home/ftp/gim/afro/AFRO.zip
200 PORT command successful. Consider using PASV.
150 Here comes the directory listing.
-rwxr-xr-x    1 1079     1079      2953495 Nov 08  2017 AFRO.zip

**Comment by botturam** [comment]
Processamento disponível em produção. Rotinas em serverofi5:/bases/oai.pmh/tpl.oai/AIM_afro_all.sh
