### ISSUE TITLE
Registros LILACS publicados no Fi-Admin não aparecem na interface IAX Regional

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/db-processing#134]
Registros LILACS da revista "Cuad. Hosp. Clín" publicados no Fi-Admin não aparecem na interface IAX Regional. No Fi-Admin já tem registros até 2018, mas fazendo uma busca pelo IAX, o último registro é de 2009.

![image](https://user-images.githubusercontent.com/47643830/52813616-49e26900-3081-11e9-8fe2-16728eecd59e.png)

![image](https://user-images.githubusercontent.com/47643830/52813637-58308500-3081-11e9-91ab-6964d21ddb92.png)

**Comment by anakatiacamilo** [comment]
Bom dia Angelica,
Esses registros são de migração entram ontem no FI-Admin então na semana que vem estarão disponíveis no iaHx, mandei dois e-mail para LILACS com a lista de registros e ID que foram migrados.
Atenciosamente
Katinha
