### ISSUE TITLE
Tornar a atualização dos dados da IMEMR no GIM mensal 

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#135]
Conforme orientação do Hatem, de 16/02/2019, por e-mail (abaixo), tornar atualização de EMRO / IMEMR regular mensal.

Dear Renato
Thanks for your message. IMEMR update would be monthly INSHA ALLAH.
Best regards
Hatem

**Comment by botturam** [comment]
Concluído shell-script em serverofi5:/bases/lilG4/shs.lil/_emr.sh

OBS: talvez seja necessário alterar o nome do arquivo de origem no endereço de download indicado pelo Hatem. Aguardar novo processamento para conferir.

arquivo coletas.tab:

emr     IMEMR   /bases/lilG4/emr.lil    wget    ^h=https://www.dropbox.com/s/ilhe90e1dfl0evp/^d=^l=^p=^s=^b=emro.iso^c=

**Comment by botturam** [comment]
falta cadastrar as tarefas de emr.sh no Celery.

**Comment by renatomurasaki** [comment]
IMEMR alterou o sistema de gestão da base de dados e EMRO está desenvolvendo API para novo tipo de coleta de dados.
