### ISSUE TITLE
Restabelecer processamento de coleta e processamento ARCA

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#136]
O cliente (FIOCRUZ), solicita o restabelecimento do processamento que encontrava-se em status de "congelado".

Motivação:
```
De: Augusto Vinhaes <augusto.vinhaes@icict.fiocruz.br>
Enviado: segunda-feira, 18 de fevereiro de 2019 13:43
Para: Brito, Fabio Luis de (BIR)
Cc: Angelo José Moreira Silva
Assunto: Re: ARCA - coleta de metadados
 
Boa tarde Fabio,

acabei de ter um retorno da equipe do Dspace de que o problema já foi 
resolvido. Pode, por favor, efetuar a coleta e nos informar se funcionou 
? Os formatos dim e mods já devem estar disponíveis.

Atenciosamente,

Augusto Vinhaes
Seção de Informação
CTIC - ICICT - FIOCRUZ
```

Ações a serem tomadas:
- Esse processamento era realizado antes da remodularização de scripts, dessa forma deverá ser avaliado possível refaturamento de códigos para poder adequar ao processo atual.

**Comment by falbrito** [comment]
Refatoramento realizado.

Chamada para execução em:
serverofi5:/bases/oai.pmh/tpl.oai/ARCA_process.sh

Processamento também cadastrado no Celery para execução às 2as feiras, 15hs.

STATUS: Aguardando processamento de indexação do Solr para feedback ao cliente.

**Comment by botturam** [comment]
Ficou agendado às terças-feiras, 20:00.

**Comment by falbrito** [comment]
Conteúdo disponibilizado no portal fiocruz e status informado ao cliente.
