### ISSUE TITLE
Desenvolver script iah_like_lilacs_fi.sh

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#14]
Relacionado ao #7

Responsável pelas rotinas de geração de índice ISIS.

Incluir parâmetro de entrada para especificar quando este processamento é do tipo soft, ou seja, executa apenas algumas rotinas do processamento like_lilacs.

**Comment by botturam** [comment]
depois da remodelação da arquitetura dos shells, o iah_like_lilacs foi renomeado para iah_lil_FI.sh
