### ISSUE TITLE
Revisar o processamento do cluster Tipo de Estudo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#140]
Parece que os números de documentos classificados em revisões sistemáticas está muito baixo. De acordo com o cluster, são aproximadamente 18 mil documentos. Ao executar a query https://bvsalud.org/queries/search_strategy/revisao-sistematica/?l=pt_BR&se=revisao%20sistematica na BVS Regional, o resultado é de quase 2 milhões de documentos.

**Comment by pintoros** [comment]
Solicito reprocessar com a estratégia baseada no filtro PUBMED, atualizada em 11/03/2019, disponível no REFNET:
https://bvsalud.org/queries/search_strategy/revisao-sistematica/?l=pt_BR&se=sistematica

**Comment by botturam** [comment]
processamento completo disponível em produção.

no dia de hoje, são 405,297 docs

**Comment by renatomurasaki** [comment]
@botturam favor gerar um arquivo CSV contendo ID, título e abstract dos 405.297 documentos recuperados como Revisões Sistemáticas, para envio à equipe de Epistemonikos. Eles farão um processamento em machine learning para identificar aquilo que é de fato revisão sistemática. Exportar um arquivo por idioma.

**Comment by botturam** [comment]
Seguem as instruções para download dos 3 arquivos com as tabulações dos campos ID, DB, TI e AB, uma para cada idioma (MEDLINE e LILACS):

ftp.bireme.br <ftp://ftp.bireme.br/>   - user: ofi  /  ofi@2016  

1) tabulacion_ID_TI_AB_eng.txt
2) tabulacion_ID_TI_AB_esp.txt
3) tabulacion_ID_TI_AB_por.txt

**Comment by botturam** [comment]
atividades concluídas.
