### ISSUE TITLE
Base RHS no iAHx Regional

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#143]
Favor criar no cluster Base de Dados a opção "Recursos Humanos em Saúde", "Recursos Humanos en Salud", "Health ManPower" e "Main-d'oeuvre en santé", para recuperar os registros do FI-Admin identificados como "RHS - Recursos Humanos para a Saúde"

**Comment by botturam** [comment]
É necessária permissão de escrita nos arquivos texts.ini (4 idiomas). Verificarei com o Mori.

RHS="RHS Repository"
RHS="Repositorio RHS"
RHS="Repositório RHS"
RHS="Repositorio RHS"

**Comment by botturam** [comment]
francês: "Référentiel RHS"

**Comment by botturam** [comment]
chamado Ocomon 6258 aberto para ITI

**Comment by botturam** [comment]
disponível em produção.
