### ISSUE TITLE
Solicito criação de filtro para o índice de Homeopatia

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#145]
Bom dia,

Por favor, solicito a criação do filtro do índice de Homeopatia do FI-ADMIN + os registros do LILDBI-web (legado ainda não migrado) a sigla é:

               HomeoIndex

Grata

**Comment by falbrito** [comment]
Filtro realizado e insumo concatenado ao processamento lildbiweb.
Ações realizadas.
1) Incorporado a chamada no shell script abaixo 
serverofi5:/bases/fiadmin/consolida/tpl/rodaFILTROS.sh
trecho
```
# -----------------------------------------------------------------------------
FILTRO="HomeoIndex" # HomeoIndex - Homeopatia - 20190409
./filtraDBs.sh $FILTRO
[ $? -ne 0 ] && echo "- $FILTRO" >> erro_filtro.txt

```
O insumo gerado desse filtro está em:
```
operacao@serverofi5:/bases/fiadmin/databases $ ll homeoindex/
total 220
-rw-rw-r-- 1 operacao operacao 218624 Apr  9 08:39 LILACS.mst
-rw-rw-r-- 1 operacao operacao   1536 Apr  9 08:39 LILACS.xrf

```
2) Configurado o insumo para ser concatenado ao processamento legado.
Editar o arquivo de controle coletas.tab e incluir na coluna ^c da linha hom a informação homeoindex, que é o nome do diretório onde está a base filtrada ( serverofi5:/bases/fiadmin/databases/homeoindex )
```
cd /bases/lilG4/tabs
vi coletas.tab
hom     HOMEOIndex      /bases/lilG4/hom.lil    scp     ^h=pr10vm.bireme.br^d=/home/apps/bvs.br/wp-homeopatia/bases/lildbi/dbcertif/lilacs^l=8022^p=transfer^s=102030^b=^c=homeoindex   x
```
Com isso, ao se rodar o processo **./coleta_scp.sh hom** automaticamente será concatenado.
