### ISSUE TITLE
Mudança de Servidor do ABCD-MS

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#147]
O ABCD-MS mudou de servidor é necessario mudar a coleta do LILDBI-WEB do ABCD-MS da PR20DX que mudou para CORAL50 para o processamento dos registros para a publicacão no iaHx do BVS-MS, a Sandra que identificou o problema por causa da diferença de quantidade de registros.

Aproveitar e ver se tem outros processamentos que tinha a origem dos dados no servidor desativado.
Grata

**Comment by botturam** [comment]
concluído novo processamento regular. Estará disponível em produção amanhã, dia 10/04

**Comment by botturam** [comment]
disponível em produção.
