### ISSUE TITLE
Inclusão da BIGG na APS

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#148]
Solcito incluir a Base de Dados BIGG no processamento da APS
Incluir o conteúdo no recorte:
Coleções APS  
  Diretrizes clínicas (internacional) 

Incluir o no cluster:
Bases de Dados:
  pt - BIGG - guias GRADE 
  es - BIGG - guías GRADE
  en - BIGG - GRADE guidelines

**Comment by botturam** [comment]
Primeiro passo, coleta do FIADMIN para serverofi5:/bases/fiadmin/databases

indexado em: BIGG

@falbrito

**Comment by falbrito** [comment]
Processamento de coleta realizado e colocado em fluxo.
Base disponível em:
serverofi5:/bases/fiadmin/databases/bigg/LILACS.{mst,xrf}

**Comment by botturam** [comment]
Aguardar processamento. Disponível na 4f, para inserção do label no cluster DB

**Comment by pintoros** [comment]
Obrigada, aguardo para verificação.



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:94ea064a-34d5-4b60-831e-8179443c3a52]

________________________________
De: botturam <notifications@github.com>
Enviado: segunda-feira, 22 de abril de 2019 16:45
Para: bireme/db-processing
Cc: Pinto, Rosemeire (BIR); Author
Assunto: Re: [bireme/db-processing] Inclusão da BIGG na APS (#148)


Aguardar processamento. Disponível na 4f, para inserção do label no cluster DB

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F148%23issuecomment-485528046&data=02%7C01%7Cpintoros%40paho.org%7Ceacca64370de424d433a08d6c75b148a%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636915591330570184&sdata=3tcgYQKx47NrA%2Fy6BWxBAiQI%2BikQxyxnt1Jo%2BXaIR%2Bk%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BCLYT7ITQJLPPEFMLPRYIVVANCNFSM4HG57RHQ&data=02%7C01%7Cpintoros%40paho.org%7Ceacca64370de424d433a08d6c75b148a%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636915591330570184&sdata=FGWPnlyhK8t8ryIJ22wHisLADogOooGVyqBGeU2ICpU%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
falta conclusão do chamado Ocomon 6309 pelo ITI, referente a disponibilizar pesquisa pelo cluster Base de Dados.

**Comment by botturam** [comment]
Disponível em produção. ITI atualizou arquivos da interface IAHx-APS em produção.

**Comment by pintoros** [comment]
Por favor, corrigir os labels nas interfaces.
pt - BIGG - guias GRADE
es - BIGG - guías GRADE
en - BIGG - GRADE guidelines

**Comment by pintoros** [comment]
Solicito incluir a base completa, não passando pelo filtro.
Obrigada

**Comment by botturam** [comment]
Qual filtro? A base disponível é a completa, com 570 docs (terça-feira)

**Comment by botturam** [comment]
O novo label está disponível

**Comment by botturam** [comment]
disponível em produção
