### ISSUE TITLE
Configurar processo de coleta da Secretaria de Estado da Saúde de São Paulo - SES-SP

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#153]
Por favor, configurar o processamento para juntar as coletas do FI-ADMIN e da base legado do SES-SP até finalizarmos a migração da base de dados da Secretária. 

Sigla para filtro do processamento: SES-SP

Grata

**Comment by falbrito** [comment]
Processo já operando.

```
 +++ Realiza concatenacao
    Totais:
    - Total base original: 37707
    - Total base FI-Admin: 8
    - Total Concatenado:   37715

```
Em 13/05/2019.

**Comment by botturam** [comment]
documentos já disponíveis em produção.
