### ISSUE TITLE
Bibliografia do SUS

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#156]
Solicito incluir os IDs nos 23 temas da Bibliografia do SUS (http://pesquisa.bvsalud.org/sus), somando-se (OR) aos IDs já processados em cada área temática.
Arquivo anexo.
[atualizacao_bibliografia_sus.xlsx](https://github.com/bireme/db-processing/files/3209039/atualizacao_bibliografia_sus.xlsx)

**Comment by pintoros** [comment]
Arquivos em txt para processamento

[Base juridico.txt](https://github.com/bireme/db-processing/files/3212598/Base.juridico.txt)
[Principios_SUS.txt](https://github.com/bireme/db-processing/files/3212599/Principios_SUS.txt)
[SUS_comparacao.txt](https://github.com/bireme/db-processing/files/3212600/SUS_comparacao.txt)
[Ciencia_tecnologia.txt](https://github.com/bireme/db-processing/files/3212601/Ciencia_tecnologia.txt)
[Protecao_vigilancia.txt](https://github.com/bireme/db-processing/files/3212602/Protecao_vigilancia.txt)
[Sistemas_informacao.txt](https://github.com/bireme/db-processing/files/3212603/Sistemas_informacao.txt)
[Assistencia_farmaceutica.txt](https://github.com/bireme/db-processing/files/3212604/Assistencia_farmaceutica.txt)
[Redes_atencao.txt](https://github.com/bireme/db-processing/files/3212605/Redes_atencao.txt)
[Educacao_popular.txt](https://github.com/bireme/db-processing/files/3212606/Educacao_popular.txt)
[Gestao_educacao.txt](https://github.com/bireme/db-processing/files/3212607/Gestao_educacao.txt)
[Gestao_administrativa.txt](https://github.com/bireme/db-processing/files/3212608/Gestao_administrativa.txt)
[Gestao_trabalho.txt](https://github.com/bireme/db-processing/files/3212609/Gestao_trabalho.txt)
[Promocao_intersetorialidade.txt](https://github.com/bireme/db-processing/files/3212610/Promocao_intersetorialidade.txt)
[Atencao_basica.txt](https://github.com/bireme/db-processing/files/3212611/Atencao_basica.txt)
[Saude_suplementar.txt](https://github.com/bireme/db-processing/files/3212612/Saude_suplementar.txt)
[Regionalizacao.txt](https://github.com/bireme/db-processing/files/3212613/Regionalizacao.txt)
[Controle_auditoria.txt](https://github.com/bireme/db-processing/files/3212614/Controle_auditoria.txt)
[Regulacao.txt](https://github.com/bireme/db-processing/files/3212615/Regulacao.txt)
[Comunicacao.txt](https://github.com/bireme/db-processing/files/3212616/Comunicacao.txt)
[Controle_social.txt](https://github.com/bireme/db-processing/files/3212617/Controle_social.txt)
[Financiamento.txt](https://github.com/bireme/db-processing/files/3212618/Financiamento.txt)
[Judicializacao.txt](https://github.com/bireme/db-processing/files/3212619/Judicializacao.txt)
[Reforma_sanitaria.txt](https://github.com/bireme/db-processing/files/3212621/Reforma_sanitaria.txt)

**Comment by suelisuga** [comment]
Prezados,

Solicito que os registros marcados para a Bibliografia do SUS no sistema FI-Admin sejam incluidos nessa interface de iAHx.

Em registros bibliográficos o campo marcado deve ser o "Base de dados" e o valor presente é BIBLIOGRAFIA-SUS.
Ao coletar estes registros, incluir também a categorização presente em "Descritores Locais".

Em Multimedia, coletar os registros marcados com "Bibliografia do SUS" no campo "Área Temática".

Dessa forma, além dos registros marcados via IDs, os registros do FI-Admin marcados também serão coletados e publicados.

Muito obrigada!

Sueli M Yano Suga
BIREME/OPAS/OMS

**Comment by renatomurasaki** [comment]
@botturam issue antigo. Tenho dúvida se as solicitações foram realizadas, olhando o iAHx da Bibliografia do SUS.

**Comment by botturam** [comment]
concluído
