### ISSUE TITLE
Estratégias de basic research, implementation research e product development

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#157]
As estratégias estão disponíveis em

https://bvsalud.org/queries/search_strategy/implementation-research-optional/?l=pt_BR&se=research

https://bvsalud.org/queries/search_strategy/basic-research-optional/?l=pt_BR&se=research

https://bvsalud.org/queries/search_strategy/product-development/?l=pt_BR&se=product

É possível executá-las contra os registros recuperados em LILACS, Medline, WoS e SESSP-Prod no âmbito dos indicadores infométricos da SES-SP?

**Comment by botturam** [comment]
Resultados de:

1) LILACS (3.578 docs):

   Basic Research                    723 docs (20.2%)
   Product_Development        602docs  (16.8%)
   Implementation Research  727docs  (20.3%)

2) MEDLINE (4.099 docs):

   Basic Research                   2.093 docs (51.1%)
   Product_Development         712 docs  (17.4%)
   Implementation Research    727 docs  (20.3%)

**Comment by renatomurasaki** [comment]
Obrigado, Marcelo. O perfil está se confirmando. Aguardo geração para WoS e SESPROD e o respectivo CSV.

________________________________
De: botturam <notifications@github.com>
Enviado: quarta-feira, 29 de maio de 2019 18:13
Para: bireme/db-processing
Cc: Renato Murasaki; Author
Assunto: Re: [bireme/db-processing] Estratégias de basic research, implementation research e product development (#157)


Resultados de:

  1.  LILACS (3.578 docs):

Basic Research 723 docs (20.2%)
Product_Development 602docs (16.8%)
Implementation Research 727docs (20.3%)

  2.  MEDLINE (4.099 docs):

Basic Research 2.093 docs (51.1%)
Product_Development 712 docs (17.4%)
Implementation Research 727 docs (20.3%)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F157%3Femail_source%3Dnotifications%26email_token%3DAAJLL2WIO5IDVSEPBXXZCZ3PX3WXZA5CNFSM4HPE6W2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWQVCSY%23issuecomment-497111371&data=02%7C01%7Cmurasaki%40paho.org%7Cf76771e10eb649566ae308d6e47a8329%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636947612168799263&sdata=5QA8O4xEZxHhv%2F%2Fb9OUopF22Xx4rPTpT53LwQLpHylo%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAJLL2XIDT4CHRWD6HVXS3LPX3WXZANCNFSM4HPE6W2A&data=02%7C01%7Cmurasaki%40paho.org%7Cf76771e10eb649566ae308d6e47a8329%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636947612168809262&sdata=NUhbuToE7xO8XR%2FovfgUgclJ1tgIENGoqf%2Fm0Z2iLY4%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
Estão disponíveis em:

1) ftp.bireme.br (usuário ofi): /home/ftp/OFI/sessp2019/v2
2) pendrive: F:\SESSP_2019

A tabela com os temas tem o seguinte sufixo: "_afil_tema_SESSP.txt"

**Comment by botturam** [comment]
faltou apenas fechar o chamado. Tabulações concluídas em jun/2019
