### ISSUE TITLE
Atualizar arquivos de conversão de instituições NMAIL para carga no FI-ADMIN

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/db-processing#159]
Os arquivos gerados anteriormente se encontram no caminho abaixo:

serverofi5:/bases/lilG4/tab_nmail/tabulacao_instituicoes/

Obrigado

**Comment by botturam** [comment]
Fiz uma nova execução em:

serverofi5:/bases/lilG4/tab_nmail/tabulacao_instituicoes_maio2019 
(NMAIL de quartzo2:/home/intranet/bases/nmail/nmail.*)

**Comment by viniciusandrade** [comment]
Obrigado, vou testar a importação dos dados e informo se esta tudo OK.

**Comment by viniciusandrade** [comment]
@botturam 

Tive problemas ao tentar importar o arquivo devido ao tamamnho do campo phone_number em alguns registros que ultrapassaram o limite de 155 caracteres previstos no banco de dados.

Seria possível tratar o campo phone_number quebrando em ocorrências usando a / e o ; como separadores? 

Obrigado.

**Comment by botturam** [comment]
concluído.
