### ISSUE TITLE
Ordenar os subcampos do Localização[3] 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#162]
Por favor, se possível ordenar os subcampos da Localização [3] dos registros de referencia bibliográfica que utilizem a metodologia LILACS. Conforme ordem abaixo:

Subcampo ^*:
Registra-se a Localização normalmente o Código do Centro Cooperante
Subcampo ^a:
Registra-se no subcampo ^a, o número de classificação (NLM, CDU, DEWEY, etc.) do documento:
^a: o número de classificação (NLM, CDU, DEWEY, etc.) do documento
Subcampo ^b:
Registra-se no subcampo ^b, o número de autor (CUTTER, PHA, etc.):
^b: o número de autor (CUTTER, PHA, etc.);
Subcampo ^c:
Registra-se no subcampo ^c informações referentes a: volume, tomo, parte, etc. que fizerem parte
do número de chamada, separadas entre si por vírgula:
^c: informações referentes a volume, tomo, parte, etc. que fizerem parte do número de chamada,
separadas entre si por vírgula.
Subcampo ^t:
Ver anotação no ítem “Sistema de Empréstimo” deste campo. 

Grata

**Comment by falbrito** [comment]
Incorporado processo que ordena o conteúdo do campo v3

Arquivos envolvidos:
```
serverofi5:/bases/fiadmin/consolida/tpl/harv_fiadmin.sh
serverofi5:/usr/local/bireme/tabs/v3_ordena.prc

```
Processo incluído:
```
  # Corrigindo ordem no campo v3
  mx tmp8 "proc=@$TABS/v3_ordena.prc" "proc='d3'" create=tmp9 -all now
  # retag de 333 para 3
  echo "333 3" > retag_v3.tab
  retag tmp9 retag_v3.tab

```

A alteração deve ser visível no próximo processamento.

Realizado.
