### ISSUE TITLE
Criar sitemap para todas as bases de dados do GIM e registrar no google search console (antigo google webmasters)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#163]
Exceto para a base LILACS
Com o novo framework de interoperabilidade, a ideia é promover novamente esses documentos no Google e Google Academico.

**Comment by falbrito** [comment]
- Processo de criação de sitemap para as bases WPRIM, IMEMR, IMSEAR e AIM realizado.
- Cadastro dos sitemaps em Google Search Console realizado.

Documentação pertinente: 
wiki.bireme.org/intranet/index.php/Sitemap
