### ISSUE TITLE
Desenvolver script saneamento_colecionasus.sh

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#17]
Responsável pelas rotinas de normalização específicas da fonte de informação ColecionaSUS

**Comment by botturam** [comment]
depois da remodelação da arquitetura dos shells, o normailza_colecionasus.sh foi renomeado para saneamento_colecionasus.sh

**Comment by botturam** [comment]
será desenvolvido posteriormente, conforme formos seguindo a sequência de desenvolvimento dos fluxos das FIs

**Comment by santosfj** [comment]
O script está desenvolvido e testado (preliminarmente), será commitado na manhã do dia 16/06, além de seu nome ter sido alterado para saneamento_sus.sh para confirmadade com as demais denominações de scripts
