### ISSUE TITLE
Economic evaluations

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#170]
[Economic_evaluations.txt](https://github.com/bireme/db-processing/files/3552965/Economic_evaluations.txt)

**Comment by pintoros** [comment]
Substitui o arquivo txt

**Comment by botturam** [comment]
disponível em produção.

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção.

**Comment by botturam** [comment]
já foi atualizada em junho:

(mh:Economia OR ti:econom* OR mh:"Custos e Análise de Custo" OR ti:"Custos e Análise de Custo" OR ti:"Costs and Cost Analysis" OR ti:"Costos y Análisis de Costo" OR mh:"Economia da Enfermagem" OR ti:"Economia da Enfermagem" OR ti:"Nursing Economics" OR ti:"Economía de la Enfermería" OR mh:"Economia Médica" OR ti:"Economia Médica" OR ti:"Medical Economics" OR mh:Farmacoeconomia OR ti:Farmacoeconomia OR ti:"Economia Farmacêutica" OR ti:"Economia da Farmacologia" OR ti:"Economia da Farmácia" OR ti:"Economia de Farmácia" OR ti:"Economia em Farmácia" OR ti:"Economía Farmacéutica" OR ti:"Pharmaceutical Economics" OR ti:Pharmacoeconomics OR ti:"Pharmacy Economics"  OR ti:"Economía de la Farmacia" OR ti:"Economía de Farmacia" OR mh:"Economia Hospitalar" OR ti:"Economia Hospitalar" OR ti:"Hospital Economics" OR ti:"Economía Hospitalaria" OR ti:"Economía de Hospital" OR mh:"Economia em Odontologia" OR ti:"Economia em Odontologia" OR ti:"Dental Economics" OR ti:"Economía Dental" OR mh:"Honorários e Preços" OR ti:"Honorários e Preços" OR ti:"Fees and Charges" OR ti:"Honorarios y Precios" OR mh:Orçamentos OR ti:Orçamento* OR ti:Budget* OR ti:Presupuestos OR ti:"Controle Orçamentário"  OR ti:(cost OR custo OR costs OR custos OR costly OR costing OR custeio OR price OR prices OR pricing OR preço OR preços OR expenditure OR expenditures OR expense* OR expenses OR despesa* OR gasto OR financ* OR budget OR pressupuesto* OR orçament*) OR ti:"value for money" OR ti:"monetary value" OR ti:"valor monetário" OR mh:"Modelos Econômicos" OR ti:"Modelos Econômicos" OR ti:"Economic Models" OR ti:"Economic Model" OR mh:"Cadeias de Markov" OR ti:"Cadeias de Markov" OR ti:"Markov Chains" OR ti:"Cadenas de Markov" OR ti:markov  OR mh:"Método de Monte Carlo" OR ti:"Método de Monte Carlo" OR ti:"Carlo Method" OR ti:"Método de Montecarlo" OR mh:"Teoria da Decisão" OR ti:"Teoria da Decisão" OR ti:"Decision Theory" OR ti:"Teoría de las Decisiones" OR ti:"decision tree" OR ti:"decision treeboost" OR ti:"decision trees" OR ti:"decision analyses" OR ti:"decision analysis" OR ti:"decision analyst" OR ti:"decision analysts" OR ti:"decision analytic" OR ti:"decision analytical" OR ti:"decision analytics" OR ti:"decision model" OR ti:"decision modelers" OR ti:"decision modeling" OR ti:"decision modelling" OR ti:"decision models")
