### ISSUE TITLE
Implementation research

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#171]
[Implementation research.txt](https://github.com/bireme/db-processing/files/3506646/Implementation.research.txt)

**Comment by botturam** [comment]
disponível em produção.

**Comment by botturam** [comment]
concluído.

**Comment by pintoros** [comment]
Solicito atualizar o filtro com a estratégia corrigida disponível em:
https://bvsalud.org/queries/search_strategy/6205/?l=pt_BR

**Comment by botturam** [comment]
em processamento...
