### ISSUE TITLE
Inclusão BIGG no Portal Regional da BVS

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#172]
Solicito incluir a Base de Dados BIGG no processamento do Portal Regional. http://pesquisa.bvsalud.org

Incluir no cluster:
Bases de Dados:
pt - BIGG - guias GRADE
es - BIGG - guías GRADE
en - BIGG - GRADE guidelines
E, como parte da Coleção - Bases de dados especializadas

**Comment by botturam** [comment]
Processamento concluído. Disponível em produção.

Abri o chamado OCOMON 6561 para criarem a nova entrada no cluster "db"

**Comment by botturam** [comment]
disponível em produção.
