### ISSUE TITLE
Public Health & Practice guidelines

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#173]
[Guidelines.txt](https://github.com/bireme/db-processing/files/3510223/Guidelines.txt)

**Comment by botturam** [comment]
Rose, por favor, conferir o cluster na IAHx, pois não o encontro. Seria "Clínica de prática clínica"?

**Comment by pintoros** [comment]
Solicito atualizar o processamento. Sim Marcelo, é o "guia de prática clínica" no regional.
Segue o arquivo.
[Guidelines.txt](https://github.com/bireme/db-processing/files/4523617/Guidelines.txt)

**Comment by pintoros** [comment]
[Guidelines.txt](https://github.com/bireme/db-processing/files/4589803/Guidelines.txt)

Marcelo, editei a estratégia, tive que incluir mais termos.

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
@botturam encerrando este issue, pois creio que o resultado do processamento já esteja disponível em produção (1 ano desde a última atualização deste issue)

**Comment by pintoros** [comment]
Solicito atualização do filtro no Portal Regional da BVS

**Comment by botturam** [comment]
atualizado e verificado (tpl/confestrategy.sh) em study_type/STUDY_TYPE-guideline.sch

**Comment by botturam** [comment]
concluído.
