### ISSUE TITLE
Health technology assessments (HTA)

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#174]
[Health_technology_assessment.txt](https://github.com/bireme/db-processing/files/3510789/Health_technology_assessment.txt)

**Comment by botturam** [comment]
disponível em produção

**Comment by botturam** [comment]
concluído.

**Comment by pintoros** [comment]
Favor atualizar a estratégia de busca para esse tipo de estudo no iahx regional e demais instâncias.

type_of_study:("health_technology_assessment")

[ATS.txt](https://github.com/bireme/db-processing/files/8430401/ATS.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
concluído.
