### ISSUE TITLE
Estratégia de busca sobre Estatísticas Vitais

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#176]
Para LILACS e MEDLINE para geração de CSV infometria. Também entregar para o Luciano o output com os IDS para ele gerar rotina de marcação de documentos dentro da estrutura de data lake.

`((mh:("Estadisticas Vitales" OR "Certificado de Nacimiento" OR "Certificado de Defunción" OR "Causas Múltiples de Muerte" OR "Mortalidad Neonatal Precoz" OR "Mortalidad Laboral" OR "Clasificación Internacional de Enfermedades" OR "Clasificación Internacional del Funcionamiento, de la Discapacidad y de la Salud" OR "Codificación Clínica" OR "Indicadores Demográficos" OR "Indicadores Sociales" OR "Carga Global de Enfermedades") OR ("Esperanza de Vida" AND NOT ("/terapia" OR (("/complicaciones" OR "/patologia" OR "/fisiopatologia") AND NOT ("/epidemiologia" OR "/economia" OR "/estadística & datos numéricos" OR "/tendencias" OR "/legislación & jurisprudencia"))))) OR (no_indexing:1 AND (ti:("Estadisticas Vitales" OR "Estatísticas Vitais" OR "Vital Statistics" OR "Clasificación Internacional de Enfermedades" OR "International Classification of Diseases" OR "Classificação Internacional de Doenças" OR CIE OR CID OR ICD OR "Clasificación Internacional del Funcionamiento, de la Discapacidad y de la Salud" OR "International Classification of Functioning, Disability and Health" OR "Classificação Internacional de Funcionalidade, Incapacidade e Saúde" OR CIF OR ICF OR "Certificado de Nacimiento" OR "Birth Certificates" OR "Declaração de Nascimento" OR "Certificados de Nacimiento" OR "Declaración de Nacido Vivo" OR "Certificado de Defunción" OR "Certificado de Defunción" OR "Atestado de Óbito" OR "Atestados de Óbito" OR "Death Certificates" OR "Causas Múltiples de Muerte" OR "Multiple Cause of Death" OR "Causas Múltiplas de Morte" OR "Codificación Clínica" OR "Clinical Coding" OR "Codificação Clínica" OR "Indicadores Demográficos" OR "Demographic Indicators" OR "Indicadores Sociales" OR "Indicadores Sociais" OR "Social Indicators" OR "Carga Global de Enfermedades" OR "Carga Global da Doença" OR "Global Burden of Disease" OR "Carga de Morbimortalidad Global" OR "Tablas de vida" OR "Tábuas de Vida" OR "Life Tables" OR "Encuestas de Morbilidad" OR "Inquéritos de Morbidade" OR "Morbidity Surveys" OR "Encuestas de Morbilidad" OR "Inquéritos de Morbidade" OR "Morbidity Surveys" OR "Encuestas Epidemiológicas" OR "Inquéritos Epidemiológicos" OR "Health Surveys" OR "Pesquisas sobre Serviços de Saúde" OR "Health Care Surveys" OR "Pesquisas sobre Serviços de Saúde" OR "Health Care Surveys" OR "Indicadores de Morbimortalidad" OR "Indicadores de Morbimortalidade" OR "Indicators of Morbidity and Mortality" OR ((Natalidad* OR Birth OR Mortali* OR Morbilidad* OR Morbidade* OR Morbidit* OR Morbimortalidad) AND (tasa* OR indicador* OR indicator* OR coeficiente OR rate)) OR (("Esperanza de Vida" OR "Expectativa de Vida" OR "Life Expectancy") AND NOT (patient* OR paciente* OR surg* OR cirurg* OR cirug* OR specie* OR especie* OR symptom* OR sintoma* OR therap* OR terapia* OR treatment* OR tratam*)) OR ("Causas de Muerte" OR "Causas de defuncion" OR "Cauda de Morte" OR "Cause of Death")))) OR ((mj:("Tablas de vida" OR "Encuestas de Morbilidad" OR "Encuestas Epidemiológicas" OR "Indicadores de Morbimortalidad" OR "Tasa de Natalidad" OR "Registros de Mortalidad" OR "Estadísticas de Secuelas y Discapacidad") OR (mj:("Causas de Muerte" OR "Morbilidad" OR "Mortalidad" OR "Mortalidad del Niño" OR "Resultado Fatal" OR "Mortalidad Fetal" OR "Mortalidad Infantil" OR "Mortalidad Perinatal" OR "Mortalidad Materna" OR "Mortalidad Prematura" OR "Tasa de Supervivencia" OR "Demografía") AND mh:("/epidemiologia" OR "/métodos" OR "/economia" OR "/estadística & datos numéricos" OR "/tendencias" OR "/legislación & jurisprudencia") AND NOT mh:("/complicaciones"))))) AND NOT mh:("Animales")`

**Comment by botturam** [comment]
Criação do ambiente de configuração e operação regular concluída:

1) Estratégia de pesquisa criada em:
serverofi5:/bases/Strategies2IAHX/apps/strategies/evitais/EVITAIS.sch

2) arquivo de IDs estará disponível em:
serverofi5:/bases/Strategies2IAHX/apps/ids_iahx/evitais/

Primeira execução em andamento...

**Comment by botturam** [comment]
Processamento concluído.

Disponível em: serverofi5:/bases/Strategies2IAHX/apps/ids_iahx/evitais/EVITAIS_full.ids
Tempo de referência: 1h

**Comment by botturam** [comment]
Arquivo com os IDs-IAHx já estão em xisto01.bireme.br
