### ISSUE TITLE
MTyC Bases de Dados

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#177]
Solcito verificar documento disponível em [https://bir-fc.paho.org/TC/TC/Projetos/NICARAGUA/Temas-estrategias/EXTRATEGIAS%20MTyC%20-%202018.xlsx](url) para ajuste de inclusão/exclusão das bases de dados na instância [http://pesquisa.bvsalud.org/mtyc](url)

**Comment by botturam** [comment]
está em operação regular. Disponível em produção.
