### ISSUE TITLE
Aplicar processamento de estratégias de busca relacionadas a cluster da BVS no GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#186]
@botturam percebi, por exemplo, que o cluster tipo de estudo só está recuperando documentos da LILACS. Por favor, inclua todas as bases do GIM para que tenhamos uma visão global. Minha sugestão é fazer o mesmo para todas as outras estratégias, porque nos dá a oportunidade de agregar valor ou entregar análises específicas para a OMS daquilo que já temos.

**Comment by botturam** [comment]
comando shell para verificar campos disponíveis em AFRO:
grep "<field name=\"" afr_regional.xml|cut -f1 -d\>|cut -f2 -d=|sort -u

Amanhã, inserir o cluster "tipo de estudo" na instância GIM

**Comment by botturam** [comment]
Cluster "type of study" inserido em instância de teste. 

Neste momento, as instâncias de GIM e Portal-Regional possuem os mesmos clusteres.

**Comment by botturam** [comment]
disponível em produção
