### ISSUE TITLE
verificar Google Search Console do iAHx GIM -> site maps apresentam erros

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#187]

**Comment by botturam** [comment]
uma nova propriedade/instância https (https://pesquisa.bvsalud.org/gim/) foi criada no GOOGLE Search Console. foram cadastradas:

/sitemap/AIM_Sitemap_index_https.xml	
/sitemap/IMSEAR_Sitemap_index_https.xml
/sitemap/WPRIM_Sitemap_index_https.xml
/sitemap/IMEMR_Sitemap_index_https.xml

**Comment by botturam** [comment]
sitemaps sendo gerados:

operacao@serverofi5:/bases/IAHX_Sitemaps/apps/BVS/gim $ ll
total 56
drwxr-sr-x 2 operacao operacao 4096 Oct 29 07:55 AIM/
-rw-r--r-- 1 operacao operacao  293 Oct 29 07:55 AIM_Sitemap_index_https.xml
-rw-r--r-- 1 operacao operacao  286 Oct 29 07:55 AIM_Sitemap_index.xml
drwxr-sr-x 2 operacao operacao 4096 Oct 29 07:55 IMEMR/
-rw-r--r-- 1 operacao operacao 1299 Oct 29 07:55 IMEMR_Sitemap_index_https.xml
-rw-r--r-- 1 operacao operacao 1250 Oct 29 07:55 IMEMR_Sitemap_index.xml
drwxr-sr-x 2 operacao operacao 4096 Oct 29 07:55 IMSEAR/
-rw-r--r-- 1 operacao operacao 1313 Oct 29 07:55 IMSEAR_Sitemap_index_https.xml
-rw-r--r-- 1 operacao operacao 1264 Oct 29 07:55 IMSEAR_Sitemap_index.xml
drwxr-sr-x 2 operacao operacao 4096 Oct 29 07:55 WPRIM/
-rw-r--r-- 1 operacao operacao 4489 Oct 29 07:55 WPRIM_Sitemap_index_https.xml
-rw-r--r-- 1 operacao operacao 4307 Oct 29 07:55 WPRIM_Sitemap_index.xml

no Google Search Console, os erros são erros regulares:

https://search.google.com/u/1/search-console/index?resource_id=https%3A%2F%2Fpesquisa.bvsalud.org%2Fgim%2F&hl=pt

**Comment by renatomurasaki** [comment]
Problema corrigido. Sitemaps processados
