### ISSUE TITLE
Temas transversais - Etnicidade

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#188]
Segue a estratégia de recorte para Etnicidade.
[Etnicidade.txt](https://github.com/bireme/db-processing/files/3785978/Etnicidade.txt)

**Comment by botturam** [comment]
tema de "etinicidade" incorporado nos processamentos, através de ../tpl.lil/Insere_Tema_Subtema_via_Id.sh, na tag 708

**Comment by pintoros** [comment]
Estratégia de busca "narrow" para etnicidade
[Etnicity_narrow.txt](https://github.com/bireme/db-processing/files/3941856/Etnicity_narrow.txt)

**Comment by botturam** [comment]
disponíveis para pesquisa no Portal regional por:    

tag_temasprioritarios:"etnicidade"

**Comment by botturam** [comment]
em produção regular.
