### ISSUE TITLE
Filtro Systematic Review

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#189]
Solicito verificar o processamento do filtro Systematic Review, pois o conteúdo do filtro não corresponde com o resultado da sintaxe de busca aplicada.

Exemplo: Ao combinar o termo teledentistry com a sintaxe, manualmente, o resultado são 7 Revisões Sistemáticas. Ao pesquisar o mesmo termo e aplicar o filtro processado, o resultado são 2 Documentos que não fazem parte do resultado correto (7 RS)

**Comment by botturam** [comment]
está disponível uma forma de pesquisar apenas as Revisões Sistemáticas de LILACS, segundo Epistemonikos  (21.263 docs):

revsys_epistem:"1" and db:"LILACS"

Segundo a estratégia atual, apenas LILACS (3.131 docs):

db:"LILACS" and ((((ti:"systematic review" OR ti:"revisao sistematica" OR ti:"revision sistematica" OR ti:"systematic literature review" OR ti:"systematic scoping review" OR ti:"systematic narrative review" OR ti:"systematic qualitative review" OR ti:"systematic evidence review" OR  ti:"systematic quantitative review" OR ti:"syst ematic meta-review" OR ti:"systematic critical review" OR ti:"systematic mixed studies review" OR ti:"systematic mapping review" OR ti:"systematic cochrane r eview" OR ti:"systematic search and review" OR ti:"systematic integrative review" OR ab:"this systematic review" OR ab:"esta revisao sistematica" OR ab:"esta  revision sistematica" OR ta:"Cochrane Database Syst Rev" OR pt:"systematic review") AND NOT (pt:comment OR pt:letter OR ti:(protocol OR protocols OR protoco lo*)))))

**Comment by botturam** [comment]
O novo processamento de MEDLINE com 301.775 docs de "Revisão Sistemática" estará pronto na 2f, dia 11.

**Comment by botturam** [comment]
disponível em produção

**Comment by botturam** [comment]
processamento em produção regular

**Comment by pintoros** [comment]
Solicito atualizar a estratégia de busca de Revisão Sistemática.
Atual disponível em: https://bvsalud.org/queries/search_strategy/revisao-sistematica/?l=pt_BR

**Comment by botturam** [comment]
atualizada em apps/strategies/study_type/STUDY_TYPE-systematic_reviews.sch

**Comment by pintoros** [comment]
@botturam , isso significa que foi atualizado no cluster do iAHx? É que o resultado da estratégia de busca está diferente em quase 30 mil documentos do resultado do cluster.

**Comment by botturam** [comment]
@pintoros as estratégias dos 3 tipos de estudo abaixo nunca vão bater com o cluster Tipo de Estudo, pois existem 2 arquivos de um processamento de Epistemonikos (MDL e LIL) que marcam registros de LILACS e MEDLINE:

1) broad_synthesis
2) structured_summary_of_systematic_review
3) systematic_reviews

Os documentos de LILACS e MEDLINE, apenas, são marcados durante o processamento com os arquivos:

STUDY_TYPE_LIL_epistemonikos.ids
STUDY_TYPE_MDL_epistemonikos.ids

**Comment by botturam** [comment]
Concluído, em produção.
