### ISSUE TITLE
Desenvolver script iah_lilacs.sh

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#19]
Relacionado ao #7

Responsável pelas rotinas de geração de índice ISIS.

**Comment by botturam** [comment]
depois de uma remodelação da arquitetura de shells, o iah_lilacs.sh passou a ser iah_lil_FI.sh

**Comment by botturam** [comment]
será incorporado pelo iah_like_lilacs_fi.sh  task #14
