### ISSUE TITLE
Estratégias de busca ODS 3 - LILACS

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#192]
Segue o arquivo das estratégias de busca para ODS 3 elaboradas para LILACS
[Estratégias LILACS-ODS3-REV.xlsx](https://github.com/bireme/db-processing/files/3798343/Estrategias.LILACS-ODS3-REV.xlsx)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
processamento regular semanal disponível em produção:

serverofi5:/bases/Strategies2IAHX/apps/ids_iahx/ods3/ODS3_full.ids
