### ISSUE TITLE
Verificar ID do AIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#193]
Parece q os ID dos documentos do AIM não estão se mantendo ao longo do tempo.
O documento https://search.bvsalud.org/gim/resource/en/afr-4 tem ID 4 e foi publicado em 2019.

**Comment by botturam** [comment]
no arquivo afr.prc, a linha abaixo estava incorreta, gerando o campo 2 incorreto.

era:
if p(v1^1) then 'a2~^1'v1^1[1]'~' else if p(v1^2) then 'a2~'f(val(v1^2[1]),1,0)'~' fi,fi,

ficou:
if p(v1) then 'a2~'v1[1]'~' fi,

**Comment by botturam** [comment]
disponível em produção.
