### ISSUE TITLE
Temas transversais - Direitos Humanos

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#197]
Segue anexo a estratégia com o filtro de Direitos Humanos revisado. Média de 158 mil documentos.
[Derechos_humanos.txt](https://github.com/bireme/db-processing/files/3865794/Derechos_humanos.txt)

**Comment by botturam** [comment]
processento em andamento.

**Comment by botturam** [comment]
disponível em produção, juntamente com "gênero" e "etnicidade":

serverofi5:/bases/Strategies2IAHX/apps/ids_iahx/temas prioritários/TEMASPRIORITARIOS_full.ids

**Comment by pintoros** [comment]
Segue a estratatégia narrow para Direitos Humanos

**Comment by pintoros** [comment]
[Human_rights_narrow.txt](https://github.com/bireme/db-processing/files/3995868/Human_rights_narrow.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponíveis para pesquisa no Portal regional:

tag_temasprioritarios:"direitos_humanos"
