### ISSUE TITLE
Temas transversais - Equidade

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#198]
Segue arquivo anexo.
Aproximadamente 220 mil documentos
[Equidade.txt](https://github.com/bireme/db-processing/files/3906446/Equidade.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível para pesquisa no Portal Regional por:

tag_temasprioritarios:"equidade"

**Comment by botturam** [comment]
disponível em produção.
