### ISSUE TITLE
Arquidos de IDs da IAHx - campo 3

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#201]
Preencher a coluna 3 dos arquivos de IDs com o valor do PK (776^i) quando existir, senão deixar o valor que atualmente é apresentado.

**Comment by falbrito** [comment]
Realizado.

Para o teste foram utilizados 3 registros da base LILACS cada um com uma situação em particular:
1) Registro onde não tem o campo v776^i e o acrônimo é inserido no processamento LILACS
lil-8
** Não tem id_pk e o v2 é 8

2) Registro onde existe o campo alternate_id. Com isso o v2 vem do campo v779 já com o acrônimo e existe o campo v776^i
lil-11
** campo json: "id_pk": "697632",

3) Registro criado já no FI-Admin então o v2 vem do campo v776^i, e o acrônimo é inserido no ato da coleta.
biblio-899640
** campo json: "id_pk": "899640",

Alterado script:
serverofi5:/bases/Strategies2IAHX/apps/tpl/coleta-IDs_portal.py

Arquivo de estratégia:
operacao@serverofi5:/bases/Strategies2IAHX/apps/strategies/flb_teste $ more FLB_TESTE.sch
id:lil-8 OR id:lil-11 OR id:biblio-899640

Processamento:
operacao@serverofi5:/bases/Strategies2IAHX/apps/tpl $ ./BaixaIDs.sh flb_teste

Resultado:
operacao@serverofi5:/bases/Strategies2IAHX/apps/ids_iahx/flb_teste $ more FLB_TESTE_full.ids 
LILACS|biblio-899640|899640|FLB_TESTE|||
LILACS|lil-11|697632|FLB_TESTE|||
LILACS|lil-8|8|FLB_TESTE|||

**Comment by botturam** [comment]
em produção.
