### ISSUE TITLE
2019-nCoV

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#209]
Segue anexo 2 estratégias pra processamento, uma narrow (18 docs nesta data) e uma abroad (mais de 300 docs)

[CoV++2019_2020.txt](https://github.com/bireme/db-processing/files/4140212/CoV%2B%2B2019_2020.txt)
[nCoV_2020.txt](https://github.com/bireme/db-processing/files/4140213/nCoV_2020.txt)

**Comment by pintoros** [comment]
considerar este arquivo para processamento
[Narrow_2019-nCoV.txt](https://github.com/bireme/db-processing/files/4172057/Narrow_2019-nCoV.txt)

**Comment by pintoros** [comment]
Estratégia atualizada com COVID
[Narrow_COVID-19.txt](https://github.com/bireme/db-processing/files/4187841/Narrow_COVID-19.txt)
-19

**Comment by botturam** [comment]
Rose, aguardar pela próxima atualização do Portal regional, hj ou amanhã.

**Comment by botturam** [comment]
disponível em produção.
