### ISSUE TITLE
why  biblio-1021175 is being retrieved in the following search strategy?

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#212]
There is no clear reason for the record biblio-1021175 being retrieved by the search strategy below:

`tw:((afghan* OR algeria* OR bahrain* OR djibouti* OR egypt* OR iran* OR iraq* OR jordan* OR kuwait* OR lebanon OR lebanese OR libya* OR mauritania* OR morocco OR morroccan* OR oman* OR palestin* OR pakistan* OR qatar* OR saudi-arabia* OR saudi* OR somalia* OR sudan* OR syria* OR tunisia* OR "united arab emirates" OR emirati* OR yemen* OR middle-east* OR north-africa* OR "west bank" OR gaza* OR mena OR maghreb* OR israel* OR arab* OR druze OR kabul OR algiers OR manama OR djibouti OR cairo OR tehran OR baghdad OR amman OR "Kuwait City" OR beirut OR tripoli OR nouakchott OR rabat OR muscat OR ramallah OR jerusalem OR islamabad OR doha OR riyadh OR mogadishu OR khartoum OR damascus OR tunis OR "Abu Dhabi" OR sana'a OR sanaa)) AND tw:("Brincadeiras indígenas do povo tembé do alto rio guamá: diálogo entre a tradição e a modernidade ")`

**Comment by botturam** [comment]
é por causa de tw:((**sana'a**)) and id:biblio-1021175, que possui o descritor QUALITY OF LIFE, que tem como sinônimo em español "Vida Sana"

  1  "HEALTHY LIFESTYLE"
  2  "ESTILO DE VIDA SALUDABLE"
  3  "ESTILO DE VIDA SAUDAVEL"
 50  "^eVida Sana"

**Comment by renatomurasaki** [comment]
Tks. Answer already sent to the user. The suggestion was to use sanaa instead of sana'a, because sanaa retrieves both variations and it is also synonym for Yemen.
