### ISSUE TITLE
BDNPAR - Verificar registros que não foram coletados

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#215]
- [x] Produzir listagem com ID's
- [x] Verificar quais ID's não estão em fiadmin.iso
- [x] Fazer processo de coleta de ID's específicos

**Comment by anakatiacamilo** [comment]
Fabinho, o arquivo esta no serverofi5
/bases/fiadmin2/tools/wrk/lista_ID_BDNPAR.txt

**Comment by falbrito** [comment]
Inclusão dos registros faltantes realizada.
