### ISSUE TITLE
Tema ÁGUA - BVS Saude Ambiental

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#218]
Os arquivos em anexos representam os subtemas.
Devem ser relacionados com OR para compor o tema ÁGUA

[AGUA-Poluentes_da_agua.txt](https://github.com/bireme/db-processing/files/4320700/AGUA-Poluentes_da_agua.txt)
[AGUA-Poluicao_da_agua.txt](https://github.com/bireme/db-processing/files/4320701/AGUA-Poluicao_da_agua.txt)
[AGUA-Abastecimento_de_agua.txt](https://github.com/bireme/db-processing/files/4320702/AGUA-Abastecimento_de_agua.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção.

seguem as expressões para pesquisar tema/subtema da Saúde Ambiental:

tag_saudeambiental:"agua/abastecimento_agua"
tag_saudeambiental:"agua/poluentes_agua"
tag_saudeambiental:"agua/poluicao_agua"
tag_saudeambiental:"desatres"
tag_saudeambiental:"engenharia_saude_publica"
tag_saudeambiental:"geral"
tag_saudeambiental:"meio_ambiente"
tag_saudeambiental:"saneamento"
tag_saudeambiental:"saude_populacao"
tag_saudeambiental:"solo/contaminacao_solo"
tag_saudeambiental:"solo/microbiologia_solo"
tag_saudeambiental:"solo/poluentes_solo"
