### ISSUE TITLE
Tema SOLO - BVS Saude Ambiental

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#219]
Os arquivos em anexos representam os subtemas.
Devem ser relacionados com OR para compor o tema SOLO
[SOLO-Contaminacao_do_solo.txt](https://github.com/bireme/db-processing/files/4320788/SOLO-Contaminacao_do_solo.txt)
[SOLO-Microbiologia_do_solo.txt](https://github.com/bireme/db-processing/files/4320789/SOLO-Microbiologia_do_solo.txt)
[SOLO-Poluentes_do_solo.txt](https://github.com/bireme/db-processing/files/4320790/SOLO-Poluentes_do_solo.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção.

seguem as expressões para pesquisar tema/subtema da Saúde Ambiental:

tag_saudeambiental:"agua/abastecimento_agua"
tag_saudeambiental:"agua/poluentes_agua"
tag_saudeambiental:"agua/poluicao_agua"
tag_saudeambiental:"desatres"
tag_saudeambiental:"engenharia_saude_publica"
tag_saudeambiental:"geral"
tag_saudeambiental:"meio_ambiente"
tag_saudeambiental:"saneamento"
tag_saudeambiental:"saude_populacao"
tag_saudeambiental:"solo/contaminacao_solo"
tag_saudeambiental:"solo/microbiologia_solo"
tag_saudeambiental:"solo/poluentes_solo"
