### ISSUE TITLE
Tema MEIO AMBIENTE - BVS Saude Ambiental

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#220]
Segue anexo
[em revisão]

**Comment by pintoros** [comment]
[MEIO_AMBIENTE.txt](https://github.com/bireme/db-processing/files/4637462/MEIO_AMBIENTE.txt)

revisado!

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção.

seguem as expressões para pesquisar tema/subtema da Saúde Ambiental:

tag_saudeambiental:"agua/abastecimento_agua"
tag_saudeambiental:"agua/poluentes_agua"
tag_saudeambiental:"agua/poluicao_agua"
tag_saudeambiental:"desatres"
tag_saudeambiental:"engenharia_saude_publica"
tag_saudeambiental:"geral"
tag_saudeambiental:"meio_ambiente"
tag_saudeambiental:"saneamento"
tag_saudeambiental:"saude_populacao"
tag_saudeambiental:"solo/contaminacao_solo"
tag_saudeambiental:"solo/microbiologia_solo"
tag_saudeambiental:"solo/poluentes_solo"
