### ISSUE TITLE
Criar índice de busca por data de entrada do registro na base de dados para poder ordenar o resultado de busca

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#230]
Apesar de ser uma demanda para o iAHx do COVID da OMS, creio que isso possa ser implementado na rotina de todas as instâncias de interface de pesquisa.

Relacionado a https://github.com/bireme/iahx-opac/issues/165

**Comment by renatomurasaki** [comment]
Índice já existe entry_date (para entrada na base) e update_date (atualização do registro).

**Comment by viniciusandrade** [comment]
@botturam @falbrito 
Estou reabrindo só para informar que para o índice COVID este elemento esta com conteúdo inválido, não sei se o dado já vem errado da preparação ou se posteriormente no processamento ele esta sendo manipulado.
Pelo que vi todos os documentos estão desta forma:
```
<str name="entry_date">6</str>
```
Obrigado

**Comment by renatomurasaki** [comment]
@botturam @falbrito o campo de entry_date é na planilha o "Date Added", e está no formato DD/MM/AAAA.
