### ISSUE TITLE
Ativar o processo de resumo estruturado na interface do COVID iAHx

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#231]
Exemplo de documento com potencial de ter a marcação dos títulos das seções do resumo estruturado:

https://search.bvsalud.org/global-research-on-novel-coronavirus-2019-ncov/resource/en/covidwho-34503

**Comment by botturam** [comment]
O registro em questão passa pelo processamento regular (/bases/iahx/exec/cron_weekly3.sh) e é marcado no campo "mark_ab". 

Pedirei ao Heitor para dar uma olhada no que pode estar acontecendo.

<doc boost="20">
<field name="id">covidwho-34503</field>
<field name="bvs">covidwho</field>
<field name="db">COVIDWHO</field>
<field name="instance">covidwho</field>
<field name="collection">04-international_org</field>
<field name="type">article</field>
<field name="nivel_tratamento">as</field>
<field name="au">Zhu, N.</field>
<field name="au">Li, C.</field>
<field name="au">Ning, S. S.</field>
<field name="au">Chen, S.</field>
<field name="au">Cao, L.</field>
<field name="au">Yang, G. J.</field>
<field name="au">Li, X. X.</field>
<field name="au">Nian, Y. P.</field>
<field name="au">Wang, W. H.</field>
<field name="au">Liu, Y. Z.</field>
<field name="au">Wang, L.</field>
<field name="au">Lei, F. L.</field>
<field name="au">Zhang, Y.</field>
<field name="au">Zhuang, G. H.</field>
<field name="ti">[Epidemiological characteristics of COVID-19 in Shaanxi province]</field>
<field name="fo">Zhonghua Liu Xing Bing Xue Za Zhi;</field>
<field name="ta">Zhonghua Liu Xing Bing Xue Za Zhi</field>
<field name="ta_var">Chung-Hua Liu Hsing Ping Hsueh Tsa Chih (Chinese Journal of Epidemiology)</field>
<field name="ta_var">Zhonghua Liu Xing Bing Xue Za Zhi</field>
<field name="ab">Objective: To understand the incidence trend and epidemiological characteristics of COVID-19 in Shaanxi province  Methods: The incidence data of COVID-19 reported in Shaanxi as of 22 February, 2020 were collected for an epidemiological descriptive analysis  Results: A total of 245 confirmed cases of COVID-19 were reported in Shaanxi  Most cases were mild (87 76%)  As time passed, the areas where confirmed cases were reported continued to increase  The case number in Xi'an was highest, accounting for nearly half of the total reported cases in the province  The epidemic pattern in Shaanxi had gradually shifted from imported case pattern to local case pattern, and the transmission of local cases was mainly based on family cluster transmission  The confirmed cases from different sources had caused the secondary transmission in Shaanxi  After February 7, the number of reported cases began to fluctuate and decrease stably, indicating a decrease-to-zero period  Conclusions: At present, the overall epidemic of COVID-19 in Shaanxi has gradually been mitigated  However, considering the approaching of return to work and study and the increasing of imported cases from other countries, the prevention and control of COVIS-19 in Shaanxi will face new challenges</field>
<field name="mark_ab">&lt;h2&gt;OBJECTIVE:&lt;/h2&gt; To understand the &lt;a class="decs" id="028583"&gt;incidence&lt;/a&gt; trend and epidemiological characteristics of COVID-19 in Shaanxi province  &lt;a class="decs" id="008901"&gt;Methods&lt;/a&gt;: The &lt;a class="decs" id="028583"&gt;incidence&lt;/a&gt; data of COVID-19 reported in Shaanxi as of 22 February, 2020 were collected for an epidemiological descriptive analysis  Results: A total of 245 confirmed cases of COVID-19 were reported in Shaanxi  Most cases were mild (87 76%)  As &lt;a class="decs" id="014382"&gt;time&lt;/a&gt; passed, the areas where confirmed cases were reported continued to increase  The case number in Xi'an was highest, &lt;a class="decs" id="000070"&gt;accounting&lt;/a&gt; for nearly half of the total reported cases in the province  The &lt;a class="decs" id="054398"&gt;epidemic&lt;/a&gt; pattern in Shaanxi had gradually shifted from imported case pattern to local case pattern, and the transmission of local cases was mainly based on &lt;a class="decs" id="023905"&gt;family&lt;/a&gt; cluster transmission  The confirmed cases from different sources had caused the secondary transmission in Shaanxi  After February 7, the number of reported cases began to fluctuate and decrease stably, indicating a decrease-to-zero period  Conclusions: At present, the &lt;a class="decs" id="029643"&gt;overall&lt;/a&gt; &lt;a class="decs" id="054398"&gt;epidemic&lt;/a&gt; of COVID-19 in Shaanxi has gradually been mitigated  However, considering the approaching of &lt;a class="decs" id="055127"&gt;return to work&lt;/a&gt; and study and the increasing of imported cases from other countries, the &lt;a class="decs" id="050219"&gt;prevention&lt;/a&gt; and &lt;a class="decs" id="051607"&gt;control&lt;/a&gt; of COVIS-19 in Shaanxi &lt;a class="decs" id="015238"&gt;will&lt;/a&gt; &lt;a class="decs" id="005246"&gt;face&lt;/a&gt; new challenges</field>
<field name="no_indexing">1</field>
<field name="services">SCAD</field>
<field name="weight">20</field>
<field name="entry_date">20200406</field>
<field name="regional_office">others</field>
<field name="id_pk">34503</field>
</doc>

**Comment by heitorbarbieri** [comment]
Existem duas questões: o documento em questão assim como vários outros no site OMS/COVID, não apresentam ponto final antes da palavra delimitadora de uma seção do resumo (por ex:  acontecimentos. CONCLUSOES: ) o que era uma condição para o funcionamento da marcação e que exigiu mudanças no algoritmo já implementadas.

Uma segunda questão, conforme relatado pelo Renato, é que por exemplo o documento medline-31986264 aparececia com seu resumo estruturado no portal regional, mas o mesmo com id covid-31986264 não apareceria com seu resumo estruturado no site da OMS/COVID. Verifiquei que no segundo caso o documento também estava marcado corretamente o que me levou a crer que o mecanismo de representação dos blocos do resumo no site OMS/COVID talvez não estivesse levando em conta o tag <h2> assim como no portal regional.

Comuniquei o fato ao Vinicius para que erificasse se o mecanismo de representação dos blocos que considera o <h2>, está funcionando corretamente em OMS/COVID.

**Comment by viniciusandrade** [comment]
Faltava adicionar no **schema.xml** do índice covidoms a definição para que o campo fosse armazenado e fosse possível realizar o display no template:

``
<field name="mark_ab" type="string" indexed="false" stored="true" multiValued="true"/>
<dynamicField name="mark_ab_*" type="string" indexed="false" stored="true" multiValued="true"/>
``

As definições originais deste campo que são usadas no índice portal-org não funcionaram nesta versão do Solr por isso após vários testes foi necessário alterar o tipo do campo de **type="text"** para **type="string"**.

Já disponível em produção.

**Comment by botturam** [comment]
parece que o Vinícius arrumou.
