### ISSUE TITLE
Integrar o processamento da instância COVID-19 com o padrão da BVS e GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#233]
O objetivo, além de entrar no fluxo padrão de processamento do OFI, é permitir o processamento de enriquecimento e qualidade de dados existentes para o clusters/filtros de revistas, tipos de estudo, assunto principal etc, conforme possibilidade de acordo com os metadados disponíveis (a maioria dos documentos da COVID-19 são provenientes do Medline.

**Comment by botturam** [comment]
Já está em operação regular diária, no momento, no cron do Usuário "operação":

/usr/local/bireme/cron/cron_COVIDWHO.sh > /bases/logs/celery/logs/genCOVIDWHO.out
