### ISSUE TITLE
Avaliar se os formatos XML NLM podem ser utilizados para a instância do COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#234]
Tendo em vista os processamentos de Medline e WPRIM, verificar se os formatos XML NLM e XML NLM Standard para citações bibliográficas podem ser úteis, comparado ao uso do atual CSV implementado.

[formato-xml-nlm-citation.zip](https://github.com/bireme/db-processing/files/4469490/formato-xml-nlm-citation.zip)

**Comment by falbrito** [comment]
Análise realizada e enviado e-mail a WHO.
[Email_Analise_XML_a_WHO_20200420.pdf](https://github.com/bireme/db-processing/files/4595364/Email_Analise_XML_a_WHO_20200420.pdf)
