### ISSUE TITLE
Policy briefs

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#239]
[Policy_brief.txt](https://github.com/bireme/db-processing/files/4478565/Policy_brief.txt)

**Comment by botturam** [comment]
em processamento...
OBS: não existia estratégia para Síntese de evidência.

**Comment by renatomurasaki** [comment]
@botturam não encontrei esta entrada no cluster Type of Study

**Comment by renatomurasaki** [comment]
Seria Evidence Synthesis?

**Comment by botturam** [comment]
Esta estratégia já foi atualizada há bastante tempo:

((ti:evidence* OR ti:evidencia*) AND (ti:summar* OR ti:synthesis OR ti:sumario* OR ti:sintes* OR ti:resumo* OR ti:resumen*) OR "policy brief" OR "policy briefs" OR "sintese de evidências" OR "sintese de evidência")

Atualmente recupera 254.105 docs

**Comment by pintoros** [comment]
Está correta Marcelo. É isso mesmo.

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:521d68ce-78df-4bff-b3bc-d1c6dd2abd8b]

________________________________
De: botturam ***@***.***>
Enviado: terça-feira, 10 de agosto de 2021 15:16
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/db-processing] Policy briefs (#239)


Esta estratégia já foi atualizada há bastante tempo:

((ti:evidence* OR ti:evidencia*) AND (ti:summar* OR ti:synthesis OR ti:sumario* OR ti:sintes* OR ti:resumo* OR ti:resumen*) OR "policy brief" OR "policy briefs" OR "sintese de evidências" OR "sintese de evidência")

Atualmente recupera 254.105 docs

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F239%23issuecomment-896209587&data=04%7C01%7Cpintoros%40paho.org%7C4bdfc69ac5ed4a68c42508d95c2ae9a3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637642161653030819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HWnr2xnhVvIoJz4mk53s09k6vOQ1g%2FtNfXqBotHszTE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4FJ74XB5ORBL3UWOGDT4FUGDANCNFSM4MIFXEPA&data=04%7C01%7Cpintoros%40paho.org%7C4bdfc69ac5ed4a68c42508d95c2ae9a3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637642161653040765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Mc6QQhST%2FxtqwM3TrV%2FmMnvh9xqjs51ptwq9Yuvi6xA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7C4bdfc69ac5ed4a68c42508d95c2ae9a3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637642161653050725%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=h%2FncIyOKoi156DNz326rBqSNlyBE%2BTVB8KBy0VCkSH0%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cpintoros%40paho.org%7C4bdfc69ac5ed4a68c42508d95c2ae9a3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637642161653050725%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fbE7O7PYcYZAOP00%2F7P%2FNNDBRa1yRoBu27eGViG7DJg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
Favor atualizar o filtro:

Disponível em: https://bvsalud.org/queries/search_strategy/sintese-de-evidencias/?l=pt_BR

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
Concluído, em produção.
