### ISSUE TITLE
Refatorar o script iahx_xml_BDENF.sh

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#24]
Relacionado ao #16

O refatoramento considerará a possibilidade de gerar um script genérico iahx_xml_fi.sh com um script de pós geração do xml pos_iahx_xml_bdenf.sh.

**Comment by botturam** [comment]
Foi quase concluída a generalização do shell que gera os XMLs Like-LILACS para iAHx (genlilbvsxml.sh). Falta analisar os impactos para CARPHA, que demandam processamento particular.

**Comment by renatomurasaki** [comment]
Em desenvolvimento um script genérico que receberá parametro de base de dados - iahx_xml_fi.sh.

**Comment by botturam** [comment]
atividade encerrada em 2016.
