### ISSUE TITLE
Identificar registros Medline na base WHO COVID por meio do campo DOI

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#243]
Aproximadamente 90% dos documentos não identificados como Medline no processo de ETL inicial possuem o campo DOI preenchido, sendo este dado potencial ponte para enriquecimento tendo o mesmo dado disponível na base Medline

**Comment by renatomurasaki** [comment]
@botturam se for para facilitar este processo, envie para o Luciano um CSV contendo PMID, DOI e URL disponível nos registros do Medline. Pode ser apenas dos documentos publicados em 2020, tendo em vista que o WHO COVID tem esse recorte temporal. Dessa forma, ele enriqueceria os arquivos CSV antes de enviar para processamento diário. O que acha? Se acho que sim, teria que manter um fluxo contínuo (talvez semanal) de atualização desse novo arquivo CSV contendo esta relação PMID, DOI e URL

**Comment by botturam** [comment]
Fiz um teste inicial e cosegui um bom número de 5.926 links. Vou seguir com um fluxo de processamento e depois verificar os que faltam. Eu já havia visto que na WHOLIS há apenas 2. Faltam as regionais da WHO.

**Comment by botturam** [comment]
Terminado e disponível em homologação. No fim, consegui 4.500 lins a mais, além dos 1.532 via PMID. Falta testar mais um pouco. Estou verificando.

OBS: Dentre os docs MDL com os quais trabalhei (uns 6.000), existem, na base COVIDWHO, mais ou menos 450 docs repetidos.

**Comment by renatomurasaki** [comment]
@botturam excelente avanço! Obrigado! Por favor, poderia me gerar uma lista dos repetidos? Poderia ser COVNUMBER, PMID e DOI?

**Comment by renatomurasaki** [comment]
@botturam agora lembrei que enviei uma lista para a OMS com os possíveis duplicados... mas foi semana passada

**Comment by botturam** [comment]
mas aquela eram 35 pares registros duplicados. Usando o doi como chave primária, é bem mais.
