### ISSUE TITLE
Systematic Rev - Observational Studies

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#244]
[Systematic Rev_Observational_studies.txt](https://github.com/bireme/db-processing/files/4554548/Systematic.Rev_Observational_studies.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção.

Hoje, 19 de aqgosto, contei:

operacao@serverofi5:/bases/Strategies2IAHX/apps/ids_iahx/study_type $ grep -i "observa" STUDY_TYPE_full.ids|wc -l
35.929

**Comment by renatomurasaki** [comment]
@botturam encerrando este issue, pois creio que o resultado do processamento já esteja disponível em produção (1 ano desde a última atualização deste issue)
