### ISSUE TITLE
Ethics

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#245]
[Ethics.txt](https://github.com/bireme/db-processing/files/4554602/Ethics.txt)

**Comment by renatomurasaki** [comment]
@botturam o processamento desta estratégia foi realizado?

**Comment by renatomurasaki** [comment]
Processado no âmbito do EVID@Easy - Ethical Aspects

![image](https://user-images.githubusercontent.com/1226218/122992732-d3ef1a80-d37c-11eb-8df8-b484cc39c9af.png)
