### ISSUE TITLE
Diferença entre a quantidade de registros recuperados na planilha Excel do COVID e a interface iAHx, baseando-se no campo "Date Added" do Excel versus "entry_date" do Lucene

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#248]
entry_date:(20200414): [Retrieved: 476 - Submitted: 1120]

entry_date:(20200428): [Retrieved: 327 - Submitted: 472]

entry_date:(20200429): [Retrieved: 412 - Submitted: 480]

entry_date:(20200501): [Retrieved: 73   - Submitted: 856]

**Comment by botturam** [comment]
o campo "Date Added" das tabelas CSVs provavelmente representam a data em que o documento entrou na planilha ou no sistema de controle deles. Começou no dia 01/02/2020

Já o date_entry representa o dia em que o registro entrou no sistema da NLM.

Alguma coisa bate, mas muitos não. É melhor manter o "Date Added" original em todos, uma vez que conceitualmente esse campo representa outra coisa no MEDLINE.

**Comment by renatomurasaki** [comment]
@botturam sim, favor manter o Date Added pois se refere à data de inserção na Base WHO COVID. Não reescrever este campo.

**Comment by botturam** [comment]
Estará disponível no próximo processamento, com atualização em produção às 04:00

**Comment by botturam** [comment]
disponível em produção.
