### ISSUE TITLE
Equity and inequality

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#256]
[Equity.txt](https://github.com/bireme/db-processing/files/4589373/Equity.txt)

**Comment by renatomurasaki** [comment]
@botturam esta estratégia foi processada?

**Comment by renatomurasaki** [comment]
@botturam acabei de ver que sim e está disponível no cluster Aspects

![image](https://user-images.githubusercontent.com/1226218/122995033-714b4e00-d37f-11eb-8b72-508488b3ff44.png)
