### ISSUE TITLE
Patient-preference

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#257]
[Patient-preference.txt](https://github.com/bireme/db-processing/files/4589954/Patient-preference.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
@botturam essa estratégia foi processada?

**Comment by renatomurasaki** [comment]
@botturam acabei de checar que sim. Está no cluster Aspects

![image](https://user-images.githubusercontent.com/1226218/122994927-4f51cb80-d37f-11eb-9600-56de4f9740d4.png)
