### ISSUE TITLE
Criar sitemap e registrar a interface iAHx WHO COVID-19 no Google Console (webmasters)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#262]
Não temos a prática de indexar registros MDL, pois a BVS disponibiliza todos os seus registros. Entretanto, a interface da WHO COVID-19 é somente uma pequena parte e a OMS está trabalhando em conjunto com a NLM, CDC e outras instituições em prol do acesso à informação sobre COVID.
Por favor, deixar toda a base da WHO COVID exposta via sitemap e registrada no Google Console.

**Comment by falbrito** [comment]
Realizado a inclusão de coleta de ID's para COVIDWHO no processo de sitemap. Os registros de MEDLINE foram incluídos conforme determinado.

Os arquivos XML pertinentes já estão no servidor de produção "ardosia01", sendo necessário agora fazer a configuração diretamente no Webmasters do Google.

**Comment by botturam** [comment]
Cadastrado. Aguardar indexação do GOOGLE.

https://search.google.com/u/1/search-console/sitemaps?resource_id=https%3A%2F%2Fpesquisa.bvsalud.org%2Fglobal-literature-on-novel-coronavirus-2019-ncov%2F&hl=pt

endereço do sitemap:

https://pesquisa.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/sitemap/covidoms_Sitemap_index_https.xml
