### ISSUE TITLE
ND-Dengue

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#267]

**Comment by pintoros** [comment]
[Dengue.txt](https://github.com/bireme/db-processing/files/4611626/Dengue.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
@botturam esse processamento foi concluído? Não o vejo no ambiente de testes via interface EVID@easy

**Comment by renatomurasaki** [comment]
@botturam ainda não vejo a opção de Dengue na interface do EVID@Easy. Veja imagem abaixo:

![image](https://user-images.githubusercontent.com/1226218/122994038-647a2a80-d37e-11eb-91d6-37d37b39d663.png)

**Comment by pintoros** [comment]
Marcelo, falta incluir Dengue no contexto ND. #267

Qualquer dúvida, pode me chamar.

Abraço



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:3a348c67-1bad-4b0e-9e28-b2c210fbcb28]

________________________________
De: Renato Murasaki ***@***.***>
Enviado: terça-feira, 22 de junho de 2021 17:22
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/db-processing] ND-Dengue (#267)


@botturam<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbotturam&data=04%7C01%7Cpintoros%40paho.org%7C99dbdfab94c04ba8493408d935bb762b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637599901527433221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=H%2BP6UQar7QdFaKih%2BcAZjtIy%2FpwnZc8t9oc4uGnVXhM%3D&reserved=0> ainda não vejo a opção de Dengue na interface do EVID@Easy. Veja imagem abaixo:

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1226218%2F122994038-647a2a80-d37e-11eb-91d6-37d37b39d663.png&data=04%7C01%7Cpintoros%40paho.org%7C99dbdfab94c04ba8493408d935bb762b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637599901527438198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X63tM6vBmVhr35cPJQidNy6UPA4Pzb2SYLmureJtdjc%3D&reserved=0>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F267%23issuecomment-866306942&data=04%7C01%7Cpintoros%40paho.org%7C99dbdfab94c04ba8493408d935bb762b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637599901527443177%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CnhPW6d2p6NYXa5FVUtL9pJp%2Bfz9qPSIabBnc3JaKyM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4HOZ4RJ56DJKYWQKHLTUDWILANCNFSM4M6FXTTA&data=04%7C01%7Cpintoros%40paho.org%7C99dbdfab94c04ba8493408d935bb762b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637599901527448156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IGin6J2lFzG%2FmA3L0cIi3fTlKV19quwXvG2hpKFXhQY%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
o tema "Dengue" foi incluído e deverá aparecer a partir de 4f nas FIs LILACS e like-LILACS.

**Comment by botturam** [comment]
@pintoros poderia checar se entrou? 

Campo está em LILACS e MEDLINE ao menos.

\<field name="tag_tema_saude">**3_dengue**\</field>

**Comment by pintoros** [comment]
Entrou Marcelo, mas precisa fazer a tradução do label. Vc pode encaminhar?
Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:477139bd-8992-408c-a314-1aa706b2749e]

________________________________
De: botturam ***@***.***>
Enviado: quinta-feira, 22 de julho de 2021 23:40
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/db-processing] ND-Dengue (#267)


@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7Cdbe8be6b7b1e46a1784108d94d8336e0%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637626048242805345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bVZwQWbBLfWB5QPXcjEOaEuAbObeUqkvl9%2BFnWWiack%3D&reserved=0> poderia checar se entrou?

Campo está em LILACS e MEDLINE ao menos.

<field name="tag_tema_saude">3_dengue</field>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F267%23issuecomment-885360515&data=04%7C01%7Cpintoros%40paho.org%7Cdbe8be6b7b1e46a1784108d94d8336e0%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637626048242815300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FjQC4%2BKegUi4K0yx2mb72PR4bXbBWcHlTtT6Lx56WnM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4DPFMITOY7M3W2ZVV3TZDJBJANCNFSM4M6FXTTA&data=04%7C01%7Cpintoros%40paho.org%7Cdbe8be6b7b1e46a1784108d94d8336e0%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637626048242815300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xvyM5U4TAcAyBdNtgMRTrzRx%2FLwxgwMVQNEKf4W6Qj0%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
aberto o Ocomon N.º 8105

**Comment by botturam** [comment]
@pintoros concluido em producao.
