### ISSUE TITLE
ND-Neglected_diseases

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#280]
[Neglected_diseases.txt](https://github.com/bireme/db-processing/files/4619093/Neglected_diseases.txt)

Este arquivo deve ser somado com OR todas as ND para copmper a busca geral sobre o tema.

**Comment by botturam** [comment]
em processamento...

**Comment by pintoros** [comment]
Marcelo, ajustei o nome. O contexto é o mesmo das doenças classificadas como temas em saúde. Apesar de fazer parte, não é especificamente nem da ASSA nem do ODS3.

**Comment by botturam** [comment]
Ok. Obrigado.

**Comment by pintoros** [comment]
Marcelo, o resultado dessa estratégia deve ser somado aos resultados individuais de cada doença nesse contexto. Então seria a estratégia já processada OR a soma de todas as doenças Negligenciadas.
É necessário montar o arquivo? Ou faz direto via sistema?

**Comment by botturam** [comment]
Rose, por favor monte o arquivo e me passe. É mais seguro. Obrigado.

**Comment by pintoros** [comment]
Segue o arquivo combinando as doenças para substituir o atual
[Doencas_negligenciadas_corrigido.txt](https://github.com/bireme/db-processing/files/5382110/Doencas_negligenciadas_corrigido.txt)

**Comment by renatomurasaki** [comment]
@botturam essa estratégia foi atualizada?

**Comment by renatomurasaki** [comment]
@pintoros essa estratégia foi atualizada para processamento?

**Comment by pintoros** [comment]
Boa noite Renato,

Alem dos comentários feitos pelo Arthur no ano passado, a equipe do Ludovic também está discutindo esse tema com uma série de sugestões. Solicito que aguarde. Encaminharei esse tema para processamento junto com essa nova leva do Evid@Easy.



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:60dc164b-e855-4705-b793-d793d7d661e3]

________________________________
De: Renato Murasaki ***@***.***>
Enviado: terça-feira, 22 de junho de 2021 17:24
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Assign ***@***.***>
Assunto: Re: [bireme/db-processing] ND-Neglected_diseases (#280)


Assigned #280<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F280&data=04%7C01%7Cpintoros%40paho.org%7C99bdaf4119e84e006c2908d935bbad36%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637599902450018533%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jORwXaY2aTqeiwlhOzJf5drcjxAzeYvrpDAaJ2DwBSI%3D&reserved=0> to @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C99bdaf4119e84e006c2908d935bbad36%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637599902450023508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=00aFmd5zReX0ui%2FjXKx1Z7BoUSnH6dAHUHGdYsglljI%3D&reserved=0>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F280%23event-4925010556&data=04%7C01%7Cpintoros%40paho.org%7C99bdaf4119e84e006c2908d935bbad36%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637599902450028488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gOUN%2B8RPpVs1USx%2BjfAZSMBnfzKp%2Btz0xoEBZOzcKpI%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4HSGAN7NZ652MVR76DTUDWOFANCNFSM4M7JAGAQ&data=04%7C01%7Cpintoros%40paho.org%7C99bdaf4119e84e006c2908d935bbad36%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637599902450033466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AT%2BPwvDHrPjgyexJ8sRyZZINcbi8HJTuCCaWK2ZoAvw%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
@pintoros  favor validar e fechar o chamado. Obrigado.

**Comment by botturam** [comment]
finalizado.
