### ISSUE TITLE
Verificar base AIM/AFRO do GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#288]
@botturam ao acessar o AIM no site da AFRO e fazer uma pesquisa por COVID encontro 12 referencias bibliográficas:

https://indexmedicus.afro.who.int/aim/opac_css/index.php?lvl=more_results&autolevel1=1

Ao fazer a mesma pesquisa no GIM a reposta é zero.

https://search.bvsalud.org/gim/?output=site&lang=en&from=0&sort=&format=summary&count=20&fb=&page=1&filter%5Bdb%5D%5B%5D=AIM&index=tw&q=covid&search_form_submit=

Por favor, verificar e se necessário contactar o Mike a respeito desta situação.

**Comment by renatomurasaki** [comment]
O total de registros na base AIM na interface do portal da AFRO é de 18.324, exatamente 12 a menos que no GIM. Será que são documentos recém ingressados?

**Comment by botturam** [comment]
a última vez que eles enviaram -- em abril --, o arquivo estava corrompido em um determinado documento e os seguintes talvez, pois não apresentava fim de registro. Tirei-o todo até o início do próximo bom. Não soube qual o impacto disso. 

Tenho esperado o envio de maio para ver como vem, mas não sei se eles estão trabalhando. Não costumam atrasar, mas já adentramos junho.

**Comment by renatomurasaki** [comment]
@botturam acho que coincidiu com esses 12 então... eles estão em teletrabalho tb. Por favor, faça seguimento com o Mike. É importante o nosso seguimento, mesmo que a resposta seja que não vão enviar na data definida. Faz parte do nosso gerenciamento e governança.

**Comment by renatomurasaki** [comment]
vou deixar em aberto este issue até nos certificarmos sobre estes 12 documentos que parecem que são exatamente sobre COVID
