### ISSUE TITLE
ODS3-Acesso universal aos serviços de saude reprodutiva

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#300]
ODS 3

[Acceso universal servicios de salud salud sexual reproductiva.txt](https://github.com/bireme/db-processing/files/4719389/Acceso.universal.servicios.de.salud.salud.sexual.reproductiva.txt)

**Comment by renatomurasaki** [comment]
Disponível em produção como `tag_contexto:("2_ODS3") AND tag_tema_saude:("2_salud_sexual_reprodutiva")`
