### ISSUE TITLE
ODS3-Deter a transmissão de doenças transmissiveis e negligenciadas

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#301]
ODS 3

[Detener transmisión enfermedades transmisibles y desatendidas.txt](https://github.com/bireme/db-processing/files/4719394/Detener.transmision.enfermedades.transmisibles.y.desatendidas.txt)

**Comment by renatomurasaki** [comment]
Disponpivel em produção como` tag_contexto:("2_ODS3") AND tag_tema_saude:("2_enfermedades_transmissibles")`
