### ISSUE TITLE
ODS3-Reduzir mortes por químicos  y contaminação do ar, água e solo

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#304]
ODS 3

[Reducir muertes por quimicos  y contaminación del aire agua suelo.txt](https://github.com/bireme/db-processing/files/4719762/Reducir.muertes.por.quimicos.y.contaminacion.del.aire.agua.suelo.txt)

**Comment by renatomurasaki** [comment]
Disponível em produção como `tag_contexto:("2_ODS3") AND tag_tema_saude:("2_quimicos_contaminacion")`
