### ISSUE TITLE
Qualitative research

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#306]
[Qualitative_research.txt](https://github.com/bireme/db-processing/files/4724311/Qualitative_research.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
@botturam encerrando este issue, pois creio que o resultado do processamento já esteja disponível em produção (1 ano desde a última atualização deste issue)

**Comment by pintoros** [comment]
Solicito atualizar o filtro de acordo com a pesquisa disponível em:

https://bvsalud.org/queries/search_strategy/qualitativo/?l=pt_BR

**Comment by botturam** [comment]
em processamento...
