### ISSUE TITLE
Realizar split do campo Title utilizando o token "TT -"

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#307]
@dossanluc 
Há aprox. 40 registros com o título traduzido no mesmo campo do título em inglês. Avaliando, o que separa o título em inglês e a sua tradução é o token "TT -". Colocar a tradução no campo "Translated Title"

@falbrito @botturam Favor adaptar o processo para receber mais este campo. Lembrem-se que no futuro teremos a existência deste campo exatamente com esta funcionalidade de receber o título em idioma diferente de inglês, como explicado em reuniões anteriores, assim como o campo Notes que terá o resumo em outro idioma diferente do inglês.

**Comment by botturam** [comment]
incluí o trecho em shs.lil/pos_coleta_covidwho.sh

# ----split de v12 por "TT -"
echo "TT -|^B" > gcampo12_TT.seq
mx seq=gcampo12_TT.seq create=gcampo12_TT -all now
mx x3 gizmo=gcampo12_TT,12 "proc='Gsplit=12=^B'" create=x3_tmp -all now tell=10001
mxcp x3_tmp create=x3 clean > /dev/null
rm gcampo12_TT.*
rm x3_tmp.*

Resultado:

mfn= 40008
  2  "8092"
  5  "S"
  6  "as"
  8  "^uhttps://doi.org/10.1016/j.medcli.2020.02.002"
 10  "Trilla, Antoni"
 30  "Medicina clinica"
 64  "2020"
 65  "20200000"
 91  "20200313"
724  "10.1016/j.medcli.2020.02.002"
776  "WHO^i8092"
870  "Opinion piece"
933  "Medicina clinica;154(5):175-177, 2020."
1001  "8092"
1002  "2020"
1004  "154"
1005  "5"
1006  "175-177"
1008  "13/03/2020"
 12  "One world, one health: The novel coronavirus COVID-19 epidemic"
 12  "Un mundo, una salud: la epidemia por el nuevo coronavirus COVID-19"

# -------------------------

OBS: Disponível 4f, 17:00

**Comment by botturam** [comment]
Para conferir:

v2=630044
v2=629748
v2=629344
v2=614496
v2=614494
v2=614290
v2=614288
v2=614286
v2=614220
v2=614218
v2=614107
v2=613829
v2=613702
v2=613700
v2=613687
v2=613684
v2=613682
v2=613678
v2=613673
v2=613500
v2=613479
v2=613391
v2=613369
v2=613350
v2=613306
v2=613264
v2=613263
v2=613196
v2=613181
v2=613172
v2=613152
v2=613135
v2=613098
v2=613074
v2=613070
v2=613053
v2=613051
v2=613036
v2=613032
v2=612987
v2=612985
v2=612961
v2=612948
v2=612930
v2=612886
v2=612758
v2=612752
v2=612728
v2=612722
v2=612702
v2=612604
v2=612565
v2=612555
v2=612525
v2=612497

**Comment by botturam** [comment]
em produção regular.
