### ISSUE TITLE
Erro no entry_date da WHO COVID-19 Database: aparentemente ocorre após o registro ser enriquecido com registro LILACS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#310]
@botturam Este chamado se refere ao email "WHO Database: Records Missing / incomplete Entry Dates" enviado pela equipe da OMS Genebra. 

No arquivo anexo do e-mail, aprox, 80 documentos estão com o entry_date errado e por isso eles reportam problemas de recuperação.

Exemplos:

```
COVNUM         Date Added (MS Excel)             Entry_date (after processing)
5526397           05/06/2020                        <str name="entry_date">202060</str>
13720             25/03/2020                        <str name="entry_date">202032</str>
276111            18/05/2020                        <str name="entry_date">202051</str>
```

**Comment by botturam** [comment]
Problema de formatação da data foi resolvido e está em produção. Abaixo, 1 exemplo; mais abaixo, a lista dos docs LILACS.

  <doc boost="27">
    <field name="id">**covidwho-13720**</field>
    <field name="cc">BR91.2</field>
    <field name="bvs">regional</field>
    <field name="db">LILACS</field>
    <field name="db">SES-SP</field>
    <field name="db">SESSP-ACVSES</field>
    <field name="collection_ses">acervo_geral</field>
    <field name="instance">SES-SP</field>
    <field name="instance">aps</field>
    <field name="db">SESSP-IALPROD</field>
    <field name="db">SES-SP</field>
    <field name="collection_ses">producao_cientifica</field>
    <field name="instance">regional</field>
    <field name="instance">SES-SP</field>
    <field name="instance">aps</field>
    <field name="instance">regional</field>
    <field name="instance">regional</field>
    <field name="instance">ghl</field>
    <field name="instance">fronteriza</field>
    <field name="instance">bvsespana</field>
    <field name="instance">carpha</field>
    <field name="instance">paraguay</field>
    <field name="instance">panama</field>
    <field name="instance">conass</field>
    <field name="instance">saude_indigena</field>
    <field name="instance">bvsms</field>
    <field name="collection">04-international_org</field>
    <field name="type">non-conventional</field>
    <field name="nivel_tratamento">m</field>
    <field name="ur">http://fi-admin.bvsalud.org/document/view/mtvzn</field>
    <field name="au">São Paulo (Estado) Secretaria da Saúde. Instituto Adolfo Lutz</field>
    <field name="ti_pt">Protocolo laboratorial para a coleta, acondicionamento e transporte de amostras biológicas para investigação de covid-19</field>
    <field name="ti_en">Laboratory protocol for the collection, packaging and transport of biological samples for investigation of covid-19</field>
    <field name="pg">9</field>
    <field name="fo">São Paulo; SES/SP; 2020. 9 p. ilus.</field>
    <field name="la">pt</field>
    <field name="pu">SES/SP</field>
    <field name="dp">2020</field>
    <field name="cy">São Paulo</field>
    <field name="cp">BR</field>
    <field name="cp">BRASIL</field>
    <field name="cp">BRAZIL</field>
    <field name="cp">BRASIL</field>
    <field name="cp">BRESIL</field>
    <field name="cp">BRASILE</field>
    <field name="da">202000</field>
    <field name="mj">^d31543</field>
    <field name="mj">^d31619</field>
    <field name="mj">^d56929</field>
    <field name="ano_publicacao">2020</field>
    <field name="carpha_geral">geral</field>
    <field name="carpha_language">outros</field>
    <field name="fulltext">1</field>
<field name="weight">27</field>
<field name="entry_date">**20200325**</field>
<field name="update_date">20200318</field>
<field name="dp_ym">202000202000</field>
<field name="nro_month">00060006</field>
    <field name="regional_office">paho</field>
    <field name="id_pk">1052889</field>
  </doc>

Docs LILACS já corrigidos:

    <field name="id">covidwho-526397</field>
    <field name="id">covidwho-526126</field>
    <field name="id">covidwho-526125</field>
    <field name="id">covidwho-526124</field>
    <field name="id">covidwho-526123</field>
    <field name="id">covidwho-526122</field>
    <field name="id">covidwho-526062</field>
    <field name="id">covidwho-526059</field>
    <field name="id">covidwho-525988</field>
    <field name="id">covidwho-525863</field>
    <field name="id">covidwho-525860</field>
    <field name="id">covidwho-525843</field>
    <field name="id">covidwho-525638</field>
    <field name="id">covidwho-437999</field>
    <field name="id">covidwho-437630</field>
    <field name="id">covidwho-326028</field>
    <field name="id">covidwho-326027</field>
    <field name="id">covidwho-326024</field>
    <field name="id">covidwho-325282</field>
    <field name="id">covidwho-324945</field>
    <field name="id">covidwho-324944</field>
    <field name="id">covidwho-276111</field>
    <field name="id">covidwho-276103</field>
    <field name="id">covidwho-276102</field>
    <field name="id">covidwho-276101</field>
    <field name="id">covidwho-276100</field>
    <field name="id">covidwho-276099</field>
    <field name="id">covidwho-221171</field>
    <field name="id">covidwho-221115</field>
    <field name="id">covidwho-221114</field>
    <field name="id">covidwho-221101</field>
    <field name="id">covidwho-221083</field>
    <field name="id">covidwho-221037</field>
    <field name="id">covidwho-221036</field>
    <field name="id">covidwho-221010</field>
    <field name="id">covidwho-221004</field>
    <field name="id">covidwho-221001</field>
    <field name="id">covidwho-220998</field>
    <field name="id">covidwho-220997</field>
    <field name="id">covidwho-164991</field>
    <field name="id">covidwho-153972</field>
    <field name="id">covidwho-153445</field>
    <field name="id">covidwho-153444</field>
    <field name="id">covidwho-143468</field>
    <field name="id">covidwho-143114</field>
    <field name="id">covidwho-142232</field>
    <field name="id">covidwho-142007</field>
    <field name="id">covidwho-133107</field>
    <field name="id">covidwho-133096</field>
    <field name="id">covidwho-88335</field>
    <field name="id">covidwho-87689</field>
    <field name="id">covidwho-87625</field>
    <field name="id">covidwho-87624</field>
    <field name="id">covidwho-87355</field>
    <field name="id">covidwho-72206</field>
    <field name="id">covidwho-71645</field>
    <field name="id">covidwho-71644</field>
    <field name="id">covidwho-71426</field>
    <field name="id">covidwho-66089</field>
    <field name="id">covidwho-66069</field>
    <field name="id">covidwho-59997</field>
    <field name="id">covidwho-59976</field>
    <field name="id">covidwho-59726</field>
    <field name="id">covidwho-59725</field>
    <field name="id">covidwho-59664</field>
    <field name="id">covidwho-59663</field>
    <field name="id">covidwho-59655</field>
    <field name="id">covidwho-59654</field>
    <field name="id">covidwho-59653</field>
    <field name="id">covidwho-59625</field>
    <field name="id">covidwho-52420</field>
    <field name="id">covidwho-47682</field>
    <field name="id">covidwho-46350</field>
    <field name="id">covidwho-19243</field>
    <field name="id">covidwho-13720</field>
    <field name="id">covidwho-9988</field>
    <field name="id">covidwho-9496</field>
    <field name="id">covidwho-1802</field>
    <field name="id">covidwho-1797</field>
    <field name="id">covidwho-937</field>
    <field name="id">covidwho-801</field>

**Comment by botturam** [comment]
O problema de formatação da data foi resolvido e já está em produção. Abaixo segue 1 exemplo:

  <doc boost="27">
    <field name="id">covidwho-13720</field>
    <field name="cc">BR91.2</field>
    <field name="bvs">regional</field>
    <field name="db">LILACS</field>
    <field name="db">SES-SP</field>
    <field name="db">SESSP-ACVSES</field>
    <field name="collection_ses">acervo_geral</field>
    <field name="instance">SES-SP</field>
    <field name="instance">aps</field>
    <field name="db">SESSP-IALPROD</field>
    <field name="db">SES-SP</field>
    <field name="collection_ses">producao_cientifica</field>
    <field name="instance">regional</field>
    <field name="instance">SES-SP</field>
    <field name="instance">aps</field>
    <field name="instance">regional</field>
    <field name="instance">regional</field>
    <field name="instance">ghl</field>
    <field name="instance">fronteriza</field>
    <field name="instance">bvsespana</field>
    <field name="instance">carpha</field>
    <field name="instance">paraguay</field>
    <field name="instance">panama</field>
    <field name="instance">conass</field>
    <field name="instance">saude_indigena</field>
    <field name="instance">bvsms</field>
    <field name="collection">04-international_org</field>
    <field name="type">non-conventional</field>
    <field name="nivel_tratamento">m</field>
    <field name="ur">http://fi-admin.bvsalud.org/document/view/mtvzn</field>
    <field name="au">São Paulo (Estado) Secretaria da Saúde. Instituto Adolfo Lutz</field>
    <field name="ti_pt">Protocolo laboratorial para a coleta, acondicionamento e transporte de amostras biológicas para investigação de covid-19</field>
    <field name="ti_en">Laboratory protocol for the collection, packaging and transport of biological samples for investigation of covid-19</field>
    <field name="pg">9</field>
    <field name="fo">São Paulo; SES/SP; 2020. 9 p. ilus.</field>
    <field name="la">pt</field>
    <field name="pu">SES/SP</field>
    <field name="dp">2020</field>
    <field name="cy">São Paulo</field>
    <field name="cp">BR</field>
    <field name="cp">BRASIL</field>
    <field name="cp">BRAZIL</field>
    <field name="cp">BRASIL</field>
    <field name="cp">BRESIL</field>
    <field name="cp">BRASILE</field>
    <field name="da">202000</field>
    <field name="mj">^d31543</field>
    <field name="mj">^d31619</field>
    <field name="mj">^d56929</field>
    <field name="ano_publicacao">2020</field>
    <field name="carpha_geral">geral</field>
    <field name="carpha_language">outros</field>
    <field name="fulltext">1</field>
<field name="weight">27</field>
<field name="entry_date">20200325</field>
<field name="update_date">20200318</field>
<field name="dp_ym">202000202000</field>
<field name="nro_month">00060006</field>
    <field name="regional_office">paho</field>
    <field name="id_pk">1052889</field>
  </doc>

**Comment by botturam** [comment]
O problema de formatação da data foi resolvido e já está em produção. Abaixo segue 1 exemplo:

    <field name="id">covidwho-13720</field>
    <field name="entry_date">20200325</field>

**Comment by botturam** [comment]
A lista completa de ids:

    <field name="id">covidwho-526397</field>
    <field name="id">covidwho-526126</field>
    <field name="id">covidwho-526125</field>
    <field name="id">covidwho-526124</field>
    <field name="id">covidwho-526123</field>
    <field name="id">covidwho-526122</field>
    <field name="id">covidwho-526062</field>
    <field name="id">covidwho-526059</field>
    <field name="id">covidwho-525988</field>
    <field name="id">covidwho-525863</field>
    <field name="id">covidwho-525860</field>
    <field name="id">covidwho-525843</field>
    <field name="id">covidwho-525638</field>
    <field name="id">covidwho-437999</field>
    <field name="id">covidwho-437630</field>
    <field name="id">covidwho-326028</field>
    <field name="id">covidwho-326027</field>
    <field name="id">covidwho-326024</field>
    <field name="id">covidwho-325282</field>
    <field name="id">covidwho-324945</field>
    <field name="id">covidwho-324944</field>
    <field name="id">covidwho-276111</field>
    <field name="id">covidwho-276103</field>
    <field name="id">covidwho-276102</field>
    <field name="id">covidwho-276101</field>
    <field name="id">covidwho-276100</field>
    <field name="id">covidwho-276099</field>
    <field name="id">covidwho-221171</field>
    <field name="id">covidwho-221115</field>
    <field name="id">covidwho-221114</field>
    <field name="id">covidwho-221101</field>
    <field name="id">covidwho-221083</field>
    <field name="id">covidwho-221037</field>
    <field name="id">covidwho-221036</field>
    <field name="id">covidwho-221010</field>
    <field name="id">covidwho-221004</field>
    <field name="id">covidwho-221001</field>
    <field name="id">covidwho-220998</field>
    <field name="id">covidwho-220997</field>
    <field name="id">covidwho-164991</field>
    <field name="id">covidwho-153972</field>
    <field name="id">covidwho-153445</field>
    <field name="id">covidwho-153444</field>
    <field name="id">covidwho-143468</field>
    <field name="id">covidwho-143114</field>
    <field name="id">covidwho-142232</field>
    <field name="id">covidwho-142007</field>
    <field name="id">covidwho-133107</field>
    <field name="id">covidwho-133096</field>
    <field name="id">covidwho-88335</field>
    <field name="id">covidwho-87689</field>
    <field name="id">covidwho-87625</field>
    <field name="id">covidwho-87624</field>
    <field name="id">covidwho-87355</field>
    <field name="id">covidwho-72206</field>
    <field name="id">covidwho-71645</field>
    <field name="id">covidwho-71644</field>
    <field name="id">covidwho-71426</field>
    <field name="id">covidwho-66089</field>
    <field name="id">covidwho-66069</field>
    <field name="id">covidwho-59997</field>
    <field name="id">covidwho-59976</field>
    <field name="id">covidwho-59726</field>
    <field name="id">covidwho-59725</field>
    <field name="id">covidwho-59664</field>
    <field name="id">covidwho-59663</field>
    <field name="id">covidwho-59655</field>
    <field name="id">covidwho-59654</field>
    <field name="id">covidwho-59653</field>
    <field name="id">covidwho-59625</field>
    <field name="id">covidwho-52420</field>
    <field name="id">covidwho-47682</field>
    <field name="id">covidwho-46350</field>
    <field name="id">covidwho-19243</field>
    <field name="id">covidwho-13720</field>
    <field name="id">covidwho-9988</field>
    <field name="id">covidwho-9496</field>
    <field name="id">covidwho-1802</field>
    <field name="id">covidwho-1797</field>
    <field name="id">covidwho-937</field>
    <field name="id">covidwho-801</field>

**Comment by botturam** [comment]
disponível em produção.
