### ISSUE TITLE
Verificar a devida inclusão de Notes e Translated title

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#317]
Para Notes - definir ocorrência como campo 83 e subcampo ^izh

Para Translated title - definir ocorrência como campo 12 e subcampo ^izh

**Comment by falbrito** [comment]
Luciano, estou analisando aqui e parece que estão faltando algumas colunas em arquivos csv Chinês
Em /bases/oai.pmh/csv.rec/DistillerSR-zh
1) who-covid-19-repo-export2iAHxProcessingOnlyAbstract-zh.csv (Com novo campo "Notes")
está com CovNum;Abstract apenas

2) who-covid-19-repo-export2iAHxProcessingOnlyTitle-zh.csv (Com novo campo "Translated Title")
está com CovNum;Title apenas

**Comment by dossanluc** [comment]
O processo de carga foi corrigido e os arquivos estão disponíveis no servidor ServerOfi5
/bases/oai.pmh/csv.rec/DistillerSR-zh

**Comment by falbrito** [comment]
Realizado.
