### ISSUE TITLE
Criar tratamento no conteúdo de autor para processamento Chinês

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#319]
O campo de autor existente no arquivo **who-covid-19-repo-export2iAHxProcessingOnlyAuthors-zh.csv**, mostra 2 tipos de situação para ser realizado tratamento, considerando que utilizaremos a coluna 2, e que as colunas estão divididas por ponto e vírgula.

1) Quando ocorrer na linha a sequência de 2 vírgulas ", ,", deverá ser trocado por pipe "|"

```
Ex.:
CovNum;Authors;Translated Author
1;Bai,  Jun, ,Zhou,  Jie, ,Ma,  Wanling, ,Ji,  Bingyuan, ,Xiang,  Ziyun,;白君

Deverá ser transformado em:
1;Bai,  Jun|Zhou,  Jie|Ma,  Wanling|Ji,  Bingyuan|Xiang,  Ziyun,;白君

```
2) Depois de realizada substituição acima, quando não houver pipe, haverão autores na escrita chinesa, então substituir nesse tipo de linha, a vírgula "," por pipe "|"

```
Ex.:
CovNum;Authors;Translated Author
13;唐凌,李少滨,袁敏,张天嵩,徐诚,吴银根,方泓;

Deverá ser transformado em:
13;唐凌|李少滨|袁敏|张天嵩|徐诚|吴银根|方泓;

```

**Comment by dossanluc** [comment]
No processo de carga e transformação de dados para os arquivos CSVs, foram realizados os ajuste solicitados.

**Comment by falbrito** [comment]
* Foi constatado que a linha exemplificada no item 1 estava com erro. Dessa forma o problema das 2 vírgulas não existe.
Por hora foi convencionado que a separação dos campos será feito por pipe "|".

* Em relação a tradução dos autores, seguindo o cabeçalho do arquivo CSV ( CovNum;Authors;Translated Author), o conteúdo da coluna 2 e 3 não definem qual coluna deve ser utilizada para "Authors" e "Translated Author".  Na coluna 2 e 3 aparecem tanto na escrita chinesa quanto no formato alfabético. Dessa forma, optou-se por considerar somente a coluna 2 para utilização, que possue quase que na totalidade o conteúdo em chinês.
