### ISSUE TITLE
Adaptar processamento da HISA de acordo com a nova arquitetura de scripts criada

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#32]

**Comment by santosfj** [comment]
Tabela de controle de coletas atualizada com as informações de coleta de HISA
Pos-coleta específica pronta e testada

**Comment by santosfj** [comment]
Fica faltando o saneamento específico de HISA, caso seja necessário (MB vai informar se e o que), o restante todo ok (coletas.tab; coleta_wget; pos_coleta_his; pre_saneamento_fi; iah_like_lilacs; iahh)
