### ISSUE TITLE
Criar o Processo do Preprints da FIOCRUZ 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#324]
Criar o processo de Preprints da FIOCRUZ aproveitando a coleta do ARCA. 

- Fazer o Filtro para separar os registros do Preprints;
- Criar o processo de saneamento like LILACS ;
- Criar o Processo de geração do XML do iaHx;;

**Comment by falbrito** [comment]
Processo criado, aguardando OK para colocar em produção.

**Comment by anakatiacamilo** [comment]
@renatomurasaki  Podemos publicar os registro de Preprints da FIOCRUZ?

**Comment by renatomurasaki** [comment]
@anakatiacamilo e @falbrito - me confirmem se estes registros estão corretamente marcados para pertecerem aos clusters Coleção: Preprints e Base de dados: Fiocruz preprints.

Se assim estiver, podemos seguir em frente, uma vez que o disclaimer já está funcionando.

**Comment by anakatiacamilo** [comment]
@renatomurasaki esta no mesmo padrão do SciELO Preprints, podendo seguir eu peço a tradução do cluster da base de dados
    <field name="bvs">regional</field>
    <field name="db">PREPRINT-SCIELO</field>
    <field name="instance">regional</field>
    <field name="collection">09-preprints</field>


    <field name="bvs">regional</field>
    <field name="db">PREPRINT-FIOCRUZ</field>
    <field name="instance">regional</field>
    <field name="collection">09-preprints</field>

**Comment by renatomurasaki** [comment]
@anakatiacamilo OK. Avise-me assim que estiver disponível, por favor.

**Comment by falbrito** [comment]
Colocado em linha e agurdando processamento.

**Comment by botturam** [comment]
Disponível em produção. 

Falta traduzir o label PREPRINT-FIOCRUZ para Fiocruz preprints (cluster db)
