### ISSUE TITLE
Documentos sem título na base COVID-WHO

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/db-processing#326]
@botturam, favor verificar lista abaixo de IDs que estão sem o elemento "ti" no índice Solr e consequentemente não apresentam título na interface pública e na exportação:

covidwho-46328
covidwho-593228
covidwho-174769
covidwho-164990
covidwho-164989
covidwho-164988
covidwho-143027
covidwho-143026
covidwho-142694
covidwho-142667
covidwho-124624
covidwho-124623
covidwho-87095
covidwho-31552
covidwho-1549

Obrigado.

**Comment by botturam** [comment]
Olhei em serverofi5:/bases/oai.pmh/csv.rec/covidwho/*.csv e parece que não vem o título mesmo. Vou pedir ao Fábio para dar uma olhada.

-rw-rw-r--  1 operacao operacao  1741403 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessing.csv
-rw-rw-r--  1 operacao operacao 31953216 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessingOnlyAbstract.csv
-rw-r-----  1 operacao operacao  2116796 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessingOnlyAbstract-zh.csv
-rw-rw-r--  1 operacao operacao  4240384 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessingOnlyAuthors.csv
-rw-r-----  1 operacao operacao    71469 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessingOnlyAuthors-zh.csv
-rw-rw-r--  1 operacao operacao  1467233 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessingOnlyDOI.csv
-rw-r-----  1 operacao operacao     8971 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessingOnlyDOI-zh.csv
-rw-rw-r--  1 operacao operacao  2193601 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessingOnlyFullTextLink.csv
-rw-r-----  1 operacao operacao    10436 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessingOnlyFullTextLink-zh.csv
-rw-rw-r--  1 operacao operacao  1746509 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessingOnlyJournal.csv
-rw-r-----  1 operacao operacao    28524 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessingOnlyJournal-zh.csv
-rw-rw-r--  1 operacao operacao   694591 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessingOnlyNewIDFields.csv
-rw-r-----  1 operacao operacao     9808 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessingOnlyNewIDFields-zh.csv
-rw-rw-r--  1 operacao operacao   558207 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessingOnlyTags.csv
-rw-r-----  1 operacao operacao    68493 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessingOnlyTags-zh.csv
-rw-rw-r--  1 operacao operacao  4601437 Jul 20 14:15 who-covid-19-repo-export2iAHxProcessingOnlyTitle.csv
-rw-r-----  1 operacao operacao   178353 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessingOnlyTitle-zh.csv
-rw-r-----  1 operacao operacao    33506 Jul 20 14:20 who-covid-19-repo-export2iAHxProcessing-zh.csv

**Comment by renatomurasaki** [comment]
Olhando o arquivo Excel (raw data), o únicos que realmente tem título é o seguinte

covidwho-46328
> Refid | Author | Title
> 46328 | Schiariti, Verónica | 突發公共衛生事件期間身心障礙兒童的人權: 挑战 冠状病毒病

O mais estranho @botturam é que este registro está marcado como Medline e deveria ter sido enriquecido, a não ser que no registro MDL tampouco tenha título.

Vou solicitar a equipe da OMS revisar os demais.

**Comment by botturam** [comment]
Esse documento foi enriquecido, mas não tem título no PUBMED.

PMID: 32277488
Editorial Dev Med Child Neurol. 2020 Jun;62(6):E1. doi: 10.1111/dmcn.14527. Epub 2020 Apr 10.
[No title available]
Verónica Schiariti
PMID: 32277488 DOI: 10.1111/dmcn.14527
No abstract available

**Comment by botturam** [comment]
Peguei um outro, ao acaso, e parece que tem repetições, uma delas (a última), sem título:

mfn= 24569
  2  "399016"
  5  "S"
  6  "as"
 10  "Nau, J. Y."
 30  "Revue medicale suisse"
 64  "2020"
 65  "20200000"
 91  "20200529"
776  "WHO^i399016"
933  "Revue medicale suisse;16(691):800-801, 2020."
1001  "399016"
1002  "2020"
1004  "16"
1005  "691"
1006  "800-801"
1008  "29/05/2020"
 12  "Covid-19, dans les brouillards de l’hydroxychloroquine (3)"
..
mfn= 24570
  2  "399015"
  5  "S"
  6  "as"
 10  "Nau, J. Y."
 30  "Revue medicale suisse"
 64  "2020"
 65  "20200000"
 91  "20200529"
776  "WHO^i399015"
933  "Revue medicale suisse;16(690):756-757, 2020."
1001  "399015"
1002  "2020"
1004  "16"
1005  "690"
1006  "756-757"
1008  "29/05/2020"
 12  "Covid-19, dans les brouillards de l’hydroxychloroquine (2)"
..
mfn= 33077
  2  "208510"
  5  "S"
  6  "as"
 10  "Nau, J. Y."
 30  "Revue medicale suisse"
 64  "2020"
 65  "20200000"
 83  "Poursuivons notre chronique de « l’affaire de la chloroquine »,1 une polémique désormais multiforme et internationale après avoir été, en France, déclenchée et alimentée par le Pr Didier Raoult (Institut hospitalo-universitaire Méditerranée, Marseille)  L’affaire a soudain, ces derniers jours, pris une nouvelle dimension, étrangement politique  Ce fut, le 9 avril, la visite surprise, scénarisée et amplement médiatisée du Président de la République au Pr Raoult, directeur controversé de l’IHU-Méditerranée de Marseille  Et ce alors même que ce dernier est désormais vivement et ouvertement critiqué par le « Conseil scientifique » chargé de conseiller le gouvernement dans la lutte contre le Covid-19 et constitué à la demande du Président de la République"
 91  "20200511"
776  "WHO^i208510"
933  "Revue medicale suisse;16(N 6912):876-877, 2020."
1001  "208510"
1002  "2020"
1004  "16"
1005  "N 6912"
1006  "876-877"
1008  "11/05/2020"
 12  "COVID-19, dans les brouillards de l’hydroxychloroquine"
..
mfn= 38295
  2  "116446"
  5  "S"
  6  "as"
 10  "Nau, Jean Yves"
 30  "Revue medicale suisse"
 64  "2020"
 65  "20200000"
 91  "20200427"
776  "WHO^i116446"
933  "Revue medicale suisse;16(689):704-705, 2020."
1001  "116446"
1002  "2020"
1004  "16"
1005  "689"
1006  "704-705"
1008  "27/04/2020"
 12  "Covid-19, dans les brouillards français de l’hydroxychloroquine"
..
mfn= 42890
  2  "46491"
  5  "S"
  6  "as"
 10  "Nau, Jean-Yves"
 30  "Revue medicale suisse TT - Covid-19, dans les brouillards francais de lhydroxychloroquine."
 64  "2020"
 65  "20200000"
 91  "20200414"
776  "WHO^i46491"
933  "Revue medicale suisse TT - Covid-19, dans les brouillards francais de lhydroxychloroquine.;16(689):704-705, 2020."
1001  "46491"
1002  "2020"
1004  "16"
1005  "689"
1006  "704-705"
1008  "14/04/2020"
 12  "No Title"

**Comment by botturam** [comment]
Todos IDs acima parecem ser da mesma revista: Revue medicale suisse, e parecem ser documentos duplicados entre eles.

mfn= 24569
  2  "399016"
  5  "S"
  6  "as"
 10  "Nau, J. Y."
 30  "Revue medicale suisse"
 64  "2020"
 65  "20200000"
 91  "20200529"
776  "WHO^i399016"
933  "Revue medicale suisse;16(691):800-801, 2020."
1001  "399016"
1002  "2020"
1004  "16"
1005  "691"
1006  "800-801"
1008  "29/05/2020"
 12  "Covid-19, dans les brouillards de l’hydroxychloroquine (3)"
..
mfn= 24570
  2  "399015"
  5  "S"
  6  "as"
 10  "Nau, J. Y."
 30  "Revue medicale suisse"
 64  "2020"
 65  "20200000"
 91  "20200529"
776  "WHO^i399015"
933  "Revue medicale suisse;16(690):756-757, 2020."
1001  "399015"
1002  "2020"
1004  "16"
1005  "690"
1006  "756-757"
1008  "29/05/2020"
 12  "Covid-19, dans les brouillards de l’hydroxychloroquine (2)"
..
mfn= 33077
  2  "208510"
  5  "S"
  6  "as"
 10  "Nau, J. Y."
 30  "Revue medicale suisse"
 64  "2020"
 65  "20200000"
 83  "Poursuivons notre chronique de « l’affaire de la chloroquine »,1 une polémique désormais multiforme et internationale après avoir été, en France, déclenchée et alimentée par le Pr Didier Raoult (Institut hospitalo-universitaire Méditerranée, Marseille)  L’affaire a soudain, ces derniers jours, pris une nouvelle dimension, étrangement politique  Ce fut, le 9 avril, la visite surprise, scénarisée et amplement médiatisée du Président de la République au Pr Raoult, directeur controversé de l’IHU-Méditerranée de Marseille  Et ce alors même que ce dernier est désormais vivement et ouvertement critiqué par le « Conseil scientifique » chargé de conseiller le gouvernement dans la lutte contre le Covid-19 et constitué à la demande du Président de la République"
 91  "20200511"
776  "WHO^i208510"
933  "Revue medicale suisse;16(N 6912):876-877, 2020."
1001  "208510"
1002  "2020"
1004  "16"
1005  "N 6912"
1006  "876-877"
1008  "11/05/2020"
 12  "COVID-19, dans les brouillards de l’hydroxychloroquine"
..
mfn= 38295
  2  "116446"
  5  "S"
  6  "as"
 10  "Nau, Jean Yves"
 30  "Revue medicale suisse"
 64  "2020"
 65  "20200000"
 91  "20200427"
776  "WHO^i116446"
933  "Revue medicale suisse;16(689):704-705, 2020."
1001  "116446"
1002  "2020"
1004  "16"
1005  "689"
1006  "704-705"
1008  "27/04/2020"
 12  "Covid-19, dans les brouillards français de l’hydroxychloroquine"
..
mfn= 42890
  2  "46491"
  5  "S"
  6  "as"
 10  "Nau, Jean-Yves"
 30  "Revue medicale suisse TT - Covid-19, dans les brouillards francais de lhydroxychloroquine."
 64  "2020"
 65  "20200000"
 91  "20200414"
776  "WHO^i46491"
933  "Revue medicale suisse TT - Covid-19, dans les brouillards francais de lhydroxychloroquine.;16(689):704-705, 2020."
1001  "46491"
1002  "2020"
1004  "16"
1005  "689"
1006  "704-705"
1008  "14/04/2020"
 12  "No Title"

**Comment by renatomurasaki** [comment]
@botturam pior que não são... buscando no Google dá pra ver que são versões diferentes (2) / (3) / (4) - o mesmo número que mostra no final do título

**Comment by renatomurasaki** [comment]
Os MFN 38295 e 42890 realmente parecem ser duplicados

**Comment by renatomurasaki** [comment]
Entende-se que os títulos aparecerão quando estes documentos forem atualizados no Medline. A questão de duplicação está sendo tratada a parte.
