### ISSUE TITLE
Deixar a coleta do SES-SP somente com os registros do FI-ADMIN

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#327]
- [x] Marcar/incluis registros no FI-ADMIN;

- [x] Coleta de IDS específicos; 

- [x] Atualizar fiadmin.iso;

- [x] Filtrar a base temática;

- [x] Ajustar coletas.tab;

- [x] Rodar processamento para criação de XML.

**Comment by anakatiacamilo** [comment]
Feito por @falbrito  e @anakatiacamilo. Aguardando processamento.
@anakatiacamilo Analisar 159 registros com problemas de coleta nos registros da SES-SP.

**Comment by botturam** [comment]
processamento em andamento. Ficará pronto para a atualização de 4f, 06:00

**Comment by botturam** [comment]
disponível em produção.

**Comment by botturam** [comment]
concluído
