### ISSUE TITLE
Criar prefixo com código para Contexto de Saúde e Tema de Saúde

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#329]
Para filtrar os temas de saúde a partir do contexto, na interface wizard, será necessário implementar um código como prefixo para os valores de ambos os clusters.

Exemplo:

ATUAL
tag_contexto:("ASSA2030_WIZARD")
tag_tema_saude:("accidentes_transito")

COMO DEVE FICAR
tag_contexto:("1_ASSA2030_WIZARD")
tag_tema_saude:("1_accidentes_transito")

**Comment by botturam** [comment]
Disponível em produção, mas sem o número no segundo campo, conforme acerto que fiz com o Vinícius. Então ficou:

tag_contexto:("1_ASSA2030_WIZARD")
tag_tema_saude:("accidentes_transito")

**Comment by botturam** [comment]
com uma correção em tag_tema_saude, ficou:

tag_contexto:("1_ASSA2030_WIZARD")
tag_tema_saude:("1_accidentes_transito")

disponível, parcialmente, em homolgação e produção

**Comment by botturam** [comment]
processar MEDLINE full...
