### ISSUE TITLE
Confirmar se o dado do campo entry_date da base Chinesa está sendo populado corretamente

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#330]
@falbrito @botturam percebi que todos os registros da base chinesa estão com o mesmo entry_date: 20200724.

Por favor, revisem o processo para termos certeza que isso está correto.

**Comment by falbrito** [comment]
@renatomurasaki, sim a data apresentada no arquivo CSV who-covid-19-repo-export2iAHxProcessing-zh.csv é a mesma em todos os registros.

E está **14/07/2020** - totalizando 988 ocorrências

```
operacao@serverofi5:/bases/oai.pmh/csv.rec/covidwho $ mx seq=who-covid-19-repo-export2iAHxProcessing-zh.csv";"
mfn=     1 
  1  "CovNum"
  2  "Published Year"
  3  "Published Month"
  4  "Volume"
  5  "Issue"
  6  "Pages"
  7  "Accession Number"
  8  "Date Added"
" 9  "PublishDate
..
mfn=     2 
  1  "1"
  2  "2020"
  3  "04"
  6  "1-4"
  8  "14/07/2020"
" 9  "15/04/2020
..x
operacao@serverofi5:/bases/oai.pmh/csv.rec/covidwho $ mx x "tab=(v8/)" now
999999011|988|14/07/2020
999999998|1|Date Added

```

**Comment by renatomurasaki** [comment]
Fabinho, 14/07/2020 me parece correto. Então algo precisa ser ajustado no processamento da base chinesa, pois inseriu a data de 24/07/2020, quando a mesma entrou no processo diário de atualização. Veja o XML do iAHx:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?output=xml&lang=en&from=0&sort=&format=summary&count=20&fb=&page=1&skfp=&index=tw&q=

Todos os registros tem o elemento `<str name="entry_date">20200724</str>`

**Comment by falbrito** [comment]
Renato, os registros em questão são oriundos da base COVIDWHO ( who-repo4covid-biblio.xlsx ) e não da base exclusiva de Chinês CNKI_Lanzhou.

A base COVIDWHO possui registros em Chinês, Japonês e outros idiomas também
![image](https://user-images.githubusercontent.com/6940371/88574594-f1a2eb00-d018-11ea-9b58-6a0644bd4f09.png)

**Comment by renatomurasaki** [comment]
@falbrito obrigado e desculpe-me. O filtro não estava aplicado para a base chinesa. Desconsiderar. Forte abraço,!
