### ISSUE TITLE
ODS3-Acabar com mortes prematuras devido doenças não transmissíveis

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#332]
[Acabar com mortes prematuras devido doenças não transmissíveis.txt](https://github.com/bireme/db-processing/files/5003401/Acabar.com.mortes.prematuras.devido.doencas.nao.transmissiveis.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
Disponível em produção como `tag_contexto:("2_ODS3") AND tag_tema_saude:("2_muertes_prematuras_enfermedades_notrasmisibles") `
