### ISSUE TITLE
ODS3-Prevenção e tratamento do consumo de substâncias psicoativas

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#333]
[Prevenção e tratamento do consumo de substâncias psicoativas.txt](https://github.com/bireme/db-processing/files/5003429/Prevencao.e.tratamento.do.consumo.de.substancias.psicoativas.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção.
