### ISSUE TITLE
Processamento de dados do ORCID (atributo k) e Web of Science ResearcherID (atributo s) dos registros bibliográficos para apresentação no iAHx da BVS Regional

### ISSUE THREAD

**Issue by suelisuga** [bireme/db-processing#343]
Prezados @falbrito e @botturam ,

Solicito coleta e processamento do número persistente do autor dos registros bibliográficos do FI-Admin para apresentação no iAHx da BVS Regional.

Atributos:
k - ORCID
s - Web of Science ResearcherID

Atributos presentes nos campos:
Nível série - autor pessoal [10]
Nível monográfico - autor pessoal [16]
Nível coleção - autor pessoal [23]

Espera-se que esse dado seja mais frequentemente encontrado em artigos de periódicos, porém já foram solicitadas a inclusão nos outros tipos, conforme os chamados a seguir:

https://github.com/bireme/fi-admin/issues/236
Criar atributo k (Identificador de Autor) para Autor Pessoal (autor pessoal - 10) #236

https://github.com/bireme/fi-admin/issues/1126
Criar subcampo para número persistente de autor (ORCID => atributo k e Web of Science ResearcherID => atributo s | nível monográfico - campo 16 #1126

https://github.com/bireme/fi-admin/issues/1127
Criar subcampo para número persistente de autor (ORCID => atributo k e Web of Science ResearcherID => atributo s | nível coleção - campo 23 #1127

Muito obrigada!
Sueli

**Comment by falbrito** [comment]
@suelisuga, conforme verificamos o subcampo ^k só ocorre para o campo 10, para 16 e 23 não ocorre.

Para o subcampo ^s, identificamos que já está sendo utilizado com outro fim, possivelmente para preenchimento de estado.

**Comment by botturam** [comment]
MEDLINE: ORCID está no campo v372^u, mas falta normalizar. Ex:
https://orcid.org/0000-0002-0601-8127
https://orcid.org/0000-0001-5615-3442
0000-0002-0682-6036
https://orcid.org/0000-0002-9422-4245
0000-0002-6288-8821
0000-0002-6869-2870

LILACS: ORCID está no v10^k, está normalizado. Ex:
0000-0003-4533-0129
0000-0001-6830-4914
0000-0002-2709-6335

**Comment by botturam** [comment]
1) ORCID - Campo "orcid" inserido em:

    a)  tabs/bvs_reg_XML.pft (LILACS):
         ( if p(v10^k) then '    <field name="orcid">'if p(v10^k) then ||v10^k|| fi'</field>'/,fi),

    b) tabs/bvs_mdl_XML.pft (MEDLINE):
         (if p(v372^u) then
              |    <field name="orcid">|v372^u|</field>|/
         ,fi),

2) Web of Sciense (wosid) - inserir nos mesmos moldes que ORCID

**Comment by botturam** [comment]
Com relação ao /home/javaapps/iahx-server/indexes/solr5-port6/portal/conf/schema.xml  declarar o novo campo:

<field name="'''orcid'''"                       type="string"                   indexed="true"   stored="true" />

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
mudança no nome do Author Identifier (até o momento era apenas ORCID):

de **orcid** para **auid**

**Comment by botturam** [comment]
Inseridos 2 campos no processamento do Portal-regional (e Brasil, Hanseníase, Homeopatia, etc.)
pesquisa orcid e wosid:
<field name="auid" type="string" indexed="true" stored="true" multiValued="true" />
pesquisa doi:
<field name="aid" type="string" indexed="true" stored="true" />

**Comment by botturam** [comment]
em processamento...

**Comment by suelisuga** [comment]
@botturam e @falbrito
Boa tarde,

Somente para confirmar se estou entendendo bem o processamento em criação:

1. os atributos **k** (Orcid) e **w** (Web of Science ResearcherID) estão sendo coletados dos campos [10], [13] e [26] (Autor pessoal para serie, monográfico e coleção)

2. o processamento mescla ambos conteúdos de **k** e **w**

3. geram um único índice que foi definido como **auid**

Se for isso que entendi, então é isso mesmo.

Sobre os atributos que ainda estão vazios, é esperado por enqto visto que os atributos não estavam disponíveis, mas gostaria que eles estivessem prontos e preparados para que quando o dado chegar, ele seja apresentado sem que precisemos revisar o processamento novamente.

Muito obrigada!

**Comment by suelisuga** [comment]
> 1. inserido em tabs/bvs_reg_XML.pft: (LILACS)
>    ( if p(v10^k) then '    <field name="**auid**">'if p(v10^k) then ||v10^k|| fi''/,fi),
> 2. inserido em tabs/bvs_mdl_XML.pft (MEDLINE)
>    (if p(v372^u) then |    <field name="**auid**">|v372^u||/,fi),
> 
> OBS: falta "**wosid**"

@botturam fiz o comentario acima por causa do p(v10^k).

Obrigada!

**Comment by botturam** [comment]
É isso mesmo, Sueli. Colocarei uma previsão para ^w (wos)

**Comment by botturam** [comment]
Já se encontra disponível em produção para pesquisar e mostrar.

Exemplo:

auid:"0000-0003-3504-118X"

**Comment by botturam** [comment]
Foi acrescentado para v16 e v23, além do v10 previamente colocado, os **^k** (ORKID) e **^w** (WOS):

( if p(v10^k) then '    <field name="auid">'if p(v10^k) then ||v10^k|| fi'</field>'/,fi),
( if p(v10^w) then '    <field name="auid">'if p(v10^w) then ||v10^w|| fi'</field>'/,fi),
                  ( if p(v16^k) then '    <field name="auid">'if p(v16^k) then ||v16^k|| fi'</field>'/,fi),
                  ( if p(v16^w) then '    <field name="auid">'if p(v16^w) then ||v10^6|| fi'</field>'/,fi),
                               ( if p(v23^k) then '    <field name="auid">'if p(v23^k) then ||v23^k|| fi'</field>'/,fi),
                               ( if p(v23^w) then '    <field name="auid">'if p(v23^w) then ||v23^w|| fi'</field>'/,fi),

**Comment by botturam** [comment]
Disponível em produção. Atividades totalmente concluídas.

**Comment by suelisuga** [comment]
muitíssimo obrigada @botturam e @falbrito !
