### ISSUE TITLE
Coleta e processamento do DOI para visualização no iAHx Regional (Portal Regional da BVS)

### ISSUE THREAD

**Issue by suelisuga** [bireme/db-processing#344]
Olá @botturam e @falbrito ,

Solicito inclusão do campo DOI de registros bibliográficos para coleta do FI-Admin e processamento para apresentação no iAHx Regional (Portal Regional da BVS)

Campo Número DOI [724]

Exemplo de valor: 10.1590/S0102-311X2008000500013 

O mesmo campo será criado para LIS e Multimedia pensando nas questões de dados de pesquisa e provavelmente solicitarei a mesma inclusão futuramente.

Muito obrigada!
Sueli

**Comment by falbrito** [comment]
@suelisuga, conforme verificamos já existe o campos v724 na bases isis e também no arquivo xml.

Base:
```
ex.:
724  "10.5585/ConsSaude.v14n2.5252"

```
Xml:
```
ex.:
<field name="doi">10.5585/ConsSaude.v14n2.5252</field>
```

**Comment by suelisuga** [comment]
@falbrito considerando que está disponível, vou encerrar esse chamado.

Ficou pendente eu criar o do LIS e Multimedia, que estou aguardando implantação do campo no FI-Admin
