### ISSUE TITLE
Tabular e depois normalizar o campo DOi (v724) na LILACS

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#347]
valores para substituição:

doi: http://doi.org/|
doi: https://doi.org/|
DOI: http://dx.doi.org/|
DOI: https://dx.doi.org/|
https://doi.org/|
http://doi.org/|
https://dx.doi.org/|
http://dx.doi.org/|
DOI: https://doi.org/|
DOI: http://doi.org/|
DOI: http://dx.doi.org/|
DOI: |
DOI: https://doi. org/|

Incluir gizmo no processamento regular da LILACS

**Comment by renatomurasaki** [comment]
@botturam @falbrito @viniciusandrade Entendo que o ideal seria retirar qualquer menção de URL e deixar neste campo somente o  identificador. O que acham? A regra de formação de URL fica na camada de apresentação.

**Comment by viniciusandrade** [comment]
De acordo.

A entrada de dados pelo FI-ADMIN já não permite iniciar o campo com letra e possui a seguinte mensagem de erro em caso de entrada inválida: "Por favor informe um número válido de DOI number. Ex. 10.1000/xyz123"

**Comment by botturam** [comment]
Disponível em produção
