### ISSUE TITLE
Coleta do Registros da IPEA

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#349]
@botturam, por favor, fazer a coleta do IPEA no dia 01/09 para inclusão dos dados no FI-ADMIN, poderíamos combinar essa coleta para todo o começo do mês?
Grata

**Comment by botturam** [comment]
coleta ainda com problema em:

http://bibliotecaweb.ipea.gov.br/oai/saude/oai.php?verb=ListRecords&metadataPrefix=oai_marcxml

**Comment by botturam** [comment]
está disponível nova coleta com 714 docs em serverofi5:/bases/oai.pmh/isis/ipe:

-rw-rw-r-- 1 operacao operacao 1461760 Oct 16 18:35 ipe_LILACS.mst 
-rw-rw-r-- 1 operacao operacao    3072 Oct 16 18:35 ipe_LILACS.xrf
