### ISSUE TITLE
Desenvovler processo de coleta de metadados a partir de "medRxiv"

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#351]
Motivação:

```
De: Murasaki, Renato (BIR)
Enviado: quarta-feira, 8 de julho de 2020 11:59
Assunto: JSON do medRxiv / bioRxiv somente para preprints COVID-19 / SARS-CoV-2
 
https://connect.medrxiv.org/relate/content/181

JSON - https://connect.medrxiv.org/relate/collection_json.php?grp=181

Podemos incorporar mais de 6 mil preprints na BVS, a partir do JSON acima, marcando o cluster Base de Dados com medRxiv/bioRxiv COVID e Coleção com Preprints

Um abraço,

Renato Murasaki

```

**Comment by falbrito** [comment]
Sobre a API

https://api.biorxiv.org/covid19/help

**Comment by falbrito** [comment]
Processo criado.

scripts:
serverofi5:/bases/oai.pmh/tpl.json/coleta_BIORXIV.sh
serverofi5:/bases/oai.pmh/tpl.json/cria_xml_BIORXIV.py
serverofi5:/bases/oai.pmh/tpl.json/descobreTotal_BIORXIV.py

XMLs resultantes:
ppmedrvix_regional.xml
ppbiorvix_regional.xml

**Comment by botturam** [comment]
Renato liberou para disponibilizar em produção. Proc de IAHx-Portal deve terminar amanhã, 6f

**Comment by falbrito** [comment]
Em produção
