### ISSUE TITLE
Revisar e traduzir os labels de Type of Documento da interface iAHx WHO COVID-19 

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#355]
![image](https://user-images.githubusercontent.com/1226218/91460958-d406b280-e85e-11ea-896d-99937564653e.png)

**Comment by marcoslmori** [comment]
ajustado em pt/en/es/fr... procedendo para ajustar ar/ru/zh

**Comment by marcoslmori** [comment]
Ajustado ar/ru/zh em produção
