### ISSUE TITLE
Coletar os registros de SES-BA, SES-RN e SES-PE do FIADMIN para IAHx-CONASS

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#357]
coletar os docs nos mesmos moldes que as 2 últimas: SES-RJ e SES-GO. Guardar em: serverofi5:/bases/fiadmin/databases

**Comment by falbrito** [comment]
Os processos de coleta foram criados. 

No momento apenas SES-BA possui registros - 11

SES-PE e SES-RN não retornaram registros.
