### ISSUE TITLE
medRxiv e bioRxiv - disponibilizar docs coletados em IAHx-Portal-regional em OFI5

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#358]
operacao@serverofi5:/bases/oai.pmh/xml.rec/BIORXIV $ ll

-rw-rw-r-- 1 operacao operacao  6228585 Aug 28 17:21 ppbiorvix_regional.xml
-rw-rw-r-- 1 operacao operacao 23705311 Aug 28 17:21 ppmedrvix_regional.xml

**Comment by botturam** [comment]
em processamento para disponibilizar em produção...

**Comment by falbrito** [comment]
Cadastrado e em operação via Celery.
