### ISSUE TITLE
Determinantes Sociais em Saude

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#364]
[Determinantes_sociais_saude_atualizado.txt](https://github.com/bireme/db-processing/files/5388016/Determinantes_sociais_saude_atualizado.txt)

**Comment by botturam** [comment]
Onde coloco esse tema? é da interface Wizard?

**Comment by pintoros** [comment]
Eu tenho dúvida quanto a esse tema, mas ele já está previsto na navegação da interface, está no mesmo nível de tipos de estudos, apesar de não ser considerado como tal, mas, por favor confirme com o Renato. Este realmente eu fiquei em dúvida, por isso não marquei.



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:7bd16193-96b1-44b0-87ae-83304d6f642c]

________________________________
De: botturam <notifications@github.com>
Enviado: quarta-feira, 7 de outubro de 2020 16:32
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Determinantes Sociais em Saude (#364)


Onde coloco esse tema? é da interface Wizard?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F364%23issuecomment-705148779&data=02%7C01%7Cpintoros%40paho.org%7C05bcc40a289740f6676c08d86af7c295%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637376959642539731&sdata=IAwLCJ%2F0wHzR1nSXiAj60bkUCpJShpp4dnlbdFHYpHU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4FQEXUZOOTHD4VV7RDSJS65TANCNFSM4RC4TCIA&data=02%7C01%7Cpintoros%40paho.org%7C05bcc40a289740f6676c08d86af7c295%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637376959642539731&sdata=pAJw6jaT3KpOQvBCKoorqudIbGAzGDUEm8ADj7%2BCtSM%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
Marcelo, atualizei essa estratégia e o anexo acima.

**Comment by botturam** [comment]
em processamento...

**Comment by marcoslmori** [comment]
Esse elemento apareceu no cluster tipo de estudo da interface de iahx do OMS covid (https://pesquisa.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/),  Procedo com a tradução, se sim, poderia me informar nos 4 idiomas.  @botturam e @pintoros 

![image](https://user-images.githubusercontent.com/10047460/97719603-06729d00-1aa6-11eb-96e2-baf49787946a.png)

**Comment by botturam** [comment]
Mori,

este item entrou por causa da nova interface wizard. Não é propriamente um Tipo de estudo, mas foi acomodado neste cluster. Vamos ver o que a Rose acha. @pintoros

**Comment by marcoslmori** [comment]
OK

**Comment by pintoros** [comment]
Esse entra no cluster Aspecto.



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:047cd756-3628-4d34-ba13-f710ac1b7747]

________________________________
De: Marcos Luis Mori <notifications@github.com>
Enviado: sexta-feira, 30 de outubro de 2020 12:19
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/db-processing] Determinantes Sociais em Saude (#364)


OK

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F364%23issuecomment-719615445&data=04%7C01%7Cpintoros%40paho.org%7Cce65a951922448903e4e08d87ce730fe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637396679685347268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dfDlWjTj3tLbrrEavS0W3K%2F7vUJ2CxZTZydNp7NZc6A%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BQZOPVI2VX5DSRBXTSNLKP5ANCNFSM4RC4TCIA&data=04%7C01%7Cpintoros%40paho.org%7Cce65a951922448903e4e08d87ce730fe%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637396679685357220%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yBY%2BR24zTHZVOGN3VYedWTd%2Fh2IlR5%2FM%2FlbqmZNCdi4%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcoslmori** [comment]
@botturam  não ficou claro essa questão para mim, se não é para ficar em tipo de estudo, deve se retirar e colocar em aspecto clinico. No cluster aspecto clinico da instancia OMS Covid e no portal, não consegui identificar esse elemento.  Por favor, indicar qual é o encaminhamento a ser feito.

**Comment by pintoros** [comment]
@Mori, Marcos (BIR)<mailto:morimarc@paho.org>, o cluster aspecto clínico não existe mais. Foi substituído pelo cluster Aspectos. Os filtros desse cluster tem o mesmo "nível" quanto ao processamento e na interface wizard dos tipos de estudo, mas metodologicamente não podem ser considerados como tal e sim aspectos. Por isso a diferença quanto a localização na interface. Aproveito para solicitar que corrija a tradução e grafia nos 4 idiomas:

Determinantes sociais da saúde / Social determinants of health / Determinantes sociales de la salud / Déterminants sociaux de la santé

Obrigada



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:805b8348-f1dd-4f61-834c-7439268a2c4e]

________________________________
De: Marcos Luis Mori <notifications@github.com>
Enviado: terça-feira, 3 de novembro de 2020 15:36
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Mention <mention@noreply.github.com>
Assunto: Re: [bireme/db-processing] Determinantes Sociais em Saude (#364)


@botturam<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbotturam&data=04%7C01%7Cpintoros%40paho.org%7Ce9991d6b53a449f6824208d8802756c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637400253728031046%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=37vVzqjeoGmc2IaPT%2FBKQr6WUKH6wBkWciB9k7Wt09A%3D&reserved=0> não ficou claro essa questão para mim, se não é para ficar em tipo de estudo, deve se retirar e colocar em aspecto clinico. No cluster aspecto clinico da instancia OMS Covid e no portal, não consegui identificar esse elemento. Por favor, indicar qual é o encaminhamento a ser feito.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F364%23issuecomment-721305631&data=04%7C01%7Cpintoros%40paho.org%7Ce9991d6b53a449f6824208d8802756c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637400253728041012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q4CLJokoitxNO83DhE0k6gEDf75I0m%2F2RKvW%2BgBbUSg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4CF63HKVF6OOLBMAF3SOBERXANCNFSM4RC4TCIA&data=04%7C01%7Cpintoros%40paho.org%7Ce9991d6b53a449f6824208d8802756c6%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637400253728041012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f8megwPxOrEG5mpNJoB1hriycPTbijJ%2BASJwjMOsSK8%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
Nova entrada do cluster "aspect" disponível em produção (aspect:determinantes_sociais_saude)

Falta traduzir o label:

Aspecto
Determinantes_sociais_saude (2947)
Equidade e iniquidade (427)
Preferência do paciente (319)
Aspectos éticos (108)
Pesquisa de implementação (8)

**Comment by botturam** [comment]
em IAHx-Portal regional, cluster "Aspecto"; falta traduzir o label abaixo:

Determinantes_sociais_saude (24805)

texto enviado pela Rose:

Determinantes sociais da saúde / Social determinants of health / Determinantes sociales de la salud / Déterminants sociaux de la santé

**Comment by renatomurasaki** [comment]
@botturam encerrando este issue, pois creio que o resultado do processamento já esteja disponível em produção (1 ano desde a última atualização deste issue)

**Comment by pintoros** [comment]
A tag de recuperação desse tema não corresponde com o resultado da estratégia de busca proposta. Favor revisar
Estratégia: 939.936 em 23/09
Tag:  aspect:"determinantes_sociais_saude" 57.912 em 23/09

Também solicito a tradução label na interface que ainda não foi feita.

**Comment by botturam** [comment]
Falta traduzir o nome lógico para os 4 idiomas, no cluster "aspect"

_cluster_: aspect

_Nome lógico:_ determinantes_sociais_saude

_Texto de trradução (4 idiomas):_ 
Determinantes sociais da saúde / Social determinants of health / Determinantes sociales de la salud / Déterminants sociaux de la santé

Ocomon  8265 aberto

**Comment by pintoros** [comment]
Ainda não foi traduzido na interface. Estou sem acesso ao OCOMON
[cid:6d13cb71-643a-484d-8a80-82693324e18a]



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:c18dd48f-8a12-416a-9c77-50a7aaf28436]

________________________________
De: botturam ***@***.***>
Enviado: segunda-feira, 22 de novembro de 2021 17:41
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; State change ***@***.***>
Assunto: Re: [bireme/db-processing] Determinantes Sociais em Saude (#364)


Falta traduzir o nome lógico para os 4 idiomas, no cluster "aspect"

cluster: aspect

Nome lógico: determinantes_sociais_saude

Texto de trradução (4 idiomas):
Determinantes sociais da saúde / Social determinants of health / Determinantes sociales de la salud / Déterminants sociaux de la santé

Ocomon 8265 aberto

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F364%23issuecomment-975901320&data=04%7C01%7Cpintoros%40paho.org%7Cac5070191ea141a1bd7208d9adf8858f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637732105188906239%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GciF0u9ZVesHpoU%2FxS7y8t8kbzRqgHNEBqk1VOSUoUU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4FWHPHDTTHBKW5ORMDUNKTJFANCNFSM4RC4TCIA&data=04%7C01%7Cpintoros%40paho.org%7Cac5070191ea141a1bd7208d9adf8858f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637732105188916198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VdRAfVMHsBCHgRmBTp3WBhyMgCkBZ4kx%2FRLm7uqfLJg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7Cac5070191ea141a1bd7208d9adf8858f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637732105188926152%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lG5IXVTpVZuN3jpZLvNVagQSCt%2Bl%2BczAWf4yfYtkhZU%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpintoros%40paho.org%7Cac5070191ea141a1bd7208d9adf8858f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637732105188926152%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JACxTiPvozCg7tXchEtpagCMIKL8xJTcAkZudHXC9YU%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
@pintoros eu abri  o Ocomon 8265 para esta tradução. Vou precisar da ajuda do Vinícius, pois o Mori está de férias

**Comment by pintoros** [comment]
Obrigada Marcelo!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:95395b51-917a-4a9a-bc86-e9d39b940be9]

________________________________
De: botturam ***@***.***>
Enviado: terça-feira, 7 de dezembro de 2021 17:01
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/db-processing] Determinantes Sociais em Saude (#364)


@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C56b90d785ab344bf8a8508d9b9bc5985%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637745040878293385%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r8fjI4UsGnLFNuqVLVp7I83sO4YDUrXOO4Xn2Z9zFuY%3D&reserved=0> eu abri o Ocomon 8265 para esta tradução. Vou precisar da ajuda do Vinícius, pois o Mori está de férias

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F364%23issuecomment-988226081&data=04%7C01%7Cpintoros%40paho.org%7C56b90d785ab344bf8a8508d9b9bc5985%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637745040878303341%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=y5YHbOc2F9VgeqfY7utRpzDnGQZqQWTjdcA%2FBwVuv%2Fg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4ERZRHGEUVMRL4SN3LUPZRZLANCNFSM4RC4TCIA&data=04%7C01%7Cpintoros%40paho.org%7C56b90d785ab344bf8a8508d9b9bc5985%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637745040878303341%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=81WtTOgCrfZZknUmApTPX%2Fr4BQ31xRZatTNy%2BRk1%2F78%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7C56b90d785ab344bf8a8508d9b9bc5985%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637745040878313295%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nRrwrH9VgKEz1wiAmtOZgbbEy077mNp15xwUBVbEMVw%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpintoros%40paho.org%7C56b90d785ab344bf8a8508d9b9bc5985%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637745040878313295%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ls68RG%2FoDMAUwKWrEkgcAlhlkFB0MD6Tz46mbCiuv%2F4%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
