### ISSUE TITLE
Marcação do campo "Indexado em" via script

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/db-processing#368]
@anakatiacamilo, veja se esta planilha é o suficiente para sua atividade!

De acordo com o Amilson, que criou a planilha, em vermelho não são indexadas na LILACS e em bege não estão com indexação BDENF na TITLE.

Obrigada!
[Revistas_BDENF_e_LILACS.xlsx](https://github.com/bireme/db-processing/files/5220211/Revistas_BDENF_e_LILACS.xlsx)

**Comment by AngelicaSAPaula** [comment]
segue planilha enviada pela Jordana!
[CB 2020_NOVO.xlsx](https://github.com/bireme/db-processing/files/5220606/CB.2020_NOVO.xlsx)

**Comment by anakatiacamilo** [comment]
Boa tarde @AngelicaSAPaula, analisei os dois levantamento da Jordana e do Amilson. 
Com a lista de revistas BDENF vou dar andamento documentando as atividades. Segue algumas observações 

- Pedir a Cobertura de Indexação da BDENF para essas Revistas

CO	Investigación en enfermería	Investig. enferm	0124-2059	CO185.1	CO638.9	LL^aVol.12^bn.1^c2010-^gCO1.1
CU	Revista cubana de enfermería	Rev. cuba. enferm	0864-0319	CU1.1	CU608.9	LL^aVol.1^bn.1^c1985-^gCU1.1EC

- Pedir para o Amilso colocar o Subcampo g = BR1.1 na cobertura de Indexação da BDENF 
BR	Journal Health NPEPS	J. Health NPEPS	2526-1010	BR1.1	BR1972.9	LL^aVol.3^bn.2^c2018-^gBR1.1^h1	BDENF^aVol.1^bn.2^c2016-

- Indicar essas Revistas LILACS para a Jordana/Chico avaliarem se pode ser BDENF? Se puder informar a cobertura de Indexação.

AR	Notas de enfermería (Córdoba)	Notas enferm. (Córdoba)	1668-8821	AR475.1	AR393.9	LL^aVol.1^bn.1^c2-^gAR475.1	BDENF
PE	Revista enfermería herediana	Rev. enferm. herediana	1998-5487	PE1.1	PE380.9	LL^aVol.18^bn.12^c2008-gPE1.1
PE	Revista peruana de obstetricia y enfermería	Rev. peru. obstet. enferm	1816-7713		PE376.9	LL^aVol.2^n.1^c2006-^dVol.3^en.2^f2007

- Criar um check no campo "Indexado em associado (LILACS)" a "Cobertura de Indexação (TITLE)" -  A questão é que as revistas que não são LILACS não podem ser Indexada em LILACS sei que não é possível fazer um check genérico, porque, nem toda a lista do campo "Indexado em" esta cadastrada com a Cobertura de indexação da title e como o check depende de muitas variáveis  talvez prejudique no tempo de gravação do registros podemos pensar em algum processamento fora do FI-ADMIN. Issue associado #758 fi-admin
Revistas BDENFs que não são LILACS, mas tem alguns registros que estão como LILACS.

BR	Enfermagem em foco (Brasília)		Enferm. foco (Brasília)		2177-4285	BR1898.2	BR1898.9	BDENF^aVol.1^bn^c2010-^gBR1898.2
BR	Journal of Nursing and Health		J. nurs. Health	2		236-1987	BR538.1		BR539.9		BDENF^aVol.4^bn.1^c2014-^gBR538.1
BR	Revista de enfermagem UFPE on line	Rev. enferm. UFPE on line	1981-8963	BR9.1		BR1904.9	BDENF^aVol.4^bn.1^c2010-^gBR9.1

Atenciosamente.

**Comment by AngelicaSAPaula** [comment]
@anakatiacamilo segue planilha atualizada com a cobertura de indexação BDENF. 
[CB 2020_NOVO (1).xlsx](https://github.com/bireme/db-processing/files/5241418/CB.2020_NOVO.1.xlsx)


As demais informações, solicitei à Jordana e estou no aguardo.

O que deveria ser corrigido na Title, o Amilson já realizou!

**Comment by AngelicaSAPaula** [comment]
@anakatiacamilo 

Jordana está entrando em contato com as revistas que não são brasileiras.

As revistas Enfermagem em foco (Brasília) e Journal of Nursing and Health, foram incluídas na LILACS (cadastro na Title atualizado).

Falta alguma coisa?

**Comment by renatomurasaki** [comment]
@anakatiacamilo tenho entendido que este issue já foi resolvido de acordo com as nossas últimas conversas.
