### ISSUE TITLE
Vitrine Nursing Now - Gestão no trabalho da enfermagem

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#369]
[Gestão no trabalho da enfermagem.txt](https://github.com/bireme/db-processing/files/5239115/Gestao.no.trabalho.da.enfermagem.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by pintoros** [comment]
Bom dia Marcelo!
Quando finalizar o processamento vc pode me passar as tags para eu poder rodar da BVS Enfermeria?

Muito obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:db88747b-4ca1-43af-bd93-35784594dd01]

________________________________
De: botturam <notifications@github.com>
Enviado: sexta-feira, 11 de dezembro de 2020 18:13
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Gestão no trabalho da enfermagem (#369)


em processamento...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F369%23issuecomment-743429577&data=04%7C01%7Cpintoros%40paho.org%7C3123bdfe5d944f0f70fc08d89e199160%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637433179929656402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FShn6CPX3NBDXWDYbafpzFwUJFYKKcN0HFJ289mrCCQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4C2WREQ7EYXA5KU57TSUKDORANCNFSM4RQMD3IA&data=04%7C01%7Cpintoros%40paho.org%7C3123bdfe5d944f0f70fc08d89e199160%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637433179929656402%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Id6gCGjdkgQZtbKovVgTY7jts5DxEy6TJx9csUT90D0%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
disponível em produção, LILACS, ColecionaSUS e BDENF.

tag_enfermeria:"VNN_doencas_transmissiveis"
tag_enfermeria:"VNN_gestao"
tag_enfermeria:"VNN_saude_sexual_reprodutiva"
tag_enfermeria:"VNN_saude_trabalhador_enfermagem"

**Comment by pintoros** [comment]
Rose,

disponível em produção, LILACS, ColecionaSUS e BDENF.

tag_enfermeria:"VNN_doencas_transmissiveis"
tag_enfermeria:"VNN_gestao"
tag_enfermeria:"VNN_saude_sexual_reprodutiva"
tag_enfermeria:"VNN_saude_trabalhador_enfermagem"


abc,


Marcelo Bottura
Supervisor OFI - Operação de Fontes de Informação
BIREME/OPAS/OMS
Departamento de Evidência e Inteligência para a Ação em Saúde
Fone: +55 11 5576-9817
VoIP: 44852
botturam@paho.org<https://mymail.paho.org/owa/redir.aspx?C=yLTqiDx_VECNKWe5PY31-YqMmpHTsdEIesrr2JOQ4xicl2FzzE3bsLP1IxIYKseiLADbwXiIWto.&URL=mailto%3asugasuel%40bireme.ops-oms.org>
________________________________
De: Pinto, Rosemeire (BIR) <pintoros@paho.org>
Enviado: segunda-feira, 14 de dezembro de 2020 09:55
Para: bireme/db-processing <reply@reply.github.com>; Bottura, Marcelo (BIR) <botturam@paho.org>
Assunto: RE: [bireme/db-processing] Vitrine Nursing Now - Gestão no trabalho da enfermagem (#369)


Bom dia Marcelo!
Quando finalizar o processamento vc pode me passar as tags para eu poder rodar da BVS Enfermeria?

Muito obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:db88747b-4ca1-43af-bd93-35784594dd01]

________________________________
De: botturam <notifications@github.com>
Enviado: sexta-feira, 11 de dezembro de 2020 18:13
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Gestão no trabalho da enfermagem (#369)


em processamento...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F369%23issuecomment-743429577&data=04%7C01%7Cbotturam%40paho.org%7Cbe2dbefebf0c4e2fe4ef08d8a02f8387%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435473216964740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TMU%2BGy5U0UZ6KSPgfLUGiuetg3TZSrUjCK2OS9XndPQ%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4C2WREQ7EYXA5KU57TSUKDORANCNFSM4RQMD3IA&data=04%7C01%7Cbotturam%40paho.org%7Cbe2dbefebf0c4e2fe4ef08d8a02f8387%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435473216974735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=czfMUDvJIe1qHhfSlDVQU4S4F%2B6KRcj3vvkDaUJZ%2F1k%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by pintoros** [comment]
Obrigada!!!!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:f31327d3-1a1b-4808-9ae0-bc1329c72fe4]

________________________________
De: Bottura, Marcelo (BIR) <botturam@paho.org>
Enviado: segunda-feira, 14 de dezembro de 2020 11:26
Para: Pinto, Rosemeire (BIR) <pintoros@paho.org>; bireme/db-processing <reply@reply.github.com>
Assunto: RE: [bireme/db-processing] Vitrine Nursing Now - Gestão no trabalho da enfermagem (#369)


Rose,

disponível em produção, LILACS, ColecionaSUS e BDENF.

tag_enfermeria:"VNN_doencas_transmissiveis"
tag_enfermeria:"VNN_gestao"
tag_enfermeria:"VNN_saude_sexual_reprodutiva"
tag_enfermeria:"VNN_saude_trabalhador_enfermagem"


abc,



Marcelo Bottura
Supervisor OFI - Operação de Fontes de Informação
BIREME/OPAS/OMS
Departamento de Evidência e Inteligência para a Ação em Saúde
Fone: +55 11 5576-9817
VoIP: 44852
botturam@paho.org<https://mymail.paho.org/owa/redir.aspx?C=yLTqiDx_VECNKWe5PY31-YqMmpHTsdEIesrr2JOQ4xicl2FzzE3bsLP1IxIYKseiLADbwXiIWto.&URL=mailto%3asugasuel%40bireme.ops-oms.org>

________________________________
De: Pinto, Rosemeire (BIR) <pintoros@paho.org>
Enviado: segunda-feira, 14 de dezembro de 2020 09:55
Para: bireme/db-processing <reply@reply.github.com>; Bottura, Marcelo (BIR) <botturam@paho.org>
Assunto: RE: [bireme/db-processing] Vitrine Nursing Now - Gestão no trabalho da enfermagem (#369)


Bom dia Marcelo!
Quando finalizar o processamento vc pode me passar as tags para eu poder rodar da BVS Enfermeria?

Muito obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:db88747b-4ca1-43af-bd93-35784594dd01]

________________________________
De: botturam <notifications@github.com>
Enviado: sexta-feira, 11 de dezembro de 2020 18:13
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Vitrine Nursing Now - Gestão no trabalho da enfermagem (#369)


em processamento...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F369%23issuecomment-743429577&data=04%7C01%7Cpintoros%40paho.org%7C1fbe956e43ec4d61e91508d8a03c42ee%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435527977336626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b8uy7MXG%2FULWyuZUz5xmJo%2F0vV7%2FUxYxc6NXxIjK0tc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4C2WREQ7EYXA5KU57TSUKDORANCNFSM4RQMD3IA&data=04%7C01%7Cpintoros%40paho.org%7C1fbe956e43ec4d61e91508d8a03c42ee%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637435527977336626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hurxpWwJfhSb5S6Ho21mQQyUMzdPVQHHfAVJ8Es3UCg%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
