### ISSUE TITLE
Adaptar processamento da INDEXPSIC TESES de acordo com a nova arquitetura de scripts criada

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#37]

**Comment by santosfj** [comment]
Fica faltando o saneamento específico de homeopatia, caso seja necessário (MB vai informar se e o que), o restante todo ok (coletas.tab; coleta_wget; pos_coleta_pte; pre_saneamento_fi; iah_like_lilacs; iahh)

**Comment by renatomurasaki** [comment]
@botturam este saneamento específico foi implementado?
