### ISSUE TITLE
Vitrine Nursing Now - Trabalho do enfermeiro no enfrentamento das doenças transmissíveis

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#371]
[Trabalho do enfermeiro no enfrentamento das doenças transmissíveis.txt](https://github.com/bireme/db-processing/files/5239124/Trabalho.do.enfermeiro.no.enfrentamento.das.doencas.transmissiveis.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção, LILACS, ColecionaSUS e BDENF.

tag_enfermeria:"VNN_doencas_transmissiveis"
tag_enfermeria:"VNN_gestao"
tag_enfermeria:"VNN_saude_sexual_reprodutiva"
tag_enfermeria:"VNN_saude_trabalhador_enfermagem"
