### ISSUE TITLE
Correção de hyperlinks cravados no portal antigo do DeCS

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/db-processing#374]
Trocar os 3 URLs (tanto quando coloco http quanto https):

DE: http://decs.bvsalud.org/homepage.htm --> PARA: http://decs2020.bvsalud.org/
DE: http://decs.bvsalud.org/I/homepagei.htm --> PARA: http://decs2020.bvsalud.org/E/homepagee.htm  
DE: http://decs.bvsalud.org/E/homepagee.htm --> PARA: http://decs2020.bvsalud.org/I/homepagei.htm

DE: https://decs.bvsalud.org/homepage.htm --> PARA: http://decs2020.bvsalud.org/
DE: https://decs.bvsalud.org/I/homepagei.htm --> PARA: http://decs2020.bvsalud.org/E/homepagee.htm
DE: https://decs.bvsalud.org/E/homepagee.htm --> PARA: http://decs2020.bvsalud.org/I/homepagei.htm

Exemplo: Banner da página http://trigramas.bireme.br/cgi-bin/mx/cgi=@1?collection=DeCSxp&lang=p&minsim=0.30&maxrel=10&text=Macaca%20mulatta

**Comment by renatomurasaki** [comment]
Portal novo já em operação
