### ISSUE TITLE
Hanseniase - Geral

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#379]
Recorte para área temática BVS Hanseniase
[BVS Hanseniase - Recorte geral.txt](https://github.com/bireme/db-processing/files/5300933/BVS.Hanseniase.-.Recorte.geral.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
Disponível em https://pesquisa.bvsalud.org/hansen/

**Comment by pintoros** [comment]
Será necessário atualizar o recorte geral da BVS Hanseníase.
* O recorte geral não deve ser aplicado à base de dados hanseníase, que deverá entrar completa na BVS. O número de documentos total da instância com esse filtro geral é de aproximadamente 60 mil documentos.
* Os recortes temáticos devem ser aplicados diretamente as bases de dados incluídas na BVS Hanseníase. 


Segue o novo arquivo
[BVS.Hanseniase.-.Recorte.geral_atualizado.txt](https://github.com/bireme/db-processing/files/5631293/BVS.Hanseniase.-.Recorte.geral_atualizado.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
@botturam encerrando este issue, pois creio que o resultado do processamento já esteja disponível em produção (6 meses desde a última atualização deste issue)
