### ISSUE TITLE
Hanseniase - Aspectos sociais

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#380]
Área temática BVS Hanseniase - estratégia combinada com recorte geral
[Hanseniase - Aspectos sociais.txt](https://github.com/bireme/db-processing/files/5300950/Hanseniase.-.Aspectos.sociais.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
Disponível em https://pesquisa.bvsalud.org/hansen/

@marcoslmori @botturam corrigir tradução do label Aspectos_sociais

**Comment by marcoslmori** [comment]
Atualizado em instancia de teste e solicitado para sincronizar em produção (chamado 7551)

**Comment by marcoslmori** [comment]
sincronizado em produção!
