### ISSUE TITLE
Hanseniase - Complicações

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#381]
Área temática BVS Hanseniase - estratégia combinada com recorte geral

[Hanseniase - Complicacoes.txt](https://github.com/bireme/db-processing/files/5301006/Hanseniase.-.Complicacoes.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
Disponível em https://pesquisa.bvsalud.org/hansen/
