### ISSUE TITLE
Hanseniase - Etiologia

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#382]
Área temática BVS Hanseniase - estratégia combinada com recorte geral
[Hanseniase - Etiologia.txt](https://github.com/bireme/db-processing/files/5301060/Hanseniase.-.Etiologia.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
Disponível em https://pesquisa.bvsalud.org/hansen/
