### ISSUE TITLE
Hanseniase - Mortalidade

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#383]
Área temática BVS Hanseniase - estratégia combinada com recorte geral
[Hanseniase - Mortalidade.txt](https://github.com/bireme/db-processing/files/5301063/Hanseniase.-.Mortalidade.txt)

**Comment by botturam** [comment]
em processamento

**Comment by renatomurasaki** [comment]
Disponível em https://pesquisa.bvsalud.org/hansen/
