### ISSUE TITLE
Hanseniase - Transmissao

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#384]
Área temática BVS Hanseniase - estratégia combinada com recorte geral
[Hanseniase - Transmissao.txt](https://github.com/bireme/db-processing/files/5301097/Hanseniase.-.Transmissao.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by renatomurasaki** [comment]
Disponível em https://pesquisa.bvsalud.org/hansen/
