### ISSUE TITLE
Processar  SophiA/Butantan juntamente com a SES para publicação no IAHx da SES

### ISSUE THREAD

**Issue by marcoslmori** [bireme/db-processing#39]
- Verificar se o ID das duas Bases e se possível prefixar. 
-  Será publicado como produção e acervo

**Comment by falbrito** [comment]
Inserido o prefixo "ib" no campo v2. 
Exemplo de coo ficará:

ib1234

**Comment by falbrito** [comment]
Processamento realizado e em processo de ajustes seguindo feedback  do cliente

**Comment by falbrito** [comment]
A fonte de informação de Butantan foi incorporada ao processamento. 
Para realizar pesquisa de registros exclusivos buscar em http://pesquisa.bvsalud.org/ses  por:
id:but-ib*
