### ISSUE TITLE
Arquivo CSV para apoiar deduplicação da Elsevier

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#391]
@botturam por favor, seria possível gerar um arquivo CSV, no final do processamento da interface COVID, com os dados já enriquecidos, contendo os seguintes campos:

- RefID
- Covidence
- Journal
- DOI
- Title (article) 
- Volume
- Issue
- Pages
- Publication Year
- ISSNs
- Abstract
- Authors

Quando for repetitivo, separar os valores com ";".

Title e Abstract somente em inglês. Na ausência do inglês, no idioma disponível.

**Comment by renatomurasaki** [comment]
Mudança de decisão: retroalimentar o XML do Lucene para contemplar elementos DOI e ISSN

**Comment by botturam** [comment]
1) inseridas as linhas no schema.xml:
   <field name="is"                           type="string"    indexed="true"  stored="true"  multiValued="true"/>
   <field name="is_linking"               type="string"    indexed="true"  stored="true"  multiValued="true"/>      (ISSN online)
   <field name="aid"                         type="string"    indexed="true"   stored="true"/>                                      (DOI)

2) foi gerado novo MDL-XML-Covidwho com os campos acima.

3) serviço SoLR, porta 1, reiniciado em OFI5; novo processamento COVIDWHO iniciado. 

Previsão de que tudo esteja disponível na 4f cedo.

**Comment by botturam** [comment]
disponível em produção.

OBS: acima, não consigo editar o assentamento para corrigir o texto do item 1.

**Comment by renatomurasaki** [comment]
@botturam quando os registros são Medline, todos estes estão aparecendo corretamente no XML. Entretanto, quando é WHO COVID, por exemplo, muitos deles não aparece, como volume, número, página, issn, mesmo tendo no campo fonte a informação.

Poderia checar, por favor, para os casos que não são enriquecidos mas que o dado vem da planilha original da OMS?

**Comment by botturam** [comment]
foram acrescentados os campos pg(v14), vi(v31) e ip(v32), abaixo, no XML-COVID (cvd_regional.xml), o qual representa os docs sem enriquecimento:

'\<14 0\>',v1006[1]'\</14\>'  
'\<31 0\>',v1004[1]'\</31\>'
'\<32 0\>',v1005[1]'\</32\>'

disponível em teste:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/

Na próxima atualização (virada), amanhã, 04:00, estará disponível em produção.
