### ISSUE TITLE
Analizar la base de descripción bibliográfica de TC-Legis

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#392]

**Comment by anakatiacamilo** [comment]
Analisei a base fiz e um tabela de compatibilização dos registros da TC-Legis para o FI-ADMIN, falta poucos ajustes que espero resolver esta semana.

**Comment by anakatiacamilo** [comment]
Analise concluída documentação no link abaixo 

https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/FI-ADMIN/Migration/AR-Legisalud/AR_legisalud.xlsx?d=w9166353ced9d405f991d1102201b7eb7&csf=1&web=1&e=hnE8wo
