### ISSUE TITLE
Analizar la base de texto completo de TC-Legis

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#394]

**Comment by heitorbarbieri** [comment]
Base de dados localizada em:  ftp.bireme.br/TcLegis/AR/document_201020


Analysis Date: Tue Nov 03 17:06:21 BRT 2020

Database:
   dbname = /home/heitor/document
   platform = Linux
   encoding = ISO-8859-1
   ffi = true
   swapped = true
   max size = 4 gigabytes
   next mfn = 35661
   data entry lock (DEL) = 0
   exclusive write lock (EWL) = 0


Records:
   active records = 32731 (91,79%)
   deleted records = 2929 (8,21%)
   max record size = 656400
   min record size = 1256
   avg record size = 9941


Fields:
      name       tag  presence presence%   ausence  ausence%       occ  minTimes  maxTimes    minLen    maxLen    avgLen      type

                   1     32731    91,79%      2929     8,21%     32731         1         1      1218    656364      9902  ALPHANUM


Subfields:
   fld tag   subf id  presence presence%   ausence  ausence%       occ  minTimes  maxTimes    minLen    maxLen    avgLen      type

         1         4         3     0,01%     32728    99,99%         3         1         1     12539     12747     12610  ALPHANUM
         1         _ (A) 32731   100,00%         0     0,00%     32731         1         1      1218    656364      9898  ALPHANUM
         1         p         3     0,01%     32728    99,99%         3         1         1     25061     25069     25066  ALPHANUM


Characters:
             char     val(Unicode)  val(ISO-8859-1)            times           times%
                              127              127                1            0,00%
                ¦              166              166                1            0,00%
                Ô              212              212                1            0,00%
                ×              215              215                1            0,00%
                Ý              221              221                1            0,00%
                þ              254              254                1            0,00%
                ©              169              169                2            0,00%
                Ê              202              202                2            0,00%
                Î              206              206                2            0,00%
                Û              219              219                2            0,00%
                ÷              247              247                2            0,00%
                Ë              203              203                3            0,00%
                ë              235              235                4            0,00%
                Å              197              197                5            0,00%
                Ï              207              207                5            0,00%
                Ù              217              217                5            0,00%
                ä              228              228                5            0,00%
                å              229              229                6            0,00%
                \               92               92                8            0,00%
                ¬              172              172                8            0,00%
                æ              230              230                8            0,00%
                ÿ              255              255                8            0,00%
                              150              150                9            0,00%
                ¼              188              188                9            0,00%
                Æ              198              198                9            0,00%
                À              192              192               10            0,00%
                ¸              184              184               12            0,00%
                ù              249              249               13            0,00%
                £              163              163               14            0,00%
                ¹              185              185               15            0,00%
                È              200              200               15            0,00%
                Ì              204              204               15            0,00%
                              148              148               16            0,00%
                              147              147               17            0,00%
                Â              194              194               17            0,00%
                ~              126              126               20            0,00%
                ô              244              244               20            0,00%
                Ä              196              196               22            0,00%
                õ              245              245               22            0,00%
                ^               94               94               23            0,00%
                {              123              123               23            0,00%
                Ò              210              210               24            0,00%
                Ö              214              214               24            0,00%
                ³              179              179               25            0,00%
                ¾              190              190               26            0,00%
                `               96               96               28            0,00%
                ì              236              236               30            0,00%
                }              125              125               33            0,00%
                Þ              222              222               37            0,00%
                ¨              168              168               38            0,00%
                §              167              167               40            0,00%
                ø              248              248               42            0,00%
                à              224              224               43            0,00%
                ö              246              246               46            0,00%
                ¡              161              161               47            0,00%
                Ç              199              199               49            0,00%
                ò              242              242               52            0,00%
                               160              160               55            0,00%
                ½              189              189               58            0,00%
                ¢              162              162               62            0,00%
                ï              239              239               62            0,00%
                ß              223              223               79            0,00%
                Ã              195              195               97            0,00%
                ®              174              174              105            0,00%
                µ              181              181              117            0,00%
                è              232              232              125            0,00%
                ´              180              180              168            0,00%
                |              124              124              177            0,00%
                ±              177              177              178            0,00%
                ê              234              234              181            0,00%
                ã              227              227              187            0,00%
                Ü              220              220              211            0,00%
                ç              231              231              215            0,00%
                â              226              226              218            0,00%
                ­              173              173              234            0,00%
                ²              178              178              333            0,00%
                Ø              216              216              366            0,00%
                @               64               64              671            0,00%
                »              187              187              766            0,00%
                «              171              171              775            0,00%
                ª              170              170              948            0,00%
                ¿              191              191             1554            0,00%
                '               39               39             1574            0,00%
                ·              183              183             1594            0,00%
                +               43               43             2208            0,00%
                Ñ              209              209             4229            0,00%
                ü              252              252             5240            0,00%
                *               42               42             8831            0,00%
                Á              193              193            10023            0,00%
                Ú              218              218            11434            0,00%
                K               75               75            11769            0,00%
                É              201              201            13116            0,00%
                $               36               36            14049            0,00%
                	                9                9            15975            0,00%
                %               37               37            25235            0,01%
                !               33               33            27034            0,01%
                Z               90               90            34070            0,01%
                W               87               87            37828            0,01%
                X               88               88            39730            0,01%
                Í              205              205            40218            0,01%
                [               91               91            55138            0,02%
                ]               93               93            55163            0,02%
                Ó              211              211            70712            0,02%
                _               95               95            84266            0,03%
                w              119              119            85994            0,03%
                Y               89               89            86529            0,03%
                ?               63               63            96991            0,03%
                J               74               74           128809            0,04%
                ñ              241              241           138897            0,04%
                #               35               35           140178            0,04%
                H               72               72           187666            0,06%
                ú              250              250           203249            0,06%
                Q               81               81           225938            0,07%
                °              176              176           241045            0,07%
                F               70               70           255041            0,08%
                B               66               66           258935            0,08%
                V               86               86           261636            0,08%
                º              186              186           267506            0,08%
                k              107              107           334682            0,10%
                (               40               40           366770            0,11%
                G               71               71           386192            0,12%
                :               58               58           407141            0,13%
                x              120              120           419470            0,13%
                é              233              233           427227            0,13%
                &               38               38           498762            0,15%
                7               55               55           513026            0,16%
                z              122              122           532704            0,16%
                6               54               54           542347            0,17%
                j              106              106           558112            0,17%
                )               41               41           601769            0,19%
                4               52               52           625656            0,19%
                8               56               56           636245            0,20%
                9               57               57           649130            0,20%
                3               51               51           686936            0,21%
                5               53               53           697678            0,22%
                U               85               85           719077            0,22%
                M               77               77           772271            0,24%
                á              225              225           791979            0,24%
                ;               59               59           825380            0,25%
                í              237              237           882196            0,27%
                q              113              113           898595            0,28%
                =               61               61           963226            0,30%
                T               84               84           990062            0,31%
                "               34               34          1072283            0,33%
                O               79               79          1199110            0,37%
                -               45               45          1282323            0,40%
                h              104              104          1338475            0,41%
                L               76               76          1364177            0,42%
                C               67               67          1373816            0,42%
                R               82               82          1404833            0,43%
                D               68               68          1453591            0,45%
                S               83               83          1475265            0,46%
                N               78               78          1644664            0,51%
                v              118              118          1783533            0,55%
                2               50               50          1789117            0,55%
                ó              243              243          1837278            0,57%
                E               69               69          1882871            0,58%
                1               49               49          1919714            0,59%
                0               48               48          1922700            0,59%
                ,               44               44          1958105            0,60%
                y              121              121          1962156            0,61%
                I               73               73          2030547            0,63%
                g              103              103          2227314            0,69%
                f              102              102          2284975            0,71%
                b               98               98          2369344            0,73%
                A               65               65          2405054            0,74%
                .               46               46          3051344            0,94%
                /               47               47          3872678            1,19%
                P               80               80          4353467            1,34%
                m              109              109          5427394            1,67%
                <               60               60          5463141            1,69%
                >               62               62          5463253            1,69%
                p              112              112          6089240            1,88%
                u              117              117          6972840            2,15%
                c               99               99         11140388            3,44%
                t              116              116         11335585            3,50%
                l              108              108         11622895            3,59%
                d              100              100         11909511            3,67%
                s              115              115         14845765            4,58%
                n              110              110         14874157            4,59%
                o              111              111         16383263            5,05%
                i              105              105         16890959            5,21%
                r              114              114         18147367            5,60%
                e              101              101         27472931            8,48%
                a               97               97         29250309            9,03%
                                32               32         40671691           12,55%

Field Definition Table (FDT):

W:doc   
F:doc   
S:doc   
***
field_1                       4_p                 1 656364 0 0


======================================================================

XML Schema gerado a partir de 11 documentos selecionados aleatoriamente:

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="documents" type="documentsType"/>
  <xs:complexType name="document-controlType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:long" name="id" use="optional"/>
        <xs:attribute type="xs:string" name="status" use="optional"/>
        <xs:attribute type="xs:byte" name="version" use="optional"/>
        <xs:attribute type="xs:string" name="destination" use="optional"/>
        <xs:attribute type="xs:long" name="date" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="document-more-infoType">
    <xs:sequence>
      <xs:element type="xs:string" name="leisref-id"/>
      <xs:element type="xs:string" name="pkLeisref"/>
      <xs:element type="document-controlType" name="document-control"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="InlineGraphicType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Depth" use="optional"/>
        <xs:attribute type="xs:string" name="width" use="optional"/>
        <xs:attribute type="xs:string" name="FileRef" use="optional"/>
        <xs:attribute type="xs:string" name="Width" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ParaType" mixed="true">
    <xs:sequence>
      <xs:element type="InlineGraphicType" name="InlineGraphic" minOccurs="0"/>
      <xs:element type="ULinkType" name="ULink" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="epigraphType">
    <xs:sequence>
      <xs:element name="Para" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="InlineGraphicType" name="InlineGraphic" minOccurs="0"/>
            <xs:element type="ULinkType" name="ULink" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="summaryType">
    <xs:sequence>
      <xs:element type="xs:string" name="Para" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="prefaceType">
    <xs:sequence>
      <xs:element name="Para" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="InlineGraphicType" name="InlineGraphic" minOccurs="0"/>
            <xs:element type="ULinkType" name="ULink" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="frontType">
    <xs:sequence>
      <xs:element type="epigraphType" name="epigraph"/>
      <xs:element type="summaryType" name="summary"/>
      <xs:element type="prefaceType" name="preface"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ULinkType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:anyURI" name="URL" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="bodyType">
    <xs:sequence>
      <xs:element name="Para" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="InlineGraphicType" name="InlineGraphic" minOccurs="0"/>
            <xs:element type="ULinkType" name="ULink" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="backType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="Para" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="legis-fulltextType">
    <xs:sequence>
      <xs:element type="document-more-infoType" name="document-more-info"/>
      <xs:element type="frontType" name="front"/>
      <xs:element type="bodyType" name="body"/>
      <xs:element type="backType" name="back"/>
      <xs:element type="attachType" name="attach" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="receiptHeaderType">
    <xs:sequence>
      <xs:element type="xs:long" name="date"/>
      <xs:element type="xs:long" name="id"/>
      <xs:element type="xs:string" name="fileName"/>
      <xs:element type="xs:string" name="institutionalAuthorId"/>
      <xs:element type="xs:string" name="institutionalAuthor"/>
      <xs:element name="userName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ecriscuolo"/>
            <xs:enumeration value="lvmacosta"/>
            <xs:enumeration value="acalveiro"/>
            <xs:enumeration value="oscar.baggini"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="userId"/>
      <xs:element type="xs:string" name="senderManufacturerId"/>
      <xs:element type="xs:string" name="senderManufacturer"/>
      <xs:element name="senderResponsibleName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ecriscuolo"/>
            <xs:enumeration value="lvmacosta"/>
            <xs:enumeration value="acalveiro"/>
            <xs:enumeration value="oscar.baggini"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="senderResponsibleId"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="documentsType">
    <xs:sequence>
      <xs:element type="legis-fulltextType" name="legis-fulltext"/>
      <xs:element type="receiptHeaderType" name="receiptHeader"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="attachType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="Para">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="InlineGraphicType" name="InlineGraphic" minOccurs="0"/>
            <xs:element type="ULinkType" name="ULink" maxOccurs="unbounded" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element type="TABLEType" name="TABLE"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TDType">
    <xs:sequence>
      <xs:element type="xs:string" name="Para" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:byte" name="rowspan" use="optional"/>
    <xs:attribute type="xs:byte" name="colspan" use="optional"/>
  </xs:complexType>
  <xs:complexType name="TRType">
    <xs:sequence>
      <xs:element type="TDType" name="TD" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TBODYType">
    <xs:sequence>
      <xs:element type="TRType" name="TR" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TABLEType" mixed="true">
    <xs:sequence>
      <xs:element type="TBODYType" name="TBODY" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
