### ISSUE TITLE
Desarrollar procedimientos para exportar los datos de descripción bibliográfica de TC-Legis

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#396]

**Comment by anakatiacamilo** [comment]
Procedimento feito que transforma a base de ISISXML == XML == ISIS
Esta documentado em 
https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/FI-ADMIN/Migration/AR-Legisalud/TCLegisAR2FIADMINLeisref.xlsx?d=wad549a8c008e474b890cc03e7cf1f887&csf=1&web=1&e=M3iyuX

Validar com o @viniciusandrade uma informação da ordem do campo de relacionamento.

**Comment by viniciusandrade** [comment]
@anakatiacamilo, 
Adicionado campo **order** na tabela **actrelationship** para migração da informação de ordem das leis relacionadas. 

Ajuste disponível no ambiente de testes do FI-ADMIN ... após validação favor informar para que eu possa aplicar em produção.

Obrigado

Issue relacionado: https://github.com/bireme/fi-admin/issues/1173

**Comment by anakatiacamilo** [comment]
OK 
"model": "leisref.actrelationship",
--
"pk": 1998,
"fields": {
"created_time": "2020-12-02T18:58:59Z",
"updated_time": "2020-12-02T18:58:59Z",
"created_by": 87,
"updated_by": null,
"act_related": 5469,
"relation_type": 18,
"act_referred": 30,
"act_apparatus": "Dispositivo",
**"order": 3**
