### ISSUE TITLE
Desarrollar procedimientos de estandardización de los datos de descripción bibliográfica extraídos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#397]

**Comment by anakatiacamilo** [comment]
Campos Normalizados conforme o arquivo abaixo, 

 https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/FI-ADMIN/Migration/AR-Legisalud/AR_legisalud.xlsx?d=w9166353ced9d405f991d1102201b7eb7&csf=1&web=1&e=fm6FwU
