### ISSUE TITLE
Enlazar los archivos PDF, HTML y XML en los metadatos de descripción bibliográfica correspondiente

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#399]
Evaluar con @anakatiacamilo y @viniciusandrade la solución pertinente para este desarrollo. Entiendo que estos archivos deberán estar hospedados en el servidor LEGISALUD de Argentina. Para eso, es necesario pensar en la estructura de carpetas del sitio LEGISALUD, donde el WP y plug-in estarán instalados y configurados.

**Comment by renatomurasaki** [comment]
Evaluar con @anakatiacamilo y @viniciusandrade la solución pertinente para este desarrollo. Entiendo que estos archivos deberán estar hospedados en el servidor LEGISALUD de Argentina. Para eso, es necesario pensar en la estructura de carpetas del sitio LEGISALUD, donde el WP y plug-in estarán instalados y configurados.

**Comment by heitorbarbieri** [comment]
Arquivos xml, pdf e html transferidos para servidor do wordpress (dolomita02:/home/apps/bvsalud.org/wp-legis-ar/htdocs/legisalud/). Os nomes dos arquivos são os identificadores dos documentos de metadados. Segue o processo de enlace com @anakatiacamilo

**Comment by anakatiacamilo** [comment]
@heitorbarbieri, Inclui os links nos registros da legisalud AR. Estão no FI-ADMIN de curso.
