### ISSUE TITLE
Desarrollar procedimientos para importar los datos de descripción bibliográfica extraídos y normalizados para la estructura de datos de legislación en salud del FI-Admin

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#400]

**Comment by anakatiacamilo** [comment]
Procedimento e formatos criados, migrados na instancia de curso para avaliação.

Segue Relatório para ckeck.
[informe_alerta.xlsx](https://github.com/bireme/db-processing/files/5815595/informe_alerta.xlsx)

Formatos
fixture_leisref_actrelationship.pft
fixture_leisref_act.pft
fixture_leisref_url.pft
fixture_leisref_url_1.pft
fixture_leisref_url_2.pft
fixture_leisref_alternateid.pft
