### ISSUE TITLE
Ajustes en los procedimientos de estandardización e importación de los datos de descripción bibliográfica

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#402]

**Comment by anakatiacamilo** [comment]
Os Ajustes da migração foram feitos nos campos de:
act_collection;
organ_issuer;
issue_date;
publication_date

Relatório esta no #400 

Os campos de Relacionamento ainda em analise.

**Comment by anakatiacamilo** [comment]
O Oscar percebeu um problema na migração nos campos de relacionamento, então tive que alterar o ato ativo e o passivo no formato de criação do json.

      /*  act_related [521^i] */
       if p(v521^m) then,
            ,'"act_related": ',v521^i,', '
       fi,

       /* act_referred [521^m] */
       if p(v521^i) then,
            ,'"act_referred": ',v521^m,', '
       fi,

**Comment by anakatiacamilo** [comment]
Procedimento de padronização  ajustados e importação dos dados dos atos realizado.
