### ISSUE TITLE
Ejecutar, probar y ajustar los procedimientos de importación, mitigando el riesgo de pérdida de información

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#404]

**Comment by anakatiacamilo** [comment]
Registros migrado no FI-ADMIN de produção, como a base veio da origem com problemas tivemos a perda de 7 registros dos 33000 registros no total e um problema com um campo de relacionamento.

**Comment by renatomurasaki** [comment]
@anakatiacamilo o Oscar tem os IDs desses registros, caso ele queira recatalogar?

**Comment by anakatiacamilo** [comment]
@renatomurasaki, acho que ele tem no TC-Legis, vou conversar com ele na próxima reunião.
