### ISSUE TITLE
Desenvolver processamento para arquivo de Literatura cinza COVID-19

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#406]
Desenvolver nos mesmos moldes do processamento da base covidwho. Este processamento será incremental.

arquivo para TESTE com conteúdo "fake" disponível em:
```
operacao@serverofi5:/bases/oai.pmh/csv.rec/covidwho $ ll *gr.csv
-rw-r----- 1 operacao operacao  37587 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessing-gr.csv
-rw-r----- 1 operacao operacao 927024 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessingOnlyAbstract-gr.csv
-rw-r----- 1 operacao operacao  58610 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessingOnlyAuthors-gr.csv
-rw-r----- 1 operacao operacao  27572 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessingOnlyDOI-gr.csv
-rw-r----- 1 operacao operacao  41891 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessingOnlyFullTextLink-gr.csv
-rw-r----- 1 operacao operacao  42112 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessingOnlyJournal-gr.csv
-rw-r----- 1 operacao operacao  15179 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessingOnlyNewIDFields-gr.csv
-rw-r----- 1 operacao operacao   8221 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessingOnlyTags-gr.csv
-rw-r----- 1 operacao operacao  89335 Oct 30 13:58 who-covid-19-repo-export2iAHxProcessingOnlyTitle-gr.csv

```

**Comment by falbrito** [comment]
Processo criado.
Aguardando massa de dados real para colocar em linha.

**Comment by falbrito** [comment]
Dados reais foram disponibilizados. O conteúdo foi validade na instância de teste do COVID-19 "borda preta".

![image](https://user-images.githubusercontent.com/6940371/98281421-8358b780-1f7b-11eb-990d-c995792a2e91.png)

**Comment by falbrito** [comment]
@marcoslmori , por gentileza preparar a tradução para o label de base de dados "GREY-COVIDWHO" conforme abaixo:

Inglês --> Grey literature
Espanhol --> Literatura gris
Português --> Literatura cinzenta

Demais idiomas fazer a tradução pelo google translate

Obrigado

**Comment by marcoslmori** [comment]
Feito na instancia de teste, agora solicitado para sincronizar na produção

**Comment by marcoslmori** [comment]
chamado ocomon para o ITI  sobre sincronização dos arquivos texts,ini: 7569

**Comment by marcoslmori** [comment]
validado na produção!
