### ISSUE TITLE
Verificar linhas de autor com problema na separação

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#409]
Avaliar o que está ocorrendo nas linhas de autor do arquivo who-covid-19-repo-export2iAHxProcessingOnlyAuthors.csv pois não está sendo realizado a devida separação regrada por pipe "|"

Evidência:
```
serverofi5:/bases/oai.pmh/csv.rec/covidwho $ cat who-covid-19-repo-export2iAHxProcessingOnlyAuthors.csv | grep -v "|" | wc -l
25928

operacao@serverofi5:/bases/oai.pmh/csv.rec/covidwho $ cat who-covid-19-repo-export2iAHxProcessingOnlyAuthors.csv | grep -v "|" > x1
operacao@serverofi5:/bases/oai.pmh/csv.rec/covidwho $ mx seq=x1";" create=x2 -all now
operacao@serverofi5:/bases/oai.pmh/csv.rec/covidwho $ mx x2 lw=0 "pft=if size(v2)>20 then v2/ fi" now | wc -l
5139



```

**Comment by renatomurasaki** [comment]
@heitorbarbieri parece que esse erro de Nov/2020 ainda persiste. Vide registro recente disponível em 

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1271098
