### ISSUE TITLE
Desenvolver processamento para arquivo de Updates de COVID-19

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#410]
Este terá 2 etapas de preparação:

Fábio
- Processo incremental de adição de registros a sua base completa
- Conversão arquivos CSV em Isis

Marcelo
- Integração e utilização do arquivo ISIS à base de covidwho para atualização.

**Comment by falbrito** [comment]
Criação da base ISIS de update realizada para continuidade no processo
```
serverofi5:/bases/oai.pmh/wrk/covidwho_upd $ ll final.*
-rw-rw-r-- 1 operacao operacao 117760 Nov  4 11:02 final.mst
-rw-rw-r-- 1 operacao operacao    512 Nov  4 11:02 final.xrf

```

**Comment by botturam** [comment]
Já estou atualizando os docs com a chamada de covid_upd_docs.sh dentro de pos_coleta_covidwho.sh

**Comment by renatomurasaki** [comment]
@falbrito @botturam obrigado pela conclusão. Por favor, informar equipe da OMS.
