### ISSUE TITLE
Adicionar ao processamento do índice regional cópia para o servidor basalto01

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/db-processing#412]
Para efeitos de teste de balanceamento de carga do índice regional  precisamos que no processo regular de atualização do índice regional seja realizada também a transferência dos dados para o servidor basalto01.

Relacionado ao issue https://github.com/bireme/iahx-server/issues/1

**Comment by botturam** [comment]
rotina de transferência criada. Execução manual ainda, procurando o melhor momento para fazer a trasnferência.

É necessário que o Marco configure a rotina que promove a "virada" do diretório index.new para index

transfer@basalto01:/home/javaapps/iahx-server/indexes/solr5-port6/portal/data/index.new$ ll
total 449524996
-rw-rw-r-- 1 transfer users  47515375726 Nov  4 18:41 _12v0.fdt
-rw-rw-r-- 1 transfer users     21840363 Nov  4 18:41 _12v0.fdx
-rw-rw-r-- 1 transfer users        96945 Nov  4 22:06 _12v0.fnm
-rw-rw-r-- 1 transfer users 100341363876 Nov  4 21:45 _12v0_Lucene50_0.doc
-rw-rw-r-- 1 transfer users 206028806709 Nov  4 21:45 _12v0_Lucene50_0.pos
-rw-rw-r-- 1 transfer users   3037788344 Nov  4 21:45 _12v0_Lucene50_0.tim
-rw-rw-r-- 1 transfer users     63149262 Nov  4 21:45 _12v0_Lucene50_0.tip
-rw-rw-r-- 1 transfer users    898369391 Nov  4 21:46 _12v0.nvd
-rw-rw-r-- 1 transfer users          356 Nov  4 21:46 _12v0.nvm
-rw-rw-r-- 1 transfer users          546 Nov  4 22:06 _12v0.si
-rw-rw-r-- 1 transfer users 102332645778 Nov  4 22:06 _12v0.tvd
-rw-rw-r-- 1 transfer users     74024625 Nov  4 22:06 _12v0.tvx
-rw-rw-r-- 1 transfer users          170 Nov  4 22:07 segments_hhn
-rw-rw-r-- 1 transfer users            0 Aug 15 02:29 write.lock

**Comment by viniciusandrade** [comment]
@botturam, obrigado pela implementação da rotina. 

Na próxima semana vou iniciar os testes, também de forma manual da execução da instância adicional do Solr do índice regional .... dependendo do resultado destes testes vou formalizar com o Marco a inclusão da rotina de "virada" do índice regional também no basalto01.

**Comment by botturam** [comment]
A cópia está sendo feita com sucesso para o basalto01 e o basalto02. Já foram feitos 2 processamentos exitosos.

Realmente os problemas da semana passada se deram em função do horário de término mais adiantado, após às 06:00, hora da "virada".

Vou continuar monitorando esta semana.

**Comment by viniciusandrade** [comment]
@botturam obrigado pelos ajustes e acompanhamento.

Caso amanhã (17/11) tenha sucesso novamente o processamento e o índice esteja sincronizado corretamente entre os dois servidores posso iniciar o teste do balanceamento jogando requisições para a basalto01 para acompanhar esta semana?

**Comment by botturam** [comment]
estou testando a rotina que desloca a execução do MarkAbstract do processamento do IAHx-Portal para a fase de geração dos XMLs das fontes de informação, assim economizo esse tempo para poder realizar as transferências dos índices SoLR5 para os servidores de produção.

Hoje será a primeira execução. Creio que na 5f estará disponível em produção regular.

**Comment by botturam** [comment]
processo de transferência regular do índice SoLR5-Portal para BASALTO01 e BASALTO02 concluído. Ao final de cada processamento IAHx-Portal em OFI5, será enviada uma cópia para os 2 servidores de produção.

**Comment by viniciusandrade** [comment]
@botturam,
Verifiquei que o processo de atualização de hoje (30/11) apresentou alguma falha pois no diretório da BASALTO01 consta 238G de arquivos e na BASALTO02 o total é de 434G. 

Favor quando possível verificar. Obrigado

**Comment by botturam** [comment]
ao final do dia 30/11, alguma rotina realizou indevidamente, fora de hora, o processamento do Portal transferido no período da tarde do mesmo dia. Aparentemente, aconteceu às 19h:

transfer@basalto01:/home/javaapps/iahx-server/indexes/solr5-port6/portal/data$ ll -tcr
total 12
drwxr-s--- 2 root     tomcat 4096 Nov 11 09:43 tlog
drwxrwsr-x 2 transfer tomcat 4096 Nov 30 19:00 index.old
drwxrwsr-x 2 transfer tomcat 4096 Nov 30 19:00 index

Precisamos descobrir o que está causando essa virada neste horário. Verificarei amanhã, dia 01/12 novamente. Sábado e domingo não acontece. Aparentemente, apenas nos dias úteis, de 2f a 6f.

Eu só tenho acesso ao usuário transfer, mas não consegui descobrir nada com ele. Tem o usuário TOMCAT, mas não tenho a senha neste servidor.

**Comment by viniciusandrade** [comment]
entendido ... acho melhor você entrar em contato com o suporte para que eles possam te passar a lista de tarefas agendadas em cron para o usuário root.

**Comment by botturam** [comment]
estou monitorando o basalto01 hora a hora com o Marco, para pegar o erro no flagrante. Só assim para chegar a uma conclusão.

**Comment by botturam** [comment]
O Marco ficou de arrumar o shell da virada em basalto01, que estava virando tudo junto com os horários da COVIDWHO, e não apenas às 05:59

**Comment by viniciusandrade** [comment]
OK, como hoje os índices estavam pareados nos dois servidores subi com o apoio do Anderson o balanceamento de carga que esta funcionando desde as 11:00 para verificarmos a questão de aumento de carga do servidor basalto01.

**Comment by botturam** [comment]
amanhã, 04/12, não haverá virada, pois o processamento atrasou hoje.

**Comment by botturam** [comment]
basalto01 está recebendo a transferência do índice SOLR5 de OFI5 há muitas horas e parece que não vai terminar até às 06:00. Começou às 18h de 2f... sem dúvida é a transferência mais longa até agora. 

No momento, não consigo logar no servidor, que está muito lento. Qualquer comando leva 20s ou 30s ou mais para executar.

comando TOP:

top - 02:05:19 up 2546 days, 19:53,  4 users,  load average: 35.01, 35.35, 35.49
Tasks: 157 total,   1 running, 156 sleeping,   0 stopped,   0 zombie
Cpu(s): 29.9%us,  3.5%sy,  0.0%ni, 11.1%id, 55.5%wa,  0.0%hi,  0.1%si,  0.0%st
Mem:  65931804k total, 64431480k used,  1500324k free,    66824k buffers
Swap: 19530748k total,  1775160k used, 17755588k free, 22021004k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
11446 root      20   0 9507m 1.6g 254m S   15  2.5 622:37.85 java
 8918 root      20   0 60924  46m  812 D   11  0.1  22:21.91 rsync
13003 root      20   0  471g  29g 4.4g S    9 46.7  68:02.83 java
   52 root      20   0     0    0    0 D    8  0.0   5733:08 kswapd0
   53 root      20   0     0    0    0 D    6  0.0   4131:47 kswapd1
15836 root      20   0 37.8g 6.8g  24m S    2 10.9   7:47.40 java
29398 transfer  20   0 22180  760  180 D    1  0.0  47:36.81 rsync
18037 transfer  20   0 6127m 131m 5876 S    0  0.2   1:30.62 java
18639 zabbix    20   0 68420  896  832 S    0  0.0   1089:17 zabbix_agentd
18643 zabbix    20   0 68420  636  512 S    0  0.0  73:04.36 zabbix_agentd
27417 transfer  20   0 7180m 1.0g 6072 S    0  1.6   3:23.44 java
29249 transfer  20   0 59832 6012  908 S    0  0.0  67:31.88 sshd

----------
Para a basalto02, foi normal:

Indice transferido: portal
Processo de transferencia dos dados  (total)    de (1) 2020-12-07 14:09:27 ate (1) 2020-12-07 17:44:28 (  12901[s] ou 03:35:01)
Periodo de ocupacao do canal de transmissao de (1) 2020-12-07 14:09:52 ate (1) 2020-12-07 15:32:04 (   4932[s] ou 01:22:12)
Tempo para garantir a qualidade da operacao de (1) 2020-12-07 15:32:04 ate (1) 2020-12-07 17:42:45 (   7841[s] ou 02:10:41)
Quantidade de dados transferida 455555452 bytes (ou 435G bytes)

**Comment by botturam** [comment]
No momento, basalto01 está normal:

top - 15:22:08 up 2547 days,  9:10,  6 users,  load average: 20.92, 22.14, 21.09
Tasks: 159 total,   1 running, 158 sleeping,   0 stopped,   0 zombie
Cpu(s): 72.6%us,  1.3%sy,  0.0%ni,  6.8%id, 18.8%wa,  0.0%hi,  0.4%si,  0.0%st
Mem:  65931804k total, 65677576k used,   254228k free,    12204k buffers
Swap: 19530748k total,   188652k used, 19342096k free, 21823108k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
12937 root      20   0 9485m 1.6g 265m S   78  2.5 400:28.92 java
26390 root      20   0  471g  30g 5.0g S   20 48.0  98:52.44 java
 8918 root      20   0 60468  44m  692 D    9  0.1 104:59.35 rsync
   53 root      20   0     0    0    0 S    2  0.0   4156:39 kswapd1
11944 root      20   0 37.8g 6.8g  24m S    2 10.8  28:35.48 java
 2335 transfer  20   0 7503m 2.2g 7280 S    1  3.5   3:35.90 java
   52 root      20   0     0    0    0 S    1  0.0   5837:06 kswapd0
 1991 snmp      20   0 50956 1100  552 S    0  0.0 583:28.96 snmpd
32368 root      20   0     0    0    0 S    0  0.0   0:00.10 kworker/0:0
32689 transfer  20   0 17340 1348  980 R    0  0.0   0:00.07 top

**Comment by botturam** [comment]
transferência índice SoLR5 para basalto02 (3h18min):

Indice transferido: portal
Processo de transferencia dos dados de (2) 2020-12-08 16:53:33 ate (2) 2020-12-08 20:12:31 (  11939[s] ou 03:18:59)
Periodo de ocupacao do canal de transmissao de (2) 2020-12-08 16:53:55 ate (2) 2020-12-08 18:36:13 (   6138[s] ou 01:42:18)
Tempo para garantir a qualidade da operacao de (2) 2020-12-08 18:36:13 ate (2) 2020-12-08 20:10:59 (   5686[s] ou 01:34:46)
Quantidade de dados transferida 455574032 bytes (ou 435G bytes)

já para basalto01:
início:  20:12:32
fim (não terminado, pois o próximo processamento entrou): 05:40:06 
Dec 09 05:40:06 serverofi5 sendemail[6408]: ERROR => You must specify at least one recipient via -t, -cc, or -bcc
*** FAIL +++ ERRO fatal - rsync to basalto01 - enviaDados_basalto01_comMD5.sh  *** EXIT CODE (9) ***

Não é possível garantir a transferência do índice SoLR5 para basalto01, sem antes saber o que executa neste servidor e qual horário seria o mais indicado para isso.

**Comment by viniciusandrade** [comment]
OK, estou parando o teste de balanceamento do índice visto que os servidores ficaram com dados diferentes e ao realizar refresh na interface pode-se notar a diferença de totais quando a requisição é enviada para um servidor ou outro:

![basalto01](https://user-images.githubusercontent.com/349287/101645236-e3c49400-3a14-11eb-83cc-435304b72649.png)

![basalto02](https://user-images.githubusercontent.com/349287/101645258-ea530b80-3a14-11eb-8006-5f4dfdb3e828.png)

**Comment by botturam** [comment]
mudei os horários e a ordem de transferência do índice do Portal regional. Parece que está bem e com bastante folga.

O Marco ainda não acertou o shell da "virada" em basalto01. Neste momento, às 18h do dia 14/12, ele virou indevidamente.

Já comuniquei-o do problema, e ele disse que verificará amanhã, dia 15/12

**Comment by botturam** [comment]
Vinícius, a atualização do índice Portal-SoLR5 está sendo feita em basalto02 e basalto01, já há 2 meses, sem problemas. 

Podemos  fazer os testes de balanceamento de carga.

**Comment by viniciusandrade** [comment]
@botturam OK, vou verificar uma data para poder retomar este teste.

**Comment by ChicoLopes** [comment]
@botturam a “virada” é composta por um conjunto de rotinas que devem ser executadas na devida sequência. Tais ações principiam em serverofi5 ao término do processamento de cada índice de instância IAHx com a rotina endiaDados.new.sh (/bases/iahx/exec/enviaDados.new.sh), cujo argumento de chamada é a sigla de identificação da instância (portal; pmm; covidoms; etc.) e por uma coleção de possíveis opções de execução (-d; -H; -T; -x entre outras).
Este shell se guia pela tabela de configuração de processamento iAHx.tab composta de 36 colunas e se vale do conteúdo de algumas dessas colunas (1; 2; 4; 5; 6; 7; 8; 9; 10; 11; 19; 30; 31; e 36) para desempenhar sua função, que é transferir o conjunto de arquivos de índice da instância para o servidor de produção e eventualmente para um servidor par de balanceamento.
O processo se baseia em criar um diretório temporário no(s) servidor(es) destino, transferir para lá os arquivos do índice; por meio de um checksum MD5 garantir a correta transferência dos dados, renomear o diretório temporário de destino para sua denominação de aguardo por atualização (xxx.now para xxx.new), gerar um arquivo de permissão de atualização composto de três linhas de texto (data e hora dos dados; expressão de busca para efeito de teste; e resultado esperado) e finalizar o seu processo transferindo para o destino tal arquivo  de sinalização de permissão de atualização.
No servidor de produção (ou par de balanceamento), deve ser executado por agendamento a rotina de verificação de permissão de atualização, incluindo a própria função de atualização. O controle de tarefas agendadas (crontab) deve chamar o shell ReiniciaTodosIAHX.new.sh (nome inapropriado, sendo sugerido alterá-lo para VerAtualizaIAHX.sh), localizado em /home do servidor. Esta rotina chama a função efetiva de atualização de índices IAHx e ao seu retorno emite um e-mail de aviso de execução dos índices residentes no servidor.
A função de atualização é desempenhada por outro shell denominado atualizaIAHx.new.sh, localizado em /home/javaapps/iahx-server/bin. As tarefas sequenciais executadas por ele são: interromper a execução dos servidores Solr ativos; verificar a existência de arquivos de permissão de atualização (flags) e a cada um encontrado em /home/javaapps/iahx-server/indexes, efetuar a rotação de diretórios contendo o conjunto de arquivos no índice atualmente servido com o que contém o conjunto de arquivos do novo índice; disparar a execução do servidor Solr; efetuar uma busca segundo a expressão contida no arquivo de permissão de atualização comparando o resultado obtido com o esperado (também contido no arquivo de permissão); havendo divergência de valores os diretórios com os arquivos de índice são retornados à sua condição inicial e o servidor Solr é reiniciado e emitido um e-mail informando a ocorrência; para o caso de concordância de valores é emitido um e-mail de sinalização de atualização concluída; por fim o arquivo de permissão de atualização é apagado.
Para dar apoio à tarefa de atualização há um outro shell, denominado ReiniciaTodosIAHXsv.new.sh, localizado no diretório /home/javaapps/iahx-server/bin, que não efetua a rotação de diretórios de arquivos dos índices, no entanto para e reinicia todos os servidores Solr.
Estão assim envolvidos os seguintes shells:
Em serverofi5: enviaDados.new.sh
Em basalto01: ReiniciaTodosIAHX.new.sh e ReiniciaTodos IAHSXsv.sh
Em basalto02: ReiniciaTodosIAHX.new.sh e ReiniciaTodos IAHSXsv.sh
Estes cindo shells são objeto dos chamados 412; 564; 565 presentes no GitHub.
A atual situação é de rotinas criadas/alteradas/adaptadas e no aguardo por uma oportunidade para sua execução monitorizada para efeito de teste homologatório, uma vez que todos os testes estáticos possíveis foram realizados, observando que esta execução obrigatoriamente necessita de envolvimento ativo por parte do ITI, uma vez que OFI não tem os direitos de acesso necessários para a operação plena dos servidores de produção e par de balanceamento (basalto01 e basalto02).

**Comment by botturam** [comment]
Ficou decidido que não faremos o balanceamento de instâncias nos servidores Basalto01 e 02 porque o sistema não se mostrou confiável. Futuramente, com um melhor amadurecimento das tecnologias envolvidas, tenhamos mais condições de implementá-lo por nós mesmos ou com a ajuda de um consultor.
