### ISSUE TITLE
Realizar coleta IMSEAR - searo

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#420]

**Comment by falbrito** [comment]
Fluxo de coleta, criação de base de dados, arquivo XML e indexação realizados.
Atualizado em produção.

Total de registros - 203.456
![image](https://user-images.githubusercontent.com/6940371/99258907-fd98ff80-27f7-11eb-86be-48c82652dbe6.png)

**Comment by renatomurasaki** [comment]
@falbrito excelente notícia! Muito obrigado!
Por favor, manter coleta mensal.

**Comment by falbrito** [comment]
Pontos para análise:

1. O total de registros disponibilizados na interface OAI-PMH é de 203.555.
![image](https://user-images.githubusercontent.com/6940371/99259427-c37c2d80-27f8-11eb-9667-645902b966c6.png)




 Durante o processo de coleta observou-se que ocorre erro na tentativa de coleta do range 171600 conforme trecho do arquivo de log da coleta:
```
---> Acessando: http://imsear.searo.who.int/oai/request?verb=ListRecords&resumptionToken=dim////171600
[harv]              ERROR: 503 - Service Unavailable 
```
Com isso, ocorre perda de um range de 100 registros

2. O total da interface de busca IMSEAR difere do total oferecido no na interface OAI-PMH
Interface IMSEAR – 203.856 registros
![image](https://user-images.githubusercontent.com/6940371/99260748-916bcb00-27fa-11eb-88bc-d700a71335c3.png)
Interface OAI-PMH - 203.555 registros
![image](https://user-images.githubusercontent.com/6940371/99260795-a2b4d780-27fa-11eb-99be-492739322289.png)
