### ISSUE TITLE
Verificar arquivo de duplicados da Elsevier após mudança no processo, utilizando o XML do iAHx

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#421]
@falbrito @botturam o Zubair da Elsevier informou que há novo arquivo na área de FTP com a indicação de registros duplicados após mudança no processo, utilizando o XML do iAHx. O arquivo com registros duplicados parece ser incremental e, sendo assim, precisaremos adaptar o nosso processo interno.

**Comment by falbrito** [comment]
Arquivo baixado do SFTP da Elsevier. 

Total de registros - 785

```
operacao@serverofi5:/bases/oai.pmh/xml.rec/bkp_Elsevier/Arquivo_Deduplicacao $ mx Potential_WHO_Duplicates_TAB "pft=v1/" now | wc -l
785

```

**Comment by falbrito** [comment]
Processo incremental criado.

`serverofi5:/bases/oai.pmh/xml.rec/bkp_Elsevier/Arquivo_Deduplicacao/concatena_Duplicates.sh`

Este shell faz a concatenação do arquivo incremental com o arquivo que acumulará todos os envios. O arquivo ISIS full resultante está disponível para uso em:
```
serverofi5:/bases/oai.pmh/xml.rec/bkp_Elsevier/Arquivo_Deduplicacao/
-rw-rw-r--  1 operacao operacao 14813696 Nov 16 15:26 Potential_WHO_Duplicates_TAB.mst
-rw-rw-r--  1 operacao operacao    29184 Nov 16 15:26 Potential_WHO_Duplicates_TAB.xrf


```
