### ISSUE TITLE
Diferenças nos números de processamento registrados no serverofi.bireme.org e interface iAHx

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#422]
@botturam a página http://serverofi.bireme.org/docs/est/2020/dbstatus_202010.html mostra que a WPRIM tem 786.451 registros. Na interface iAHx mostra 779.936. Na mesma página, a EMRO tem 110.115 e na interface iAHx mostra 207.163.

Eu mantenho uma planilha com base nos dados do serverofi para informar aos membros do GLG da OMS o crescimento do GIM. Por favor, verifique os dados disponíveis no serverofi.

**Comment by botturam** [comment]
Sobre WPRIM, a diferença entre 786.451 - 779.936 = 6.515 docs diz respreito aos documentos repetidos nos 81 XMLs atualmente usados para o processamento.

Sobre a EMRO, não há repetidos. O número correto é de 207.163 docs. Na página do serverofi está um número de 2017.

Vou modificar o modo como os números são calculados em /bases/lilG4/tpl.lil/gerestXML.sh

**Comment by renatomurasaki** [comment]
Perfeito! Obrigado! Quando alterar, favor fechar este issue.

**Comment by falbrito** [comment]
Revisão realizada.
