### ISSUE TITLE
Fazer uma tabela de compatibilização do TC-Legis para o FI-ADMIN de Leisref

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#428]

**Comment by anakatiacamilo** [comment]
Tabela de Compatibilização
https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/FI-ADMIN/Migration/AR-Legisalud/TCLegisAR2FIADMINLeisref.xlsx?d=wad549a8c008e474b890cc03e7cf1f887&csf=1&web=1&e=unGzOd

**Comment by renatomurasaki** [comment]
Issue relacionado ao #392
