### ISSUE TITLE
Verificar a devida conversão para a data no processamento Pentaho

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#429]
Verificar a devida conversão para a data no processamento Pentaho.

![image](https://user-images.githubusercontent.com/6940371/99975296-d22a8d80-2d80-11eb-9b28-63d3a79e3438.png)

**Comment by renatomurasaki** [comment]
Este campo foi substituido pelo 'D Date' ao passar a receber Excel do sistema Distiller
