### ISSUE TITLE
Revisar campo de textos completos da base de dados LIPECS (Perú) publicado no IAHx Perú e Portal Regional

### ISSUE THREAD

**Issue by marcoslmori** [bireme/db-processing#434]
O conteúdo contem o documento com path  local

Exemplo:  http://pesquisa.bvsalud.org/portal/resource/en/biblio-1046551

**Comment by anakatiacamilo** [comment]
Fiz uma lista das URLs e passei no Check links, no momento do check encontramos 1870 links que não estavam funcionando vou encaminha a lista para a pessoal responsável da base LIPECS.
