### ISSUE TITLE
Adicionar na exportação do XML da instancia de IAHx do GIM o elemento entry_date para as bases não LILACS

### ISSUE THREAD

**Issue by marcoslmori** [bireme/db-processing#437]
Adicionar na exportação do XML da instancia de IAHx do GIM o elemento entry_date para as bases não LILACS. 

Exemplo: https://pesquisa.bvsalud.org/gim/resource/es/emr-199922
xml: https://pesquisa.bvsalud.org/gim/?output=xml&lang=es&from=&sort=&format=&count=&fb=&page=1&index=tw&q=id%3Aemr-199922

Obrigado, 

Mori

**Comment by botturam** [comment]
inclusão de entry_date em AFRO. 2f estará em produção

/bases/lilG4/afr.lil/datacleaner/afr.prc

/* entry_date */
|a91^Y|v100^a.8|^Y|,

**Comment by marcoslmori** [comment]
ok!

**Comment by marcoslmori** [comment]
Marcelo, essa proc se refere a todos as bases que não são LILACS, certo?

**Comment by botturam** [comment]
sim, mas preciso ver se esse campo existe nas outras FIs-GIM. Por enquanto, apenas AFRO.

**Comment by botturam** [comment]
campo entry_date não existe nas FIs requisitadas.
