### ISSUE TITLE
Incluid no Google Search Console (antigo webmaster) o bvsalud.org

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#438]

**Comment by botturam** [comment]
Não vai dar conflito com as outras já cadastradas?

**Comment by renatomurasaki** [comment]
@botturam entendo que não. Se fosse dar conflito teria dado nas diferentes instancias de pesquisa.bvsalud.org/xxxx
O que acha?

**Comment by botturam** [comment]
Posso tentar cadastrar **https://bvsalud.org/** , já que https://pesquisa.bvsalud.org/ é o mesmo que **https://pesquisa.bvsalud.org/portal** (que já é cadastrado)

**Comment by renatomurasaki** [comment]
Essa é a proposta, @botturam - https://bvsalud.org --> o site da BVS Regional usando WordPress.

**Comment by botturam** [comment]
Cadastro em:

https://search.google.com/u/1/search-console?resource_id=sc-domain%3Abvsalud.org&hl=pt

Foi validada a nova propriedade "bvsalud.org" e iinserido o domínio bvsalud.org no servidor de DNS da BIREME.
