### ISSUE TITLE
Hanseniase - diferença no resultado de processamento

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#444]
Observando o resultado disponível após o processamento dos temas na BVS HANSEN -  https://pesquisa.bvsalud.org/hansen/?lang=pt percebi que há uma diferença significativa nos resultados comparados ao portal regional, considerando as bases de dados incluídas na BVS Hanseniase.

Por exemplo: na estratégia aplicada para o filtro epidemiologia a Medline conta com mais de 6.600 documentos , enquanto que na BVS Hansen aparece pouco mais de 3 mil. O mesmo tema recupera pela estratégia mais de 1200 docs na Lilacs e na BVS somente 1027, a base Hanseniase tem uma diferença de 500 docs do Portal Regional para a BVS. 

Outro exemplo é o tema Aspectos sociais que recupera no total mais do 2 mil documentos enquanto que na BVS cerca de 300.

O recorte geral, ainda em processamento, deverá recuperar perto de 58 mil documentos. Hoje a BVS conta com menos de 40 mil. 
Solicito verificar. Obrigada

**Comment by botturam** [comment]
a diferença é por causa de docs MEDLINE que não foram marcados pelas  estratégias IAHx:

-rw-rw-r-- 1 operacao operacao 7791 Nov 19 14:53 HANSENIASE-tratamento_medicamentoso.sch
-rw-rw-r-- 1 operacao operacao 6661 Nov 19 14:53 HANSENIASE-reabilitacao.sch
-rw-rw-r-- 1 operacao operacao 5464 Nov 19 14:53 HANSENIASE-prevencao_controle.sch
-rw-rw-r-- 1 operacao operacao 6321 Nov 19 14:53 HANSENIASE-epidemiologia.sch
-rw-rw-r-- 1 operacao operacao 6661 Nov 19 14:53 HANSENIASE-diagnostico.sch
-rw-rw-r-- 1 operacao operacao 5323 Dec  3 15:37 HANSENIASE-historia.sch

Terei que fazer um processamento completo de MEDLINE, o qual chamamos de Blocão-MEDLINE (1966-2019). Vai levar aproximadamente 2 semanas.

**Comment by pintoros** [comment]
Obrigada Marcelo, vou informar a contraparte.

Abraço



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:64d87b5a-6d05-46af-8a1a-5164f96da1e2]

________________________________
De: botturam <notifications@github.com>
Enviado: quinta-feira, 10 de dezembro de 2020 16:46
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Hanseniase - diferença no resultado de processamento (#444)


a diferença é por causa de docs MEDLINE que não foram marcados pelas estratégias IAHx:

-rw-rw-r-- 1 operacao operacao 7791 Nov 19 14:53 HANSENIASE-tratamento_medicamentoso.sch
-rw-rw-r-- 1 operacao operacao 6661 Nov 19 14:53 HANSENIASE-reabilitacao.sch
-rw-rw-r-- 1 operacao operacao 5464 Nov 19 14:53 HANSENIASE-prevencao_controle.sch
-rw-rw-r-- 1 operacao operacao 6321 Nov 19 14:53 HANSENIASE-epidemiologia.sch
-rw-rw-r-- 1 operacao operacao 6661 Nov 19 14:53 HANSENIASE-diagnostico.sch
-rw-rw-r-- 1 operacao operacao 5323 Dec 3 15:37 HANSENIASE-historia.sch

Terei que fazer um processamento completo de MEDLINE, o qual chamamos de Blocão-MEDLINE (1966-2019). Vai levar aproximadamente 2 semanas.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F444%23issuecomment-742753938&data=04%7C01%7Cpintoros%40paho.org%7Ce9dd20bb52b84e9eafad08d89d44406f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637432263750869737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=neJo%2Bmv7al1gL9Im4dfPe7iDMQqCBCZaPfMrXv19Yqo%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4EB3DDEY27LI3EJCC3SUEQQJANCNFSM4UT7XBFQ&data=04%7C01%7Cpintoros%40paho.org%7Ce9dd20bb52b84e9eafad08d89d44406f%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637432263750869737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4CTuacxwY9%2B1mltmZCHfj7ab8IZK6QpVTLlQqBzdQqw%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
