### ISSUE TITLE
WHO COVID-19 DB: registros sem ano de publicação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#448]
Há mais de 12 mil registros sem ano de publicação:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?output=site&lang=en&from=101&sort=&format=summary&count=20&fb=&page=6&skfp=&index=tw&q=*+and+not+year_cluster%3A%28%222020%22+OR+%222019%22%29

1) Aproximadamente 40 são de 2021, mas o cluster de ano de publicação não mostra 2021 como opção, somente 2020 e 2019
2) Alguns são WHO COVID e não foram enriquecidos. Para estes, por favor, gerar uma lista de ref-id e título para enviar à equipe da OMS
3) Os demais me parecem ser preprints do medRxiv e bioRxiv. Favor verificar se é um erro no processamento ou se de fato este campo não existe nos metadados coletados.
4) Há alguns Elsevier e LILACS que tampouco não mostram ano de publicação.

**Comment by botturam** [comment]
Sobre year_cluster:"2021", passou a entrar no proc de ontem, 18h, e diz respeito a MEDLINE. No momento, o cluster "year_cluster" ("da") já está aparecendo na IAHx-COVIDWHO (513 docs).

Sobre as demais bases, o formato que determina a geração do campo acima estava com uma limitação:

if val(v65[1].4) > 1900 and val(v65[1].4) <= val(left(date,4))**+2** then

Eu deixei o formato igual ao do MEDLINE, adicionando 2 anos a mais à data corrente, no filtro de validação da mesma.

Já executei na elsevier e na covidwho (sem enriquecimento) e já computo:

45   docs em Elsevier-Covidwho 
736 docs em Covidwho

Vamos aguardar o processamento de hoje.

**Comment by renatomurasaki** [comment]
@botturam obrigado! Sobre medRxiv e bioRxiv, realmente não vem o ano de publicação nos metadados?

**Comment by renatomurasaki** [comment]
@botturam @falbrito creio que o ano de publicação dos preprints de medRxiv e bioRxiv podem ser extraídos do elemento json 'rel_date'

**Comment by botturam** [comment]
eu não encontrei nas bases ISIS este campo. Vou falar com o Fábio para ver se é possível extrairmos no início do processo.

**Comment by falbrito** [comment]
@renatomurasaki , sim atualmente o elemento rel_date ja é utilizado para criar o campo entry_date

![image](https://user-images.githubusercontent.com/6940371/102660469-d9637200-4159-11eb-8508-57f155fab07a.png)

![image](https://user-images.githubusercontent.com/6940371/102660664-28a9a280-415a-11eb-8be0-6e7203629c08.png)

**Comment by falbrito** [comment]
@renatomurasaki vou fazer a criação do campo

**Comment by falbrito** [comment]
Campo "da" incorporado no XML de indexação
![image](https://user-images.githubusercontent.com/6940371/102664455-93121100-4161-11eb-839b-13d7b4e6c623.png)

Estará disponível no próximo processamento.

**Comment by botturam** [comment]
"da"=2021 disponível em produção.

Database
  WHO COVID (610)
  MEDLINE (545)
  ELSEVIER (44)
  LILACS (Americas) (7)
