### ISSUE TITLE
Cadastrar em Google Search Console as URL https dos sites.bvsalud.org que já estão registrados apenas com http

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#451]

**Comment by botturam** [comment]
Foram cadastradas as seguintes instâncias faltantes de IAHX em https:

https://pesquisa.bvsalud.org/brasil
https://pesquisa.bvsalud.org/controlecancer/
https://pesquisa.bvsalud.org/cvsp/
https://pesquisa.bvsalud.org/fiocruz
https://pesquisa.bvsalud.org/ses

Falta verificar, nos próximos dias, como o GOOGLE indexará as páginas indicadas.
