### ISSUE TITLE
Inclusão de ensaios clínicos do ICTRP na interface do WHO COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#456]
O ICTRP/WHO está disponibilizando os ensaios clínicos sobre COVID-19 sistematicamente em 2 formatos:

CSV - https://bit.ly/3po1own
XML - https://bit.ly/2KAwTom

Ambos os links estão disponíveis na seguinte página - https://www.who.int/clinical-trials-registry-platform

Proposta versão 1.0 de mapeamento de campos para o iAHx, baseando-se no nome dos campos XML (aparentemente o mesmo nome das colunas do CSV)

```
iAHx --> clinical trial

ti               --> <Public_title>
au               --> <Primary_sponsor>
db               --> "ICTRP"
type             --> "clinical trial register"
collection       --> "clinical trial registers"
da               --> <Date_registration3>  (está em formato ISO YYYYMMDD)
ab               --> <Intervention> + <Primary_outcome> + <Inclusion_Criteria> + <Exclusion_Criteria> (manter essa ordem e separar cada elemento com <br/><br/> )
entry_date       --> <Date_registration3>
id               --> "ictrp-" + <TrialID>
ur               --> <web_address>
fo               --> <Source_Register> + ";" + <Date_registration>
```
A atualização dos registros de ensaios clínicos será sempre full, de acordo com o comportamento dos arquivos CSV e XML que a OMS disponibiliza. Entendo que a periodicidade possa ser semanal.

Favor realizar essa integração nas duas primeiras semanas de janeiro para apresentar à equipe da OMS na terceira semana no ambiente de testes.

**Comment by botturam** [comment]
Observação: sobre a correspondência dos campos, "da" e "entry_date" são a mesma coisa (Date_registration3):

"da"=v65
|    <field name="da">|v8^*[1].6|</field>|/,

"entry_date"=v91
if p(v8) then
  '    <field name="entry_date">'f(val(v8[1]),1,0)'</field>'/
fi,

**Comment by falbrito** [comment]
Desenvolvido o processo para conversão do arquivo XML COVID19-web.xml para arquivo XML Solr ictrp_regional.xml.

O resultado pode ser observado no ambiente de testes de Covid-19
[https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/?lang=en](https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/?lang=en)

Observações:
1) O total de 7815 registros corresponde ao arquivo baixado de [https://bit.ly/2KAwTom](https://bit.ly/2KAwTom) na data de hoje - 21/01/2021.

2) O campo de id formado como **ictrp- + TrialID** precisou ser normalizado. Em alguns registros existe o "/" na sua string, o que impossibilita a indexação do Solr. Foi realizado a substituição de "/" por ""

Exemplo do campo id:
```
Antes
ictrp-CTRI/2021/01/030169

Agora após tratamento
ictrp-CTRI202101030169

```
Dessa forma sugiro a inclusão do TrialID no campo Fonte para melhor referenciar o registro na origem.
Exemplo:
_CTRI; 01-01-2021; TrialID: CTRI/2021/01/030169_

**Comment by renatomurasaki** [comment]
@falbrito excelente! Muito obrigado!
Concordo com a sua sugestão do TrialID no campo Fonte. Por favor, pode incluir. Assim que reprocessar, me avise para poder comunicar a equipe da OMS.

**Comment by renatomurasaki** [comment]
@falbrito deu para perceber que alguns registros de ensaio clínico no arquivo disponibilizado pelo ICTRP não são sobre a COVID, pois tem alguns com ano de publicação abaixo de 2019. Vou reportar isso para a OMS também, para ver se criamos uma regra para eliminar registros com ano inferior a 2019.

**Comment by falbrito** [comment]
@renatomurasaki, realizado o reprocessamento incorporando TrialID à fonte.

**Comment by renatomurasaki** [comment]
@falbrito obrigado! Comunicarei OMS.

**Comment by falbrito** [comment]
@renatomurasaki, realizado a correção no resumo.

**Comment by renatomurasaki** [comment]
@falbrito obrigado! Aguardemos reação da equipe da OMS sobre meu último e-mail.

**Comment by renatomurasaki** [comment]
@falbrito incluir no campo ab do XML do iAHx o elemento <Condition> do XML do ICTRP. Pode ser antes de Intervention.

**Comment by botturam** [comment]
resultado disponível em produção.
