### ISSUE TITLE
Avaliar o campo Database dos metadados originais do WHO COVID-19 para enriquecer o cluster Database

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#459]
Quando o registro WHO COVID-19 não é enriquecido durante o processamento, o mesmo recebe a denominação "WHO COVID" no cluster Database. Entretanto, há no metadado original informação no campo Database que poderá ser utilizado para reclassificar estes registros.

Haverá necessidade de normalização, uma vez que este campo não é controlado na entrada de dados da OMS.

**Comment by falbrito** [comment]
Verificado a necessidade de inclusão do campo **Database** na conversão do formato Excel para CSV

**Comment by renatomurasaki** [comment]
Resolvido em #488
