### ISSUE TITLE
Formatação do campo ab quando o campo é proveniente de registros de ensaios clínicos (ICTRP)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#460]
@falbrito para melhorar a leitura do abstract, resultante da concatenação dos campos realizada no issue #456 :

`<Condition> + <Intervention> + <Primary_outcome> + <Inclusion_Criteria> + <Exclusion_Criteria>`

Por favor, seguir a seguinte estrutura no momento de criar o field 'ab' :

```
<h2>Condition:</h2>
<Condition>

<h2>Intervention:</h2>
<Intervention>

<h2>Primary outcome:</h2>
<Primary_outcome>

<h2>Criteria:</h2>
<Inclusion_Criteria> + <Exclusion_Criteria>
```

**Comment by falbrito** [comment]
@renatomurasaki, realizado.

**Comment by renatomurasaki** [comment]
@falbrito o texto `<h2>Primary outcome</h2>` ficou quebrado em `<h2>Primary</h2><h2>outcome</h2>`. Favor corrigir, por favor.

**Comment by falbrito** [comment]
O trecho em questão (Primary outcome) é inserido ao XML na seguinte forma:
```
&lt;h2&gt;Primary&#160;outcome:&lt;/h2&gt;
que é <h2>Primary outcome:</h2>

Obs.: &#160; é o mesmo que &nbsp; que simula um espaço. Anteriormente coloquei o texto apenas com o espaço do teclado e também não houve diferença
```
Abaixo o exemplo de um registro com essa formatação:
![image](https://user-images.githubusercontent.com/6940371/105550463-3960b180-5ce0-11eb-8e97-6861f058db09.png)

Ao realizar o processamento para indexação é criado o campo "mark_ab" com o conteúdo do campo "ab" tratado. E é nesse momento que ocorre o problema.
```
torna-se no campo “mark_ab”
&lt;h2&gt;Primary&#160;&lt;h2&gt;outcome:&lt;/h2&gt;&lt;/h2&gt;
que é <h2>Primary <h2>outcome:</h2></h2>
```
Ou seja, é inserido um `<h2>` e `</h2>` indevidamente ao campo "mark_ab"
Esse campo "mark_ab" no arquivo XML é responsável pela mostragem do resumo na vizualização do registro.
![image](https://user-images.githubusercontent.com/6940371/105550811-9ceadf00-5ce0-11eb-8b1a-abe1aa25be6f.png)

Verificarei junto ao @heitorbarbieri o que pode estar acontecendo

**Comment by renatomurasaki** [comment]
@falbrito isso ocorre porque o markab coloca `<h2>` nos títulos das seções de um resumo estruturado e a palavra 'outcome' é um token reconhecido como título de seção.

Vamos publicar mesmo assim e depois incorporamos a correção.
