### ISSUE TITLE
Registros sem informação de autor na base WHO COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#461]
É possível identificar os documentos sem informação de autor na planilha abaixo

[MissingAuthors.xlsx](https://github.com/bireme/db-processing/files/5873384/MissingAuthors.xlsx)

Verifiquei que de fato o campo autor está vazio e a equipe da OMS verificou que no Distiller este campo está presente.

Exemplo:
https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1027466

Esse documento foi ingressado em 20210118

**Comment by botturam** [comment]
durante a execução de pos_coleta_covidwho.sh, havia um registro -- recém adicionado -- com muitas ocorrências de autores, quebrando no comando abaixo

# =============================================================================
echo "+ Authors ..."
mx x2 from=2 "proc=if p(v2) and v2:'|' then 'Gsplit=2=|' fi" append=x3 -all now
. log
