### ISSUE TITLE
Incluir no XML iAHx (WHO COVID-19 e BVS Regional) metadado que determina o link entre preprint e artigo de periódico

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#464]
Este metadado deve permitir criar o relacionamento entre um documento preprint e o documento do artigo de periódico que foi publicado via processo de peer-review.

@heitorbarbieri discutir esta inclusão com o @botturam por afetar o processamento de dados e o @viniciusandrade por afetar a interface OPAC.

**Comment by botturam** [comment]
concluído. Detalhes no e-mail enviado hoje.

O schema.xml ficou com 2 novos campos (os 2 campos são repetitivos):

   <field name="id_pprint"                   type="string"   indexed="true"  stored="true"   multiValued="true"/>   
   <field name="id_published"             type="string"   indexed="true"  stored="true"   multiValued="true"/>

falta colocar em atualização regular.

**Comment by botturam** [comment]
o processamento está em teste e produção, e também já retirei os "grey" da planilha.

**Comment by renatomurasaki** [comment]
Obrigado, Marcelo!

Para acompanhamento dos registros que estão sendo relacionados, poderia criar um índice de busca, tipo preprintlinked:1, olhando o campo "id_pprint"?

**Comment by renatomurasaki** [comment]
@botturam vou encerrar este chamado. Depois de testarmos no COVID, abrirei outro chamado para incluir na BVS Regional.
