### ISSUE TITLE
Processamento dos metadados do ICTRP na interface da WHO COVID-19: eliminar ensaios clínicos anteriores a 2020

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#466]
Ao processar o XML do ICTRP referente aos metadados dos registros de ensaios clínicos, criar regra para incluir na interface somente os registros com data de publicação a partir de 2020. Com essa regra, serão excluídos aprox. 52 ensaios clínicos publicados antes de 2020.

Solicitação feita pela equipe da OMS, após avaliarem a relevância destes 52 ensaios.

**Comment by botturam** [comment]
regra criada em serverofi5:/bases/oai.pmh/tpl.xml/criaXML.py

                # FILTRO >= 2020
                if y.tag == 'Date_registration3' and y.text and ( int(y.text[0:4]) >= 2020 ):

**Comment by botturam** [comment]
disponível em produção.

https://pesquisa.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?u_filter%5B%5D=fulltext&u_filter%5B%5D=db&u_filter%5B%5D=collection&u_filter%5B%5D=mj_cluster&u_filter%5B%5D=type_of_study&u_filter%5B%5D=clinical_aspect&u_filter%5B%5D=la&u_filter%5B%5D=year_cluster&u_filter%5B%5D=ta_cluster&fb=&where=&filter%5Bcollection%5D%5B%5D=10-clinical_trial_registers&range_year_start=&range_year_end=

**Comment by renatomurasaki** [comment]
@botturam obrigado!
