### ISSUE TITLE
Relação entre o tipo de ato normativo e os países da base Fatores de Risco de Doenças Não Transmissíveis se perdeu

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#467]
Algo aconteceu na lista controlada de Tipo de Ato que fez perder a relação entre o tipo com os países que publicam atos indexados na base Fatores de Risco de Doenças Não Transmissíveis.

Tipos de atos utilizados na base:
![image](https://user-images.githubusercontent.com/1226218/109692495-5dc56e80-7b67-11eb-8ebb-b00ae1f603d3.png)

Exemplos de perda do relacionamento entre ato e o país: Norma Técnica e Declaração

![image](https://user-images.githubusercontent.com/1226218/109692747-a2e9a080-7b67-11eb-923d-068eebdbfa33.png)

Ao editar o registro 2531, o campo Tipo de Ato não apresenta o tipo Norma Técnica no campo correspondente
![image](https://user-images.githubusercontent.com/1226218/109692950-d9bfb680-7b67-11eb-80b2-620995733306.png)

O mesmo ocorre ao editar o registro 2529
![image](https://user-images.githubusercontent.com/1226218/109693075-feb42980-7b67-11eb-8729-fa66e89d6bba.png)

Ao verificar a área de adminitração das listas, percebe-se que ambos os tipos de ato não estão associados com os respectivos países destes registros.

Fazendo um filtro pelo tipo de ato Declaração, percebe-se que o mesmo é utilizando, na base de Fatores de Risco pelos seguintes países:

![image](https://user-images.githubusercontent.com/1226218/109693409-61a5c080-7b68-11eb-98c3-e6a3649ffabf.png)

Pela área de administração das listas, este tipo de ato está relacionado apenas para Argentina e Perú.

@anakatiacamilo favor reestabelecer os relacionamentos entre tipo de ato e país da base de Fatores de Risco, utilizando a interface de busca https://sites.bvsalud.org/legislacion/factores-de-riesgo/ como referência para saber quais países adotam cada um dos tipos de atos utilizados na catalogação e indexaçãos dos 800 registros disponíveis.

**Comment by anakatiacamilo** [comment]
@renatomurasaki comecei a fazer a analise do Tipos de atos, dos atos que estão no índice Fatores de Risco de Doenças Não Transmissíveis, conforme a sua sugestão.

Dos 20 atos 10 estavam com problemas e olhando o histórico dos atos, eles estão com este problema desde 18 de Fevereiro de 2019 quando fizeram as alterações para o Perú, tinham outros atos com problemas que foram resolvido pontualmente antes desta data. Ontem arrumei a relação desses atos, normalizando pelo menos esta questão do Registros do Fatores de Risco.

O Tipo de Ato com maior problema e o Ordenanza que foi criado em 2018, mas infelizmente quem fez a lista para o Brasil criou o ato Portaria em 2019 como este ato já esta na base de legislação, para arrumar eu preciso alterar a base antes de arrumar a tabela de controle.

Segue a analise e o print dos históricos principalmente da atos Norma Técnica que com a relação estabelecida os formulários estão OK e o ato  Declaração que foi alterado para somente Perú em 2019 que me induziu o erro no momento de criar a lista para Argentina.

Não vou fechar este issue até terminar a analise de todos os Tipos de ato, ontem já comecei a analisar do Tipos de ato do Peru.

![analise_acttype](https://user-images.githubusercontent.com/19270675/109807114-3f618080-7c04-11eb-8a38-9ff73b974f3f.JPG)

![actTypeResolucion](https://user-images.githubusercontent.com/19270675/109804989-ab8eb500-7c01-11eb-9e94-b9b83be27fb0.JPG)
![actType_Decreto](https://user-images.githubusercontent.com/19270675/109805005-afbad280-7c01-11eb-8adc-918889146098.JPG)
![actType_Declaracao](https://user-images.githubusercontent.com/19270675/109805017-b2b5c300-7c01-11eb-98ed-c872e8cb14e0.JPG)
![actType_Portaria5](https://user-images.githubusercontent.com/19270675/109805024-b5b0b380-7c01-11eb-926e-b5d887684ad8.JPG)
![decretosupremo](https://user-images.githubusercontent.com/19270675/109805037-b8aba400-7c01-11eb-9c3d-53bf83284b76.JPG)
![actType_Normatecnica](https://user-images.githubusercontent.com/19270675/109805049-bba69480-7c01-11eb-9650-10e7dd8e2d08.JPG)
  ![actType_Portaria95Brasil](https://user-images.githubusercontent.com/19270675/109805884-beee5000-7c02-11eb-9302-d0f2150b223d.JPG)

**Comment by renatomurasaki** [comment]
obrigado, @anakatiacamilo . Faz sentido, porque me parece que a data do último registro entrado na base de Fatores de Risco, realizado pela consultora contratada à epoca, foi em 29 de janeiro de 2019. Reparo que as alterações feitas no tipo Declaração e Norma Técnica ocorreram depois desta data. Infelizmente não me lembro de algum evento com o Perú para realização destes ajustes e como as ações são feitas com o usuário admin, não é possível rastrear. Creio que é importante verificar a possibilidade de atribuir função admin para usuários individuais que tenham acesso ao usuário/senha admin.

Os registros de Perú que fazem parte da base Fatores de Risco foram ingressados no período de 20 de março a 30 de outubro de 2018.

**Comment by anakatiacamilo** [comment]
@renatomurasaki ontem conversei com o @viniciusandrade e ele resolveu a questão de atribuir a função de admin para os usuários individuais.

**Comment by renatomurasaki** [comment]
> @renatomurasaki ontem conversei com o @viniciusandrade e ele resolveu a questão de atribuir a função de admin para os usuários individuais.

excelente! obrigado!

**Comment by anakatiacamilo** [comment]
Os Tipos de ato do Fatores de Risco que estavam com problemas foram corrigidos.
