### ISSUE TITLE
Nova coleta do BUTANTAN-Dspace, de documentos de produção científica (IBProd)

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#468]
gerar uma nova instância de coleta de repositório Dspace para os documentos de produção científica.

OBS: O processamento regular de BUTANTAN-Sophia continua normalmento.

**Comment by botturam** [comment]
Processo de coleta e conversão concluído. Enviado para a contraparte validar.

**Comment by botturam** [comment]
Conversão dos demais tipos de documentos concluída.

Processamento e geração de XML-IAHx pronto.

**Comment by botturam** [comment]
Falta levar a afiliação. No IAHx, ela não é utilizada. 

Verificar se há necessidade.

**Comment by renatomurasaki** [comment]
@botturam estou encerrando este issue, pois o tema da afiliação está fora do padrão do nosso processamento, tendo em vista que o metadado do DSpace não garante a paridade. Vou abrir outro issue que ficará no nosso backlog para planejarmos uma solução que possa contemplar qualquer fonte de informação tipo DSpace que garanta pareamento da info de autor e afiliação.
