### ISSUE TITLE
Preprints de bioRxiv e medRxiv não estão entrando no cluster de Texto Completo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#469]
Conforme imagem abaixo, poucos preprints estão marcados no filtro Texto Completo
![image](https://user-images.githubusercontent.com/1226218/109850337-27ecbc80-7c31-11eb-9803-96b296baea76.png)

Percebe-se que os registros dos principais repositórios de preprint (medRxiv e bioRxiv), mesmo tendo o link para o texto completo do manuscrito, não estão marcados no cluster Texto Completo.

**Comment by botturam** [comment]
1) campo "fulltext" criado em  ppbiorvix_regional.xml  e  ppmedrvix_regional.xml:
<field name="fulltext">1</field>

2) sobre Pre-print-Covid (4699 docs), existem 295 docs com fulltext=1. 

Outros 24 docs perdem o campo "ur" e "fulltext" caso sejam das URLs abaixo (propositadamente, penso eu)

operacao@serverofi5:/bases/oai.pmh/csv.rec/covidwho $ grep mdl who-covid-19-repo-export2iAHxProcessingOnlyFullTextLink-pp.csv
2205;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32908947
2206;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32908946
2207;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32908945
2208;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32908948
2267;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32995364
2268;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32995366
2269;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32995367
2270;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32995365
2355;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32908948
2400;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33083498
2549;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33173802
2576;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33235895
2889;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33330741
6242;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33442558
6243;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33442560
6245;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33469559
6247;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33442559
6460;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32550253
6467;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33564697
6468;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33564696
6479;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32550242
6487;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33564698
8167;https://pesquisa.bvsalud.org/portal/resource/en/mdl-33688554
8174;https://pesquisa.bvsalud.org/portal/resource/en/mdl-32793769

**Comment by renatomurasaki** [comment]
@botturam coloque aqui, por favor, um trecho do XML/JSON que é coletado do bioRxiv/medRxiv

**Comment by botturam** [comment]
id:ppmedrxiv-21253782

(JSON)
,"version":"1","license":"cc_by_nc_nd","type":"PUBLISHAHEADOFPRINT","category":"infectious diseases"},{"rel_doi":"10.1101\/2021.03.17.21253782","rel_title":"B.1.1.7 became the dominant variant in Lebanon.","rel_date":"2021-03-17","rel_site":"medRxiv","rel_link":"https:\/\/medrxiv.org\/cgi\/content\/short\/2021.03.17.21253782","rel_abs":"Recently, a new variant of severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) designated VOC 202012\/01 (or B.1.1.7 lineage) has become highly prevalent in several countries, after first being described in the United Kingdom (UK). Its rate of transmission has been estimated to be increased compared to other lineages. In the present study, we show the emergence, dominance and the rapid spread of the B.1.1.7 lineage in Lebanon.","rel_num_authors":13,"rel_authors":[{"author_name":"Mahmoud younes","author_inst":"Beirut cardiac institute"},{"author_name":"Kassem Hamze","author_inst":"Lebanese University"},{"author_name":"Karen L. Osman","author_inst":"Public health england"},{"author_name":"Daniel P. Carter","author_inst":"public health england"},{"author_name":"Steven T Pullan","author_inst":"Public Health England"},{"author_name":"Miles Caroll","author_inst":"Public health england"},{"author_name":"Richard T Vipond","author_inst":"Public Health England"},{"author_name":"Nada Mohamad","author_inst":"University of Oxford"},{"author_name":"hassan nassar","author_inst":"bahman hospital"},{"author_name":"Mayssa Ghaddar","author_inst":"Bahman hospital"},{"author_name":"Mohammad Makki","author_inst":"Beirut cardiac institute"},{"author_name":"Paul Nguewa","author_inst":"University of Navarra"},{"author_name":"fadi Abdel Sater","author_inst":"Lebanese university"}],

**Comment by renatomurasaki** [comment]
@botturam Ok, obrigado!
