### ISSUE TITLE
Corrigir dashboard dos eixos transversais: o filtro pelos eixos está incorreto

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#470]

**Comment by anakatiacamilo** [comment]
Consegui fazer uma primeira versão, depois de publicado notei que tenho que fazer pequenos ajustes.
 
https://public.tableau.com/app/profile/bireme/viz/infometria-lilacs-ejes-transversales/Histria1

**Comment by anakatiacamilo** [comment]
Feito a trandução dos eixos transversais:
Género, Equidad, Etnicidad y Derechos Humanos
E o ajuste da legenda do gráfico "Cuales son los tipos de documentos publicados?"
