### ISSUE TITLE
Link do preprint para o artigo de periódico está ok, mas não existe o link do artigo de periódico para o preprint

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#474]
Ao acessar o preprint - https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/ppbiorxiv-915157 é possível ver que há um artigo de periódico baseado neste preprint.

Ao clicar no link See journal article e visualizá-lo - https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-2364  percebe-se que não há o link de volta, mostrando que há um preprint para este artigo de periódico.

**Tela de visualização dos metadados do preprint**
![image](https://user-images.githubusercontent.com/1226218/111204633-1c8c8000-85a5-11eb-8d7c-34affdcade67.png)

**Tela de visualização dos metadados do artigo de periódico**
![image](https://user-images.githubusercontent.com/1226218/111204799-3928b800-85a5-11eb-8e05-d7347a31f7fc.png)

**Comment by botturam** [comment]
disponível em produção.
