### ISSUE TITLE
Criar sitemap.xml e robots.txt na raíz do pesquisa.bvsalud.org

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#475]
Colocar dentro deste site map os 8 sitemapindex do /portal, 4 do /gim e 1 do /global-research-on-novel-coronavirus-2019-ncov

**Comment by botturam** [comment]
serão colocados na raiz do pesquisa.bvslud.org  os arquivos robots.txt e sitemap.xml

[sitemap.txt](https://github.com/bireme/db-processing/files/6207016/sitemap.txt)
[robots.txt](https://github.com/bireme/db-processing/files/6207017/robots.txt)

**Comment by renatomurasaki** [comment]
@botturam assim que colocar, atualize o issue, por favor. Conseguiu gerar procedimento para atualizar semanalmente o elemento <lastmod> do sitemap.txt?

**Comment by botturam** [comment]
procedimento foi incluído ao final do processamento semanal de geração de sitemaps:

serverofi5:/bases/IAHX_Sitemaps/apps/tpl/2-XMLs.sh

O resultado encontra-se em:

/bases/IAHX_Sitemaps/apps/BVS/**sitemap.xml**
/bases/IAHX_Sitemaps/apps/BVS/robots.txt  (este é estático, não gerado pelo proc. de sitemaps)

Falta eu combinar com o Marco e o Anderson para onde deverão ir em produção

**Comment by botturam** [comment]
Resultado em homologação:

transfer@ts10vm:/home/repository/sitemap$ ll
total 76
drwxrwxr-x 17 root     bvs      4096 Mar 25 18:29 ./
drwxrwsr-x 40 root     bvs      4096 Oct 10  2019 ../
drwxrwxr-x  3 root     bvs      4096 Oct 24  2019 brasil/
drwxrwxr-x  3 root     bvs      4096 Oct 24  2019 bvsms/
drwxrwxr-x  3 root     bvs      4096 Jan 21 08:35 controlecancer/
drwxrwxr-x  3 transfer bvs      4096 May 14  2020 covidoms/
drwxrwxr-x  3 root     bvs      4096 Oct 24  2019 cvsp/
drwxrwxr-x  3 transfer bvs      4096 Apr 30  2020 enfermagem/
drwxrwxr-x  3 transfer bvs      4096 Oct 25  2019 enfermeria/
drwxrwxr-x  4 transfer bvs      4096 Oct 24  2019 fiocruz/
drwxrwxr-x  7 transfer bvs      4096 Feb 20  2020 gim/
drwxrwxr-x  3 root     bvs      4096 Oct 16  2019 homeopatia/
drwxrwxr-x  3 root     bvs      4096 Oct 24  2019 odontologia/
drwxrwxr-x  9 root     bvs      4096 Jan 21 08:35 portal/
drwxrwxr-x  7 root     bvs      4096 Oct 24  2019 ripsa/
-rw-r--r--  1 transfer transfer   82 Mar 25 18:29 robots.txt
drwxrwxr-x  3 root     bvs      4096 Oct 24  2019 ses/
-rw-rw-r--  1 transfer transfer 2283 Mar 25 18:29 sitemap.xml
drwxrwxr-x  5 root     bvs      4096 Oct 24  2019 unifesp/

**Comment by botturam** [comment]
Aguardando contato do ITI para  efetivar a tarefa de atualização semanal.

**Comment by botturam** [comment]
O ITI diz que já estão atualizando semanalmente, entretanto eu não sei verificar se o arquivo sitemap.xml está, de fato, no raiz do pesquisa.bvsalud.org

**Comment by renatomurasaki** [comment]
@botturam melhor conversar com eles, pois talvez não tenha ficado claro. Veja que nem o sitemap, nem o robots, estão na raiz do pesquisa.bvsalud.org, pois está dando erro 404:

https://pesquisa.bvsalud.org/robots.txt
https://pesquisa.bvsalud.org/sitemap.xml

**Comment by renatomurasaki** [comment]
Validado e funcionando. Equipe Google Scholar já ciente
