### ISSUE TITLE
Incluir elemento author_inst presente no JSON do bioRxiv/medRxiv, referente a afiliação do autor (author_name)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#476]
Exemplo:

{"author_name":"Gargi Doulatani","author_inst":"Weill Cornell Medicine"},
{"author_name":"Michael W. O'Dell","author_inst":"Weill Cornell Medicine"},
{"author_name":"Joan Toglia","author_inst":"Mercy College"},
{"author_name":"Abhishek Jaywant","author_inst":"Weill Cornell Medicine"}

**Comment by renatomurasaki** [comment]
@botturam há algum avanço neste issue?

**Comment by botturam** [comment]
Inserido o novo campo "afiliacao author" em /bases/oai.pmh/tpl.json/cria_xml_BIORXIV.py

**createLineMed**("afiliacao_autor", item_authors['author_name'].encode('utf-8') + '; ' + item_authors['author_inst'].encode('utf-8') )
**createLineBio**("afiliacao_autor", item_authors['author_name'].encode('utf-8') + '; ' + item_authors['author_inst'].encode('utf-8') )

Aguardar o próximo processamento (hoje ainda).

**Comment by botturam** [comment]
BioRxiv funcionou (id:ppbiorxiv-136861), MedRxiv, não (má formação do XML).

**Comment by renatomurasaki** [comment]
@botturam por favor, poderia informar o endereço de coleta do bioRxiv e medRxiv?

**Comment by botturam** [comment]
A coleta é feita através da API  https://api.biorxiv.org/covid19/

**Comment by renatomurasaki** [comment]
@botturam esse link não funciona. Entendo que você quis dizer https://api.biorxiv.org/. E a coleta de medRxiv?

**Comment by renatomurasaki** [comment]
@botturam agora vi que a chamada começa com o token 0 - https://api.biorxiv.org/covid19/0 e bioRxiv e medRxiv relacionado a COVID estão todos juntos na mesma chamada da API

**Comment by renatomurasaki** [comment]
@botturam precisa entender a origem do erro que você reportou de XML mal formado no caso das afiliações dos preprints do medRxiv.

**Comment by botturam** [comment]
retirando "bicudos" do dado de afiliação: <okurzai@hygiene.uni-wuerzburg.de>

em /bases/oai.pmh/tpl.json/cria_xml_BIORXIV.py

createLineMed("afiliacao_autor", item_authors['author_name'].encode('utf-8').replace("<","").replace(">","") + '; ' + item_authors['author_inst'].encode('utf-8').replace("<","").replace(">","")

**Comment by botturam** [comment]
disponível em produção.

**Comment by renatomurasaki** [comment]
@botturam obrigado! Excelente!
