### ISSUE TITLE
Informação de afiliação de autores dos registros Medline e LILACS não está aparecendo na interface WHO COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#477]
Exemplo ao comparar o mesmo registro em:

Na BVS Regional - https://pesquisa.bvsalud.org/portal/resource/pt/mdl-33651706

Na WHO COVID-19 - https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1133828

**Comment by renatomurasaki** [comment]
@botturam há algum avanço neste issue?

**Comment by botturam** [comment]
o dado de afiliação consta no XML de processamento.  Falta a declaração no _schema.xml_:

<field name="afiliacao_autor"             type="string"   indexed="false" stored="true"   multiValued="true" />

Processamento em andamento...




 Verei com o Vinícius.

**Comment by botturam** [comment]
disponível em teste:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1133828

**Comment by renatomurasaki** [comment]
@botturam excelente

**Comment by botturam** [comment]
Disponível em produção
