### ISSUE TITLE
Telemedicina

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#478]
Segue o filtro para uso no contexto do TC/93 - TA2
Resultado em 07/04/2021 -  111.355 documentos
[Estrategia_busca_ehealth_042021.txt](https://github.com/bireme/db-processing/files/6274542/Estrategia_busca_ehealth_042021.txt)

**Comment by renatomurasaki** [comment]
@botturam esse processamento deve gerar os arquivos de tabulação para geração de indicadores infométricos, via Tableau

**Comment by botturam** [comment]
estabelecidada coleta regular semanal para geração do arquivo de IDs:

operacao@serverofi5:/bases/Strategies2IAHX/apps/ids_iahx/telemedicina $ ll
total 5108
-rw-rw-r-- 1 operacao operacao 5224567 Apr 12 11:21 **TELEMEDICINA_full.ids**
-rw-rw-r-- 1 operacao operacao     130 Apr 12 11:21 totais.txt

**Comment by renatomurasaki** [comment]
@botturam favor manter a cópia regular dos arquivos de tabulação na área de dados da bismuto (data lake Dremio). Avise-me por aqui assim que tiver disponível.

**Comment by renatomurasaki** [comment]
@botturam por favor, copiar os arquivos de tabulação desta estratégia de busca na bismuto01 para que eu possa iniciar o processa de geração de indicadores infométricos.

**Comment by botturam** [comment]
@renatomurasaki depois me diga se vc prefere todos os temas num único arquivo  -- junto com todos os outros ex:1) --, ou 

FI|SCH|ID|SUB
LILACS|RHS|lil-17612|educacion
LILACS|TELEMEDICINA|lil-17618
LILACS|TEMASPRIORITARIOS|lil-17684|equidade
LILACS|EVITAIS|lil-17687
LILACS|TEMASPRIORITARIOS|lil-17742|equidade
LILACS|RHS|lil-17779
LILACS|CGAN|lil-17893|organizacao_atencao_nutricional
LILACS|CGAN|lil-17893|vigilancia_alimentar_nutricional
LILACS|RHS|lil-15863|distribucion_RRHH
LILACS|RHS|lil-15863|planificacion_distribucion_RHS
LILACS|RHS|lil-15863|planificacion_RHS

2) LILACS_id_telemedicina.txt
    FI|SCH|ID
    LILACS|TELEMEDICINA|biblio-112
    LILACS|TELEMEDICINA|biblio-207
    LILACS|TELEMEDICINA|biblio-306
    LILACS|TELEMEDICINA|biblio-320
    LILACS|TELEMEDICINA|lil-458
    LILACS|TELEMEDICINA|lil-803

**Comment by renatomurasaki** [comment]
@botturam obrigado, vou checar. Por favor, nas próximas vezes, não criar diretório old e não mover os arquivos anteriores para este diretório. Simplesmente atualize os arquivos para não afetar o funcionamento do Dremio.

**Comment by renatomurasaki** [comment]
@botturam prefiro como você fez, deixando todos os temas em um único arquivo **lilacs_id_tema_subtema.txt**

**Comment by renatomurasaki** [comment]
@botturam por favor, gere o mesmo para Medline, colocando a tabulação na bismuto01. Pode manter todos os temas no mesmo arquivo.

**Comment by botturam** [comment]
foram feitas a marcações dos registros segundo a estratégia geral e foram geradas as tabulações, disponíveis em:

bismuto01:/home/data/LILACS_tab
bismuto01:/home/data/MEDLINE_tab/TELEMEDICINA/

bismuto01c1:/home/data/LILACS_tab
bismuto01c1:/home/data/MEDLINE_tab/TELEMEDICINA/

**Comment by botturam** [comment]
@renatomurasaki assentamento indicando que terminou

**Comment by renatomurasaki** [comment]
@botturam obrigado! Creio que esteja faltando nas tabulações de Medline o arquivo **lilacs_id_tema_subtema.txt**. Sem ele não consigo identificar os subtemas. Para telemedicina não tem problema porque não há subtema, mas para os demais temas, por exemplo CGAN, vai precisar.

**Comment by botturam** [comment]
@renatomurasaki vou gerar novamente o TELEMEDICINA com um novo arquivo MEDLINE_id_tema_subtema.txt
