### ISSUE TITLE
Realizar trocas no DB do FI-ADMIN das URL's dos registros migrados devido a alteração de domínio

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/db-processing#479]
Confirmado pelo Oscar em 16/04 que o domínio que será utilizado para o projeto é o: **e-legis-ar.msal.gov.ar**

URL onde ficarão os textos completos: **e-legis-ar.msal.gov.ar/htdocs/legisalud/migration/pdf/**

**Comment by anakatiacamilo** [comment]
Confirmando o Replace no MySQL
De:
https://legis-ar.msal.gov.ar/legisalud/migration/
Para:
https://e-legis-ar.msal.gov.ar/htdocs/legisalud/migration/

Exemplos nos três tipo de documento:
https://legis-ar.msal.gov.ar/legisalud/migration/html/454.html
https://e-legis-ar.msal.gov.ar/htdocs/legisalud/migration/html/454.html

https://legis-ar.msal.gov.ar/legisalud/migration/pdf/454.pdf
https://e-legis-ar.msal.gov.ar/htdocs/legisalud/migration/pdf/454.pdf

https://legis-ar.msal.gov.ar/legisalud/migration/xml/454.xml
https://e-legis-ar.msal.gov.ar/htdocs/legisalud/migration/xml/454.xml

**Comment by viniciusandrade** [comment]
Obrigado Katinha.
