### ISSUE TITLE
Enriquecimento do campo idioma - base WHO COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#481]
@botturam utilizei as planilhas Excel que a equipe da OMS compartilhou com toda a base de dados da COVID (core, preprints e grey literature) exportada com os campos de ID e idioma. Seguem CSV gerados para cada uma delas com o ID, o campo de idioma original e o campo de idioma em formato ISO que usamos (2 caracteres). Com esses CSV já é possível atualizar o campo idioma para aqueles registros marcados ainda como base de dados WHO COVID (que não foram enriquecidos com MDL, LILACS, WPRIM e Elsevier).

Quando há mais de um idioma, o valores estão separados por pipe.
[who-covid-id-lang-langiso.zip](https://github.com/bireme/db-processing/files/6360173/who-covid-id-lang-langiso.zip)

**Comment by renatomurasaki** [comment]
@botturam favor considerar este outro arquivo
[who-covid-id-lang-langiso.zip](https://github.com/bireme/db-processing/files/6360370/who-covid-id-lang-langiso.zip)

**Comment by botturam** [comment]
olhando a tabela who-covid-id-lang-langiso-core.csv, noto que não há o campo idioma nesses ids da planilha principal (who-covid-19-repo-export2iAHxProcessing.csv):

1) who-covid-19-repo-export2iAHxProcessing.csv:717431;2020;;;;429-436;;18/08/2020;
    717431;English;en (who-covid-id-lang-langiso-core)

2) who-covid-19-repo-export2iAHxProcessing.csv:716074;2020;;11;7;813-825;;18/08/2020;
    716074;English;en (who-covid-id-lang-langiso-core)

3) who-covid-19-repo-export2iAHxProcessing.csv:1045998;2021;;22;;22;33482671;27/01/2021;;MEDLINE
    1045998;German;de (who-covid-id-lang-langiso-core)

acho que primeiro temos que verificar se estamos recebendo integralmente o campo idioma nas planilhas de vimos processando.

**Comment by renatomurasaki** [comment]
@botturam creio que o campo idioma não estava sendo processado pelo PENTAHO no início do projeto. Creio que faz 1 ou 2 meses que o @heitorbarbieri incorporou. O mesmo ocorreu com o campo Database

**Comment by botturam** [comment]
correto. Só existe "la" em nos docs de 05/03/2021 em diante. Vou montar uma tabela de gizmo geral a partir do conteúdo das 3 tabelas recebidas.

**Comment by renatomurasaki** [comment]
ok. Sobre o enriquecimento do campo idioma a partir destes arquivos, seria bom pensar em algo "genérico" ou "customizável", pois outros campos serão enriquecidos com dados contidos no Distiller, como por exemplo, Database (já estou trabalhando com esse campo e vou abrir outro issue).

**Comment by botturam** [comment]
campo de idioma ("la") normalizado tanto em IAHx-COVID-19 como IAHx-GIM
