### ISSUE TITLE
Avaliar se é possível incluir no XML iAHx do WHO COVID-19 os ID originais quando o registro é enriquecido

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#482]
@botturam seria apenas incluir no XML o ID original de Medline, LILACS e outras bases de dados, quando o registro é enriquecido, mantendo intacto o atual ID que vem do MS Excel (RefID). Será que poderia utilizar o elemento alternate_id?

**Comment by botturam** [comment]
o ID original é o campo "id_pk", que coincide sempre com o próprio campo "id", mas sem a string inicial "covidwho-"

Há também os campos "alternate_id", indicando documentos que foram eliminados por duplicação. Neste caso, eu crio sempre o alternate_id com e sem a string inicial "covidwho-", pois isso já significou algo no passado. Se formos usá-lo para alguma coisa, é bom revisar seu histórico de constituição.

Exemplo:

    <field name="id">covidwho-1207382</field>

    <field name="id_pk">1207382</field>
    <field name="alternate_id">920849</field>
    <field name="alternate_id">covidwho-920849</field>
    <field name="alternate_id">991182</field>
    <field name="alternate_id">covidwho-991182</field>

**Comment by renatomurasaki** [comment]
@botturam quando falo de ID original é a identificação na sua base de origem, ou seja, Medline, LILACS etc. Como podemos manter no XML o PMID, o LILACSID (biblio-*), etc, quando o registro na base COVID foi enriquecido?

**Comment by renatomurasaki** [comment]
@botturam Nesse seu exemplo, seria onde armazenar no XML o ID mdl-33179265 ou 33179265, que é o ID Medline na BVS ou o PMID, respectivamente.

**Comment by renatomurasaki** [comment]
@botturam creio que poderia colocar no alternate_id. O efeito será que o documento também poderá ser encontrado na interface WHO COVID-19 através do seu ID na sua fonte de dados original.

**Comment by renatomurasaki** [comment]
@botturam favor retomar este issue

**Comment by botturam** [comment]
conforme  conversa com o Heitor, foi inserido o PMID num novo campo ("original_id") do MEDLINE-Covidwho. Para buscar no Portal Regional, basta acrescentar "mdl-" na frente desse PMID.

O alternate_id não era um bom campo, pois atualmente ele é preenchido com os ids que originalmente tinham o prefixo "covidwhomdl-" e também os ids de documentos deduplicados com o documento em questão.

Ficou assim:

\<field name="id">covidwho-1305892\</field>
\<field name="original_id">34038385\</field>

**Comment by renatomurasaki** [comment]
@botturam excelente. Favor fazer o mesmo para os registros enriquecidos com LILACS e demais bases usadas neste processo (PAHOIRIS, WHOIRIS etc)

**Comment by botturam** [comment]
@renatomurasaki @heitorbarbieri  coloquei o original_id nas seguintes FIs:

Elsevier
LILACS
PAHOIRIS
WPRIM
WHOIRIS

dúvida: coloquei o campo original em todas elas, como fiz no MEDLINE; não o campo que consta na IAHx. É isso mesmo?

    <field name="id">covidwho-864904</field>
    <field name="original_id">817580</field>  (no IAHx, o id seria **wpr-817580**)

**Comment by renatomurasaki** [comment]
@botturam e @heitorbarbieri na minha opinião, em todas, incluindo MDL, deveríamos colocar o prefixo, pois este é o ID original que identifica unicamente os documentos dentro das nossas interfaces. Procedimentos como o do @heitorbarbieri que precisa do PMID deve tratar o original_id para retirar o prefixo.

**Comment by botturam** [comment]
alterações realizadas. Ficou assim:

1) MEDLINE: mdl-"PMID"
2) LILACS: como todos começam originariamente por "biblio-", então nada muda neste caso.
3) WPRIM: wpr-"v2"
4) PAHOIRIS: phr-"v2"
5) WHOIRIS:who-"v2"
6) Elsevier: também não recebe prefixo, pois ela não está em nehuma outra IAHx. Fica com o ID original sem prefixo.

Aguardar o proc. de hoje, que já está em curso.

**Comment by renatomurasaki** [comment]
@botturam ao olhar o XML da interface iAHx, não encontro o elemento <field name="original_id">

**Comment by botturam** [comment]
colocado campo "original_id" em:

/home/javaapps/iahx-server/indexes/covidoms/main/conf/schema.xml

   \<field name="original_id"                 type="string"   indexed="true"  stored="true"   multiValued="true"/>

**Comment by botturam** [comment]
já estão disponíveis no XML:

Ex1:
id:covidwho-864904
<arr name="original_id">
<str>wpr-817580</str>
</arr>

Ex2:
id:covidwho-1558983
<arr name="original_id">
<str>biblio-1339843</str>
</arr>
