### ISSUE TITLE
Total de registros por base de dados é diferente do total de registros disponíveis na interface iAHx GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#484]
De acordo com o cluster Database do iAHx do GIM:

![image](https://user-images.githubusercontent.com/1226218/116307097-488e4a00-a77c-11eb-977d-67a3d25afae4.png)

O total de registros por base de dados é 2.152.219. 

Entretanto, o total disponível na interface
![image](https://user-images.githubusercontent.com/1226218/116307198-652a8200-a77c-11eb-84d4-acac31ae1c61.png)

é de 2.189.245

**Comment by botturam** [comment]
havia um problema com a marcação de docs com collection_gim:"LILACS", mostrando no cluster "base de dados"   (collection_gim) menos registros que o nro de docs de LILACS.

a diferença entre docs com *instance:"ghl"* menos  collection_gim:* era de mais ou menos 25.000 docs. Agora, está zerada.

instance:"ghl" and not collection_gim:*
