### ISSUE TITLE
Normalizar campo de idioma no GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#485]
Acessar o seguinte link para ver todos os valores do cluster Language

https://pesquisa.bvsalud.org/gim/?u_filter%5B%5D=fulltext&u_filter%5B%5D=collection_gim&u_filter%5B%5D=mj_cluster&u_filter%5B%5D=type_of_study&u_filter%5B%5D=la&fb=la%3A60&lang=en&_charset_=UTF-8&index=&q=&where=&range_year_start=&range_year_end=&range_year_start=&range_year_end=#la

**Comment by renatomurasaki** [comment]
@botturam por favor, ajustar as traduções do filtro de idioma da interface do GIM asap.

**Comment by botturam** [comment]
está processando desde ontem à noite. Aguardar amanhã cedo.

**Comment by botturam** [comment]
concluído e disponível em produção no idioma inglês da interface IAHx-Covid

**Comment by renatomurasaki** [comment]
@botturam ainda faltam alguns códigos para ajustar:

No : Norwegian
Ch: Chinese (o correto é ZH, mas o CH provavelmente vem do CHI em ISO-639-2B/)
Ed: chequei o texto completo do arquivo e na verdade está em inglês - EN

**Comment by renatomurasaki** [comment]
Resolvido
