### ISSUE TITLE
Ajustar traduções e corrigir valores inválidos no cluster Language da interface de busca WHO COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#486]

**Comment by botturam** [comment]
campo "la" (language) normalizado nas FIs normalizado nas seguintes FIs, através da nova tabela lilG4/tabs/**gGIM_lang40.seq**:

- covidwho (core)
- medline
- lilacs
- wprim
- elsevier
- preprint
- grey-literature

Foi criada também nova rotina única (**lilG4/shs.lil/insereLAcovidwho.sh**) para inserção dos campos "la" nas FIs covidwho (core), preprint e grey-literature, a partir dos CSVs abaixo: 

a) who-covid-id-lang-langiso-core.csv
b) who-covid-id-lang-langiso-grey-literature.csv
c) who-covid-id-lang-langiso-preprints.csv

Foram alterados os arquivos texts.ini em produção a fim de contemplar novos idiomas ainda não identificados.

**Comment by renatomurasaki** [comment]
@botturam obrigado. Temos um grande avanço. Ainda persistem os seguinte códigos neste campo que podem ser mapeados da seguinte maneira:

- No : Norwegian
- Jp : Japan (olhando o texto completo - o jp vem provavelmente do iso 3 caracteres jpn)
- Kr : Kanuri
- Am : Amharic
- Bn : Bengali
- Gu : Gujarati
- Kk : Kazakh
- Man : Chinese (olhando o texto completo - deve ser man de mandarim)
- Mr : Marathi
- Mt : Maltese
- Om : Oromo
- Te : Telugu
- Ti : Tigrinya
- Tl : Tagalog
- Tur : Turkish
- Ur : Urdu

fonte: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Segue anexo um arquivo tabulado com todas as traduções para retroalimentar a configuração do iAHx (deveríamos ter como padrão todos estes idiomas), assim como processo de enriquecimento de dados, pois este arquivo associa as diferentes variações da ISO-639.
[iso-639-language.zip](https://github.com/bireme/db-processing/files/6428257/iso-639-language.zip)

**Comment by marcoslmori** [comment]
@botturam e @renatomurasaki vou pegar essa tabela que o Renato passou e configurar na instancia de teste no inglês.  Estando validado, vou replicar para outros idiomas e ai a gente sincroniza na produção.  Pode ser assim, ou tem alguma outra etapa que tem que ser feita?

**Comment by botturam** [comment]
Os XMLs da IAHx já estão bem, mas falta acertar no texts.ini.

em COVID, esses novos  códigos que faltam texto são todos de Literature-Grey, que inderi no processante de ontem em COVID-Iahx.

em GIM, a mesma coisa. Falta levar o texts.ini para produção.

**Comment by marcoslmori** [comment]
Ajustei o texts.ini em inglês e pela validação está ok. vou pedir para sincronizar para a produção e traduzir os outros idiomas   

Observação: 
Juntei as configurações  do GIM  + as recomendações do Renato.  

A tradução do nome lógico (no="Norwegian") está sendo ajustado pelo Marcelo, porque esse código é palavra reservada do sistema

Comparando com as configurações atuais  mantive as duplicações de tradução com nome lógico diferentes

ja="Japanese" jp="Japan" 
zh="Chinese" man="Chinese" 
tur="Turkish"  tr="Turkish"
vie="Vietnamese" vi="Vietnamese" 
 
idiomas adicionados no texts.ini 

;novos
am="Amharic"
az="Azerbaijani"
bi="Bislama"
bn="Bengali"
gu="Gujarati"
kr="Kanuri"
km="Khmer"
kk="Kazakh"
lo="Lao"
jp="Japan"
man="Chinese"
mr="Marathi"
ml="Malayalam"
mn="Mongolian"
mt="Maltese"
nr="Ndebele, South"
ny="Chichewa, Nyanja"
om="Oromo"
sn="Shona"
te="Telugu"
ti="Tigrinya"
tl="Tagalog"
tur="Turkish"
ur="Urdu"
vi="Vietnamese"
wo="Wolof"

**Comment by renatomurasaki** [comment]
@marcoslmori trocar Japan para Japanese (escrevi errado no meu comentário).

@marcoslmori @botturam não tem problema ter mais de um código com o mesmo label?

**Comment by marcoslmori** [comment]
Está ocorrendo a tradução duas vezes desse idioma:  ja="Japanese" jp="Japanese".  Esse ajuste é no processamento certo?

**Comment by renatomurasaki** [comment]
@marcoslmori minha pergunta é se com esta configuração, o total de ja e de jp se somam para mostrar o total correto de Japanese.

**Comment by botturam** [comment]
jp é incorreto. O correto é ja (japonês). 

Já consertei o dado nos XMLs de grey-literature e covid-core.

**Comment by renatomurasaki** [comment]
@marcoslmori @botturam essa fonte é mais completa 

https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt

**Comment by botturam** [comment]
campo normalizado tanto em IAHx-COVID-19 como IAHx-GIM
