### ISSUE TITLE
Enriquecimento do campo database - base WHO COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#488]
@botturam utilizei as planilhas Excel que a equipe da OMS compartilhou com toda a base de dados da COVID (core, preprints e grey literature) exportada com os campos de ID e database. Seguem CSV gerados para cada uma delas com o ID, o campo de database original e o campo de database "normalizado", seguindo, quando possível, a codificação já existente. Com esses CSV já é possível atualizar o campo database para aqueles registros marcados ainda como base de dados WHO COVID (que não foram enriquecidos com MDL, LILACS, WPRIM e Elsevier).

Quando há mais de um database, os valores estão separados por pipe.

[who-covid-id-db-dbstd.zip](https://github.com/bireme/db-processing/files/6394647/who-covid-id-db-dbstd.zip)

**Comment by renatomurasaki** [comment]
@botturam com o enriquecimento do campo database, perderemos a precisão na identificação daqueles registros que não foram enriquecidos, tendo tem vista que podemos ter registros não enriquecidos que terão como base de dados Medline, LILACS, WPRIM etc. Por favor, criar um campo que possa ser indexado e que nos permita identificar os registros enriquecidos e não enriquecidos.

**Comment by botturam** [comment]
@heitorbarbieri  indique-me quando for feito o ajuste de delimitador (; por |) no campo Base de Dados da planilhas principais de cada fonte de informação (Ex: who-covid-19-repo-export2iAHxProcessing.csv)

1160634;2021;;12;3;765-783;;06/04/2021;;"Agricultural & Environmental Science Collection; Coronavirus Research Database; ProQuest Central";en
1160310;2021;;73;;115-116;;06/04/2021;;"Agricultural & Environmental Science Collection; ProQuest Central";en
1160534;2021;;4;1;;;06/04/2021;;"Coronavirus Research Database; ProQuest Central";en

**Comment by renatomurasaki** [comment]
@heitorbarbieri @botturam Conforme e-mail recem enviado pela Deborah, que lhes coloquei em cópia, sobre a identificação de registros da "Indonesian Research", esse issue se torna prioritário e urgente.

**Comment by botturam** [comment]
Disponível em produção cluster "db" (Base de dados) - FIs COVID-core, Grey-COVID e PP-COVID. 

Os conteúdos foram normalizados (tabs/gCampo4.seq) e enriquecidos com as planilhas:

who-covid-id-db-dbstd-core.csv
who-covid-id-db-dbstd-grey-literature.csv 
who-covid-id-db-dbstd-preprints.csv

**Comment by renatomurasaki** [comment]
@botturam tendo em vista que o campo database não é normalizado no sistema de entrada de dados da OMS, você conseguirá utilizar os arquivos csv who-covid-id-db-dbstd-*.* para criar um gizmo para ser aplicado nos próximos processamentos?

**Comment by botturam** [comment]
o gizmo que já é aplicado no campo 4 de todas as FIs do COVID segue anexo
[gCampo4.txt](https://github.com/bireme/db-processing/files/6556445/gCampo4.txt)

**Comment by renatomurasaki** [comment]
@botturam ok, Marcelo! Entendo que esse gizmo inclui a normalização contida nos arquivos csv `who-covid-id-db-dbstd-.*`
Obrigado

**Comment by heitorbarbieri** [comment]
@renatomurasaki - Cluster com "Indonesian Research" já presente na interface de busca.
@botturam - Troca de delimitador (; por |) no campo Base de Dados da planilhas realiza. Favor verificar.
