### ISSUE TITLE
Problema na visualização dos descritores e qualificadores no iAHx para registros da IBECS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#49]
Ao recuperar documentos da [IBECS na BVS Regional](http://pesquisa.bvsalud.org/portal/?lang=pt&from=0&sort=&format=summary&count=20&fb=&page=1&filter%5Bcollection%5D%5B%5D=06-national%2FES&q=&index=tw) e visualizar um documento qualquer, os decritores e qualificadores apresentam os tags de subcampo.
Vide imagem abaixo para o [primeiro documento retornado](http://pesquisa.bvsalud.org/portal/resource/pt/ibc-160527):
![image](https://cloud.githubusercontent.com/assets/1226218/24814993/02991848-1baa-11e7-8a0a-370c610bf8bf.png)

**Comment by falbrito** [comment]
O código foi revisado pelo Marcelo e reprocessado.  Problema solucionado.

Registro para análise:
http://pesquisa.bvsalud.org/portal/resource/pt/ibc-160527
