### ISSUE TITLE
Atualizar o ambiente iAHx do WHO COVID-19 para usar versão 5.x

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#490]

**Comment by viniciusandrade** [comment]
@botturam esta disponível no servidor de processamento na porta 8983 a instância solr5 com índice covidoms vazio. 

Favor remover do arquivo solrconfig.xml os filtros que não fazem parte deste projeto e quando possível realizar uma indexação completa para que possamos apontar a interface de testes (https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/) para este índice.

Obrigado

**Comment by renatomurasaki** [comment]
Resolverá o issue #489

**Comment by botturam** [comment]
Processamento regular IAHx-COVID-SoLR5 configurado e disponível em:

tomcat@serverofi5:/home/javaapps/iahx-server/indexes/solr5-port3/covidwho/data/index $ ll
total 1826184
-rw-rw-r-- 1 tomcat operacao 414063543 May 28 16:47 _7h.fdt
-rw-rw-r-- 1 tomcat operacao    187954 May 28 16:47 _7h.fdx
-rw-rw-r-- 1 tomcat operacao     10545 May 28 16:49 _7h.fnm
-rw-rw-r-- 1 tomcat operacao 268972677 May 28 16:48 _7h_Lucene50_0.doc
-rw-rw-r-- 1 tomcat operacao 694732491 May 28 16:48 _7h_Lucene50_0.pos
-rw-rw-r-- 1 tomcat operacao 119139479 May 28 16:48 _7h_Lucene50_0.tim
-rw-rw-r-- 1 tomcat operacao   2208939 May 28 16:48 _7h_Lucene50_0.tip
-rw-rw-r-- 1 tomcat operacao   5922745 May 28 16:48 _7h.nvd
-rw-rw-r-- 1 tomcat operacao       289 May 28 16:48 _7h.nvm
-rw-rw-r-- 1 tomcat operacao       523 May 28 16:49 _7h.si
-rw-rw-r-- 1 tomcat operacao 364501232 May 28 16:49 _7h.tvd
-rw-rw-r-- 1 tomcat operacao    224625 May 28 16:49 _7h.tvx
-rw-rw-r-- 1 tomcat operacao       167 May 28 16:49 segments_3h
-rw-rw-r-- 1 tomcat operacao         0 May 28 14:30 write.lock

arquivos schema.xml e solrconfig.xml otimizados em:
  serverofi5:/home/javaapps/iahx-server/indexes/solr5-port3/covidwho/conf

**Comment by viniciusandrade** [comment]
@renatomurasaki os dois ambientes de testes estão configurados para validação:

**Ambiente solr3**

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/

**Ambiente solr5**

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/

**Comment by botturam** [comment]
a partir de hoje, 02/junho, colocarei a atual SoLR3-Covid e a nova SoLR5-Covid para executarem uma após a outra, a partir das 18:00. Assim poderemos comparar uma com a outra:

atual SoLR3:
https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/

nova SoLR5:
https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/

**Comment by renatomurasaki** [comment]
O comportamento esperado de aumento do número de registros bibliográficos recuperados está ocorrendo no SOLR5, exemplo:

`tw:(sars-cov-2)`
SOLR 3 - 76.332
SOLR 5 - 88.893

Para facilitar a análise, comparei um resultado de busca com menos resultados:

`tw:(b.1.1*)`
SOLR 3 - 536
SOLR 5 - 591

Comparando os ID recuperados em ambos ambientes, posso afirmar que o resultado do SOLR3 está contido no SOLR5.

Exemplos de registros recuperados no SOLR 5 e não recuperados no SOLR 3, comprovando melhora na produção do índice de busca:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/resource/en/ppcovidwho-6345
- neste caso, o SOLR 5 conseguiu recuperar a string (B.1.1.7)

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/resource/en/ppbiorxiv-293258
- neste caso, o SOLR 5 conseguiu recuperar a string (B.1.1.7, B.1.351 and P.1)

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov-test/resource/en/ppbiorxiv-423920
- neste caso, o SOLR 5 conseguiu recuperar a string (B.1.1.X)

Entretanto, ao fazer a busca
`tw:(b.1.1* AND p.1)`
SOLR 3 - 88
SOLR 5 - 34

Há uma discrepancia entre os conjuntos de resultados e gostaria de entender a razão.

**Comment by viniciusandrade** [comment]
@renatomurasaki ativando o debug no Solr obtive a seguinte resposta que indica a diferença entre o parser de uma versão e da outra:

SOLR3:
parsedquery_toString: +tw:b.1.1* +tw:p.1

SOLR5:
parsedquery_toString: +tw:b.1.1* +(+(tw:p.1 tw:p) +tw:1)

**Comment by renatomurasaki** [comment]
@viniciusandrade pode fazer o mesmo debug para as outras duas expressões de busca, por favor?

**Comment by viniciusandrade** [comment]
@renatomurasaki segue o debug:

SOLR3:
parsedquery_toString: tw:b.1.1*
parsedquery_toString: tw:sars-cov-2

SOLR5:
parsedquery_toString: tw:b.1.1*
parsedquery_toString: +(tw:sars-cov-2 tw:sars tw:sarscov) +tw:cov +tw:2

**Comment by viniciusandrade** [comment]
@renatomurasaki não consigo explicar o comportamento, no parserquery o que tem sinal + significa AND e o sinal - significa AND NOT fazendo o debug da query ficou:

SOLR3
parsedquery_toString: +(+tw:b.1.1* +tw:p.1*) -(+tw:b.1.1* +tw:p.1)

SOLR5
parsedquery_toString: +(+tw:b.1.1* +tw:p.1*) -(+tw:b.1.1* +(+(tw:p.1 tw:p) +tw:1))

**Comment by botturam** [comment]
o proc. SoLR5-COVIDWHO não será utilizado no momento. Ele está configurado e proto para processamento regular, nos mesmos moldes do SoLR3, entretanto não será adotado, devido às diferenças de recuperação com a versão SoLR3..

**Comment by botturam** [comment]
Farei a sugestão para o pessoal do COVID-WHO avaliar os resultados da pesquisa do SoLR5, a fim de melhorarmos os resultados que estão no SoLR3.

**Comment by botturam** [comment]
proposta para substituição da IAHx-SoLR3 pela SoLR5: 

feita em https://github.com/bireme/Covid-19_WHO/issues/10

**Comment by botturam** [comment]
concluído.
