### ISSUE TITLE
Traduzir os valores do cluster Tipo de Estudo do GIM (reaproveitar o já feito no WHO COVID-19)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#492]
![image](https://user-images.githubusercontent.com/1226218/117978655-7e990580-b308-11eb-91e1-19e4d6ff0120.png)

Favor tornar padrão para qualquer instância a tradução destes labels.

**Comment by renatomurasaki** [comment]
@marcoslmori @botturam acabo de ver que na instância WHO COVID-19, ainda há labels com necessidade de tradução, como mostra a imagem abaixo

![image](https://user-images.githubusercontent.com/1226218/117979008-d7689e00-b308-11eb-9a78-6dce09b0b3cc.png)

**Comment by marcoslmori** [comment]
na instancia da OMS Covid está faltando as seguintes traduções: 
Determinantes_sociais_saude 
Broad_synthesis
Implementation_research

No entanto, comparando com o cluster do portal regional

**Comment by renatomurasaki** [comment]
@marcoslmori sim Mori, pode retirar. Precisa verificar como o @botturam pois se não me falha a memória, estas 3 entradas não estratégias relacionadas ao processamento de cluster do Evid@Easy

**Comment by botturam** [comment]
sim, Renato. São referenctes ao Evi@Easy.

**Comment by marcoslmori** [comment]
@botturam, essas entradas tem que ser retiradas no processamento ou no xml.  No texts.ini já não está.   Abraços,

**Comment by marcoslmori** [comment]
Corrigido via parametrização no config.xml 
<cluster default="true" show_only_translated_items="true">type_of_study</cluster>

**Comment by renatomurasaki** [comment]
@marcoslmori já está na produção?

**Comment by marcoslmori** [comment]
chamado 7972

**Comment by marcoslmori** [comment]
Em produção a instancia da OMS COVID, agora normalizando o GIM

**Comment by marcoslmori** [comment]
Por favor @botturam 

No cluster tipo de estudo na instancia do portal em inglês existe essa entrada:
cohort="Cohort study" e é traduzido normalmente. No portal GIM não.  Você pode verificar se existe esse componente nesse cluster?    

Revisando o GIM com o Portal Regional e configurando para apenas aparecer os que tem tradução identifiquei essas novas entradas.

incidence_studies="Incidence study"
diagnostic_studies="Diagnostic study"
etiology_studies="Etiology study"
qualitative_research="Qualitative research"
observational_studies="Observational study"
policy_brief="Evidence synthesis"
prevalence_studies="Prevalence study" * Nome lógico errado
prognostic_studies="Prognostic study"
structured_summary_of_systematic_review = "Structured summary of systematic review"
risk_factors_studies="Risk factors"
screening_studies="Screening study"
sysrev_observational_studies="Systematic review of observational studies"

**Comment by marcoslmori** [comment]
Ajustado o IAHx GIM na instancia de teste o parâmetro (show_only_translated_items="true) no config.xml e a normalização do cluster tipo de estudo.
O componente cohort="Cohort study"  ainda não aparece nesse cluster mas já está contemplado na tradução. 
Chamado: 7982 para sincronização dos arquivos para a produção!

**Comment by renatomurasaki** [comment]
@marcoslmori obrigado. Receio ter este parâmetro configurado de show_only*, porque qual é o mecanismo, além da própria visualização do cluster na área pública, teremos para ver estes ajustes?

**Comment by marcoslmori** [comment]
Renato, eu depois comento aqui o processo que eu estou usando de validação com o cluster do portal e já estou documentando alguns componentes que tem comportamentos diferentes. Eu sempre inicio os ajustes e a validação sem esse parâmetro ligado. 
Eu só quero terminar de finalizar essas faltas de traduções desse cluster e  volto a esse tema sobre o que pode impactar. 

Abraços,

**Comment by renatomurasaki** [comment]
Ok, @marcoslmori . Meu comentário é pelo fato das bases serem vivas. Novos valores aparecem nestes clusters após o deployment inicial. Deixar o flag como true impossibilita saber quais são os novos valores do cluster que precisam de tradução, a não ser que você tenha elaborado um procedimento que avalia periodicamente estes clusters para retroalimentar a tradução.

**Comment by marcoslmori** [comment]
Entendi Renato!  o problema é que se eu tirar esse parâmetro desse cluster, ira aparecer itens que não tem no cluster do portal, por exemplo "implementation_research="Implementation research".  Vou verificar direito com o pessoal qual será a boa prática desse processo

**Comment by marcoslmori** [comment]
instancia de GIM em produção 
e aberto o chamado para sincronização da instancia do AIM (7895)

Próximo passo documentação do comportamento desse cluster nas instâncias  do portal regional, oms-covid, gim e aim

**Comment by renatomurasaki** [comment]
@marcoslmori ok, obrigado.
