### ISSUE TITLE
Registros ICTRP disponíveis no WHO COVID-19 com "link para o texto completo" indo para ensaio clínico errado

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#493]
Exemplos:

- Ensaio clínico "Responses to COVID19 Vaccination in Patients With a Treatment History of Rituximab."
- Registro na interface WHO COVID-19 - https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/ictrp-NCT04877496
- Link para o texto completo no clinicaltrials.gov - https://clinicaltrials.gov/ct2/show/NCT04877002

Repare que o ID do registro no iAHx é NCT04877496 e o id do link para o texto completo é NCT04877002

Fazendo uma busca no XML do ICTRP, o metadado está correto:

```
<Trial>
    <TrialID>NCT04877496</TrialID>
    <Last_Refreshed_on>17 May 2021</Last_Refreshed_on>
    <Public_title>Responses to COVID19 Vaccination in Patients With a Treatment History of Rituximab.</Public_title>
    <Scientific_title>Registry Study for COVID19 Vaccination Efficacy in Patients With a Treatment History of Rituximab.</Scientific_title>
    <Acronym>RituxiVac</Acronym>
    <Primary_sponsor>University Hospital Inselspital, Berne</Primary_sponsor>
    <Date_registration>06/05/2021</Date_registration>
    <Date_registration3>20210506</Date_registration3>
    <Export_date>5/26/2021 10:51:13 PM</Export_date>
    <Source_Register>ClinicalTrials.gov</Source_Register>
    <web_address>https://clinicaltrials.gov/show/NCT04877496</web_address>
```

Parece que todos os registros bibliográficos do ICTRP estão apontando para URLs diferentes.

**Comment by botturam** [comment]
Problema solucionado com a ajuda do Vinícius. Foram modificados:

1) reset de variáveis no início do loop principal:
au = ti = ur = db = collection = da = entry_date = ab = ab1 = ab2 = ab3 = ab4 = ab5 = Criteria = src = dtr = ''

2) foram alteradas a edentação de 2 blocos de comandos.

old: /bases/oai.pmh/tpl.xml/bak/criaXML.py.old
new: /bases/oai.pmh/tpl.xml/criaXML.py

já disponível em produção.

**Comment by renatomurasaki** [comment]
@botturam @viniciusandrade obrigado pela análise e correção.
