### ISSUE TITLE
Doenças transmissiveis - Sepsis

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#502]
Tema Doenças transmissíveis Evid@Easy
arquivo atualizado
[3.3.Sepsis_x.txt](https://github.com/bireme/db-processing/files/6880956/3.3.Sepsis_x.txt)

**Comment by ChicoLopes** [comment]
Expressão atualizada

**Comment by ChicoLopes** [comment]
@botturam arquivo de estratégia de Doenças Transmissíveis (transmisible_diseases), denominado 4_TD-4_sepsis.sch está processado com dados disponíveis para continuidade do processo e agendamento de coleta semanal automática (para sábado às 0:30 com duração de aproximadamente 30 min) implantado.
