### ISSUE TITLE
Resumos na interface WHO COVID-19 sem pontuação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#508]
Parece que alguns resumos do Indonesian Research estão sem pontuação (ponto no final das orações). Exemplo:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1235270

De acordo com o Distiller, este resumo tem pontuação (ver arquivo anexo)

[Missing_abstract_punctuation.xlsx](https://github.com/bireme/db-processing/files/6611193/Missing_abstract_punctuation.xlsx)

Outro exemplo:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1235466

**Comment by renatomurasaki** [comment]
@botturam parece que não é somente nos registros do Indonesian Research. Encontrei outros registros com o mesmo problema:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1239374

**Comment by renatomurasaki** [comment]
@botturam conseguiu verificar o que ocorre nestes resumos?

**Comment by botturam** [comment]
havia um sed + tr, sobre o campo resumo dos CSVs, que eliminava todos os "." . Acontecia nas outras FIs que passavam pelo fluxo ISIS de processamento.

# 28/06/2021 - Marcelo
#cat x2.id | sed 's/<[^>]*>//g' | tr "\056" " " > x2_1.id

Comentei nos seguintes shell-scripts o camando acima:

-rwxrwxr-x 1 operacao        operacao   28333 Jun 28 17:58 pos_coleta_covidwho.sh*
-rwxrwxr-x 1 operacao        operacao   18858 Jun 28 18:00 pos_coleta_covidwho_GR.sh*
-rwxrwxr-x 1 operacao        operacao   18444 Jun 28 18:02 pos_coleta_covidwho_PP.sh*
-rwxrwxr-x 1 operacao        operacao   17017 Jun 28 18:03 pos_coleta_covidwho_UPD.sh*
-rwxrwxr-x 1 operacao        operacao   15261 Jun 28 18:05 pos_coleta_covidwho_ZH.sh*

Vou reiniciar agora o processamento de hoje, a fim de consertar os erros e verificar possíveis efeitos colaterais da retirada deles.

**Comment by renatomurasaki** [comment]
Verificado e aprovado
