### ISSUE TITLE
DeCS 2021 - atualização e distribuição dos insumos do DeCS

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#509]
1o. Vinicius
	- iAHX (atualizar portas em instances /home/javaapps/iahx-server/instances/?/resources)
	- Depois que o Vini atualizar, processar o comando abaixo
  - IAHx controler (para interfaces IAHx - compartilhado)

2o. Heitor
	Utiliza no $TABS da serverofi5 o decs.id e decs.{mst,xrf}
  - MarkAbstract
 
3o. Marcelo
	- dcs_regional - aguardando pronto em /bases/iahx/xml-inbox/decs/wait, é só mover para ..
  - Atualizar processo de coleta FI-Admin
		serverofi5:/bases/fiadmin/consolida/tpl/Atualiza_DeCS_ANUAL.sh
  - FI-admin - o diretório VMX deverá ser copia para dolomita11 ou para o bases??? - verificar diretório (PERGUNTAR PARA VÍNICIUS)
	
4o. Wilson
  Virada do portal DeCS Teste para Portal DeCS Produção 
    - base congelada
    - índice SoLR
    - se necessário, gerar cache do portal

5o. Heitor
	Utiliza no $TABS da serverofi5 o decs.id e decs.{mst,xrf}
  - BVS-InfoButton
  - DeCSHighlighter
  - SimilarDocs
  - e-BlueInfo

6o. Ana kátia
	Lildbi WEB (migração)

**Comment by viniciusandrade** [comment]
@botturam DeCS atualizado nas instâncias de processamento IAHx do serverofi5 (/home/javaapps/iahx-server/instances/?/resources/). 

Favor acompanhar nos próximos processamentos se esta tudo OK para que eu possa atualizar as instâncias no servidor de produção.

Obs: necessário reiniciar a instância para que passe a valer o novo DeCS.

**Comment by viniciusandrade** [comment]
@botturam adicionei no arquivo "Processamento DeCS_v1.txt" o caminho para onde deve ser copiado a base do VMX. 

Por favor, quando conseguir copiar para o servidor de testes avisar por aqui para que eu possa verificar.

Obrigado.

**Comment by botturam** [comment]
1) novo DeCS-2021 atualizado nas instâncias de processamento MDL e like-LILACS;  tabelas auxiliares também preparadas.

/bases/lilG4/tabs
/bases/mdlG4/tabs
/usr/local/bireme/tabs
/bases/fiadmin/consolida/tabs (para coleta do FI-ADMIN)

2) DeCS como fonte de informação (**dcs_regional.xml**) disponível para IAHx-Portal-Regional.
operacao@serverofi5:/bases/iahx/xml-inbox/decs $ ll
-rw-rw-r-- 1 operacao operacao 239658720 Jun 10 15:51 **dcs_regional.xml**

**Comment by botturam** [comment]
@viniciusandrade O processamento na porta 3 (novo SoLR5) não está funcionando desde ontem, 5f.

tomcat@serverofi5:/bases/iahx/proc/covidwho/main $ /bases/iahx/exec/cron_weekly3.sh -p covidwho
[TIME-STAMP] (5) 2021-06-11 13:31:08 [:INI:] {361} cron_weekly3.sh -p covidwho
covidwho
covidwho/main

/bases/iahx/exec/update-index.sh     -p covidwho
unix2dos: converting file logs/out-update.20210611.txt to DOS format ...
Tempo de execucao de cron_weekly3.sh -p covidwho de (5) 2021-06-11 13:31:08 ate (5) 2021-06-11 13:31:09 =       1[s] ou 00:00:01
[TIME-STAMP] (5) 2021-06-11 13:31:09 [:FIM:] {361} cron_weekly3.sh -p covidwho
*** FAIL +++ delete fail for index   *** EXIT CODE (1) ***
*** FAIL +++ Problem deleting old index covidwho  *** EXIT CODE (1) ***
*** FAIL +++ step 1 - index weekly  *** EXIT CODE (1) ***
208:*** FAIL +++ delete fail for index   *** EXIT CODE (1) ***
209:*** FAIL +++ Problem deleting old index covidwho  *** EXIT CODE (1) ***
210:*** FAIL +++ step 1 - index weekly  *** EXIT CODE (1) ***
208:*** FAIL +++ delete fail for index   *** EXIT CODE (1) ***
209:*** FAIL +++ Problem deleting old index covidwho  *** EXIT CODE (1) ***
210:*** FAIL +++ step 1 - index weekly  *** EXIT CODE (1) ***
         x.xx.xx.xx -Execucao terminada

Será que é por causa da atualização do DeCS?

**Comment by viniciusandrade** [comment]
@botturam sim, revisei a instância e o erro era devido a atualização do DeCS. 
Já corrigi o problema.

**Comment by botturam** [comment]
A porta 6, do Portal-SoLR5 também está com problema, mas o erro é outro. Será que é necessária alguma intervenção nesse sentido também?

**Comment by viniciusandrade** [comment]
@botturam, fiz um teste simples de busca e esta retornando corretamente, ou seja, aparentemente não esta com problemas no componente do DeCS. 
Se quiser pode colar aqui o erro para que eu possa verificar se tem alguma dica do que seja.

**Comment by botturam** [comment]
@viniciusandrade investiguei mais a fundo e o erro no Portal era sobre a entidade **&percnt;** inserida recentemente por mim. Não tem a ver com as atualizações recentes por causa do DeCS.

Podemos seguir com as atualizações do DeCS. Obrigado

**Comment by botturam** [comment]
Vinícius, dados para VMX transferidos:

de....: serverofi5:/bases/dec.000/dec.dec/outputvmx
Para: dolomita02:/home/apps/bvs.br/wp-decs/www/bases

**Comment by viniciusandrade** [comment]
@botturam parece que o local de cópia não bate com o caminho indicado no txt. 

Fiz o teste e não recupera os termos novos.

**Comment by botturam** [comment]
corrigindo...

de....: serverofi5:/bases/dec.000/dec.dec/outputvmx
Para: dolomita02:/home/apps/bvs.br/wp-decs/www/bases/vmx

**Comment by viniciusandrade** [comment]
OK, ambiente de testes funcionando com a versão nova do DeCS. Obrigado.

**Comment by heitorbarbieri** [comment]
ìtens 2 e 5 da lista inicial realizados. Por favor, verificar o resultado no MarkAbstract.

**Comment by viniciusandrade** [comment]
Aberto chamados 8023, 8024 e 8025 referentes a atualização na produção dos serviços: iahx-controller, decsquickterm e vmx.

**Comment by botturam** [comment]
Foram atualizados os arquivos **zdecs?.*** (interface IAH) em serverw e bases (vide documentação em FC):

zdecse.mst
zdecse.xrf
zdecsi.mst
zdecsi.xrf
zdecsp.mst
zdecsp.xrf

**Comment by wilsonmoura** [comment]
4. Virada do Portal DeCS Teste para Portal DeCS Produção (Wilson)
    - base congelada - **OK**
    - índice SoLR - **OK**
    - se necessário, gerar cache do portal - **OK**

**Comment by viniciusandrade** [comment]
1o. Vinicius
    - iAHX analyzer (serverofi5) -  **OK**
   -  iAHx controler - **OK**
   -  Localizador DeCS  - **OK**

**Comment by wilsonmoura** [comment]
@botturam Creio que já pode encerrar esse issue e criar um novo com as mesmas atividades para o lançamento da base definitiva do DeCS 2021, de acordo?

**Comment by botturam** [comment]
De acordo. Atividades finalizadas.
