### ISSUE TITLE
Desenvolver o processamento onde são coletados dados do FI-Admin com marcação especifica de uma BVS  e publicar em um IAHx especializado.

### ISSUE THREAD

**Issue by marcoslmori** [bireme/db-processing#51]
Primeiro projeto - BVS Colombia

**Comment by falbrito** [comment]
Processo existente. O filtro é realizado sobre o arquivo ISO denominado fiadmin.iso, que é uma base onde recebe atualização e inserção ocorridas no FI-Admin.
O filtro se baseia na regra que se houver no campo v4 ou campo v904 o conteúdo do nome da FI cria uma base para a mesma.

Ex.: Abaixo comando apenas para mostrar o total que haverá para a base BBO
FI='BBO'
mx iso=/bases/fiadmin/consolida/original/fiadmin.iso "pft=if v904:'$FI' or v4:'$FI' then v2/ fi" now | wc -l


Outros testes realizados e que estão em linha, ou seja já está sendo realizado o filtro para as FI abaixo.

serverofi5:/bases/fiadmin/databases
../consolida/tpl/filtraDBs.sh LILACS
../consolida/tpl/filtraDBs.sh BBO
../consolida/tpl/filtraDBs.sh BDS
../consolida/tpl/filtraDBs.sh REPOSITORIOBVS


O processo para Colombia seguirá o mesmo formato, havendo conteúdo no campo v4 ou v904 com "COLOMBIA" ou algo parecido será feito o filtro.
Obs.: Necessário informar qual será o conteúdo para posterior configuração.

Ex.:
../consolida/tpl/filtraDBs.sh COLOMBIA
