### ISSUE TITLE
reprocessar MEDLINE-2021 completo com o DeCS-2021

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#510]

**Comment by botturam** [comment]
início da conversão dos XMLs Baseline e Update para ISIS

**Comment by botturam** [comment]
processamento do Baseline-2021 interrompido no arquivo pubmed21n0900.xml até pubmed21n1062.xml. Erro desconhecido.

**Comment by botturam** [comment]
Foi enviado ao Heitor, o arquivo pubmed21n1125.xml para análise (possui 25.000 linhas de autores).

Paralelamente, foi implementado no processamento MEDLINE, um salto de registro, quando não houver PMID no registro. Dessa maneira, o respectivo registro não ingressará nos masteres distribuídos por Data de Publicação, mas existirá nos masteres relativos aos arquivos provenientes da NLM, por exemplo :

operacao@serverofi5:/bases/mdlG4/fasea/update_isis $ /bases/mdlG4/fasea/update_isis $ mx bmd1125b from=18998

-rw-rw-r-- 1 operacao operacao    106496 Jun 17 15:59 bmd1125b.iyp
-rw-rw-r-- 1 operacao operacao        56 Jun 17 15:59 bmd1125b.cnt
-rw-rw-r-- 1 operacao operacao    950528 Jun 17 15:59 bmd1125b.ly1
-rw-rw-r-- 1 operacao operacao         0 Jun 17 15:59 bmd1125b.ly2
-rw-rw-r-- 1 operacao operacao  86047232 Jun 17 15:59 bmd1125b.mst
-rw-rw-r-- 1 operacao operacao        56 Jun 17 15:59 imd1125b.cnt
-rw-rw-r-- 1 operacao operacao       512 Jun 17 15:59 dmd1125b.xrf
-rw-rw-r-- 1 operacao operacao      3584 Jun 17 15:59 dmd1125b.mst
-rw-rw-r-- 1 operacao operacao    102400 Jun 17 15:59 bmd1125b.xrf
-rw-rw-r-- 1 operacao operacao         0 Jun 17 15:59 bmd1125b.n02
-rw-rw-r-- 1 operacao operacao     58864 Jun 17 15:59 bmd1125b.n01
-rw-rw-r-- 1 operacao operacao    950528 Jun 17 15:59 imd1125b.ly1
-rw-rw-r-- 1 operacao operacao    106496 Jun 17 15:59 imd1125b.iyp
-rw-rw-r-- 1 operacao operacao         0 Jun 17 15:59 imd1125b.ly2
-rw-rw-r-- 1 operacao operacao         0 Jun 17 15:59 imd1125b.n02
-rw-rw-r-- 1 operacao operacao     58864 Jun 17 15:59 imd1125b.n01
-rw-rw-r-- 1 operacao operacao      9473 Jun 17 16:59 imd1125b.sta
-rw-rw-r-- 1 operacao operacao    102400 Jun 17 17:35 imd1125b.xrf
-rw-rw-r-- 1 operacao operacao 156343296 Jun 17 17:35 imd1125b.mst
-rw-rw-r-- 1 operacao operacao    126375 Jun 17 19:36 imd1125b.rdp
-rw-rw-r-- 1 operacao operacao       247 Jun 17 19:36 imd1125b.dp

**Comment by botturam** [comment]
o processamento foi reiniciado com as alterações e deve ficar pronto no fim de semana (ano corrente)

**Comment by renatomurasaki** [comment]
@botturam o processamento foi finalizado com sucesso?

**Comment by botturam** [comment]
O processamento do BASELINE está em curso. Deverá terminar em 10 dias.

O processamento diário do MEDLINE foi retomado na 2f, inclusive para o enriquecimento dos docs do COVIDWHO.

**Comment by renatomurasaki** [comment]
@botturam ok. Se o BASELINE der erro, abrir outro issue. Vou finalizar este.
