### ISSUE TITLE
Projeto CGAN - Participacao e controle social

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#511]
Infometria para o Projeto CGAN
[PARTICIPAÇÃO E CONTROLE SOCIAL.txt](https://github.com/bireme/db-processing/files/6638807/PARTICIPACAO.E.CONTROLE.SOCIAL.txt)

**Comment by renatomurasaki** [comment]
@botturam favor manter a cópia regular dos arquivos de tabulação na área de dados da bismuto (data lake Dremio). Avise-me por aqui assim que tiver disponível.

**Comment by ChicoLopes** [comment]
@botturam arquivo de estratégia da Participação e controle social, denominado 'CGAN-participacao_controle_social.sch' está processado com dados disponíveis para continuidade do processo e processo automático de coleta semanal implantado.

**Comment by botturam** [comment]
continuação #514
