### ISSUE TITLE
Projeto CGAN - Vigilancia alimentar e nutricional

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#512]
Infometria - Projeto CG
[VIGILÂNCIA ALIMENTAR E NUTRICIONAL.txt](https://github.com/bireme/db-processing/files/6638810/VIGILANCIA.ALIMENTAR.E.NUTRICIONAL.txt)
AN

**Comment by renatomurasaki** [comment]
@botturam favor manter a cópia regular dos arquivos de tabulação na área de dados da bismuto (data lake Dremio). Avise-me por aqui assim que tiver disponível.

**Comment by ChicoLopes** [comment]
@botturam arquivo de estratégia da Vigilância alimentar e nutricional, denominado 'CGAN-vigilancia_alimentar_nutricional.sch' está processado com dados disponíveis para continuidade do processo e processo automático de coleta semanal implantado.

**Comment by pintoros** [comment]
Qual seu e-mail Chico?


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:d991d27e-0cf8-41df-95b8-f53d5d8bce46]

________________________________
De: Francisco José Lopes ***@***.***>
Enviado: sexta-feira, 23 de julho de 2021 17:06
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/db-processing] Projeto CGAN - Vigilancia alimentar e nutricional (#512)


@botturam<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbotturam&data=04%7C01%7Cpintoros%40paho.org%7Ccaf05216612442d7fb8008d94e1552ad%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637626675767849619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EvQzm6jiVGBeO6YwG%2FaLMjIgZC6f0OVf2bOninaxx48%3D&reserved=0> arquivo de estratégia da Vigilância alimentar e nutricional, denominado 'CGAN-vigilancia_alimentar_nutricional.sch' está processado com dados disponíveis para continuidade do processo e processo automático de coleta semanal implantado.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F512%23issuecomment-885886253&data=04%7C01%7Cpintoros%40paho.org%7Ccaf05216612442d7fb8008d94e1552ad%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637626675767859568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ia%2BipqKX9b8hJSS3cWXrS%2BNQOzelXzIjHo4v3hqJMJI%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4GTCVXPH4VVSKCZI73TZHDTJANCNFSM46QYW6JA&data=04%7C01%7Cpintoros%40paho.org%7Ccaf05216612442d7fb8008d94e1552ad%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637626675767859568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iFiZ4Azm7tNyYSfB4syZUhKwGd8xSZYJFsvoP8iBqOs%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
continuação #514
