### ISSUE TITLE
Projeto CGAN - Promocao da alimentacao adequada e saudável

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#513]
Infometria - Projeto CGAN
[PROMOÇÃO DA ALIMENTAÇÃO ADEQUADA E SAUDÁVEL.txt](https://github.com/bireme/db-processing/files/6638815/PROMOCAO.DA.ALIMENTACAO.ADEQUADA.E.SAUDAVEL.txt)

**Comment by renatomurasaki** [comment]
@botturam favor manter a cópia regular dos arquivos de tabulação na área de dados da bismuto (data lake Dremio). Avise-me por aqui assim que tiver disponível.

**Comment by ChicoLopes** [comment]
@ChicoLopes Coleta de ID da Organização da atenção nutricional, sob o nome 'organizacao_atencao_nutricional' completada sem apontamento de erros, Disponível para próxima etapa @botturam

**Comment by ChicoLopes** [comment]
@botturam arquivo de estratégia da Promoção da Alimentação Adequada Saudável, denominado 'CGAN-alimentacao_adequada_saudavel.sch' está processado com dados disponíveis para continuidade do processo e processo automático de coleta semanal implantado.

**Comment by botturam** [comment]
continuação #514
