### ISSUE TITLE
Projeto CGAN - Organização da atencao nutricional

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#514]
Infometria - Projeto CGAN
[ORGANIZAÇÃO DA ATENÇÃO NUTRICIONAL.txt](https://github.com/bireme/db-processing/files/6638828/ORGANIZACAO.DA.ATENCAO.NUTRICIONAL.txt)

**Comment by renatomurasaki** [comment]
@botturam favor manter a cópia regular dos arquivos de tabulação na área de dados da bismuto (data lake Dremio). Avise-me por aqui assim que tiver disponível.

**Comment by ChicoLopes** [comment]
@botturam arquivo de IDs da Organização da Atenção Nutricional, denominado 'organizcao_atencao_nutriiconal' está processado e disponível para continuidade do processo.

**Comment by botturam** [comment]
@renatomurasaki para CGAN, criei um novo arquivo MEDLINE_id_tema_subtema.txt

Está disponível em:

bismuto01:/home/data/MEDLINE_tab/CGAN
bismuto01c1:/home/data/MEDLINE_tab/CGAN

**Comment by renatomurasaki** [comment]
@botturam reparei que a coluna ID do arquivo **MEDLINE_id_tema_subtema.txt** está vazia. Precisamos desta informação para saber qual ID (documento) se refere ao tema.

**Comment by botturam** [comment]
já estou verificando.

**Comment by botturam** [comment]
disponível em 

bismuto01:/home/data/MEDLINE_tab/CGAN
bismuto01c1:/home/data/MEDLINE_tab/CGAN
Exemplo:
FI|SCH|ID|SUB
MEDLINE|CGAN|4159628|organizacao_atencao_nutricional
MEDLINE|CGAN|4159628|vigilancia_alimentar_nutricional
MEDLINE|CGAN|4159629|organizacao_atencao_nutricional
MEDLINE|CGAN|4159629|vigilancia_alimentar_nutricional

**Comment by renatomurasaki** [comment]
@botturam obrigado! Chequei e está ok
