### ISSUE TITLE
Arquivos para migração dos dados de descrição de periódicos (TITLE) da base AIM / GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#515]
@anakatiacamilo seguem dois arquivos para início da migração dos metadados dos periódicos da base AIM na TITLE do FI-Admin
[aim-from-pmb-csv-files-aim-journal4fiadmin-import-mike-validation.zip](https://github.com/bireme/db-processing/files/6651601/aim-from-pmb-csv-files-aim-journal4fiadmin-import-mike-validation.zip)

### Alguns detalhes:
- Todos os campos que começam com aim-* são dados informados (originais ou corrigidos) pela AFRO
- Todos os campos que começam com issn-* são dados extraídos do portal ISSN

**Arquivo `aim-from-pmb-csv-files-aim-journal4fiadmin-import-without-mike-validation.csv`**
Este arquivo possui dados de períódicos que não foram revisados pelo Mike e por isso os únicos campos aim-* são issn e journal title. Todos os demais foram extraídos do portal ISSN.

**Arquivo `aim-from-pmb-csv-files-aim-journal4fiadmin-import-mike-validation.csv`**
Este arquivo possui mais campos aim-* porque foram validados pelo Mike. 

Proposta de regra para migração, aplicável em ambos os arquivos:

1) Quando o campo `issn_issn` e `issn_journal_title` forem nulos, não migrar
2) Quando o campo `issn_issn` não for nulo e `issn_journal_title` for nulo, utilizar o campo `aim_journal_title`

Proposta de regra para o arquivo `aim-from-pmb-csv-files-aim-journal4fiadmin-import-mike-validation.csv`

1) Utilizar o campo aim-* quando o campo issn-* correspondente for nulo para os seguinte casos: `aim_country`, `aim_city`, `aim_publisher`
2) O campo `aim_journal_website` pode ser usado sempre, pois não há correspondência no portal do ISSN

**Comment by renatomurasaki** [comment]
@anakatiacamilo algumas revistas não serão migradas por falta de informação de ISSN, mesmo que o registro bibliográfico do AIM a inclua na fonte. Entendo que não terá problema, correto?

**Comment by anakatiacamilo** [comment]
@renatomurasaki Correto, não tem problema não ter o título na title para os registros não LILACS.

**Comment by renatomurasaki** [comment]
@anakatiacamilo perfeito, obrigado!

**Comment by anakatiacamilo** [comment]
Foram migrados 93 registros no FI-ADMIN da produção + 90 registros marcados como AIM, compartilhei o relatório com a equipe SeCS para verificação.
