### ISSUE TITLE
WHO COVID-19 DB: registro medline que foi atualizado voltou ao status antigo na interface de busca

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#517]
Em 14 de junho, o registro medline - https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1135313 estava com a notação "Withdrawn:" no título, como mostra a captura de tela abaixo:

![image](https://user-images.githubusercontent.com/1226218/122231328-bf98b280-ce90-11eb-92ff-8c62d827be5e.png)

Entretanto, hoje percebeu-se que o mesmo registro no iAHx está diferente, sem a notação Withdrawn. O registro no medline é https://pubmed.ncbi.nlm.nih.gov/33293107/ e o texto completo na Elsevier é https://www.sciencedirect.com/science/article/pii/S0378378220307556?via%3Dihub

**Comment by renatomurasaki** [comment]
@botturam abaixo análise preliminar do @heitorbarbieri 

> Verifiquei que a última referência ao documento id:1135313 ocorreu na planilha who-repo4covid-biblio.xlsx do dia 18/03/2021. O título apresentava o prefixo "WITHDRAWN:" assim como o arquivo csv correspondente who-covid-19-repo-export2iAHxProcessingOnlyTitle.csv gerado. Reparei que os documentos adjacentes a este na planilha, ie, 1135310, 1135312 e 1135314 também apresentavam o mesmo prefixo e também apresentam o mesmo problema na interface de busca.
> 
> Interessante notar que o documento 1135330 apresenta palavras em letras maiúsculas no título e dois pontos, mas mesmo assim sua apresentação na interface de busca não foi alterada:
> 
> SHORT-TERM WORKING ALLOWANCE AND FIRM RISK IN THE POST-COVID-19 PERIOD: NOVEL MATCHING EVIDENCE FROM AN EMERGING MARKET

**Comment by heitorbarbieri** [comment]
@botturam verificar que o mesmo documento pesquisado no portal da BVS também apresenta o mesmo comportamento.

**Comment by renatomurasaki** [comment]
Alterado processamento MDL baseline para diminuir o tempo de atualização deste tipo de documento
