### ISSUE TITLE
Desenvolver procedimento Medline para documentos WITHDRAWN

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#518]
O documento disponível no índice de busca precisa ser editado da seguinte maneira:

1) Acrescentar no título "WITHDRAWN"
2) Alterar resumo. Verificar se o registro com status DELETED do Medline já possui o novo resumo.

Exemplos de registros WITHDRAWN disponível no PubMed:

https://pubmed.ncbi.nlm.nih.gov/33293107/
https://pubmed.ncbi.nlm.nih.gov/33213969/

**Comment by botturam** [comment]
O problema se dá por causa de um delay de atualização do BASELINE (1966-2020).

esses 2 documentos pertencem ao MDL-20 de nosso processamento MEDLINE, que por sua vez pertence ao BASELINE-NLM (mdl66 até mdl20), encerrado em dezembro de cada ano. A aplicação dos arquivos UPDATE-NLM no BASELINE completo ocorre trimestralmente, no ano corrente, e visa atualizar/corrigir os documentos lá compreendidos. 

No BASELINE-MDL-20, este documento está assim:

operacao@serverofi5:/bases/mdlG4/m20.mdl $ mx mdlbb20 "text=related acute decline in paediatric admissions in Malta"
mfn=1492247
305  "Early Hum Dev"
306  "eng"
307  "Ireland"
308  "Early human development"
309  "Early Hum Dev"
**352  "COVID-19 related acute decline in paediatric admissions in Malta, a population-based study."**
353  "105251"
354  "2020 Nov 12"
355  "20201112"
360  "Journal Article"
 85  "COVID-19"
 85  "Emergency"
 85  "Paediatrics"
 85  "SARS-CoV-2"
668  "Publisher"
969  "33293107"
968  "S0378-3782(20)30755-6^apii"
968  "10.1016/j.earlhumdev.2020.105251^adoi"
372  "Degiorgio S^1Department of Paediatrics, Mater Dei Hospital, L-Imsida, Malta. Electronic address: sophie.degiorgio@gov.mt."
372  "Grech N^1Department of Medicine, Mater Dei Hospital, L-Imsida, Malta."
372  "Dimech YM^1Department of Paediatrics, Mater Dei Hospital, L-Imsida, Malta."
372  "Xuereb J^1Department of Paediatrics, Mater Dei Hospital, L-Imsida, Malta."
372  "Grech V^1Department of Paediatrics, Mater Dei Hospital, L-Imsida, Malta."

No UPDATE-MDL21 (pubmed21n1194.xml) a correção está assim:

305  "Early Hum Dev"
306  "eng"
307  "Ireland"
308  "Early human development"
309  "Early Hum Dev"
324  "IM"
**352  "WITHDRAWN: COVID-19 related acute decline in paediatric admissions in Malta, a population-based study."**
353  "105251"
354  "2020 Nov 12"
355  "20201112"
360  "Retraction of Publication"
668  "Publisher"
969  "33293107"
370  "This article has been withdrawn at the request of the author(s) and/or editor. The Publisher apologizes for any inconvenience this may cause. The full Elsevier Policy on Article Withdrawal can be found at https://www.elsevier.com/about/our-business/policies/article-withdrawal."

Eu iniciei ontem, dia 22/06, a atualização do MDL-20 pelos docs do UPDATE-NLM (genMDLupdALL.sh). Deve ficar pronto amanhã.

Vou verificar como posso atualizar os docs do MDL-20 numa frequência de 2x por semana.

**Comment by renatomurasaki** [comment]
@botturam minha sugestão é que o BASELINE seja ANO CORRENTE - 3 anos, ou seja, 1966 - 2018. O MDL-20 deveria se transforma em MDL-Last3Years.

Com isso não impacta tanto o processamento frequente e garante maior cobertura de possíveis atualizações. Se 3 anos for muito para o processo de atualização frequente, pelo menos deixar 2 anos.

**Comment by botturam** [comment]
minha sugestão é aproveitar o fluxo diário de geração de XML-UPDATE-IAHx, desenvolvido recentemente, e aplicá-lo no Master File de mdl20 e talvez mdl19 (esse não vejo sentido, pois não usamos docs que foram ingressados em 2019/2020).

Paralelamente, eu passaria a executar a atualização do BASELINE-1966-2019 nos finais de semana, ou conforme a atualização se fizer necessária.

**Comment by renatomurasaki** [comment]
@botturam minha sugestão foi pensando também na BVS para mitigar o risco de estarmos disponibilizando informação desatualizada por muito tempo na interface de busca.

**Comment by renatomurasaki** [comment]
@botturam vejo que o documento https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1135313 ainda não sofreu atualização. A atualização do MDL-20 deu certo?

**Comment by botturam** [comment]
não acabou ainda. Terminará hoje à tarde.

**Comment by renatomurasaki** [comment]
Checado e corrigido
