### ISSUE TITLE
Enriquecimento do arquivo de tabulação "lilacs_todos" da base AIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#519]
Segue anexo arquivo zip contendo os seguintes CSV:

### aim-from_tab_files-aim_lilacs_todos_enriched_step1.csv
**Header:** `ID,issn_issnorg,issn_journal_title,issn_abbreviated_journal_title,issn_country`
Contém todos os registros bibliográficos do AIM. Quando o campo é diferente de vazio ou diferente de null é possível utilizar a informação do CSV para enriquecer a base AIM com dados de ISSN (issn_issnorg), Título Completo da Revista (issn_journal_title), Título Abreviado (issn_abbreviated_journal_title) e País de publicação (issn_country)

### aim-from_tab_files-aim_lilacs_todos_enriched_step2.csv
**Header:** `ID,issn_issnorg,issn_journal_title,issn_abbreviated_journal_title,issn_country`
Idem explicação do arquivo anterior, entretanto neste há somente um subconjunto de registros bibliográficos.

### aim-from_tab_files-aim_lilacs_todos_enriched_step3.csv
**Header:** `ID,TL,NT,PT`
Contém todos os registros bibligáficos do AIM. Quando o campo é diferente de vazio ou diferente de null é possível utilizar a informação do CSV para enriquecer a base AIM com dados de nível de tratamento (TL e NT) e Tipo de Publicação (PT)

Abaixo as regras aplicadas para enriquecimento dos campos TL, NT e PT:

```
CASE
   WHEN TL = 'S' and NT ='as' and (TA = '' or TA is null or TA = 'null') THEN 'N'
   WHEN ((TA like '%Journal%' or (TA <> '' and I_S <> '')) and TL = '' and NT = '') THEN 'S'
   WHEN TL = '' and NT = '' and TA = '' THEN 'N'
   WHEN TL = 'SS' or TL = 'SN' THEN 'S'
   ELSE TL
END as TL,

CASE
   WHEN TL = 'S' and NT ='as' and (TA = '' or TA is null or TA = 'null') THEN 'm'
   WHEN ((TA like '%Journal%' or (TA <> '' and I_S <> '')) and TL = '' and NT = '') THEN 'as'
   WHEN TL = '' and NT = '' and TA = '' THEN 'm'
   WHEN NT = 'asas' or NT = 'asm' THEN 'as'
   ELSE NT
END as NT,

CASE
   WHEN TL = 'S' and NT ='as' and (TA = '' or TA is null or TA = 'null') and PT = 'JOURNAL ARTICLE' THEN ''
   WHEN ((TA like '%Journal%' or (TA <> '' and I_S <> '')) and TL = '' and NT = '' and PT = '') THEN 'JOURNAL ARTICLE'
   ELSE PT
END as PT
```

[aim-from_tab_files-aim_lilacs_todos_enriched_steps1-3.zip](https://github.com/bireme/db-processing/files/6696859/aim-from_tab_files-aim_lilacs_todos_enriched_steps1-3.zip)

**Comment by botturam** [comment]
sobre o "split" do campo 87 (descritor), será entregue depois?

**Comment by renatomurasaki** [comment]
> sobre o "split" do campo 87 (descritor), será entregue depois?

Sim, abrirei outro issue, somente para os registros novos

**Comment by botturam** [comment]
geração de um master file enriquecido com as 3 tabelas acima concuído.

Faltam:

- Descritores separados por ocorrência
- dados de Vol (v31), Issue (v32), pg (14) e, talvez, "informação descritiva" (v38)
- incluir 30 documentos restantes, da diferença entre Fev2021 e Dez2020

**Comment by renatomurasaki** [comment]
@botturam segue arquivo CSV com o enriquecimento dos dados de descritor e qualificador.

Achei melhor não incluir `^d` e `^s` no resultado final, porque começou a dar efeitos colaterais no ETL. Por favor, realizar esta inclusão no momento de gerar a base ISIS. Os qualificadores estão associados ao descritor pelo caracter `/ `e os descritores ou decritores/qualificadores estão separados pelo caracter `|`

Sobre o arquivo:

### aim-from-pmb-csv-files-aim-descriptor-enrichment.csv

**Header**: `notice_id,index_l,index_l_enriched`
O campo `index_l` é o dado original armazenado na base AIM. O campo `index_l_enriched` é o resultado da transformação realizada a partir de consecutivas expressões regulares de acordo com o padrão do dado original. Mantive o dado original para referência em relação à qualidade alcançada.

**Principais padrões em que funcionaram as ações de correção do dado original:**

_RAW DATA_  `PopulationPopulation dynamicsFamily planningPopulation growth`
_ENRICHED DATA_  `Population|Population dynamics|Family planning|Population growth`

_RAW DATA_  `Multiple myeloma;DiagnosisMultiple myeloma;Therapy`
_ENRICHED DATA_  `Multiple myeloma/Diagnosis|Multiple myeloma/Therapy`

_RAW DATA_  `Lymphoma, Non-Hodgkin - therapy`
_ENRICHED DATA_  `Lymphoma, Non-Hodgkin/therapy`

_RAW DATA_  `Community health aides;educationConsumer participation`
_ENRICHED DATA_  `Community health aides/education|Consumer participation`

_RAW DATA_ ` Family planningKnowledge;attitudes;practice`
_ENRICHED DATA_ `Family planning|Knowledge/attitudes|Knowledge/practice`

_RAW DATA_  `Fluid therapy;economicsDiarrhea;Infantile;epidemiology;therapyCosts and cost analysis`
_ENRICHED DATA_  `Fluid therapy/economics|Diarrhea|Infantile/epidemiology|Infantile/therapy|Costs and cost analysis`

_RAW DATA_ ` Yellow fever;epidemiology;prevention et controlViral vaccines;administration and dosage`
_ENRICHED DATA_  `Yellow fever/epidemiology|Yellow fever/prevention & control|Viral vaccines/administration and dosage`

_RAW DATA_  `Immunization - statistics;Immunization Schedule;Tetanus - prevention & control;Program Evaluation;Outcome and Process Assessment (Health Care);Mozambique - Maputo.`
_ENRICHED DATA_  `Immunization/statistics|Immunization Schedule|Tetanus/prevention & control|Program Evaluation|Outcome and Process Assessment (Health Care)|Mozambique|Maputo.`

**Principais padrões em que não foi possível melhorar o dado original neste momento:**

_RAW DATA_  `ACQUIRED IMMUNODEFICIENCY SYNDROMEHISTIOCYTOSIS;MALIGNANTHIV`
_RAW DATA_  `HANDICAPPEDLEPROSY`
_RAW DATA_  `Infant;NEWBORNMIDWIFERY`

O enriquecimento de volume, número e issue será enviado em arquivo separado. Sobre os aprox. 30 novos documentos, este arquivo de enriquecimento de descritor e qualificador já os inclui. Você consegue extrair os metadados principais destes novos registros a partir do último envio do Mike?

[aim-from-pmb-csv-files-aim-descriptor-enrichment.zip](https://github.com/bireme/db-processing/files/6726954/aim-from-pmb-csv-files-aim-descriptor-enrichment.zip)

**Comment by renatomurasaki** [comment]
@botturam segue arquivo CSV com o enriquecimento dos dados de volume, número, páginas e informação descritiva.

### aim-from-pmb-csv-files-aim-vol-issue-pag-desc-info-enriched.csv
**Header**: `notice_id,aim_info,volume,issue,pages,v38a,v38b,v38c`

O campo `aim_info` é o dado original que, por meio do processo de extração e transformação, gerou os campos `volume`, `issue`, `pages `e a informação descritiva (`v38a`, `v38b `e `v38c`).

[aim-from-pmb-csv-files-aim-vol-issue-pag-desc-info-enriched.zip](https://github.com/bireme/db-processing/files/6729706/aim-from-pmb-csv-files-aim-vol-issue-pag-desc-info-enriched.zip)

**Comment by renatomurasaki** [comment]
@botturam assim que finalizar a base ISIS, favor informar a @anakatiacamilo em #529

**Comment by renatomurasaki** [comment]
@botturam segue arquivo **aim-from-pmb-csv-files-aim-vol-issue-pag-desc-info-enriched.csv** sem a coluna `aim_info`, conforme solicitado.

[aim-from-pmb-csv-files-aim-vol-issue-pag-desc-info-enriched.zip](https://github.com/bireme/db-processing/files/6736959/aim-from-pmb-csv-files-aim-vol-issue-pag-desc-info-enriched.zip)

**Comment by botturam** [comment]
@renatomurasaki  estou  verificando se os tipos Monografia (v5='M') estão bem enriquecidos com a planilha acima, mas não encontrei o dado da coluna 4 (página) na base de dados (nem no xml original, nem no master file LILACS). Não sei de onde vieram. São 94 documentos, do tipo Monografia, nessa condição.

2 exemplos:

1=187171
2=
3=
4=1075-1083
5=
6=
7=
------
1=187169
2=
3=
4=999-1043
5=
6=
7=

**Comment by renatomurasaki** [comment]
@botturam vieram da base original do sistema de gestão do AIM. Repare que tem padrão de paginação, onde o first page é maior que last page.

**Comment by renatomurasaki** [comment]
@botturam pode liberar o ISIS atualizado para a Ana Kátia, se o único entrave que você encontrou é esse. Estamos com o prazo muito curto para ela executar a migração.

**Comment by renatomurasaki** [comment]
@botturam qualquer erro que a equipe da AFRO encontrar poderá ser ajustado posteriormente, uma vez que temos o histórico de todos os processos no Dremio responsáveis pela geração dos CSV que você utilizou no enriquecimento.

**Comment by renatomurasaki** [comment]
@botturam conforme conversamos sobre o campo v38^b, por favor, utilizar a versão atual do CSV, pois ao tentar incluir os casos com múltiplas ocorrências de informação descritiva com ; gerou muito efeito colateral. Depois poderemos decidir melhorar este dado pós migração, lembrando que atualmente esta informação não é nem mostrada na  interface de busca do GIM e AFRO.

**Comment by botturam** [comment]
base ISIS entregue à Kátia para migração no FIADMIN.

OFI5:/bases/lilG4/afr.fia/afro_lil_fiadmin.mst
