### ISSUE TITLE
Criar índice para identificar documentos na BVS que não estão indexados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#52]
A proposta é ter uma forma de recuperar documentos não indexados separadamente daqueles que estão indexados. Pode ajudar também na precisão da recuperação de documentos, combinando expressões ti e ab somente naqueles documentos que não estão indexados, por exemplo.

**Comment by botturam** [comment]
no processamento IAH-LILACS o índice de limites (CT) já contempla uma entrada que recupera docs LILACS-Express, nas seguintes circunstâncias:

5 0 if s(mpu,v4) : 'LILACSEXPRESS' then 'LX LILACS-LLXPSCIELO'/ fi,
5 0 if s(mpu,v4) : 'LLXPEDT' then 'LX LILACS-LLXPEDT'/ fi,
5 0 if s(mpu,v4) : 'LILACSEXPRESS' or s(mpu,v4) : 'LLXPEDT' then 'LX LILACS-EXPRESS'/ fi,

Antigamente, era usado para algumas pessoas selecionarem e exportarem, via ISO, os registros de interesse.

Para IAHx, vejo 3 hipóteses:

1) Criar um cluster exatamente como o atual cluster "Texto completo" ("fulltext"). A condição de existência desse novo campo seria a presença ou não dos campos "Tipo de Publicação", "Limites" ou Descritor [Primário ou Secundário] no documento da referência bibliográfica.

2) criar um índice oculto -- prefixo "ni", por exemplo --, que possibilitaria apenas quem conhecesse sua existência de praticar a pesquisa ni:$ ou ni:1, no box principal. A condição de existência desse novo campo ("ni" ou "no_indexing") seria a mesma do item anterior.

3) no formulário avançado, criar um novo índice novo uma nova entrada no próprio índice de Limites, indicando esses documentos. Não sugiro esta alternativa, pois o formulário avançado está precário em termos de bugs.

**Comment by renatomurasaki** [comment]
Creio que para a nossa necessidade, seria o cenário 2, sendo o critério para identificar que o documento não está indexado a ausência do campo MeSH/DeCS. Isso se aplicaria para todas as bases de dados like LILACS e Medline.

**Comment by renatomurasaki** [comment]
@botturam OK para as bases like LILACS. Funcionou perfeitamente o no_indexing:1. Muito obrigado.

Pode programar o reprocessamento das demais like LILACS que são atualizadas exporadicamente, como também Medline.

**Comment by botturam** [comment]
Índice oculto "no_indexing" gerado. Para pesquisar, basta digitar "no_indexing:1" ou "no_indexing:*" ou "no_indexing:$"

**Comment by anakatiacamilo** [comment]
ok obrigada

**Comment by renatomurasaki** [comment]
índice funcionando corretamente. @botturam favor informar a equipe SAU e FIR sobre esta nova funcionalidade.
