### ISSUE TITLE
Aplicar as estratégias de busca dos clusters "Type of Study" e "Clinical Aspects" a todos os registros do WHO COVID-19

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#520]

**Comment by botturam** [comment]
Considerando a estratégia do Portal Regional para marcar docs com tipo de estudo "clinical trial", abaixo, por que ela seleciona apenas 1.368 docs quando aplicada à FI ICTRP, sendo que existem 10.367 nesta base de dados?

((pt:"Ensaio Clinico Controlado Aleatorio" OR pt:"Ensaio Clinico Controlado" OR pt:"Estudo Multicentrico" OR mh:"Ensaios Clinicos Contr
olados Aleatorios como Assunto" OR mh:"Ensaios Clinicos Controlados como Assunto" OR mh:"Estudos Multicentricos como Assunto" OR mh:"Di
stribuicao Aleatoria" OR mh:"Metodo Duplo-Cego" OR mh:"Metodo Simples-Cego" OR mh:"Placebos") OR ((tw:ensaio* OR tw:ensayo* OR tw:trial
*) AND (tw:azar OR tw:acaso OR tw:placebo OR (tw:control* AND (tw:group OR tw:grupo)) OR tw:aleator* OR tw:randomi* OR tw:enmascarado*
OR tw:simpleciego OR ((tw:simple* OR tw:singl* OR tw:duplo* OR tw:doble* OR tw:doubl* OR tw:trebl* OR tw:tripl*) AND (tw:cego OR tw:cie
go OR tw:blind OR tw:mask OR tw:dumm*) AND tw:clinic*)))) AND NOT ((mh:animals OR mh:coelhos OR mh:ratos OR mh:camundongos OR mh:primat
as OR mh:caes OR mh:gatos OR mh:suinos OR mh:"tecnicas in vitro") AND NOT mh:humans)

**Comment by botturam** [comment]
foram criadas as rotinas para marcar os registros do COVID-WHO com as mesmas estratégias que marcam os registros do Portal Regional:

operacao@serverofi5:/bases/Strategies2IAHX/apps/strategies $ ll study_type/
total 100
drwxrwsr-x 2 operacao operacao 4096 May 21  2020 new/
-rw-rw-r-- 1 operacao operacao  349 Oct 16  2020 NOTAS
drwxrwsr-x 2 operacao operacao 4096 May 18  2020 old/
-rw-rw-r-- 1 operacao operacao  895 Apr 17  2020 STUDY_TYPE-clinical_trials.sch
-rw-rw-r-- 1 operacao operacao 3073 Oct 16  2020 STUDY_TYPE-determinantes_sociais_saude.sch
-rw-rw-r-- 1 operacao operacao  429 May 26  2020 STUDY_TYPE-diagnostic_studies.sch
-rw-rw-r-- 1 operacao operacao 1112 Jul  2  2020 STUDY_TYPE-equity_inequality.sch
-rw-rw-r-- 1 operacao operacao  291 Jul  2  2020 STUDY_TYPE-ethics.sch
-rw-rw-r-- 1 operacao operacao  296 May 26  2020 STUDY_TYPE-etiology_studies.sch
-rw-rw-r-- 1 operacao operacao  445 Jul  6  2020 STUDY_TYPE-evaluation_studies.sch
-rw-rw-r-- 1 operacao operacao 2375 May 18  2020 STUDY_TYPE-guideline.sch
-rw-rw-r-- 1 operacao operacao 2366 May 18  2020 STUDY_TYPE-health_economic_evaluation.sch
-rw-rw-r-- 1 operacao operacao 1655 Sep 16  2019 STUDY_TYPE-health_technology_assessment.sch
-rw-rw-r-- 1 operacao operacao 1624 Sep 16  2019 STUDY_TYPE-implementation_research.sch
-rw-rw-r-- 1 operacao operacao  340 May 18  2020 STUDY_TYPE-incidence_studies.sch
-rw-rw-r-- 1 operacao operacao 1886 May 26  2020 STUDY_TYPE-observational_studies.sch
-rw-rw-r-- 1 operacao operacao 4056 Jul  2  2020 STUDY_TYPE-patient_preference.sch
-rw-rw-r-- 1 operacao operacao  217 May 18  2020 STUDY_TYPE-policy_brief.sch
-rw-rw-r-- 1 operacao operacao  852 May 18  2020 STUDY_TYPE-prevalence_studies.sch
-rw-rw-r-- 1 operacao operacao 1325 May 26  2020 STUDY_TYPE-prognostic_studies.sch
-rw-rw-r-- 1 operacao operacao 1445 Jul 27  2020 STUDY_TYPE-qualitative_research.sch
-rw-rw-r-- 1 operacao operacao 3080 May 26  2020 STUDY_TYPE-risk_factors_studies.sch
-rw-rw-r-- 1 operacao operacao  761 May 18  2020 STUDY_TYPE-screening_studies.sch
-rw-rw-r-- 1 operacao operacao 1624 May 18  2020 STUDY_TYPE-sysrev_observational_studies.sch
-rw-rw-r-- 1 operacao operacao  793 May 18  2020 STUDY_TYPE-systematic_reviews.sch

Estará disponível no próximo processamento.

**Comment by renatomurasaki** [comment]
> Considerando a estratégia do Portal Regional para marcar docs com tipo de estudo "clinical trial", abaixo, por que ela seleciona apenas 1.368 docs quando aplicada à FI ICTRP, sendo que existem 10.367 nesta base de dados?
> 
> ((pt:"Ensaio Clinico Controlado Aleatorio" OR pt:"Ensaio Clinico Controlado" OR pt:"Estudo Multicentrico" OR mh:"Ensaios Clinicos Contr
> olados Aleatorios como Assunto" OR mh:"Ensaios Clinicos Controlados como Assunto" OR mh:"Estudos Multicentricos como Assunto" OR mh:"Di
> stribuicao Aleatoria" OR mh:"Metodo Duplo-Cego" OR mh:"Metodo Simples-Cego" OR mh:"Placebos") OR ((tw:ensaio* OR tw:ensayo* OR tw:trial
> _) AND (tw:azar OR tw:acaso OR tw:placebo OR (tw:control_ AND (tw:group OR tw:grupo)) OR tw:aleator* OR tw:randomi* OR tw:enmascarado*
> OR tw:simpleciego OR ((tw:simple* OR tw:singl* OR tw:duplo* OR tw:doble* OR tw:doubl* OR tw:trebl* OR tw:tripl*) AND (tw:cego OR tw:cie
> go OR tw:blind OR tw:mask OR tw:dumm*) AND tw:clinic*)))) AND NOT ((mh:animals OR mh:coelhos OR mh:ratos OR mh:camundongos OR mh:primat
> as OR mh:caes OR mh:gatos OR mh:suinos OR mh:"tecnicas in vitro") AND NOT mh:humans)

Isso acontece porque a estratégia foi pensada para recuperar artigos publicados a partir de resultados de ensaios clínicos, o que não é o mesmo que recuperar, com as mesmas palavras-chave, registros de ensaios clínicos. 

@botturam se ainda não está fazendo, favor marcar tudo que for ICTRP como ensaio clínico.

**Comment by renatomurasaki** [comment]
> foram criadas as rotinas para marcar os registros do COVID-WHO com as mesmas estratégias que marcam os registros do Portal Regional:
> 
> operacao@serverofi5:/bases/Strategies2IAHX/apps/strategies $ ll study_type/
> total 100
> drwxrwsr-x 2 operacao operacao 4096 May 21 2020 new/
> -rw-rw-r-- 1 operacao operacao 349 Oct 16 2020 NOTAS
> drwxrwsr-x 2 operacao operacao 4096 May 18 2020 old/
> -rw-rw-r-- 1 operacao operacao 895 Apr 17 2020 STUDY_TYPE-clinical_trials.sch
> -rw-rw-r-- 1 operacao operacao 3073 Oct 16 2020 STUDY_TYPE-determinantes_sociais_saude.sch
> -rw-rw-r-- 1 operacao operacao 429 May 26 2020 STUDY_TYPE-diagnostic_studies.sch
> -rw-rw-r-- 1 operacao operacao 1112 Jul 2 2020 STUDY_TYPE-equity_inequality.sch
> -rw-rw-r-- 1 operacao operacao 291 Jul 2 2020 STUDY_TYPE-ethics.sch
> -rw-rw-r-- 1 operacao operacao 296 May 26 2020 STUDY_TYPE-etiology_studies.sch
> -rw-rw-r-- 1 operacao operacao 445 Jul 6 2020 STUDY_TYPE-evaluation_studies.sch
> -rw-rw-r-- 1 operacao operacao 2375 May 18 2020 STUDY_TYPE-guideline.sch
> -rw-rw-r-- 1 operacao operacao 2366 May 18 2020 STUDY_TYPE-health_economic_evaluation.sch
> -rw-rw-r-- 1 operacao operacao 1655 Sep 16 2019 STUDY_TYPE-health_technology_assessment.sch
> -rw-rw-r-- 1 operacao operacao 1624 Sep 16 2019 STUDY_TYPE-implementation_research.sch
> -rw-rw-r-- 1 operacao operacao 340 May 18 2020 STUDY_TYPE-incidence_studies.sch
> -rw-rw-r-- 1 operacao operacao 1886 May 26 2020 STUDY_TYPE-observational_studies.sch
> -rw-rw-r-- 1 operacao operacao 4056 Jul 2 2020 STUDY_TYPE-patient_preference.sch
> -rw-rw-r-- 1 operacao operacao 217 May 18 2020 STUDY_TYPE-policy_brief.sch
> -rw-rw-r-- 1 operacao operacao 852 May 18 2020 STUDY_TYPE-prevalence_studies.sch
> -rw-rw-r-- 1 operacao operacao 1325 May 26 2020 STUDY_TYPE-prognostic_studies.sch
> -rw-rw-r-- 1 operacao operacao 1445 Jul 27 2020 STUDY_TYPE-qualitative_research.sch
> -rw-rw-r-- 1 operacao operacao 3080 May 26 2020 STUDY_TYPE-risk_factors_studies.sch
> -rw-rw-r-- 1 operacao operacao 761 May 18 2020 STUDY_TYPE-screening_studies.sch
> -rw-rw-r-- 1 operacao operacao 1624 May 18 2020 STUDY_TYPE-sysrev_observational_studies.sch
> -rw-rw-r-- 1 operacao operacao 793 May 18 2020 STUDY_TYPE-systematic_reviews.sch
> 
> Estará disponível no próximo processamento.

Excelente @botturam. Inclui também as estratégias do cluster "Clinical Aspects"?

**Comment by botturam** [comment]
inserido o campo abaixo em todos os registros ICTRP

<field name="type_of_study">clinical_trials</field>

**Comment by renatomurasaki** [comment]
@botturam favor aplicar as estratégias relacionadas ao cluster clinical aspects

**Comment by botturam** [comment]
O cluster "Clinical aspect" já existe. Atualmente são aplicadas as estratégias IAH abaixo.

operacao@serverofi5:/bases/lilG4/bvs.reg.ori $ ll CLINI*LIL*sch
-rw-rw-r-- 1 operacao operacao 227 Nov  1  2016 CLINICAL-LIL-diagnosis.sch
-rw-rw-r-- 1 operacao operacao 221 Nov  1  2016 CLINICAL-LIL-etiology.sch
-rw-rw-r-- 1 operacao operacao 173 Nov  1  2016 CLINICAL-LIL-prediction.sch
-rw-rw-r-- 1 operacao operacao 131 Nov  1  2016 CLINICAL-LIL-prognosis.sch
-rw-rw-r-- 1 operacao operacao 301 Nov  1  2016 CLINICAL-LIL-therapy.sch

operacao@serverofi5:/bases/lilG4/bvs.reg.ori $ more CLINI*LIL*sch
::::::::::::::
CLINICAL-LIL-diagnosis.sch
::::::::::::::
(((TW sensitiv$ OR TW specificity OR TW especificida$ or TW sensibilid$) AND TW diagnos$) OR MH diagnostico or MH diagnostico diferenci
al OR MH Sensibilidade e Especificidade OR MH /DI OR EX E01.370$ OR MH diagnostico precoce)
::::::::::::::
CLINICAL-LIL-etiology.sch
::::::::::::::
((TW risco$ OR TW risk$ OR TW riesgo$) AND (TW fator$ OR TW factor$)) OR TW causalidad$ OR MH fatores de risco or MH causalidade OR MH
fatores desencadeantes OR MH estudos de coortes or TW coorte$ OR TW cohort$ OR MH /ET
::::::::::::::
CLINICAL-LIL-prediction.sch
::::::::::::::
TW predict$ OR MH Valor Preditivo dos Testes or MH Variacoes Dependentes do Observador OR ((TI scor$ OR TI measur$ OR TI rate OR TI rat
ing) AND (TI observ$ OR TI validat$))
::::::::::::::
CLINICAL-LIL-prognosis.sch
::::::::::::::
TW incidencia OR MH mortalidade OR MH Seguimentos OR TW prognos$ OR TW pronosti$ OR MH EX E01.789$ OR (TW estud$ and tw prospect$)
::::::::::::::
CLINICAL-LIL-therapy.sch
::::::::::::::
((TW clinic$ AND (tw ensayo$ or tw ensaio$ or TW trial)) OR MH EX E05.337.250$ OR PT ensaio$ OR (TW random$ and (TW aloca$ or TW alloca
tion)) OR (TW randomiz$ OR TW acaso or TW azar or TW aleator$ OR MH distribuicao aleatoria)) AND (MH /TU OR MH /TH OR MH /DT OR MH /SU
OR MH /DH OR MH /RT) OR MH /TU

**Comment by botturam** [comment]
@renatomurasaki disponível em produção.

**Comment by renatomurasaki** [comment]
@botturam é possível aplicar as estratégias Clinical Aspects para todas as fontes de informação do WHO COVID-19, da mesma maneira que você fez para as estratégias do Type of Study?

**Comment by renatomurasaki** [comment]
@botturam de fato as estratégias de Clinical Aspects estão sendo aplicadas, com a exceção da base ICTRP. O "Therapy" é muito restritivo e por isso só recupera Medline e LILACS.
