### ISSUE TITLE
Generate CSV files for AFRO

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#53]
Please, use the recent mapping between UNIMARC and LILACS methodologies.

**Comment by botturam** [comment]
CSVs disponíveis em serverofi5:/bases/lilG4/gim.lil/afro_tab/

**Comment by renatomurasaki** [comment]
@botturam please, modify the processing script to include on CSV files the raw data for mesh/decs descriptor and publication type.

**Comment by botturam** [comment]
included raw data for mesh/decs descriptor and publication type.

**Comment by botturam** [comment]
new tabulation avaiable on FTP server (user OFI - directory "gim").

according to chronology, this new tabulation was done regarding some fix errors in  export921442001508252049.xml, after the first data analysis report (by DataCleaner software) sent to AFRO team.
