### ISSUE TITLE
Inclusão de campos no schema do Solr COVID/WHO

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#531]
Para que a IAHx possa mostrar os triples da base SemMedDB na interface do COVID/WHO, serão necessários o armazenamento e indexação dos seguintes novos campos a serem incluídos nos arquivos xml:   

    <field name="semantic">SUBJECT:[Kidney Transplantation] PREDICATE:[TREATS] OBJECT:[Tuberous Sclerosis]</field>
    <field name="semantic_subject">Kidney Transplantation</field>
    <field name="semantic_predicate">TREATS</field>
    <field name="semantic_object">Tuberous Sclerosis</field>
    <field name="semantic_triple">Kidney Transplantation TREATS Tuberous Sclerosis</field>

O primeiro campo é só para se fazer o display do conteúdo, não necessitando ser indexado, apenas armazenado. Os demais devem ser indexados e armazenados.

**Comment by viniciusandrade** [comment]
@botturam por favor adicionar estes novos campos no schema do índice para solr3 e solr5. 

Qualquer dúvida é só informar.

**Comment by renatomurasaki** [comment]
@botturam favor aguardar a conclusão do issue #528

**Comment by botturam** [comment]
Campos incluídos. Aguardar processamento.

**Comment by botturam** [comment]
Favor testar.

**Comment by renatomurasaki** [comment]
@botturam segundo o seu comentário, o documento com ID **covidwho-1316676** deveria ter os elementos semânticos no XML, mas não os encontro:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?output=xml&lang=en&from=&sort=&format=&count=&fb=&page=1&skfp=&index=tw&q=id%3Acovidwho-1316676

Favor verificar

**Comment by botturam** [comment]
isolei apenas 5 documentos para teste, e deu certo! Quando tentei com um xml maior (2020 ou 2021), deu erro no proc. IAHx-Covid (Solr5):

/bases/iahx/exec/**update-index.sh -p covidwho**
unix2dos: converting file logs/out-update.20210726.txt to DOS format ...
Tempo de execucao de cron_weekly3.sh -p covidwho de (1) 2021-07-26 17:09:36 ate (1) 2021-07-26 17:10:07 =      31[s] ou 00:00:31
[TIME-STAMP] (1) 2021-07-26 17:10:07 [:FIM:] {25752} **cron_weekly3.sh** -p covidwho
*** FAIL +++ step 2 - index index  *** EXIT CODE (5) ***
*** FAIL +++ step 1 - index weekly  *** EXIT CODE (5) ***
91:*** FAIL +++ step 2 - index index  *** EXIT CODE (5) ***
92:*** FAIL +++ step 1 - index weekly  *** EXIT CODE (5) ***
91:*** FAIL +++ step 2 - index index  *** EXIT CODE (5) ***
92:*** FAIL +++ step 1 - index weekly  *** EXIT CODE (5) ***
         x.xx.xx.xx -Execucao terminada

Testei no Solr3 e Solr5; nos XMLs mdl_covidwho_2020.xml e mdl_covidwho_2021.xml; funcionou apenas com mdl_covidwho_2022.xml (5 docs isolados de mdl_covidwho_2021.xml. 

OBS: INBOX-XML-COVID: /bases/iahx/xml-inbox/covidwho

Pedirei ao Chico para verificar esse erro e por que ele não parou o processamento, se é que era possível.

**Comment by botturam** [comment]
@ChicoLopes os campos abaixos foram incluídos em /home/javaapps/iahx-server/indexes/solr5-port3/covidwho/conf/schema.xml, 

e os documentos de /bases/iahx/xml-inbox/covidwho/mdl21_SemMedDB/mdl_covidwho_2021.xml receberam os campos do schema (exemplo no início desse chamado)

Logo no início do processamento IAHx-COVIDWHO (porta 3), ocorre um erro em cron_weekly3.sh

Você poderia verificar?



   

   <field name="semantic"            type="text"      indexed="false"  stored="true"  multiValued="true"/>
   <field name="semantic_subject"    type="text"      indexed="true"   stored="true"  multiValued="true"/>
   <field name="semantic_predicate"  type="text"      indexed="true"   stored="true"  multiValued="true"/>
   <field name="semantic_object"     type="text"      indexed="true"   stored="true"  multiValued="true"/>
   <field name="semantic_triple"     type="text"      indexed="true"   stored="true"  multiValued="true"/>

**Comment by botturam** [comment]
issue relacionado: bireme/db-processing#535
issue relacionado: bireme/db-processing#539

**Comment by botturam** [comment]
@heitorbarbieri foram detectados os seguintes problemas no dado:

1)  [<12 months]                                      => [less then 12 months]
 2) [Procedures on Tonsils & Adenoids]   => [Procedures on Tonsils and Adenoids]

É possível mudá-lo na origem? (seria mais fácil e menos demorado aplicar um SED nos XMLs das bases de dados)

**Comment by botturam** [comment]
Deu certo!!! está disponível em teste:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/

**Comment by renatomurasaki** [comment]
@botturam testei e está ok tanto o XML como a recuperação pelos respectivos índices. Pode colocar em produção, por favor.
