### ISSUE TITLE
Exportar para equipe da OMS, o RefId dos registros bibliográficos sem informação de idioma que vem da exportação diária (Distiller/EndNote)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#532]
Essa exportação deve excluir, por exemplo, os registros que vem da coleta dos preprints (medRxiv e bioRxiv) e ensaios clínicos (ICTRP)

**Comment by botturam** [comment]
foi gerado, através da coleta de IDS da IAHx-Covidwho, o arquivo **covidwho_no_language_ID.csv** (anexo), que possui  98.953 linhas:

CovNum|iahxID|Database
820549|covidwho-820549|A9H
820561|covidwho-820561|A9H
820562|covidwho-820562|A9H
822142|covidwho-822142|A9H
855885|covidwho-855885|Airiti Library
855886|covidwho-855886|Airiti Library
855888|covidwho-855888|Airiti Library

Aguardo verificação antes de enviá-lo.
[covidwho_no_language_ID.txt](https://github.com/bireme/db-processing/files/6816595/covidwho_no_language_ID.txt)

**Comment by renatomurasaki** [comment]
@botturam obrigado. Editei o arquivo TXT que você gerou para excluir as referências vindas do ICTRP, bioRxiv e medRxiv. Nestes 3 casos estou aguardando autorização da equipe da OMS para automaticamente colocarmos o idioma 'en' no campo language durante o processamento.

Seguem os arquivos que compartilhei com a equipe:

[murasaki-who-covid-19-covidwho_no_language.zip](https://github.com/bireme/db-processing/files/6817191/murasaki-who-covid-19-covidwho_no_language.zip)

O outro CSV mostra a concentração de citações por base de dados para que eles possam priorizar a correção deste campo.

**Comment by renatomurasaki** [comment]
Arquivos enviados para a equipe da OMS por e-mail.
