### ISSUE TITLE
Inclusão no shell de geração dos xml para o IAHx - COVID/WHO do subprocesso que acrescenta os triples semanticos do SemMedDB

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#535]
@botturam  precisamos juntos alterar o mesmo shell que chama o MarkAbstract para que também chame o processo de geração dos triples. Você já me mostrou onde fazê-lo mas ainda preciso de sua ajuda para não gerar outros efeitos colaterais pela modificação do shell.

**Comment by heitorbarbieri** [comment]
relacionado ao #531

**Comment by botturam** [comment]
campos já foram inseridos e estão disponíveis nos XMLs-MDL

Até agora foi feito manualmente. Falta colocar em produção regular.

**Comment by botturam** [comment]
inserido em shs/rodaCOVIDWHO.sh , ao final do proc. Covid WHO

echo "- executa AddPredicatesOfi5.sh... (SemMedDB)"
TPR="iffatal"
MSG="Erro: AddPredicatesOfi5.sh /bases/iahx/xml-inbox/covidwho"
/home/javaapps/sbt-projects/AddPredicates/bin/AddPredicatesOfi5.sh /bases/iahx/xml-inbox/covidwho
. log

Será habilitado assim que o problema de #531 sejam sanados.

**Comment by botturam** [comment]
@heitorbarbieri @renatomurasaki  problema resolvido.

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/

já liberei a execução de /home/javaapps/sbt-projects/AddPredicates/bin/AddPredicatesOfi5.sh  durante o proc. do COVIDWHO

**Comment by renatomurasaki** [comment]
@heitorbarbieri @botturam muito obrigado. Já fechei o chamado #531 pois já validei o ambiente de testes. Pode colocar em produção.
