### ISSUE TITLE
DeCS 2021 - atualização e distribuição dos insumos do DeCS - versão 2

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#538]
Link para a documentação deste processo no sharepoint: [https://bit.ly/2TivjvO](https://bit.ly/2TivjvO)
----------
Tarefas:

0 Marcelo
- Processamento novo DeCS e disponibilização dos insumos para as atualizações dos demais serviços 

1o. Vinicius
- iAHX (atualizar portas em instances /home/javaapps/iahx-server/instances/?/resources)
- Depois que o Vini atualizar, processar o comando abaixo
- IAHx controler (para interfaces IAHx - compartilhado)

2o. Todos em OFI5 (coleta FI-Admin, MarkAbstract, etc.)
Utiliza no $TABS da serverofi5 o decs.id e decs.{mst,xrf}
- MarkAbstract
 
3o. Marcelo
- dcs_regional - aguardando pronto em /bases/iahx/xml-inbox/decs/wait, é só mover para ..
- Atualizar processo de coleta FI-Admin
- serverofi5:/bases/fiadmin/consolida/tpl/Atualiza_DeCS_ANUAL.sh
- FI-Admin - o diretório VMX deverá ser copia para dolomita11 ou para o bases??? - verificar diretório (PERGUNTAR PARA VÍNICIUS)
	
4o. Wilson
Virada do portal DeCS Teste para Portal DeCS Produção 
- base congelada
- índice SoLR
- se necessário, gerar cache do portal

5o. Heitor
Utiliza no $TABS da serverofi5 o decs.id e decs.{mst,xrf}
- BVS-InfoButton
- DeCSHighlighter
- SimilarDocs
- e-BlueInfo

6o. Ana Kátia
- Lildbi WEB (migração)

**Comment by wilsonmoura** [comment]
4. Virada do Portal DeCS Teste para Portal DeCS Produção (Wilson)
    - base congelada - **OK**
    - índice SoLR - **OK**
    - se necessário, gerar cache do portal - **OK**

**Comment by viniciusandrade** [comment]
@botturam editei a descrição deste issue para adicionar a tarefa inicial de processamento e disponibilização dos insumos para os que seja possível atualizar os demais serviços. 

Favor quando os insumos forem liberados informar por aqui para que possamos prosseguir.

Obrigado

**Comment by botturam** [comment]
@viniciusandrade @wilsonmoura  @heitorbarbieri @anakatiacamilo 

1. novo DeCS-2021 atualizado nas instâncias de processamento MDL e like-LILACS; tabelas auxiliares também preparadas.

    \/bases/lilG4/tabs
    \/bases/mdlG4/tabs
    \/usr/local/bireme/tabs
    \/bases/fiadmin/consolida/tabs (para coleta do FI-ADMIN)

2. DeCS como fonte de informação (dcs_regional.xml) disponível para IAHx-Portal-Regional.
   operacao@serverofi5:/bases/iahx/xml-inbox/decs $ ll
   -rw-rw-r-- 1 operacao operacao 239774094 Jul 22 12:14 dcs_regional.xml

**Comment by botturam** [comment]
quem precisar da documentação do proc DeCS, para consultar ou editar:

https://paho.sharepoint.com/sites/BIR/TC/TC/Forms/AllItems.aspx?id=%2Fsites%2FBIR%2FTC%2FTC%2FGerencias%2FMTI%2Fdocumentacao%2Dsaida%2Dfabio%2Dbrito%2FDeCS%2FFluxo%20de%20atualizacao%2F4%20%2D%20Processamento%20DeCS%20%2D%20Marcelo%2FProcessamento%20DeCS%2Etxt&parent=%2Fsites%2FBIR%2FTC%2FTC%2FGerencias%2FMTI%2Fdocumentacao%2Dsaida%2Dfabio%2Dbrito%2FDeCS%2FFluxo%20de%20atualizacao%2F4%20%2D%20Processamento%20DeCS%20%2D%20Marcelo&p=5

**Comment by viniciusandrade** [comment]
@botturam analizador atualizado nas instâncias do serverofi5 ... válido quando for realizado restart da instância solr. 
Qualquer problema favor avisar.

Vinicius

- iAHX analyzer (serverofi5 / basalto01 / basalto02 ) - OK (serverofi5)
- iAHx controler - pendente
- Localizador DeCS - pendente

**Comment by heitorbarbieri** [comment]
Atualização DeCS 2021 - versão 2

BVS-InfoButton - OK
DeCSHighlighter - OK
MarkAbstract - OK
SimilarDocs - OK
e-BlueInfo - OK

**Comment by viniciusandrade** [comment]
Atualização DeCS 2021 - versão 2

- iAHX analyzer (serverofi5 / basalto01 / basalto02 ) - **OK**
- iAHx controler - **OK**
- Localizador DeCS - **OK**

**Comment by viniciusandrade** [comment]
@botturam analizador atualizado nas instâncias basalto01 e basalto02 ... válido quando for realizado restart da instância solr.
Qualquer problema favor avisar.

**Comment by viniciusandrade** [comment]
@botturam eu e o @wilsonmoura identificamos um pequeno problema com o campo de notas de indexação na última base de dados disponibilizada.

O Wilson gerou uma nova base e transferiu para /bases/dec.000/get_thesaurus/wrk_ths_1/

Você poderia gerar novamente somete a base do serviço VMX e disponibilizar no servidor de testes?

Obrigado

**Comment by botturam** [comment]
Executarei novamente o shell nohup ../tpl.dec/GenDECS.sh 2021 La &

Isso vai demorar 5 horas aproximadamente. Eu darei sequência assim que terminar ainda hoje.

**Comment by viniciusandrade** [comment]
OK, obrigado ... lembrando que só é necessário atualizar a base do serviço VMX ... os demais estão OK.

**Comment by botturam** [comment]
@viniciusandrade transferido

de....: OFI5:/bases/dec.000/dec.dec/outputvmx
para: dolomita02:/home/apps/bvs.br/wp-decs/www/bases/vmx/

**Comment by viniciusandrade** [comment]
@botturam infelizmente o processo não atualizou os campos de nota de indexação. 

Seguem as informações que tenho para auxiliar no processo de encontrar o problema verificando os campos **110, 210 e 310**

O @wilsonmoura me informou que realizou um novo processamento e o resultado foi transferido para:

serverofi5:/bases/dec.000/get_thesaurus/wrk_ths_1/

Executando neste diretório 
**mx fiadmin_decs from=5**

```
  1  "Abdomen"
  2  "Abdomen"
  3  "Abdome"
  4  "abdomen"
  5  "^nThat portion of the body that lies between the THORAX and the PELVIS."
  6  "^nPorción del cuerpo que se encuentra entre el TÓRAX y la PELVIS."
  7  "^nRegião do corpo que se localiza entre o TÓRAX e a PELVE."
  8  "^nPorción del cuerpo que se encuentra entre el TÓRAX y la PELVIS."
 16  "Abdomen"
 20  "A01.923.047"
 50  "^fVentre"
 50  "^iAbdomens"
 50  "^pAbdômen"
 99  "000005"
105  "H"
106  "h"
110  "^ngeneral or unspecified; prefer specifics; ABDOMINAL MUSCLES and specifics are available; abrupt disease requiring emergency surgery equals ABDOMEN, ACUTE"**
170  "IN^iAbdominal Injuries"
210  "^ngeneral o no especificado; prefiera específicos; MÚSCULOS ABDOMINALES y específicos están disponibles; para la enfermedad abrupta requiriendo cirugía de urgencia utilice ABDOMEN AGUDO"
310  "^ngeral ou não especificado; prefira específicos; MÚSCULOS ABDOMINAIS e específicos estão disponíveis; doença abrupta requerendo cirurgia de emergência use ABDOME AGUDO"
480  "D000005"
776  "000005"
950  "AB AH BS DG EM GD IR MI PA PH PP PS RE SU VI"
999  "000005"
```

Já no diretório resultado do seu processamento se eu executo o mesmo comando os valores são da versão anterior.

```
mfn=     5 
  1  "Abdomen"
  2  "Abdomen"
  3  "Abdome"
  4  "abdomen"
  5  "^nThat portion of the body that lies between the THORAX and the PELVIS."
  6  "^nPorci�n del cuerpo que se encuentra entre el T�RAX y la PELVIS."
  7  "^nRegi�o do corpo que se localiza entre o T�RAX e a PELVE."
  8  "^nPorci�n del cuerpo que se encuentra entre el T�RAX y la PELVIS."
 16  "Abdomen"
 20  "A01.923.047"
 21  "A01923047"
 50  "^fVentre"
 50  "^iAbdomens"
 50  "^pAbd�men"
 99  "000005"
105  "H"
106  "h"
110  "^nGEN: prefer specifics; abdom muscles = ABDOMINAL MUSCLES but RECTUS ABDOMINIS is available; abdominal pain = ABDOMINAL PAIN; abrupt dis requiring emerg surg = ABDOMEN, ACUTE"
210  "^ngeneral o no especificado; prefiera espec�ficos; M�SCULOS ABDOMINALES y espec�ficos est�n disponibles; para la enfermedad abrupta requiriendo cirug�a de urgencia utilice ABDOMEN AGUDO"
310  "^nGER: prefira espec�ficos; m�sculos abdominais = M�SCULOS ABDOMINAIS mas RETO DO ABDOME est� dispon�vel; dor abdominal = DOR ABDOMINAL; doen�a abrupta requerendo cirurgia de emerg�ncia = ABDOME AGUDO"
480  "D000005"
500  "T029^hA2.1.5.2^iBody Location or Region^eSitio o Regi�n del Cuerpo^pS�tio ou Regi�o do Corpo"
776  "000005"
950  "AB AH BS DG EM GD IR MI PA PH PP PS RE SU VI"
999  "000005"
2023  "A^o1^m5^iANATOMY^eANATOM�A^pANATOMIA^j59596^2.^iANATOMY^eANATOM�A"
2023  "A01^o1^m5^1A^iBody Regions^eRegiones Corporales^pRegi�es do Corpo^j1854^2.^iBody Regions^eRegiones Corporales"
2023  "A01.923^o1^m5^1A01^iTorso^eTorso^pTronco^j54411^2.^iTorso^eTorso"
2023  "A01.923.047^o1^m5^1A01.923^iAbdomen^eAbdomen^pAbdome^j5^iAbdomen^eAbdomen"
170  "IN^iAbdominal Injuries"
170  "IN^eTraumatismos Abdominales"
170  "IN^pTraumatismos Abdominais"

```

Poderia por favor verificar?

Obrigado

**Comment by botturam** [comment]
@viniciusandrade  @wilsonmoura novo DeCS para VMX, em dolomita02, disponível.

dolomita02:/home/apps/bvs.br/wp-decs/www/bases/vmx/

**Comment by botturam** [comment]
1. novo DeCS-2021 atualizado nas instâncias de processamento MDL e like-LILACS; tabelas auxiliares também preparadas.

/bases/lilG4/tabs
/bases/mdlG4/tabs
/usr/local/bireme/tabs
/bases/fiadmin/consolida/tabs (para coleta do FI-ADMIN)

2. DeCS como fonte de informação (dcs_regional.xml) disponível para IAHx-Portal-Regional.
operacao@serverofi5:/bases/iahx/xml-inbox/decs $ ll
total 925972
-rw-rw-r-- 1 operacao operacao 239891371 Aug  6 11:44 dcs_regional.xml

**Comment by botturam** [comment]
Foram atualizados os arquivos zdecs?.* (interface IAH) em **serverw e basalto02** (vide documentação em FC):

zdecse.mst
zdecse.xrf
zdecsi.mst
zdecsi.xrf
zdecsp.mst
zdecsp.xrf

**Comment by viniciusandrade** [comment]
> @viniciusandrade @wilsonmoura novo DeCS para VMX, em dolomita02, disponível.
> 
> dolomita02:/home/apps/bvs.br/wp-decs/www/bases/vmx/

@botturam OK, arquivos transferidos pelo ITI para produção e portanto WS do DeCS atualizado. 

Obrigado

**Comment by botturam** [comment]
@heitorbarbieri @anakatiacamilo @wilsonmoura caros amigos, posso encerrar esse chamado?

**Comment by heitorbarbieri** [comment]
Atualização DeCS 2021 - última versão

BVS-InfoButton - OK
DeCSHighlighter - OK
MarkAbstract - OK
SimilarDocs - OK
e-BlueInfo - OK

**Comment by botturam** [comment]
concluído
