### ISSUE TITLE
Colocar no Celery a coleta da Title do FI-ADMIN 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#540]
Por favor, colocar o script de coleta dos registros da title do Fi-ADMIN no Celery para ser executados nos dia segundas, quartas e sextas as 6h da manha.
path:  /bases/iahx/proc/coletas/main/title/
script: coleta_title.sh
Grata

**Comment by botturam** [comment]
repetir o mesmo processo de ICTRP, criando o projeto em /bases/apps/ofi_django_project  (atalho DJA) e cadastrando no DJANGO

**Comment by ChicoLopes** [comment]
@botturam coleta da Title do FI-ADMIN foi incluída no Celery, conforme os passos da Wiki para shell sem parâmetros. A seguir foi feito o cadastramento do Django conforme documento Cadastrando_e_Agendando_nova_tarefa_na_Administracao_do_Django.pdf

**Comment by botturam** [comment]
@santosfj  por favor, verificar o erro ao final do arquivo de log:

serverofi5:/bases/logs/celery/logs/coleta_title.log

Ademais, está funcionando bem.

**Comment by ChicoLopes** [comment]
@botturam verificado era um erro "inocente" no início do shell que fazia a inclusão do infoini.inc, mas estava referindo o diretório errado (havia um /inc a mais), isso levava a faltarem as funções de conversao  calculo de hora e tempo de execução. Está devidamente alterado. Obs: Isso estava assim desde sempre!
