### ISSUE TITLE
Corrigir erro de diacríticos na interface iAHx AIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#543]
![image](https://user-images.githubusercontent.com/1226218/126347553-da4d1eb6-096c-462f-a33b-62c7db40a1d9.png)

No FI-Admin está correto

![image](https://user-images.githubusercontent.com/1226218/126347642-d25fdde6-d89d-43c3-a82f-9b2be440b225.png)

**Comment by renatomurasaki** [comment]
@botturam o mesmo está ocorrendo para o resumo

No Fi-Admin
![image](https://user-images.githubusercontent.com/1226218/126348551-36d098a5-27ca-4f2d-8e27-3e0f644dd5a5.png)

Na interface
![image](https://user-images.githubusercontent.com/1226218/126348600-b8cdf8b2-8341-4544-a305-fec37b1182e7.png)

**Comment by botturam** [comment]
retirado "tidy" executado na AIM e em outras FIs UTF-8 quando da geração do XML para IAHx. Agora, AIM vem do FI-ADMIN, e por isso não é mais necessário.

tidy -xml -w 0 -i -utf8 -o ${PARM1}_$NOMEINST.xml_tmp ${PARM1}_$NOMEINST.xml

**Comment by botturam** [comment]
aguardar atualização amanhã, 3f

**Comment by botturam** [comment]
disponível em produção

**Comment by renatomurasaki** [comment]
@botturam verificado e ok. Obrigado
