### ISSUE TITLE
COVID WHO - verificar qual o problema de caractere no registro covidwho-790204

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#546]
- documeto isolado em (covidwho-790204):

serverofi5:/bases/bases/oai.pmh/csv.rec/covidwho/cvd_doc_ab_problem.xml

- CSV original:

/bases/oai.pmh/csv.rec/covidwho/who-covid-19-repo-export2iAHxProcessingOnlyAbstract.csv.15jul2021

**Comment by botturam** [comment]
/bases/oai.pmh/csv.rec/covidwho/ruim/cvd_doc_ab_problem.xml

**Comment by ChicoLopes** [comment]
Encontrado no final do abstract um caracter UTF-8 mal formado, talvez devido ao truncamento do texto. Este foi apagado dando condição de XML bem formado. O arquivo anexo mostra os bytes eliminados.

![COVIDWHO_BadChar](https://user-images.githubusercontent.com/670205/126833859-da71b7e0-ebcc-46d2-8d1e-4de4ff8815e5.png)

**Comment by renatomurasaki** [comment]
@ChicoLopes excelente!

**Comment by ChicoLopes** [comment]
@renatomurasaki 🙏🏼
