### ISSUE TITLE
Doenças transmissíveis - Histoplasmosis

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#550]
Tema Doenças transmissíveis Evid@Easy

arquivo corrigido
[3.3.Histoplasmosis_x.txt](https://github.com/bireme/db-processing/files/6901503/3.3.Histoplasmosis_x.txt)

**Comment by ChicoLopes** [comment]
Espressão revisada

**Comment by ChicoLopes** [comment]
@botturam arquivo de estratégia de Doenças Transmissíveis (transmisible_diseases), denominado 4_TD-4_histoplasmosis.sch está processado com dados disponíveis para continuidade do processo e agendamento de coleta semanal automática (para sábado às 0:30 com duração de aproximadamente 30 min) implantado.
