### ISSUE TITLE
Doenças transmissíveis -Paracoccidioidomycosis

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#553]
Tema Doenças transmissíveis Evid@Easy

arquivo corrigido
[3.3.Paracoccidioidomycosis_x.txt](https://github.com/bireme/db-processing/files/6901663/3.3.Paracoccidioidomycosis_x.txt)

**Comment by ChicoLopes** [comment]
@botturam arquivo de estratégia de Doenças Transmissíveis (transmisible_diseases), denominado 4_TD-4_paracoccidioidomycosis.sch está processado com dados disponíveis para continuidade do processo e agendamento de coleta semanal automática (para sábado às 0:30 com duração de aproximadamente 30 min) implantado.
