### ISSUE TITLE
Generate CSV files for SEARO

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#56]

**Comment by botturam** [comment]
É preciso construir um processamento de conversão XML2ISIS de registro SEARO-XML para ISIS-LILACS.

Exemplo de registro:

      <record>
        <header>
          <identifier>oai:imsear.hellis.org:123456789/588</identifier>
          <datestamp>2015-10-26T11:54:51Z</datestamp>
          <setSpec>com_123456789_2</setSpec>
          <setSpec>com_123456789_1</setSpec>
          <setSpec>col_123456789_8</setSpec>
        </header>
        <metadata>
          <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:doc="http://www.lyncode.com/xoai" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dc="http://purl.org/dc/elements/1.1/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
            <dc:title>Evaluation of an early childhood parenting programme in rural Bangladesh.</dc:title>
            <dc:creator>Aboud, Frances E</dc:creator>
            <dc:subject>Adult</dc:subject>
            <dc:subject>Bangladesh</dc:subject>
            <dc:subject>Child Development</dc:subject>
            <dc:subject>Child, Preschool</dc:subject>
            <dc:subject>Female</dc:subject>
            <dc:subject>Health Behavior</dc:subject>
            <dc:subject>Health Knowledge, Attitudes, Practice</dc:subject>
            <dc:subject>Health Promotion</dc:subject>
            <dc:subject>Humans</dc:subject>
            <dc:subject>Intervention Studies</dc:subject>
            <dc:subject>Male</dc:subject>
            <dc:subject>Mothers --education</dc:subject>
            <dc:subject>Parenting --psychology</dc:subject>
            <dc:subject>Parents --education</dc:subject>
            <dc:subject>Program Evaluation</dc:subject>
            <dc:subject>Social Support</dc:subject>
            <dc:description>Journal of Health, Population, and Nutrition.</dc:description>
            <dc:description>To promote physical and mental development of children, parenting education programmes in developing countries focus on specific practices such as age-appropriate responsive stimulation and feeding. A programme delivered to groups of poor mothers of children, aged less than three years, in rural Bangladesh was evaluated using an intervention-control post-test design. Mothers (n=170) who had attended a year of educational sessions and their children were compared with those (n=159) from neighbouring villages who did not have access to such a programme. After covariates were controlled, the parenting mothers obtained higher scores on a test of child-rearing knowledge and on the Home Observation for Measurement of the Environment (HOME) inventory of stimulation. The parenting mothers did not communicate differently with their children while doing a picture-talking task, and children did not show benefits in nutritional status or language comprehension. Parenting sessions offered by peer educators were informative and participatory, yet they need to include more practice, problem-solving, and peer-support if information is to be translated into behaviour.</dc:description>
            <dc:description>ICDDR,B, GPO Box 128, Dhaka 1000, Bangladesh. frances.aboud@mcgill.ca</dc:description>
            <dc:date>2007-03-10</dc:date>
            <dc:date>2009-05-27T03:49:37Z</dc:date>
            <dc:date>2007-03-10</dc:date>
            <dc:date>2009-05-27T03:49:37Z</dc:date>
            <dc:date>2007-03-10</dc:date>
            <dc:type>Journal Article</dc:type>
            <dc:type>Research Support, Non-U.S. Gov't</dc:type>
            <dc:identifier>Aboud FE. Evaluation of an early childhood parenting programme in rural Bangladesh. Journal of Health, Population, and Nutrition. 2007 Mar; 25(1): 3-13</dc:identifier>
            <dc:identifier>http://imsear.hellis.org/handle/123456789/588</dc:identifier>
            <dc:language>eng</dc:language>
            <dc:source>http://www.icddrb.org/pub/publication.jsp?classificationID=30&amp;typeClassificationID=2</dc:source>
            <dc:source>http://www.icddrb.org/uploads/originaluploads/jhpn251_Evaluation.pdf</dc:source>
          </oai_dc:dc>
        </metadata>
      </record>

**Comment by renatomurasaki** [comment]
@botturam please, use the same processing to generate these data files when the data set harvested follow DIM format.

**Comment by botturam** [comment]
Segue a tabulação de todos os campos disponíveis no formato DIM. Farei a atualização da planilha de mapeamento de campos:

<dim_field mdschema="dc" element="contributor" qualifier="advisor"
<dim_field mdschema="dc" element="contributor" qualifier="author"
<dim_field mdschema="dc" element="contributor" qualifier="editor"
<dim_field mdschema="dc" element="contributor" qualifier="illustrator"
<dim_field mdschema="dc" element="contributor" qualifier="other"
<dim_field mdschema="dc" element="date" qualifier="accessioned"
<dim_field mdschema="dc" element="date" qualifier="available"
<dim_field mdschema="dc" element="date" qualifier="created" 
<dim_field mdschema="dc" element="date" qualifier="issued"
<dim_field mdschema="dc" element="description" lang="en_US"
<dim_field mdschema="dc" element="description" qualifier="abstract"
<dim_field mdschema="dc" element="description" qualifier="affiliation"
<dim_field mdschema="dc" element="description" qualifier="provenance" 
<dim_field mdschema="dc" element="description" qualifier="sponsorship" 
<dim_field mdschema="dc" element="description" qualifier="tableofcontents" 
<dim_field mdschema="dc" element="format" qualifier="extent" 
<dim_field mdschema="dc" element="identifier" qualifier="citation"
<dim_field mdschema="dc" element="identifier" qualifier="issn"
<dim_field mdschema="dc" element="identifier" qualifier="uri"
<dim_field mdschema="dc" element="language" lang="en_US"
<dim_field mdschema="dc" element="language" qualifier="iso" 
<dim_field mdschema="dc" element="publisher"
<dim_field mdschema="dc" element="relation" qualifier="hasversion" 
<dim_field mdschema="dc" element="relation" qualifier="ispartofseries"
<dim_field mdschema="dc" element="relation" qualifier="uri" 
<dim_field mdschema="dc" element="rights" 
<dim_field mdschema="dc" element="rights" qualifier="uri" 
<dim_field mdschema="dc" element="source" lang="en_US"
<dim_field mdschema="dc" element="source" qualifier="uri"
<dim_field mdschema="dc" element="subject"
<dim_field mdschema="dc" element="subject" qualifier="ddc"
<dim_field mdschema="dc" element="subject" qualifier="lcsh"
<dim_field mdschema="dc" element="subject" qualifier="mesh"
<dim_field mdschema="dc" element="subject" qualifier="other"
<dim_field mdschema="dc" element="title"
<dim_field mdschema="dc" element="title" qualifier="alternative"
<dim_field mdschema="dc" element="type"

**Comment by botturam** [comment]
mapeamento concluído em:
 https://bir-fc.paho.org/TC/TC/Gerencias/AFI/OFI/GHL/GIM_data_dictionary_2017_shared.xlsx

Falta ajustar a XSL para que os campos sejam colocados nos tags corretos. Do modo como foi feito -- aproveitando a conversão da WHOLIS -- ficou incompleto e em alguns casos, tags errados, como o Descritor no lugar do Descritor Local.

**Comment by botturam** [comment]
CSVs de SEARO, com data raw, estão disponíveis em serverofi5:/bases/lilG4/gim.lil/searo_tab/

Foi criada uma nova planilha "lilacs_Afiliacao.txt" apenas com um campo de afiliação que provavelmente refere-se ao primeiro autor. Este campo não é repetitivo.

**Comment by renatomurasaki** [comment]
CSV OK.
