### ISSUE TITLE
consertar o shell da virada em basalto01

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#564]
apagar o arquivo de flag após ter exsecutado a "virada". O mesmo sheel em basalto02 está funcionado. 

Para logar, usar ssh transfer@basalto02 a partir de OFI5

atalho "indexes" -> /home/javaapps/iahx-server/indexes

analisar os shells virada1.sh e virada.sh

**Comment by ChicoLopes** [comment]
Realizado o pareamento das rotinas de atualização de índices iAHx entre basalto01 e basalto02, dependendo de ativação pelo ITI.

[Atualuzação Indices iAHx.docx](https://github.com/bireme/db-processing/files/6896592/Atualuzacao.Indices.iAHx.docx)

**Comment by botturam** [comment]
@ChicoLopes falei com o Marco sobre o conserto que vc fez. Por favor, entre em contato com ele para passar as orientações

**Comment by ChicoLopes** [comment]
Ok falarei com ele!

**Comment by ChicoLopes** [comment]
@botturam a “virada” é composta por um conjunto de rotinas que devem ser executadas na devida sequência. Tais ações principiam em serverofi5 ao término do processamento de cada índice de instância IAHx com a rotina endiaDados.new.sh (/bases/iahx/exec/enviaDados.new.sh), cujo argumento de chamada é a sigla de identificação da instância (portal; pmm; covidoms; etc.) e por uma coleção de possíveis opções de execução (-d; -H; -T; -x entre outras).
Este shell se guia pela tabela de configuração de processamento iAHx.tab composta de 36 colunas e se vale do conteúdo de algumas dessas colunas (1; 2; 4; 5; 6; 7; 8; 9; 10; 11; 19; 30; 31; e 36) para desempenhar sua função, que é transferir o conjunto de arquivos de índice da instância para o servidor de produção e eventualmente para um servidor par de balanceamento.
O processo se baseia em criar um diretório temporário no(s) servidor(es) destino, transferir para lá os arquivos do índice; por meio de um checksum MD5 garantir a correta transferência dos dados, renomear o diretório temporário de destino para sua denominação de aguardo por atualização (xxx.now para xxx.new), gerar um arquivo de permissão de atualização composto de três linhas de texto (data e hora dos dados; expressão de busca para efeito de teste; e resultado esperado) e finalizar o seu processo transferindo para o destino tal arquivo  de sinalização de permissão de atualização.
No servidor de produção (ou par de balanceamento), deve ser executado por agendamento a rotina de verificação de permissão de atualização, incluindo a própria função de atualização. O controle de tarefas agendadas (crontab) deve chamar o shell ReiniciaTodosIAHX.new.sh (nome inapropriado, sendo sugerido alterá-lo para VerAtualizaIAHX.sh), localizado em /home do servidor. Esta rotina chama a função efetiva de atualização de índices IAHx e ao seu retorno emite um e-mail de aviso de execução dos índices residentes no servidor.
A função de atualização é desempenhada por outro shell denominado atualizaIAHx.new.sh, localizado em /home/javaapps/iahx-server/bin. As tarefas sequenciais executadas por ele são: interromper a execução dos servidores Solr ativos; verificar a existência de arquivos de permissão de atualização (flags) e a cada um encontrado em /home/javaapps/iahx-server/indexes, efetuar a rotação de diretórios contendo o conjunto de arquivos no índice atualmente servido com o que contém o conjunto de arquivos do novo índice; disparar a execução do servidor Solr; efetuar uma busca segundo a expressão contida no arquivo de permissão de atualização comparando o resultado obtido com o esperado (também contido no arquivo de permissão); havendo divergência de valores os diretórios com os arquivos de índice são retornados à sua condição inicial e o servidor Solr é reiniciado e emitido um e-mail informando a ocorrência; para o caso de concordância de valores é emitido um e-mail de sinalização de atualização concluída; por fim o arquivo de permissão de atualização é apagado.
Para dar apoio à tarefa de atualização há um outro shell, denominado ReiniciaTodosIAHXsv.new.sh, localizado no diretório /home/javaapps/iahx-server/bin, que não efetua a rotação de diretórios de arquivos dos índices, no entanto para e reinicia todos os servidores Solr.
Estão assim envolvidos os seguintes shells:
Em serverofi5: enviaDados.new.sh
Em basalto01: ReiniciaTodosIAHX.new.sh e ReiniciaTodos IAHSXsv.sh
Em basalto02: ReiniciaTodosIAHX.new.sh e ReiniciaTodos IAHSXsv.sh
Estes cindo shells são objeto dos chamados 412; 564; 565 presentes no GitHub.
A atual situação é de rotinas criadas/alteradas/adaptadas e no aguardo por uma oportunidade para sua execução monitorizada para efeito de teste homologatório, uma vez que todos os testes estáticos possíveis foram realizados, observando que esta execução obrigatoriamente necessita de envolvimento ativo por parte do ITI, uma vez que OFI não tem os direitos de acesso necessários para a operação plena dos servidores de produção e par de balanceamento (basalto01 e basalto02).

**Comment by botturam** [comment]
como não faremos o sistema de balanceamento entre as Basaltos 01 e 02, vamos deixar a "virada" como está hoje. Caso precisemos de alguma otimização ou sofisticação, retomaremos o tema.
