### ISSUE TITLE
transferir índice Solr5-Portal para basalto01

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#565]
transferir o índice Solr5 através de enviaDados.sh, por parâmetro, eliminando o shell atual enviaDados_basalto01.sh

atalho exec -> /bases/iahx/exec
chamada de enviaDados.sh -> update-index.sh

**Comment by botturam** [comment]
db02dx=basalto01
bases=basalto02

**Comment by ChicoLopes** [comment]
@botturam a “virada” é composta por um conjunto de rotinas que devem ser executadas na devida sequência. Tais ações principiam em serverofi5 ao término do processamento de cada índice de instância IAHx com a rotina endiaDados.new.sh (/bases/iahx/exec/enviaDados.new.sh), cujo argumento de chamada é a sigla de identificação da instância (portal; pmm; covidoms; etc.) e por uma coleção de possíveis opções de execução (-d; -H; -T; -x entre outras).
Este shell se guia pela tabela de configuração de processamento iAHx.tab composta de 36 colunas e se vale do conteúdo de algumas dessas colunas (1; 2; 4; 5; 6; 7; 8; 9; 10; 11; 19; 30; 31; e 36) para desempenhar sua função, que é transferir o conjunto de arquivos de índice da instância para o servidor de produção e eventualmente para um servidor par de balanceamento.
O processo se baseia em criar um diretório temporário no(s) servidor(es) destino, transferir para lá os arquivos do índice; por meio de um checksum MD5 garantir a correta transferência dos dados, renomear o diretório temporário de destino para sua denominação de aguardo por atualização (xxx.now para xxx.new), gerar um arquivo de permissão de atualização composto de três linhas de texto (data e hora dos dados; expressão de busca para efeito de teste; e resultado esperado) e finalizar o seu processo transferindo para o destino tal arquivo  de sinalização de permissão de atualização.
No servidor de produção (ou par de balanceamento), deve ser executado por agendamento a rotina de verificação de permissão de atualização, incluindo a própria função de atualização. O controle de tarefas agendadas (crontab) deve chamar o shell ReiniciaTodosIAHX.new.sh (nome inapropriado, sendo sugerido alterá-lo para VerAtualizaIAHX.sh), localizado em /home do servidor. Esta rotina chama a função efetiva de atualização de índices IAHx e ao seu retorno emite um e-mail de aviso de execução dos índices residentes no servidor.
A função de atualização é desempenhada por outro shell denominado atualizaIAHx.new.sh, localizado em /home/javaapps/iahx-server/bin. As tarefas sequenciais executadas por ele são: interromper a execução dos servidores Solr ativos; verificar a existência de arquivos de permissão de atualização (flags) e a cada um encontrado em /home/javaapps/iahx-server/indexes, efetuar a rotação de diretórios contendo o conjunto de arquivos no índice atualmente servido com o que contém o conjunto de arquivos do novo índice; disparar a execução do servidor Solr; efetuar uma busca segundo a expressão contida no arquivo de permissão de atualização comparando o resultado obtido com o esperado (também contido no arquivo de permissão); havendo divergência de valores os diretórios com os arquivos de índice são retornados à sua condição inicial e o servidor Solr é reiniciado e emitido um e-mail informando a ocorrência; para o caso de concordância de valores é emitido um e-mail de sinalização de atualização concluída; por fim o arquivo de permissão de atualização é apagado.
Para dar apoio à tarefa de atualização há um outro shell, denominado ReiniciaTodosIAHXsv.new.sh, localizado no diretório /home/javaapps/iahx-server/bin, que não efetua a rotação de diretórios de arquivos dos índices, no entanto para e reinicia todos os servidores Solr.
Estão assim envolvidos os seguintes shells:
Em serverofi5: enviaDados.new.sh
Em basalto01: ReiniciaTodosIAHX.new.sh e ReiniciaTodos IAHSXsv.sh
Em basalto02: ReiniciaTodosIAHX.new.sh e ReiniciaTodos IAHSXsv.sh
Estes cindo shells são objeto dos chamados 412; 564; 565 presentes no GitHub.
A atual situação é de rotinas criadas/alteradas/adaptadas e no aguardo por uma oportunidade para sua execução monitorizada para efeito de teste homologatório, uma vez que todos os testes estáticos possíveis foram realizados, observando que esta execução obrigatoriamente necessita de envolvimento ativo por parte do ITI, uma vez que OFI não tem os direitos de acesso necessários para a operação plena dos servidores de produção e par de balanceamento (basalto01 e basalto02).

**Comment by ChicoLopes** [comment]
@botturam de primeira, penso em trocar apenas a rotina de envio de dados aos servidores de produção, a gente observa se tem efeitos inesperados nos processamentos em geral. Claro não é para ter efeitos colaterais.
O que espero que aconteça? Espero que tudo funcione como hoje, com a mudança de que ao enviar os dados estará acontecendo o cálculo de MD5 dos dados de serverofi5 que estão sendo enviados. Ao término tanto do cálculo quanto do envio, o arquivo MD5 (máscara do nome r<$IDIDX>.md5) é enviado para o diretório main da instância no servidor de produção e de serverofi5 é disparado em background o cálculo (na verdade conferência) remoto do MD5 que ao acabar gera em serverofi5 um arquivo flag indicando que está pronto. Neste momento em serverofi5 conclui como de costume a transferência e gera o arquivo flag de atualização (vira.<$IDIDX>.flg) com as três linhas de sempre e a vida segue.
Para o caso PORTAL o envio passa a ser para os dois servidores (eu chamei no shell de $DESTINO, este é o de sempre, e $BALANCEPAIR, que é o duplo para operar com balanceamento de carga)  partir do próprio envia dados, tratando a operação de verificação de MD5 simultânea em background nos remotos.
Essa alteração não causando inconvenientes iremos ao passo seguinte, que será mudar nos servidores de produção as rotinas de atualização.
Enquanto está em teste eu pego o Marco e verifico com ele como a coisa vai funcionar nos servidores de produção e combino com ele como fazer a mudança das rotinas
Ok? Podemos fazer dessa forma?
Ações imediatas já realizadas:
1- troca de nome de enviaDados.sh para enviaDados.ate20210929.sh
2- troca de nome de enviaDados.new.sh para enviaDados.sh (que passa a operar)
3- troca de nome da biblioteca iAHx2.inc para iAHx2.original.inc
4- troca de nome da biblioteca iAHx2a.inc para iAHx2.inc
5- para de utilizar a tabela iAHx.tab para usar iAHx.tab.futura
Uma vez tudo estabilizado e aprovado as ações serão:
1- remoção para outro diretório (no_use) das variantes de enviaDados
2- remoção para outro diretório (no_use) de iAHx2.original.inc
3- edição de iAHx2.inc para utilizar a tabela iAHx.tab (linha 6)
4- remoção para outro diretório (no_use) da tabela iAHx.Tab
5- renomeação da tabela iAHx.tab.futura para iAHx.tab
Desta forma a porção de serverofi5 estará concluída e estabilizada.

**Comment by ChicoLopes** [comment]
@botturam na primeira execução de enviaDados versão4.00, a referência à biblioteca de funções foi para produção com o “nome da biblioteca de teste” o que causou um erro “fatal” e não executou a transferência dos dados (realizada assincronamente depois). Estava chamando iAHx2a.inc, mas foi corrigido de pronto para iAHx2.inc.
Nas próximas execuções não monitoradas em detalhe, só posteriormente analisadas, observa-se que na geração do registro de tempo de conferência, que não tem repercussão operacional nas instâncias, não estava sendo gerado o relato do tempo de conferência da massa de dados, muito embora a conferência estivesse ocorrendo como devido. Para sanar esta deficiência, imediatamente antes de solicitar a verificação remota do checksum MD5 no servidor de produção (referido como $DESTINO no shell) é anotado o momento de envio da solicitação nas variáveis TINICH e TINICS. Posteriormente, ao receber a confirmação de execução (com ou sem sucesso na conferência), do servidor de produção e quando devido do servidor par de balanceamento (referido como $BALANCE no shell), é anotado o momento tomado como término nas variáveis TFIMCH e TFIMCS, para então proceder ao cálculo e registro de tempo de conferência na saída de log da execução.

**Comment by ChicoLopes** [comment]
@botturam como o desempenho foi satisfatório durante o período de observação usando pmm como objeto de teste, hoje o portal será transferido para basalto02 e basalto01. Para tanto foram feitas as seguintes alterações:
1- Efetuada cópia de segurança da versão corrente da tabela iAHx.tab (iAHx.tab.20211008)
2- Edição da tabela iAHx.tab, normalizando os servidores de produção para sua denominação atual (basalto01.bireme.br e basalto02.bireme.br)
3- Adicionado basalto01.bireme.br à coluna 19 da tabela para o processamento de portal (matido basalto02.bifreme.br na mesma coluna de pmm)
4- Complementando a açã 5 do comentário de 29 de setembro alterado o uso para a tabela iAHx.tab (iAHx.tab.futura deixa de ser necessária e pode ser apagada)
5- Eliminado arquivo iAHx2a.inc (todas as alterações ali testadas foram incorporadas a iAHx2.inc presentemente nas versão 2.10)

**Comment by ChicoLopes** [comment]
@botturam foram tomados os logs de processamento do ano de 2021 (4/jan./2021 até 12/out./2021) e extraído deles o tempo total de processamento do portal.
A massa de dados foi dividida em três épocas a saber:
1ª Processamento com envio de dados para basalto02 e basalto01 em shell-scripts separados;
2ª Processamento com envio de dados para basalto02 e basalto01 em shell-script único vrs 1;
3ª Processamento com envio de dados para basalto02 e basalto01 em shell-script único vrs final.

As transferências de portal para os dois servidores está funcional e hoje o processamento demorou no total 21h e 45min.
Anexo um documento em Word (docx) que mostra as evoluções de tempo de processamento.
[enviaDadosAvaliacao.docx](https://github.com/bireme/db-processing/files/7341349/enviaDadosAvaliacao.docx)

**Comment by ChicoLopes** [comment]
@botturam período de teste e ajustes já demonstrou a correção do procedimento.
