### ISSUE TITLE
Os 681 registros WHO COVID-19 de 26/07/2021 entraram na interface de busca

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#568]
Pergunta por conta das mensagens enviadas pela equipe da OMS

=======
26/07/2021:

Hi again,

Should I re-date the citations from this file with tomorrow's date and then send them with tomorrow's batch?

=======

On Monday, July 26, 2021, 01:55:55 PM EDT XXXXXXXXXX wrote:

Hi Renato, Heitor & Marcelo,

Can the file for today be harvested late? 

I just put the file in the DropBox now.  There was a miscommunication between me and Tini about who was putting the file there today.  My apologies.

There were 681 new citations.

**Comment by renatomurasaki** [comment]
De acordo com a equipe da OMS, estes registros entraram em 27/07/2021, com esta nova data. Por esta razão não aparecem com data de 26/07.

**Comment by botturam** [comment]
foi pelo mesmo motivo que as citações de 02/06/2021 desapareceram. Elas tiveram suas datas alteradas e enviadas novamente em alguma data posterior.
