### ISSUE TITLE
Generate CSV files for WHOLIS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#57]

**Comment by botturam** [comment]
CSVs disponíveis em serverofi5:/bases/lilG4/gim.lil/wholis_tab

**Comment by renatomurasaki** [comment]
CSV files are ok.

**Comment by botturam** [comment]
É necessária uma revisão nos CSVs, de forma que mostre apenas raw data. Está sendo feito, mas não concluído.
