### ISSUE TITLE
Corrigir índice iAHx pais_afiliacao

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#572]
O índice está incluindo as chaves de pesquisa no seguinte formato:

"^iAlbania^eAlbania^pAlbânia^fAlbanie"

Deveria explodir todos os idiomas individualmente, correto?

**Comment by botturam** [comment]
Esse campo se apresenta no XML desta maneira mesmo.

<field name="pais_afiliacao">^iChina^eChina^pChina^fChine</field>

Que eu me lembre, era para não perder a paridade com o Autor. O Vinícius pediu para deixar o dado assim nos XMLs, há muitos anos. Preciso ver com ele sobre isso.

@viniciusandrade vc lembra desse campo nos XMLs em geral?

**Comment by viniciusandrade** [comment]
Este é o formato correto quando é preciso mostrar um campo com tradução ... neste caso o índice pais_afiliacao é mostrado como cluster na interface.

**Comment by botturam** [comment]
não há o que mudar.
