### ISSUE TITLE
Alterar processamento da informação semântica do WHO COVID-19 para evitar duplicação dos elementos XML

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#575]
Identificada a duplicação dos elementos semânticos no XML iAHx do WHO COVID-19

![image](https://user-images.githubusercontent.com/1226218/128026760-4f76429f-ded7-488c-94af-3714f89b7d32.png)

**Comment by botturam** [comment]
foi resolvido pelo Heitor:

https://github.com/bireme/AddPredicates/issues/4#issuecomment-894489858
