### ISSUE TITLE
criar um procedimento para verificação da integridade de um XML qualquer

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#577]
criar um shell script que receba de entrada um XML qualquer e pare o processamento no ponto do processamento onde ele checou, além de mandar e-mail para a lista ofi - appofi@bireme.org

**Comment by ChicoLopes** [comment]
@botturam  criado o shell “verificaXML.sh” com a sintaxe: _verificaXML.sh [-h|-V|-changelog] <PARM1>_, que efetua a verificação de formação do XML e saí com código 1 em caso de má formação e código 2 em caso de problemas na chamada (arquivo inexistente ou vazio). Gravei o shell em **$PATH_EXEC**, para que possa ser chamado como componente do $PATH do usuário operação de serverofi5.
Achei um ponto de inserção do teste no shell _iah_xml_fi.sh_ que está no diretório _/bases/lilGe/tpl.lil_, e inseri a chamada como comentário **entre as linhas 1303 e 1307**, no entanto você precisa validar se esse local é satisfatório.
Utiliza o ‘xmlwf’ do pacote ‘expat’ mesmo, para fazer melhor deve ser instalado o pacote ‘xmlstarlet’, não fiz a instalação do mesmo porque o Ubuntu da máquina é versão 12.04 e como é muito antigo, melhor fazer com supervisão à miúde do ITI. Este pacote, permitirá mostrar a linha com erro até o ponto do erro no stderr, o que seria bem mais útil.
Agora é necessário que acertemos uma forma de validar isso para colocar em produção, e inclui-lo de alguma forma em rotina de backup caso necessário

**Comment by botturam** [comment]
@chico não está mandando o -e-mail. Deveria chegar um e-mail com o subject abaixo, certo?

SUBJECT="ERRO de formação no XML ${PARM1} em ${HOSTNAME}"

**Comment by ChicoLopes** [comment]
@botturam para efetuar o teste de envio de e-mail em caso de erro do shell verificaXML_02,sh com o diretório /bases/iahx corrente efetuei a chamada: 'verificaXML_02.sh xml-inbox/covidwho_teste/mdl_covidwho_2021.xml' (um XML sabidamente com erro) e ocorram tanto a sinalização de erro quanto o envio de e-mail. Obs. efetuei o mesmo teste com o shell verificaXML.sh que também funcionou devidamente, no entanto com tempo de execução bastante maior.

**Comment by botturam** [comment]
@ChicoLopes legal. Estou recebendo os e-mails.

**Comment by ChicoLopes** [comment]
@botturam  verificando o erro do processamento da BVS-PMM, estranhei que a rotina de verificação de XMl reclamou de não ter achado o arquivo lil_pmm.xml em /bases/iahx/proc/pmm/main/xml.index/, só que o arquivo está lá.
Assim incluí no shell verificaXML_02.sh o envio de e-mail para mais três condições de erro:
1- não passar o arquivo a ser testado na chamada do shell
2- não encontrar o arquivo indicado (foi o que sinalizou erro)
3- arquivo indicado vazio
e também um 'ls -l' do arquivo a ser verificado imediatamente antes do xmlstarlet para poder "arredadar" dados para análise de falhas.

**Comment by botturam** [comment]
@ChicoLopes show! melhor ainda com mais essas verificações. Fiz um teste e deu certo. Vou aguardar até amanhã para encerrar.

**Comment by botturam** [comment]
@ChicoLopes sugiro mais uma funcionalidade, qual seja, deletar a linha em que ocorreu um erro. 

A execução inicial de verificaXML_02.sh indica a linha com problema. Em seguida, o próprio shell poderia eliminar a linha, enviando por e-mail o que foi eliminado. Assim o processamento não para.

No mais, está funcionando perfeitamente.

**Comment by ChicoLopes** [comment]
@botturam uma nova versão do shell de verificação de XML foi implementada e aguarda teste e aprovação para entrar em produção. Por enquanto o nome do shell é 'verificaXML_ng.sh' (nova geração) e se aprovado será renomeado para 'verificaXML_02.sh' para evitar alteração dos pontos de uso do mesmo.
Agora ele aceita as seguintes opções de chamada:
-h ou --help; -V ou --version; --changelog; -d N ou --debug N e a nova opção -x N ou --fix N
A opção -x ou --fix ativa as tentativas de correção do arquivo em teste, ela que deve ser o ultimo elemento da linha quando usada. A clausula N pode ser omitida (e por isso deve ser o último da linha) assumindo o default que é de 4 tentativas.
Está gravado em $PATH_EXEC dispensando caminho para chamada, por emeplo:
verificaXML_ng.sh arquivo.xml -x
verificaXML_ng.sh arquivo.xml -x 5
verificaXML_ng.sh arquivo.xml --fix
verificaXML_ng.sh arquivo.xml --fix 10

**Comment by botturam** [comment]
1) versão final ficou **verificaXML_02.sh arquivo.xml --fix 10**  (default=4)

2) coloquei o check apenas em shs.lil/rodaCOVIDWHO.sh  (20 tentativas)

echo "- verifica e conserta cvd_regional.xml ..."
TPR="iffatal"
MSG="Erro: verificaXML_02.sh cvd_regional.xml --fix 20"
verificaXML_02.sh /bases/iahx/xml-inbox/covidwho/cvd_regional.xml --fix 20
. log
