### ISSUE TITLE
Adotar procedimentos de atualização do índice de similares baseando-se no processo de atualização do iAHx

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#58]

**Comment by renatomurasaki** [comment]
@heitorbarbieri @santosfj  já está em produção os procedimentos de atualização do índice de similares de acordo com os procedimentos do iAHx?

**Comment by renatomurasaki** [comment]
@heitorbarbieri @santosfj podemos encerrar este issue, tendo em vista as últimas ações que vocês tiveram com o ITI?

**Comment by heitorbarbieri** [comment]
O processo já está em produção e sua execução funciona de acordo com o esperado, ie, está OK.
