### ISSUE TITLE
inserir nova rotina de check de integridade em INBOX/covidwho - proc. covidoms

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#582]
inserir a nova rotina de check de integridade --  verificaXML.sh [-h|-V|-changelog]  -- no "0-process.sh" (ou outro melhor lugar) dos processamentos abaixo:

1) /bases/iahx/proc/covid**who**/main
2) /bases/iahx/proc/covid**oms**/main

deverão verificar os XMLs de: /bases/iahx/xml-inbox/covidwho

A ideia é não deixar que os processamentos iniciem, caso algum XML não esteja bom. Atualmente, os XMLs com problemas de formação estão sendo descartados do processamento, o que não pode acontecer.

**Comment by botturam** [comment]
@ChicoLopes imaginei fazer uma chamada como a que está abaixo dentro de /bases/iahx/proc/covidoms/main/0-process.sh 

verificaXML.sh [PARMS]
RSP=$?; [ "$NOERRO" = "1" ] && RSP=0
source checkerror $RSP "Problem XML INBOX"

**Comment by ChicoLopes** [comment]
@botturam verificação de qualidade do XML usando o shell verificaXML_02.sh (este usa o xmlstrlet que aponta o local com erro), foi inserido em 0-process-inbox.sh que é rotina comum a todos os processamentos, em um ponto onde só não são testados os XML referentes ao portal. Mas a inserção da verificação já está prevista e basta descomentá-la, entre as linhas 211 e 219 do shell, sinalizadas com as marcas [:ini:] e [:fim:]. Avaliei também o tempo de execução da verificação nos arquivos mdl21_regional de 7G7 bytes e lil_regional.xml de 8G1 bytes que foi de menos de 4 minutos (máximo de 3 min e 55 seg) para cada um deles.

**Comment by botturam** [comment]
@ChicoLopes deu erro no processamento de 6f do COVIDOMS (SolR 3). Eu comentei a execução para seguir em frente. Vc poderia dar uma olhada no que aconteceu? Existe um arquivo de log no diretório "logs".

**Comment by ChicoLopes** [comment]
@botturam 'mea culpa' faltou na chamada do verificaXML_02.sh colocar o nome do arquivo a ser verificado ($FILE_NAM) após o caminho ($PWD/xml.index) do arquivo a verificar (forma final 'verificaXML_02.sh $PWD/xml.index/$FILE_NAM'). Está corrigida a falha no código.

**Comment by botturam** [comment]
@ChicoLopes  Agora está funcionando. Entretanto o shell ainda não está enviando o e-mail. Deveria chegar um com o subject abaixo:

SUBJECT="ERRO de formação no XML ${PARM1} em ${HOSTNAME}"

ver #577

**Comment by botturam** [comment]
Está em funcionamento, atualmente após MarkAbstract, em 0-process-inbox.sh
