### ISSUE TITLE
coletar nova FI CNS-BR (Conselho Nacional de Saúde na BVS Brasi) para IAHx-Brasil

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#586]
Dados da FI CNS-BR (Conselho Nacional de Saúde na BVS Brasi) para IAHx-Brasil

base de dados do Conselho Nacional de Saúde na BVS Brasi
Informação constante no FI-Admin: Sigla: CNS-BR 

Labels IAHx-Brasil (Mori)
PT: CNS - Conselho Nacional de Saúde do Brasil 
ES: CNS - Consejo Nacional de Salud de Brasil 
EN: CNS - Brazilian National Health Council 

ID da base: 69 - https://fi-admin.bvsalud.org/admin/database/database/69/ 
CC responsável: BR878 
Hoje a base conta com 720 registros publicados, mas em breve contará com mais de 1000 considerando registros em status rascunho.

**Comment by botturam** [comment]
Passos:

1) coletar do FI-Admin para /bases/fiadmin/databases/cns-br
/bases/fiadmin/consolida/tpl/filtraDBs.sh "CNS-BR"

depois, incluir no rodaFILTROS.sh

2) gerar linha de proc. da FI em questão (cns)  
    - /bases/lilG4/tabs/coletas.tab
    - /bases/lilG4/tabs/coletasXML-IAHx.tab

*3) configurar arquivos tabs/instance.pft, /tabs/db.pft, collection.pft  (Marcelo)
    
4) criar /bases/lilG4/shs.lil/_cns_br.sh, com as chamadas etapas do proc., simulando o Celery

5) cadastrar no Celery as chamadas parciais de /bases/lilG4/shs.lil/_cns_br.sh

**Comment by ChicoLopes** [comment]
@botturam cadastramento no Celery realizado, por favor verificar se não há falhas na operação de configuraçã e cadastramento

**Comment by botturam** [comment]
Deu certo. Processamento diário cadastrado no Celery
