### ISSUE TITLE
WPRIM - processamento regular quadrimestral

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#588]
@ChicoLopes favor encaminhar a atualização da WPRIM:

segue a documentação da WPRIM:

https://wiki.bireme.org/intranet/index.php/WPRIM_WPRO_vers2

ou na página do OFI buscar por WPRIM

**Comment by ChicoLopes** [comment]
@botturam processamento WPRIM executado sem detecção de erros, gerando 799977 registros em base de dados e documentos em XML.

**Comment by botturam** [comment]
@ChicoLopes não estou encontrando docs de /bases/oai.pmh/xml.rec/XMLs_WPRIM_nao_apagar/tmp_ftp/ftp_20210420/ e ftp_20210810/ em   wpr_regional.xml

Ex 1) operacao@serverofi5:/bases/oai.pmh/xml.rec/XMLs_WPRIM_nao_apagar/tmp_ftp/ftp_20210420/2021-04-20 $ grep "diagnostic value of monocyte to high density lipoprotein ratio" WPRIM2021-04-20-1618884588414-4.xml
      <![CDATA[The diagnostic value of monocyte to high density lipoprotein ratio and lipoprotein-associated phospholipase A2 in diabetic foot]]>

grep "diagnostic value of monocyte to high density lipoprotein ratio" wpr_regional.xml

Ex 2) operacao@serverofi5:/bases/oai.pmh/xml.rec/XMLs_WPRIM_nao_apagar/tmp_ftp/ftp_20210420/2021-04-20 $ grep "effect of water extract of danshen on degeneration of osteoarticula" WPRIM2021-04-20-1618884588414-3.xml_tmp
    <ArticleTitle><![CDATA[Preventive effect of water extract of danshen on degeneration of osteoarticular cartilage induced by monosodium iodocaetate in rats]]></ArticleTitle>

operacao@serverofi5:/bases/iahx/xml-inbox/regional $ grep "effect of water extract of danshen on degeneration of osteoarticula" wpr_regional.xml


Pode dar uma olhada?

**Comment by ChicoLopes** [comment]
@botturam o processamento Celery, processos pos_coleta_oai e pre_saneamento ocorreram a partir das 2h30 de 13/08/2021, mas iah_like_lilacs está até o momento com status "STARTED". A base /bases/lilG4/wpr.lil/lilacs agora conta com 847866 registros sendo que todos os três exemplos apontados agora integram o conjunto de dados.
Efetuei correções no documento contido na wiki para refletir a atual realidade de execução do processamento e anexo o arquivo docx e pdf a este comentário.
[WPRIM_WPRO_vrs2.1.pdf](https://github.com/bireme/db-processing/files/6984121/WPRIM_WPRO_vrs2.1.pdf)
[WPRIM WPRO vrs2.docx](https://github.com/bireme/db-processing/files/6984124/WPRIM.WPRO.vrs2.docx)

**Comment by renatomurasaki** [comment]
@ChicoLopes apaguei as referências aos arquivos que você anexou no comentário anterior, por conterem dados de usuário e senha

**Comment by renatomurasaki** [comment]
@ChicoLopes por favor, repasse os arquivos para o @botturam acrescentar no sharepoint da BIREME ou edite os arquivos para retirar os dados de autenticação.

**Comment by ChicoLopes** [comment]
@botturam processamento concluído sem indicações de erro em log e os documentos apontados estão presente no arquivo XML

**Comment by botturam** [comment]
concluído.
