### ISSUE TITLE
Atualização do item Revisao Sistemática - Cluster Tipo de estudo

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#59]
Processamento na instância: http://pesquisa.bvsalud.org/portal e todas que replicam este cluster
 type_of_study:("systematic_reviews")

Atualmente somente uma estratégia de busca é utilizada para Medline e Lilacs, na atualização deverá ser processada uma estratégia para MEDLINE e uma para demais bases (lilacs like) conforme anexo.
Não registrado no Repositório de Estratégias por ainda estarem no padrão iAH (causa erro no resultado de busca do Repositório)
Obrigada
Rose

[Revisao Sistematica.txt](https://github.com/bireme/db-processing/files/1181291/Revisao.Sistematica.txt)

**Comment by pintoros** [comment]
Considerar a estratégia abaixo para LILACS LIKE

((((TI revis$ AND TI sistemati$) OR (TI systemati$ AND TI reviw$)) OR (((AB revis$ AND AB sistemati$) OR (AB systemati$ AND AB reviw$)) AND MH revisao)) AND NOT ((PT carta OR PT Artigo de Jornal OR PT Comentario) OR (MH animais OR MH coelhos OR MH ratos OR MH camundongos OR MH primatas OR MH caes OR MH gatos OR MH suinos OR PT in vitro)))
Obrigada

**Comment by botturam** [comment]
Feito para todas as FIs. MEDLINE, apenas ano corrente.

Favor conferir na 2f cedo, em produção.

**Comment by botturam** [comment]
Problemas na infraestrutura impediram a atualização no dia de hoje. É necessário verificar com o ITI quando a situação se normalizará. Até o momento, sem previsão de atualização.

**Comment by botturam** [comment]
De minha parte, está concluído.

**Comment by pintoros** [comment]
Resultado OK na produção do Portal Regional.

Obrigada
