### ISSUE TITLE
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema1: Complications during labor and delivery

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#591]
[Complications during labor and delivery.txt](https://github.com/bireme/db-processing/files/6978580/Complications.during.labor.and.delivery.txt)

**Comment by botturam** [comment]
@pintoros vi que vc sairá (ou saiu) de férias. Vc poderia encaminhar a questão de tradução dos 5 temas do contexto "Mortalidade materna" para alguém? 

-rw-rw-r-- 1 operacao operacao 2026 Aug 13 14:11 5_ODS3_mortalidade_materna-5_abortion.sch
-rw-rw-r-- 1 operacao operacao 4414 Aug 13 14:10 5_ODS3_mortalidade_materna-5_Complications_during_labor_delivery.sch
-rw-rw-r-- 1 operacao operacao 2266 Aug 13 14:12 5_ODS3_mortalidade_materna-5_haemorrhage.sch
-rw-rw-r-- 1 operacao operacao 2284 Aug 13 14:13 5_ODS3_mortalidade_materna-5_hypertensive_disorders.sch
-rw-rw-r-- 1 operacao operacao 4137 Aug 13 14:13 5_ODS3_mortalidade_materna-5_infections.sch

**Comment by renatomurasaki** [comment]
@veronicaabdala poderia nos apoiar nesta tradução?

**Comment by botturam** [comment]
seguem os 5 temas do contexto ODS3-Reduzir mortalidade materna:

ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema1: Complications during labor and delivery 
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema2: Abortion policy makers temas_salud
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema3: Haemorrhage policy makers temas_salud
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema4: Hypertensive disorders policy makers temas_salud
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema5: Infections policy makers temas_salud

**Comment by botturam** [comment]
está coletando muito pouco através do tpl/coletaIDs.sh, apesar de estar apontando para o Portal Regional. Lá, o resultado da expressão abaixo é de 2.491.587 docs

pelo ColetaIDs.sh (OFI5):

 Tema da pesquisa: 5_ODS3_mortalidade_materna-5_abortion - Total de registros: 2.675 (muito baixo). A parte final em negrito é que não funciona.

 Pesquisa por:  ((((("indice de mortalidad" OR "taxa de mortalidade" OR "mortality rate" OR "death rate" OR "indices de mortalidad" OR "taxas de mortalidade" OR "mortality rates" OR "death rates" OR death* OR obito* OR mortali* OR morte* OR muerte* OR mh:mortality OR mh:"mortalidade prematura" OR sh:mortalidade OR "mortalidade prematura" OR "mortalidad prematura" OR "premature mortality" OR "mortalidade precoce" OR "mortalidad precoz" OR "early death" OR "muerte prematura" OR "muerte precoz" OR "muerte temprana" OR "morte precoce" OR fallecid* OR fallecimiento* OR falecid* OR faleciment* OR dye OR dying) OR (mh:"Maternal Mortality" OR "mortalidade materna" OR "mortalidad materna" OR "Maternal Mortality" OR "maternal deaths" OR "Maternal death" OR "Mortalities Maternal"))  OR ((ti:reduct* ti:(death* OR mortali*)) OR "reduce deaths" OR "reducir las muertes" OR "reduccion de las muertes" OR "reduzir as mortes" OR "reducao das mortes") **AND NOT mj:G04.146.954.035***))) AND ( (instance:"regional") OR (instance:"ghl") )

Idem para as outras 4 estratégias desse contexto.

**Comment by botturam** [comment]
@viniciusandrade pode me ajudar?

aplicando a estratégia abaixo, em 2 ambiente, dá resultados muito diferentes. O problema está no final da pesquisa. Será que tem a ver com a atualização do DeCS?

("indice de mortalidad" OR "taxa de mortalidade" OR "mortality rate" OR "death rate" OR "indices de mortalidad" OR "taxas de mortalidade" **AND NOT mj:G04.146.954.035***)

1. IAHx-Portal (via browser, na interface IAHx)  -  724.528 docs
2. bases.bireme.br:8986/solr5/admin.html#/portal/query (via interface de administração)  -  66.039 docs

será que tem a ver com a atualização do DeCS?

**Comment by viniciusandrade** [comment]
A diferença é por que somente no IAHx-Portal é feito o tratamento do **AND NOT** por questão de compatibilidade com o ISIS. 

Para pesquisar diretamente na interface de administração Solr é preciso trocar o **AND NOT** por somente **NOT**

**Comment by botturam** [comment]
aparentemente deu certo tratar o "AND NOT" como "NOT" apenas. Vou seguir com os processamentos.

**Comment by botturam** [comment]
@viniciusandrade finalizei o processamento de ontem com algumas FIs já com os campos do contexto 5 (tag_contexto  e  tag_tema_saude). Já estão em produção:

- Sec. Est. Saúde SP (104)          (db:"SES-SP" and tag_contexto:"5_ODS3_mortalidade_materna")
- Coleciona SUS (101)                (db:"colecionaSUS" and tag_contexto:"5_ODS3_mortalidade_materna") 
- Sec. Munic. Saúde SP (60)       (db:"SMS-SP" and tag_contexto:"5_ODS3_mortalidade_materna")  

Amanhã estarão MEDLINE-ano-corrente , LILACS e demais Like-LILACS

**Comment by viniciusandrade** [comment]
@botturam ok,  você sabe onde estão as traduções para os temas referentes a este contexto para que eu possa abrir um issue para o Mori adicionar nos arquivos de tradução?

**Comment by botturam** [comment]
@renatomurasaki vc teve alguma resposta da Verônica sobre a tradução para os 4 idomas dos labels abaixo?

ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema1: Complications during labor and delivery
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema2: Abortion
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema3: Haemorrhage
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema4: Hypertensive disorders
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema5: Infections

**Comment by botturam** [comment]
@viniciusandrade venho irformar onde deverão ser registradas as traduções.

as traduções para os 4 idiomas, dos 5 temas de Mortalidade Materna, deverão estar no link abaixo que, posteriormente, irão para o Mori.

https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/Processamento/evideasy/traducao-labels-police-makers_TD4.CORRIGIDO-mori.xlsx?d=wce9c0454fe2641718101244492a176c4&csf=1&web=1&e=2vwzXw

**Comment by botturam** [comment]
@viniciusandrade  as traduções já estão na planilha. A Verônica enviou por e-mail e eu passei para o documento no sharepoint.
Informar ao Mori que, na coluna 1, coloquei o nome lógico dos temas.

https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/Processamento/evideasy/traducao-labels-police-makers_TD4.CORRIGIDO-mori.xlsx?d=wce9c0454fe2641718101244492a176c4&csf=1&web=1&e=2vwzXw

**Comment by botturam** [comment]
@viniciusandrade  o Marco acabou de atualizar o IAHx-Portal. LILACS e like-LILACS já estão disponíveis; MEDLINE tentarei até amanhã cedo.

**Comment by botturam** [comment]
MEDLINE disponível também.

**Comment by veronicaabdala** [comment]
Olá todos, eu estou revisando estas estratégias de busca, acabei de enviar via GitHub a estratégia corrigida para a meta3.1 tema 2 abortion. 

Por favor informar se estou fazendo da forma indicada.

Obrigada 

Enviado do meu iPhone

**Comment by veronicaabdala** [comment]
Refiz a busca para o tema1 Complications during labour and delivery:

((Reduc* OR reduzir OR reduct* OR reducci* OR mitiga* OR detener OR detencion OR diminuir OR diminuicao OR diminut* OR disminucion OR disminuir OR evitar OR evitable* OR evitave* OR declin* OR prevencion OR prevention OR prevencao OR preventiv* OR decrease OR decresce* OR ti:end OR combat* OR acabar OR terminar OR control* OR erradica* OR elimina* OR eradica* OR mitiga* OR baixar OR bajar OR sh:"prevencao e controle" OR "servicos preventivos" OR "servicios preventivos" OR "preventive services" OR mh:"Prevention and Mitigation" OR "Prevention and Mitigation" OR "Prevencion y Mitigacion" OR "Prevencao e Mitigacao" OR mh:H02.403.720.750* OR mh:N02.421.726*) AND ((("indice de mortalidad" OR "taxa de mortalidade" OR "mortality rate" OR "death rate" OR "indices de mortalidad" OR "taxas de mortalidade" OR "mortality rates" OR "death rates" OR death* OR obito* OR mortali* OR morte* OR muerte* OR mh:mortality OR mh:"mortalidade prematura" OR sh:mortalidade OR "mortalidade prematura" OR "mortalidad prematura" OR "premature mortality" OR "mortalidade precoce" OR "mortalidad precoz" OR "early death" OR "muerte prematura" OR "muerte precoz" OR "muerte temprana" OR "morte precoce" OR fallecid* OR fallecimiento* OR falecid* OR faleciment* OR dye OR dying OR "Near Miss") AND (TI:materna OR TI:maternal)) OR ("Maternal Mortality" OR "mortalidade materna" OR "mortalidad materna" OR "Maternal Mortality" OR "maternal deaths" OR "Maternal death" OR "Mortalities Maternal" OR "Maternal Near Miss")) AND (MH:C13.703* OR "Complicações do Trabalho de Parto" OR "Delivery complications" OR "Delivery complication" OR "labor complications" OR "labor complication" OR "obstructed labor" OR "labour complications" OR "labour complication" OR "obstructed labour" OR "uterine rupture" OR "ruptura uterina" OR "Ruptura Prematura de Membranas Fetais" OR "preterm premature rupture of membranes" OR "Premature Rupture of Fetal Membranes" OR ("Membrane Premature Rupture" AND (fetal OR pregna*)) OR macrosomia OR "macrossomia fetal" OR partograph OR "Third Labor Stage" OR "third stage of labour" OR "third stage of labor" OR "Extração Obstétrica" OR "instrumental delivery" OR "Obstetric Extraction" OR "Obstetrical Extraction" OR "obstetric trauma" OR Eclamps* OR "Hemorragia Pós-Parto" OR "Postpartum Hemorrhage" OR "Hemorragia Posparto" OR "Multiple pregnancy" OR "gravidez múltipla" OR "embarazo múltiple" OR "Fetal malpresentation" OR "Prelabour rupture of membranes" OR "Preterm labour" OR "Preterm labor" OR "trabalho de parto prematuro" OR "Trabajo de Parto Prematuro" OR "Trabalho de Parto Induzido" OR "parto induzido" OR "Trabajo de Parto Inducido" OR "induction of labour" OR "Pain during labour" OR "induction of labor" OR "Pain during labor" OR "Dor durante o parto" OR Dystocia OR Distocia OR "Perineal trauma" OR "Trauma perineal" OR "Operative vaginal delivery" OR "Parto vaginal quirúrgico" OR "Parto vaginal operatório" OR Caesarean OR cesária OR "Complicações Infecciosas na Gravidez" OR "Infectious Pregnancy Complication" OR "Infectious Pregnancy Complications" OR "Maternal Sepsis" OR "Sepsis during Pregnancy" OR "Sepsis in Pregnancies" OR "Sepsis in Pregnancy" OR "Puerperal Infection" OR "Amniotic Fluid Embolism" OR "Amniotic Fluid Embolisms" OR "Embolia amniotica" OR "Embolia de líquido amniótico" OR (TI:(embolism* OR embolia) AND TI:amniotic*) OR haemorrhag* OR hemorrhag* OR fistula OR sepsis OR sepse OR "anaesthesia complications" OR "Embolia Pulmonar" OR "Pulmonary Embolism" OR (TI:(emboli* OR tromboemboli* OR thromboemboli*) AND TI:pulmonar*))) AND (instance:"regional" OR instance:"ghl")

**Comment by botturam** [comment]
alterado em  /bases/Strategies2IAHX/apps/strategies/ods3_wizard_mortalidade_materna/**5_ODS3_mortalidade_materna-5_Complications_during_labor_delivery.sch**

**Comment by botturam** [comment]
disponível em produção.
