### ISSUE TITLE
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema2: Abortion

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#592]
[Abortion.txt](https://github.com/bireme/db-processing/files/6978594/Abortion.txt)

**Comment by veronicaabdala** [comment]
Refiz a busca para ajustar o problema reportado. Por favor considerar a seguinte estratégia:

((Reduc* OR reduzir OR reduct* OR reducci* OR mitiga* OR detener OR detencion OR diminuir OR diminuicao OR diminut* OR disminucion OR disminuir OR evitar OR evitable* OR evitave* OR declin* OR prevencion OR prevention OR prevencao OR preventiv* OR decrease OR decresce* OR ti:end OR combat* OR acabar OR terminar OR control* OR erradica* OR elimina* OR eradica* OR mitiga* OR baixar OR bajar OR sh:"prevencao e controle" OR "servicos preventivos" OR "servicios preventivos" OR "preventive services" OR mh:"Prevention and Mitigation" OR "Prevention and Mitigation" OR "Prevencion y Mitigacion" OR "Prevencao e Mitigacao" OR mh:H02.403.720.750* OR mh:N02.421.726*) AND ((("indice de mortalidad" OR "taxa de mortalidade" OR "mortality rate" OR "death rate" OR "indices de mortalidad" OR "taxas de mortalidade" OR "mortality rates" OR "death rates" OR death* OR obito* OR mortali* OR morte* OR muerte* OR mh:mortality OR mh:"mortalidade prematura" OR sh:mortalidade OR "mortalidade prematura" OR "mortalidad prematura" OR "premature mortality" OR "mortalidade precoce" OR "mortalidad precoz" OR "early death" OR "muerte prematura" OR "muerte precoz" OR "muerte temprana" OR "morte precoce" OR fallecid* OR fallecimiento* OR falecid* OR faleciment* OR dye OR dying OR "Near Miss") AND (TI:materna OR TI:maternal)) OR ("Maternal Mortality" OR "mortalidade materna" OR "mortalidad materna" OR "Maternal Mortality" OR "maternal deaths" OR "Maternal death" OR "Mortalities Maternal" OR "Maternal Near Miss")) AND (aborto* OR abortion* OR "Pérdida Precoz del Embarazo" OR "Pérdida Temprana del Embarazo" OR "Pérdidas Precoces del Embarazo" OR "Pérdidas Tempranas de los Embarazos" OR "Interrupção Involuntária da Gravidez" OR "Perda Precoce da Gravidez" OR "Perdas Precoces das Gestações" OR TI:miscarriage OR "safe abortion" OR "aborto seguro" OR "Ectopic pregnancy" OR "Gravidez Ectopica" OR "Embarazo Ectopico" OR "post-abortion care" OR "aborto induzido" OR "criminal abortion" OR "aborto criminoso" OR "Aborto Criminal" OR "Illegal Abortion" OR "Illegal Abortions" OR "Aborto ilegal")) AND (instance:"regional" OR instance:"ghl")

**Comment by renatomurasaki** [comment]
@botturam favor reprocessar

**Comment by botturam** [comment]
alterado em /bases/Strategies2IAHX/apps/strategies/ods3_wizard_mortalidade_materna/**5_ODS3_mortalidade_materna-5_abortion.sch**

**Comment by botturam** [comment]
@pintoros favor validar e fechar o chamado.

**Comment by botturam** [comment]
concluído.
