### ISSUE TITLE
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema3:Haemorrhage

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#593]
[Haemorrhage.txt](https://github.com/bireme/db-processing/files/6978598/Haemorrhage.txt)

**Comment by veronicaabdala** [comment]
Segue expressão de busca refeita para a meta 3.1 tema 3 haemorrhage:

((Reduc* OR reduzir OR reduct* OR reducci* OR mitiga* OR detener OR detencion OR diminuir OR diminuicao OR diminut* OR disminucion OR disminuir OR evitar OR evitable* OR evitave* OR declin* OR prevencion OR prevention OR prevencao OR preventiv* OR decrease OR decresce* OR ti:end OR combat* OR acabar OR terminar OR control* OR erradica* OR elimina* OR eradica* OR mitiga* OR baixar OR bajar OR sh:"prevencao e controle" OR "servicos preventivos" OR "servicios preventivos" OR "preventive services" OR mh:"Prevention and Mitigation" OR "Prevention and Mitigation" OR "Prevencion y Mitigacion" OR "Prevencao e Mitigacao" OR mh:H02.403.720.750* OR mh:N02.421.726*) AND ((("indice de mortalidad" OR "taxa de mortalidade" OR "mortality rate" OR "death rate" OR "indices de mortalidad" OR "taxas de mortalidade" OR "mortality rates" OR "death rates" OR death* OR obito* OR mortali* OR morte* OR muerte* OR mh:mortality OR mh:"mortalidade prematura" OR sh:mortalidade OR "mortalidade prematura" OR "mortalidad prematura" OR "premature mortality" OR "mortalidade precoce" OR "mortalidad precoz" OR "early death" OR "muerte prematura" OR "muerte precoz" OR "muerte temprana" OR "morte precoce" OR fallecid* OR fallecimiento* OR falecid* OR faleciment* OR dye OR dying OR "Near Miss") AND (TI:materna OR TI:maternal)) OR ("Maternal Mortality" OR "mortalidade materna" OR "mortalidad materna" OR "Maternal Mortality" OR "maternal deaths" OR "Maternal death" OR "Mortalities Maternal" OR "Maternal Near Miss")) AND ("Hemorragia Pós-Parto" OR "Postpartum Hemorrhage" OR "Hemorragia Posparto" OR "Hemorragia Puerperal" OR (((haemorrhag* OR hemorrhag* OR "hemorragia uterina" OR "Uterine Hemorrhage") AND TI:(obstetr* OR interpart* OR delivery OR parto OR pos-parto OR Postpart* OR labor OR puerpera* OR gestati* OR gestant* OR gestac* OR pregnan* OR gravidez OR embaraz* OR grávida*)) OR ((TI:(haemorrhag* OR hemorrhag* OR hemorrag*) OR MH:"hemorragia" OR "hemorragia uterina" OR "Uterine Hemorrhage") AND (MH:"Obstetric Labor Complications" OR "Obstetric Labor" OR "Labor Complications" OR "Complicações do Parto" OR "Trabajo de Parto" OR "Pregnancy Complications" OR "Complicações na Gravidez" OR "Complicaciones del Embarazo" OR "obstetric complications" OR MH:"pregnancy"))))) AND (instance:"regional" OR instance:"ghl")

**Comment by renatomurasaki** [comment]
@botturam favor reprocessar

**Comment by botturam** [comment]
alterado em ods3_wizard_mortalidade_materna/**5_ODS3_mortalidade_materna-5_haemorrhage.sch**

**Comment by botturam** [comment]
@pintoros favor validar e fechar o chamado.

**Comment by botturam** [comment]
concluído.
