### ISSUE TITLE
 ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema4:Hypertensive disorders

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#594]
[Hypertensive disorders.txt](https://github.com/bireme/db-processing/files/6978602/Hypertensive.disorders.txt)

**Comment by veronicaabdala** [comment]
Por favor processar esta expressão de busca Meta3.1 - Tema4:

((Reduc* OR reduzir OR reduct* OR reducci* OR mitiga* OR detener OR detencion OR diminuir OR diminuicao OR diminut* OR disminucion OR disminuir OR evitar OR evitable* OR evitave* OR declin* OR prevencion OR prevention OR prevencao OR preventiv* OR decrease OR decresce* OR ti:end OR combat* OR acabar OR terminar OR control* OR erradica* OR elimina* OR eradica* OR mitiga* OR baixar OR bajar OR sh:"prevencao e controle" OR "servicos preventivos" OR "servicios preventivos" OR "preventive services" OR mh:"Prevention and Mitigation" OR "Prevention and Mitigation" OR "Prevencion y Mitigacion" OR "Prevencao e Mitigacao" OR mh:H02.403.720.750* OR mh:N02.421.726*) AND ((("indice de mortalidad" OR "taxa de mortalidade" OR "mortality rate" OR "death rate" OR "indices de mortalidad" OR "taxas de mortalidade" OR "mortality rates" OR "death rates" OR death* OR obito* OR mortali* OR morte* OR muerte* OR mh:mortality OR mh:"mortalidade prematura" OR sh:mortalidade OR "mortalidade prematura" OR "mortalidad prematura" OR "premature mortality" OR "mortalidade precoce" OR "mortalidad precoz" OR "early death" OR "muerte prematura" OR "muerte precoz" OR "muerte temprana" OR "morte precoce" OR fallecid* OR fallecimiento* OR falecid* OR faleciment* OR dye OR dying OR "Near Miss") AND (TI:materna OR TI:maternal)) OR ("Maternal Mortality" OR "mortalidade materna" OR "mortalidad materna" OR "Maternal Mortality" OR "maternal deaths" OR "Maternal death" OR "Mortalities Maternal" OR "Maternal Near Miss")) AND(("hypertension, Pregnancy-Induced" OR "Pregnancy Induced hypertension" OR "Pregnancy-induced hypertension" OR "Gestational Hypertension" OR "Pregnancy Induced Hypertension" OR "Pregnancy Transient Hypertension" OR "Hipertensão Induzida pela Gravidez" OR "Hipertensão Gestacional" OR "Hipertensión gestacional" OR "Hipertensión Inducida en el Embarazo" OR "Pre-Eclampsia" OR Preeclampsia OR Eclampsia) OR ((MH:"hipertension" OR TI:(hipertens* OR hypertens*) OR hipertens* OR hypertens* OR "High pressure" OR "Blood Pressure" OR "Pressão arterial alta" OR "Pressão alta" OR "Pressão sanguinea alta" OR "Presión sanguínea alta" OR "Presión alta" OR Toxemia* OR Gestosis OR Gestose) AND (gravidez OR gravidas OR gravida OR gestaciona* OR gestacao OR gravidic* OR embarazad* OR embarazo OR pregnanc* OR pregnant*)))) AND (instance:"regional" OR instance:"ghl")

**Comment by veronicaabdala** [comment]
CONSIDERAR ESTA ESTRATÉGIA, Encontrei um erro no espaço antes de um AND:

((Reduc* OR reduzir OR reduct* OR reducci* OR mitiga* OR detener OR detencion OR diminuir OR diminuicao OR diminut* OR disminucion OR disminuir OR evitar OR evitable* OR evitave* OR declin* OR prevencion OR prevention OR prevencao OR preventiv* OR decrease OR decresce* OR ti:end OR combat* OR acabar OR terminar OR control* OR erradica* OR elimina* OR eradica* OR mitiga* OR baixar OR bajar OR sh:"prevencao e controle" OR "servicos preventivos" OR "servicios preventivos" OR "preventive services" OR mh:"Prevention and Mitigation" OR "Prevention and Mitigation" OR "Prevencion y Mitigacion" OR "Prevencao e Mitigacao" OR mh:H02.403.720.750* OR mh:N02.421.726*) AND ((("indice de mortalidad" OR "taxa de mortalidade" OR "mortality rate" OR "death rate" OR "indices de mortalidad" OR "taxas de mortalidade" OR "mortality rates" OR "death rates" OR death* OR obito* OR mortali* OR morte* OR muerte* OR mh:mortality OR mh:"mortalidade prematura" OR sh:mortalidade OR "mortalidade prematura" OR "mortalidad prematura" OR "premature mortality" OR "mortalidade precoce" OR "mortalidad precoz" OR "early death" OR "muerte prematura" OR "muerte precoz" OR "muerte temprana" OR "morte precoce" OR fallecid* OR fallecimiento* OR falecid* OR faleciment* OR dye OR dying OR "Near Miss") AND (TI:materna OR TI:maternal)) OR ("Maternal Mortality" OR "mortalidade materna" OR "mortalidad materna" OR "Maternal Mortality" OR "maternal deaths" OR "Maternal death" OR "Mortalities Maternal" OR "Maternal Near Miss")) AND (("hypertension, Pregnancy-Induced" OR "Pregnancy Induced hypertension" OR "Pregnancy-induced hypertension" OR "Gestational Hypertension" OR "Pregnancy Induced Hypertension" OR "Pregnancy Transient Hypertension" OR "Hipertensão Induzida pela Gravidez" OR "Hipertensão Gestacional" OR "Hipertensión gestacional" OR "Hipertensión Inducida en el Embarazo" OR "Pre-Eclampsia" OR Preeclampsia OR Eclampsia) OR ((MH:"hipertension" OR TI:(hipertens* OR hypertens*) OR hipertens* OR hypertens* OR "High pressure" OR "Blood Pressure" OR "Pressão arterial alta" OR "Pressão alta" OR "Pressão sanguinea alta" OR "Presión sanguínea alta" OR "Presión alta" OR Toxemia* OR Gestosis OR Gestose) AND (gravidez OR gravidas OR gravida OR gestaciona* OR gestacao OR gravidic* OR embarazad* OR embarazo OR pregnanc* OR pregnant*)))) AND (instance:"regional" OR instance:"ghl")

**Comment by renatomurasaki** [comment]
@botturam favor reprocessar

**Comment by botturam** [comment]
alterado em /bases/Strategies2IAHX/apps/strategies/ods3_wizard_mortalidade_materna/**5_ODS3_mortalidade_materna-5_hypertensive_disorders.sch**

**Comment by botturam** [comment]
@pintoros favor validar e fechar o chamado.

**Comment by botturam** [comment]
concluído.
