### ISSUE TITLE
ODS3-Meta 3.1: Reduzir a mortalidade materna - Tema5: Infections

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#595]
[Infections.txt](https://github.com/bireme/db-processing/files/6978607/Infections.txt)

**Comment by veronicaabdala** [comment]
Pesquisa refeita, corrigida:

((Reduc* OR reduzir OR reduct* OR reducci* OR mitiga* OR detener OR detencion OR diminuir OR diminuicao OR diminut* OR disminucion OR disminuir OR evitar OR evitable* OR evitave* OR declin* OR prevencion OR prevention OR prevencao OR preventiv* OR decrease OR decresce* OR ti:end OR combat* OR acabar OR terminar OR control* OR erradica* OR elimina* OR eradica* OR mitiga* OR baixar OR bajar OR sh:"prevencao e controle" OR "servicos preventivos" OR "servicios preventivos" OR "preventive services" OR mh:"Prevention and Mitigation" OR "Prevention and Mitigation" OR "Prevencion y Mitigacion" OR "Prevencao e Mitigacao" OR mh:H02.403.720.750* OR mh:N02.421.726*) AND ((("indice de mortalidad" OR "taxa de mortalidade" OR "mortality rate" OR "death rate" OR "indices de mortalidad" OR "taxas de mortalidade" OR "mortality rates" OR "death rates" OR death* OR obito* OR mortali* OR morte* OR muerte* OR mh:mortality OR mh:"mortalidade prematura" OR sh:mortalidade OR "mortalidade prematura" OR "mortalidad prematura" OR "premature mortality" OR "mortalidade precoce" OR "mortalidad precoz" OR "early death" OR "muerte prematura" OR "muerte precoz" OR "muerte temprana" OR "morte precoce" OR fallecid* OR fallecimiento* OR falecid* OR faleciment* OR dye OR dying OR "Near Miss") AND (TI:materna OR TI:maternal)) OR ("Maternal Mortality" OR "mortalidade materna" OR "mortalidad materna" OR "Maternal Mortality" OR "maternal deaths" OR "Maternal death" OR "Mortalities Maternal" OR "Maternal Near Miss")) AND (MH:C01.610.752.530* OR MH:Plasmodium OR MH:Antimalarials OR Malaria OR "Doença Malárica" OR "Febre Malárica" OR "Febre Remitente Paludosa" OR "Remittent Fever" OR "Febre da Malária" OR "Febre do Mangue" OR "Marsh Fever" OR "Fiebre Remitente na Malária" OR "Infecção Malárica" OR "Infecções por Plasmodium" OR "Plasmodium Infection" OR "Plasmodium Infections" OR Maleita OR Paludismo OR Antimalari* OR Plasmódio OR Anti-malári* OR MH:"HIV" OR MH:B04.820.650.589.650.350* OR MH:"Receptores de HIV" OR MH:D12.776.543.750.830.700* OR "Infecções por HIV" OR MH:C01.778.640.400* OR "Fármacos Anti-HIV" OR MH:D27.505.954.122.388.077.088* OR MH:"Síndrome de Imunodeficiência Adquirida" OR "Vacinas contra a AIDS" OR TI:("HIV" OR "Vírus da AIDS" OR "Vírus da Imunodeficiência Humana" OR "Vírus de Imunodeficiência Humana" OR "AIDS Virus" OR "Acquired Immune Deficiency Syndrome Virus" OR "Acquired Immunodeficiency Syndrome Virus" OR "Human Immunodeficiency Virus" OR "Receptores de HIV" OR "HIV Receptors" OR "Infecções por HIV" OR "Anti-HIV Agents" OR "Fármacos Anti-HIV" OR "Agentes Anti-AIDS" OR "Agentes Anti-HIV" OR "HIV infection" OR "Síndrome de Imunodeficiência Adquirida" OR "Acquired Immunodeficiency Syndrome" OR AIDS OR SIDA OR "AIDS Vaccine" OR "AIDS Vaccines" OR "HIV Vaccine" OR "HIV Vaccines") OR "Infectious Pregnancy Complications" OR MH:Sepsis OR MH:C23.550.470.790.500* OR "Síndrome de Resposta Inflamatória Sistemica" OR MH:C23.550.470.790* OR "Sepsis in Pregnancy" OR "Maternal Sepsis" OR TI:(Sepsis OR Piemia OR Pioemia OR Sepsia OR Septicemia OR "Blood Poisoning" OR Pyaemia* OR Pyemia* OR Pyohemia* OR Septicemia* OR "Severe Sepsis" OR SRIS OR Fungemia* OR Bacteriemia OR Bacteremia OR "Choque Séptico" OR "Septic Shock"))) AND (instance:"regional" OR instance:"ghl")

**Comment by renatomurasaki** [comment]
@botturam favor reprocessar.

**Comment by botturam** [comment]
alterado em /bases/Strategies2IAHX/apps/strategies/ods3_wizard_mortalidade_materna/**5_ODS3_mortalidade_materna-5_infections.sch**

**Comment by botturam** [comment]
@pintoros favor validar e fechar o chamado.

**Comment by botturam** [comment]
concluído.
