### ISSUE TITLE
atuar para resolver problema na coleta de Butantan-Sophia

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#596]
a URL não funciona: http://biblioteca-acervo.butantan.gov.br/biblioteca_web/oai/oai.asp

**Comment by botturam** [comment]
em contato com Joanita; Sarah está em férias.

**Comment by botturam** [comment]
Ainda não solucionado. Informei à Joanita sobre minhas férias.

_Joanita e Sarah,

perfeito. Eu sairei de férias hoje e volto dia 28/09. Qualquer novidade, por favor, informem ao Chico Lopez  lopesf.bir@gmail.com

A coleta segue sendo feita, mas dando erro. Caso volte a funcionar, a atualização será normalizada automaticamente.

obrigado,_

**Comment by renatomurasaki** [comment]
@botturam editei seu comentário acima por conter informação sensível. Se o problema da coleta é um problema na aplicação Sofia, creio que não há necessidade de manter este issue aberto. Como você comentou, assim que Sofia volte a funcionar, a atualização será normalizada.

**Comment by renatomurasaki** [comment]
@botturam se meu comentário acima está correto, pode encerrar

**Comment by botturam** [comment]
o suporte do Sophia-Butantan foi acionado pelo Butantan. Se normalizar o serviço de coleta, o processamento volta a funcionar.
