### ISSUE TITLE
desenvolver rotina de espera de início de processamento IAHx-covidoms (Solr3) e IAHx-covidwho (Solr5) 

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#597]
@ChicoLopes criar rotina que verifica se XMLs de covidom e covidwho estão prontas em INBOX-Covid

1) basicamente apagar e criar arquivo de flag em rodaCOVIDWHO.sh (marcações apaga e cria no arquivo sh)
2) em /bases/iahx/exec/cron_weekly3.sh, criar mecanismo de início apenas quando houver flag em /bases/iahx/xml-inbox/covidwho/**cvd_regional.flg**

A ideia é checar a cada 20min, por 6 vezes, até que se inicie o processamento.

**Comment by botturam** [comment]
rotina de espera arquivo de flag (cvd_regional.flg) funcionando e em operação.

**Comment by renatomurasaki** [comment]
@botturam excelente!
