### ISSUE TITLE
Cadastrar módulos do processamento BDENF no Cellery

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#6]

**Comment by botturam** [comment]
aguardando mais estudos de como podemos cadastrar os novos módulos de processamento no Celery

**Comment by falbrito** [comment]
Cadastrados os seguintes modulos para realizar processamento através do Celery
1) ../tpl.lil/coleta_scp.sh bde
2) ../tpl.lil/pos_coleta_bde.sh bde
3) ../tpl.lil/pre_saneamento_fi.sh bde
4) ../tpl.lil/saneamento_bde.sh bde
5) ../tpl.lil/iah_like_lilacs_fi.sh bde
6) ../tpl.lil/iahh_fi.sh bde

Os testes foram realizados desconsiderando o passo 6 pois ainda não estamos enviando para homologação.
Tudo correu bem em termos de processamento. 
Os dados de processamento foram populados corretamente no mysql porém a visualização no Flower está com o horário marcando 3 horas na frente, problema de timezone que ainda não consegui resolver.

**Comment by renatomurasaki** [comment]
Aguardando instalação do Celetry em ambiente de produção.

**Comment by falbrito** [comment]
Cadastro e em linha.
