### ISSUE TITLE
Verify the completeness of database conversion for WPRO and SEARO

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#60]
To be sure if all fields from XML harvested are in the processing/conversion database.

**Comment by botturam** [comment]
SEARO verificada. Campos foram mapeados. Falta gerar um ISIS a partir do dado crú, em formato DIM.

WPRO - Falta verificar com o Fábio. Isso é rápido.

**Comment by botturam** [comment]
WPRO is completed. CSVs files are ready in ftp.bireme.br/gim/wprim_tabulacoes.zip

**Comment by renatomurasaki** [comment]
SEARO is already done according to #56

**Comment by renatomurasaki** [comment]
WPRO is ok also.
