### ISSUE TITLE
Verificar porque o resumo do documento covidwho-1135313 não foi atualizado com a mensagem padrão de withdraw

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#602]
O documento https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwho-1135313

Está mostrando o resumo original e deveria mostrar o resumo padrão nos casos de WITHDRAW, como mostra a imagem 

![image](https://user-images.githubusercontent.com/1226218/131189274-4b280b91-fa33-41a2-b160-e5eff81a8302.png)

E como se vê no texto completo

https://www.sciencedirect.com/science/article/pii/S0378378220307556?via%3Dihub

Como esse registro foi enriquecido, favor verificar como está o campo resumo na base Medline que utilizamos no processamento.

Outros detalhes estão na troca de e-mail com a Deborah com o subject "COVIDDB/ 2021 /June/ Withdrawn article / Degiorgio Sophie at Health-MDH"

**Comment by botturam** [comment]
O Portal regional está correto:

WITHDRAWN: COVID-19 related acute decline in paediatric admissions in Malta, a population-based study.
Degiorgio, Sophie; Grech, Neil; Dimech, Yana Marie; Xuereb, John; Grech, Victor. 
Early Hum Dev ; : 105251, 2020 Nov 12.
Artigo em Inglês | MEDLINE | ID: mdl-33293107
Estudo primário |  Ver em Epistemonikos
ABSTRACT
This article has been withdrawn at the request of the author(s) and/or editor. The Publisher apologizes for any inconvenience this may cause. The full Elsevier Policy on Article Withdrawal can be found at https//www.elsevier.com/about/our-business/policies/article-withdrawal.

É algo do proc. COVID

**Comment by botturam** [comment]
@renatomurasaki a falha foi minha. Quando passei a aplicar os arquivos diários de MEDLINE-UPDATE em mdl-2020, criei a estrutura de diretório abaixo para trabalhar:

m20.upd/            (Portal Regional)
m20.upd/bak/     (COVID)

ao terminar a atualização, deveria ter movido os conteúdos acima para seus respectivos abaixo:

m20.mdl/        (proc. oficial Portal Regional)
m20.mdl/bak  (proc. oficial COVID)

entretanto, não movi "m20.mdl/bak" para ../m20.mdl, de onde o processamento COVID toma o dado. Aí foi a causa da desatualização.

No processamento de hoje, os registros mdl20 serão atualizados.

Acrescentei em genMDLupdALL.sh:

   mv *.* ../m${ANO_Processado}.mdl
   [ -d ../m${ANO_Processado}.mdl/bak ] && rm -r ../m${ANO_Processado}.mdl/bak
   mv bak ../m${ANO_Processado}.mdl

**Comment by renatomurasaki** [comment]
@botturam verificado e o resumo agora está correto. Obrigado. Importante evitar esse problema, pois este tipo de atualização relacionado ao WITHDRAW é muito sensível e manter a informação disponível após decisão de retirada é super negativa para a nossa iniciativa.
