### ISSUE TITLE
BVS-VETINDEX acrescentar os registros do FI-ADMIN no iaHx

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#605]
Acrescentar os registros coletado do FI-ADMIN do índice VETINDEX no processamento e publicação do iaHx
Grata

**Comment by botturam** [comment]
@anakatiacamilo Kátia, os 3.601 docs de :/bases/fiadmin/databases/vetindex  já estavam incorporados no processamento regular de vetindex.

Não tivemos nenhuma ação.

**Comment by anakatiacamilo** [comment]
Obrigada vou informar os responsáveis da BVS-VETINDEX
