### ISSUE TITLE
COVID - Não recebemos CSV planilha principal (csv.rec/covidwho/incremental/)

### ISSUE THREAD

**Issue by ChicoLopes** [bireme/db-processing#606]
Não recebemos a planilha principal, inclusive o e-mail sinalizou algum ERRO.

Comparando a página do dropbox observa-se que houve atualização de entrada, porém não surtiu efeito em serverofi5.
Os demais arquivos CSV foram recebidos normalmente.

**Comment by renatomurasaki** [comment]
Obrigado pela identificação do problema @ChicoLopes 

@heitorbarbieri por favor, veja o que ocorreu, pois acabo de acessar o DropBox da iniciativa e o arquivo Excel está disponível com os metadados de 31-08-21, conforme e-mail recebido hoje que fora enviado pela Tini.

Anexo o arquivo aqui 
[who-repo4covid-biblio.xlsx](https://github.com/bireme/db-processing/files/7086439/who-repo4covid-biblio.xlsx)

**Comment by heitorbarbieri** [comment]
Reprocessei o arquivo e os csv correspondentes foram gerados corretamente e validados pelo  @ChicoLopes
