### ISSUE TITLE
Fazer double check da informação semântica mostrada na interface do WHO COVID-19 e os dados originalmente disponíveis no SemMed

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#607]
@heitorbarbieri por favor, fazer uma nova checagem para validar se o dado original disponível no SemMed está corretamente sendo mostrado na interface do WHO COVID-19. Apenas um double check para garantir que os predicados mostrados são realmente dos documentos que o processo associou.

**Comment by heitorbarbieri** [comment]
@renatomurasaki realizada a checagem em uma amostra aleatória de 7 referências:

1) Assessment of musculoskeletal pain, fatigue and grip strength in hospitalized patients with COVID-19.
covidwho-1406909 
mdl-33393277
COVID-19 PROCESS_OF hospitalized patients
(191188204,361902557,'33393277','PROCESS_OF','C5203670','COVID-19','dsyn',1,'C0870668','hospitalized patients','humn',1,NULL,NULL,NULL)


2) Master Regulator Analysis of the SARS-CoV-2/Human Interactome.
covidwho-1403624
mdl-32244779
Proteins PART_OF Host Cell 
(183676193,345405470,'32244779','PART_OF','C0033684','Proteins','aapp',0,'C1819995','Host Cell','celc',1,NULL,NULL,NULL)


3) On coughing and airborne droplet transmission to humans. 
covidwho-1396542
mdl-32574229
Coughing PROCESS_OF Homo sapiens 
(187165285,352980551,'32574229','PROCESS_OF','C0010200','Coughing','sosy',1,'C0086418','Homo sapiens','humn',1,NULL,NULL,NULL)


4) Multivessel coronary thrombosis in a patient with COVID-19 pneumonia. 
covidwho-1393240
mdl-32374373
Coronary Thrombosis PROCESS_OF Patients 
(183655019,345357074,'32374373','PROCESS_OF','C0010072','Coronary Thrombosis','dsyn',1,'C0030705','Patients','humn',0,NULL,NULL,NULL)


5) Trypsin-Like Proteases and Their Role in Muco-Obstructive Lung Diseases.
covidwho-1389398
mdl-34072295
KLK11 protei ASSOCIATED_WITH C0600260 
(194178610,368793206,'34072295','ASSOCIATED_WITH','C1447694|11012','KLK11 protein, human|KLK11','aapp',1,'C0600260','Lung Diseases, Obstructive','dsyn',1,NULL,NULL,NULL)


6) Localized and Generalized Urticarial Allergic Dermatitis Secondary to SARS-CoV-2 Vaccination in a Series of Six Patients. 
covidwho-1385880
mdl-34109263
SARS-CoV-2 vaccination CAUSES Dermatiti 
(194255357,368968536,'34109263','CAUSES','C5203672','SARS-CoV-2 vaccination','topp',1,'C0011615','Dermatitis, Atopic','dsyn',1,NULL,NULL,NULL)


7) SARS-CoV-2 genomic variations associated with mortality rate of COVID-19. 
covidwho-666290
mdl-32699345
Genome PART_OF 2019 novel coronavirus
(183575555,345181268,'32699345','PART_OF','C0017428','Genome','gngm',0,'C5203676','2019 novel coronavirus','virs',1,NULL,NULL,NULL)


O quinto teeste nos alertou para um bug corrigido no issue AddPredicates/#5 . Todos os outros exemplos apresentaram o resultado esperado, isto é, geração correta dos predicados.
