### ISSUE TITLE
Main database (covidwho- prefix) citations missing language tags

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#609]
I finished isolating the covidwho- citations that are missing their language tags.  A total of 59 077 downloaded from the online database were missing these tags.  Of these, 58 520 came from the main database in Distiller, and 544 from the grey lit database in Distiller (grey lit citations that hold covidwho- prefixes, as they pre-date our separation of grey lit from journal articles).

If you do the math, you'll notice the numbers don't match.  13 citations downloaded from the online database did not appear in Distiller.  I can think of several potential causes for this discrepancy.  However, I have not yet taken the time to isolate these citations.  

As you will see in the attached spreadsheets, 49 875 of the citations in Distiller have their language tags. The other 8881 in the main database and 308 in the grey database do not have language tags.  I will work with our volunteers to create language tags for these citations.  

A large number of the citations missing language tags in Distiller are citations out of Covidence.  I am checking with Jose, whether their tags exist in Covidence, and if so, if we might be able to easily re-attach them.

**Comment by renatomurasaki** [comment]
[31Augcovidwho-GreyLitMissingLang.xlsx](https://github.com/bireme/db-processing/files/7091693/31Augcovidwho-GreyLitMissingLang.xlsx)
[31AugMainMissingLang.xlsx](https://github.com/bireme/db-processing/files/7091694/31AugMainMissingLang.xlsx)

**Comment by botturam** [comment]
continuação desse tema do idioma em https://github.com/bireme/Covid-19_WHO/issues/2
