### ISSUE TITLE
Verify if the CSV processing are using raw data for WHOLIS, WPRO and SEARO

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#61]

**Comment by botturam** [comment]
verificarei amanhã cedo, 6f, 04/08/17, com o Fábio

**Comment by botturam** [comment]
WHOLIS, WPRO and SEARO are using raw data.

**Comment by botturam** [comment]
WHOLIS is completed. CSVs files are ready in ftp.bireme.br/gim/wholis_tabulacoes.zip

**Comment by renatomurasaki** [comment]
All CSV are using raw data for analysis and data quality processing.
