### ISSUE TITLE
Projeto CGAN - Qualificacao da forca de trabalho

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#617]
Processamento para infometria

[QUALIFICAÇÃO DA FORÇA DE TRABALHO EM NUTRICAO.txt](https://github.com/bireme/db-processing/files/7188845/QUALIFICACAO.DA.FORCA.DE.TRABALHO.EM.NUTRICAO.txt)

**Comment by botturam** [comment]
concluído.
