### ISSUE TITLE
Projeto CGAN - Seguranca alimentar e nutricional

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#618]
Processamento para infometria

[COOPERAÇÃO E ARTICULAÇÃO PARA A SEGURANÇA ALIMENTAR E NUTRICIONAL.txt](https://github.com/bireme/db-processing/files/7188847/COOPERACAO.E.ARTICULACAO.PARA.A.SEGURANCA.ALIMENTAR.E.NUTRICIONAL.txt)

**Comment by ChicoLopes** [comment]
@botturam arquivo de estratégia de Seguranca alimentar e nutricional, denominado 'CGAN-cooperacao_articulacao_seguranca_alimentar.sch' está processado com dados disponíveis para continuidade do processo e processo automático de coleta semanal implantado.

**Comment by botturam** [comment]
concluído.
