### ISSUE TITLE
Projeto CGAN - Pesquisa inovacao e conhecimento em nutricao

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#619]
processamento para infometria

[PESQUISA, INOVAÇÃO E CONHECIMENTO EM NUTRICAO.txt](https://github.com/bireme/db-processing/files/7188848/PESQUISA.INOVACAO.E.CONHECIMENTO.EM.NUTRICAO.txt)

**Comment by botturam** [comment]
concluído.
