### ISSUE TITLE
Labels - Evid@Easy

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#621]
Favor corrigir o tópico: Doenças transmissíveis no nível 1 de navegação para:

ODS3-Meta 3.3 Acabar com as doenças tropicais negligenciadas e combater as doenças transmissíveis
SDG3-Target 3.3 End transmission of communicable diseases
ODS3-Meta 3.3 Poner fin a las enfermedades desatendidas y detener  enfermedades transmisibles
ODS3-Objectif 3.3 Mettre fin aux maladies tropicales négligées et combattre les maladies transmissibles

Para os futuros tópicos favor observar a planilha de Labels disponível em:

https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Projetos/REGIONAL/Evid@Easy/Traducao-labels.xlsx?d=w72ad4e35e72b41719072d14fa20447d5&csf=1&web=1&e=c4H6Ba

**Comment by viniciusandrade** [comment]
@pintoros ajutes no rótulo "Doenças transmissíveis" realizado para todos os idiomas.
