### ISSUE TITLE
O total de registros mostrados no cluster Database do WHO COVID-19 deveria mostrar mais de 2000 documentos do Indonesian Research e só mostra um pouco mais de 500

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#622]
De acordo com o controle da OMS, a entrada de registros da Indonesian Research é o seguinte:

![image](https://user-images.githubusercontent.com/1226218/135089272-b9030d32-c818-4e18-ad37-c2a53af3193f.png)

Entrentanto, olhando o cluster Database, vemos somente 547 para o Indonesian Research:

![image](https://user-images.githubusercontent.com/1226218/135089414-3d485db9-c003-40cb-9a78-1973e4c86ebb.png)

Suspeita: alguns registros do Indonesian research podem estar indexados em Medline e sendo enriquecidos, o que ocasionará a perda da informação Indonesian Research pois o campo database se tornará Medline.

A equipe da OMS colocou no Dropbox o arquivo **who-repo4covid-biblio-updates-08.09.21 Indonesian Cits.xlsx** com a lista de todos os documentos da Indonesian Research já ingressados na base.

**Comment by renatomurasaki** [comment]
@botturam veja o e-mail que a Deborah enviou em 10 de setembro para o @heitorbarbieri com cópia para o Mori e para você. O subject é "decrease in the number of Indonesian Research citations appearing online". Pode ajudar na sua análise.

**Comment by botturam** [comment]
@renatomurasaki já está consertado em produção. O problema era o mesmo daquele que ocorreu com o campo idioma, no mês passado. Os registros que eles enviaram posteriormente no set update (arquivos who-covid-19-repo-export2iAHxProcessing-upd.csv) estavam sem a informação do "db". Fiz um acerto de modo que não perca esse campo, mesmo que deixe de existir no set update.

**Comment by renatomurasaki** [comment]
@botturam obrigado! Excelente!
