### ISSUE TITLE
Relatório de links quebrados - TITLE

### ISSUE THREAD

**Issue by suelisuga** [bireme/db-processing#625]
Solicito geração de relatório de links quebrados de periódicos (TITLE):
-Correntes
-Area de Saúde

**Comment by anakatiacamilo** [comment]
@suelisuga, segue a lista. 
[TITLE_url_brk_202110.xlsx](https://github.com/bireme/db-processing/files/7348628/TITLE_url_brk_202110.xlsx)

**Comment by suelisuga** [comment]
Muito obrigada @Camilo, Ana Katia ***@***.***>

Sueli Mitiko Yano Suga

Supervisora, Fontes de Informação Referenciais/Produção de Fontes de Informação

Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde - BIREME

OPAS/OMS | Tel +55 11 5576-9831 VOIP 44831

<http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>

[cid:fadb7461-f58f-423c-9ea4-a6a177036d18]
LILACS 35 años
https://lilacs.bvsalud.org/35anos/es/
[cid:647e5002-f661-4834-86aa-1ab713e2a2d2]
________________________________
De: anakatiacamilo ***@***.***>
Enviado: jueves, 14 de octubre de 2021 15:53
Para: bireme/db-processing ***@***.***>
Cc: Suga, Sueli Mitiko Yano (BIR) ***@***.***>; Mention ***@***.***>
Asunto: Re: [bireme/db-processing] Relatório de links quebrados - TITLE (#625)


@suelisuga<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsuelisuga&data=04%7C01%7Csugasuel%40paho.org%7C0b5113b7fb5741bef69b08d98f43f92b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637698344369546327%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AlVTzdhxTN0V545iDJTirssmXmeSAr84bWYZuDMIG6A%3D&reserved=0>, segue a lista.
TITLE_url_brk_202110.xlsx<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Ffiles%2F7348628%2FTITLE_url_brk_202110.xlsx&data=04%7C01%7Csugasuel%40paho.org%7C0b5113b7fb5741bef69b08d98f43f92b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637698344369556282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=A4qVGP%2BjZRhamvug7rRYguXK%2BIWVOHOM56oDi3kEBdY%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F625%23issuecomment-943632282&data=04%7C01%7Csugasuel%40paho.org%7C0b5113b7fb5741bef69b08d98f43f92b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637698344369556282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fM57lCGi%2BHlEbWkrvFzUpx0874I%2F0wBlduDwulUS5pk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADD7UEZDCO7CE4AX4PKOQF3UG4RMHANCNFSM5FOR2XMA&data=04%7C01%7Csugasuel%40paho.org%7C0b5113b7fb5741bef69b08d98f43f92b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637698344369566243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=L2VfuItXDCOV%2BD0h1mEsYm0ueZwlhzRshqFSAiGedFk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csugasuel%40paho.org%7C0b5113b7fb5741bef69b08d98f43f92b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637698344369566243%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F1PwlSh7%2FeJELfPY51kRAODgKPFteFIr4MzOY4d2DIs%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csugasuel%40paho.org%7C0b5113b7fb5741bef69b08d98f43f92b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637698344369576197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3Qh5Lv8TqzxcrvGtSQdwk5l9k44oV9SkLpbM5%2FQ9Cs0%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
