### ISSUE TITLE
COVIDDB / 2021 / Nov / Inclusion of IRIS / COVID documents in the WHO Covid Db

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#642]
Hi All,

It came up in the meeting of the Rapid Review Group  that some WHO guidance on COVID 19 was not found in the search of the COVID 19 Database.
My understanding was that the citations from IRIS were beiing automatically harvested from IRIS directly.
The citations are available through this link

https://apps.who.int/iris/discover?search-result=true&query=&scope=&filtertype_0=mesh&filter_relational_operator_0=contains&filter_0=COVID-19&rpp=10&sort_by=dc.date.accessioned_dt&order=desc

which is a predetermined link  to find all the citations created by the IRIS team.
Jose, can you clarify the situation. Perhaps I was just making an assumption.

Tomas

------------------------------------------------------------------------------------------------------------------------------------------------------------------

Hi Tomas,

 

Yes. I remember. BIREME is harvesting IRIS from what I remember with a standard search strategy done by BIREME. But at our technical meeting on 11.03.2021, they asked if we could provide them with a better search strategy to better capture and filter WHO COVID-19 citations. See note below from that meeting.  See notes here below:

 

 

17.          For citations without DOI, should we be including URLs or some other type of link? (IRIS cits, many grey lit cits)  For IRIS we’ve put in the URI.  But CDC doesn’t have this.  URL as alternative?

The data processing has a rule to use the URI/URL in the DOI field. However, we need to check if this is working properly to make sure we can keep proceeding as like. Could you check some samples that is putting URI/URL/Handle? in the DOI field to check the search interface?

Meeting note: Renato to check with BIREME team. Deborah to provide some examples? Tomas to share search strategies with Renato. Renato to check how often IRIS is harvested.

 

Special Note

For the COVID-19 db: Biorxiv and Medrxiv & ICTRP are being automatically harvested by BIREME. Approach can be extended to other information services such as: IRIS, GIM, LILACS, etc.

 

​docx icon WHO COVID-19-new implementations-next steps questions-2021-MeetingNotes-11.03.21.docx
[WHO COVID-19-new implementations-next steps questions-2021-MeetingNotes-11.03.21.pdf](https://github.com/bireme/db-processing/files/7468146/WHO.COVID-19-new.implementations-next.steps.questions-2021-MeetingNotes-11.03.21.pdf)

**Comment by heitorbarbieri** [comment]
Here are the two minimal filters which can be applied from what I can remember from IRIS: 

dc.subject.mesh: COVID-19 - http://apps.who.int/iris/discover?filtertype_1=subject&filter_relational_operator_1=contains&filter_1=COVID-19&submit_apply_filter=&query=

dc.subject: WHO guideline http://apps.who.int/iris/discover?filtertype_1=subject&filter_relational_operator_1=contains&filter_1=WHO+Guideline&submit_apply_filter=&query=

Over to Tomas to supplement and make them more exhaustive.

**Comment by botturam** [comment]
@heitorbarbieri Eu acho que o Tomas pensa que coletamos docs sobre COVID no WHOIRIS, mas não fazemos isso. Apenas enriquecemos os docs que já estão na base COVIDWHO.

De qualquer forma, vc poderia me indicar mais especificamente os documentos que estão faltando? olhei para o primeiro e os 4 últimos da página que vc indicou, mas estão todos na IAHx-COVID

**Comment by botturam** [comment]
@heitorbarbieri não fazemos isso que o Garnica menciona:

Yes. I remember. BIREME is harvesting IRIS from what I remember with a standard search strategy done by BIREME.

**Comment by botturam** [comment]
apenas enriquecemos 283 docs de COVIDWHO que estáo em WHOIRIS e possuem DOI idënticos.

**Comment by heitorbarbieri** [comment]
@botturam vendo na url abaixo

https://apps.who.int/iris/discover?rpp=10&etal=0&scope=&group_by=none&page=75&sort_by=dc.date.accessioned_dt&order=desc&filtertype_0=mesh&filter_relational_operator_0=contains&filter_0=COVID-19

o primeiro artigo da mesma, não se encontra na interface de busca da COVIS/WHO 

ApartTogether survey: preliminary overview of refugees and migrants self-reported impact of COVID-19

**Comment by botturam** [comment]
@heitorbarbieri Como eu disse, esse documento não tem DOI no WHOIRIS:

mfn=  1348
  1  "CH1.1"
  2  "337931"
  4  "WHOLIS"
  6  "m"
  8  "^uhttps://apps.who.int/iris/handle/10665/337931"
 16  "World Health Organization"
 18  "ApartTogether survey: preliminary overview of refugees and migrants self-reported impact of COVID-19"
 40  "en"
 62  "World Health Organization"
 64  "2020"
 65  "20200000"
 66  "Geneva"
 67  "CH"
 69  "9789240017924 (electronic version)"
 69  "9789240017931 (print version)"
 71  "12077"
 87  "^d59585;^d12458;^d37735;^d52950;^d28608;^d54399"
 91  "2020-12-18T12:43:26Z"
776  "dspace - who^i337931^bcom_10665_8"
854  "202000"
855  "0022"
1033  "en"

e também não está na base do COVIDWHO. Tem que, primeiro, estar na COVIDWHO e, depois, ter um DOI para link com WHOIRIS (para enriquecimento).

Eles estão achando que os docs do WJHOIRIS vão automaticamente para COVIDWHO, o que não é verdade

**Comment by botturam** [comment]
@heitorbarbieri acho que isso foi esclarecido, certo?

**Comment by botturam** [comment]
realmente já foi esclarecido. Estou finalizando após reunião minha com Heitor.
