### ISSUE TITLE
COVID-19 Literature Update - Discrepancy in the number of citations

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#643]
We’re contacting you to tell you that there is again some discrepancy in the numbers of citations for 01.11.2021

Citations in database: 20 (yesterday there were 11)
(entry_date:20211101)

Citations sent to BIREME: 1326

**Comment by botturam** [comment]
@heitorbarbieri  Enviei um e-mail indicando problema de envio dos dados do PENTAHO ao OFI5.

Favor verificar.

**Comment by botturam** [comment]
@barbieri todos os 1.326 docs referentes à data 01/11/2021 foram ingressados manualmente nos csvs-COVID-principal
