### ISSUE TITLE
Projeto CGAN - GESTÃO DAS AÇÕES DE ALIMENTAÇÃO E NUTRIÇÃO

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#644]
processamento para infometria
[GESTÃO DAS AÇÕES DE ALIMENTAÇÃO E NUTRIÇÃO.txt](https://github.com/bireme/db-processing/files/7470637/GESTAO.DAS.ACOES.DE.ALIMENTACAO.E.NUTRICAO.txt)

**Comment by botturam** [comment]
incluído.
