### ISSUE TITLE
COVIDWHO - relatório diário de documentos por data de entrada (entry_date)

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#645]
Criar um relatório diário para determinar quantos documentos de cada FI entraram no INBOX/covidwho. Seria para determinar os registros de entrada por entry_date dos seguintes XMLs:

cvd_regional.xml
czh_regional.xml
grc_regional.xml
ictrp_regional.xml
ppbiorvix_regional.xml
ppc_regional.xml
ppmedrvix_regional.xml

Exemplo para "entry_date:20211101":

grep "entry_date\">20211101" *.xml | grep -ve "mdl\|lil\|els\|lph\|lwh\|lwp"

cvd_regional.xml:            1325 docs
ppbiorvix_regional.xml:        6 docs
ppmedrvix_regional.xml:   14 docs

Gravar em /bases/oai.pmh/csv.rec/covidwho/relatorios_geral

**Comment by ChicoLopes** [comment]
@botturam é necessário alguma "tradução", por exemplo de ictrp_regional.xml para ICTRP ou Clinical Trials, u coisa parecida para os XMLs apontados?

**Comment by ChicoLopes** [comment]
@botturam qualquer coisa depois ajusto. No momento o programa é chamado relatDOCScovid.sh, cria um relatório em arquivo chamado 'relatorio-YYYY-MM-DD.txt', no momento, no diretório '/bases/iahx/xml-inbox/covidwho/wrk', que pode ser alterado a qualquer tempo.
Na chamada deve ser fornecido o número de dias que se deseja retroceder em relação ao do momento da execução, assim 0 (zero), obtem-se os dados do dia, 1 de ontem, 2 de anteontem e assim por diante.
O relatório gerado (só guarda o último gerado no dia) tem a seguinte formação:

 BIREME-OPS-OMS                 Daily ticket report extracted from 2021-11-11
==============================================================================
        Documents entered in cvd_regional.xml on the 2021-11-10: 2273
        Documents entered in czh_regional.xml on the 2021-11-10: 0
        Documents entered in grc_regional.xml on the 2021-11-10: 1091
      Documents entered in ictrp_regional.xml on the 2021-11-10: 0
  Documents entered in ppbiorvix_regional.xml on the 2021-11-10: 7
        Documents entered in ppc_regional.xml on the 2021-11-10: 0
  Documents entered in ppmedrvix_regional.xml on the 2021-11-10: 11
==============================================================================
                 Total documentos entered on the day 2021-11-10: 3382

Aqui aparece meio desalinhado porque não são caracteres monospaced, mas esta tudo alunhado pelo dois pontos (:). Este foi gerado (11/nov/2021) com o comando **relatDOCScovid.sh 1**, gerando então com os dados de ontem (10-nov-2021).

**ATENÇÃO: o arquivo 'listaXMLs' deve pré-existir no diretório de execução, que é o mesmo onde ficam os relatórios!**

Por favor dê uma criticada e me oriente sobre o que deve ser alterado.

**Comment by botturam** [comment]
essa semana, 08/11/2021, a OMS passou a mandar o campo date_entry com data D+1, ou seja, hoje chegam os dados de 2f (date_entry=15/11/2021). Vi que vc colocou um parâmetro para retroceder "n" dias; dá para adiantar 1 dia (se dia atual for 2f a 5f), e adiantar 3 dias, caso seja 6f? Na verdade, o "dia_calendario" tem que ser D+1 (2f a 5f) e D+3 (6f).

Por exemplo,  o dado do relatório que vc gerou ontem é o dado que chegou na 4f, e o dado do relatório de hoje, chegou ontem.

**Comment by ChicoLopes** [comment]
@botturam o shell de montagem de relatório de documentos de COVID incluídos no dia (**relatDOCScovid.sh**) está pronto para teste e está agendado para ser executado às 20:59 de segunda a sexta, imediatamente antes, portanto, da execução do processamento de covidwho. Da forma que esta agendado o programa determina automáticamente o acréscimo de dias necessário para a geração do relatório, que será armazenado e acumulado em _/bases/iahx/proc/logs/relatorios_, com o nome no formato **relatorio-covid-YYYY-MM-DD.txt**.
Acredito que observar o comportamento por dois ou três dias seja suficiente para homologá-lo. Assm que esteja certificado envio um arquivo com a documentação completa do mesmo.

**Comment by ChicoLopes** [comment]
@botturam segue anexado a este comentário o arquivo **relatorioDocumentosCOVIDnosXML.txt**, contendo o que pude detalhar mais detidamente sobre a geração de relatórios dos documentos COVID-19.

Vale ressaltar que da versão do dia 16-nov para esta foi um incluído um sinalizador de último relatório gerado para que possa ser coletado para envio por e-mail à WHO por **cron_weekly3.sh**.  O arquivo de sinalização é denominado **lastCOVIDrel.txt** e como sugere o nome sempre conterá o nome do arquivo de relatório mais recentemente gerado. Ele fica no mesmo diretório dos relatórios, que está anotado na variável **$RELATDIR** do shell e deve ter seu conteúdo mantido par e passo com a mesma variável em **cron_weekly3.sh**.

[relatorioDocumentosCOVIDnosXML.txt](https://github.com/bireme/db-processing/files/7628763/relatorioDocumentosCOVIDnosXML.txt)

**Comment by botturam** [comment]
relatório inserido em shs.lil/rodaCOVIDWHO.sh

# Executa contagem de documentos ingressados
TPR="iffatal"
MSG="Erro: relatDOCScovid.sh"
relatDOCScovid.sh
. log

resultado: csv.rec/covidwho/relatorios_geral
