### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis - Haemoglobinopathies-hemolytic anaemias

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#659]
[haemoglobinopathies-hemolytic anaemias.txt](https://github.com/bireme/db-processing/files/7522272/haemoglobinopathies-hemolytic.anaemias.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
concluído, já em produção.
