### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis - Immune disorders

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#660]
[Immune disorders.txt](https://github.com/bireme/db-processing/files/7522276/Immune.disorders.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
@pintoros favor acertar a estatrégia Immune disorders.txt  no ponto:

OR Polimiosit* **OR OR** "Miosite Múltipla"

Para o processamento, já acertei esse detalhe.

**Comment by botturam** [comment]
concluído.
