### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis - Kidney, renal pelvis ureter cancer

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#663]
[Kidney, renal pelvis ureter cancer.txt](https://github.com/bireme/db-processing/files/7522317/Kidney.renal.pelvis.ureter.cancer.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
concluído.
