### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis - Lymphomas, multiple myeloma

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#667]
[Lymphomas, multiple myeloma.txt](https://github.com/bireme/db-processing/files/7522361/Lymphomas.multiple.myeloma.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
concluído, já em produção.
