### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis - Mouth-oropharynx cancers

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#671]
[Mouth-oropharynx cancers.txt](https://github.com/bireme/db-processing/files/7522375/Mouth-oropharynx.cancers.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
concluído, já em produção.
