### ISSUE TITLE
ODS3-Meta 3.2 Reduzir as mortes de recém nascidos e crianças com menos de 5 anos - Neonatal care

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#689]
[3.2_Neonatal care-health.txt](https://github.com/bireme/db-processing/files/7522573/3.2_Neonatal.care-health.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
@pintoros acertar a estratégia no trecho: 

OR ti:respeit* **OR OR** ti:Respet*

**Comment by pintoros** [comment]
Obrigada Marcelo, vou corrigir.

Abraço



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:f9ea2ff7-d030-42a2-b356-7054e6cce505]

________________________________
De: botturam ***@***.***>
Enviado: terça-feira, 21 de dezembro de 2021 12:12
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/db-processing] ODS3-Meta 3.2 Reduzir as mortes de recém nascidos e crianças com menos de 5 anos - Neonatal care (Issue #689)


@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=04%7C01%7Cpintoros%40paho.org%7C14b2d918ddeb4b2406d508d9c4945fa5%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637756963824039066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cDuAvIudtxhWucCsJ6JWQW1f1cM1NyC9DCrbJI7RUU4%3D&reserved=0> acertar a estratégia no trecho:

OR ti:respeit* OR OR ti:Respet*

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F689%23issuecomment-998858610&data=04%7C01%7Cpintoros%40paho.org%7C14b2d918ddeb4b2406d508d9c4945fa5%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637756963824039066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nGV%2FXYaIf2QAffpY38HNVi1rEwrZ98RcaoRH%2FQPwJmY%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4DYLCYQNFUOPCMTO4TUSCKPJANCNFSM5H3C6G6A&data=04%7C01%7Cpintoros%40paho.org%7C14b2d918ddeb4b2406d508d9c4945fa5%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637756963824039066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hWNcD8N1N3sFdn2VdaijY5S1nw8s7CVlfw3UIfqqWsk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7C14b2d918ddeb4b2406d508d9c4945fa5%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637756963824039066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6c26fP%2F5xgagFm09XJ70be8eP7O53pT45O0ST9hmwg4%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpintoros%40paho.org%7C14b2d918ddeb4b2406d508d9c4945fa5%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C1%7C637756963824039066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SC5v4EQdkDCj4DU36Yg0pHKlHNJIXD6aTYFzsTo%2BoD0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
finalizado. Disponível em produção.
