### ISSUE TITLE
Analisar metadados utilizados na base decs

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#69]
Realizar análise dos metadados utilizados na base DeCS

Origem do dado
Quartzo2: /home/decsweb/www/bases/decsweb.{mst,xrf}

**Comment by renatomurasaki** [comment]
@falbrito favor atualizar esse issue

**Comment by falbrito** [comment]
Análise realizada. Alguns campos deverão ser normalizados para futura migração.

https://bir-fc.paho.org/TC/TC/Gerencias/AFI/OFI/decs_fdt_ANALISE.xlsx
