### ISSUE TITLE
Generalização dos módulos de processamento denvolvidos para BDENF

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#7]
Baseado no processamento BDENF, generalizar os módulos para qualquer base like LILACS:

- [x] Criar módulo coleta do processamento
- [x] Criar módulo normaliza/harmoniza do processamento
- [x] Criar módulo processamento_iAH
- [x] Criar módulo atualiza_iAH_homologacao do processamento
- [x] Criar módulo geracao_XML_iAHx do processamento

**Comment by botturam** [comment]
sobre o item "geração_xml_iAHx", falta arquitetar e desenvolver um procedimento mais genérico que o atual para geração de iAHx-XML. A idéia é gerar os XMLs das instâncias, partindo das FIs individualmente, e não mais gerá-los a partir de uma determinada instância.

**Comment by renatomurasaki** [comment]
Este issue foi concluído dentro da especificação inicial. @botturam o seu comentário deve gerar outro issue para refatoramento da geração xml iAHx, de acordo com esta nova arquitetura.
