### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis - Malnutrition and Nutritional deficiencies

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#706]
[Malnutrition and Nutritional deficiencies.txt](https://github.com/bireme/db-processing/files/7571167/Malnutrition.and.Nutritional.deficiencies.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
concluído e disponível em produção
