### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis - Chronic Obstructive Pulmonary Disease

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#707]
[Chronic Obstructive Pulmonary Disease.txt](https://github.com/bireme/db-processing/files/7571206/Chronic.Obstructive.Pulmonary.Disease.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
concluído e disponível em produção
