### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis -  Congenital and chromosomal anomalies

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#708]
[Congenital and chromosomal anomalies.txt](https://github.com/bireme/db-processing/files/7571491/Congenital.and.chromosomal.anomalies.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
concluído e disponível em produção
