### ISSUE TITLE
ODS3-Meta 3.4 - Reduzir as mortes prematuras devido doenças não transmissíveis -  Musculoskeletal diseases

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#713]
[Musculoskeletal diseases and rheumatic disorders.txt](https://github.com/bireme/db-processing/files/7571535/Musculoskeletal.diseases.and.rheumatic.disorders.txt)

**Comment by botturam** [comment]
em processamento...

**Comment by botturam** [comment]
disponível em produção.
