### ISSUE TITLE
Proc. COVIDOMS - SoLR3 - incluir envio de e-mail para membros da WHO

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#715]
Enviar e-mail de término de processamento com relatório anexado. Por exemplo, /bases/oai.pmh/csv.rec/covidwho/relatorios_geral/report_EntryDate_2021-11-24.txt

subject:
O Subject por ser: COVID-WHO - end processing (Entry Date: 2021-11-24)

enviar para:
GARNICA CARRENO, Jose Luis <garnicacarrenoj@who.int>
ALVARADO WU, Silvia Ines <alvaradowusi@who.int>

TOMCAT
\# covidoms (SoLR3 - porta 1)
30 19 * * 1-5 /bases/iahx/exec/cron_weekly3.sh covidoms

**Comment by ChicoLopes** [comment]
@botturam o envio do e-mail está provido ao final do shell **cron_weekly3.sh**, condicionado à instância em processamento ser **covidoms**, como mostrado no código incluído no arquivo txt carregado (e-mailWHO.txt).
O e-mail carrega como anexo o relatório de quantidade de documento CODIV-19 há para a data, devido a isso **cron_weekly3.sh** teve de receber a declaração de mais uma variável que aponta o local de depósito dos relatórios, que caso seja alterado necessita ser atualizado no shell.

[e-mailWHO.txt](https://github.com/bireme/db-processing/files/7628656/e-mailWHO.txt)

**Comment by botturam** [comment]
Faz o envio após o final do proc. IAHx-COVIDWHO, em cron_weekly3.sh

os relatórios enviados ficam em csv.rec/covidwho/relatorios_geral
