### ISSUE TITLE
SMS-SP Gerar um arquivo para estatística de contribuição

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#716]
Gerar um arquivo com a base legado (lildbi-web congelado) + a base filtrado (SMS-SP) do FI-ADMIN com os seguintes campos:

CentroCooperantes [1]
ID [2]
Tipo de Documento [5]
Níve Bibliografico [6]
Data de Publicação [64]
Data de Publicação iso [65]
Data de entrada de dados [91] Contribuição
Data de atualização de dados [93] Contribuição

Para geras as estatísticas:
a)      Número total de registro/documento da   SMS
b)        Número de registro/documento publicado por ano – 2011, 2012, etc...
c)         Número de registro/documento por período, exemplo de 2016 a 2021
d)        Número de registro/documento por centro cooperante
e)        Número de registro por tipo de documento: ano, período, centro   cooperante

**Comment by anakatiacamilo** [comment]
Foi criado a base do SMS-SP legado + FI-ADMIN com o total de 13629 registros com a pft abaixo

mx LILACS_posjunta "pft='SMS-SP|'v1'|'v2'|'v5'|'v6'|'v64'|'v65'|'if v2:'biblio' then v91.4,v91*5.2,v91*8.2 else v91.8 fi'|'if v2:'biblio' then v93.4,v93*5.2,v93*8.2 else v93.8 fi'|'(v4+|; |)'|'(v904+|; |)/" lw=0

Como no iaHx o índice da SMS-SP  tem 16907 registros conversamos com o @botturam e indentificamos que o OFI faz um tratamento especial para alguns índices (SMS-SP, SES-SP e colecionaSUS) que tem controle de instituições no campo Base de dados [4] (aba local). O script procura instituições e marca o campos Base de dados e Indexado em somente para a publicação no iaHx, por isto a diferença de aproximadamente 3000 registros no SMS-SP.

Vamos solicitar esses regisitro para incluir no arquivo de estatistica.
Vamos marcar esses registros como SMS-SP no FI-ADMIN.

**Comment by botturam** [comment]
criado lilacs_SMS-SP.txt em /bases/lilG4/sms/SMS-SP_tab

**Comment by anakatiacamilo** [comment]
Apaguei os registros duplicados da base legado congelada. O Arquivo ficou com 14510 registros
Resumo 
12647 registros legado congelada LILDBI-Web
+
990 registros Marcados SMS-SP no campo Indexado em
+
6017 estratégia no campo Base de dados com as Instituições da SMS-SP
=
19654 lilacs_SMS-SP.txt
-
5144 registros duplicados
=
14510 Registros no Final

Foi criado um arquivo excel SMS-SP_Estatistica contrib com tabelas dinamicas conforme solicitado e enviado para Sueli
