### ISSUE TITLE
Solicito base de origem do FI-ADMIN com os registros do índice SMS-SP 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#717]
Conforme explicação no #716 solicito a base que vem do FI-ADMIN com os registros do SMS-SP do campo Indexado em - 985 registos + os aproximadamente os 3000 registros do tratamento do campo Base de dados com as instituição do SMS-SP.

**Comment by botturam** [comment]
O critério para gerar esses docs foi o aplicar o critéio abaixo em 10 bases de dados, nas quais ocorriam algum dos subcritérios:

for i in cna con eco inc lil red rhs ses sms sus
do
   mx $i.lil/lilacs "proc=if v904:'SMS-SP' or s(mpu,v4,mpl) : 'ATTI-PRODUCAO' or s(mpu,v4,mpl) : 'AHM-PRODUCAO' or s(mpu,v4,mpl) : 'AHM-ACERVO' or s(mpu,v4,mpl) : 'CAMPOLIMPO-PRODUCAO' or s(mpu,v4,mpl) : 'CAMPOLIMPO-ACERVO' or s(mpu,v4,mpl) : 'TATUAPE-PRODUCAO' or s(mpu,v4,mpl) : 'TATUAPE-ACERVO' or s(mpu,v4,mpl) : 'CEP-PRODUCAO' or s(mpu,v4,mpl) : 'CAB-PRODUCAO' or s(mpu,v4,mpl) : 'CEINFO-PRODUCAO' or s(mpu,v4,mpl) : 'CGP-PRODUCAO' or s(mpu,v4,mpl) : 'CSMRCAA-PRODUCAO' or s(mpu,v4,mpl) : 'COGERH-PRODUCAO'  or s(mpu,v4,mpl) : 'TIRADENTES-PRODUCAO' or s(mpu,v4,mpl) : 'CACHOEIRINHA-PRODUCAO' or s(mpu,v4,mpl) : 'CACHOEIRINHA-ACERVO' or s(mpu,v4,mpl) : 'MBOIMIRIM-PRODUCAO' or s(mpu,v4,mpl) : 'SAOLUIZGONZAGA-PRODUCAO' or s(mpu,v4,mpl) : 'VILAMARIA-PRODUCAO' or s(mpu,v4,mpl) : 'SAMU-PRODUCAO' or s(mpu,v4,mpl) : 'COMURGE-PRODUCAO' or s(mpu,v4,mpl) : 'COVISA-PRODUCAO' or s(mpu,v4,mpl) : 'COVISA-ACERVO' or s(mpu,v4,mpl) : 'CRSCENTROOESTE-PRODUCAO' or s(mpu,v4,mpl) : 'CRSCENTRO-PRODUCAO' or s(mpu,v4,mpl) : 'CRSLESTE-PRODUCAO' or s(mpu,v4,mpl) : 'CRSNORTE-PRODUCAO' or s(mpu,v4,mpl) : 'CRSOESTE-PRODUCAO' or s(mpu,v4,mpl) : 'CRSSUDESTE-PRODUCAO' or s(mpu,v4,mpl) : 'CRSSUL-PRODUCAO' or s(mpu,v4,mpl) : 'EMS-PRODUCAO' or s(mpu,v4,mpl) : 'EMS-ACERVO' or s(mpu,v4,mpl) : 'HSPM-PRODUCAO' or s(mpu,v4,mpl) : 'HSPM-ACERVO' or s(mpu,v4,mpl) : 'DST/AIDS-PRODUCAO' or s(mpu,v4,mpl) : 'DST/AIDS-ACERVO' or s(mpu,v4,mpl) : 'NP-PRODUCAO' or s(mpu,v4,mpl) : 'MAEPAULISTANA-PRODUCAO' or s(mpu,v4,mpl) : 'CRAEA-PRODUCAO' or s(mpu,v4,mpl) : 'CORAS-PRODUCAO' or s(mpu,v4,mpl) : 'SMS'  then else 'd*' fi" append=lilacs_all_sms -all now tell=100000

done

**Comment by botturam** [comment]
Obtive /bases/lilG4/sms/lilacs.mst (19.653 docs) já sem duplicação de IDs.

Após executar em /bases/lilG4/sms:
../tpl.lil/tabulacoes_likelilacs_fi.sh lilacs SMS-SP

o resultado (CSVs) está em:
/bases/lilG4/sms/SMS-SP_tab

OBS: vamos aguardar a próxima atualização da IAHx-Portal, na 6f, 03/12/2021, 06:00, para ver qual o nro de de docs da SMS-SP será maior que 16.917 docs (02/12/2021). Minha expectativa é que tenha uns 2.500 docs a mais.

**Comment by botturam** [comment]
@anakatiacamilo  o resultado de incremento de docs em IAHx-SMS-SP ainda não está refletido no site. Vamos aguardar até a próxima atualização, 2f.

Para conferir, o registro abaixo tem que aparecer na IAHx-SMS-SP:

  \<doc boost="8">
    \<field name="id">biblio-870700\</field>
    \<field name="cc">BR73.1\</field>
    \<field name="lo">BR73.1; WB410, R762n. 3872\</field>
    \<field name="bvs">regional\</field>
    \<field name="db">LILACS\</field>
     \<field name="db">AHM-Acervo\</field>
    \<field name="collection_sms">acervo_geral\</field>
    **\<field name="instance">sms\</field>**
     \<field name="db">TATUAPE-Acervo\</field>
    \<field name="collection_sms">acervo_geral\</field>
