### ISSUE TITLE
Diferenças no número de registros da revista Hansenologia Internationalis

### ISSUE THREAD

**Issue by suelisuga** [bireme/db-processing#720]
Solicito marcação de todos os registros da revista Hansenologia Internationalis nas bases de dados HANSEN, LILACS e SES-SP

ta:"hansen. int"

![image](https://user-images.githubusercontent.com/13105683/144476254-4f77aa19-8929-4c6f-83a9-d4fd3c56ed71.png)

iAHX da BVS Hanseníase: 805 registros
https://pesquisa.bvsalud.org/hansen/?lang=pt&home_url=https:%2F%2Fhansen.bvs.br&home_text=Biblioteca+Virtual+em+Sa%C3%BAde+Hansen%C3%ADase&q=ta:%22hansen.+int%22&submit=Pesquisa

iAHx LILACS: 566 registros
https://pesquisa.bvsalud.org/portal/?lang=pt&home_url=http:%2F%2Flilacs.bvsalud.org&home_text=Base+de+dados+LILACS%2C+informa%C3%A7%C3%A3o+em+sa%C3%BAde+da+Am%C3%A9rica+Latina+e+Caribe&filter%5Bdb%5D%5B%5D=LILACS&q=ta:%22hansen.+int%22&submit=

iAHx BVS RIC: 806 registros
https://pesquisa.bvsalud.org/ses/?output=site&lang=pt&from=0&sort=&format=summary&count=20&fb=&page=1&q=ta%3A%22Hansen.+int%22&index=tw&search_form_submit=Pesquisar

E no FI-Admin: 717 registros
![image](https://user-images.githubusercontent.com/13105683/144476797-f1525e1e-165d-4769-a4ec-0329582c2b16.png)

Obrigada!
Sueli

**Comment by botturam** [comment]
Entre Portal Regional X SES-SP (diferença de 1 doc),  a FI ACV-CRTAIDS está apenas em SES-SP, e não está em Portal Regional. 

_Existe um doc_:
Incapacidades físicas em hanseníase no momento do diagnóstico: II. Indicador para avaliacão do programa de controle da hanseníase / Physical disabilities in Hansen's disease at the moment of the diagnosis: II. Indicator for the evaluation of Hansen's disease control program
Trindade, Maria Angela Bianconcini; Teixeira, Paulo Roberto; Paula, Silvia Rodrigues de.
**Hansenol Int**; 12(2): 29-37, dez. 1987. tab
Artigo Português | SES SP - Acervo Centro de Referência e Treinamento DST/AIDS | ID: crt-3284

**Comment by botturam** [comment]
@suelisuga 
sobre os docs 721 docs, de **IAHx-Portal Regional** (retirar "db:LILACS da pesquisa, indicada no link 2) , é preciso considerar que a base SES-SP entra em IAHx-Portal Regional apenas com os docs de produção científica (filtro s(mhu,v4,mhl) : 'PROD'), ignorando os docs de Acervo (filtro s(mhu,v4,mhl) : 'ACERVO' or s(mhu,v4,mhl) : 'ACV'):
