### ISSUE TITLE
Solicito inclusão do autor Marchan S, no ID med-17570

### ISSUE THREAD

**Issue by suelisuga** [bireme/db-processing#723]
From: Shivaughn Marchan 
Sent: Friday, October 29, 2021 1:51 PM
To: Ayaana Alleyne-Cumberbatch 
Subject: Incorrect Google Scholar Citation

 

Dear Ms. Alleyne-Cumberbatch

 Prezados,

Solicito inclusão do autor Marchan S, no ID med-17570.
![image](https://user-images.githubusercontent.com/13105683/144920880-d2e9b827-2134-43e8-8ddd-b4df248cd86e.png)

![image](https://user-images.githubusercontent.com/13105683/144920928-bb917fe0-8a73-4777-82e5-60795529b7ca.png)

As per our telephone conversation regarding the exclusion of my name as first author in a record in Goggle Scholar.

 

The article is currently cited as:

 An in vitro evaluation of shear bond strengths of glass ionomer/amalgam combinations
Rafeek, R. ; Coldero, L. ; Smith, W. ; Ramcharan, K. 

 

The correct citation is:

Marchan S, Rafeek R, Coldero L, Smith W, Ramcharan K. An in vitro evaluation of the shear bond strengths of glass Ionomer/Amalgam combinations. CPD Dentistry. 2004;5:90–4.  

 

If you click on persons who have gone on to cite the work, the correct citation is included then.

I do hope that you can help me with this.

Dr. S Marchan

School of Dentistry

**Comment by anakatiacamilo** [comment]
@suelisuga, inclui o autor Marchan S no artigo An in vitro evaluation of shear bond strengths of glass ionomer/amalgam combinations na base de legado do Medcarib

/bases/lilG4/med.lil/isos/LILACS

mfn= 17568
  1  "TT5"
  2  "17570"
  4  "MEDCARIB"
  5  "S"
  6  "as"
  9  "a"
 10  "Marchan S^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
 10  "Rafeek, R. ^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
 10  "Coldero, L. ^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
 10  "Smith, W. ^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
 10  "Ramcharan, K. ^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
 12  "An in vitro evaluation of shear bond strengths of glass ionomer/amalgam combinations^ien"
 14  "^f90^l94"
 30  "Cpd dentistry"
 31  "5"
 32  "3"
 35  "1468-165X"
 64  "2004"
 65  "20040000"
 71  "JOURNAL ARTICLE"
 76  "Humans"
 76  "In Vitro"
 83  "Purpose: The purpose of this study was to assess the shear bond strength of amalgam when bonded to dentine with various cements. Materials and Methods: Eighty human molars were divided into five groups and ground dentine surfaces treated, with one of five cements (Fuji I, Vitrebond, Rely X, Fuji II and Panavia F). Spherical amalgam (Tytin) was condensed onto the unset cement and shear bond strengths were measured after one week. Results: The mean shear bond strength of Panavia F (25.3 MPa) was significantly higher compared with Fuji I (16.8 MPa), Fuji II (10.3 MPa) and Vitrebond (5.1 MPa) however there was no significant difference with Rely X (19.0 MPa). Conclusion: The combination of a resin modified glass ionomer luting cement with a spherical alloy may enhance bonding of amalgam to dentine. ^ien"
 87  "^dDental Amalgam^sanal"
 87  "^dGlass Ionomer Cements^sanal"
 87  "^dGlass Ionomer Cements^sdiag use"
 87  "^dShear Strength"
 91  "20090304^i10:51:29^f11:02:07^t0:10:38"
 92  "DATA"
 93  "20120405^i14:36:03^f14:36:50^t0:0:47"
 98  "FONTE"
113  "p"
899  "LILDBI-WEB 1.6"

**Comment by suelisuga** [comment]
Ok @Camilo, Ana Katia ***@***.***>

Muito obrigada!

Sueli Mitiko Yano Suga

Supervisora, Fontes de Informação Referenciais/Produção de Fontes de Informação

Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde - BIREME

OPAS/OMS | Tel +55 11 5576-9831 VOIP 44831

<http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>

[cid:511eabb4-c105-401e-a736-100f2cb2b996]
LILACS 35 años
https://lilacs.bvsalud.org/35anos/es/
[cid:6ecef8ad-7e39-4939-97ad-7447896e147e]
________________________________
De: anakatiacamilo ***@***.***>
Enviado: martes, 7 de diciembre de 2021 11:23
Para: bireme/db-processing ***@***.***>
Cc: Suga, Sueli Mitiko Yano (BIR) ***@***.***>; Mention ***@***.***>
Asunto: Re: [bireme/db-processing] Solicito inclusão do autor Marchan S, no ID med-17570 (Issue #723)


@suelisuga<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsuelisuga&data=04%7C01%7Csugasuel%40paho.org%7C96173ae7db4149dd5e0408d9b98d1f55%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637744838034626617%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XsuIWA8CJ02tHE%2B7oS9oqhomzx18Hrw8O9Rf%2FS02beM%3D&reserved=0>, inclui o autor Marchan S no artigo An in vitro evaluation of shear bond strengths of glass ionomer/amalgam combinations na base de legado do Medcarib

/bases/lilG4/med.lil/isos/LILACS

mfn= 17568
1 "TT5"
2 "17570"
4 "MEDCARIB"
5 "S"
6 "as"
9 "a"
10 "Marchan S^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
10 "Rafeek, R. ^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
10 "Coldero, L. ^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
10 "Smith, W. ^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
10 "Ramcharan, K. ^1School of Dentistry^2Faculty of Medical Sciences^3University of the West Indies^cSt. Augustine^pTrinidad and Tobago^raut"
12 "An in vitro evaluation of shear bond strengths of glass ionomer/amalgam combinations^ien"
14 "^f90^l94"
30 "Cpd dentistry"
31 "5"
32 "3"
35 "1468-165X"
64 "2004"
65 "20040000"
71 "JOURNAL ARTICLE"
76 "Humans"
76 "In Vitro"
83 "Purpose: The purpose of this study was to assess the shear bond strength of amalgam when bonded to dentine with various cements. Materials and Methods: Eighty human molars were divided into five groups and ground dentine surfaces treated, with one of five cements (Fuji I, Vitrebond, Rely X, Fuji II and Panavia F). Spherical amalgam (Tytin) was condensed onto the unset cement and shear bond strengths were measured after one week. Results: The mean shear bond strength of Panavia F (25.3 MPa) was significantly higher compared with Fuji I (16.8 MPa), Fuji II (10.3 MPa) and Vitrebond (5.1 MPa) however there was no significant difference with Rely X (19.0 MPa). Conclusion: The combination of a resin modified glass ionomer luting cement with a spherical alloy may enhance bonding of amalgam to dentine. ^ien"
87 "^dDental Amalgam^sanal"
87 "^dGlass Ionomer Cements^sanal"
87 "^dGlass Ionomer Cements^sdiag use"
87 "^dShear Strength"
91 "20090304^i10:51:29^f11:02:07^t0:10:38"
92 "DATA"
93 "20120405^i14:36:03^f14:36:50^t0:0:47"
98 "FONTE"
113 "p"
899 "LILDBI-WEB 1.6"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F723%23issuecomment-987972211&data=04%7C01%7Csugasuel%40paho.org%7C96173ae7db4149dd5e0408d9b98d1f55%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637744838034636571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kckOYLfyw9xizQxQorg72NqYKqaTbpYtOoLIa5uuPsM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADD7UEZZBOETQNRMNQ52JS3UPYKFRANCNFSM5JPS45QA&data=04%7C01%7Csugasuel%40paho.org%7C96173ae7db4149dd5e0408d9b98d1f55%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637744838034636571%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r0hyvVxhelXSqIEsU%2B4hGXO1TD1Wy0IaIWZu9KzGmZw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csugasuel%40paho.org%7C96173ae7db4149dd5e0408d9b98d1f55%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637744838034646530%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3mmp%2BRe9sfDp0ueacU6ZDiKX%2Ba8ULoHfLaTkdhY9zpc%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csugasuel%40paho.org%7C96173ae7db4149dd5e0408d9b98d1f55%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637744838034656485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PUoMXt0An7t%2F1%2FyDPWpNUnunUwz8udTQibo5jpU0kl8%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by anakatiacamilo** [comment]
![image](https://user-images.githubusercontent.com/19270675/146657684-2105fa5f-07ae-4e1a-a34a-b812e7f30d53.png)

**Comment by suelisuga** [comment]
![image](https://user-images.githubusercontent.com/13105683/147953289-7d9da763-f9b9-4491-afb5-e489cc3b4042.png)
