### ISSUE TITLE
IAHx-Portal Regional - MEDLINE-Blocão - gerar um novo índice sem a fase inicial de MarkAbstract

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#744]
fazer um novo índice para substituir o atual, possivelmente com problema, mas sem a fase inicial de MarkAbstract, considerando os XMLs de MDL já existentes em:

serverofi5:/bases/iahx/proc/mdl5/main/xml.index $ ll
total 224484036
-rw-rw-r-- 1 tomcat operacao  3627895834 Jan 21 16:46 mdl00_regional.xml
-rw-rw-r-- 1 tomcat operacao  3778553125 Jan 21 18:26 mdl01_regional.xml
-rw-rw-r-- 1 tomcat operacao  3929953352 Jan 21 20:04 mdl02_regional.xml
-rw-rw-r-- 1 tomcat operacao  4160611162 Jan 21 21:46 mdl03_regional.xml
-rw-rw-r-- 1 tomcat operacao  4441649334 Jan 21 23:31 mdl04_regional.xml
-rw-rw-r-- 1 tomcat operacao  4732146487 Jan 22 01:24 mdl05_regional.xml
-rw-rw-r-- 1 tomcat operacao  4960871458 Jan 22 03:22 mdl06_regional.xml
-rw-rw-r-- 1 tomcat operacao  5192114856 Jan 22 05:42 mdl07_regional.xml
-rw-rw-r-- 1 tomcat operacao  5583324556 Jan 22 07:58 mdl08_regional.xml
-rw-rw-r-- 1 tomcat operacao  5868715446 Jan 22 10:22 mdl09_regional.xml
-rw-rw-r-- 1 tomcat operacao  6211473531 Jan 22 12:58 mdl10_regional.xml
-rw-rw-r-- 1 tomcat operacao  6649329808 Jan 22 16:16 mdl11_regional.xml
-rw-rw-r-- 1 tomcat operacao  7092324998 Jan 22 19:27 mdl12_regional.xml
-rw-rw-r-- 1 tomcat operacao  7844190690 Jan 22 22:38 mdl13_regional.xml
-rw-rw-r-- 1 tomcat operacao  9466834106 Jan 23 02:08 mdl14_regional.xml
-rw-rw-r-- 1 tomcat operacao 10471966899 Jan 23 05:37 mdl15_regional.xml
-rw-rw-r-- 1 tomcat operacao 11177618665 Jan 23 09:26 mdl16_regional.xml
-rw-rw-r-- 1 tomcat operacao 11500088285 Jan 23 13:19 mdl17_regional.xml
-rw-rw-r-- 1 tomcat operacao 12124390751 Jan 23 17:32 mdl18_regional.xml
-rw-rw-r-- 1 tomcat operacao 12899074150 Jan 23 22:09 mdl19_regional.xml
-rw-rw-r-- 1 tomcat operacao 15008410839 Jan 24 03:28 mdl20_regional.xml
-rw-rw-r-- 1 tomcat operacao 17513646926 Jan 24 09:33 mdl21_regional.xml
-rw-rw-r-- 1 tomcat operacao   524494234 Jan 24 09:34 mdl66_regional.xml
-rw-rw-r-- 1 tomcat operacao   571681135 Jan 24 09:36 mdl67_regional.xml
-rw-rw-r-- 1 tomcat operacao   628500619 Jan 24 09:37 mdl68_regional.xml
-rw-rw-r-- 1 tomcat operacao   659485564 Jan 24 09:38 mdl69_regional.xml
-rw-rw-r-- 1 tomcat operacao   676710364 Jan 24 09:40 mdl70_regional.xml
-rw-rw-r-- 1 tomcat operacao   702541156 Jan 24 09:42 mdl71_regional.xml
-rw-rw-r-- 1 tomcat operacao   725518492 Jan 24 09:44 mdl72_regional.xml
-rw-rw-r-- 1 tomcat operacao   743732001 Jan 24 09:46 mdl73_regional.xml
-rw-rw-r-- 1 tomcat operacao   769729040 Jan 24 09:48 mdl74_regional.xml
-rw-rw-r-- 1 tomcat operacao  1038420840 Jan 24 10:03 mdl75_regional.xml
-rw-rw-r-- 1 tomcat operacao  1070824344 Jan 24 10:18 mdl76_regional.xml
-rw-rw-r-- 1 tomcat operacao  1070840796 Jan 24 10:32 mdl77_regional.xml
-rw-rw-r-- 1 tomcat operacao  1111195315 Jan 24 10:47 mdl78_regional.xml
-rw-rw-r-- 1 tomcat operacao  1175962049 Jan 24 11:03 mdl79_regional.xml
-rw-rw-r-- 1 tomcat operacao  1214044125 Jan 24 11:21 mdl80_regional.xml
-rw-rw-r-- 1 tomcat operacao  1140738687 Jan 24 11:40 mdl81_regional.xml
-rw-rw-r-- 1 tomcat operacao  1332062452 Jan 24 12:01 mdl82_regional.xml
-rw-rw-r-- 1 tomcat operacao  1484410094 Jan 24 12:27 mdl83_regional.xml
-rw-rw-r-- 1 tomcat operacao  1565947759 Jan 24 12:55 mdl84_regional.xml
-rw-rw-r-- 1 tomcat operacao  1655163733 Jan 24 13:25 mdl85_regional.xml
-rw-rw-r-- 1 tomcat operacao  1729788167 Jan 24 13:56 mdl86_regional.xml
-rw-rw-r-- 1 tomcat operacao  1860916055 Jan 24 14:30 mdl87_regional.xml
-rw-rw-r-- 1 tomcat operacao  2025039450 Jan 24 15:06 mdl88_regional.xml
-rw-rw-r-- 1 tomcat operacao  2009849433 Jan 24 15:52 mdl89_regional.xml
-rw-rw-r-- 1 tomcat operacao  2402732498 Jan 24 16:40 mdl90_regional.xml
-rw-rw-r-- 1 tomcat operacao  2429133405 Jan 24 17:33 mdl91_regional.xml
-rw-rw-r-- 1 tomcat operacao  2511920167 Jan 24 18:28 mdl92_regional.xml
-rw-rw-r-- 1 tomcat operacao  2608191433 Jan 24 19:26 mdl93_regional.xml
-rw-rw-r-- 1 tomcat operacao  2724157315 Jan 24 20:28 mdl94_regional.xml
-rw-rw-r-- 1 tomcat operacao  2852124486 Jan 24 21:31 mdl95_regional.xml
-rw-rw-r-- 1 tomcat operacao  2986518263 Jan 24 22:39 mdl96_regional.xml
-rw-rw-r-- 1 tomcat operacao  3063135290 Jan 24 23:51 mdl97_regional.xml
-rw-rw-r-- 1 tomcat operacao  3215020249 Jan 25 01:06 mdl98_regional.xml
-rw-rw-r-- 1 tomcat operacao  3355505054 Jan 25 02:32 mdl99_regional.xml

**Comment by ChicoLopes** [comment]
Na direção deste objetivo o shell update-index, foi alterado para só otimizar o índice quando não for **portal**.
A seguir inicio a alteração de enviaDados.sh para só enviar dados ao servidor basalto02 durante o período de reparo da geração de índice otimizado e assim que alterado o enviaDados.sh será coloca aqui mensagem de aviso.

**Comment by botturam** [comment]
@ChicoLopes  em 1-index-daily.sh, eu havia comentado as linhas abaixo para não apagar os XMLs em /bases/iahx/proc/mdl5/main/xml.index, mas não deu certo. 

\#echo "[idxupd]  1.02      - Limpa area de dados de processamento (Processamento FULL)"
\#[ $(ls xml.index/*.xml 2> /dev/null | wc -l | awk {' print $1 '}) -gt 0  ] && rm -f xml.index/*

já voltei o 1-index-daily.sh original. Se vc conseguir resolver essa questão, pode seguir com a ideia de processar o Blocão sem apagar os XMLs já com MarkAbstract. Existe um backup dos XMLs já marcados em /bases/iahx/proc/mdl5/main/xml.index.2022

**Comment by ChicoLopes** [comment]
@botturam o realizado foi, eliminar a execução de 0-process.sh do mdl5 (/bases/iahx/proc/mdl5/main/0-process.sh), mantendo o original como 0-process.20220203.sh para posterior reposição, e provida uma cópia manual dos XML de medline previamente marcados para xml.index.

**Comment by ChicoLopes** [comment]
@botturam Para efetuar o processamento do bloco de dados do Medline (que forma o índice inicial do processamento de diversas instâncias) **SEM** efetuar a marcação dos resumos durante o processamento, é necessário, ter pronta a marcação de abstracts dos diversos XML de Medline, que deverão ser previamente carregados no diretório **xml.index** da árvore **/bases/iahx/proc/mdl5/main**.

Uma vez disponibilizados os XML preparados, no shell-script **0-process.sh**, localizado em **/bases/iahx/proc/mdl5/main**, na **linha 33** deve ser incluído o comando **exit 0**, de tal forma que 0-process.sh simplesmente seja desviado sem qualquer execução.

Shell-script exemplo deixado em /bases/iahx/proc/mdl5/main com o nome 0-process.NoMarkAbstract.sh devidamente ajustado.

Obs.: Este conteúdo se encontra reproduzido no arquvo NOTAS.txt da árvore /bases/iahx/proc/mdl5/main

**Comment by botturam** [comment]
concluído.
