### ISSUE TITLE
adaptar processamento IAHx-Portal Regional para não fazer optimize.sh nem CHECK do md5sum

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#745]
momentaneamente, até ser gerado o novo SoLR5-Blocão-MDL , retirar do proc. do Portal Regional as 2 operações indicadas no título

**Comment by botturam** [comment]
@ChicoLopes deu um erro no proc. de hoje (03/02/22) em out-update.20220202.portal.txt:

+-----------------------------------------------------------+
| ATENCAO - Erro detectado                                  |
|     Erros conhecidos foram encontrados no arquivo abaixo: |
+-----------------------------------------------------------+
Arquivo conferido: logs/out-update.20220202.portal.txt
=============================================================================
3808:rm: cannot remove `sub33290.sh': No such file or directory
3815:tail: cannot open `/home/javaapps/iahx-server/indexes/solr5-port6/portal/destino.flg' for reading: No such file or directory
3846:tail: cannot open `/home/javaapps/iahx-server/indexes/solr5-port6/portal/destino.flg' for reading: No such file or directory
=============================================================================

**Comment by botturam** [comment]
@ChicoLopes não sei se esse log é de hoje ou de ontem. Iniciei um proc. agora cedo, pois há demanda de atualização para amanhã cedo.

**Comment by ChicoLopes** [comment]
Analisando as mensagens de erro do processamento os dois erros foram provocados como explicado a seguir e as condições foram remediadas em enviaDados.sh para não recorerem.

-O primeiro erro: 3808:rm: cannot remove sub33290.sh': No such file or directory
não pode apagar o sub33290.sh (na verdade sub${MYPID}.sh) justamente por não fazer o cálculo local do MD5, para depois mandar para as Basaltos, então foi feito um arquivo sub${MYPID}.sh fake para não reclamar que não tem o que ser apagado.
-O segundo erro: 3846:tail: cannot open `/home/javaapps/iahx-server/indexes/solr5-port6/portal/destino.flg' for reading: No such file or directory
é devido a tentativa de mostrar quanto tempo demorou para fazer verificação MD5 no BASALTO, e não existir o arquivo, já que não foi efetuada a operação. Então foi provido um arquivo fake de destino.flg (da basalto01 o nome seria balance.flg)

**Comment by botturam** [comment]
@ChicoLopes o proc. do Portal acabou bem e transferiu para Basalto02. Resta saber apenas se a virada às 06:00 será bem-sucedida.

**Comment by ChicoLopes** [comment]
@botturam alterações em dois arquivos shell-script devem ser providas, em um para evitar a otimização no outro para evitar o check por MD5. Em adição a isso na tabela iAHx.tab, é mandatório eliminar o conteúdo da coluna 19 (Balance) deixando de solicitar o envio de dados para o servidor de balanceamento em produção.

### Alteração para não otimizar
Para efetuar a indexação sem realizar a otimização do índice, é necessário no shell-script update-index.sh condicionar a execução do shell-script optimize.sh, que se encontra na etiqueta de mensagem de out “**[upidx]  3         - Otimiza o indice de MDL+DeCS**”, nas proximidades da linha número 345, efetuando um teste se a instancia em processamento NÃO for determinada EFETUA a otimização.
Shell-script exemplo deixado em /bases/iahx/exec com o nome update-index.NoOptimize.sh ajustado para portal.

### Alteração para não usar MD5Sum na conferência dos dados enviados
Para não efetuar a verificação por meio do cálculo de MD5 (MD5Sum) são necessárias quatro  alterações no shell-script enviaDados.sh como descrito:
1- Na sequência da atribuição **TFIMCS=$(date '+%s')**, aproximadamente na **linha 616**, deve ser inserido um IF testando se o IDIDX (identificador de índice) é aquele que se deseja NÃO efetuar a verificação e no ramo do THEN colocar um echo de mensagem explicando que a comparação foi por simulação, ficando o echo de mensagem indicando fim de comparação no ramo do ELSE.
2- Pouco abaixo do comentário “**ATENCAO caso não exista servidor p...**“ na **linha 573**, deve ser inserido um IF testando se o IDIDX (identificador de índice) é aquele que se deseja NÃO efetuar a verificação e no ramo do THEN colocar comandos simulando que a conferência do MD5 remoto foi Ok da seguinte forma:
**RSPD=0          # Simula conferencia OK no destino e no balance
RSPB=0
echo -e "0\nConferencia na  PRODUCAO nao iniciada nem concluida, durando    0[s]" > ${R_IDX}/${DATAD}/destino.flg**
No ramo do ELSE deve ser mantido o código original (que termina no **done**)
3- Próximo comentário “**Solicita conferencia no servidor**” próximo à **linha 564** deve ser inserido outro IF testando a mesma condição e no ramo do THEN colocar um comendo inócuo, como, por exemplo, um echo. No ramo do ELSE deve ser mantido o código original (que termina na linha do **[ ! -z ${BALANCE} ] &&  $PATH_EXEC/md5_balance.sh**).
4- Próximo ao comentário “**Calcula MD5 da massa de dados em ...**”, ao redor da **linha 477** deve ser inserido mais um IF testando a mesma condição e no ramo do THEN colocar a montagem de um shell-script que será chamado pelo enviaDados.sh mais adiante da seguinte forma:
**echo "sleep 2" > sub${MYPID}.sh**
No ramo do ELSE deve ser mantido o código original (que **termina no echo “[upDATA]   “**)
Shell-script exemplo deixado em /bases/iahx/exec com o nome enviaDados.NoMD5check.sh ajustado para portal.

**Comment by botturam** [comment]
SoLR5-Portal sem optimize e MD5 checksum concluído
