### ISSUE TITLE
Proc. Portal Regional – olhar erro nos logs diários

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#748]
@ChicoLopes  Proc. Portal Regional – olhar erro nos logs do Portal regional. Parece ser um problema com o FEED de notícias da Economia da Saúde (ECO):

[pECO]  2         - Inicia procedimentos de pre-processamento da instancia
[pECO]  2.01      - Tratamento de dados de bases de dados processadas
wget -o logs/ecolog.txt -O xml.rec/feed_noticias_eco.20220203.xml http://ecos-brasil.bvs.br/export-articles_rss.php
[pECO]  2.02      - Transforma o XML para indexacao iAHx
ERROR:  'Premature end of file.'
ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.'
javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Premature end of file.

**Comment by ChicoLopes** [comment]
@botturam foi provido mecanismo de cópia do último XML obtido em 6 de abril de 2021, data após a qual passou a não mais ser possível coletar o dado na origem.
O mecanismo de cópia foi inserido no shell-script 0-process-eco.sh (/bases/iahx/proc/portal/main) nimediatamente antes da chamada da transformação efetuada com rotina escrita em java, na altura do label "[pECO]  2.01 ..." no shell.

**Comment by botturam** [comment]
agora está usando xml.rec/feed_noticias_eco.20210406.xml.
