### ISSUE TITLE
shell reiniciaIAHX.sh - erro no final do arquivo de OUT

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#749]
/home/javaapps/iahx-server/bin/reinicia_iAHx.sh  -  erro  -  olhar OUT em /bases/iahx/proc/portal/main/reiniciaIAHX.out  (procurar por PARM1)

**Comment by ChicoLopes** [comment]
@botturam A rotina reinicia_iAHx.sh tem por função reiniciar todos os servidores Solr e para isso determina quantos servidores há com base no número de diretórios de configuração existem. O servidor chamado 3 teve sua versão atualizada de Solr3 para Solr5, nessa oportunidade o diretório de configurações foi renomeado (3.old) e um novo foi criado (3), com isso para a rotina parecia haver 7 servidores e não 6 como na verdade é. Para reparar a situação o diretório denominado 3.old foi movido para o diretório pai (/home/javaapps/iahx-server) daquele onde ele residia (/home/javaapps/iahx-server/instances).

**Comment by botturam** [comment]
Resolvido.
