### ISSUE TITLE
Shell pos_coleta_oai.sh  -  inclusão de envio de e-mail quando não substituir Master File anterior pelo atual.

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#751]
em **pos_coleta_oai.sh**, na condição inversa abaixo, em negrito, enviar um e-mail para lista OFI, quando ${LAST_[$ITER]} -gt  ${FINAL[$ITER]} , ou seja, quando **não fizer** o "cp" abaixo. Preciso que me avise quando não atualizou o Master File do proc. atual e permaneceu com o último, que é maior.

Colocar no subject **ALERTA!!!**, como nas msgs do COVID.

echo "[pcoai]  2.04.04   - Escolhe M/F para uso"
ITER=0
for i in $(ls -d --color=never $IDFI*)
do
    echo -n "[pcoai]  2.04.04.$(printf "%02d" $(($ITER + 1)))- Entre FINAL[$ITER] (${FINAL[$ITER]}) e LAST_[$ITER] (${LAST_[$ITER]}) => "
    **[ ${FINAL[$ITER]} -ge ${LAST_[$ITER]} ]** && echo FINAL || echo LAST
    **[ ${FINAL[$ITER]} -ge ${LAST_[$ITER]} ]** && (cp -p $i/final.mst ../isis/$i/LILACS.mst; cp -p $i/final.xrf ../isis/$i/LILACS.xrf)
    ExibeNRegs "$i/LILACS" "${LAST_[$ITER]}" >> ${DTISO}.${IDFI}-LILACS-oai.txt
    let ITER++
done

**Comment by ChicoLopes** [comment]
@botturam foi inserido um teste no laço de verificação (localizado entre 2.04.04 e 2.05 no shell-script). o assunto do e-mail tem esse modelão: **ALERTA!!!  Master File ${i}/final NAO substituiu o existente.** e o texto contendo detalhes do processamento, como a seguir:
O M/F  $i/final  nao substituiu a base LILACS localizada em ../isis/${i}/
Data e hora atuais: $(date '+%F %T'))  diretorio corrente: $(pwd)
---
Execucao : ${HOSTNAME}:${PRGDR}/${TREXE} ${LCORI}

**Comment by botturam** [comment]
Concluído.
