### ISSUE TITLE
Base Hanseniase não apresenta só 6 registros

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#753]
A base de dados Hanseniase não carregou o número total de registros. Apresenta somente 6 dos quase 20 mil registros na interface https://pesquisa.bvsalud.org/portal.

**Comment by botturam** [comment]
acrescentei o trecho abaixo em tabs/instance.pft

case  'HANSEN':
      '    <field name="instance">hanseniase</field>'/,
      '    <field name="instance">regional</field>'/,
      '    <field name="instance">brasil</field>'/,
      '    <field name="instance">aps</field>'/,
      if p(v699) then '    <field name="instance">psbe</field>'/ fi,
      if p(v702) then '    <field name="instance">mtc</field>'/ fi,
      '    <field name="instance">bvsms</field>'/,

**Comment by botturam** [comment]
A alteração acima não surtiu efeito, pois havia uma duplicidade de uso do nome da Base de dados:  ora HANSEN, ora HANSENIASE. 

Foi acertado para considerar os dois nomes.

**Comment by pintoros** [comment]
Pergunta: qual o correto numa sintaxe de busca? Terei que colocar os dois?



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:89227e0b-3c0b-4a56-86c0-bc1240c473ff]

________________________________
De: botturam ***@***.***>
Enviado: sexta-feira, 11 de fevereiro de 2022 13:52
Para: bireme/db-processing ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/db-processing] Base Hanseniase não apresenta só 6 registros (Issue #753)


A alteração acima não surtiu efeito, pois havia uma duplicidade de uso do nome da Base de dados: ora HANSEN, ora HANSENIASE.

Foi acertado para considerar os dois nomes.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F753%23issuecomment-1036410698&data=04%7C01%7Cpintoros%40paho.org%7C8579922837d2443a8e8b08d9ed7ef241%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637801951764511623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JY8w5nEHHusyLDW6oOAa%2BvxbZMBePfA%2FepoOyKEoKKU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BKHE6462U6MEOHKFLU2U5GJANCNFSM5N3RK6YQ&data=04%7C01%7Cpintoros%40paho.org%7C8579922837d2443a8e8b08d9ed7ef241%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637801951764511623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8zDDJIn%2FWfTjv0QnnbPUPMFJ0zqOJLhMH2S18LwIhTw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpintoros%40paho.org%7C8579922837d2443a8e8b08d9ed7ef241%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637801951764511623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1ksBL2rsCc%2B6FSx1RhHKyWyNDYWxdTJereYZTcNTYtA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpintoros%40paho.org%7C8579922837d2443a8e8b08d9ed7ef241%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637801951764511623%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g2MqK3anHpuOtQ6YW7PfDO3g4PuVRk2A74JpRfoEoQI%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
@pintoros  pensando nessa questão, fiz de um jeito que é válido tanto HANSEN como HANSENIASE. Não precisa se preocupar.

Está disponível em produção.
