### ISSUE TITLE
exec/verificaXML_02.sh - relatório dos consertos em cvd_regional.xml não está enviando por e-mail

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#754]
Relatório dos “consertos” de INBOX-COVID/cvd_regional.xml, por exec/verificaXML_02.sh, não está sendo gerado em INBOX-COVID e também não está enviando por e-mail. 

OBS: o programa está funcionando bem na correção das linhas com problemas.

**Comment by ChicoLopes** [comment]
@botturam ensaiando a operação do shell verificaXML_02.sh, observo que ele está operando normalmente, uma vez que a última forma que o deixamos é de exibir em LOG o relatório de reparos efetuados, se houver ao menos um a efetuar, e caso ainda existam mais erros que não puderam ser reparados é emitido o e-mail com o relatório em anexo (sinalizando que é necessário alterar o número de ciclos de correção), e a última versão gerada do relatório sempre permanece no diretório de execução do shell, sobrescremendo uma versão anterior.

**Comment by botturam** [comment]
sobre o problema de não consertar alguns tipos de erro (sinais <, > / no elemento XML:

Marcelo bom dia.

O programa xmlstarlet, base do shell, é limitado quanto à capacidade de apontar erros do arquivo sendo verificado.

Há alguns tipos de erros que não são detectados com precisão, mas apenas após o fechamento da tag pai, por exemplo:

<tag1>
                <tag2>conteúdo tag2</tag2>
                <tag2>defeito no fechamento</tag2
                <tag2>conteúdo tag2</tag2>
</tag1>

O xmlstarlet (tanto quanto o tidy) só detectam os erros ao atingirem a linha com a marca </tag1>, que é quando é possível perceber um problema de “balanceamento” de tags. Ou seja, dependendo da organização das linhas, verificaXML_02 não “corrigirá” certos tipos de erros, pois retirará do arquivo uma linha que não é aquela onde ocorre o erro e na reverificação entrará na mesma situação de detecção de linha com erro que não é a real localização do erro.

No entanto, problemas de caracteres inválidos são detectados imediatamente.

Logo, a conclusão é que a correção é apenas uma tentativa, não uma certeza.

Outro aspecto a ser observado, é o modo de operação:

1- Se o arquivo está sem erros, com ou sem requisição de correção, NÃO emite e-mail algum;
2- Se o arquivo contém erro(s), mas não é requerida correção, EMITE e-mail avisando que o arquivo contém erro(s);
3- Se o arquivo contém erro(s), é requerida correção e esta foi efetiva, NÃO emite e-mail;
4- Se o arquivo contém erro(s), é requerida correção e esta NÃO foi efetiva EMITE e-mail.

**Comment by botturam** [comment]
IMPORTANTE: o e-mail enviado à lista OFI com o subject "ERRO de formacao no XML /bases/iahx/xml-inbox/covidwho/aaa_covidwho.xml em serverofi5" indicará que o XML avaliado NÃO foi arrumado e que continua com problema(s) no INBOX.

**Comment by botturam** [comment]
Chico verá a possibilidade de mandar outro relatório, por e-mail, com os consertos realizados e bem-sucedidos

verificaXML_02.sh /bases/iahx/xml-inbox/covidwho/cvd_covidwho.xml --fix 40

**Comment by ChicoLopes** [comment]
@botturam foram providas as alterações solicitadas de forma que agora:
1- se não houver erros não há envio de e-mail
2- se houver erros sem solicitação de correção envia e-mail avisando a condição
3- se houver erros com solicitação de correção e correção bem sucedida, envia e-mail incluindo relatório dos erros corrigidos (no corpo do e-mail consta o último reparo efetuado)
4- se houver erros co msolicitação de correção e correção mal sucedida, envia e-mail incluinido relatório das tentativas de correção efetuadas

**Comment by botturam** [comment]
Concluído. Envia e-mail apenas se der algum erro, e não conserta problemas na sintaxe do XML, como fechamento de campos ("<") :

\<field name="instance">regional/field>
