### ISSUE TITLE
verificar criação do Master File CHICO.mst em alguns processamentos.

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#755]
Verificar a necessidade de criação do master file CHICO.mst, em pos_coleta_oai.sh

(mx ${IDFI}_LILACS create=CHICO -all now) em shs.lil/pos_coleta_oai.sh. Pode ser apagado? Exemplos:

./psa.lil/CHICO.mst
./vtt.lil/CHICO.mst
./vti.lil/CHICO.mst

**Comment by ChicoLopes** [comment]
@botturam a finalidade da criação do master-file era para propósitos de back-up, pois no contrato passado foi necessário atuar no processo e para garantir que não haveriam efeitos danosos foi provida a criação da base antes de ser tratada pelo processo. A criação do M/F foi interrompida nesta data, e os arquivos desnecessários eliminados.

**Comment by botturam** [comment]
concluído
