### ISSUE TITLE
Chave Pública - usuário  "transfer" - dolomita22.bireme.br

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#756]
Favor criar chaves públicas entre OFI5 e dolomita22 (usuário "transfer": levando dados de OFI5 para dolomita22) .

**Comment by ChicoLopes** [comment]
@botturam foram criadas as chaves públicas de autenticação entre serverofi5 e dolomita22 (nesse sentido específico) para o usuário transfer, bem como os "passes" para tomcat e operacao se passarem por transfer.
Semelhantemente foram criadas chaves públicas de autenticação entre serverofi6 e dolomita22 (nesse sentido específico) para o usuário transfer, bem como o "passe" para operacao se passar por transfer.
