### ISSUE TITLE
Criar novo projeto no Celery para FI SDG

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#759]
Criar novo projeto no Celery para FI SDG, com as tarefas de /bases/lilG4/shs.lil/_sdg.sh. 

OBS: a coleta do FI-ADMIN (filtraDBs.sh) já está funcionando. Basta fazer a coleta_scp em /bases/fiadmin/databases/sdg

**Comment by ChicoLopes** [comment]
@botturam Fluxo SDG configurado, utilizando a sigla sdg na sua individualização ocupando a árvore /bases/lilG4/sdg.lil e usando a denominação [SDG - Sustainable Development Goals no Celery e escalada para execução às 5:47 de segunda a sexta.

**Comment by botturam** [comment]
proc. regular em operação INBOX/regional/sdg_regional.xml
