### ISSUE TITLE
Dado que o índice do iahx contenha os campos ab_mark", e variações "ab_pt_mark", "ab_es_mark", "ab_*_mark", alterar a interface do iahx para formatar o resumo.

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#76]
Os campos ab_mark", e variações "ab_pt_mark", "ab_es_mark", "ab__mark" contém a marcação &lt;h2&gt; para separar ítens tais como: Objetivo, Metodologia, Conclusões dentre outros. Utilizar tal marcação para criar uma apresentação mais agradável no IAHx quando se mostrar o campo de resumo de um documento.

**Comment by viniciusandrade** [comment]
Issue registrado no projeto iahx-opac para facilitar acompanhamento futuro. 

https://github.com/bireme/iahx-opac/issues/30
