### ISSUE TITLE
Operador NOT apresenta comportamento aparentemente inesperado na interface COVID/WHO

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#761]
@botturam e @viniciusandrade quando pesquiso na interface de busca da COVID/WHO (https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov) obtenho os seguintes resultados para as buscas:

title,abstract,subject   <sem expressão de busca>   =>   497.168 documentos
title,abstract,subject     health                                   =>   147.458 documentos
title,abstract,subject    NOT health                           =>     40.862 documentos      (eu esperaria  497.168 - 147.458 = 349.710 documentos)

Outro caso interessante:

title,abstract,subject  born            =>   obtenho dentre vários, o documento de id: covidwho-1693763  
title,abstract,subject  NOT born    =>  também  obtenho o documento de id: covidwho-1693763

Seriam estes dois casos um mau comportamento ou apenas um equívoco meu de interpretação do operador NOT?

Abraços.

**Comment by viniciusandrade** [comment]
@heitorbarbieri por favor lembre-se que não é possivel aplicar diretamente a sintaxe lucene/solr na interface de busca devido a adaptações realizadas para compatibilização com a forma de pesquisa do ISIS.

Desta forma  seu exemplo deveria ser:

title,abstract,subject * AND NOT health =>349.710 documentos

**Comment by botturam** [comment]
@heitorbarbieri se colocar "and not" em vez de "not" funciona bem.
