### ISSUE TITLE
Ausência do caractere de fim de linha em arquivo pipe_dup de PrePrints

### ISSUE THREAD

**Issue by ChicoLopes** [bireme/db-processing#764]
### Problema
Foi verificado que o arquivo **preprints_LIS.pipe_dup** (localizado em: _serverofi5:/bases/oai.pmh/xml.rec/similar-deduplicacao/duplicated/tmp_pp_) ao ser lido pelo mx (com o comando: _mx seq=preprints_LIS.pipe_dup "pft=v6' 'v5/" now -all >> lista_ids.seq_tmp_), tem sua última (no caso a segunda) linha ignorada.

Da execução acima obtém-se:
**ppcovidwho-3882 covidwho-656978**
Quando o esperado seria obter:
**ppcovidwho-3882 covidwho-656978
ppcovidwho-3882 grc-750756**

### Causa
Analisando o arquivo com o comando hexdump (_hexdump- C preprints_LIS.pipe_dup_), foi constatado que não existe o caractere terminador de linha (0x0A hexa, ou 012 octal) ao final do arquivo, tanto que o comando wc (_wc -l preprints_LIS.pipe_dup_) informa que só há uma linha no arquivo.

**Obtido em análise**:
_hexdump -C preprints_LIS.pipe_dup_
00000000  4c 49 53 7c 4c 49 53 7c  31 2e 30 7c 49 47 4e 4f  |LIS|LIS|1.0|IGNO|
00000010  52 45 7c 63 6f 76 69 64  77 68 6f 2d 36 35 36 39  |RE|covidwho-6569|
00000020  37 38 7c 70 70 63 6f 76 ...
...  20 4c 69 62 72 61 72 79  |ectronic Library|
00000ba0  20 4f 6e 6c 69 6e 65 7c  31 2e 30 7c 53 49 4d 49  | Online|1.0|SIMI|
00000bb0  4c 41 52 |LAR|
00000bb3
_wc -l preprints_LIS.pipe_dup_
1 preprints_LIS.pipe_dup

**Esperado**:
_hexdump -C preprints_LIS.pipe_dup_
00000000  4c 49 53 7c 4c 49 53 7c  31 2e 30 7c 49 47 4e 4f  |LIS|LIS|1.0|IGNO|
00000010  52 45 7c 63 6f 76 69 64  77 68 6f 2d 36 35 36 39  |RE|covidwho-6569|
00000020  37 38 7c 70 70 63 6f 76 ...
...  20 4c 69 62 72 61 72 79  |ectronic Library|
00000ba0  20 4f 6e 6c 69 6e 65 7c  31 2e 30 7c 53 49 4d 49  | Online|1.0|SIMI|
00000bb0  4c 41 52  **0a** |LAR.|
00000bb4
_wc -l preprints_LIS.pipe_dup_
2 preprints_LIS.pipe_dup

### Solicitação
É preciso que o programa que gera o arquivo .pipe_dup inclua o tal caractere de final de linha para o bom funcionamento do processamento do arquivo.

### Sugestão adicional
Adicionalmente **se for viável** fazer que os arquivos gerados não contenham o caractere ESPAÇO (0x20 hexa, ou 040 octal), trocando este por outro, por exemplo UNDERLINE (_), ou SINAL DE SOMA (+), coisa que favoreceria o processamento.

Exemplo:
Ao invés de:
**preprints_Web of Science.pipe_dup**
Se possível:
**preprints_Web_of_Science.pipe_dup**
ou mesmo
**preprints_Web+of+Science.pipe_dup**

**Comment by heitorbarbieri** [comment]
Resolvido em [6abf59b](https://github.com/bireme/CovidDeDup/commit/6abf59bb324c24d1d56fffe55c2f4a2322cf4bca)
