### ISSUE TITLE
coleta OAI Dante Pazzanese - nova URL de coleta

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#765]
Os dados atuais são:

COLECAO > dantepazzanese

URL_OAI > http://hdpazzanese.bluesolutions.com.br/sophia/oai/oai.asp
URL_COMPLETA > http://hdpazzanese.bluesolutions.com.br/sophia/oai/oai.asp?verb=ListRecords&metadataPrefix=oai_marcxml
DIR_SAIDA > dan-dantepazzanese
METADATAPREFIX > oai_marcxml
SISTEMA_OAI > sophia
SIGLA_3
DE_PARA > marcxml_sophia
STATUS >
ARQUIVO_CUSTOMIZACAO > 3_Customiza_SOPHIA_marcxml.sh
TRANSFORMA_XML > TransformaXML_sophia_marcxml.sh
CODIFICACAO > UTF8

A nova URL é:

Boa tarde Marcelo, tudo bem?

Você poderia tentar fazer  novamente a coleta Sophia Acervo Dante.

http://200.114.1.46:8088/SOPHIA_WEB/index.html]

Obrigada,

**Comment by ChicoLopes** [comment]
@botturam o endereço está com o número IP errado, melhor confirmar com a instituição, no URL <http://200.144.1.46:8088/SOPHIA_WEB/index.html> pude obter acesso a uma página do Sophia

**Comment by botturam** [comment]
Anna simene respondeu, enviando o novo endereço:

Desde o último contato tivemos várias mudanças na nossa TI – O Alex saiu, estou aqui com o Claudinei que em contato com o pessoal do Sophia encontrou o seguinte caminho [http://200.144.1.46:8088/sophia_web/oai/oai.asp](https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2F200.144.1.46%3A8088%2Fsophia_web%2Foai%2Foai.asp&data=05%7C01%7Cbotturam%40paho.org%7Cee7f265ce26842c32a7a08da284d0e72%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637866608711388572%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UVUk64Cs6qr6rfCHTueQFBgGmB%2B571bo%2F0%2FzGi18LJ8%3D&reserved=0)

 Você pode por favor fazer um novo teste de coleta para a BVS?

**Comment by ChicoLopes** [comment]
@botturam A coleta não operava, inicialmente porque o resumptionToken não estava sendo detectado direito e o URL estava mudando do primeiro para o segundo wget. Isso devido ao arquivo de configuração dan.cnf que estava com o item URL_OAI desatualizado (continha: http://hdpazzanese.bluesolutions.com.br/sophia/oai/oai.asp) e foi trocado para o atual URL (http://200.144.1.46:8088/sophia_web/oai/oai.asp) com isso todos os blocos estão sendo coletados como esperado.
Rodei manualmente a sequência que o Celery gerencia (coleta_oai -> pos_coleta -> pre-saneamento ->iah_like_lilacs_fi -> iahx_xml_geral_fi) e não ouve intercorrências, ao menos em nível de execução.
