### ISSUE TITLE
server IAHx - transferência de processamentos IAHx de OFI5 para OFI6

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#767]
reproduzir, em OFI6, as estruturas de diretórios em OFI5 para processamentos IAHx:

/home/javaapps/iahx-server
/bases/iahx
/usr/local/bireme
/home/users/tomcat
/etc

preparar com o usuário TOMCAT, como está em OFI5.

**Comment by ChicoLopes** [comment]
@botturam seguem ações efetuadas em OFI6

### Ajustes efetuados para o novo servidor de processamento AHx (**serverofi6**)

Uma série de ajustes e configurações tem de ser efetuados para dar condição de processamento de IAHx, conforme segue.
**1º** Prover instalação de programa adicionais
**2º** Ajuste de configurações gerais do servidor
**3º** Carregar arquivos de configuração de login de usuário
**4º** Ajustes de login de usuário
**5º** Carregar arquivos do processamento no servidor
**6º** Prover chaves públicas de autenticação

_Admitindo-se uma instalação UBUNTU SERVER_

1º **Programas adicionais a instalar**:

1. tree
2. dos2unix
3. xmlstarlet

2º **Ajuste de configurações gerais**:
_**ATENÇÃO: como root**_
- Alterar a máscara padrão do sistema (UMASK em **/etc/login.defs**) para 002, permitindo o trabalho em grupos de projeto
- Incluir o nome do próprio servidor (172.17.1.138) em **/etc/hosts** (FQSN e short-name), além de serverofi5 (172.17.1.215); basalto01 (192.168.1.210); e basalto02 (192.168.1.211)
- Criar os usuários **operacao** e **transfer**, utilizado nas tarefas de processamento (ITI faz ao montar o servidor, ou se entregar com poder de root podemos fazer nos mesmos)
- Colocar **transfer** no grupo **operacao**
- Colocar o usuário **operacao** no grupo **sudoers** 

3º **Carregar arquivo de configuração de login de usuário**:
**_Como root_**:
- Em /usr/local, criar a árvore a seguir:

> bireme/
> |
> +--- cisis
> +--- java
> +--- misc
> +--- tabs

- Carregar a árvore **bireme** do servidor anterior (serverofi5)
	Obs.: de **cisis**, levar apenas os ramos **5.7c** e **5.7e**
- sobrescrever, complementar, com os arquivos listados abaixo (encontrados no ftp.bireme.br usuário ofi, diretório ofi6):

1.  ambienteIAHx
2.  profil_here
3.  profil_iahx
4.  profil_isis
5.  profil_java
6.  profil_path

- Alterar grupo dos galhos da árvore:
	`chown -R root:operacao /usr/local/bireme/*`
- Alterar as permissões dos galhos da árvore:
	`chmod -R g+w /usr/local/bireme/*`
	`find /usr/local/bireme/*  -t d | xargs chmod -R g+sw`
- Testar logar como operacao verificando variáveis de ambiente e path etc.
**_Como operacao_**:
- Criar as árvores:
	/bases/iahx/exec/inc
	/bases/iahx/exec/logs/timex
	/bases/iahx/exec/messages
	/bases/iahx/exec/tabs
	/bases/iahx/proc/covidoms/main
	/bases/iahx/proc/covidoms/logs
	/bases/iahx/proc/covidoms/cron
	/bases/iahx/proc/mdl5/main
	/bases/iahx/proc/mdl5/logs
	/bases/iahx/proc/mdl5/cron
	/bases/iahx/proc/portal/main
	/bases/iahx/proc/portal/logs
	/bases/iahx/proc/portal/cron
	/bases/javaapps/iahx-server/bin/curl
	/bases/javaapps/iahx-server/indexes
	/bases/javaapps/iahx-server/instances/1/bin
	/bases/javaapps/iahx-server/instances/2/bin
	/bases/javaapps/iahx-server/instances/3/bin
	/bases/javaapps/iahx-server/instances/4/bin
	/bases/javaapps/iahx-server/instances/5/bin
	/bases/javaapps/iahx-server/instances/6/bin
	(as demais árvores serão trazidas após testes comprovatórios de operacao)

**_Como root_**:
- Criar link o simbólico /home/javaapps em /home/
	`ln -s /bases/javaapps /home/javaapps`

4º **Ajustes de login de usuário**:
VIDE NOTA AO FINAL DO COMENTÁRIO
- Criar um link simbólico em /etc/profile.d apontando para profil_here
	`ln -s /usr/local/bireme/misc/profil_here profil_here.sh`
- Alterar **~/.bashrc** da seguinte forma
	Alterar o alias de ll (`alias ll='ls -alF'`) para `alias ll='ls -l'`
	Acrescentar na última linha:
	`[ -s /usr/local/bireme/misc/ambienteIAHx ] && source /usr/local/bireme/misc/ambienteIAHx || true`

5º **Carregar arquivos do processamento no servidor**:
- Transferir do conteúdo da árvore **/bases/iahx/exec** de serverofi5 para serverofi6
**_de inc_**:
	clean_wrk.*.inc; (criar links simbólicok clean_wrk.index.inc e clean_wrk.mdl.inc);
	dbg_displ.inc; detporta.inc (necessita ser revisto pois as portas são padrão hoje);
	iAHx2.inc; chincada.inc; infoini.inc (criar link simbólico inff_exec.inc);
	infofim.inc (criar link simbólico infi_exec.inc); lddefault.opt.inc; lddefault.vf_conf.inc;
	lddefault.viahx.inc; lddefault.dummy.inc (criar links simbólicos: leddefault.index.inc;
	lddefault.mdl.inc; e lddefault.pinbox.inc); mhelp_opc.*.inc (provavelmente não é usado); *ambulo.inc; mhelp_trf.data.inc
**_de messages_**: 	*.txt; 
_**de tabs**_:
	*.conf; *.tab; *.rol; *.iso; *.mst; *.xrf; *.cfg; *.ord; e *.nconf
_**de exec**_:
	0-process-inbox.sh; 1-incr.sh; 1-indexar.sh; 1-index-daily.sh; 1-index-mdl.sh;
	1-index-MDL.sh; 1-indexMDL.sh; 1-index.sh; agendate.sh; an.sh; backupdata.sh;
	backupproc.sh; confcol.sh; confere.sh; cron_weekly3.sh; customchg.sh;
	enviaDados.NoMD5check.sh; enviaDados.sh; estatura.sh; IAHxmlfix.sh;
	index-weekly.sh; instancias.rol; leParametros.sh; limpa_memo.root.txt;
	md5_balance.sh; md5_destino.sh; monitoraEspaco.sh; NOTAS.txt; optan.sh;
	README; reinicia_iahx-server.sh; reinicia-server-homolog.sh; relatDOCScovid.sh;
	rsync2dbx; rsync2hm; scpidxnew2dbx; temposIDX.sh; tiraFI.sh; tool_coleta.sh;
	tool_showDOC.sh; updateConf.sh; update-index.NoOptimize.sh; update-index.sh;
	verifAtual.sh; verif_conf.sh; verificaXML_02.sh; viAHx.sh; viewFlag.sh; devnull
- Transferir do conteúdo da árvore **/home/javaapps/iah-server/indexes** de serverofi5 para serverofi6

6º **Prover chaves públicas de autenticação**:
- Implantar chaves públicas de autenticação do usuário transfer
	Criar a chave pública de autenticação do usuário transfer com o comando:
		`ssh-keygen -t rsa` (no arquivo padrão id_rsa e sem frase-passe)
	Implantar quatro chaves públicas de autenticação com o comando:
		`ssh-copy-id <user>@<servidor>`
	São as seguintes combinações a usar:
		Como transfer em serverofi6 => tranfer/serverofi6
		Como transfer em serverofi6 => transfer/serverofi5
		Como transfer em serverofi6 => transfer/basalto01
		Como transfer em serverofi6 => transfer/basalto02
- Implantar chaves públicas de autenticação do usuário operacao
	Criar a chave pública de autenticação do usuário operacao com o comando:
		`ssh-keygen -t rsa` (no arquivo padrão id_rsa e sem frase-passe)
	Implantar sete chaves públicas de autenticação com o comando:
		`ssh-copy-id <user>@<servidor>`
	São as seguintes combinações a usar:
		Como operacao em serverofi6 => operacao/serverofi6
		Como operacao em serverofi6 => transfer/serverofi6
		Como operacao em serverofi6 => operacao/serverofi5
		Como operacao em serverofi6 => transfer/serverofi5
		Como operacao em serverofi5 => operacao/serverofi6
		Como operacao em serverofi6 => transfer/basalto01
		Como operacao em serverofi6 => transfer/basalto02
--- FIM ---

### NOTAS: No UBUNTU a sequência de login é a seguinte
1º /etc/profile
	a. /etc/bash.bashrc
	b. /etc/bash_completion
2º executar arquivos '.sh' presentes em /etc/profile.d
3º ~/.profile
4º ~/.bashrc
	a. ajuste do sinal de prontidão
	b. incorporar se existirem:
		i. ~/.bash_aliases
		ii. /usr/share/bash-completion/bash_completion
		iii. /etc/bash_completion

**Comment by ChicoLopes** [comment]
@botturam após um período de uso e baterias de testes de indexação de diversas instânciasé possível afirmar que se houverem problemas serão absolutamente pontuais e o desempenho do servidor tende a ser supeior que o de OFI5, no entanto pouco superior.
Não houveram ajustes posteriores relevantes a serem relatados.
Próximo ponto de atenção será a transferência de resultados para servidores front-end (basaltos 01 e 02) sem expectativa de melhora de desempenho.

**Comment by ChicoLopes** [comment]
@bottura o processamento IAHX de portal e de medline operam corretamente desde o inciio de outubro.
