### ISSUE TITLE
ODS3 Meta 3.6 Reduzir as mortes e traumatismos por acidentes de trânsito: Resposta pos-acidente

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#777]
[3.6 Resposta pos-acidentes.txt](https://github.com/bireme/db-processing/files/8592315/3.6.Resposta.pos-acidentes.txt)

**Comment by botturam** [comment]
proc. concluído.

**Comment by botturam** [comment]
https://paho.sharepoint.com/:x:/r/sites/BIR/TC/_layouts/15/Doc.aspx?sourcedoc=%7B72AD4E35-E72B-4171-9072-D14FA20447D5%7D&file=Traducao-labels.xlsx&action=default&mobileredirect=true&cid=f6123fc0-fabc-469a-a54a-c75358f0e0fd
