### ISSUE TITLE
ODS3 Meta 3.7 Universal access to sexual and reproductive health-care services:Family planning

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#780]
[3.7 Family planning and infertility services.txt](https://github.com/bireme/db-processing/files/8595268/3.7.Family.planning.and.infertility.services.txt)

**Comment by botturam** [comment]
proc. concluído.

**Comment by botturam** [comment]
https://paho.sharepoint.com/:x:/r/sites/BIR/TC/_layouts/15/Doc.aspx?sourcedoc=%7B72AD4E35-E72B-4171-9072-D14FA20447D5%7D&file=Traducao-labels.xlsx&action=default&mobileredirect=true&cid=f6123fc0-fabc-469a-a54a-c75358f0e0fd
