### ISSUE TITLE
Criar novo projeto no Celery para FI BIMENA

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#781]
Criar novo projeto no Celery para FI BIMENA (Honduras), com as tarefas de /bases/lilG4/shs.lil/_bimena.sh

OBS: a coleta do FI-ADMIN (filtraDBs.sh) já está funcionando com o parâmetro BIMENA. 

Seguir os passos da FI SDG.

Arquivos coletas.tab e coletasXML-IAHx.tab já estão configurados ("bim")

**Comment by ChicoLopes** [comment]
@botturam a tarefa **BIM.tasks.all**, está cadastrada no Celery sob o nome **BIMENA - FI-ADMIN**, e agendada para execução de segunda a sexta-feira às **13:30**
Qualquer alteração de agendamento é só avisar que efetuo.

**Comment by ChicoLopes** [comment]
@botturam já ocorreu uma execução com sucesso do processamento BIM que já desitou o XML em /bases/iahx/xml-inbox/regional/ às 13h48 com apróx 12Mbytes e 5533 documentos no arquivo.
