### ISSUE TITLE
Atualizar processo de indexação das fontes SOFs e POEMS

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/db-processing#784]
@botturam conforme informado em nossas reuniões semanais foi realizada a migração das fontes SOF e POEMS para nova instância do WP com nova URL.

Favor verificar se é somente alterar a URL no processo de coleta destas fontes ou se é necessário algum ajuste adicional nesta nova instância.

nova url: https://aps-repo.bvs.br/

A @alvesmarilda já registrou novos conteúdos nesta nova instância então quando for ajustado o processamento favor informar por aqui para que ela possa validar.

Obrigado.

**Comment by botturam** [comment]
chamada wget de coleta:

wget --no-check-certificate -O BLOCO "https://aps-repo.bvs.br/?feed=iahx&ct=sof-pearl&post_type=aps&db=SOF&la=pt&type=perg_resp&count=300&offset=0" --user-agent="Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1"

**Comment by viniciusandrade** [comment]
@wilsonmoura precisamos do seu apoio neste tema. Note que a url de coleta utilizada pelo OFI esta usando feed=iahx que provavelmente se trata de algum plugin ou ajuste realizado por nós na instância APS. 

Agradeço, quando possível, verificar se possui o histórico deste tema e nos auxiliar em implementar este ajuste na instância de repositório.

Obrigado

**Comment by viniciusandrade** [comment]
@botturam ambiente atualizado com o plugin que era responsável em exportar os conteúdos com os campos necessários para indexação.

Favor realizar nova tentativa de coleta e indexação dos conteúdos.

Obrigado

**Comment by botturam** [comment]
disponível em produção.
