### ISSUE TITLE
ODS3 Meta 3.7 Universal access to sexual and reproductive health-care services: Sexual health and reproductive rights

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#785]
https://bvsalud.org/queries/search_strategy/ods-3-meta-3-7-acesso-universal-aos-servicos-de-saude-reprodutiva-saude-sexual-e-direitos-reprodutivos/?l=en_US&se=%
https://bvsalud.org/queries/search_strategy/ods-3-meta-3-7-acesso-universal-aos-servicos-de-saude-reprodutiva-saude-sexual-e-direitos-reprodutivos/?l=es_ES&se=%
https://bvsalud.org/queries/search_strategy/ods-3-meta-3-7-acesso-universal-aos-servicos-de-saude-reprodutiva-saude-sexual-e-direitos-reprodutivos/?l=pt_BR&se=%

**Comment by botturam** [comment]
proc. concluído.
