### ISSUE TITLE
Migração das IAHx menores -- atuais portas 1 e 2  em OFI5 -- para OFI6

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#786]
- bioetica
- haiti
- bivipsil
- bvsvet
- cvsp
- dss
- sde
- panamazonica
- binacis

**Comment by ChicoLopes** [comment]
@botturam na sexta-feira passada (20/05) bioética foi implantada com sucesso em OFI6. Na manhã de hoje cvsp foi implantada e testada. Ambas estão retornando o número esperado de documentos na busca.

**Comment by ChicoLopes** [comment]
@botturam entre ontem e hoje já foram migrados e passaram por uma execução teste com resultados 100% os seguintes IAHx:
- bvsvet
- bivipsil
- binacis
- sde
- dss
Todos os já migrados estão agendados em crontab como segue:
01 22 * * 1-5 /bases/iahx/exec/cron_weekly3.sh covidwho
00 04 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bioetica
25 05 * * 1-5 /bases/iahx/exec/cron_weekly3.sh cvsp
47 04 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bivipsil
05 05 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bvsvet
40 05 * * 1 /bases/iahx/exec/cron_weekly3.sh dss
10 06 * * 1 /bases/iahx/exec/cron_weekly3.sh sde
20 03 * * 1-5 /bases/iahx/exec/cron_weekly3.sh binacis

O IAHx panamazonica está passando por uma execução teste  agora no período da tarde.
Em seguida a fazer este comentário concluo a migração de haiti e já disparo uma execução teste

**Comment by ChicoLopes** [comment]
@botturam concluídas as migrações dos nove (09) IAHx relacionados neste assentamento. Abaixo um resumo consolidado do estado de coisas.

Instancias migradas (11): binacis; bioetica; bivipsil; bvsvet; covidwho; cvsp; dss; h1n1; panamazonica; portal; sde
Todas testadas e sem apresentar erros de execução e com quantidades de documentos esperadas.
* Intercorrência: na interface Web (<http://localhost:18983/solr/index.html#/covidwho/query>) uma query por todos os documentos (*:*) está travando o meu browser, mas buscas com outras expressões, por exemplo id:* funcionam corretamente.

As instânicas migradas estão em crontab, exceto portal e h1n1, conforme a  seguir (em ordem crescente de horário):
* 20 03 * * 1-5 /bases/iahx/exec/cron_weekly3.sh binacis
* 00 04 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bioetica
* 35 04 * * 1 /bases/iahx/exec/cron_weekly3.sh haiti
* 47 04 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bivipsil
* 05 05 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bvsvet
* 25 05 * * 1-5 /bases/iahx/exec/cron_weekly3.sh cvsp
* 40 05 * * 1 /bases/iahx/exec/cron_weekly3.sh dss
* 10 06 * * 1 /bases/iahx/exec/cron_weekly3.sh sde
* 07 07 * * 1 /bases/iahx/exec/cron_weekly3.sh panamazonica
* 01 22 * * 1-5 /bases/iahx/exec/cron_weekly3.sh covidwho

Os tempos de indexação incluíndo a execução de MarkAbstract são os seguintes (mesma ordem que a lista anterior):
* binacis    00:08:19 (00:06:13)
* bioetica    00:11:53 (00:24:17)
* haiti    05:03:27 (05:10:39)
* bivipsil    00:03:16 (00:03:06)
* bvsvet    00:43:37 (00:51:10)
* cvsp    00:03:38 (00:05:35)
* dss    00:58:35 (02:01:46)
* sde    01:31:10 (01:36:08)
* panamazonica    03:07:38 (02:29:05)
* covidwho    03:06:13 (04:08:48)
* h1n1    00:14:10 (00:13:55)
* portal    14:31:54 (09:15:26)

Obs1: valores entre parenteses são os obtidos nas últimas  execuções em OFI5
Obs 2: o valor de portal não é comparável, pois não há histórico de marcação para redução de tempo de execução

Os espaços em disco ocupados pelos XML preparados para indexação são equivalentes aos observados em OFI5
