### ISSUE TITLE
Levantamento de registros com o link hist.library.paho.org

### ISSUE THREAD

**Issue by suelisuga** [bireme/db-processing#787]
Solicitamos levantamento de registros que tenham o link hist.library.paho.org no campo endereço eletrônico.

Foi identificado que links estão quebrados e será necessário revisão desses links.

Outro ponto a considerar é que esses registros não aparecem no Portal Regional da BVS, apesar de PAHO IRIS estar coleção.

Exemplos:

Asistencia técnica para el desarrollo económico / Technical assitance for economic development
Washington, D.C; Oficina Sanitaria Panamericana; 1950. 50p (OSP/CD4/PP7).
Monografia em Es | PAHO | ID: pah-192423
Biblioteca responsável: US1.1
link correto: https://iris.paho.org/bitstream/handle/10665.2/4480/47780.pdf?sequence=1&isAllowed=y

Informe del director sobre los acuerdos celebrados entre los Gobiernos y la Oficina Sanitaria Panamericana para servicios técnicos y de asesoramiento
Washington, D.C; Oficina Sanitaria Panamericana; 1950. 7p (OSP/CD4/AFL7).
Monografia em Es | PAHO | ID: pah-192434
Biblioteca responsável: US1.1
link correto: https://iris.paho.org/bitstream/handle/10665.2/4478/47778.pdf?sequence=1&isAllowed=y

CD4.R9 : Asistencia técnica para el desarrollo económico
Washington, D.C; Oficina Sanitaria Panamericana; set. 1950. 1 p. (CD4.R9 Es).
Monografia em Es | PAHO | ID: pah-47152
Biblioteca responsável: US1.1
link correto: https://iris.paho.org/bitstream/handle/10665.2/1777/CD4.R9sp.pdf?sequence=2&isAllowed=y

**Comment by suelisuga** [comment]
@botturam não são apenas esses 3. É necessário pesquisar no XML todos os que tem hist.library.paho.org, pois devem estar com o link quebrado.

No pedido acima, solicitamos uma lista para realizarmos a verificação.

Obrigada

**Comment by botturam** [comment]
@suelisuga realmente são muitos... milhares. Segue lista anexa.

Acho que vou excluir esses links da base, até decidirmos o que fazer.

[hist.library.paho.org.txt](https://github.com/bireme/db-processing/files/8894059/hist.library.paho.org.txt)

**Comment by suelisuga** [comment]
@botturam penso que se não há como recuperar a base de dados, **melhor excluir** senão quando o usuário entrar no registro, não vai encontrar o conteúdo linkado.

Talvez verificar com Eliane Santos né?

Obrigada

**Comment by botturam** [comment]
links do domínio  "http://hist.library.paho.org/" retirados das FIs:

PAHO - antiga base PAHO, proveniente de LILDBI, atualmente congelada. (19.899 docs)
PAHOIRIS - atual DSpace (4.458 docs)

**Comment by botturam** [comment]
foi estendido para todas as bases de dados.

**Comment by suelisuga** [comment]
@Bottura, Marcelo ***@***.***> showw! Muitíssimo obrigada!

Sueli Mitiko Yano Suga

Supervisora

Fontes de Informação Referenciais|Produção de Fontes de Informação

Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde - BIREME

OPAS/OMS | Tel +55 11 5576-9831 VOIP 44831

<http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>

[cid:3d1114bc-4c5a-4ee5-aad5-9c12308c27ec]
________________________________
De: botturam ***@***.***>
Enviado: martes, 28 de junio de 2022 10:38
Para: bireme/db-processing ***@***.***>
Cc: Suga, Sueli Mitiko Yano (BIR) ***@***.***>; Mention ***@***.***>
Asunto: Re: [bireme/db-processing] Levantamento de registros com o link hist.library.paho.org (Issue #787)


foi estendido para todas as bases de dados.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F787%23issuecomment-1168738528&data=05%7C01%7Csugasuel%40paho.org%7C55755b8b851e4aa37ebd08da590b8671%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637920203288438203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I7WCi9s8kk05vpN4ceSr%2Bsn1%2BvPcqNcHH7MuFKbWcW0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADD7UE3GDDNMQ3CN5RV6DKTVRL56LANCNFSM5WWV427Q&data=05%7C01%7Csugasuel%40paho.org%7C55755b8b851e4aa37ebd08da590b8671%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637920203288438203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=99zfCi61kT8M0J8AYXWAwPT4p%2BBPF5nT%2FP0MDr3Diys%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
concluído. Disponível em produção.
