### ISSUE TITLE
Parametrizar o uso do serviço de Similar Docs nas IAHx em geral

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#789]
o serviço de similar docs que foi desativado em IAHx-Portal, também o foi em IAHx-COVIDWHO. Seria interessante se pudéssemos indicar qual IAHx pode ou não ter o serviço disponível.

**Comment by viniciusandrade** [comment]
Parâmetro adicionado ao **config.xml**
 
```<show_similar_docs>true</show_similar_docs>```

Para o caso do Portal de Pesquisa Regional este parâmetro esta configurado para **false**  conforme solicitado pelo @heitorbarbieri devido a degradação do serviço de similares com alto número de requisições.

Favor verificar como o deve ficar para IAHx-COVIDWHO.

Obrigado
