### ISSUE TITLE
Processamento de estratégia sobre RHS para publicação de interface iAHx correspondente

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#79]
Processar, contra BVS Regional, a seguinte estratégia de busca:

`(TI:("allied health personnel" OR "health care professional" OR "health care professionals" OR "healthcare professional" OR "healthcare professionals" OR "health professional" OR "health professionals" OR "health manpower" OR "health personel" OR "health personnel" OR "health science manpower" OR "health workforce" OR "healthcare worker" OR "healthcare workers" OR "health care worker" OR "health care workers" OR "health worker" or "health workers" or "medical personnel" or "pessoal médico" or "personal médico" OR "medical team" OR "equipe de saúde" or "equipes de saúde" or "equipo de salud" or "equipos de salud" or "health team" or "equipe médica" or "equipo medico" or "nursing staff" or "medical staff" or "hospital staff" OR "hospital personnel" or "hospital team" OR "personal de salud" OR "personal en hospital" OR "personal en hospitales" or "pessoal de hospital" OR "pessoal de saude" or "pessoal da saude" OR "pessoal tecnico de saude" OR "profissionais da saude" or "profissionais de saude" OR "profissional da saude" or "profissional de saude" or "profissionais da atenção primária" OR "profissional da atenção primária" or "tecnicos en salud" or "tecnicos de salud" OR "trabajador de salud" OR "trabalhador da saude" OR "trabalhador de saude" OR "trabalhadores da saude" OR "trabalhadores de saude" OR "health worker" OR "health workers" OR "health employee" or "health employees" OR "medical workforce" or "nursing workforce" or "primary care workforce" or "health care workforce" or "healthcare workforce" or "força de trabalho medica" or "fuerza de trabajo medica" or "força de trabalho em enfermagem" or "fuerza de trabajo en enfermeria" or "força de trabalho de enfermagem" or "força de trabalho em saúde" or "fuerza de trabajo en salud" or "health labor force" or "nursing labor force" or "recursos humanos em enfermagem" or "recursos humanos em saúde" or "recursos humanos en enfermeria" or "recursos humanos en salud" or "nursing human resources" or "health human resources" or physician? or medico? or "nursing personnel" or "pessoal de enfermagem" or "pessoal da enfermagem" or "personal de enfermería" or "trabalhadores de enfermagem" or "trabalhadores da enfermagem" or "trabalhador de enfermagem" or "trabalhador da enfermagem" or "trabajadores de enfermería" or "trabajador de enfermería" or "nursing workers" or "nursing worker" or "tecnico de enfermagem" or "auxiliares de enfermagem" or "auxiliares de enfermeria" or "tecnico de enfermeria" or "allied nursing personnel" or "nursing technicians" or "Nurse Practitioner" or nurse? or enfermeir* or enfermer* or (observator* and ("recursos humanos" or "human resources" or rrhh or rrhhss or rh or rhs) and (saude or salud or health)) or "INOVA SUS" OR "MORE DOCTORS PROGRAM" OR "MORE PHYSICIANS PROGRAM" OR "MAIS MEDICOS PROGRAM" or "PET-SAUDE" OR "PRO RESIDENCIA" OR "PROGRAM MORE DOCTORS" OR "PROGRAMA MAIS MEDICOS" OR "PRO-SAUDE" OR PROVAB OR UNASUS or "non medical staff" or paramedico? or paramedica? "medical doctor" or "medical doctors" or "enfermagem rural" or "enfermeiro rural" or "enfermeira rural" or "enfermeria rural" or "enfermero rural" or "enfermera rural" or "rural nursing" or "rural nurse" or "rural nurses") or mh:("recursos humanos de enfermagem no hospital" or "recursos humanos em hospital" or "recursos humanos em nutrição" or "recursos humanos em odontologia" or "administracao de recursos humanos" or VS3.004* or N02.360* or M01.526.485* or SP1.011.117.133* or N04.452.677*)) and not (mh:(c0* OR c1* OR c2* OR d0* OR d1* OR d2* OR E01* OR E02* OR E03* OR E04* OR E05* OR E06* OR L01* or F01* OR F02* OR F03* OR F04* OR K01.844* or N04.452.822* or V01* OR H01.770.644* OR G08* OR I01.076.201.450* OR H01.158* or M01.526.070* or N02.278*) OR animais or animal or animals or animales)`

Objetivo é criar uma instância iAHx dedicada para RHS, a qual será utilizada para executar as estratégias específicas para cada um dos temas e subtemas dentro desta temática. 

Sugestão de URL
http://pesquisa.bvsalud.org/gcrhs

**Comment by botturam** [comment]
XMLs de LILACS e MEDLINE_ANO2017 prontos. Iniciarei o processamento esta noite.

Falta configurar initial filter e apontar nova interface para SoLR5, conforme descrito no Ocomon 5301

**Comment by renatomurasaki** [comment]
@botturam encontrei um erro na estratégia, mas que não influencia no resultado. Estava faltando um "OR" entre os tokens paramedica? e "medical doctor". Por favor, atualizar procedimento.

`(TI:("allied health personnel" OR "health care professional" OR "health care professionals" OR "healthcare professional" OR "healthcare professionals" OR "health professional" OR "health professionals" OR "health manpower" OR "health personel" OR "health personnel" OR "health science manpower" OR "health workforce" OR "healthcare worker" OR "healthcare workers" OR "health care worker" OR "health care workers" OR "health worker" or "health workers" or "medical personnel" or "pessoal médico" or "personal médico" OR "medical team" OR "equipe de saúde" or "equipes de saúde" or "equipo de salud" or "equipos de salud" or "health team" or "equipe médica" or "equipo medico" or "nursing staff" or "medical staff" or "hospital staff" OR "hospital personnel" or "hospital team" OR "personal de salud" OR "personal en hospital" OR "personal en hospitales" or "pessoal de hospital" OR "pessoal de saude" or "pessoal da saude" OR "pessoal tecnico de saude" OR "profissionais da saude" or "profissionais de saude" OR "profissional da saude" or "profissional de saude" or "profissionais da atenção primária" OR "profissional da atenção primária" or "tecnicos en salud" or "tecnicos de salud" OR "trabajador de salud" OR "trabalhador da saude" OR "trabalhador de saude" OR "trabalhadores da saude" OR "trabalhadores de saude" OR "health worker" OR "health workers" OR "health employee" or "health employees" OR "medical workforce" or "nursing workforce" or "primary care workforce" or "health care workforce" or "healthcare workforce" or "força de trabalho medica" or "fuerza de trabajo medica" or "força de trabalho em enfermagem" or "fuerza de trabajo en enfermeria" or "força de trabalho de enfermagem" or "força de trabalho em saúde" or "fuerza de trabajo en salud" or "health labor force" or "nursing labor force" or "recursos humanos em enfermagem" or "recursos humanos em saúde" or "recursos humanos en enfermeria" or "recursos humanos en salud" or "nursing human resources" or "health human resources" or physician? or medico? or "nursing personnel" or "pessoal de enfermagem" or "pessoal da enfermagem" or "personal de enfermería" or "trabalhadores de enfermagem" or "trabalhadores da enfermagem" or "trabalhador de enfermagem" or "trabalhador da enfermagem" or "trabajadores de enfermería" or "trabajador de enfermería" or "nursing workers" or "nursing worker" or "tecnico de enfermagem" or "auxiliares de enfermagem" or "auxiliares de enfermeria" or "tecnico de enfermeria" or "allied nursing personnel" or "nursing technicians" or "Nurse Practitioner" or nurse? or enfermeir* or enfermer* or (observator* and ("recursos humanos" or "human resources" or rrhh or rrhhss or rh or rhs) and (saude or salud or health)) or "INOVA SUS" OR "MORE DOCTORS PROGRAM" OR "MORE PHYSICIANS PROGRAM" OR "MAIS MEDICOS PROGRAM" or "PET-SAUDE" OR "PRO RESIDENCIA" OR "PROGRAM MORE DOCTORS" OR "PROGRAMA MAIS MEDICOS" OR "PRO-SAUDE" OR PROVAB OR UNASUS or "non medical staff" or paramedico? or paramedica? or "medical doctor" or "medical doctors" or "enfermagem rural" or "enfermeiro rural" or "enfermeira rural" or "enfermeria rural" or "enfermero rural" or "enfermera rural" or "rural nursing" or "rural nurse" or "rural nurses") or mh:("recursos humanos de enfermagem no hospital" or "recursos humanos em hospital" or "recursos humanos em nutrição" or "recursos humanos em odontologia" or "administracao de recursos humanos" or VS3.004* or N02.360* or M01.526.485* or SP1.011.117.133* or N04.452.677*)) and not (mh:(c0* OR c1* OR c2* OR d0* OR d1* OR d2* OR E01* OR E02* OR E03* OR E04* OR E05* OR E06* OR L01* or F01* OR F02* OR F03* OR F04* OR K01.844* or N04.452.822* or V01* OR H01.770.644* OR G08* OR I01.076.201.450* OR H01.158* or M01.526.070* or N02.278*) OR animais or animal or animals or animales)`

**Comment by renatomurasaki** [comment]
@botturam manter a atualização dessa instância semanalmente.

**Comment by botturam** [comment]
OK. Coletaremos às 2fs
