### ISSUE TITLE
IAHx SDE, DSS e Panamazônica  -  suspensão dos procs

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#790]
No momento, suspender proc. IAHx; futuramente, desativar instâncias nos servidores de produção.

Apagar todos os diretórios relativos a elas em OFI6.

**Comment by ChicoLopes** [comment]
@botturam Os diretórios de dados e de processamento referentes a **sde**; **panamazonica**; e **dss** foram eliminados e seus agendamentos apagados de crontab.

Com a finalidade de consolidar informações as instâncias de IAHX referentes a:

- binacis
- bioeticaediplomacia
- bivipsil
- bvsvet
- covidwho
- cvsp
- h1n1
- haiti

permanecem  sob a àrvore de dados solr5-port3 e de processamento _/bases/iahx/proc_, muito embora a chamada agendada de haiti esteja comentada e não eliminada por não constar deste issue, havendo um 'modelo' de instância denominado **like-portal** disponível apenas na árvore de dados (_/home/javaapps/iahx-server/indexes/solr5-port3_) para fins de replicação de eventuais novas instâncias a serem implamntadas.

**Comment by botturam** [comment]
retirada a geração de XMLs em tabs/coletasXML-IAHx.tab (suprimidas as linhas com dss, sde e PanAmazonica

OFI6 já não tem qualquer menção a esses processamentos.

**Comment by botturam** [comment]
cocnluído.
