### ISSUE TITLE
IAHx menores - migração interna de instâncias em Basalto01, das portas 1 e 2  para 3.

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#793]
já estamos povoando a porta 3, em Basalto01, com os procs. IAHx de:

OFI6:indexes/solr5-port3:

drwxrwsr-x 4 operacao operacao 4096 Jun 6 03:29 binacis
drwxrwsr-x 5 operacao operacao 4096 Jun 6 04:12 bioeticaediplomacia
drwxrwsr-x 4 operacao operacao 4096 Jun 6 04:50 bivipsil
drwxrwsr-x 4 operacao operacao 4096 Jun 6 05:50 bvsvet
drwxrwsr-x 4 operacao operacao 4096 Jun 6 05:28 cvsp
drwxrwsr-x 4 operacao operacao 4096 May 23 13:20 h1n1
drwxrwsr-x 4 operacao operacao 4096 May 24 11:06 haiti

"covidwho" já está funcionado na porta 3... poderia apontar essas instâncias acima para a mesma porta 3 do "covidwho"?

**Comment by botturam** [comment]
@viniciusandrade as IAHx menores abaixo, que estavam nas portas 1 e 2 do Basalto01, e agora estão na porta 3 (/home/javaapps/iahx-server/indexes/solr5-port3), ainda não foram reapontadas para o lugar certo.

operacao@OFI6:/home/javaapps/iahx-server/indexes/solr5-port3 $ ll
total 40
drwxrwsr-x 4 operacao operacao 4096 Jul 15 03:29 binacis
drwxrwsr-x 5 operacao operacao 4096 Jul 15 04:12 bioeticaediplomacia
drwxrwsr-x 4 operacao operacao 4096 Jul 15 04:50 bivipsil
drwxrwsr-x 4 operacao operacao 4096 Jul 15 05:51 bvsvet
drwxrwsr-x 4 operacao operacao 4096 Jul 15 02:30 covidwho
drwxrwsr-x 4 operacao operacao 4096 Jul 15 05:28 cvsp

Você poderia verificar, por favor? Como paramos de fazer IAHx em 15 de junho em OFI5, desde então não são mais atualizadas.

**Comment by botturam** [comment]
@viniciusandrade mapeei as IAHx que precisam continuar sendo apontadas (3 delas, eu não sei o que são), pois existem índices SoLR3 em Basalto01. 

Feito o apontamento adequado, podemos virar os índices SoLR3 para SoLR5 na porta 3 (solr5-port3) :

boletim    ?
h1n1       https://pesquisa.bvsalud.org/h1n1
iahlinks   ?
leisref    https://pesquisa.bvsalud.org/leyes
medlist    ?
unifesp    https://pesquisa.bvsalud.org/unifesp/

**Comment by marcoslmori** [comment]
para o iahx de leyes e portal de legislación foi marcado uma reunião na Quarta-feira ,em 10/08/2022 14:30 – 15:30 para tomar a decisão de desabilitar as instancias

**Comment by viniciusandrade** [comment]
@botturam realizei ajustes no módulo de controle para contemplar a situação descrita na parte de configuração.

Para os índices menores que foram atualizados para solr5-port3 (binacis, bioeticaediplomacia, bivipsil, bvsvet, cvsp)  fiz os seguintes ajustes no ambiente de testes no arquivo config.xml

```
<site>binacis</site>   -->   <site>solr/binacis</site>
<search_server>srv.bvsalud.org</search_server> --> <search_server>https://srv.teste.bvsalud.org</search_server>
<name>main</name>  -->  <!--name>main</name-->

```

E para os índices de legado (h1n1, medlist, unifesp) fiz os seguintes ajustes no ambiente de testes no arquivo dia-config.xml

```
<search_server>srv.bvsalud.org</search_server>  --> <search_server>srv.teste.bvsalud.org</search_server>
```

A ideia agora é verificar se esta alterações causaram algum efeito colateral no ambiente de testes e caso esteja tudo OK realiazar os ajustes em produção.

Agradeço, quando possível avaliar e informar problemas encontrado.

Obrigado.

**Comment by viniciusandrade** [comment]
@botturam para o ambiente de teste já estão todas apontando para o ambiente novo de processamento (OFI6).

No ambiente de produção (basalto01) a estrutura de diretórios esta incompleta e os por isso índices não estão ativos, quando a estrutura da produção estiver OK me informe para que eu possa fazer um novo teste.

Obrigado

**Comment by ChicoLopes** [comment]
@botturam @viniciusandrade a estrutura de diretórios dos índices já foram completados, são eles:

- binacis;
- bioeticaediplomacia;
- bivipsil;
- bvsvet; e
- cvsp

Agora todos contam com o arquivo core.properties e a árvore conf em basalto01 consonante a serverofi6

**Comment by viniciusandrade** [comment]
Obrigado @ChicoLopes, vou tentar amanhã realizar o reapontamento destas intâncias e aviso por aqui o resultado.

**Comment by viniciusandrade** [comment]
@botturam @ChicoLopes instâncias de produção apontando para a solr5-port3 na basalto01.

Estarei acompanhando na próxima semana o uso desta nova versão do controlador que permitiu fazer este apontamento, caso não identifique nenhum problema estarei fechando o issue por aqui.

Qualquer problema identificado favor reportar. 

Obrigado.

**Comment by botturam** [comment]
Comentei os procs de IAHx-SoLR3-OFI5 em crontab-TOMCAT

# demais IAHx - SoLR3 - comentado em 30/ago/2022
#00 04 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bioetica
#47 04 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bivipsil
#05 05 * * 1-5 /bases/iahx/exec/cron_weekly3.sh bvsvet
#25 05 * * 1-5 /bases/iahx/exec/cron_weekly3.sh cvsp
#20 03 * * 1-5 /bases/iahx/exec/cron_weekly3.sh binacis

**Comment by viniciusandrade** [comment]
Fechando este issue pois não foram encontrados problemas com o re-apontamento.
