### ISSUE TITLE
DeCS 2022 - atualização e distribuição dos insumos do DeCS

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#795]
Link para a documentação deste processo no sharepoint: [https://bit.ly/2TivjvO](https://bit.ly/2TivjvO)
----------

### Processamento do novo DeCS e disponibilização dos insumos para as atualizações dos demais serviços 

1. Vinicius

- [x] iAHX analisadores (atualizar em instances /home/javaapps/iahx-server/instances/?/resources)
- [x] iAHx controller (para interface de busca)
- [x] DeCS Autocomplete (serviço que permite a busca rápida de termos usado no FI-ADMIN e Pesquisa)

2. Todos em OFI5 (coleta FI-Admin, MarkAbstract, etc.)
Utiliza no $TABS da serverofi5 o decs.id e decs.{mst,xrf}
- [ ] MarkAbstract
 
3. Marcelo
- [ ] dcs_regional - aguardando pronto em /bases/iahx/xml-inbox/decs/wait, é só mover para ..
- [ ] Atualizar processo de coleta FI-Admin
- [ ] serverofi5:/bases/fiadmin/consolida/tpl/Atualiza_DeCS_ANUAL.sh
- [ ] FI-Admin - o diretório VMX deverá ser copia para dolomita11 ou para o bases??? - verificar diretório (PERGUNTAR PARA VÍNICIUS)
	
4. Wilson
Virada do portal DeCS Teste para Portal DeCS Produção 
- [x] base congelada
- [x] índice SoLR
- [x] se necessário, gerar cache do portal

5. Heitor
Utiliza no $TABS da serverofi5 o decs.id e decs.{mst,xrf}
- [x] BVS-InfoButton
- [x] DeCSHighlighter
- [x] SimilarDocs
- [x] e-BlueInfo

6. Ana Kátia
- [ ] Lildbi WEB (migração)

**Comment by heitorbarbieri** [comment]
@botturam  por favor, poderia atuallzar a versão do DeCS nos $TABS? A versão que está lá é de 6 de agosto de 2021. Obrigado.

**Comment by viniciusandrade** [comment]
@botturam OK, obrigado por confirmar ... melhor centralizarmos toda a comunição por aqui mesmo.

**Comment by botturam** [comment]
@heitorbarbieri liberado em $TABS

Utiliza no $TABS do serverofi5 o decs.id e decs.{mst,xrf}
  - BVS-InfoButton
  - DeCSHighlighter
  - SimilarDocs
  - e-BlueInfo
  - MarkAbstract

Heitor bom dia,

O DeCS 2022 foi atualizado e está disponível nova versão em serverofi5:/usr/local/bireme/tabs

decs.mst
decs.xrf
decs.id

**Comment by botturam** [comment]
@wilsonmoura 

Virada do portal DeCS Teste para Portal DeCS Produção 
    - base congelada
    - índice SoLR
    - se necessário, gerar cache do portal

**Comment by botturam** [comment]
@botturam  atividades realizadas:

3o. Marcelo
  - dcs_regional - aguardando pronto em /bases/iahx/xml-inbox/decs/wait, é só mover para ..
  - Atualizar processo de coleta FI-Admin
		serverofi5:/bases/fiadmin/consolida/tpl/Atualiza_DeCS_ANUAL.sh
  - FI-admin - o diretório VMX deverá ser copiado para dolomita02

**Comment by viniciusandrade** [comment]
@botturam DeCS atualizado nas instâncias de processamento da serverofi5 (portas em instances /home/javaapps/iahx-server/instances/?/resources).
* Necessário realizar o restart do serviço do iahx em cada uma das portas.

Para serverofi6 também foi atualizado mas não tenho certeza se simplesmente reiniciando o container já é suficiente para que já considere o novo DeCS ... favor entrar em contato para verificarmos em conjunto quando possível.

**Comment by wilsonmoura** [comment]
@botturam 

4. Virada do Portal DeCS Teste para Portal DeCS Produção (Wilson)
- base congelada - **OK**
- índice SoLR - **OK**
- se necessário, gerar cache do portal - **OK**

**Comment by botturam** [comment]
@anakatiacamilo  O DeCS 2022 para o LILDBI-Web está disponível em:

serverofi5:/bases/dec.000/dec.dec/output/DeCS2022.zip

Avise se faltar algo. Na documentação   https://bit.ly/2TivjvO  sua parte é essa.

**Comment by anakatiacamilo** [comment]
@botturam, para atualizar o DeCS Espanha normalmente o dados atualizados ficam neste diretório /bases/dec.000/des.des procurei na documentação e não encontrei nada sobre o DeCS Espanha.

**Comment by botturam** [comment]
concluído em 2022
