### ISSUE TITLE
Apresentar somente o dado do campo 904 [Indexado em] no registro curto e longo/detalhado do iAHx

### ISSUE THREAD

**Issue by suelisuga** [bireme/db-processing#796]
O antigo campo base de dados [04] foi desmembrado em 3:

904 - **Indexado em** na aba Metadados
XXX - **Validar com a Metodologia LILACS** na aba Metadados
4 - **Base de dados** na aba Biblioteca

O campo 904 e 4 são utilizados para o cluster Bases de dados - OK

Porém para os registros curto e logo, os valores de 904 e 4 também estão sendo apresentados, o que não é o esperado.

O ideal seria somente apresentar dado do 904.

Exemplos:

mfn=979387
  1  "BR1.1"
  2  "biblio-1285635"
  **4  "MEDLINE"** - Não apresentar
  5  "S"
  6  "as"
  8  "^gTrue^uhttp://www.scielo.br/scielo.php?script=sci_arttext&pid=S1519-69842023000100139^ien^qphp^yHTM"
  9  "a"
 10  "Moni, S S^1Jazan University^2College of Pharmacy^3Department of Pharmaceutics^cJazan^pSA^k0000-0002-4860-0166"
 10  "Alam, M F^1Jazan University^2College of Pharmacy^3Department of Pharmacology and Toxicology^cJazan^pSA^k0000-0002-4716-8658"
 10  "Sultan, M H^1Jazan University^2College of Pharmacy^3Department of Pharmaceutics^cJazan^pSA^k0000-0002-1389-1899"
 10  "Makeen, H A^1Jazan University^2College of Pharmacy^3Clinical Pharmacy Department^cJazan^pSA^k0000-0002-1078-2478"
 10  "Alhazmi, H A^1Jazan University^2Substance Abuse and Toxicology Research Centre^cJazan^pSA^k0000-0002-9647-9006"
 10  "Mohan, S^1Jazan University^2Substance Abuse and Toxicology Research Centre^cJazan^pSA^k0000-0003-2077-1278"
 10  "Alam, Md. S^1Jazan University^2College of Pharmacy^3Department of Pharmaceutical Chemistry^cJazan^pSA^k0000-0001-9127-5023"
 10  "Rehman, Z Ur^1Jazan University^2College of Pharmacy^3Department of Pharmaceutical Chemistry^cJazan^pSA^k0000-0002-6540-7966"
 10  "Jabeen, A^1Jazan University^2College of Pharmacy^3Department of Pharmaceutics^cJazan^pSA^k0000-0001-5111-1964"
 10  "Sanobar, S^1Jazan University^2College of Pharmacy^3Department of Pharmacognosy^cJazan^pSA^k0000-0002-7117-6869"
 10  "Elmobark, M E^1Jazan University^2College of Pharmacy^3Department of Pharmaceutics^cJazan^pSA^k0000-0003-0546-6697"
 10  "Siddiqui, R^1Jazan University^2College of Pharmacy^3Department of Pharmacology and Toxicology^cJazan^pSA^k0000-0001-7299-6941"
 10  "Anwer, T^1Jazan University^2College of Pharmacy^3Department of Pharmacology and Toxicology^cJazan^pSA^k0000-0002-3211-1886"
 12  "Spectral analysis, in vitro cytotoxicity and antibacterial studies of bioactive principles from the leaves of Conocarpus lancifolius, a common tree of Jazan, Saudi Arabia^ien"
 12  "An▒lise espectral, citotoxicidade in vitro e estudos antibacterianos de princ▒pios bioativos das folhas de Conocarpus lancifolius, uma ▒rvore comum de Jazan, Ar▒bia Saudita^ipt"
 14  "^ee244479"
 30  "Braz. j. biol"
 31  "83"
 35  "1519-6984"
 38  "^btab"
 38  "^bgraf"
 40  "en"
 64  "2023"
 65  "20230000"
 67  "BR"
 72  "27"
 83  "Abstract The objective of the present study was to analyse the bioactive compounds of the leaves of Conocarpus lancifolius (C. lancifolius). The GC-MS analysis of the hot methanolic extract of the leaves (HMEL) of C. lancifolius exhibited the bioactive compounds such as 1-(3-Methoxy-2-nitrobenzyl) iso quinoline, morphin-4-ol-6,7-dione, 1-bromo-N-methyl-, phytol, hexadecanoic acid, 2,3-dihydroxypropyl ester, 2,2':4',2"-terthiophene, ethyl iso-allocholate, caryophyllene oxide, campesterol, epiglobulol, cholestan-3-ol, 2-methylene-, (3▒,5▒)-, dasycarpidan-1-methanol, acetate (ester) and oleic acid, eicosyl ester. The FT-IR analysis of HMEL of C. lancifolius showed a unique peak at 3184, 2413, 1657 cm-1 representing coumaric acid, chlorogenic acid and ferulic acid. The HMEL of C. lancifolius was actively inhibiting the proliferation of breast cancer cells MCF-7 ATCC at the concentration of 72.66 ▒ 8.21 ▒g/ml as IC50 value. The HMEL of C. lancifolius also revealed a good spectrum of activity against Gram-positive and Gram-negative bacterial cultures screened in this work. The activity observed has shown more or less similar effects against screened bacteria. However, the magnitude of potentiality was significantly lesser compared to standard ciprofloxacin disc at p&lt; 0.001 level (99% confidence intervals). Furthermore, the study demonstrating the bioactive compounds can be isolated from the leaves of C. lancifolius.^ien"
 83  "Resumo O objetivo do presente estudo foi analisar os compostos bioativos das folhas de Conocarpus lancifolius (C. lancifolius). A an▒lise por GC-MS do extrato metan▒lico quente das folhas (HMEL) de C. lancifolius exibiu os compostos bioativos como 1- (3-Metoxi-2-nitrobenzil) isoquinolina, morfina-4-ol-6,7- diona, 1-bromo-N-metil-, fitol, ▒cido hexadecanoico, 2,3-di-hidroxipropil ▒ster, 2,2 ': 4', 2 " - tertiofeno, isoalocolato de etil, ▒xido de cariofileno, campesterol, epiglobulol, colestano -3-ol, 2-metileno-, (3▒, 5▒) -, dasycarpidan-1-metanol, acetato (▒ster) e ▒cido oleico, ▒ster eicos▒lico. A an▒lise FT-IR de HMEL de C. lancifolius mostrou um pico ▒nico em 3184, 2413, 1657 cm-1 representando ▒cido cumarico, ▒cido clorog▒nico e ▒cido fer▒lico. O HMEL de C. lancifolius inibiu ativamente a prolifera▒▒o de c▒lulas de c▒ncer de mama MCF-7 ATCC na concentra▒▒o de 72,66 ▒ 8,21 ▒g / ml como valor de IC50. O HMEL de C. lancifolius tamb▒m revelou bom espectro de atividade contra culturas de bact▒rias Gram-positivas e Gram-negativas rastreadas neste trabalho. A atividade observada mostrou efeitos mais ou menos semelhantes contra bact▒rias rastreadas. No entanto, a magnitude da potencialidade foi significativamente menor em compara▒▒o com o disco de ciprofloxacina padr▒o em n▒vel de p &lt; 0,001 (intervalos de confian▒a de 99%). Al▒m disso, o estudo demonstrando os compostos bioativos pode ser isolado das folhas de C. lancifolius.^ipt"
 84  "2021-08-29"
 85  "Antibacterial^ien"
 85  "Antibacteriano^ipt"
 85  "Anticancer^ien"
 85  "Antic▒ncer^ipt"
 85  "Bioactive molecules^ien"
 85  "Folhas^ipt"
 85  "Leaves^ien"
 85  "Mol▒culas bioativas^ipt"
 85  "Multiple drug resistance^ien"
 85  "Plantas^ipt"
 85  "Plants^ien"
 85  "Resist▒ncia a m▒ltiplos medicamentos^ipt"
 87  "^d14589;^d32084"
 88  "^d12911;^d23138^s22078;^d31029;^d911^s22078"
 91  "2021-08-27T19:00:00"
 92  "import"
 93  "2022-02-11T06:47:33"
 98  "FONTE"
110  "s"
113  "p"
440  "BIOLOGIA"
721  "SAUDI ARABIA"
721  "...OTHER COUNTRIES"
721  ".  ALL COUNTRIES"
722  "ARABIA SAUDITA"
722  "...OTROS PAISES"
722  ".  TODOS LOS PAISES"
723  "AR▒BIA SAUDITA"
723  "...OUTROS PAISES"
723  ".  TODOS OS PAISES"
724  "10.1590/1519-6984.244479"
725  "Arabie saoudite"
776  "FI-ADMIN^i1285635^bLILACS"
854  "202300"
855  "00-8"
888  "^gTrue^uhttp://www.scielo.br/scielo.php?script=sci_arttext&pid=S1519-69842023000100139^ien^qphp^yHTM"
899  "1.25.0-23"
**904  "LILACS"** - OK
**904  "VETINDEX"** - OK

Resultado no iAHx:

Spectral analysis, in vitro cytotoxicity and antibacterial studies of bioactive principles from the leaves of Conocarpus lancifolius, a common tree of Jazan, Saudi Arabia / Análise espectral, citotoxicidade in vitro e estudos antibacterianos de princípios bioativos das folhas de Conocarpus lancifolius, uma árvore comum de Jazan, Arábia Saudita
Moni, S S; Alam, M F; Sultan, M H; Makeen, H A; Alhazmi, H A; Mohan, S; Alam, Md. S; Rehman, Z Ur; Jabeen, A; Sanobar, S; Elmobark, M E; Siddiqui, R; Anwer, T.
Braz. j. biol ; 83: e244479, 2023. tab, graf
Artigo em Inglês | MEDLINE, **LILACS, VETINDEX**** | ID: biblio-1285635

Obrigada!
Sueli

**Comment by suelisuga** [comment]
@botturam alguma notícia?

**Comment by botturam** [comment]
@suelisuga ficou assim:

1) se tem v904, então coloca o conteúdo dele:
if p(v904)
  then
     (|    <field name="db">|v904|</field>|/),
fi

2) caso não tenha v904, crava VETINDEX:
if a(v904) 
  then 
        '    <field name="db">VETINDEX</field>'/, 
fi,

O campo 4 não será mais considerado para a FI VETINDEX.

**Comment by botturam** [comment]
disponível em produção.

**Comment by suelisuga** [comment]
verificação realizada por @alvesmarilda! ok. Muito obrigada @botturam !
