### ISSUE TITLE
cluster Type of Study - links dos filtros/entradas do cluster Type Of Study para o Queries system

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#797]
segue anexo o excel com as informações. 

Os links são para as páginas em inglês cadastradas no Queries. Creio que qualquer idioma no qual a interface esteja, ela pode remeter sempre para o inglês no Queries.

Eu fiz uma verificação na planilha e acrescentei uma última coluna na planilha com o nome lógico de cada entrada do cluster. Se não encontrar algum favor comunicar.

[Cadastro de estrategias COVID-cluster_TypeOfStudy.xlsx](https://github.com/bireme/db-processing/files/8980472/Cadastro.de.estrategias.COVID-cluster_TypeOfStudy.xlsx)

**Comment by viniciusandrade** [comment]
Disponível em ambiente de testes:

https://pesquisa.teste.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/

**Comment by viniciusandrade** [comment]
Validado em https://github.com/bireme/Covid-19_WHO/issues/35#issuecomment-1246181994

Disponível em ambiente de produção.
