### ISSUE TITLE
Incluir novas bases no iAHx GCRHS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#80]
Incluir ColecionaSUS, BVSMINSA, BDENF, CUMED e IBECS (ordem de prioridade, considerando a necessidade de obter os documentos nao convencionais em RHS.

**Comment by botturam** [comment]
processamento iniciado. Amanhã cedo, em homologação, estará disponível. 

Pedirei ao Mori para fazer que os labels dessas FIs apareçam no cluster "db"

**Comment by botturam** [comment]
Novas FIs incluídas em GCRHS:

Base de dados
  MEDLINE (105426)
  LILACS (13186)
  WHOLIS (5229)
  PAHO (2605)
  BDENF - enfermagem (Brasil) (2215)
  CUMED (1310)
  Coleciona SUS (Brasil) (1191)
  PAHO-IRIS (1150)
  IBECS (Espanha) (649)
  BBO - odontologia (Brasil) (48)
  Repositório RHS (24)
