### ISSUE TITLE
Criar lista de backup para OFI6, nos mesmos moldes da lista backup_OFI5.lst

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#800]

**Comment by ChicoLopes** [comment]
@botturam segundo meu ponto de vista é só garantir que /etc/profile.d /usr/local/bireme participem do backup, coloquei-os na lista, mas seria útil confirmar com o MArco Miacci se os diretórios já não estão no padrão de backup.

**Comment by botturam** [comment]
@heitorbarbieri vou abrir chamado o Marco amanhã, 6f. Caso vc tenha algum interesse, por favor verifique os diretórios de backup até 18:00 de amanhã.

**Comment by botturam** [comment]
Chamado Ocomon 8630 criado para o ITI.
