### ISSUE TITLE
Nome da base de dados duplicado, porém no metadado aparece somente no 904 [Indexado em:]

### ISSUE THREAD

**Issue by suelisuga** [bireme/db-processing#807]
@botturam Metadados apresenta BDNPAR somente no 904 [Indexado em], porém registro apresenta o conteúdo duas vezes:

Exemplo: base de dados repetida

Conocimientos de puérperas del servicio de alojamiento conjunto de un hospital de alta complejidad sobre los cuidados del recién nacido en el hogar / Knowledge of puerperal in a rooming-in of a hospital of high complexity about the care of the newborn in the home
Meza Torres, Giselle Elizabeth; Agüero López, Nathalia Soledad.
Rev. cient. cienc. salud ; 3(2): [60-68], 20211200.
Artigo em Espanhol | **BDNPAR, BDNPAR** | ID: biblio-1349322

Morbimortalidad infantil en pacientes hospitalizados en un hospital de referencia. Paraguay 2018 / Pediatric morbidity and mortality in patients hospitalized in a referral hospital. Paraguay 2018
Vester, Jaime Mauricio; Delgadillo, Lorena.
Rev. cient. cienc. salud ; 3(2): [69-77], 20211200.
Artigo em Espanhol | **BDNPAR, BDNPAR** | ID: biblio-1349324

No API do FI-Admin aparece só no 904:
![image](https://user-images.githubusercontent.com/13105683/180845325-573c8e17-16f6-4d79-9cd9-b346fa6c3de6.png)

Obrigada!
Sueli

**Comment by botturam** [comment]
retirei a duplicidade do campo "db" dos registros da DBNPAR, apesar de não fazer diferença que existam repetições. No caso, por exemplo, do registro da BBO abaixo, não ocorre esse problema:

    <field name="id">biblio-1210</field>
    <field name="cc">BR186.1</field>
    <field name="lo">BR186.1</field>
    <field name="db">BBO</field>
    <field name="db">LILACS</field>
    <field name="db">BBO</field>

Sobre a BDNPAR, vamos ver o que acontece com  biblio-1349324  e   biblio-1349322

**Comment by botturam** [comment]
Concluído. Disponível em produção.
