### ISSUE TITLE
OFI7 - instalação e operação de todos os serviços JAVA disponíveis em OFI5

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#809]
@heitorbarbieri preciso que vc disponibilize os serviços JAVA em OFI7 para o OFI começar a transferir os proc.s de OFI5 para OFI7. Eu destaco, em ordem decrescente de prioridade, os diretórios abaixo, apesar de que existe mais coisa em "sbt-projects/". Tem também procs. de PPrint para BioRXIV e MedRXIV... 

Precisamos ir fazendo aos poucos, mas o que você puder ir liberando, eu e o Chico já vamos testando.

operacao@OFI5:/home/javaapps $ ll

Xml2Isis/
sbt-projects/
DeDup/
Bruma/
iahx-server/
LoadIntoMongo/
NGrams/
previousTerm/
previousTerm0/
SocialCheckLinks/

**Comment by botturam** [comment]
@heitorbarbieri arquivo de configurções do Chico:  /usr/local/bireme/misc/profil_java

Qq dúvida, fale com o @ChicoLopes

**Comment by botturam** [comment]
@heitorbarbieri a execução abaixo não funciona. Ela logo finaliza a execução sem indicar o problema.

OFI7/bases/lilG4/bvs.reg.ori $ /home/javaapps/sbt-projects/MarkAbstract/MarkAbstract3.sh /home/javaapps/sbt-projects/MarkAbstract/prefixes.txt /bases/iahx/xml-inbox/regional mdl66_regional.xml /bases/lilG4/bvs.reg.ori -deCSPath=/home/javaapps/sbt-projects/DeCSHighlighter/decs/decs

**Comment by heitorbarbieri** [comment]
O diretório /home/javaapps/sbt-projects/DeCSHighlighter/decs/decs estava vazio o que gerava o erro. Situação regularizada. Serviço voltou a funcionar normalmente.

**Comment by botturam** [comment]
concluído.
