### ISSUE TITLE
Processamentos GCRHS - Temas e subtemas

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#81]
Segue abaixo a estrutura de tema, subtema e respectiva estratégia de busca. Classificar os documentos em ambos os níveis (tema e subtema):

1. ### Gestión/administración de RHS
   1. **Gestión/administración de RHS**
   `ti:("gestão de recursos humanos" or "gestao de pessoal" or "gestao de pessoas" or "administracao de pessoal" or "administração de pessoas" or "gestión de recursos humanos" or "gestión de personal" or "gestión de personas" or "administración de personas" or "administración de personal" or "human resources management" or "gestao de competencias" or "gestión de competencias" or "gestao por competencias" or "gestión por competencias" or "management skills") or (mh:"administracao de recursos humanos" or "administracao de recursos humanos em saúde" or "administracao de recursos humanos em hospitais" or "administracao de pessoal" or "administracao de pessoal em saude")`
   1. **Gobernanza**
   `ti:(governanca or governanza or governance) or mh:(Governanza or "Tomada de Decisões Gerenciais")`
   1. **Organización de trabajo**
   `ti:((organizacao and trabalho) or (planejamento and trabalho) or (planificación and trabajo) or (planeamiento and trabajo) or (planning and (work or job or workforce)) or "work organization" or "organization of work") and not ti:"family planning"`
   1. **Desempeño**
   `mh:("Avaliação de Desempenho Profissional" or "Desempenho Profissional") or (ti:(assessment or avaliacao or evaluacion or desempenho or rendimiento or performance or appraisal) and ti:(personnel or pessoal or personal or professional* or profissional* or manpower or força or fuerza or equipe? or equipo? or team? or tecnico? or worker? or trabalhador* or trabajador* or humano? or human or medico? or physician? or doctor? or nurs* or enfermer* or enfermeir*))`
   1. **Incentivo**
   `mh:("Planos de Incentivos Médicos" or "Programa de Estímulos e Incentivos" or "Reembolso de Incentivo" or "Planos para Motivação de Pessoal") or ("Incentive Reimbursement" OR "Reembolso de Incentivo" OR "Incentive Plans" OR "Planes de Incentivos" OR "Planos de Incentivos" OR "Incentives and Benefits" OR "Estímulos e Incentivos" OR (Incentivos and beneficios) OR "Employee Incentive" OR "Planes para Motivación" OR "Planos para Motivação") or TI:(incentiv* and (trabalho OR trabajo or job OR work* OR taskforce OR "human resource" OR "recursos humanos" OR RH* or medico? or physician? or doctor? or nurse? or enfermer* or enfermeir*)) and not ti:(influenza)`
   1. **Carrera sanitaria**
   `ti:(carreira* or carrera* or career*)`
1. ### Gastos
   1. **Gastos**
   `mj:("Gastos em Saude" or "Investimentos em Saude" or "Recursos financeiros em saude" or "dotacao de recursos para cuidados de saude" or "equidade na alocacao de recursos" Or "Alocacao de recursos" or "administracao financeira" or orcamento or "Custos e analise de custos" or "Financiamento da assistencia a saude" or "controle de custos" or "financiamento da pesquisa" or "financiamento governamental" or "organização do financiamento" or "Sistemas de Financiamento da Pesquisa") OR ti:(custo? or costo? or costs or investiment* or inversion* or financiamento or financial or financing or gasto? or expenditure? or orçament* or presupuesto* or budget?)`
   1. **Salarios**
   `mh:("Salários e Benefícios") or ti:(salary or salaries or salario? or sueldo?)`
   1. **Financiamiento público en salud**
   `(mj:("Gastos em Saude" or "Investimentos em Saude" or "Recursos financeiros em saude" or "dotacao de recursos para cuidados de saude" or "equidade na alocacao de recursos" Or "Alocacao de recursos" or "administracao financeira" or orcamento or "Custos e analise de custos" or "Financiamento da assistencia a saude" or "controle de custos" or "financiamento da pesquisa" or "financiamento governamental" or "organização do financiamento" or "Sistemas de Financiamento da Pesquisa") OR ti:(custo? or costo? or costs or investiment* or inversion* or financiamento or financial or financing or gasto? or expenditure? or orçament* or presupuesto* or budget?)) and (mh:"Financiamento Governamental")`
   1. **Sindicalismo**
   `Mh:"Negociacao coletiva" or ti:("Labor Unions" OR "Organized Labor" OR "Trade union" OR "Trade Unions" OR  Syndica* OR Sindica* OR "uniao sindical" or "Unioes Sindicais" OR "union sindical" or "uniones sindicales" or "union de trabajadores" or "Uniones de Trabajadores" OR "Organizacion de trabajadores" OR "Organizacao de trabalhadores")`
   1. **Corporativismo**
   `ti:(corporativismo or corporatism or "corporação médica" or "corporación médica" or "medical corporation" or "corporacoes medicas" or "corporaciones medicas" or "medical corporations" or "corporação de profissionais" or "corporações de profissionais" or "corporaciones de profesionales" or "corporación de profesionales" or "Professional Corporations" or "Professional Corporation")`
1. ### Política de RHS
   1. **Política de RHS**
   `mh:("Políticas, Planejamento e Administração em Saúde" or "Políticas Públicas de Saúde" or "Política de Saúde" or "Formulação de Políticas" or "Reforma dos Serviços de Saúde" or "Estratégias Nacionais" or "Estratégias Mundiais") or TI:("human resources policies" OR "human resources policy" OR "politica de recursos humanos" or "politicas de recursos humanos")`
1. ### Equipes de Salud
   1. **Equipes de Salud**
   `mh:("Equipe de Assistência ao Paciente" or "Equipe de Enfermagem" or "Equipe Hospitalar de Odontologia" or "Equipe de Respostas Rápidas de Hospitais" or "Atenção Primária à Saúde/ma") or ti:((equipe? or equipo? or team) and (saude or salud or health))`
   1. **Interprofesional/interdisciplinar**
   `(mh:("Equipe de Assistência ao Paciente" or "Equipe de Enfermagem" or "Equipe Hospitalar de Odontologia" or "Equipe de Respostas Rápidas de Hospitais" or "Atenção Primária à Saúde/ma") or ti:((equipe? or equipo? or team) and (saude or salud or health))) and (ti:(interdisciplinar* or interprofessional? or interprofissiona* or interprofesional*) or ab:(interdisciplinar* or interprofessional? or interprofissiona* or interprofesional*))`
   1. **Incorporación de la tecnología en salud**
   `("Technology and Innovation" OR "Tecnología e Innovación" OR "Tecnologia e Inovação" OR "Diffusion of Innovation" OR "Difusión de Innovaciones" OR "Difusão de Inovações" OR "Innovation Diffusion" OR "Biomedical Technology" OR "Tecnologia Biomédica" OR "INOVA SUS" OR "incorporacao de tecnologias" OR "incorporacion de la tecnologia" OR "incorporacion de tecnologias" OR (ti:incorpora* ti:(technolog* or tecnologi* or innovat* or innovac* or inovac*)))`
1.  ### Sistemas de información
   1. **Sistemas de información**
   `tw:("Sistemas de Informação" or "sistema de informação" or "sistemas de información" or "sistema de información" or "information systems" or "information system") or tw:("Sistemas de comunicacao") or tw:("information technology" or "tecnologia de informaçao" or "tecnologia de información") or ti:(computer or computing or computadorizado or computaçao) or ti:("decision support" or ((soporte or suporte) and (decision or decisao)))`
   1. **Observatorios**
   `ti:(observator* and ("recursos humanos" or "human resources" or rrhh or rrhhss or rh or rhs)) or (ab:(observator* and ("recursos humanos" or "human resources" or rrhh or rrhhss or rh or rhs)))`
   1. **Gestión de conocimiento**
   `tw:("gestao de conhecimento" or "gestion del conocimiento" or "knowledge management" or "knowledge sharing" or "Gestão do Conhecimento para a Pesquisa em Saúde" or ((disseminacao or diseminacion) and (conocimiento or informac*)) or "Pesquisa Médica Translacional" or "Investigación en Medicina Traslacional" or "Translational Medical Research" or ((traducao or traduccion or translation) and (conhecimento or conocimiento or knowledge)))`

**Comment by renatomurasaki** [comment]
@botturam e @falbrito  estas estratégias devem ser aplicadas na instância iAHx gcrhs

**Comment by renatomurasaki** [comment]
@botturam e @falbrito não entendi o processamento do cluster "Temas RHS". Destaco os seguintes pontos que precisam ser esclarecidos:

1. Se aplicar a estratégia 1.i - Gestión/Administración de RHS na interface iAHx GCRHS, teremos 7.895 documentos retornados. Por que no cluster mostra apenas 232? Esta discrepância está ocorrendo em todos os clusters
1. Por que aparece Geral_subtema2 e Geral_subtema5 no cluster de Gastos? O mesmo ocorre com os demais clusters que tem mais de um Geral. Cada Tema deveria conter apenas um Geral_subtema.

O processamento destes clusters não deve ser hierárquico. Somente a visualização dos temas é hierárquica dentro do cluster. Não deve combinar as estratégias no processamento. Apenas processar estratégia a estratégia e "marcar" o registro retornado com o dado tema/subtema.

@marcoslmori aguardar análise do OFI antes de configurar o ambiente de homologação.

**Comment by botturam** [comment]
houve erro na geração dos XMLs de processamento, a respeito da paridade entre o campo de tema e o campo de subtema, que estavam, na primeira versão, em ocorrências distintas. 

Atualmente, tema e subtema (quando disponível) estão na mesma ocorrência de campo ISIS.

Processamento reiniciado.

Foi aberto o chamado Ocomon 5359, para tradução dos labels do cluster de Temas RHS.

**Comment by botturam** [comment]
Fábio,

estratégias prontas para reprocessamento de temas, segundo nova organização:

G4 serverofi5:/bases/Strategies2IAHX/apps/strategies/rhs $ ll
total 132
-rw-rw-r-- 1 operacao        operacao 3863 Dec 15 17:58 RHS-carrera_sanitaria.sch
-rw-rw-r-- 1 operacao        operacao 4218 Dec 18 15:04 RHS-corporativismo.sch
-rw-rw-r-- 1 operacao        operacao 4290 Dec 15 17:53 RHS-desempeno.sch
-rw-rw-r-- 1 operacao        operacao 4084 Dec 18 15:52 RHS-equipes_salud.sch
-rw-rw-r-- 1 operacao        operacao 4522 Dec 18 14:59 RHS-financiamiento_publico_salud.sch
-rw-rw-r-- 1 operacao        operacao 4481 Dec 18 14:56 RHS-gastos.sch
-rw-rw-r-- 1 operacao        operacao 4507 Dec 15 18:08 RHS-gestion_administracion_RHS.sch
-rw-rw-r-- 1 operacao        operacao 4267 Dec 18 16:17 RHS-gestion_conocimiento.sch
-rw-rw-r-- 1 operacao        operacao 3924 Dec 15 17:45 RHS-gobernanza.sch
-rw-rw-r-- 1 operacao        operacao 4492 Dec 15 17:54 RHS-incentivo.sch
-rw-rw-r-- 1 operacao        operacao 4286 Dec 18 15:55 RHS-incorporacion_tecnologia_salud.sch
-rw-rw-r-- 1 operacao        operacao 4269 Dec 18 15:54 RHS-interprofesional_interdisciplinar.sch
-rw-rw-r-- 1 operacao        operacao 4018 Dec 18 16:16 RHS-observatorios.sch
-rw-rw-r-- 1 operacao        operacao 4073 Dec 15 18:38 RHS-organizacion_trabajo.sch
-rw-rw-r-- 1 operacao        operacao 4202 Dec 18 15:45 RHS-politica_de_RHS.sch
-rw-rw-r-- 1 operacao        operacao 3906 Dec 18 14:58 RHS-salarios.sch
-rw-rw-r-- 1 operacao        operacao 3817 Dec 15 17:02 RHS.sch
-rw-rw-r-- 1 operacao        operacao 4163 Dec 18 15:03 RHS-sindicalismo.sch
-rw-rw-r-- 1 operacao        operacao 4267 Dec 18 16:15 RHS-sistemas_informacion.sch

**Comment by renatomurasaki** [comment]
@botturam - Melhorias na estratégia geral:

1. Incluir no TI ( ... or "human resources for health" or "human resource for health" or "recursos humanos para la salud" or or "recurso humano para la salud" or ...)
2. Incluir ... or ta:("Human Resources for Health")
3. Substituir `... or nurse* or ...` por `... or nurse or nurses or ...`

**Comment by botturam** [comment]
As 3 atualizações acima foram realizadas. Falta a revisão da estratégia RHS-educacion.sch, pela Stella.

**Comment by renatomurasaki** [comment]
@botturam Novo Eje Temático para processamento: Acceso y Cobertura Universal en Salud

`((ti:(("Universal Access" Health) OR ("Acesso Universal" Saude) OR ("Acceso Universal" Salud) OR ("Universal Coverage" Health) OR ("Cobertura Universal" (Salud OR Saude)) OR "Cobertura Sanitaria Universal") OR (ti:("Universal Health" OR "Global Health" OR "Salud Global" OR "Saude Universal") (access or acesso or acceso or equidad* OR equity or equitat*)) OR ("World Health Day" da:2018*) OR ("Alma Ata" da:2018*) OR ti:("Health for all" OR "Salud para todos" OR "Salud para todos") OR (((("Universal Access" Health) OR ("Acesso Universal" Saude) OR ("Acceso Universal" Salud) OR ("Universal Coverage" Health) OR ("Cobertura Universal" (Salud OR Saude)) OR "Cobertura Sanitaria Universal" OR (("Universal Health" OR "Saude Universal") (access or acesso or acceso or equidad* OR equity or equitat*))) OR ("Health for all" OR "Salud para todos" OR "Salud para todos")) (MJ:"Objetivos de Desenvolvimento Sustentavel" OR MJ:"Saude Global" OR MJ:"Acesso aos Serviços de Saude" OR ti:("Development Goals" OR "Development Goal" OR ODS OR SDG)) 2030)) AND NOT (MJ:C0* OR ti:(Otolaryngol* or trauma* or Radiolog*)))`

Fonte: http://bvsalud.org/2018/04/04/dia-mundial-da-saude-2018-saude-universal-para-todos-em-todos-os-lugares/

**Comment by renatomurasaki** [comment]
Encerrando issue pois todo o processamento de RHS está funcionando e agora em processo de atualização periódica.
