### ISSUE TITLE
transferência de processamentos não IAHx de OFI5 para OFI7

### ISSUE THREAD

**Issue by ChicoLopes** [bireme/db-processing#812]
Prover toda a infraestrutura necessária para a transferência dos processamentos não IAHX de OFI5, para OFI6.
Incluindo toda a configuração necessária para dar suporte aos processamentos a serem transferidos.

**Comment by ChicoLopes** [comment]
@botturam a implantação de infraestrutura de suporte aos processamentos está realizada, necessitando comprovação de presença de todas as configurações necessárias.
No documento anexado encontran-se os passos realizados até o momento sob forma de instrução de trabalho simplificada, o que inclui:

1. Proposta básica da implantação
2. Usuários a serem criados e características especiais dos mesmos
3. Itens a serem configurados
4. Implantação de chaves públicas de autenticação

[SetupUsuarioOFI7.docx](https://github.com/bireme/db-processing/files/9213397/SetupUsuarioOFI7.docx)

**Comment by ChicoLopes** [comment]
@botturam em complemento ao enviado ontem, há também o gerenciamento de permissões do diretório /home/bases que deve receber a adição de stick-bit no grupo (como root: **chmod g+s /home/bases**, ou se populado com **find /home/bases -type d | xargs chmod g+d**)

**Comment by ChicoLopes** [comment]
@bottura conferindo a iniciação de ambiente para usuário de OFI7, verifiquei junto ao Heitor a necessidade de ajustar a variável JAVA_HOME. As alterações devidas estão realizadas e a documentação (anexada a este comentário) foi atualizada na seção "Ajustes por edição de configurações.

[SetupUsuarioOFI7-rev02.docx](https://github.com/bireme/db-processing/files/9364110/SetupUsuarioOFI7-rev02.docx)
"

**Comment by ChicoLopes** [comment]
@botturam em função da feitura dos demais assentamentos de transferência de processamentos diversos, penso que este chamado esteja atendido, carecendo de seu parecer quanto a isso para ser fechado.

**Comment by botturam** [comment]
@ChicoLopes atividade concluída.
