### ISSUE TITLE
Indexação MEDLINE para LILACSExpress (FI-ADMIN) - Campos: Tipo de Publicação[71] e Pré-Cod[76]

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#815]
Segue o modelo de arquivo para a copia dos campo de indexação Tipo de publicação [71] e Pré-codificados [76]

O Campo ID[2], precisa ser o PK do FI-ADMIN - (não pode ser o LILACS Original ID)
Os campos de Tipo de publicação e Pré-cod tem que ser em inglês.

exemplos:

ID|Tipo de publicação
1|["Case Reports", "Comparative Study", "Evaluation Studies"]
2|["Evaluation Studies"]
3|["Review"]
4|["Case Reports", "Evaluation Studies", "Clinical Trial, Veterinary"]

ID|PreCod
1|["Humans", "Male", "Female", "Aged", "History, 21st Century"]
3|["Humans"]
5|["Animals", "Female", "Dogs"]

**Comment by botturam** [comment]
@anakatiacamilo @ChicoLopes estão disponíveis as listas (campos v71 (PT) e v76 (CT)) de alguns documentos de 2018, do MEDLINE, no formato indicado acima:

OFI5:/bases/mdlG4/v87.mdl/lxp_mdl18_v71_fiadmin.txt
OFI5:/bases/mdlG4/v87.mdl/lxp_mdl18_v76_fiadmin.txt

Veja se está bom para os testes. Já coloquei na rotina que gera o arquivo ISIS, no caso, lxp_mdl18.iso.

**Comment by botturam** [comment]
IMPORTANTE lembrar que no processo atual (antigo), foi solicitado que o campo 71 NÃO fosse preenchido com JOURNAL ARTICLE. Isso vai mudar?

**MEDLINE** - PMID=30540737
360  "Case Reports"
360  "Journal Article"
360  "Review"

**lxp_mdl18.iso**: ID=biblio-1014100 (para transferir)
operacao@OFI7/bases/mdlG4/v87.mdl $ mx iso=lxp_mdl18.iso text=biblio-1014100
mfn=   174
  2  "biblio-1014100"
 71  "CASE REPORTS"
 71  "REVIEW"

**Comment by anakatiacamilo** [comment]
@botturam, não muda o Tipo de Publicação JOURNAL ARTICLE não deve ser transferido, segundo a metodologia LILACS.

**Comment by anakatiacamilo** [comment]
Os scripts para a atualização deste campos foram feitos, agora preciso dos outros campos de indexão do issue #831

**Comment by anakatiacamilo** [comment]
@botturam se o registros tiver outros campos de indexação como, por favor, incluir no arquivo.
Segue os exemplos:
ID|Alcance temporal (desde)
ID|Alcance temporal (até)
ID|Indivíduo como tema
ID|Região não DeCS
ID|Instituição como tema

Lembrando que o ID tem que ser o do FI-ADMIN e não o LILACS Original ID

**Comment by anakatiacamilo** [comment]
Novo Formato

ID[v776^i]|Tipo de publicação[71]
1|["Case Reports", "Comparative Study", "Evaluation Studies"]
2|["Evaluation Studies"]
3|["Review"]
4|["Case Reports", "Evaluation Studies", "Clinical Trial, Veterinary"]

ID[v776^i]||PreCod[76]
1|["Humans", "Male", "Female", "Aged", "History, 21st Century"]
3|["Humans"]
5|["Animals", "Female", "Dogs"]

**Comment by botturam** [comment]
@anakatiacamilo favor validar os arquivos  **lxp_mdl_ALL_v76_fiadmin.txt**  e  **lxp_mdl_ALL_v71_fiadmin.txt**  com as alterações, gerados em:

OFI5:/bases/mdlG4/v87.mdl  (consolida_MDL2LIL_v71_v76.sh*):
-rw-rw-r-- 1 operacao operacao      15170 Aug 29 11:31 lxp_mdl_ALL_v71_fiadmin.txt
-rw-rw-r-- 1 operacao operacao      52669 Aug 29 11:31 lxp_mdl_ALL_v76_fiadmin.txt

- O período de match foi de mdl2010 até mdl2022. Não há nada de 2020-2022.
- Não existem linhas repetidas.

**Comment by anakatiacamilo** [comment]
Terminei o processo de troca dos campos: Tipo de publicação[71] e PreCod[76] esta no FI-ADMIN de curso verificação.
