### ISSUE TITLE
IAHx - testar e documentar o funcionamento de todos os índices de pesquisa para uso do SCI/FIR e da rede

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#816]
a ideia é explicitar a pesquisa para usuários mais avançados, com necessidades de busca mais específicas e sofisticadas.

a planilha com a documentação está em:

https://paho.sharepoint.com/:x:/s/BIR/TC/Ec39u2BLAh5PgHcYs16GG4gB0OC7Gyg8a49RZogvJHL93w?email=botturam%40paho.org&e=4%3ATqCrgK&at=9&CID=5a2f285a-d564-47a6-bfb9-e6c211a05a6d

**Comment by botturam** [comment]
@suelisuga a planilha está finalizada. Favor conferir e acrescentar comentários aqui no GITHUB, por favor.

**Comment by suelisuga** [comment]
Nota técnica atualizada: https://lilacs.bvsalud.org/guias-e-manuais/docs/filtros-de-busca-para-tipos-metodologicos-de-estudo-na-metodologia-lilacs/notas-tecnicas/02-22-campos-de-dados-da-metodologia-lilacs-utilizados-para-pesquisa-na-interface-de-pesquisa-iahx-do-portal-regional-da-bvs/

Muitíssimo obrigada @botturam
