### ISSUE TITLE
GIM - tabular quantidades de documentos totais por Revista (ta) e Tipo de Documento (type)

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#817]
excluir documentos com Data de Publicação (DP) = "2022"

**Comment by heitorbarbieri** [comment]
Para 2020 tivemos:

2,800 scientific journals
83%  journal articles

**Comment by botturam** [comment]
sobre revistas, seguem os números:

AIM (AFRO) - 495
IMEMR (EMRO) - 736
IMSEAR (SEARO) - 51
LILACS - 2.253
WPRIM - 718
---------------
total - 4.248 (sem repetidos)

**Comment by botturam** [comment]
sobre o tipo de documento (esse bateu):

2.015.593 (Sas) / 2.328.629 (total de docs) = 0,86 (86%) de Journal Article.
