### ISSUE TITLE
coleta OAI - PAHOIRIS (phr) - OFI7 

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#818]
Coleta DSpace

shell de referência:

operacao@OFI7/bases/lilG4/shs.lil $ more _phr.sh
echo "PAHO"
./coleta_oai.sh phr
./pos_coleta_oai.sh phr
./pre_saneamento_fi.sh phr
./saneamento_phr.sh phr
./iah_like_lilacs_fi.sh phr
./iahx_xml_geral_fi.sh phr

**Comment by ChicoLopes** [comment]
@botturam procedimento disparado em background exceto a fase de coleta_oai. que já estava feita.

**Comment by ChicoLopes** [comment]
@botturam a coleta (phr) previamente realizada contou com 33 registros a menos que OFI5 (OFI5 51749 x OFI7 51716), diferença que se mandeve no XML phr_regional.xml em xml-inbox/regional.

**Comment by ChicoLopes** [comment]
@botturam em /bases/lilG4/shs.lil está o shell _phr.sh que foi ajustado para poder ser executado por crontab, pel inclusão da inicialização de ambiente (profil_here e ambienteIAH), sem o que falharia. O agendamento por crontab dispara o processamento às 21:50 de segunda e sexta-feiras.

**Comment by ChicoLopes** [comment]
@botturam como reportado em mensagem pessoal por whatsapp, o processamento PHR não foi executado no horário agendado em OFI7 devido a problemas não relacionados com os shell-scripts, tendo sido reagendado para às 22:52, ocasião em que a execução foi bem sucedida, no entanto a execução em OFI5 incorreu no mesmo problema que em OFI7, não permitindo a comparação no dia de hoje.
Não obstante o processamento de OFI7 resultou mais documentos no XML de entrada de IAHX que o último disponível em OFI5, sendo esta uma indicação positiva, embora não conclusiva.

**Comment by ChicoLopes** [comment]
@botturam coleta e processamento em **serverofi7** gerou resultado **superior** a **serverofi5**, portanto processamento **Celery** em serverofi5 foi **desativado** e o agendamento por **crontab** em serverofi7 foi **efetivado**, nos termos apontados em comentário anterior.

**Comment by botturam** [comment]
@ChicoLopes vamos tirar do tabs/coletasXML-IAHx.tab, deixando só o "regional":

phr haiti|PAHOIRIS||s|s|680|04-international_org|UTF-8|phr.lil|bvs.hai|haiti
phr RIPSA|PAHOIRIS||s|s|680;681|04-international_org|UTF-8|phr.lil|bvs.rps|RIPSA

**Comment by ChicoLopes** [comment]
@botturam em 13/12 foram retiradas da tabela $TABS/coletasXML-IAHx.tab as linhas correspondentes à fonte de informação PAHO IRIS para as instâncias HAITI e RIPSA, asism sendo passa a ser gerado arquivo XML apenas para a instância regional.
