### ISSUE TITLE
coleta OAI - ARCA-FIOCRUZ - OFI7

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#819]
são 2 coletas: DIM e MODS, com 3 linhas no coletas.tabs

arca_mods       ARCA    /bases/lilG4/arc.lil    oai     ^h=^d=/bases/xml2isis/oai/tpl^l=^p=^s=^b=^c=
arca_dim        ARCA    /bases/lilG4/arc.lil    oai     ^h=^d=/bases/xml2isis/oai/tpl^l=^p=^s=^b=^c=
arc     ARCA    /bases/lilG4/arc.lil    oai     ^h=^d=/bases/oai.pmh/isis/arca^l=^p=^s=^b=LILACS^c=

tpl.oai/ARCA_process.sh

**Comment by ChicoLopes** [comment]
@botturam realizado o processamento de **ARCA** seguindo os passos de **/bases/oai.pmh/tpl.oai/ARCA_process.sh**, conforme contido em **tasks.py** do diretório **/bases/apps/ofi_django_project/ARCA** ou seja, a sequência:

- coleta_oai.sh arca_dim; 
- coleta_oai.sh arca_mods; 
- pos_coleta_oai.sh arca_dim; 
- pos_coleta_oai.sh arca_mods; 
- ARCA-junta-dim-mods.sh; 
- pre_saneamento_fi.sh arc; 
- iah_like_lilacs_fi.sh arc; e
- iahx_xml_geral_fi.sh arc

Os resutados obtidos foram:
Base "**lil**" em /bases/lilG4/arc.lil contando com **46326** registros tanto em OFI5 quanto em OFI7
XML "**arc_regional**" em /bases/iahx/xml-inbox/regional contando com **46326** "id" tanto em OFI5 quanto em OFI7

**Comment by ChicoLopes** [comment]
@botturam coleta e processamento em serverofi7 gerou resultado identico a serverofi5, portanto processamento Celery em serverofi5 foi desativado e o agendamento por crontab em serverofi7 foi efetivado, nos termos apontados em comentário anterior.
