### ISSUE TITLE
GCRHS: incluir no CSV de autor_afiliação, o autor institucional

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#82]

**Comment by renatomurasaki** [comment]
@botturam conforme falamos, melhor criar um arquivo autor_inst_afiliacao.txt contendo somente os dados de autor institucional, seguindo a mesma estrutura de dados de autor_afiliacao.txt

Pode incluir no autor_afiliacao os autores pessoais das monografias.

**Comment by renatomurasaki** [comment]
Arquivo criado e agora passamos a gerar indicadores também de autores institucionais.

**Comment by botturam** [comment]
O Autor Institucional é gerado na planilha "lilacs_Inst_Afiliacao.txt", para todas as FIs like LILACS.
