### ISSUE TITLE
Coleta OAI - binacuy/BVSNACUY (bnu) - OFI7

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#822]
aparentemente está funcionando

**Comment by ChicoLopes** [comment]
@botturam foi criado um shell-script denominado _bnu.sh nos moldes do _bcc.sh, _arca.sh, e _phr.sh para executar o processamento, e que está em teste por disparo manual, sendo que o processamento em OFI5 por Celery se dá às 2:10 às quartas-feiras.

**Comment by ChicoLopes** [comment]
@botturam o processamento de disparo manual _bnu.sh em OFI7 foi realizado com sucesso obtendo 19978 documentos semelhantemente à OFI5 que reporta 19979 documentos, sendo o último um documento de conteúdo não válido, como mostra o fragmento de XML a seguir:

&nbsp;&nbsp;&lt;/doc>
&nbsp;&nbsp;&lt;doc boost="1">
&nbsp;&nbsp;&nbsp;&nbsp;**&lt;field name="id">bnu-0&lt;/field>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;field name="cc">.^e&lt;/field>**
&nbsp;&nbsp;&nbsp;&nbsp;&lt;<field name="bvs">regional&lt;/field>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;field name="db">BVSNACUY&lt;/field>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;field name="instance">bvsnacuy&lt;/field>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;field name="collection_bvsnacuy">BINAME&lt;/field>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;field name="no_indexing">1&lt;/field>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;field name="weight">1&lt;/field>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;field name="regional_office">others&lt;/field>
&nbsp;&nbsp;&lt;/doc>
&lt;/add>

**Comment by ChicoLopes** [comment]
@botturam teste homologatório disparado em 8/12 às 11H30 finalizado com resultados positivos, coleta e processamento em **serverofi7** gerou resultado **identico** a **serverofi5,** portanto processamento **Celery** em serverofi5 foi **desativado** e o agendamento por **crontab** em serverofi7 foi **efetivado,** nos termos apontados em comentário anterior.
