### ISSUE TITLE
Coleta OAI - BUTANTAN-DSPACE (bud) - OFI7

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#823]
está funcionado. A parte do Sophia (but) não está.

**Comment by ChicoLopes** [comment]
@botturam coleta e processamento em **serverofi7 gerou resultado identico a serverofi5**, portanto processamento **Celery** em serverofi5 foi **desativado** e o agendamento por **crontab** em serverofi7 foi **efetivado**, nos termos apontados em comentário anterior.
