### ISSUE TITLE
Adaptar processamento iAHx para as fontes de Repositorio REA atualmente coletadas via OAI-PMH do CWIS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#83]
Os repositorios que serão migrados do CWIS para o FI-Admin são: Cuba, Colombia, Perú, Argentina, Costa Rica, El Salvador, CIESS/Mexico, Paraguai, México, República Dominicana e Uruguai.

O processamento precisa ser adaptado para susbstituir o XML OAI-PMH DC para XML/JSON FI-Admin.

Lembrar que estas fontes de informação estão disponíveis tanto no iAHx da BVS Regional como no iAHX do CVSP.

Melhorar o campo de resumo na visualização do regitro no iAHx para que seja a combinação dos campos Learning Objectives e Description.

**Comment by falbrito** [comment]
Processo desenvolvido no servidor SERVEROFI5.

Arquivos de processamento:
/bases/oai.pmh/tpl.oai/oer_coleta_fia.sh
/bases/oai.pmh/tpl.oai/oer_TransformaXML2Solr.sh
/bases/oai.pmh/tpl.oai/oer_leWeb_fiadmin.fnc
/bases/oai.pmh/tpl.oai/oer_DisponibilizaXML.sh
/bases/oai.pmh/tpl.oai/xsl/convert-fiadmin-solr-oer.xsl

**Comment by renatomurasaki** [comment]
@falbrito já podemos encerrar este issue ou há algo pendente?

**Comment by falbrito** [comment]
Processo colocado em linha.
