### ISSUE TITLE
Coleta OAI - FIOCRUZ (fio) - OFI7

### ISSUE THREAD

**Issue by ChicoLopes** [bireme/db-processing#830]
Coleta OAI

Coleta nos moldes definidos no cadasto FIO no Celery de serverofi5, consonante a uma linha em coletas.tab

**Comment by ChicoLopes** [comment]
O processamento FioCruz segue os passos conforme contido em tasks.py do diretório /bases/apps/ofi_djang_project/FIO de serverofi5 ou seja, a sequência:

coleta_oai.sh fio;
pos_coleta_oai.sh fio;
pre_saneamento_fi.sh fio;
iah_like_lilacs_fi.sh fio; e
iahx_xml_geral_fi.sh fio

Foi criado em _serverofi7_ um shell-script (**/bases/lilG4/shs.lil/_fio.sh**) para ser executado por agendamento crontab que carrega o ambiente de execução conforme necessário para o usuário operacao.

Os pontos de armazenamento relativos a FIOCRUZ são (todos em serverofi7):
XMLs coletados armazenados em _/bases/oai.pmh/xml.rec/fio-*/file*.xml_
Bases CDS/ISIS das coleções armazenadas em _/bases/oai.pmh/isis/fio-*/LILACS_
Base CDS/ISIS consolidada armazenada em _/bases/oai.pmh/isis/fio/fio_LILACS_
XML para uso por IAHX armazenado em _/bases/iahx/xml-index/regional/fio_regional.xml_

finalizado o processamento FIOCRUZ com a coleta das 17 coleções, quais sejam:
1. fio-ACERVOFAR      
2. fio-AROUCA         
3. fio-BVSAM          
4. fio-BVSCARGA       
5. fio-BVSDIP         
6. fio-BVSEPS         
7. fio-BVSPS          
8. fio-BVSVS          
9. fio-CESTEH         
10. fio-CLAVES         
11. fio-CPQAM          
12. fio-CPQRR          
13. fio-ENSP           
14. fio-ILMD           
15. fio-INTEGRALIDADE  
16. fio-TESESFIO       
17. fio-THESIS         

que após o processamento e consolidação apresenta **97531** documentos no arquivo XML **fio_regional.xml** em _/bases/iahx/xml-inbox/regional_, como esperado na comparação com _serverofi5_.

O cadastramento no Celery escala a execução para a 01h30 aos sábados
Em _serverofi7_ foi criada a entrada crontab para execução do processamento conforme:
**30 01 * * 6        /bases/lilG4/shs.lil/_fio.sh > /bases/logs/celery/logs/fio.out**

**Comment by botturam** [comment]
@ChicoLopes seguir o dia e horário do cadastro em contrab-OFI5 ou do Celery mesmo, para esse e os outros cadastramentos em OFI7.

**Comment by ChicoLopes** [comment]
@bottura teste homologatório disparado em 7/12 às 21h00, finalizado, com resultado em análise
