### ISSUE TITLE
Indexação MEDLINE para LILACSExpress (FI-ADMIN) - Campos: Descritores Primários[87] e Secundário [88] e 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#831]
Pode ser gerar uma arquivo isis com a seguintes informações:

Tag|Campo
2|ID-FI-ADMIN (biblio-id)
87|Descritor Primário
88|Descritor Secundário

Por favor, o mesmo conjunto de dados do Exemplo dos campos de Tipo de publicação e Pre-Cod. #815

**Comment by anakatiacamilo** [comment]
Novo formato

Tag|Campo
77^i|ID-FI-ADMIN (biblio-id)
87|Descritor Primário
88|Descritor Secundário

**Comment by botturam** [comment]
@anakatiacamilo o master file com os campos 87 e 88 também está disponível (consolida_MDL2LIL_v87_v88.sh) em:

OFI5:/bases/mdlG4/v87.mdl/lxp_mdl_8788_ALL.mst

operacao@OFI5:/bases/mdlG4/v87.mdl $ mx lxp_mdl_8788_ALL "pft=v2/" now|sort -u|wc
   1212    1212   17018

**Comment by anakatiacamilo** [comment]
terminado. registros atualizados no FI-ADMIN de curso para verificação.
