### ISSUE TITLE
Artigos publicados há meses no FI-Admin não aparecem no iAHx

### ISSUE THREAD

**Issue by AngelicaSAPaula** [bireme/db-processing#833]
Os artigos de 2022 da revista Más Vita foram publicados em junho, mas ainda não aparecem no iAHx.

Más Vita; 4 (1), 2022
Fonte #1372039

No FI-Admin há 91 registros publicados e no iAHx, só 75.

![image](https://user-images.githubusercontent.com/47643830/190035526-46d56193-c8bd-49a7-8bf7-391645d00556.png)

![image](https://user-images.githubusercontent.com/47643830/190035541-6b45dc2c-81a9-49ce-a711-dfc1ca347245.png)

![image](https://user-images.githubusercontent.com/47643830/190035641-f89c76c3-71dc-4f67-a3fd-3f0185df2eec.png)

**Comment by viniciusandrade** [comment]
@AngelicaSAPaula trasferi o issue para o projeto de processamento e estou direcionando para o @botturam e para o @ChicoLopes para ajudar a identificar a causa do problema.

**Comment by ChicoLopes** [comment]
Analisando o que ocorre junto com @anakatiacamilo, nova sessão de análise do problema amanhã (15/9) período da tarde. Mas até o momento tudi indica que o harvest específico está trazendo realmente apenas 77 documentos

**Comment by ChicoLopes** [comment]
Em análise conjunta com @anakatiacamilo , verificou-se que um harvest específico trouxe os dados até então ausentes, que assim foram indexados devidamente em IAHx, e ficou determinado que @ChicoLopes acompanhará "de perto" a próxima execução do harvest regular para coletar informações e pistas sobre as possibiildades de eventuais falhas no procedimento de coleta de dados.

O processo a ser monitorado é **/bases/fiadmin/consolida/tpl/harv_fiadmin.sh** no serverofi5.

**Comment by ChicoLopes** [comment]
@AngelicaSAPaula os artigos de 2022 da revista Más Vita agora estão retornando na busca no IAHx. 
Este chamado está sendo encerrado, mas caso observe mais alguma situação semelhanbnte, você pode reabri-lo ok.

**Comment by AngelicaSAPaula** [comment]
Muito obrigada :)
