### ISSUE TITLE
Processamento ZIKA - MoU com a FSP/USP

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#84]
@botturam por favor, realizar processamento da seguinte estratégia de busca nas bases MEDLINE e LILACS

mh:("Infecção pelo Zika virus" or "Zika virus") or ti:("ZIKV" or "ZIKA" or "ZIKAVIRUS")

Para exportação dos arquivos CSV correspondentes.

**Comment by botturam** [comment]
estratégia de zika para coleta no índice SoLR do Portal Regional disponível em:

serverofi5:/bases/Strategies2IAHX/apps/strategies/zika/ZIKA.sch

@falbrito

**Comment by falbrito** [comment]
Processamento de coleta realizado.

Insumo disponível em:

serverofi5:/bases/Strategies2IAHX/apps/ids_iahx/zika
-rw-rw-r-- 1 operacao operacao    110 May 21 08:41 totais.txt
-rw-rw-r-- 1 operacao operacao 168121 May 21 08:41 ZIKA_full.ids

Realizado.

**Comment by renatomurasaki** [comment]
@falbrito Somente fechar o issue qdo tiver os CSV entregues

**Comment by botturam** [comment]
tabulações disponíveis em ftp.bireme.br - /home/ftp/OFI/ZIKA

-rwxr-xr-x    1 1066     1006     623697166 May 21 17:54 LILACS_tabulacoes.zip
-rwxr-xr-x    1 1066     1006      2322516 May 21 17:52 medline_tabulacoes.zip

**Comment by renatomurasaki** [comment]
@botturam @falbrito 
@botturam por favor, envie-me por e-mail as instruções de acesso ao ftp.

**Comment by renatomurasaki** [comment]
Revisar diacríticos nos arquivos exportados. Exemplo, arquivo *autores* do Medline está em ANSI com as acentuações francesas perdidas. Já o arquivo com os metadados dos documentos (*todos*) está em UTF-8. Além disso, vieram no arquivo zip arquivos de RHS e SES-SP.

**Comment by botturam** [comment]
Diacríticos revisados. Foi retirado o gizmo tabs/g850ans da geração de tabelas.

O arquivo ZIP de tabelas contém todas as tabelas de temas das várias temáticas, e não apenas do projeto em questão.
