### ISSUE TITLE
Coleta OAI - WHOLIS - WHO IRIS - WHO Headquarters (who) - OFI7

### ISSUE THREAD

**Issue by ChicoLopes** [bireme/db-processing#849]
Coleta nos moldes definidos no cadastramento WHO no Celery em serverofi5 consonante a uma linha em coletas.tab

**Comment by ChicoLopes** [comment]
@botturam o processamento **WHO IRIS - WHO-Headquarters** segue os passos conforme contido em tasks.py do diretório _/bases/apps/ofi_djang_project/who_ de serverofi5 ou seja, a sequência:

- coleta_oai.sh who;
- pos_coleta_oai.sh who;
- pre_saneamento_fi.sh who;
- iah_like_lilacs_fi.sh who; e
- iahx_xml_geral_fi.sh who

Foi criado em serverofi7 um shell-script (*/bases/lilG4/shs.lil/_who.sh*) para ser executado por agendamento crontab que carrega o ambiente de execução conforme necessário para o usuário operacao pelo shell-script cronCelery.sh.

Os pontos de armazenamento relativos a **WHO IRIS - WHO-Headquarters** são (todos em serverofi7):
XMLs coletados armazenados em /bases/oai.pmh/xml.rec/who/file*.xml
Bases CDS/ISIS das coleções armazenadas em /bases/oai.pmh/isis/who/LILACS
Base CDS/ISIS consolidada armazenada em /bases/oai.pmh/isis/who/who_LILACS
XML para uso por IAHX armazenado em /bases/iahx/xml-index/regional/who_regional.xml

finalizado o processamento WHO IRIS - WHO-Headquarters com a coleta da coleção:
**who**
que após o processamento apresenta a quantidade esperada de documentos no arquivo XML **who_regional.xml** em _/bases/iahx/xml-inbox/regional_.

O cadastramento no Celery escala a execução para as 21h30 de sexta-feira
Em serverofi7 foi criada a entrada crontab para execução do processamento conforme:
**30 21 * * 5        /usr/local/bireme/misc/cronCelery.sh _who.sh**

**Comment by ChicoLopes** [comment]
@botturam processamento teste homologatório disparado em 8 de dezembro às 10h45

**Comment by botturam** [comment]
@ChicoLopes quanto ao WHOIRIS, vamos tirar da coletasXML-IAHx.tab, deixando só o "regional"

who haiti|WHOLIS||s|s|680|04-international_org||who.lil|bvs.hai|haiti
who h1n1|WHOLIS||s|s|680|04-international_org||who.lil|bvs.h1n|h1n1
who RIPSA|WHOLIS||s|s|680;681|04-international_org||who.lil|bvs.rps|RIPSA

**Comment by ChicoLopes** [comment]
@botturam em 13/12 foram retiradas da tabela $TABS/coletasXML-IAHx.tab as linhas correspondentes à fonte de informação WHOLIS - WHO IRIS para as instâncias HAITI, H1N1 e RIPSA, asism sendo passa a ser gerado arquivo XML apenas para a instância regional e a coleta e processamento em **serverofi7** gerou resultado superior a **serverofi5**, portanto processamento **Celery** em serverofi5 foi **desativado** e o agendamento por **crontab** em serverofi7 foi **efetivado**, nos termos apontados em comentário anterior.
