### ISSUE TITLE
MEDLINE - problema com o campo Afiliação de Autor - tamanho excessivo do documento XML

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#85]
Heitor,

o excessivo nro de ocorrências do campo afiliação do MEDLINE está parando a execução do seguinte programa em JAVA:

serverofi5:/bases/mdlG4/tpl.mdl/Medline.sh

java -cp /usr/local/bireme/java/Xml2Isis/dist/Xml2Isis.jar:/usr/local/bireme/java/Xml2Isis/dist/lib/zeus
III.jar:/usr/local/bireme/java/Xml2Isis/dist/lib/Utils.jar br.bireme.xml2isis.Medline pubmed18n1130 utf-8 tmp1_pubmed18n1130

Arquivo de exemplo: serverofi5:/bases/mdlG4/fasea/update_xml/pubmed18n1130.xml
PMID: 27770183

**Comment by botturam** [comment]
Heitor,

desta vez, após sua intervenção na 6f, deu o seguinte erro:

---------------------------------------------------------------------------------------------
*** Arquivo de trabalho ( 1 / 12 ): pubmed18n1130.xml ***
[TIME-STAMP] 2018.05.25 15:17:47 [:INI:] Processa ../../../tpl.mdl/ConvXML2ISIS.sh pubmed18n1130
---------------------------------------------------------------------------------------------
[../../../tpl.mdl/ConvXML2ISIS.sh] 1 - Criando Master de Inversao...
Extraindo elementos
+++ 1 : /home/bases/mdlG4/fasea/update_xml/wrk/pubmed18n1130.xml (0 milisecond(s))
Exception in thread "main" bruma.BrumaException: nvf > 32767
        at bruma.master.Record.addField(Record.java:887)
        at br.bireme.xml2isis.IsisWriter.addField(IsisWriter.java:58)
        at br.bireme.xml2isis.StaxXmlWalker.saveContent(StaxXmlWalker.java:315)
        at br.bireme.xml2isis.StaxXmlWalker.convert(StaxXmlWalker.java:238)
        at br.bireme.xml2isis.Xml2Isis.main(Xml2Isis.java:120)
ConvXML2ISIS.sh: fatal - ../../../tpl.mdl/ConvXML2ISIS.sh - Extraindo elementos
GenBasesCISIS.sh: fatal - ../tpl.mdl/GenBasesCISIS.sh - Chamando Conversao
./geraInsumoNLM.sh - Erro de processamento!

**Comment by botturam** [comment]
Heitor,

desta vez foi o seguinte erro:

  <1002>5</1002>
  <1003>13</1003>
</record>

ERROR: skipping record database:pubmed18n1130 fileName:/home/bases/mdlG4/fasea/update_xml/wrk/pubmed18n1130.xml content:<record mfn='0' nvf='126' status='ACTIVE'>
  <668>Publisher</668>
  <969>29752875</969>
  <1031>2018</1031>
  <1032>05</1032>
  <1033>12</1033>
  <301>1097-0061</301>
  <3541>2018</3541>
  <3542>May</3542>
  <3543>12</3543>
  <3544></3544>
  <3545></3545>
  <3549></3549>
  <373></373>
  <381></381>
  <308>Yeast (Chichester, England)</308>
  <309>Yeast</309>
  <352>Characterisation of antagonistic yeasts for biocontrol applications on apples or in soil by quantitative analyses of synthetic yeast communities.</352>
  <9689>doi</9689>
  <9681>10.1002/yea.3321</9681>

**Comment by heitorbarbieri** [comment]
O problema ocorre quando o número de campos do registro Isis convertido ultrapassa o limite de 32k, o que ocorre, por exemplo,  quando um documento têm mais  de 4 mil autores pois gera-se campo para primeiro nome, nome do meio, sobrenome, afliliações, etc.
O programa foi alterado de forma a se ultrapassar os 32k campos, eliminar todos os campos de afiliação do registro. Se ainda aissim não funcionar, então gera-se um aviso e despreza-se o registro em questão. 

Favor verificar o funcionamento.

**Comment by botturam** [comment]
Heitor,

um outro problema ocorreu no seguinte teste:

serverofi5:/bases/mdlG4/fasea/flb/teste.sh

para visualizar os campos do XML pubmed18n1007.xml, procurar por PMID 28448241
