### ISSUE TITLE
Coleta OAI - CVSP-ARES UNASUS (una) - OFI7

### ISSUE THREAD

**Issue by ChicoLopes** [bireme/db-processing#851]
Coleta nos moldes definidos no cadastramento UNA no Celery em serverofi5 consonante a uma linha em coletas.tab

**Comment by ChicoLopes** [comment]
@botturam o processamento **CVSP-ARES UNASUS** segue os passos conforme contido em tasks.py do diretório _/bases/apps/ofi_djang_project/UNA_ de serverofi5 ou seja, a sequência:

- coleta_oai.sh una;
- pos_coleta_oai.sh una;
- pre_saneamento_fi.sh una;
- iah_like_lilacs_fi.sh una; e
- iahx_xml_geral_fi.sh una

Foi criado em serverofi7 um shell-script (*/bases/lilG4/shs.lil/_una.sh*) para ser executado por agendamento crontab que carrega o ambiente de execução conforme necessário para o usuário operacao pelo shell-script cronCelery.sh.

Os pontos de armazenamento relativos a **CVSP-ARES UNASUS** são (todos em serverofi7):
XMLs coletados armazenados em /bases/oai.pmh/xml.rec/una-cvsp_ares_unasusfile*.xml
Bases CDS/ISIS das coleções armazenadas em /bases/oai.pmh/isis/una-cvsp_ares_unasus/LILACS
Base CDS/ISIS consolidada armazenada em /bases/oai.pmh/isis/una/una_LILACS
XML para uso por IAHX armazenado em /bases/iahx/xml-index/regional/una_regional.xml

finalizado o processamento VETINDEX - Veterinária com a coleta da coleção:
**unasus**
que após o processamento apresenta a quantidade esperada de documentos no arquivo XML **una_regional.xml** em _/bases/iahx/xml-inbox/regional_.

O cadastramento no Celery escala a execução para as 23H20 de quarta-feria
Em serverofi7 foi criada a entrada crontab para execução do processamento conforme:
**20 23 * * 3        /usr/local/bireme/misc/cronCelery.sh _una.sh**

**Comment by botturam** [comment]
@ChicoLopes proc. concluído com êxito em OFI7.
