### ISSUE TITLE
Verificar disponibilidade de índice de instâncias IAHX 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/db-processing#852]
@botturam poderia, quando possível verificar quais instâncias da lista abaixo ainda se encontram com disponibilidade de processamento/índice solr?

https://pesquisa.bvsalud.org/afroho/
https://pesquisa.bvsalud.org/PSP/
https://pesquisa.bvsalud.org/evidenciassp/
https://pesquisa.bvsalud.org/haiti/
https://pesquisa.bvsalud.org/ripsa/
https://pesquisa.bvsalud.org/segurancaviaria/
https://pesquisa.bvsalud.org/sus/ 

Obrigado

**Comment by botturam** [comment]
@viniciusandrade 

https://pesquisa.bvsalud.org/afroho/    (desativada - não existe índice SoLR)
https://pesquisa.bvsalud.org/PSP/         (desativada - não existe índice SoLR)
https://pesquisa.bvsalud.org/evidenciassp/   (desativada - não existe índice SoLR)
https://pesquisa.bvsalud.org/haiti/      (desativada - existia um índice SoLR congelado (SoLR3), mas o Portal Haiti foi descontinuado)
https://pesquisa.bvsalud.org/ripsa/     (Portal RIPSA foi descontinuado)
https://pesquisa.bvsalud.org/segurancaviaria/    (não tenho mais notícias há muitos anos. Achei que já estava desativado).
https://pesquisa.bvsalud.org/sus/    (existia um índice SoLR3 congelado de muitos anos)

Os índices SoLR dessas IAHx não são mais necessários. Os que ainda estão bob análise são UNIFESp e H1N1, mas esses estão ativos.

**Comment by botturam** [comment]
@viniciusandrade a partir da orientação da Juliana, segundo Ocomon 8814, iremos desativar todas as instâncias acima citadas, além de algumas que vc mencionou no início do chamado, e que sequer estão disponíveis aos usuários externos, como afroho, PSP, segurancaviaria, etc.

**Comment by botturam** [comment]
concluído
