### ISSUE TITLE
Migração instâncias IAHx - Basalto01 e Basalto02

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#855]
Levar os processamentos IAHx das Basaltos para os novos servidores iahx-idx01 (Basalto01) e iahx-idx02 (Basalto02)

Usuário "operação" disponível para acesso. Preparar o ambiente necessário (talvez profil_common mais enxuto).

**Comment by botturam** [comment]
@ChicoLopes sobre o novo iahx-idx01 (antigo Basalto01), levar apenas:

/home/javaapps/iahx-server/indexes/boletim
/home/javaapps/iahx-server/indexes/medlist
/home/javaapps/iahx-server/indexes/solr5-port3

o resto será desativado.

**Comment by ChicoLopes** [comment]
@botturam algumas definições:

- servidores usarão os nomes definidos pelo ITI:
> - iahx-idx01 em substituição a basalto01 e outros apelidos se houver
> - iahx-idx02 em subsituição a basalto02 e outros apelidos se houver
- o grupo operacao será utilizado nop FS para o serviço IAHx

**Comment by ChicoLopes** [comment]
@botturam o setup de usuários nos servidores iahx-idx01 e iahx-idex02 está concluído e passível de ser homologado. No momento está sendo feita uma primeira carga do índice do portal em iahx-idx02, iahx-idx01 já tem carregados os índices: boletim; medlist; binacis; bioeticaediplomacia; bivipsil; bvsvet; covidwho e cvsp.
O roteiro de setup utilizado está contido no arquivo SetupUsuarioIAHX-IDX01.2-rev00.docx carregado aqui.

[SetupUsuarioIAHX-IDX01&2-rev00.docx](https://github.com/bireme/db-processing/files/9854016/SetupUsuarioIAHX-IDX01.2-rev00.docx)

**Comment by ChicoLopes** [comment]
@botturam  índice do portal está disponível em basalto02, iahx-idx01 e iahx-idx02. A cópia de iahx-idx01, foi realizada diretamente de iahx-idx02, tendo demorado no total pouco menos de 1 hora e 20 minutos, assim como durou a transferência de serverofi6 para iahx-idx02, indicando que sem carga nos front-ends bem como em seus canais de comunicação o desempenho é da ordem de 110 MBytes por segundo ou 880 Mbps.

Em serverofi6 a tabela de processamento iAHx.tab teve sua coluna de servidor de balanceamento da linha 'portal' alterada de basalto01.bireme.br para iahx-idx02.bireme.br, o que proporcionará no próximo processamento a atualização automática do servidor iahx-idx02.

Faltando determinar como será a logistica regular de entrega de índices atualizados do portal nos quatro servidores de front-end.

Para efeito de registro estão carregados os arquivos log das trasnsferências de serverofi6 para iahx-idx02 e de iahx-idx02 para iahx-idx01.
[TransferenciaPortal-iahx-idx02Xiahx-idx01.txt](https://github.com/bireme/db-processing/files/9863310/TransferenciaPortal-iahx-idx02Xiahx-idx01.txt)
[TransferenciaPortal-serverofi6Xiahx-idx02.txt](https://github.com/bireme/db-processing/files/9863311/TransferenciaPortal-serverofi6Xiahx-idx02.txt)

**Comment by ChicoLopes** [comment]
@botturam temos a seguinte situação presente, a **serverofi6** está devidamente configurada para fazer envio dos índices de IAHx, dos seguintes conjuntos:

- portal para basalto02 e para iahx-idx02
- binacis para basalto01 e para iahx-idx01
- bioetica para basalto01 e para iahx-idx01
- bivipsil para basalto01 e para iahx-idx01
- bvsvet para basalto01 e para iahx-idx01
- covidwho para basalto01 e para iahx-idx01
- cvsp para basalto01 e para iahx-idx01
Estas transferências estão devidamente testadas e de hoje (03-nov-2022) em diante já entram em linha com os processamentos conforme agendamento por cron.

Do lado dos novos front-ends froram ajustadas e testadas as rotinas **ReiniciaIAHxGeral.sh** e **atualizaIAHx.sh**, sendo que a última é chamada pela primeira, que é executada por agendamento cron, já configurado para execução nos seguintes horários:

- 22h15 - diariamente
- 14h45 - sabados e domingos
- 06h00 - segunda a sexta-feira
ReiniciaIAHxGeral.sh cria ambiente para execução e evoca atualizaIAHx.sh
atualizaIAHx.sh efetua toda a tarefa de verificar se há flag permitindo a virada de diretórios, executar a prórpia virada e testar sua efetividades, fazendo roll-back se necessário.

Obs.: Por enquanto os e-mails são enviados apenas para o endereço configurado em CONSULTOR, libero envio para os demais (OFI e ITI) assim que você der o positivo.

**ATENÇÃO**: estas rotinas só efetuando STOP e START dos servidores Solr quando há dados para atualizar!

**Comment by ChicoLopes** [comment]
@botturam conforme orientação do Vinícius foram copiados os seguintes conteúdos da árvore /home/javaapps/iahx-server:
diretórios:

- client
- contrib
- dist
- docs
- indexes
- instances
- lib
- src

arquivos:

- build.xml
- CHANGES.txt
- common-build.xml
- KEYS.txt
- LICENSE.txt
- NOTICE.txt
- README.txt

Sendo que os diretórios logs não tiveram seus conteúdo transferido, uma vez que não haveria valor efetivo em "trazer" anos de registro de ações e operações efetuadas em outros servidores (basalto01 e 02).

Diferentemente dos servidores basalto01 e 02, nos servidopres iahx-idx01 e 02, o usuário '**operacao**' é capaz e responsável por controlar os serviços de busca, podendo, portanto, parar e iniciar servidores Solr e efetuar rotação de diretórios de dados.

Em adição à infraestrutura já presente historicamente, estão providas nestes novos servidores as facilidades de:
1. registro de execução cron das tarefas **ReiniciaIAHxGeral.sh**, localizadas em _/home/javaapps/iahx-server/bin/_
2. registro de execução da tarefa de atualização com dados de tempo de execução de seu chamador

Alguns últimos ajustamentos feitos em ambiente de execução, incluindo a eliminação do dia da semana no TIME-STAMP dos includes infoini.inc e infofim.inc cuja relevancia era nula

Assim pode ser liberada a colocação em produção dos servidores iahx-idx01 e 02
Por fim ressalta-se a importancia de compartilhar com o ITI o documento [SetupUsuarioIAHX-IDX01&2-rev00.docx](https://github.com/bireme/db-processing/files/9888687/SetupUsuarioIAHX-IDX01.2-rev00.docx) para tomada de ciência de todas as intervenções e ações administrrativas efetuadas nos servidores.

**Comment by botturam** [comment]
foram liberados para uso, junto ao ITI, os novos servidores iahx-idx01 e iahx-idx02, via Ocomon.

Estamos aguardando contato do Marco sobre a realização dessa etapa.

**Comment by botturam** [comment]
aparentemente há problemas de DNS. Vamos aguardar.

**Comment by botturam** [comment]
@ChicoLopes  @viniciusandrade @marcoslmori @heitorbarbieri problemas solucionados e as migrações de IAHx para os novos servidores IAHX-IDX01 e IAHX-IDX02 foram concluídas. Basalto01 e Basalto02 serão desativadas em breve.

IAHX-IDX02:
https://pesquisa.bvsalud.org/portal/

IAHX-IDX01:
https://pesquisa.bvsalud.org/binacis
https://pesquisa.bvsalud.org/bioeticaediplomacia
https://pesquisa.bvsalud.org/bivipsil
https://pesquisa.bvsalud.org/bvsvet
https://pesquisa.bvsalud.org/covidwho
https://pesquisa.bvsalud.org/cvsp
https://pesquisa.bvsalud.org/ripsa (apenas restabelecida para consulta, com dados do antigo SoLR3)

As seguintes bases NÃO foram migradas:
unifesp-pesq
unifesp-prod
medlist
boletim

**Comment by botturam** [comment]
concluído.
