### ISSUE TITLE
Disponibilizar Bases de dados ISIS para o início do projeto desenvolvimento de Migração de dados ISIS para o consultor DIEGO UCHA

### ISSUE THREAD

**Issue by marcoslmori** [bireme/db-processing#857]
Katia disponibilizar Bases de dados ISIS para o início do projeto desenvolvimento de Migração de dados ISIS para o consultor DIEGO UCHA

**Comment by anakatiacamilo** [comment]
A primeira base será MINSALCHILE - Ministério da Saúde do Chile, vou solicita para o Miacci deixar os arquivos disponivel para o Diego.
