### ISSUE TITLE
links dos filtros/entradas do cluster TOPICS para o sistema Queries a partir da IAHx-COVIDWHO

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#858]
são 4 filtros a serem linkados com o sitema Queries, assim como foi feito no cluster Type of Study.
[IAHx-COVID-cluster-TOPICS_linkQueries.xlsx](https://github.com/bireme/db-processing/files/9810944/IAHx-COVID-cluster-TOPICS_linkQueries.xlsx)

**Comment by kkothari2021** [comment]
Thank you that would be great.

**Comment by viniciusandrade** [comment]
Links from Topics to Repository of search strategies implemented.

**Comment by kkothari2021** [comment]
Amazing! Thank you!

**Comment by botturam** [comment]
cocncluído.
