### ISSUE TITLE
Incluir BRISA no cluster Base de Dados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#86]
@botturam favor identificar nos registros FI-Admin aqueles que têm o campo indexado em com o valor "BRISA - Base Regional de Informes de Evaluación de Tecnologías en Salud de las Américas" e marcá-los no cluster Base de Dados como BRISA/RedTESA. A mesma deve ser classificada como "Base de dados especializadas" no cluster Coleções.

Os documentos da BRISA podem ou não ser LILACS.

**Comment by renatomurasaki** [comment]
@botturam Marcelo, como está este tema do acréscimo de BRISA como parte do cluster Base de Dados?

**Comment by renatomurasaki** [comment]
Estes documentos de BRISA também devem ser marcados como Tipo de Estudo "Avaliação de tecnologias de saúde"

**Comment by botturam** [comment]
label inserido no cluster "db":

 BRISA/RedTESA (554)
 LILACS (554)
 Coleciona SUS (1)

**Comment by botturam** [comment]
conferir os clusteres "Tipo de Estudo" e "Coleções" na 2f, dia 16/07

**Comment by botturam** [comment]
Está disponível em homologação. Pedirei ao ITI para levar os arquivos TEXTS.INI para produção.

**Comment by renatomurasaki** [comment]
@botturam favor verificar porque o cluster mostra 556 documentos sendo que a BRISA tem quase 1.000 documentos.

**Comment by botturam** [comment]
incluí os docs que são exclusivamente BRISA. Amanhã, 3f, testarei em homologação.

**Comment by botturam** [comment]
disponível em homologação.

**Comment by botturam** [comment]
adicionado em tabs/db.pft

else if getenv('VAR2')='BRISA'
        then
   '    <field name="db">BRISA</field>'/,
   '    <field name="type_of_study">health_technology_assessment</field>'/,

**Comment by botturam** [comment]
else if getenv('VAR2')='BRISA'
        then
       <field name="db">BRISA</field>/,
       <field name="type_of_study">health_technology_assessment</field>/,

**Comment by botturam** [comment]
realizado
