### ISSUE TITLE
WPRIM - executar processamento de Outubro/2022

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#860]

**Comment by ChicoLopes** [comment]
@botturam Procedimentos do processaamento WPRIM foram executados, sendo que no envio de 04/out./2022 totalizaram 13190 documentos, o que no computo geral, eunidos aos já existentes prefazem um total de 902267 documentos.
O processmento foi disparado às 9:46 do dia 20/out./2022

**Comment by botturam** [comment]
concluído, em produção. Ainda feito em OFI5. Abrirei chamado posteriormente para migrar para OFI7.
