### ISSUE TITLE
Criar novo processamento para Moçambique no OFI7 (não existe em OFI5).

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#862]
Uma primeira versão manual está em OFI5 (shs.lil/_moc.sh). Não existe no celery

Clusters e tradução

Coleções - Nacional
- pt = Moçambique / es, en, fr = Mozambique

Bases de dados

- RDSM (nos 4 idiomas)

**Comment by botturam** [comment]
as tabelas coletas.tab e coletasXML-IAHx.tab já foram configuradas e um primeiro processamento já foi feito com _moc.sh

a coleta /bases/fiadmin/consolida/tpl/rodaFILTROS.sh está configurado para baixar ./filtraDBs.sh "RSDM"

**Comment by marcoslmori** [comment]
Oi @botturam fiz o teste em pt nos texts.ini 

Em base de dados 
RSDM="RDSM"
**funcionou** 

mas em [REFINE_collection]
**esse rótulo não funcionou**
fiz assim MZ="Moçambique"
baseado na iso: https://www.sport-histoire.fr/pt/Geografia/Codigos_ISO_Paises.php

abraços

**Comment by marcoslmori** [comment]
O comentário acima se refere a instancia de teste do portal regional

**Comment by botturam** [comment]
ajuste adicional feito em tabs/collection.pft

case  'RSDM':
       '    <field name="collection">'getenv('VAR4')'</field>'/,
       '    <field name="collection">'getenv('VAR4')'/MZ</field>'/,

Aguardar até 2f, dia 14/11

**Comment by botturam** [comment]
@marcoslmori disponível em produção

**Comment by botturam** [comment]
concluído em produção.
