### ISSUE TITLE
proc. coletaLIS - FI LIS - OFI7

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#863]
projeto Celery/Django:
OFI5:/bases/apps/ofi_django_project/coletaLIS

diretório execução e shells:
OFI5:/bases/iahx/proc/coletas/main

OBS1: Não trabalha com coleta.tab
OBS2: em OFI7, pode ser em /bases, já que não existe iahx

**Comment by ChicoLopes** [comment]
a realização da coleta utilizando o procedimento harvest.py que originalmente se dá com a versão 2.7 do interpretador Python, não deve ser realizada neste novo servidor de modo a eliminar a dependência de uma versão congelada a ser descontinuado pelo mantenedor.
Em decorrência disso por intervenção do Vinícius ficou observado que as ações a serem tomadas para suplantar essa transição são:

- “recriação” da árvore env
- checagem da identação do arquivo fonte .py
- alteração de parâmetro w para wb na função open (no caso de harvest.py especificamente, da função ‘open’) e
- reparo da linha **except Exception, e:** para **except Exception as e:**

Essas recomendações foram experienciadas pelo próprio Vinícius em seu processo de ‘pesquisa’ da solução e verificadas como suficientes para a coleta de LIS em FI-Admin.
Proximamente a mesma solução será aplicada e testada na demais coletas por harvesting usando Python.

**Comment by ChicoLopes** [comment]
@botturam  o processamento está ajustado para funcionamento, no entanto, como o interpretador em uso passou da versão Python 2.7 para a versão Python 3.8 a conversão de XML não está operando como esperado e Ana Katia e Vinícius estão verificando o que é necessário para operar corretamente, asism ficamos no aguardo do trabalho deles.

**Comment by anakatiacamilo** [comment]
Ajustes feito pelo @viniciusandrade:

1-
antigo
        <xsl:apply-templates select="/response/objects" />
novo
        <xsl:apply-templates select="/response/objects/object" />
------------------------------------------------------------------------
2- No 
<xsl:template match="objects/object" >
    <doc>
2.1 - Inclusão 
         <xsl:apply-templates select="id" mode="field" />
        <xsl:apply-templates select="title" mode="field" />
        <xsl:apply-templates select="originator" mode="field" />
        <xsl:apply-templates select="author" mode="field" />

        <xsl:apply-templates select="abstract" mode="field" />
        <xsl:apply-templates select="objective" mode="field" />

        <xsl:apply-templates select="link" mode="field" />
        <xsl:apply-templates select="descriptors" mode="field" />
        <xsl:apply-templates select="thematic_areas" mode="field" />
        <xsl:apply-templates select="source_languages" mode="field" />
        <xsl:apply-templates select="source_types" mode="field" />
        <xsl:apply-templates select="cooperative_center_code" mode="field" />
        <xsl:apply-templates select="created_time" mode="field" />
        <xsl:apply-templates select="updated_time" mode="field" />
2.2 - apagou esta linha
<xsl:apply-templates />
-----------------------------------------------------------------------------------
3 - Inclusão de  mode="field" nos xsl:template match= não em todos tem algumas exeções que precisa olhar no convert.xsl

Observação a indentação precisa esta correta tb fiz um teste parcial e agora vou fazer uma coleta completa para check com o arquivo da serverOFI5

**Comment by anakatiacamilo** [comment]
@botturam imagino que esta coleta do lis é para o processamento do iaHx. Estou com algumas duvidas nos field name: instance e collection que o XSL por padrão coloca em todos os registros

        <field name="instance">regional</field>
        <field name="instance">cns-br</field>
        <field name="instance">bolivia</field>
        <field name="instance">honduras</field>
        <field name="collection_cns-br">LIS</field>
        <field name="collection_bolivia">LIS</field>
        <field name="collection_honduras">LIS</field>
        <field name="collection">05-specialized</field>
 
Não sei se este é o momento para fazermos uma revisão só queria documentar esta questão

**Comment by botturam** [comment]
@ChicoLopes os shells de LIS e Multimedia estão afinados com as necessidades atuais. Não devem ser alterados em nada.

**Comment by botturam** [comment]
@anakatiacamilo os shells de LIS e Multimedia estão afinados com as necessidades atuais. Não devem ser alterados em nada.

**Comment by ChicoLopes** [comment]
@botturam  para colocar em operação a coleta de **LIS** (isto se estende à multimedia também), como são coletados arquivos XML, foi criada a árvore **/bases/xmls** que no subdiretório ‘**exec**’ abriga os shell scripts além do subdiretório **tabs**, e para área de trabalho contém um subdiretório dedicado a cada item individual de coleta (p.ex.: leys; lis; multimedia; title; nmail; etc.)

A coleta de LIS é realizada com o shell-script **0-coleta.modif.sh**, uma rotina de coleta modificada para ser parametrizável em sua chamada e realizar a coleta de um conjunto de itens ou item a item individualmente.
Quando usado o argumento de chamada ‘**ALL**‘ são coletados todos os itens constantes na tabela de controle de coleta chamada **tabeladecoletaFIs.tab** e localizada em **/bases/xmls/exec/tabs**. Em contrapartida podem ser usados como argumentos de chamada cada um dos conteúdos da primeira coluna de cada linha (não comentada) da tabela, atualmente ‘**lis**’ e ‘**multimedia**’. Assim são válidas atualmente as seguintes três chamadas de shell-script:

- 0-coleta.modif.sh ALL
- 0-coleta.modif.sh lis
- 0-coleta.modif.sh multimedia

Tais chamadas podem ser efetuadas em linha de comando ou se forem agendadas devem ser evocadas, indiretamente, através do shell-script **cronCelery.sh** que prepara o ambiente de execução para ser equiparado ao modo interativo de execução, onde são carregadas todas as variáveis de ambiente, aliases e etc do usuário ‘**operacao**’.

Por ser utilizado o shell-script cronCelery.sh é realizada uma chamada para **_lis.sh** localizado em **/bases/lilG4/shs.lil**, único diretório admissível para residirem shell-scripts executados através do cronCelery.sh.

**NOTA**: Em alternativa ao uso de cronCelery.sh há o shell-script cronArg_01.sh (criado depois dos ajustes da coleta LIS) que admite a chamada de shell-scripts localizados em qualquer ponto do F.S. desde que indicado na chamada

Atualmente há uma previsão de agendamento (comentada) para realização da coleta de LIS de **segunda a sexta-feira** às **20h**, utilizando cronCelery.sh

**Comment by botturam** [comment]
colocar no CRON e acompanhar resultado.

**Comment by ChicoLopes** [comment]
@botturam coleta e processamento em **serverofi7** gerou resultado **identico** a **serverofi5,** portanto processamento **Celery** em serverofi5 foi **desativado** e o agendamento por **crontab** em **serverofi7** foi efetivado, nos termos apontados em comentário anterior.
