### ISSUE TITLE
proc. coletaMULTIMEDIA - FI MULTIMEDIA - OFI7

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#864]
projeto Celery/Django:
OFI5:/bases/apps/ofi_django_project/coletaMULTIMEDIA

diretório execução e shells:
OFI5:/bases/iahx/proc/coletas/main

OBS1: Não trabalha com coleta.tab
OBS2: em OFI7, pode ser em /bases, já que não existe iahx

**Comment by ChicoLopes** [comment]
@botturam  o processamento está ajustado para funcionamento, no entanto, como o interpretador em uso passou da versão Python 2.7 para a versão Python 3.8 a conversão de XML não está operando como esperado e Ana Katia e Vinícius estão verificando o que é necessário para operar corretamente, asism ficamos no aguardo do trabalho deles.

**Comment by anakatiacamilo** [comment]
@ChicoLopes, ajustei a xsl (seguindo o padrão da LIS) o arquivo para a executar do diretório geral.
 /bases/xmls/coletas/midsms.convert.xsl

Por favor, se possivel comparar o XML de saida da OFI5 com a OFI7. Para ver a necessidade de ajustes.

**Comment by anakatiacamilo** [comment]
Estou documentando para melhora e atualizado o processo.

Esta é a pouca informação que aparece no iaHx
https://pesquisa.bvsalud.org/portal/resource/pt/multimedia-10011

![image](https://user-images.githubusercontent.com/19270675/203402242-475ced7e-4d4b-4b69-9048-fe0a96f95061.png)

Por que, não estamos estamos fazerndo a transformação corretamente da informação. exemplos de campos que não estamos transformando: descrição, url e muitas outras informações importantes.
https://fi-admin-api.bvsalud.org/api/multimedia/search/?format=xml&q=%22Cuidados%20Paliativos%22

E quando nos revisar poderiamos ver, porque, temos que marcar collection_bolivia multimedia para todos os registros mesmo os que não são da Bolivia ou deixar documentado o porque fazemos isto.

**Comment by ChicoLopes** [comment]
@bottura para colocar em operação a coleta de Multimedia (isto se estende à LIS também), como são coletados arquivos XML, foi criada a árvore **/bases/xmls** que no subdiretório ‘**exec**’ abriga os shell scripts além do subdiretório **tabs**, e para área de trabalho contém um subdiretório dedicado a cada item individual de coleta (p.ex.: leys; lis; multimedia; title; nmail; etc.)

A coleta de Multimedia é realizada com o shell-script **0-coleta.modif.sh**, uma rotina de coleta modificada para ser parametrizável em sua chamada e realizar a coleta de um conjunto de itens ou item a item individualmente.

Quando usado o argumento de chamada ‘**ALL**‘ são coletados **todos** os itens constantes na tabela de controle de coleta chamada **tabeladecoletaFIs.tab** e localizada em _/bases/xmls/exec/tabs_. Em contrapartida podem ser usados como argumentos de chamada cada um dos conteúdos da primeira coluna de cada linha (não comentada) da tabela, atualmente ‘**lis**’ e ‘**multimedia**’. Assim são válidas atualmente as seguintes três chamadas de shell-script:

- 0-coleta.modif.sh ALL
- 0-coleta.modif.sh lis
- 0-coleta.modif.sh multimedia

Tais chamadas podem ser efetuadas em linha de comando ou se forem agendadas devem ser evocadas, indiretamente, através do shell-script **cronCelery.sh** que prepara o ambiente de execução para ser equiparado ao modo interativo de execução, onde são carregadas todas as variáveis de ambiente, aliases e etc do usuário ‘**operacao**’.

Por ser utilizado o shell-script cronCelery.sh é realizada uma chamada para **_mmd.sh** localizado em **/bases/lilG4/shs.lil**, único diretório admissível para residirem shell-scripts executados através do cronCelery.sh.

**NOTA**: Em alternativa ao uso de cronCelery.sh há o shell-script cronArg_01.sh (criado depois dos ajustes da coleta LIS) que admite a chamada de shell-scripts localizados em qualquer ponto do F.S. desde que indicado na chamada

Atualmente há uma previsão de agendamento (comentada) para realização da coleta de **multimedia** de **terça a sábado** às **0h40**, utilizando cronCelery.sh

**Comment by ChicoLopes** [comment]
@botturam  para colocar em operação a coleta de **LIS** (isto se estende à multimedia também), como são coletados arquivos XML, foi criada a árvore **/bases/xmls** que no subdiretório ‘**exec**’ abriga os shell scripts além do subdiretório **tabs**, e para área de trabalho contém um subdiretório dedicado a cada item individual de coleta (p.ex.: leys; lis; multimedia; title; nmail; etc.)

A coleta de LIS é realizada com o shell-script **0-coleta.modif.sh**, uma rotina de coleta modificada para ser parametrizável em sua chamada e realizar a coleta de um conjunto de itens ou item a item individualmente.
Quando usado o argumento de chamada ‘**ALL**‘ são coletados todos os itens constantes na tabela de controle de coleta chamada **tabeladecoletaFIs.tab** e localizada em **/bases/xmls/exec/tabs**. Em contrapartida podem ser usados como argumentos de chamada cada um dos conteúdos da primeira coluna de cada linha (não comentada) da tabela, atualmente ‘**lis**’ e ‘**multimedia**’. Assim são válidas atualmente as seguintes três chamadas de shell-script:

- 0-coleta.modif.sh ALL
- 0-coleta.modif.sh lis
- 0-coleta.modif.sh multimedia

Tais chamadas podem ser efetuadas em linha de comando ou se forem agendadas devem ser evocadas, indiretamente, através do shell-script **cronCelery.sh** que prepara o ambiente de execução para ser equiparado ao modo interativo de execução, onde são carregadas todas as variáveis de ambiente, aliases e etc do usuário ‘**operacao**’.

Por ser utilizado o shell-script cronCelery.sh é realizada uma chamada para **_lis.sh** localizado em **/bases/lilG4/shs.lil**, único diretório admissível para residirem shell-scripts executados através do cronCelery.sh.

**NOTA**: Em alternativa ao uso de cronCelery.sh há o shell-script cronArg_01.sh (criado depois dos ajustes da coleta LIS) que admite a chamada de shell-scripts localizados em qualquer ponto do F.S. desde que indicado na chamada

Atualmente há uma previsão de agendamento (comentada) para realização da coleta de LIS de **segunda a sexta-feira** às **20h**, utilizando cronCelery.sh

**Comment by botturam** [comment]
colocar no CRON e acompanhar resultado.

**Comment by ChicoLopes** [comment]
@botturam pelo que tenho acompanhado os XML tem o mesmo conteúdo, apenas que os elementos constituintes do XML estão em ordem diversa entre OFI5 e OFI7 devido as modificações necessárias no XSL. Estou dando por fechado, se necessário reabrimos o issue 864
