### ISSUE TITLE
proc. coletaTITLE - FI TITLE - OFI7

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#868]
projeto Celery/Django:
OFI5:/bases/apps/ofi_django_project/TITLE

diretório execução e shells:
OFI5:/bases/iahx/proc/coletas/main/title

OBS1: Não trabalha com coleta.tab
OBS2: em OFI7, pode ser em /bases, já que não existe iahx

**Comment by anakatiacamilo** [comment]
Relacionados com este issue

- Atualização do Portal de Revistas

NO Servidor QUARTZO2 com o usuário root

1 - No diretório /bases/portal/newprocs executar o comando ./geralpr.sh
2 - No diretório cd /bases/portal/iso/ copiar os arquivos para o servidor bases com o comando - e senha do usuário transfer passada anteriormente

scp titles.iso holdings.iso transfer@bases2.bireme.br://home/catrevserver/www/import/iso/.

3 - No servido BASALTO02 com o usuário root
3.1 - no diretório /home/catrevserver/www/import executar o comando ./criaMasterInvertTitleHolds.sh

Migrar do servidor BASALTO02 ==>> iah-idx01

**Comment by botturam** [comment]
@ChicoLopes na sequência do LIS e Multimedia, favor pegar esses 3 da Kátia.

**Comment by ChicoLopes** [comment]
@anakatiacamilo a coleta de TITLE tem dous processos cadastrados no Celery, um denominado TITLE e outro denominado coletaTITE, seus detalhes são:

### TITLE
sob cadastro no celery em _serverofi5:/bases/apps/ofi_django_project/TITLE_
tasks.py solicita execução de _cronTrazTitle.sh_ com diretório corrente _/usr/local/bireme/misc/infra_

Na transferência para OFI7
TITLE é executado com o shell equivalente **trazTITLE.sh** presente em **_/bases/lilG4/shs.lil_** por meio de **cronCelery.sh** de segunda a sexta-feira às _5h11_ por agendamento cron

### coletaTITLE
sob cadastro no celery em _serverofi5:/bases/apps/ofi_django_project/coletaTITLE_
tasks.py solicita execução de _coleta_title.sh_ com diretório corrente _/bases/iahx/proc/coletas/main/title_

Na transferência para OFI7
coletaTITLE é executado com o **shell coleta_title.sh** presente em **_/bases/xmls/exec_** por meio de **cronArg_01.sh** de segunda a sexta-feira às _5h01_ por agendamento cron

**Comment by ChicoLopes** [comment]
@anakatiacamilo lisando as ações dos processos relatados acima, observa-se que há redundância entre eles, de uma tal forma que dispensa a execução da tarefa denominada **TITLE**, cuja única função é editar os registros que contém no _campo 150_ o conteúdo "**Zhonghua Nei Ke Za Zhi**", podendo, portanto, deixar de ser executada.

Relativamente à tarefa **coletaTITLE** a transferência para o servidor _quartzo2_ está seriamente prejudicada pela desatualização daquele servidor que torna impossível a cópia remota segura de dados para ele, sendo a solução possível de implementação no momento a transferência por FTP, com consequente necessidade de implantação de tarefa cron para que o usuário ‘**transfer**’ do mesmo tome o dado no servidor de FTP. No entanto, em análise da utilização da informação transferida com Marcelo, ficou acordado de não efetuar a transferência e portanto parar a atualização da informação em quartzo2 até que se determine a real necessidade desta operação.

**Comment by ChicoLopes** [comment]
@anakatiacamilo a realização da coleta utilizando o procedimento **harvest.py** que originalmente se dá com a versão 2.7 do interpretador Python, não deve ser realizada neste novo servidor de modo a eliminar a dependência de uma versão congelada a ser descontinuado pelo mantenedor.
Em decorrência disso por intervenção do Vinícius ficou observado que as ações a serem tomadas para suplantar essa transição são:

- “recriação” da árvore env
- checagem da identação do arquivo fonte .py e
- alteração de parâmetro w para wb na função open (no caso de harvest.py especificamente, da função ‘open’)

Essas recomendações foram experienciadas pelo próprio Vinícius em seu processo de ‘pesquisa’ da solução e verificadas como suficientes para a coleta de TITLE em FI-Admin.
Proximamente a mesma solução será aplicada e testa na demais coletas por harvesting usando Python.

**Comment by ChicoLopes** [comment]
@anakatiacamilo efetuadas as adaptações necessárias no shell-script denominado **coleta_title.sh** localizado em **_serverofi7:/bases/xmls/exec_**, foi colocado para execução prova por agendamento crontab para às 5h01. Avaliando o resultado, foi observado a perfeita identidade com a title coletada no servidor _serverofi5_. Devido a essa perfeita identidade, por recomendação do Marcelo, a escalação Celery de OFI para a TITLE e coletaTITLE foram desativadas, assim como o agendamento cron em quartzo2 para “coletar” a **title.iso**, que antes era depositada, foi _ativado_ para o usuário **transfer** de **quartzo2**. Abaixo são descritos detalhes dos procedimentos ativado em serverofi7 e em quartzo.

### SERVEROFI7
### coleta_title.sh
O Shell-script **coleta_title.sh** efetua por harvesting com o programa **harvest.py** a coleta de _title_ em _FI_Admin_, sendo executado sob o interpretador _python3_ (Python versão 3.8.10), seguindo as alterações recomendadas por Vinícius. 
O shell **coleta_title.sh** promove a mudança para o diretório de trabalho (_/bases/xmls/coletas/title_), cria se necessário o diretório **isis_id** sob o diretório de trabalho e efetua a chamada do shell-script **run_harvest.sh**, passando como argumentos de chamada **_title_** e **_regional_** (objeto e filtro), o código de retorno deste shell é verificado e se ok procede à consolidação dos diversos arquivos ID obtido da coleta, convertendo o produto em uma base CDS/ISIS, faz tratamentos de limpeza, filtragem de dados e remontagem da base, gerando no final um arquivo ISO de nominado **title.iso**. Este arquivo é disponibilizado na raiz do servidor de FTP com o URL **ftp.bireme.br**, para posterior tomada por usuário de transferência do servidor **quartzo2** (tarefa agendada no servidor para execução às 5h20) e adicionalmente uma cópia denominada **ntitle.iso** é depositada no diretório _$TABS_ (**/usr/local/bireme/tabs**) do próprio servidor **serverofi7**.
O shell-script é executado por agendamento cron de _segunda a sexta-feira às 5h01_, sua localização é no diretório **/bases/xmls/exec**, pode ser executado manualmente em linha de comando a qualquer momento e sua execução por cron é disparada pelo shell-script **cronArg_01.sh**, cuja função é criar o ambiente de execução idêntico ao de uma sessão interativa de bash. 
### cronArg01.sh
O shell-script residente em _$MISC_ (**/usr/local/bireme/misc**) configura um ambiente de execução tal e qual o ambiente de _bash interativo_, executando os profiles específicos do usuário **operacao**, quais sejam: **profil_here** e **profil_common**; **ambienteIAH**; **profil_iah**; **profil_isis**; **profil__java**; e **profil_path** (quando existente). Com isso estarão garantidas as existências ambientais de _constantes_, _variáveis_ e _caminho de busca de executáveis_ como esperado.
Preparado todo esse ambiente, o shell coloca em execução aquilo que foi indicado como argumento de execução e repassa para ele os demais argumentos de chamada (**até o limite de nove** deles).

### QUARTZO2
### trazTITLE.sh

O Shell-script **trazTITLE.sh** efetua por ftp a ‘coleta’ do arquivo **title.iso** disponível na raiz do servidor **ftp.bireme.br**, de **segunda a sexta-feira às 5h20**.
O shell residente no diretório _home_ do usuário **transfer** de **quartzo2** (**/home/users/transfer**) promove o download do arquivo **title.iso**, efetivando gravação no diretório **/bases/portal/newprocs/isos**, apernas se a transferência tiver ocorrido com _status de sucesso_ (teste efetuado no próprio shell-scrtipt).
