### ISSUE TITLE
Criar pacote XML de DeCS para disponibilizar em servidor FTP

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#87]
Para o processamento de 2018 os XMLs de Português e Espanhol foram coletados de 
ftp://nlmpubs.nlm.nih.gov/online/mesh/MESH_FILES/mtms/ e o XML do MESH em ftp://nlmpubs.nlm.nih.gov/online/mesh/MESH_FILES/xmlmesh/.
O XML do MESH nesse endereço aparece sempre com a data do dia de visitação ao LINK. Ou seja não existe uma versão congelada.

Referência para processamento:
http://wiki.bireme.org/intranet/index.php/Decs_exportacao_xml_ftp

**Comment by falbrito** [comment]
Foi verificado que existe uma diferença de 466 registros em relação ao processamento passado. Isto se dá pois a coleta do XML desc2018 disponível já está sendo incorporado registros novos sem tradução.
Arthur possui uma versão baixada de setembro de 2018, e sugeriu realizar o processamento com esta.
quartzo2/home/decsweb/www/bases/mesh-ingles/2018/XML/desc2018.xml

**Comment by falbrito** [comment]
Processo realizado. Pacote disponibilizado para verificação em:

serverofi4:/bases/dec.000/xml_exportacao $ tree ftp_20180627/
ftp_20180627/
├── CRIA_xmls.20180626.out
├── decsbir_comID_20180626
│   ├── decsbir_comID.mst
│   └── decsbir_comID.xrf
├── E
│   ├── bireme_decs_spa2018.xml
│   ├── decs_espanol_2018.tgz
│   ├── nlmdescriptorrecordset_20180101.dtd
│   ├── nlmqualifierrecordset_20180101.dtd
│   ├── README.txt
│   ├── spadesc2018.xml
│   ├── spapolqual2018.xml
│   └── spaqual2018.xml
├── I
│   ├── bireme_decs_eng2018.xml
│   ├── decs_english_2018.tgz
│   ├── desc2018.xml
│   ├── engpolqual2018.xml
│   ├── nlmdescriptorrecordset_20180101.dtd
│   ├── nlmqualifierrecordset_20180101.dtd
│   ├── qual2018.xml
│   └── README.txt
└── P
    ├── bireme_decs_por2018.xml
    ├── decs_portugues_2018.tgz
    ├── nlmdescriptorrecordset_20180101.dtd
    ├── nlmqualifierrecordset_20180101.dtd
    ├── pordesc2018.xml
    ├── porpolqual2018.xml
    ├── porqual2018.xml
    └── README.txt

Dados do LOG de processamento disponível em:
http://wiki.bireme.org/intranet/index.php/Decs_exportacao_xml_ftp#Processamento_-_20180627

**Comment by falbrito** [comment]
Aguardando validação de Arthur e Marcelo.

**Comment by botturam** [comment]
Verifiquei se não havia descritores com identificadores únicos repetidos em:

serverofi4:/bases/dec.000/xml_exportacao/ftp_20180627/decsbir_comID_20180626/decsbir_comID.mst

Os subcampos ^z e ^w dos campos 1001, 1002, 1003, 1051, 1052 e 1053 estão sem repetição. 

Validado!

**Comment by falbrito** [comment]
Pacotes criados e disponibilizados no servidor ftp.bireme.br

Dados do LOG de processamento disponível em:
http://wiki.bireme.org/intranet/index.php/Decs_exportacao_xml_ftp#Processamento_-_20180627
