### ISSUE TITLE
Processamento de coleta da leys - OFI7

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#870]
diretório execução e shells:
OFI5:/bases/iahx/proc/coletas/main/leys
O shell principal é coleta_leys.sh

OBS1: Não trabalha com coleta.tab
OBS2: em OFI7, pode ser em /bases, já que não existe iahx

**Comment by botturam** [comment]
@ChicoLopes na sequência do LIS e Multimedia, favor pegar esses 3 da Kátia.

**Comment by anakatiacamilo** [comment]
@ChicoLopes, esta coleta foi ajustada pelo @viniciusandrade para funcionar na OFI7 com o python3 os ajustes foram:

- arquivo run_harvest.sh;
- arquivo harvest.py;
- diretório env

por favor, replicar com lis e multimedia.
Grata

**Comment by ChicoLopes** [comment]
@anakatiacamilo o processamento de coleta LEYS está revisado e adaptado para operar em serverofi7, residindo em **/bases/xmls/exec** (juntamente com 0-coletas.modif.sh; 0-cileta_generica.sh; e coleta_title.sh. Ao ser executado comuta para o diretório de trabalho **/bases/xmls/coletas/leys** de onde efetua o havesting dos dados utilizando o programa **harvest.py** devidamente adaptado para execução sob o interpretador _Python 3.8_.

Sua execução resulta em uma coleção de arquivos denominados _harvest_nnn.id_ que em verdade são arquivos **json** (JavaScript Object Notation), que em seguida são formatados, para aumentar sua legibilidade humana, com o programa _jsonlint_ (JSON syntax validator and formatter tool), usando as opções **-S** (nonstrict – verificação relaxada) e **-f** (format), sendo a versão formatada gravada no diretório json. Concluída a formatação é efetuada uma normalização nos nomes dos arquivos json para a máscara **_harvest_00000.json_**, seguida da contagem de documentos coletados em todos os arquivos, e montada uma lista com suas identificações, os arquivos json são contactados e reunidos em um arquivo tgz. Finalizando o procedimento o arquivo com a lista de identificadores de documentos e o compacto de dados são colocados no diretório **out_json** (/bases/xmls/colets/leys/out_json), configurando um pacote de entrega.

O shell-script **coleta_leys.sh** não admite argumentos de chamada, apenas opções de execução num total de cinco delas (--changelog; --debug n; --help; --info; --version), pode ser chamado de qualquer local do FS, desde que apontado o caminho absoluto para ele, que é **/bases/xmls/exec/coleta_leys.sh**

**Comment by anakatiacamilo** [comment]
@ChicoLopes, parece que a coleta do OFI7 esta com algum problema no sistema tem 36515 registro publicados da Argentina, no OFI5 é coletado 3652 arquivos com 10 registros cada e o ultimo tem 5 registros e na OFI7 é coletado 3636 no total tem 36300
 registros.

**Comment by ChicoLopes** [comment]
@anakatiacamilo após nova execução em 10/jan, tanto em OFI5 quanto em OFI7 a situação da coleta de Leys é a seguinte:

operacao@OFI7:/bases/xmls/coletas/leys $ ll out_json/
total 97788
-rw-rw-r-- 1 operacao operacao  2197759 Jan 10 12:28 IDs.lst
-rw-rw-r-- 1 operacao operacao 97932553 Jan 10 12:28 legisalud-ar.tgz

O relatório reporta:
Total de documentos recopilados **36687**


operacao@OFI5:/bases/iahx/proc/coletas/main/leys $ ll out_json/
total 94864
-rw-rw-r-- 1 operacao operacao       40 Jan 10 16:44 IDs.lst
-rw-rw-r-- 1 operacao operacao 97134128 Jan 10 16:44 legisalud-ar.tgz

O relatório reporta:
Total de documentos recompilados **36647**

Levando a melhora de resultados em serverofi7

Desta forma reitera-se que a execução deveser realizada em **serverofi7** diretório **/bases/xmls/coletas/leys** com a chamada **../../exec/coleta_leys.sh** que é realizada manualmente, não havendo previsão de agendamento para a tarefa.
