### ISSUE TITLE
OFI5 Processamento de FTP SciELO - OFI7

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#871]
Por favor, migrar a rotina (getiso.sh/TomaSciELOsLocais.sh) que faz o FTP do SciELO - servidor OFI5 para o OFI7
No diretório serverofi5:/bases/org.000/iso

do art e iss

As seguintes coleções:
arg
col
mex
per
scl
spa

**Comment by botturam** [comment]
@anakatiacamilo por favor, indique o que levaremos para OFI7 dos 3 abaixo:

operacao@OFI5:/bases $ ll -d org*
drwxrwsr-x 22 operacao operacao 36864 Nov  8 05:31 org.000/
drwxrwsr-x 11 operacao operacao  4096 Jul  3  2020 org.000C/
drwxrwsr-x 16 operacao operacao  4096 Feb  2  2017 orgG4/

**Comment by anakatiacamilo** [comment]
@botturam eu combinei com o @ChicoLopes  e deixei indicado o diretório /bases/org.000/iso e as rotinas (getiso.sh/TomaSciELOsLocais.sh) as coleções e dos tipos de documentos art e iss tudo no primeiro comentario. Como o Chiquinho que fez esses scripts acho que é mais tranquilo para ele migrar esta parte. Eu fiquei com os shells depois do FTP.

**Comment by anakatiacamilo** [comment]
OFI5:/bases/org.000/iso
art
iss

operacao@OFI7:/bases/lilG4/lxp.sci/sci.org/data $ tree .. -d
..
├── data
│   ├── art.arg
│   ├── art.scl
│   ├── iss.arg
│   └── iss.scl

somente o arquivo artigo.iso no diretório art.??? e issues.iso no diretório iss.???

**Comment by ChicoLopes** [comment]
@anakatiacamilo nos testes realizados o desempenho foi identico ao observado em serverofi5, sendo assim está concluída a adequação da rotina denominada pollSelect.sh que efetua a coleta dos arquivos ISO no servidor FTP de SciELO. 
As coletas realizadas são consoantes aos diretórios **art.xxx** existentes na árvore **/bases/lilG4/lxp.sci/sci.org/data**
