### ISSUE TITLE
erro no donwload do campo PMCID nos documentos COVIDWHO.

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#872]
@viniciusandrade verificar download do campo "pmcid" de documento COVID:

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?output=xml&lang=en&from=0&sort=&format=summary&count=20&fb=&page=1&skfp=&index=&q=id%3Acovidwho-2092269

RISFormat:

TY  - JOUR
AU  - Browne, Dillon
AU  - Roy, Sylvain
AU  - Phillips, Marjory
AU  - Shamon, Sandy
AU  - Stephenson, Michael
AD  - Browne D; Registered clinical psychologist and Canada Research Chair in Child and Family Clinical Psychology at the University of Waterloo in Ontario.
AD  - Roy S; Registered neuropsychologist in Toronto, Ont, Past President of the Ontario Psychological Association, and Lead of the Ontario Psychological Association Disaster Response Network.
AD  - Phillips M; Registered clinical psychologist and a faculty member of the University of Waterloo Clinical Psychology Program.
AD  - Shamon S; Private-practice family physician and palliative care specialist in Cambridge, Ont, and an adjunct faculty member of the Degroote School of Medicine at McMaster University.
AD  - Stephenson M; Director of Sanctuary Refugee Health Centre in Kitchener, Ont.
TI  - Supporting patient and clinician mental health during COVID-19: Via trauma-informed interdisciplinary systems.
JO  - Can Fam Physician
VL  - 66
IS  - 7
SN  - 1715-5258
DB  - MEDLINE
DP  - https://www.who.int/emergencies/diseases/novel-coronavirus-2019/global-research-on-novel-coronavirus-2019-ncov/
ID  - covidwho-2092269
C8  - covidwho-2092269
LA  - 
SP  - e190
EP  - e192
DA  - 2020/07
PY  - 2020
PMC  - 
C2  - 
KW  - Betacoronavirus
KW  - Coronavirus Infections/therapy
KW  - Patient Care Team/organization &amp; administration
KW  - Pneumonia, Viral/therapy
KW  - Psychological Trauma/therapy
KW  - COVID-19
KW  - Coronavirus Infections/complications
KW  - Coronavirus Infections/psychology
KW  - Humans
KW  - Inpatients/psychology
KW  - Mental Health
KW  - Mental Health Services/organization &amp; administration
KW  - Pandemics
KW  - Patient Care/methods
KW  - Pneumonia, Viral/complications
KW  - Pneumonia, Viral/psychology
KW  - Psychological Trauma/etiology
KW  - Quality of Health Care
KW  - SARS-CoV-2
UR  - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7365150
ER  -

**Comment by viniciusandrade** [comment]
@botturam ajuste realizado. 

No momento da criação deste campo ele foi definido como sendo de múltiplas ocorrências e agora provavelmente foi alterado o schema para valor simples.

Quando possível favor validar.

**Comment by botturam** [comment]
concluído.

**Comment by botturam** [comment]
@viniciusandrade Kavita solicitou que o campo PMC, do Risformat, seja PM, pois há um desalinhamento na coluna dos dados.

**Comment by botturam** [comment]
@viniciusandrade a demanda da Kativa sugere mudar de PMC para PM, ou tirar o espaço extra até o "-". Essa última opção é viável?

https://www.ncbi.nlm.nih.gov/pmc/?term=+PMC8441687&report=MEDLINE&format=text

**Comment by viniciusandrade** [comment]
@botturam retirado espaço extra que existia no campo PMC no formato de exportação RIS.

**Comment by botturam** [comment]
concluído.
