### ISSUE TITLE
Campo WOS (Web of Science) nos formatos de exportação do COVIDWHO

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#873]
@viniciusandrade é preciso fazer o download do campo "wos" da IAHx-COVIDWHO nos formatos de exportação. Creio que o campo pode-se chamar WOS

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?output=xml&lang=en&from=&sort=&format=&count=&fb=&page=1&skfp=&index=&q=id%3Acovidwho-2102246

XML-IAHx (pesquisa wos:*):

\<field name="wos">000853664200001\</field>

**Comment by viniciusandrade** [comment]
@botturam acho melhor aguardar um pouco pela definição da sigla que você questionou no comentário do issue https://github.com/bireme/Covid-19_WHO/issues/58#issuecomment-1327495583 para evitar re-trabalho. 
Quando definido favor informar aqui. Obrigado.

**Comment by botturam** [comment]
@viniciusandrade exatamente... ia dizer isso a você, pois acho que outros tipos de IDs que estão no campo Accession Number irão também para esse campo coringa.

**Comment by botturam** [comment]
@viniciusandrade o campo "accession_number" está disponível e pesquisável em produção. Exemplo:

accession_number:"32981335"

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/?output=xml&lang=en&from=0&sort=&format=summary&count=20&fb=&page=1&skfp=&index=&q=accession_number%3A%2232981335%22

Fazer o download para o campo "AN" (Risformat) e para o CSV (Excel) também.

**Comment by viniciusandrade** [comment]
@botturam exportação do campo disponível para RIS e CSV

**Comment by botturam** [comment]
concluído.
