### ISSUE TITLE
RIPSA - restabelecer proc. IAHx-Ripsa em OFI6

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#875]
transferindo resultado para Basalto01 e iahx-idx01

**Comment by ChicoLopes** [comment]
@botturam os F.S. de basalto01 e iahx-idx01 estão devidamente preparados com as ásvores de diretórios necessárias para receber os arquivos do índice de Ripsa e a tabela de controle de processamento iAHx.tab já está configurada. Uma primeira transferência foi provida manualmente e o servidor Solr5 porta 3 foi reinicializado para incorporar o novo índice de busca. Em ambos os servidores está operando como esperado na interface de administração do Solr, estando assim apto a ser configurado para uso pelo público externo.
