### ISSUE TITLE
proc. SES (todas) - FI-ADMIN - OFI7

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#879]
### Lista das FIs a serem migradas para OFI7. Os projetos Celery podem ser encontrados em OFI5:/bases/apps/ofi_django_project

- [x] sesapi
- [x] sesa-pr
- [x] ses-ba
- [x] ses-es
- [x] ses-go
- [x] ses-ma
- [x] ses-mg
- [x] ses-ms
- [x] ses-mt
- [x] ses-pb
- [x] ses-pe
- [x] ses-rj
- [x] ses-rn
- [x] ses-rs
- [x] ses-sc
- [x] ses-se
- [x] ses-to
- [x] ses-sp

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-BA** (sba) foi configurado em serverofi7 sob o shell script **_sba.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 6h20 foi **ativado em serverofi7**, conforme mostrado a seguir:
**20 06 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sba.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-ES** (sss) foi configurado em serverofi7 sob o shell script **_sss.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 8h05 foi **ativado em serverofi7**, conforme mostrado a seguir:
**05 08 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sss.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-GO** (sgo) foi configurado em serverofi7 sob o shell script **_sgo.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico e com mais documentos que o de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 8h05 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 06 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sgo.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-MA** (sma) foi configurado em serverofi7 sob o shell script **_sma.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 7h50 foi **ativado em serverofi7**, conforme mostrado a seguir:
**50 07 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sma.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-MG** (smg) foi configurado em serverofi7 sob o shell script **_smg.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 7h40 foi **ativado em serverofi7**, conforme mostrado a seguir:
**40 07 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sma.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-MS** (sul) foi configurado em serverofi7 sob o shell script **_sul.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 6h50 foi **ativado em serverofi7**, conforme mostrado a seguir:
**50 06 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sul.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-MT** (smt) foi configurado em serverofi7 sob o shell script **_smt.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 22h14 foi **ativado em serverofi7**, conforme mostrado a seguir:
**14 22 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _smt.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-PB** (smt) foi configurado em serverofi7 sob o shell script **_spb.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 8h00 foi **ativado em serverofi7**, conforme mostrado a seguir:
**00 08 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _spb.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-PE** (smt) foi configurado em serverofi7 sob o shell script **_spe.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 8h00 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 07 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _spe.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-PI** (smt) foi configurado em serverofi7 sob o shell script **_spi.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 9h10 foi **ativado em serverofi7**, conforme mostrado a seguir:
**10 09 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _spi.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-PR** (smt) foi configurado em serverofi7 sob o shell script **_spr.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 9h00 foi **ativado em serverofi7**, conforme mostrado a seguir:
**00 09 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _spr.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-RJ** (smt) foi configurado em serverofi7 sob o shell script **_srj.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 6h00 foi **ativado em serverofi7**, conforme mostrado a seguir:
**00 06 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _srj.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-RN** (smt) foi configurado em serverofi7 sob o shell script **_srn.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 8h10 foi **ativado em serverofi7**, conforme mostrado a seguir:
**10 08 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _srn.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-RS** (smt) foi configurado em serverofi7 sob o shell script **_srs.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 8h40 foi **ativado em serverofi7**, conforme mostrado a seguir:
**40 08 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _srs.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-SC** (smt) foi configurado em serverofi7 sob o shell script **_ssc.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalenbe ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 8h30 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 08 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _srs.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-SE** (smt) foi configurado em serverofi7 sob o shell script **_sse.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 7h10 foi **ativado em serverofi7**, conforme mostrado a seguir:
**10 07 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sse.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SES-SP** (smt) foi configurado em serverofi7 sob o shell script **_ses.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalenbe ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h30 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _ses.sh**

**Comment by ChicoLopes** [comment]
@botturam tendo o conjunto de coletas de dados e processamento para preparo de indexação em IAHx das 18 Secretarias de Estado da Saúde se completado fecha-se este issue, incluindo uma planilha onde constam horários de agendamento, shell-script responsável e estimativa de tempos de execução atuais ()jan/2023)

[SecretariasDeSaudeEstaduais.xlsx](https://github.com/bireme/db-processing/files/10469255/SecretariasDeSaudeEstaduais.xlsx)
