### ISSUE TITLE
Retirar link's de similares da página do DeCS

### ISSUE THREAD

**Issue by falbrito** [bireme/db-processing#88]
Retirar os seguintes link's de Similar da página do DeCS

- SciELO
- LIS
- PSI

Ver:
http://decs.bvsalud.org/cgi-bin/wxis1660.exe/decsserver/?IsisScript=../cgi-bin/decsserver/decsserver.xis&task=exact_term&show_tree_number=T&previous_page=homepage&interface_language=p&search_language=p&search_exp=Macaca%20mulatta&umls=all

**Comment by renatomurasaki** [comment]
Entendo que foi realizado. Acessi a página e não vi mais os links de similares.
