### ISSUE TITLE
proc. FIs provenientes do FI-Admin - like LILACS - OFI7

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#882]
Projetos Django - OFI5:/bases/apps/ofi_django_project 
Dowloads em OFI7 -  OFI7:/bases/fiadmin/databases

Todas as FIs têm correspondência na tabela /bases/lilG4/tabs/coletas.tab

Melhor deixar a LILACS por último. Não vejo problemas, mas, se todas as outras funcionarem, é mais garantido que ela funcione também.

- [x] aim
- [x] argmsal
- [x] bbo
- [x] bdenf
- [x] bdnpar
- [x] bds
- [x] bdsnic
- [x] bigg
- [x] bimena
- [x] binacis
- [x] brisa
- [x] bsaludni
- [x] cns-br
- [x] colecionasus
- [x] colnal
- [x] conass
- [x] ecos
- [x] hansen
- [x] homeoindex
- [x] inca
- [x] indexpsi
- [x] ins-peru
- [x] libocs
- [x] liboe
- [x] libope
- [x] libopi
- [x] libosa
- [x] libosp
- [x] ligcsa
- [x] lilacs
- [x] lipecs
- [x] medcarib
- [x] minsaperu
- [x] mmyp
- [x] mtci
- [x] pie
- [x] repincap
- [x] repositoriobvs
- [x] rhs
- [x] rsdm
- [x] sdg
- [x] sms-sp
- [x] unisalud
- [x] vetindex

**Comment by ChicoLopes** [comment]
@botturam o processamento de **ARGMSAL** (arg) foi configurado em serverofi7 sob o shell script **_arg.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalenbe ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 05h11 foi **ativado em serverofi7**, conforme mostrado a seguir:
**11 05 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _arg.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BDNPAR** (bdn) foi configurado em serverofi7 sob o shell script **_bdn.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalenbe ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 21h25 foi **ativado em serverofi7**, conforme mostrado a seguir:
**25 21 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bdn.sh**

**Comment by ChicoLopes** [comment]
Bioética, Diplomacia e Saúde demanda geração para regional e bioética, função idsso necessita ter um diretório próprio para bioética na árvore /bases/lil.G4 (no caso bio.iah)

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BDSNIC** (bsn) foi configurado em serverofi7 sob o shell script **_bsn.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx identico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 00h56 foi **ativado em serverofi7**, conforme mostrado a seguir:
**56 00 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bsn.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **AIM-AFRO** (aim) foi configurado em serverofi7 sob o shell script **_aim.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda-feira às 30h17 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 17 * * 1      /usr/local/bireme/misc/cronCelery.sh _aim.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BIGG** (big) foi configurado em serverofi7 sob o shell script **_big.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 21h20 foi **ativado em serverofi7**, conforme mostrado a seguir:
**20 21 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _big.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BBO** (bbo) foi configurado em serverofi7 sob o shell script **_bbo.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 17h00 foi **ativado em serverofi7**, conforme mostrado a seguir:
**00 17 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bbo.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BIMENA** (bim) foi configurado em serverofi7 sob o shell script **_bim.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 13h30 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 13 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bim.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BINACIS** (bin) foi configurado em serverofi7 sob o shell script **_bin.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 17h30 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 17 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bin.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BDENF** (bde) foi configurado em serverofi7 sob o shell script **_bde.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ou melhor ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 20h15 foi **ativado em serverofi7**, conforme mostrado a seguir:
**15 20 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bde.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BRISA** (bri) foi configurado em serverofi7 sob o shell script **_bri.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 21h30 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 21 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bri.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **BSaludNi** (msn) foi configurado em serverofi7 sob o shell script **_msn.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx idêntico ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 0h55 foi **ativado em serverofi7**, conforme mostrado a seguir:
**55 00 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _msn.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **CNS-BR** (cns) foi configurado em serverofi7 sob o shell script **_cns.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 17h15 foi **ativado em serverofi7**, conforme mostrado a seguir:
**15 17 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _cns.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **colecionaSUS** (sus) foi configurado em serverofi7 sob o shell script **_sus.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h40 foi **ativado em serverofi7**, conforme mostrado a seguir:
**40 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sus.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **colnal** (sus) foi configurado em serverofi7 sob o shell script **_cna.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h00 foi **ativado em serverofi7**, conforme mostrado a seguir:
**00 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _cna.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **CONASS** (con) foi configurado em serverofi7 sob o shell script **_con.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 21h35 foi **ativado em serverofi7**, conforme mostrado a seguir:
**35 21 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sus.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **ECOS** (eco) foi configurado em serverofi7 sob o shell script **_eco.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sábado às 23h30 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 23 * * 1-6      /usr/local/bireme/misc/cronCelery.sh _eco.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **HANSEN** (han) foi configurado em serverofi7 sob o shell script **_han.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 21h55 foi **ativado em serverofi7**, conforme mostrado a seguir:
**55 21 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _han.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **HOMEOINDEX** (hom) foi configurado em serverofi7 sob o shell script **_hom.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 22h25 foi **ativado em serverofi7**, conforme mostrado a seguir:
**25 22 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _hom.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **INCA** (inc) foi configurado em serverofi7 sob o shell script **_inc.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 21h45 foi **ativado em serverofi7**, conforme mostrado a seguir:
**45 21 * * 2      /usr/local/bireme/misc/cronCelery.sh _inc.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **INS-PERÚ** (pin) foi configurado em serverofi7 sob o shell script **_pin.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 19h50 foi **ativado em serverofi7**, conforme mostrado a seguir:
**50 19 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _pin.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **IndePSI** (psi) foi configurado em serverofi7 sob o shell script **_psi.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 22h10 foi **ativado em serverofi7**, conforme mostrado a seguir:
**10 22 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _psi.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **LIBOCS** (boc) foi configurado em serverofi7 sob o shell script **_boc.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h15 foi **ativado em serverofi7**, conforme mostrado a seguir:
**15 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _boc.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **LBOE** (boe) foi configurado em serverofi7 sob o shell script **_boe.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h10 foi **ativado em serverofi7**, conforme mostrado a seguir:
**10 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _boe.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **LIBOPE** (bpe) foi configurado em serverofi7 sob o shell script **_bpe.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h12 foi **ativado em serverofi7**, conforme mostrado a seguir:
**12 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bpe.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **LIBOPI** (bop) foi configurado em serverofi7 sob o shell script **_bop.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h13 foi **ativado em serverofi7**, conforme mostrado a seguir:
**13 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bop.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **LIBOSA** (bsa) foi configurado em serverofi7 sob o shell script **_bsa.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h09 foi **ativado em serverofi7**, conforme mostrado a seguir:
**09 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bsa.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **LIGCSA** (glc) foi configurado em serverofi7 sob o shell script **_glc.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 16h30 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 16 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _glc.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **LIBOSP** (bsp) foi configurado em serverofi7 sob o shell script **_bsp.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h14 foi **ativado em serverofi7**, conforme mostrado a seguir:
**14 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _bsp.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **LIPECS** (lip) foi configurado em serverofi7 sob o shell script **_lip.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 5h45 foi **ativado em serverofi7**, conforme mostrado a seguir:
**45 05 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _lip.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **MEDCARIB** (med) foi configurado em serverofi7 sob o shell script **_med.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de quarta-feira às 22h15 foi **ativado em serverofi7**, conforme mostrado a seguir:
**15 22 * * 3      /usr/local/bireme/misc/cronCelery.sh _med.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **MinSaPeru** (pru) foi configurado em serverofi7 sob o shell script **_pru.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 1h20 foi **ativado em serverofi7**, conforme mostrado a seguir:
**20 01 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _pru.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **MMYP** (per) foi configurado em serverofi7 sob o shell script **_per.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de quarta-feira às 21h30 foi **ativado em serverofi7**, conforme mostrado a seguir:
**30 21 * * 3      /usr/local/bireme/misc/cronCelery.sh _per.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **PIE** (pie) foi configurado em serverofi7 sob o shell script **_pie.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 22h20 foi **ativado em serverofi7**, conforme mostrado a seguir:
**20 22 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _pie.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **REPINCAP** (rin) foi configurado em serverofi7 sob o shell script **_rin.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 5h35 foi **ativado em serverofi7**, conforme mostrado a seguir:
**35 05 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _rin.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **RHS** (rhs) foi configurado em serverofi7 sob o shell script **_rhs.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 21h00 foi **ativado em serverofi7**, conforme mostrado a seguir:
**00 21 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _rhs.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **SMS-SP** (sms) foi configurado em serverofi7 sob o shell script **_sms.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 23h45 foi **ativado em serverofi7**, conforme mostrado a seguir:
**45 23 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _sms.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **RepositorioBVS** (red) foi configurado em serverofi7 sob o shell script **_red.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. Com isso o **agendamento Celery de serverofi5 foi desativado** e um agendamento **crontab** para execução de segunda a sexta-feira às 19h55 foi **ativado em serverofi7**, conforme mostrado a seguir:
**55 19 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _red.sh**

**Comment by ChicoLopes** [comment]
@botturam o processamento de **UNISALUD** (uni) foi configurado em serverofi7 sob o shell script **_uni.sh** em **/bases/lilG4/shs.lil**, sua execução resultou um arquivo XML para indexação em IAHx equivalente ao de serverofi5. O **agendamento Celery de serverofi5 inexistia** e um agendamento **crontab** para execução de segunda a sexta-feira às 19h25 foi **ativado em serverofi7**, conforme mostrado a seguir:
**25 19 * * 1-5      /usr/local/bireme/misc/cronCelery.sh _uni.sh**

**Comment by botturam** [comment]
concluído.
