### ISSUE TITLE
COVIDWHO - migração OFI5 -> OFI7 - fase Xisto01/PENTAHO

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#887]
1) criar chaves públicas entre OFI7 e xisto01 para usuário "pentaho" (ida e volta).

2) alterar os shells de transferência dos arquivos CSVs no servidor Xisto01:

pentaho@xisto01:/home/apps/pentaho/pentaho-server/tomcat/bin/who$ grep ofi5 *sh|cut -f1 -d\:|sort -u
scp_csv_allow.sh
scp_csv_blocked.sh
scp_csv_del.sh
scp_csv_gr.sh
scp_csv_pp.sh
scp_csv_pp_upd.sh
scp_csv.sh
scp_csv_upd.sh
scp_csv_zh.sh

Creio que seja melhor mandar para os 2 servidores, neste momento. Depois, eliminamos o envio para OFI5.

**Comment by ChicoLopes** [comment]
@botturam Chaves Públicas de Autenticação implantadas, permitindo operações originadas em OFI7 pelos usuários operacao e transfer para xisto01 como usuário pentaho, o reverso também é possível, operacções originadas por pentaho em xisto01 para serverofi7 como usuários operacao ou transfer.

**Comment by ChicoLopes** [comment]
@botturam Os nove shell-scripts foram editados de forma a efetuarem cópias de arquivos correspondentes de xisto01 para serverofi5 e serverofi7 com destino aos diretórios devidos, ressaltando que em serverofi7 foram criados os diretórios ainda não existentes para receber os arquivo copiados.

**Comment by ChicoLopes** [comment]
@botturam aguardando teste final para fechamento deste issue

**Comment by botturam** [comment]
concluído
