### ISSUE TITLE
CRONTAB OFI5 - verificar execuções

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#888]
Chico, poderia verificar o que são e se deven ir para OFI7? obrigado

# Verificacao diaria de arquivos (des)atualizados - EM TESTE
05 12 * * * ~/fjl/ver_atual/ver_atual.sh

# CRONTAB a ser usado em SERVEROFI5 pelo usuario operacao

07 00 * * * /usr/local/bireme/misc/infra/replica_cron.sh
07 00 * * * bin/avaliaLogdeEMAIL.sh
57 02 * * * bin/avaliaLogNEWPROC.sh

**Comment by botturam** [comment]
verificar também - CRON - OFI5 
# Coleta de dados dos SciELOs certificadosd
0 5 * * 2 /bases/org.000/tpl.org/pollSelect.sh > /bases/org.000/outs/`date '+\%F'`.PS.txt &
0 5 * * 4 /bases/org.000/tpl.org/pollSelect.sh > /bases/org.000/outs/`date '+\%F'`.PS.txt &

**Comment by ChicoLopes** [comment]
@botturam inicialmente os dois agendamentos de pollSelect.sh foram reunidos em uma só entrada de crontab, o shell em si foi deslocado para o caminho /bases/lilG4/lxp.sci/exec/ ao invéz do original /bases/org.000/tpl.org/ e foi revisado para retirar a implantação de ambiente de execução (desnecessária por ser escalado via $MISC/cronArg_01.sh), efetuar a varredura apenas dos SciELOs não coletados por OAI-PMH, e incluída uma explicação de finalidade pelo uso da opção --info (ou -i) na chamada em linha de comando. O log de execução é acumulado na árvora /bases/logs/crontabs/ sob as denominações acc_pollSelect.out (acumulado de todas as execuções deste a eliminação deste arquivo) e pollSelect.txt o log da última execução exclusivamente.

**Comment by ChicoLopes** [comment]
@botturam o shell replica_cron.sh está com seu agendamento ativo para execução diária às 7H00. Automáticamente ele determina se houve alguma mudança no agendamento por meio de cálculo de MD5 do arquivo replica confrontado com o resultado de 'crontab -l', havendo alteração na tabela de agendamento ele provê um replicação da mesma no arquivo cron_operacao.txt, no diretório home do usuário operação. (na verdade qualquer usuário pode fazer uso deste shell, pois ele se baseia no LOGNAME corrente da sessão criada pelo daemon cron)

**Comment by ChicoLopes** [comment]
@botturam relativamente a **bin/avaliaLogdeEMAIL.sh** e a **bin/avaliaLogNEWPROC.sh** os mesmo não foram portados para o servidor ServerOFI7 e se o forem deve haver uma alteração importante, pois na versão do S.O. em suo não existe o diretório **bin** no home do usuário, mas sim **.local/bin**.
A função original de **_bin/avaliaLogNEWPROC.sh_** é mover arquivos LOG presentes em **/bases/logs/newproc/** sem sinalização de falhas para o subdiretorio OK, no entanto apenas processos relacionados a coletas e pos-coletas OAI estão depositando arquivos na árvore **/bases/logs/newproc**/ que são relatórios de resultado de coleta e não logs de execução.
A função original de **_bin/avaliaLogdeEMAIL.sh_** é mover para diretório **OKs** os arquivos '.**log**' contendo a cadeia **_digo de retorno: 0_**,  no entanto, apesar de escalado em ServerOFI5, não surte efeito desde maio de 2017.

**Comment by botturam** [comment]
concluído
