### ISSUE TITLE
WPRIM - transferir para OFI7  + executar proc. regular quadrimenstral

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#891]
[WPRIM WPRO vrs2.2.docx](https://github.com/bireme/db-processing/files/10813951/WPRIM.WPRO.vrs2.2.docx)

**Comment by ChicoLopes** [comment]
@botturam o processamento de WPRIM teve problemas com os dados do último lote (11/01/2023) devido haver demasiadas ocorrências de palavra-chave do autor (campo 85 na metodologia LILACS). Foi incluída uma operação de limitação de ocorrências que sempre que houverem mais de 10 delas, só as cinco primeiras são mantidas e as demais são eliminadas. Tal tratamento foi inserido em **3_Customiza_WPRIM.sh** (chamada durante **pos_coleta_oai.sh**) no tratamento do campo v85 ,sendo o seguinte o tratamento dado:

`$CISIS/mx trash$$_1_6a create=trash$$_1_7 "proc=if nocc(v85) > 10 then 'd85','<85 0>',v85[1],'</85><85 0>',v85[2],'</85><85 0>',v85[3],'</85><85 0>',v85[4],'</85><85 0>',v85[5],'</85>' fi" -all now tell=30001`

Em execução fracionada do processamento de WPRIM (execução normal esta em /bases/lilG5/shs.lil/_wpr.sh), os resultados foram os esperados e os tempos de execução de cada parte do processamento geral foram:

**00:58:06** pos_coleta_oai.sh
**00:02:46** pre_saneamento_fi.sh
**03:48:49** iah_like_lilacs_fi.sh
**05:09:49** iahx_xml_geral_fi.sh

Ou seja praticamente 10 horas de processamento, que resultaram em 912037 documentos no XML wpr_regional.xml

O próximo passo é verificar uma execução completa por agendamento (já disparada, com término previsto para perto das 21h de hoje)
