### ISSUE TITLE
Saúde indígina - FSI - OFI7 - verificar URL de coleta

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#892]

**Comment by botturam** [comment]
Não aumenta desde o começo do mês:

https://pesquisa.bvsalud.org/saudeindigena/

**Comment by ChicoLopes** [comment]
@botturam verififcando os URLs de coleta (MODS e DIM) a resposta obtida é erro 503, serviço indisponível. Caso na FIOC tenha havido alguma alteração, não fomos comunicados.
Como primeira medida passei para o Marcos Mori um e-mail com os URLs disfuncionais solicitando que ele entre en contato com a Fio Cruz, para verificar se houve alteração ou se o serviço está temporariamente fora do ar.

**Comment by botturam** [comment]
novo alerta foi emitido ao Mori, que já entrara em contato com eles, por e-mail, mas não obtivemos resposta.

**Comment by botturam** [comment]
coleta restabelecida novamente.
