### ISSUE TITLE
ODS 3 Meta 3.1 - Tema 6: Reduzir a mortalidade materna: Violência e Desastres

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#894]
Estratégia de busca em:
https://bvsalud.org/queries/search_strategy/ods-3-meta-3-1-reduzir-a-mortalidade-materna-violencia-e-desastres/

**Comment by botturam** [comment]
@pintoros disponível em produção. Pedir ao Mori para traduzir **5_violence_disasters**

**Comment by pintoros** [comment]
@marcoslmori chamado OCOMON N.º 9074

**Comment by botturam** [comment]
processamento concluído.
