### ISSUE TITLE
2.1 - Processamento de bases de dados - Marcelo

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#896]

**Comment by botturam** [comment]
@viniciusandrade @heitorbarbieri @wilsonmoura  processamento OFI DeCS-2023 concluído:

1) DOLOMITA02:
* Esse diretório VMX deverá ser copiado para dolomita02 - verificar diretório (PERGUNTAR PARA VÍNICIUS)
cd /bases/dec.000/dec.dec/outputvmx
scp -pr decs* para transfer@dolomita02:/home/apps/bvs.br/wp-decs/www/bases/vmx/

2) VINICIUS:
Os arquivos XML de DeCS 2020 utilizados para a geração/atualização dos índices MH e MJ já estão disponíveis para uso, no path abaixo:

serverofi5:/bases/dec.fre/dec.dec/outputiahx/decs-metadata-2020.xml
serverofi5:/bases/dec.fre/dec.dec/outputiahx/decsterm_en.xml
serverofi5:/bases/dec.fre/dec.dec/outputiahx/decsterm_es.xml
serverofi5:/bases/dec.fre/dec.dec/outputiahx/decsterm_fr.xml
serverofi5:/bases/dec.fre/dec.dec/outputiahx/decsterm_pt.xml

3) HEITOR:
O DeCS 2020 foi atualizado e está disponível nova versão em serverofi5:/usr/local/bireme/tabs

decs.mst
decs.xrf
decs.id

4) KATIA:
O DeCS 2023 para o LILDBI-Web está disponível em: 
serverofi5:/bases/dec.000/dec.dec/output/DeCS2023.zip

**Comment by viniciusandrade** [comment]
@botturam obrigado.

Realizei hoje a atualização do DeCS de processamento Solr em:

**OFI6:/home/javaapps/iahx-server/docker/solr5/resources/**

Pelo que entendi não temos mais processamento Solr 1.3 pois não localizei na serverofi6 os caminhos relativos a estes índices.

Qualquer problema relativo a esta atualização favor entrar em contato.

**Comment by viniciusandrade** [comment]
@botturam diretório VMX copiado para o servidor galena01 (a aplicação foi migrada da dolomita02 para este servidor no final de 2022).

**Comment by botturam** [comment]
atualizações em mdlG4, lilG4 e $TABS concluídas.

**Comment by botturam** [comment]
documentação sobre o galena01 modificada.
