### ISSUE TITLE
Processamento mensal para troca de Indexação MEDLINE para LILACSExpress (FI-ADMIN) - Campos: Descritores Primários[87] e Secundário [88]

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/db-processing#897]
Por favor, fazer o processamento da troca de indexação MEDLINE mensal.
Informação no issue #831 e #815

**Comment by botturam** [comment]
@anakatiacamilo processamento concluído. São 1.694 docs encontrados: Seguem os arquivos:

OFI7:/bases/mdlG4/v87.mdl/lxp_mdl_ALL_v71_fiadmin.txt
OFI7:/bases/mdlG4/v87.mdl/lxp_mdl_ALL_v76_fiadmin.txt

OFI7:/bases/mdlG4/v87.mdl/lxp_mdl_8788_ALL.xrf
OFI7:/bases/mdlG4/v87.mdl/lxp_mdl_8788_ALL.mst

**Comment by anakatiacamilo** [comment]
Finalizado o Processo, Obrigado @botturam
