### ISSUE TITLE
Criação de link simbólico dos arquivos schema.xml e solrconfig.xml - OFI6

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#902]
deixar links simbólicos de schema.xml e solrconfig.xml (porta 5), em OFI6, iguais aos disponíveis em OFI5.

operacao@OFI5:/home/javaapps/iahx-server/indexes/solr5-port5/mdl5/conf $ ll

lrwxrwxrwx 1 tomcat operacao    69 Oct 21  2016 schema.xml -> /home/javaapps/iahx-server/indexes/solr5-port6/portal/conf/schema.xml
lrwxrwxrwx 1 tomcat operacao    73 Oct 21  2016 solrconfig.xml -> /home/javaapps/iahx-server/indexes/solr5-port6/portal/conf/solrconfig.xml

**Comment by ChicoLopes** [comment]
@botturam efetuada a ciração de links simbólicos para os arquivos schema.xml e solrconfig.xml, no diretório:
ServerOFI6:/home/javaapps/iahx-server/indexes/solr5-port5/mdl5/conf
os links apontam para os arquivos equivalentes do diretório:
/home/javaapps/iahx-server/indexes/solr5-port6/portal/conf/

Por favor confirme a operação correta do sistema

**Comment by botturam** [comment]
concluído.
