### ISSUE TITLE
GIM - tabular quantidades de documentos totais por Revista (ta) e Tipo de Documento (type)

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/db-processing#903]
@botturam, por favor, verificar #817 , obrigado.

**Comment by heitorbarbieri** [comment]
Obs: Estatísticas referentes ao ano 2022.

**Comment by botturam** [comment]
sobre revistas, seguem os números:

AIM (AFRO) - 521
IMEMR (EMRO) - 736
IMSEAR (SEARO) - 51
LILACS - 2.324
WPRIM - 718

total - 4.350 títulos de revistas (sem repetidos)
---------------
sobre o tipo de documento:

2.015.593 (Sas) / 2.328.629 (total de docs) = 0,86 (86%) de Journal Article.
1.953.548 (Sas) / 

falta revisar.

**Comment by heitorbarbieri** [comment]
@botturam 

O cálculo abaixo está exatamente o mesmo do #817

2.015.593 (Sas) / 2.328.629 (total de docs) = 0,86 (86%) de Journal Article.

Por favor, confira.

**Comment by botturam** [comment]
não é o mesmo... coloquei falta revisar. Não fiz também o cálculo na linha de baixo.

**Comment by botturam** [comment]
sobre revistas, 2023, seguem os números:

AIM (AFRO) - 521
IMEMR (EMRO) - 736
IMSEAR (SEARO) - 51
LILACS - 2.327  (única que cresceu)
WPRIM - 718    

total - 4.322 títulos de revistas (sem repetidos)

--------------------------------------------------

2.064.109 (Sas)  /  2.380.203 (Total) = 0,86 (86%) de Journal Article.

**Comment by botturam** [comment]
@heitorbarbieri acho que está concluído.
