### ISSUE TITLE
CVSP - nova coleta substituta de Campusvirtualsp-Fiocruz

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#905]
testar coleta_oai.sh  com novo endereço fornecido pela FIOCRUZ:

operacao@OFI5:/bases/oai.pmh/tabs/cnf $ cat cfc.cnf
COLECAO > cfc
LISTSETS >
URL_OAI > https://brasil.campusvirtualsp.org/oai/request
URL_COMPLETA > **https://brasil.campusvirtualsp.org/oai?verb=ListRecords&metadataPrefix=oai_dc**
DIR_SAIDA > cfc-cvsp_campusvirtualsp_fiocruz
METADATAPREFIX > oai_dc
SISTEMA_OAI > dspace
SIGLA_3 >
DE_PARA > oai_dc_cfc
STATUS >
ARQUIVO_CUSTOMIZACAO > 3_Customiza_campusvirtualsp_fiocruz.sh
TRANSFORMA_XML >
CODIFICACAO > UTF8

----

msg Rosane Mendes:

Respondi um e-mail da Elisabeth Biruel sobre esta mesma questão similar esta semana.

1) O domínio [brasil.campusvirtualsp.org](https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fbrasil.campusvirtualsp.org%2F&data=05%7C01%7Cbotturam%40paho.org%7Cc37448fb99c94192a32d08db3054921b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638156912031202954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iFtyRTIj%2Fs%2B51Q0oEB3HwWRoabpv3yyUtbRFzXPMVrM%3D&reserved=0) está sob a gestão do CVSP Regional e direcionando para um servidor lá.  Por isso, a URL com o OAI não é mais válida.
2) Em relação ao acervo atual (já importado), alguns links de REA estarão quebrados, pois o servidor do repositório que a ENSP administrava foi retirado do ar.

Atualmente, o repositório de REA que integra acervos da Fiocruz, do CVSP e outras redes parceiras é a [Plataforma Educare](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Feducare.fiocruz.br%2F&data=05%7C01%7Cbotturam%40paho.org%7Cc37448fb99c94192a32d08db3054921b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638156912031202954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kMAzL9dlrT8EAqpSah8pDa%2B%2FkGBy8QO1llrBU0FFZl0%3D&reserved=0).
Sendo assim, solicito que efetuem a troca para o OAI da Plataforma [Educare](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Feducare.fiocruz.br%2F&data=05%7C01%7Cbotturam%40paho.org%7Cc37448fb99c94192a32d08db3054921b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638156912031202954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kMAzL9dlrT8EAqpSah8pDa%2B%2FkGBy8QO1llrBU0FFZl0%3D&reserved=0), indicado no link abaixo.
[https://educare.fiocruz.br/oai?verb=ListRecords&metadataPrefix=oai_dc](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Feducare.fiocruz.br%2Foai%3Fverb%3DListRecords%26metadataPrefix%3Doai_dc&data=05%7C01%7Cbotturam%40paho.org%7Cc37448fb99c94192a32d08db3054921b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638156912031202954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Bm8ZCYw4aW%2FU%2FISrf%2BOHEfJG28Pcv0oPC6KuNxws1WM%3D&reserved=0)

Em tempo, seria possível encaminhar o OAI do acervo do CVSP na Bireme para que possamos apontar através do Educare também?

**Comment by botturam** [comment]
Ele está coletando apenas a primeira página. Execução:

./coleta_oai.sh cfc

**Comment by ChicoLopes** [comment]
@botturam a primeira tomada de dados ocorre normalmente, apesar de um pouco demorada, contendo 100 registros, mas a continuação  com o argumento ‘resumptionToken’ retorna sempre ‘badArgument’, quebrando assim o fluxo de recuperação de dados. A avaliação criteriosa do token informado no primeiro bloco, não mostra irregularidades patentes, levando a crer que o problema é no service provider.

 **wget "https://educare.fiocruz.br/oai?verb=ListRecords&metadataPrefix=oai_dc" -O x** executa ok

Recebe o resumtionToken que ao ser usado em:

**wget "https://educare.fiocruz.br/oai?verb=ListRecords&resumptionToken=228329ace482fea136b12bfb9ccc60ff912c04da9baa0e51ac0578ebd1a152b04254e57df2cadbc265cb74b29ad28d5bfa649df5a2df2b16afc276f42e43734db6cb74ef0f4b407d3059e34d50d1a173b12372d5ccdc1bea21f6d53b1243c059769e8f1bfe582343bc5ee241c741258b8528a5b9" -O x** resulta em execução com error code "_badArgument_".

Diversos arranjos de URL foram tentados, com e sem filtro (from=), não obstante nenhum deu quaquer resultado satisfatório. 
pode ser que seja necessário perquerir à Fiocruz - Educare se há algo de diferencial para efetuar a coleta de complementos de lista de registros.

**Comment by botturam** [comment]
coleta não está funcionando. Conforme conversa com Mori, o erro é antigo.

**Comment by botturam** [comment]
coleta https://brasil.campusvirtualsp.org/oai?verb=ListRecords&metadataPrefix=oai_dc  parou de funcionar 
coleta https://educare.fiocruz.br/oai?verb=ListRecords&metadataPrefix=oai_dc não funciona
