### ISSUE TITLE
CVSP - revisão do schema e solrconfig

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#906]
verificar campos dos arquivos schema.xml e solrconfig.xml em OFI5 e OFI6 (abaixo, campo "node", que está apenas em OFI5):

tomcat@OFI5:/home/javaapps/iahx-server/indexes/cvsp/main/conf $ grep node schema.xml
   <field name="node"          type="text"     indexed="true"  stored="true"  multiValued="true"/>

OFI6:/home/javaapps/iahx-server/indexes/solr5-port3/cvsp/conf$ grep node schema.xml

**Comment by ChicoLopes** [comment]
@botturam em s**erverofi6:/home/javaapps/iahx-server/indexes/solr5-port3/cvsp/conf**, encontram-se os arquivos **schema.cvsp.xml** e **solrconfig.cvsp.xml** que representam o entendimento que eu pude ter das alterações que devem tornar a instância CVSP equivalente à que era processada em Solr3 no serverofi5.
Necessito de seu apoio para atingir um grau mínimo de confiança para efetuar a troca desses dois arquivos no processamento regular de CVSP para IAHx.

**Comment by botturam** [comment]
@ChicoLopes eu renomeie os arquivos .cvsp para os correntes oficiais, mas dá erro no processamento (logs/out-update.20230414.cvsp.txt.erro). Voltei como era antes e mudei os .csvp para .new 

Pode testar à vontade em OFI6. Do jeito que está, ninguém pode usar. Dá pau:

https://sites.bvsalud.org/rea/  (brasil)

IAHx:

https://pesquisa.bvsalud.org/cvsp/

**Comment by ChicoLopes** [comment]
@botturam realida a revisão de sorlconfig.xml que era o item que impedia o funcionamento correto, agora opera, restando uma avaliação da correção da indexação. Os arquivos solrconfig.xml e schema.xml estão tanto em ServerOFI6 quanto em iahx-idx01 mantidos com o nome sufixado por '.old'.as versões novas estão em uso além de haver uma cópia deles em ambos os servidores, sufixados com '.cvsp.new'.
Uma vez aprovada a nova composição dos arquivos, as cópias '.cvsp.new' poderão ser eliminadas.

**Comment by botturam** [comment]
Concluído. Arquivos de configuração revisados.
