### ISSUE TITLE
migração interface IAH de Basalto02 para IAH-IDX01

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#907]

**Comment by ChicoLopes** [comment]
@botturam o sistema de busca iAH foi transferido para o novo servidor iah-idx01.bireme.br (IP. 200.10.179.214) e ao que tudo indica está operando de forma compatível com a instalação antiga (basalto02.bireme.br [200.10.179.211]). Seria recomendável que sejam efetuados mais testes.
Ocorrendo aprovação nestes testes adicionais o suporte poderá efetuar a  manobra devida no servidor de DNS para o domínio bases.bireme.br apontar o novo servidor e o domínio bases2023.bireme.br ser eliminado.

**Comment by ChicoLopes** [comment]
@botturam solucionado pelo suporte o problema de acesso ao formulário iAH em **iah-idx01.bireme.br** que agora responde pelo domínio **bases.bireme.br** e que estava apresentando a mensagem **_Forbidden_** após o reapontamento de DNS.

No diretório /home/www/htdocs, está disponível uma página html que contém um link para o formulário iAH que empreende buscas nas bases:

- 	LILACS
- 	CidSaude
- 	PAHO
- 	REPIDISCA
- 	DESASTRES
- 	ADOLEC
- 	BBO
- 	BDENF
- 	Homeoindex
- 	MedCarib
- 	WHOLIS
- 	IBECS

O URL direto para o formulário pode ser o seguinte:

`https://bases.bireme.br/cgi-bin/wxislind.exe/iah/online/?IsisScript=iah/iah.xis&base=LILACS&lang=p&form=A`

Foram transferidos também arquivos relativos a link com outras bases como **iahinks**; **iah2spa** etc.

**Comment by ChicoLopes** [comment]
@botturam a documentação do roteiro básico de setup do servidor para uso com a interface iAH está descrito no documento intitulado **SetupUsuarioIAH-IDX01-rev00.docx**, o qual é carregado este comentário.

[SetupUsuarioIAH-IDX01-rev00.docx](https://github.com/bireme/db-processing/files/11225599/SetupUsuarioIAH-IDX01-rev00.docx)

**Comment by botturam** [comment]
@ChicoLopes excelente. Agora aguardemos o Marco apontar apontar para o IAH-idx01.
