### ISSUE TITLE
IAHx- Portal Regional - revisar rotina de transferência do índice SoLR5 em OFI6

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#908]
supostamente, após a conferência dos arquivos MD5 entre OFI6 e IAHx-idx02 e Basalto02, do Portal regional, com diferença entre ambos, as decisões de apagar/mover diretórios no destino estão comprometidas. 

O resultado final do processamento resultou no seguinte:

transfer@iahx-idx02:/home/javaapps/iahx-server/indexes/solr5-port6/portal/data $ ll
total 20
drwxrwsr-x 5 transfer operacao 4096 Apr  4 22:17 ./
drwxrwsr-x 4 transfer operacao 4096 May 31  2022 ../
drwxrwxr-x 2 transfer operacao 4096 Apr  4 22:17 index/
drwxrwsr-x 2 transfer operacao 4096 Apr  4 14:59 index.bad/
drwxrwsr-x 2 transfer operacao 4096 Nov 10 11:11 tlog/

transfer@iahx-idx02:/home/javaapps/iahx-server/indexes/solr5-port6/portal/data $ ll index
total 80
drwxrwxr-x 2 transfer operacao  4096 Apr  4 22:17 ./
drwxrwsr-x 5 transfer operacao  4096 Apr  4 22:17 ../
-rw-rw-r-- 1 transfer operacao 68910 Apr  3 10:14 _136h.fnm
-rw-rw-r-- 1 transfer operacao   366 Apr  3 09:59 _136h.nvm
-rw-rw-r-- 1 transfer operacao     0 Mar 23 15:23 write.lock
transfer@iahx-idx02:/home/javaapps/iahx-server/indexes/solr5-port6/portal/data $ ll index.bad/
total 534761136
drwxrwsr-x 2 transfer operacao         4096 Apr  4 14:59 ./
drwxrwsr-x 5 transfer operacao         4096 Apr  4 22:17 ../
-rw-rw-r-- 1 transfer operacao  63237356704 Apr  4 07:29 _136f.fdt
-rw-rw-r-- 1 transfer operacao     29035182 Apr  4 07:29 _136f.fdx
-rw-rw-r-- 1 transfer operacao        68910 Apr  4 10:34 _136f.fnm
-rw-rw-r-- 1 transfer operacao 118700474807 Apr  4 10:22 _136f_Lucene50_0.doc
-rw-rw-r-- 1 transfer operacao 240963296464 Apr  4 10:22 _136f_Lucene50_0.pos
-rw-rw-r-- 1 transfer operacao   4043349803 Apr  4 10:22 _136f_Lucene50_0.tim
-rw-rw-r-- 1 transfer operacao     82575974 Apr  4 10:22 _136f_Lucene50_0.tip
-rw-rw-r-- 1 transfer operacao   1075645207 Apr  4 10:23 _136f.nvd
-rw-rw-r-- 1 transfer operacao          366 Apr  4 10:23 _136f.nvm
-rw-rw-r-- 1 transfer operacao          549 Apr  4 10:34 _136f.si
-rw-rw-r-- 1 transfer operacao 119378733616 Apr  4 10:34 _136f.tvd
-rw-rw-r-- 1 transfer operacao     84759434 Apr  4 10:34 _136f.tvx
-rw-rw-r-- 1 transfer operacao          170 Apr  4 10:34 segments_hms
-rw-rw-r-- 1 transfer operacao            0 Mar 23 15:23 write.lock

**Comment by ChicoLopes** [comment]
@botturam seguem apontamentos relacionados com os servidores iahx-idx01 e iahx-idx02 em relação às rotinas envolvidas com restart de servidores SoLR e atualização de índices.

Caminho e nome do shell-script que carrega e prepara o ambiente para execução do **atualizaIAHx.sh** suas funções são:
1- Carregar ambiente de execução com variáveis gerais
2- Garantir existência de diretório de registro de execução (**/home/users/operacao/regshell**)
3- Efetuar o registro de execução não interativa
4- Austar variáveis do shell em execução (**PRGEXE; PRGNAM; PRGDIR**)
5- Chamar a rotina de atulização de dados se disponíveis (**atualizaIAHx.sh**)
6- Emitir e-mail de execução da reinicialização de IAHx e tentativa de atualização de índices

`/home/javaapps/iahx-server/bin/ReiniciaIAHxGeral.sh`

Caminho e nome do shell-script que efetua a reinicialização dos servidores SoLR e atualização de índices se necessário:

`/home/javaapps/iahx-server/bin/atualizaIAHx.sh`

As operações deste shell-script são as seguintes:
1- Baixa servidores iahx-server ativos
2- Com base nos arquivos _vira.XXXX.flg_ presentes rotaciona diretorio index da instância
    a) elimina **index.old** presente (se houver)
    b) renomeia **index** para **index.old**
    c) renomeia **index.new** para **index**
3- Dispara servidores iahx-server
4- Verifica se retorna o número de documentos esperado
    a) caso difira
         i) efetua o roll-back da instância
            - renomeia **index** para **index.alt**
            - renomeia **index.old** para **index**
        ii) efetua restart do servidor da instancia defectiva
       iii) emite e-mail indicando a condição defectiva
    b) caso esteja correto
        i) emite e-mail indicando a condição de sucesso
 5- Coloca flag no historico (**/home/javaapps/iahx-server/indexes/historic**) prefixando a data ISO no nome do flag

Exemplo conteúdo de flag (explo. binacis)
```
solr5-port3/binacis/data/index|Virada liberada em (Mon) 2022-10-31 03:30:00
http://basalto01.bireme.br:8983/solr/binacis/select/?q=*:*&rows=1
205229

```

_OBSERVAÇÃO_: o shell-script atualizaIAHx.sh **pode** ser chamado da linha de comando de uma sessão interativa, desde que logado como o usuário 'operacao'

**Comment by ChicoLopes** [comment]
@botturam efetuados ensaios com a rotina atualizaIAHx.sh no servidor basalto02 para determinar o mau funcionamento ocorrido recentemente com a atualização do portal.

Testes realizados:
1- pacote de dados (**index.new**) em perfeitas confições e conformidade como flag vira.portal.flg
2- pacote de dados ausente (diretório **index.new** presente porém vazio)
3- pacote de dados (**index.new**) com quantidade de documentos diferente da esperada pelo flag vira.portal.flg
4- pacote de dados (**index.new**) incompleto, simulando uma má transferência de arquivos

Resultados obtidos:
Teste número 1 - pacote de dados com qualidade 100%
A rotação de diretórios foi efetuada com êxito e o teste subsequênte de  quantidade de documentos recuperados também.
STATUS: Ok com interface plenamente operacional

Teste número 2 - pacote de dados ausente
Teste número 3 - pacote de dados mau transferido (incompleto)
A rotação de diretórios foi efetuada com êxito eo teste subsequênte de quantidade de documento recuperados informou "'NADA' documentos" (a variável que recebe o numero de documentos permanece não setada, vazia mesmo), o que levou à interpretação de sucesso (decisão de implementação de anos atrás), conforme o teste realizado pela declaração:
`[ "$QTD_esperada" -eq "${QTD_lida:-$QTD_esperada}" ]`
STATUS: Ok com interface não operacional

Teste número 4 - pacote bem transferido porém com o número de documento divergente do flag de virada
A rotação de diretórios foi efetuada com êxito eo teste subsequênte de quantidade de documento recuperados informou um número de documentos menor (ou maior que seja) ao esperado segundo o flag vira.portal.flg, o que levou ao roll-back da rotação de diretórios, deixando o diretório denomiinado anteriormente **index.new** com o nome **index.alt** (anteriormente seria **index.bad**), e mantido o conjunto de dados anterior à tentativa de atualização.
STATUS: Nok com a interface operacional

Com a troca da declaração de teste para: 
`[ "$QTD_esperada" -eq "${QTD_lida:-0}" ]`
os teste número 2 e 3 resultariam STATUS Nok, com a interface operacional, obviamente sem atualização dos dados.

Obs.: A referida declaração  de teste se encontra no bloco comentado como
`# Testar operacao de cada instancia desrotacionando os defectivos`
no corpo do shell-script.

Uma versão do shell-script com a declaração de teste proposta foi deixada em **iahx-idx02:/home/javaapps/iahx-server/bin** e é demoninada: **atualizaIAHx.sh.v02**
Aguardando ser usada na troca de atualizaIAHx.sh nos servidores iahx-idx02 e iahx-idx01 se assim for decidido

**Comment by ChicoLopes** [comment]
@botturam conforme decidido em reunião ontem (17/abr) o shell-script de atualização dos dados e reinicilização dos servidores Solr nos servidores ahx-idx01 e iahxidx02 denominado atualizaIAH.sh foi alterado de forma a retirar os mecaninsmos de conferência de quantidade de documentos e roll-back em caso de divergência face o valor esperado, tornando-se assim um operação minimalista.
A versão que estava em uso até o momento, permanece no servidor na árvore de diretórios '**/home/javaapps/iahx-server/bin**' sob a demonimação **_atualizaIAHx.old.sh_**.
Uma versão intermediária do shell-script (**atualizaIAHx.v1_5.sh**) que alterava trecho da lógica de avaliação de resultado continua no servidores como histórico de versões e a nova versão está replicada com a denominação **atualizaIAHx.v2.sh**

Log da execução permanece no arquivo **/home/users/operacao/regshell/logcron.txt**, sendo que o log acumulado até o momento e que corresponde à versão anterior se mantém com a denominação _/home/users/operacao/regshell/logcron_da_versao_1.txt_

**Comment by botturam** [comment]
concluído. A etapa que gerava ".bad" não existe mais. Apenas a rotação dos diretórios index.old, index, index.new
