### ISSUE TITLE
revisão da Coleta OAI (coleta_oai.sh) - parar processamento em caso de erro.

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#909]
provavelmente, colocar verificação de erro nas execuções de "wget"  em coleta_oai.sh. 

Verificar se mais alguma outra alternativa ou providência.

**Comment by ChicoLopes** [comment]
@botturam a complexidade do processo está dificultando a completa análise, de toda forma agora pos_coleta_oai.sh sai com código de erro quando a coleta atual tiver menos registros que a última coleta válida (a que está em /basesoai.pmh/isis), permitindo asism a interrupção do processamento.
Verificquei que a condição de teste pode ser alterada para menor ou igual, ao invés de exclusivamente menor, mas não alterei para impactar o menos possível o estado atual da rotina

**Comment by botturam** [comment]
voltaremos a esse tema se necessário. Até o momento, as execuções das coletas OAI estão satisfatórias.
