### ISSUE TITLE
Harvesting da base do ICTRP/WHO - ensaios clínicos publicados dos Registros Primários

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/db-processing#91]
@botturam favor verificar meu e-mail que contém informação sigilosa sobre acesso e coleta dos metadados. Favor analisar o crawler e realizar a coleta dos arquivos XML dos ensaios clínicos para posterior análise dos metadados com vista a integrá-los na BVS Regional

**Comment by botturam** [comment]
Entramos no site, fizemos uma navegação, e não encontramos XMLs para download. O dado disponível está em HTML. A primeira página do link apresenta ranges de documentos que indicam links para os documentos individuais. Clicando em algum deles, é mostrada uma página HTML, mas sem indicações de formato XML para download.

Você poderia dar uma olhada?

**Comment by renatomurasaki** [comment]
@botturam já enviei mensagem para ICTRP perguntando se é possível coletar os registros de ensaios clínicos em formato XML. Vamos aguardar.

**Comment by renatomurasaki** [comment]
Encerrando issue. Em negociação com ICTRP a versão XML, a qual exige pagamento de licença anual para uso.
