### ISSUE TITLE
Analíticas com status "Apagado" continuam sendo recuperadas na pesquisa

### ISSUE THREAD

**Issue by silvalais** [bireme/db-processing#910]
Registros duplicados foram apagados e continuam aparecendo no portal regional da BVS

Teses: SES-RJ

id:1397121- Desafios do processo de implantação dos medicamentos das hepatites virais B e C no componente estratégico da assistência farmacêutica no Estado do Rio de Janeiro
id:1397131-Atenção odontológica aos pacientes diabéticos no contexto da equipe multiprofissional
id:1397142 -Atenção em saúde bucal no âmbito hospitalar: uma revisão de literatura
id:1397156 -Proposta de categorização dos serviços de alimentação no Estado do Rio de Janeiro com foco no risco sanitário de doenças transmitidas por alimentos
id:1395769 - Sistemas de informação na gestão de recursos humanos em saúde da Secretaria de Estado de Saúde do Rio de Janeiro

Exemplo:
Atenção odontológica aos pacientes diabéticos no contexto da equipe multiprofissional

![image](https://user-images.githubusercontent.com/37112458/230205439-2d93563f-783b-490d-864e-cd4f5df4c2c8.png)

![image](https://user-images.githubusercontent.com/37112458/230204784-45356e15-86fb-4cd6-b04d-0a6a8139a776.png)

**Comment by viniciusandrade** [comment]
@botturam poderia verificar se existe previsto no processamento tratamento para estes casos? Obrigado.

**Comment by botturam** [comment]
@viniciusandrade se os registros estiverem disponíveis para coleta, via API -- e estão --, então serão coletados. Não existe flag dizendo que são deletados.

**Comment by viniciusandrade** [comment]
@botturam talvez seja necessário realizar tratamento para estes casos. Agendei reunião para verificarmos a necessidade.

**Comment by botturam** [comment]
LOG de processamento que apagou os registros da base (existe um ERRO em OFI7:/bases/logs/celery/logs/cron_harv_fiadmin.out )

 -> Traz base fiadmin.iso para processamento ...

  1) Separa registros coletados do FI-Admin ( Cria base "upsert" )
     Com data de alteracao a partir de 2023-04-06
  ------------------------------------------------------------------------------------------------
    - Verifica existencia de atualizacoes
      *** Existem atualizacoes/insercoes para realizar
      --> Total de registros para atualizar/inserir: 780

  2) Separa da base "upsert" os registros a(v778) - reg_fiadmin e p(v778) - reg_lildbi
  ------------------------------------------------------------------------------------------------
     - Cria reg_fiadmin
     - Cria reg_lildbi

  3) Atualizacoes/Inclusoes - Registros que foram originados no FI-Admin - a(v778)
  ------------------------------------------------------------------------------------------------
     - Atualizacoes : 349
     - Insercoes    : 280

  4) Atualizacoes/Inclusoes - Registros criados no LILDBI-web que foram migrados - p(v778)
  ------------------------------------------------------------------------------------------------
     - Atualizacoes : 151
     - Insercoes    : 0

  5) Baixa lista de id's com status -1 (Rascunho), 2 (recusado) ou 3 (apagado) :
     - Verifica se existe esse id em v776^i da base consolidada e o apaga
  ------------------------------------------------------------------------------------------------

ERRO: Nao foi possivel coletar informacoes do MySQL
Nao foi verificado se existem delecoes para realizar !!!


  6) Baixa lista de id's que foram apagados fisicamente :
     - Verifica se existe esse id em v776^i da base consolidada e o apaga
  ------------------------------------------------------------------------------------------------

ERRO: Nao foi possivel coletar informacoes do MySQL
Nao foi verificado se existem delecoes para realizar !!!


  7) Realiza ajustes finais na base consolidada :
  ------------------------------------------------------------------------------------------------

   - Atualiza diretorio original

**Comment by botturam** [comment]
documentos baixados:

echo " -> Trazendo arquivo de IDs para processamento ..."

# Coleta registros
# status = (0 - LILACS-Express)
[ -f fia-status_0.id ] && rm fia-status_0.id
wget_fiadmin "0" "$dtwget"

# status = (1 - Publicado em LILACS)
[ -f fia-status_1.id ] && rm fia-status_1.id
wget_fiadmin "1" "$dtwget"

# status = (-2 - Submissao)
[ -f fia-status_-2.id ] && rm fia-status_-2.id
wget_fiadmin "-2" "$dtwget"

# status = (-3 - Migração)
[ -f fia-status_-3.id ] && rm fia-status_-3.id
wget_fiadmin "-3" "$dtwget"

**Comment by viniciusandrade** [comment]
@botturam obrigado pelo levantamento realizado.

Pelo que pude entender me parece que não existe na rotina atual um tratamento para os casos de status apagado e recusado (status 2 e 3 respectivamente).

Atualmente temos no FI-ADMIN com status 2 = 1955  e com status 3 = 17173 registros.

A sugestão seria criar um processo para coletar o ID destes documentos e realizar o delete na base de controle fiadmin ou diretamente no índice solr. 

Podemos discutir melhor na reunião. Obrigado.

**Comment by botturam** [comment]
acompanhar deleção de: 

https://fi-admin-api.bvsalud.org/api/bibliographic/?format=isis_id&id=446275

https://fi-admin.bvsalud.org/bibliographic/?page=&filter_owner=*&s=LILACS_original_id%3A305809&document_type=&filter_status=*&filter_indexed_database=&filter_collection=&filter_network=*

!ID 00000
!v002!446275 
!v091!2001-09-26T09:00:00 
!v093!2023-04-12T10:12:08 
!v001!AR144.1 
!v005!S 
!v006!as 
!v009!a 
!v038!^bilus 
!v040!es 
!v064!2000 
!v065!20000000 
!v071!Case Reports 
!v072!2 
!v076!Humans 
!v076!Male 
!v076!Aged 
!v084!2002-06-04 
!v113!p 
!v500!duplicidade id 1171815 
!v087!^dOBSTRUCCION DUODENAL/etiol 
!v087!^d8714 
!v088!^dOBSTRUCCION DUODENAL/diag 
!v088!^dOBSTRUCCION DUODENAL/radiogr 
!v088!^d7577 
!v088!^d755 
!v088!^d24501 
!v088!^dTOMOGRAFIA COMPUTARIZADA POR RAYOS X 
!v779!lil-305809 
!v904!LILACS 
!v092!import 
!v010!Vanrell, Andrés^1s.af 
!v012!Caso 4^ies 
!v013!Case 4 
!v014!^f325^l326 
!v030!Rev. argent. radiol 
!v031!64 
!v032!4 
!v035!0048-7619 
!v098!FONTE 
!v899!1.25.0-23 
!v776!FI-ADMIN^i446275^bLILACS 
!v778!305809 



=Marcelo, Bom Dia!

Segue exemplo: 

Caso 4 / Case 4
Vanrell, Andrés.
Rev. argent. radiol ; 64(4): 325-326, 2000. ilus
Artigo em Espanhol | LILACS | ID: lil-305809

[https://fi-admin.bvsalud.org/bibliographic/edit-analytic/446275](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffi-admin.bvsalud.org%2Fbibliographic%2Fedit-analytic%2F446275&data=05%7C01%7Cbotturam%40paho.org%7C2c3a28b867c14f36836b08db3b5ef71e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638169051275287277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nROsRYgzF4TRR0hiiRs%2B5pqXSS4Z4GcvoGL6QNOTgZc%3D&reserved=0)

Registro criado: 26 de Setembro de 2001 às 09:00 pelo usuário import

Código Centro Cooperante: AR144.1

Última edição realizada em 12 de Abril de 2023 às 10:12 pelo usuário marilda.perez

LILACS Original ID: 305809

**Comment by botturam** [comment]
o problema era nas chamadas para o mysql em **harv_fiadmin.sh**

operacao@OFI7:/bases/fiadmin/consolida/tpl $ cat mar
mysql -h osmio02.bireme.br -P6612 -uacesso_fiadmin -pfi_admin@BIR fi_admin -e\
"SELECT id FROM biblioref_reference WHERE "\`status"\` LIKE '-1' OR  "\`status"\` LIKE '2' OR "\`status"\` LIKE '3';" > deleta_status.lst

mysql -h osmio02.bireme.br -P6612 -uacesso_fiadmin -pfi_admin@BIR fi_admin -e\
"SELECT object_id FROM django_admin_log WHERE content_type_id = '42' AND action_flag = '3';" > deletados_fisicamente.lst
