### ISSUE TITLE
Proc. VTI/VTT - Veterinária - Erro no processamento regular

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#934]
A VTI e VTT pararam de processar em 01 de maio:

OFI7:/bases/iahx/xml-inbox/regional $ ll vti_regional.xml vtt_regional.xml
-rw-r--r-- 1 operacao operacao 528305283 May  1 23:05 vti_regional.xml
-rw-rw-r-- 1 operacao operacao 174406300 May  1 19:25 vtt_regional.xml

Está dando pau na coleta OAI (elas são coleta OAI + porção FI-ADMIN). Como há movimentação à migração para Fi_ADMIN, talvez tenham desabilitado alguma coisa.

Os LOGS são:
OFI7:/bases/logs/celery/logs $ ll vti.txt vtt.txt

-rw-rw-r-- 1 operacao operacao 3460 May 16 16:45 vti.txt
-rw-rw-r-- 1 operacao operacao 3460 May 16 17:35 vtt.txt

**Comment by ChicoLopes** [comment]
@botturam efetuei as mudança possíveis como combinado, no entanto a base LILACS que você pediu para não alterar a dada não é possível, pois ela é reconstruída no processamento e não simplesmente copiada.

As fontes que têm múltiplas partes, _por conseguinte as que tem apenas uma também_, resultam de um append das “diversas” partes resultantes da comparação uma a uma que é onde se escolhe aquelas com mais documentos. Ou seja, você deve olhar para o diretório com as parciais, por exemplo, ao invés de olhar as datas do diretório **cum**, deve olhar o diretório **cum-cumed**, ao invés de olhar **who**, deve olhar os diretórios **who-com_10665_107131**; **who-com_10665_113205**; **who-com_10665_126384**; **who-com_10665_1375187**; **who-com_10665_1637**; **who-com_10665_164806**; e **who-com_10665_8** e assim por diante.

Mas pelo menos a parte proveniente de FI-Admin **sempre** é appendada depois da reconstrução da base descrita acima, portanto, sempre estará constando no XML final.

Adiciono a este comentário um documento em txt que descreve o algoritmo implementado no shell-script **pos_coleta_oai.sh**. Eventualmente outros **pos_coleta_*.sh**  devem ser revisados de forma a garantir o tratamento de daod sprovenientes de FI-ADMIN, semelhantemente ao dado por **pos_coleta_oai.sh**.

[Algoritmo+simplificado+de+pos_coleta_oai.txt](https://github.com/bireme/db-processing/files/11535982/Algoritmo%2Bsimplificado%2Bde%2Bpos_coleta_oai.txt)

**Comment by botturam** [comment]
proc. seguirá dando erro na porção ISIS-OAI, pois o nro de docs. é inferior a fev/2022. Aguardaremos a migração do LILDBI para FI-ADMIN.
