### ISSUE TITLE
migração no DATACENTER - problemas com IAHx-IDX01 e IAHx-IDX02

### ISSUE THREAD

**Issue by botturam** [bireme/db-processing#935]
indisponibilidade dos serviços SoLR em Tamboré.

**Comment by ChicoLopes** [comment]
@botturam foi composto o documento **_FrontEnd-IAHx.docx_** que tem a pretenção de explicar diversos aspectos operacionais e administrativos dos servidores front end de IAHx, detalhando em pormenores como colocar o serviço no ar após um power-up dou reset do servidor, sej aele iahx-idx01 ou iahx-idx02.

Resumo básico para disparo manual do serviço:
01- Logar com o usuário OPERACAO
02- executar em linha de comando o seguinte:

`srviahx.sh N start`
(N é o número da porta com o serviço, presentemente 3 para iahx-idx01 ou 6 para iahx-idx02)

É feito aqui o upload do documento MS-Word (docx).

[FrontEnd-IAHx.docx](https://github.com/bireme/db-processing/files/11557859/FrontEnd-IAHx.docx)

Para uma visão completa da configuração dos servidores iahx-idx0?, veja:
 #907 migração interface IAH de Basalto02 para IAH-IDX01

**Comment by botturam** [comment]
concluído.
