### ISSUE TITLE
Inclusão de campos  iAHx - Mês de entrada (em)

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#96]
Inclusão de campo para recuperação no iAHx, habilitando sintaxe para recuperar na caixa de busca livre e, se possível, como campo no formulário da pesquisa avançada.
Campo Mês de entrada (em) - disponível em Medline e Lilacs.

**Comment by pintoros** [comment]
Justificativa: Necessidade dos pesquisadores que trabalham com alguns tipos de estudo que necessitam atualização periódica no sistema,  como as RS, por exemplo.

**Comment by botturam** [comment]
A pesquisa por "data de entrada" e "data de atualização" já está implantada. 

Seguem alguns exemplos de como o dado está disponível para pesquisa:

Data de entrada:       <field name="entry_date">20190815</field> (entry_date:20190816)
Data de atualização: <field name="update_date">20190815</field> (update_date:201908)

É suficiente?

**Comment by pintoros** [comment]
Está perfeito!

Obrigada!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:b9f56e43-372c-4a3d-9776-3eb7777eb867]

________________________________
De: botturam <notifications@github.com>
Enviado: terça-feira, 20 de agosto de 2019 11:43
Para: bireme/db-processing <db-processing@noreply.github.com>
Cc: Pinto, Rosemeire (BIR) <pintoros@paho.org>; Author <author@noreply.github.com>
Assunto: Re: [bireme/db-processing] Inclusão de campos iAHx - Mês de entrada (em) (#96)


A pesquisa por "data de entrada" e "data de atualização" já está implantada.

Seguem alguns exemplos de como o dado está disponível para pesquisa:

Data de entrada: 20190815 (entry_date:20190816)
Data de atualização: 20190815 (update_date:201908)

É suficiente?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fdb-processing%2Fissues%2F96%3Femail_source%3Dnotifications%26email_token%3DAG7UW4HKCB2YSWZFVCWJYNLQFP7HLA5CNFSM4FUQ4EU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4WRCKY%23issuecomment-523047211&data=02%7C01%7Cpintoros%40paho.org%7C001aa3fe096641d0bfe408d7257cb40a%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637019089839006243&sdata=A9u7nAcLm%2FonLXBxeymop3EMf34K5TUaNlFeGT%2FkQzY%3D&reserved=0>, or mute the thread<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4B47BTNILYJ6TYM47DQFP7HLANCNFSM4FUQ4EUQ&data=02%7C01%7Cpintoros%40paho.org%7C001aa3fe096641d0bfe408d7257cb40a%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637019089839011233&sdata=vpUHBIOgKcFNRbqNp7ACgDQzlEye4gN4asQ8t7ygr3o%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by botturam** [comment]
concluído.
