### ISSUE TITLE
Inclusão de campos no iAHx - Campo Autor institucional (ai)

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#97]
Inclusão de campo para recuperação no iAHx, habilitando sintaxe para recuperar na caixa de busca livre e, se possível, como campo no formulário da pesquisa avançada.

Campo Autor institucional (ai) = disponível em Lilacs, verificar possibilidade de habilitar também em Medline. No Pubmed equivale ao campo Corporate Author [CN]

**Comment by botturam** [comment]
Corporate Author ou Collective Author já está disponível para pesquisa em MELINE na busca livre (prefixo "ai").

Exemplo:

ai:"University of Kansas Medical Center"

**Comment by botturam** [comment]
Efetuei a exclusão do campo "ai" hoje, dia 12/09/2018.

No próximo processamento do Portal Regional, segunda-feira, estará ajustado.
