### ISSUE TITLE
Inclusão de campos no iAHx - Campo Registro de Ensaio Clínico

### ISSUE THREAD

**Issue by pintoros** [bireme/db-processing#99]
Inclusão de campo para recuperação no iAHx, habilitando sintaxe para recuperar na caixa de busca livre e, se possível, como campo no formulário da pesquisa avançada.

Campo Registro de Ensaios Clínicos - Lilacs (ec). No Medline /Pubmed é o campo EC/RN Number [RN]

**Comment by botturam** [comment]
Foi criado um novo índice ("ec") para pesquisar os documentos cujo tipo de estudo é Ensaio Clínico. 

Formas de uso: ec:1 ou ec:"1"

Por enquanto. apenas o ano corrente do MEDLINE (2018) e as vindas do FI-Admin são pesquisáveis. É necessário refazer os demais anos de MEDLINE para que recupere todos os documentos.

**Comment by botturam** [comment]
disponível em produção.
